### ISSUE TITLE
Support LLAMA 3.1 in NeMo

### ISSUE THREAD

**Issue by zhouku92** [NVIDIA/NeMo#10048]
**Is your feature request related to a problem? Please describe.**

LLAMA3.1 introduces a new ROPE implementation, while NeMo hasn't supported it.
https://github.com/huggingface/transformers/blob/51ab25e2932da15511ced35bcbdfa92d25c4794c/src/transformers/modeling_rope_utils.py#L298

**Describe the solution you'd like**

Support the new ROPE implementation and LLAMA 3.1.

**Comment by ericharper** [comment]
This has been added here: https://github.com/NVIDIA/NeMo/pull/9815

Please re-open or create a new issue if needed.
