### ISSUE TITLE
Online_ASR_Microphone_Demo is not comparable with model on ngc

### ISSUE THREAD

**Issue by Serbernari** [NVIDIA/NeMo#1005]
In code there is link
`the checkpoints are available from NGC: https://ngc.nvidia.com/catalog/models/nvidia:multidataset_quartznet15x5`
But one can find only .nemo file or old version of yaml config, which is incomparable with current version of notebook

**Comment by okuchaiev** [comment]
@vsl9 can you please modify this notebook to use ASRModel like here https://github.com/NVIDIA/NeMo/blob/master/examples/asr/speech2text.py#L82 (e.g. just use "from_pretrained" to instantiate the model)
