### ISSUE TITLE
ASR models with transcription steering prompt (canary, parakeet)

### ISSUE THREAD

**Issue by kunibald413** [NVIDIA/NeMo#10247]
**Is your feature request related to a problem? Please describe.**

is there a way for the canary and parakeet models (https://huggingface.co/nvidia/canary-1b) to steer transcription like whisper in order to have correct name spellings for example or adapt a certain style?

goal is to have better, more accurate subtitles

**Describe the solution you'd like**

pass string to the inference methods for these models to have more accurate resulting transcriptions. for example to fix spelling of names or titles

**additional context**

see whisper prompting here https://cookbook.openai.com/examples/whisper_prompting_guide

**Comment by nithinraok** [comment]
Thanks for the request. We don't offer exact functionality now. However you could use [this script ](https://github.com/NVIDIA/NeMo/blob/main/scripts/asr_context_biasing/eval_greedy_decoding_with_context_biasing.py)for CTC or hybrid RNNT-CTC models to boost such words while transcribing.
