### ISSUE TITLE
`speech_to_text_aed_chunked_infer.py`  throws `TypeError: 'TranscriptionConfig' object is not iterable`

### ISSUE THREAD

**Issue by kunibald413** [NVIDIA/NeMo#10246]
**Describe the bug**

canary model chunked infer with `speech_to_text_aed_chunked_infer.py` throws this error:
`TypeError: 'TranscriptionConfig' object is not iterable`

**Steps/Code to reproduce bug**

run this `main` function: https://github.com/NVIDIA/NeMo/blob/7cc99e95fa753f46dffffc47a19e3c1fa375159c/examples/asr/asr_chunked_inference/aed/speech_to_text_aed_chunked_infer.py#L118 

throws at this line
https://github.com/NVIDIA/NeMo/blob/7cc99e95fa753f46dffffc47a19e3c1fa375159c/examples/asr/asr_chunked_inference/aed/speech_to_text_aed_chunked_infer.py#L122

**misc**
might be legacy code?

might be that it will also throw here: https://github.com/NVIDIA/NeMo/blob/7cc99e95fa753f46dffffc47a19e3c1fa375159c/examples/asr/asr_chunked_inference/rnnt/speech_to_text_buffered_infer_rnnt.py#L149

**Comment by nithinraok** [comment]
@stevehuang52 pls have a look at this.

**Comment by stevehuang52** [comment]
Thanks for pointing out the issue, it will be fixed in https://github.com/NVIDIA/NeMo/pull/10581
