### ISSUE TITLE
Converting HF model to Nemo gets an error

### ISSUE THREAD

**Issue by PurvangL** [NVIDIA/NeMo#10264]
**Describe the bug**
I am trying to convert the [OPT-350m](https://huggingface.co/facebook/opt-350m) hugging face model to Nemo format. How can I map the following keys?
```
- model.decoder.project_out.weight
- model.decoder.project_in.weight
```
for other weight names, I can successfully map to Nemo format.

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)] Docker
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install. nemo:24.03.01.framework
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version : Ubuntu 20.04
- PyTorch version : nemo:24.03.01.framework
- Python version : nemo:24.03.01.framework

**Additional context**

Example: GPU model : H100

**Comment by PurvangL** [comment]
Hi, Following up regarding issue. Please let me know if any more information is needed.

**Comment by qijiaxing** [comment]
According to this [HF implementation](https://github.com/huggingface/transformers/blob/v4.44.2/src/transformers/models/opt/modeling_opt.py):
* `project_out` should be the final output layer, so it should be mapped to `model.output_layer.weight`
* `project_in` seems to be a linear layer projecting from embedding dim down to hidden size. Not sure if NeMo supports it.

**Comment by PurvangL** [comment]
@qijiaxing 
isn't the 'lm_head.weight' key should be mapped to model.output_layer.weight?
