### ISSUE TITLE
be prepared when a user selects a file that isn't strictly mono and other file extensions as well

### ISSUE THREAD

**Issue by BBC-Esq** [NVIDIA/NeMo#10276]
In your ```transcribe_utils.py``` script you need to be prepared when audio files are in stereo or other channels as well.

You can use ```pydub``` but I prefer to use ```soundfile```.  Either way, you need to be able to handle a wide variety of file formats and channels and gracefully convert them - even temporarily in a temp file - so that the program doesn't stop working altogether.

**Comment by nithinraok** [comment]
You can choose the channel with https://github.com/NVIDIA/NeMo/blob/c9c4bee40f839990c3382694b618ac117e601f68/examples/asr/transcribe_speech.py#L124 

regarding formats: we currently support: `wav, flac, mp3`
