### ISSUE TITLE
stop using ModelFilter and DatasetFilter from huggingface_hub

### ISSUE THREAD

**Issue by BBC-Esq** [NVIDIA/NeMo#10272]
Your usage of ModelFilter and possibly "DatasetFilter" from the ```huggingface_hub``` library is out of date.  Apparently those were removed in this here:

https://github.com/huggingface/huggingface_hub/commit/bb38f9422cb88ba02694c87fb5979cc48ecef8a0#diff-1b045ed2e860a78218b3501b6b8df1f5609c493c1e2fa16769486fb020f7c164

I noticed this when trying to implement your transcription script that you say on the huggingface repository that I can use.

You're welcome.

**Comment by titu1994** [comment]
It's been removed already from HF utils in NeMo.
