### ISSUE TITLE
Quartznet inference not deterministic

### ISSUE THREAD

**Issue by LordOfLuck** [NVIDIA/NeMo#1030]
Hi, I am running quartznet inference with the inference script from the docs and for a single recording, I am getting slightly different result every time. I noticed because the WER is slightly different on every run. Why is that and how to  make the run deterministic?

**Comment by okuchaiev** [comment]
In pre-processor params (https://github.com/NVIDIA/NeMo/blob/master/examples/asr/configs/quartznet15x5.yaml) there is a non-zero "dither" which introduces some randomness into the signal.

**Comment by LordOfLuck** [comment]
ok thanks :)
