### ISSUE TITLE
Using own pre-trained model for fine tuning - How to handle file extension .pt.nemo

### ISSUE THREAD

**Issue by piaschwarz** [NVIDIA/NeMo#1031]
I have a pre-trained model that emitted the following checkpoints:

- ENCODER: QuartzNet-STEP-255500.pt.nemo
- DECODER: JasperDecoderForCTC-STEP-255500.pt

I want to fine-tune this model further but I don't know how to handle the file extension .pt.nemo
The documentation states to restore from .pt-files. What is a .pt.nemo-file and how can I convert it to a regular .pt-file?

**Comment by Ashbajawed** [comment]
@piaschwarz  did you find any thing?
