### ISSUE TITLE
Continual training error: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbqgpune1/model_weights/model.decoder.layers.self_attention.linear_proj._extra_state/shard_0_16.pt'

### ISSUE THREAD

**Issue by GMALP** [NVIDIA/NeMo#10354]
image: nemo 2405 
Continual training model: llama3-8b.nemo

if mcore_gpt set True， 

![Image](https://github.com/user-attachments/assets/2ad02abd-c44a-45e8-a02f-303d596fd997)

why  this files are need, how to find this tmp files?

**Comment by wittysam** [comment]
Can you please show how you solve this problem, thx! I'm encountering this same problem.

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp6d5snvot/model_weights/model.decoder.layers.self_attention.core_attention._extra_state/shard_0_32.pt'

**Comment by SrinivasaGogul** [comment]
@wittysam hello have you solved the problem im facing the same issue

**Comment by wittysam** [comment]
@SrinivasaGogul No, the problem remains with NeMo version 24.09. But I switched to the older version of 24.07, which works out the problem.

**Comment by SrinivasaGogul** [comment]
@wittysam yeah, I have also switched to older version it worked. Thanks for the reply.
