### ISSUE TITLE
Cosine Similarity to Probability

### ISSUE THREAD

**Issue by gor2000** [NVIDIA/NeMo#10431]
Hi I'm trying to understand in this model how should I convert in some way the cosine Similarity to a probability.

I'm working for my company in a project where we need to detect if 2 audios have the same speaker or not. Basically, trying to detect if an audio has been cloned or it's original. 

The client has required the output of the application that detects audios to be a percentage. That is, 100% should be max similarity and 0% it's not the same speaker at all. 

My question is: Is it possible to do that?. Does it make sense? Because what I understant is that cosine similarity = 0 does not mean 50% right?

I would really appreciate any help here as I have not found anything on the internet.

Thank you in advance!!

**Comment by nithinraok** [comment]
Depends on optimal similarity for the model. 

You could first convert all similarity scores to postive value and within range of [0,1] by (1+cs)/2 and observe the values for a know trial set. 

Based on my analysis for titanet, optimal value for same speaker was found to be 0.7 (which you could consider as 50% case).
