### ISSUE TITLE
Argument error when running speech2text.py

### ISSUE THREAD

**Issue by caohongnga** [NVIDIA/NeMo#1050]
Hello,
When I run the speech2text.py file, I am getting the following error:

 File callbacks.py, line 493, in __restore_from
    mod.restore_from(checkpoint, state["local_rank"])
TypeError: restore_from() takes 2 positional arguments but 3 were given

**Comment by okuchaiev** [comment]
can you please provide more information, like what command you are running, which pytorch and nemo version, how many GPUs you are using

**Comment by caohongnga** [comment]
I already fixed. Thank you
