### ISSUE TITLE
RuntimeError: Internal: could not parse ModelProto from /tmp/tmpnf2ficir/tokenizer.decoder.32000.BPE.model

### ISSUE THREAD

**Issue by Yiran-ASU** [NVIDIA/NeMo#10514]
Hello, I am running code in the NeMo tutorial, [Sample Conversational AI application](https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/AudioTranslationSample.ipynb#scrollTo=RYGnI-EZp_nK).

I pulled a nvcr.io/nvidia/nemo:24.05 docker image, and run the tutorial code in a container. But when I try to load the pretrained MTEncDecModel (4th code cell of the tutorial, 5rd line, `nmt_model = nemo_nlp.models.MTEncDecModel.from_pretrained(model_name='nmt_zh_en_transformer6x6').cuda()`), I got the following error: 
`RuntimeError: Internal: could not parse ModelProto from /tmp/tmpnf2ficir/tokenizer.decoder.32000.BPE.model`

I reinstalled nemo_toolkit using `!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$r2.0.0rc0#egg=nemo_toolkit[all]
` inside the container, to try to solve this problem by align with the branch version, but it did not work. I confirmed the nemo version is `2.0.0rc0` by using `import nemo` and `nemo.__version__`.

I also find this error is probably due to incomplete model structure? Or do I need to change a version of nemo? Could you give me some possible solutions?

Thanks in advance!

**Comment by xinyou-egis** [comment]
Hi, i have face same issue. 
Any solution?
