### ISSUE TITLE
Unable to connect to network no Internet connection

### ISSUE THREAD

**Issue by Savage0725** [NVIDIA/NeMo#10583]
**Describe the bug**

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: Docker
 - Method of install: Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Additional context**

Example: GPU model

**Comment by elliottnv** [comment]
Please fill out the template and reopen. Thank you!
