### ISSUE TITLE
Sentence classification needs a more abstract DataDesc class

### ISSUE THREAD

**Issue by MuyangDu** [NVIDIA/NeMo#106]
Currently, the sentence classification task uses SentenceClassificationDataDesc to prepare training and testing data. If the user wants to use their own dataset. They need to add a process_xxx function and set num_class in SentenceClassificationDataDesc. That's not convenient because users have to change the source code of NeMo. Users should be able to define their own process_xxx function in training script and pass the function & num_class to SentenceClassificationDataDesc as parameters. SentenceClassificationDataDesc should use the user-defined process function to process data.

**Comment by MuyangDu** [comment]
Also, NER needs a more abstract 'dataset_type'. Currently, the dataset_type is 'BertCornellNERDataset'. This is actually the dataset in BIO format. BertCornellNERDataset should be able to process any data in BIO format. So should we consider to change the name of 'BertCornellNERDataset' to something more generic like 'BIONERDataset'? Then users should be able to prepare their data in BIO format and use the script directly.

**Comment by ekmb** [comment]
BertCornellNERDataset is 'faking' BIO format now, I'm working on adding a more general dataset for a tokenclassification problems.

**Comment by chiphuyen** [comment]
> Currently, the sentence classification task uses SentenceClassificationDataDesc to prepare training and testing data. If the user wants to use their own dataset. They need to add a process_xxx function and set num_class in SentenceClassificationDataDesc. That's not convenient because users have to change the source code of NeMo. Users should be able to define their own process_xxx function in training script and pass the function & num_class to SentenceClassificationDataDesc as parameters. SentenceClassificationDataDesc should use the user-defined process function to process data.

This is an excellent suggestion. Do you feel down to work on that or would you like us to?

**Comment by MuyangDu** [comment]
> > Currently, the sentence classification task uses SentenceClassificationDataDesc to prepare training and testing data. If the user wants to use their own dataset. They need to add a process_xxx function and set num_class in SentenceClassificationDataDesc. That's not convenient because users have to change the source code of NeMo. Users should be able to define their own process_xxx function in training script and pass the function & num_class to SentenceClassificationDataDesc as parameters. SentenceClassificationDataDesc should use the user-defined process function to process data.
> 
> This is an excellent suggestion. Do you feel down to work on that or would you like us to?

Okay, I will work on this.

**Comment by MuyangDu** [comment]
> BertCornellNERDataset is 'faking' BIO format now, I'm working on adding a more general dataset for a tokenclassification problems.

Okay, thanks.

**Comment by MuyangDu** [comment]
@chiphuyen Hi, I have with withdrew the pr because besides the sentenceclassificationdesc, other datadesc should also let users define their own processor. That actually requires a union style for input and output for both datadesc and processor. I think it's better you guys do this. Thanks
