### ISSUE TITLE
[FEA] Make SequenceClassifier and TokenClassifier signature the same

### ISSUE THREAD

**Issue by miguelusque** [NVIDIA/NeMo#1060]
Hi!

When inspecting `SequenceClassifies `and `TokenClassifier` signatures, they look quite similar, but not the same.

```
import inspect

print(inspect.signature(nemo_nlp.nm.trainables.SequenceClassifier))
print(inspect.signature(nemo_nlp.nm.trainables.TokenClassifier))
```

Output:
```
(hidden_size, num_classes, num_layers=2, activation='relu', log_softmax=True, dropout=0.0, use_transformer_pretrained=True)
(hidden_size, num_classes, name=None, num_layers=2, activation='relu', log_softmax=True, dropout=0.0, use_transformer_pretrained=True)
```

Both classes would have the same signatures if we may add `name` to `SequenceClassifier`.

I think it would be great to have both classes with the same signature, considering that adding a name to `SequenceClassifier` would be useful.

Hope it helps!

Regards,
Miguel

**Comment by okuchaiev** [comment]
We are working on a new version of NeMo which has a lot of changes compared to 0.11 
Can you please have a look at https://github.com/NVIDIA/NeMo/tree/candidate branch instead
