### ISSUE TITLE
[FEA] Add an issues GitHub template similar to rapids.ai/cudf

### ISSUE THREAD

**Issue by miguelusque** [NVIDIA/NeMo#1061]
Hi!

It would be great to have an issues template similar to the one used at rapids.ai.

It would make easier to classify bugs, feature requests, documentation related issues ndquestions.

The template I am referring to can be found [here](https://github.com/rapidsai/cudf/issues/new/choose).
 
Hope it helps!

Regards,
Miguel

**Comment by okuchaiev** [comment]
done
