### ISSUE TITLE
** How to EXPORT my model after finetuning? **

### ISSUE THREAD

**Issue by soheiltehranipour** [NVIDIA/NeMo#1063]
Hello,

I want to deploy my model But I couldn't get help from "**deployment_export**" function from documentation.
I would appreciate if anyone can help me with that.

P.S: I did fine-tuning and it's ready with the following files:
* JasperEncoder.pt
* JasperDecoderForCTC
* quartznet15x5.yaml

**Comment by okuchaiev** [comment]
have you tried https://github.com/NVIDIA/NeMo/blob/master/scripts/export_jasper_to_onnx.py ?

**Comment by EmreOzkose** [comment]
Is there any example of Bert version (any NLP example)? I could not find.
