### ISSUE TITLE
Segmentation Fault using custom Language Model

### ISSUE THREAD

**Issue by cdettmering-st** [NVIDIA/NeMo#1064]
When using the asr_service (https://github.com/NVIDIA/NeMo/tree/master/examples/applications/asr_service) example Nemo will crash with a Segmentation Fault. Below is a log from Nemo where this occurs. Moreover, this is on the official Nemo docker v0.11 in CPU mode.

The encoder / decoder being used is here: https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5

I've attached the LM and __init__.py files being used within the example project. I have reproduced this issue within the example service however the problem was first detected within an external project.

[NeMo I 2020-08-25 17:02:30 collections:158] Dataset loaded with 1 files totalling 5.00 hours
[NeMo I 2020-08-25 17:02:30 collections:159] 0 files were filtered totalling 0.00 hours
[NeMo I 2020-08-25 17:02:30 routes:49] Running with beam search
[NeMo I 2020-08-25 17:02:30 actions:695] Evaluating batch 0 out of 1
Segmentation fault

[test.zip](https://github.com/NVIDIA/NeMo/files/5125549/test.zip)

**Comment by okuchaiev** [comment]
can you please provide more details on your system? E.g. ubuntu version, cuda version, pytorch version, etc.

**Comment by cdettmering-st** [comment]
Yes,

This was using the nvidia nemo docker container v0.11 here https://ngc.nvidia.com/catalog/containers/nvidia:nemo so the OS, pytorch and all that is whatever comes with that image. Note I was using NEMO in CPU mode not GPU. Also I was running the docker container on a windows 10 host. Let me know if you need moreinfo.

Chad Dettmering
Software Engineer III
SoarTech

**Comment by okuchaiev** [comment]
Unfortunately, we tested this app only on Ubuntu 16/18. I think "Also I was running the docker container on a windows 10 host." - I think this could be the source of the problem. The seg fault error above is from beam search C++ implementation and it matters how it was built from source

**Comment by cdettmering-st** [comment]
The decoders were built inside the docker container that is running Ubuntu using the install_decoders.sh script from the official docker image.

**Comment by okuchaiev** [comment]
closing as this is related to the old version
