### ISSUE TITLE
Unable to decode using canary 1b model

### ISSUE THREAD

**Issue by uni-saurabh-vyas** [NVIDIA/NeMo#10680]
**Describe the bug**

I am using nemo inside docker environment, with single GPU, unable to get the ASR ouput using canary 1b model

```
Error executing job with overrides: ['pretrained_name=nvidia/canary-1b', 'audio_dir=/opt/workspace/es_test', 'output_filename=canary_output.txt', 'clean_groundtruth_text=True', 'langid=es', 'batch_size=1', 'compute_timestamps=False', 'compute_langs=False', 'cuda=0', 'amp=True', 'append_pred=False', 'pred_name_postfix=canary']
Traceback (most recent call last):
  File "/opt/asr_ensemble/repo/nemo/examples/asr/transcribe_speech.py", line 290, in main
    asr_model.change_decoding_strategy(cfg.ctc_decoding)
  File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/models/aed_multitask_models.py", line 203, in change_decoding_strategy
    self.decoding = MultiTaskDecoding(
  File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/parts/submodules/multitask_decoding.py", line 377, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/parts/submodules/multitask_decoding.py", line 124, in __init__
    raise NotImplementedError("Greedy decoding is not implemented yet.")
NotImplementedError: Greedy decoding is not implemented yet.

```

**Steps/Code to reproduce bug**

    python3 nemo/examples/asr/transcribe_speech.py \
    pretrained_name="nvidia/canary-1b" \
    audio_dir="/opt/workspace/es_test" \
    output_filename="canary_output.txt" \
    clean_groundtruth_text=True \
    langid='es' \
    batch_size=1 \
    compute_timestamps=False \
    compute_langs=False \
    cuda=0 \
    amp=True \
    append_pred=False \
    pred_name_postfix="canary"

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version Ubuntu 20
- PyTorch version
- Python version 3.10

**Additional context**

Example: GPU model

**Comment by pzelasko** [comment]
Which NeMo version is this? Greedy decoding for Canary should work if you install the latest 2.0 pre-release, or the latest `main` branch.
