### ISSUE TITLE
`IPython` should be included in the requirements

### ISSUE THREAD

**Issue by MahmoudAshraf97** [NVIDIA/NeMo#10772]
**Describe the bug**

`IPython` is not included in the requirements but it is used in an non-optional manner

**Steps/Code to reproduce bug**

`from nemo.collections.asr.parts.utils.vad_utils import load_tensor_from_file`
On a new environment that comes without `IPython`

**Expected behavior**

`IPython` should be included in the requirements or imported inside the functions that need it (`plot` and `plot_sample_from_rttm`)

This was already discussed in https://github.com/NVIDIA/NeMo/pull/9890#discussion_r1704593976

**Comment by MahmoudAshraf97** [comment]
.

**Comment by svandiekendialpad** [comment]
👍 ➕
