### ISSUE TITLE
Correction in the 1_ASR_tutorial_using_NeMo.ipynb

### ISSUE THREAD

**Issue by mehulsuresh** [NVIDIA/NeMo#108]
noticed a tiny error in the example jupyter notebook

`metadata = {
                    "audio_filename": audio_path,
                    "duration": duration,
                    "text": transcript
                }`
should be

`metadata = {
                    "audio_filepath": audio_path,
                    "duration": duration,
                    "text": transcript
                }`

otherwise it causes a key error

**Comment by redoctopus** [comment]
Thanks for catching this! Both `audio_filepath` and `audio_filename` should be supported in the manifest, and it looks like this was broken in a recent change. Fix to be reviewed in PR https://github.com/NVIDIA/NeMo/pull/110.

**Comment by redoctopus** [comment]
PR merged.
