### ISSUE TITLE
Conversion script of phi3 from HF to Nemo

### ISSUE THREAD

**Issue by zhouxie000** [NVIDIA/NeMo#10825]
**Is your feature request related to a problem? Please describe.**
Contionual pretraining of Phi-3-mini-128k-instruct using nemo.

Hi, we are looking to run continual pretraining based on Phi-3-mini-128k-instruct in Nemo. Currently, there's no conversion script available under convert_mistral_7b_hf_to_nemo.py. Could you please add the support?

Phi-3-mini-128k-instruct conversion script from HF to Nemo.

**Describe alternatives you've considered**
I'm implementing a custom script based on https://github.com/NVIDIA/NeMo/blob/main/scripts/checkpoint_converters/convert_llama_hf_to_nemo_save_dict.py with some additional processing on the qkv_proj tensor from Phi3.

**Comment by LopezGG** [comment]
+1 to this. I am looking for a conversion script or pointers on how to get started with this
