### ISSUE TITLE
[Question] Converting a Megatron-LM ckpt to Nemo

### ISSUE THREAD

**Issue by abgoswam** [NVIDIA/NeMo#10831]
Following the [GPT Pretraining](https://github.com/NVIDIA/Megatron-LM/tree/main?tab=readme-ov-file#gpt-pretraining) section in the  `Megatron-LM` repo,  we are able to successfully train a model using  `Megatron-LM` 

I saw pointers on how to convert from HF to `nemo`.  For example, this conversion script  [ convert_llama_hf_to_nemo.py](https://github.com/NVIDIA/NeMo/blob/stable/scripts/checkpoint_converters/convert_llama_hf_to_nemo.py)

However I did not see any examples of converting a ckpt saved using  the  `Megatron-LM` to `nemo` format .  Are there any examples for this?

p.s.  I am thinking of doing this conversion to `nemo`, so I can use tools like `Nemo-Aligner` for post-training

**Comment by aimarz** [comment]
There is a script for that: [`<NeMo_ROOT_FOLDER>/examples/nlp/language_modeling/megatron_lm_ckpt_to_nemo.py`](https://github.com/NVIDIA/NeMo/blob/b4f308600a8a35eecf33f5cfdecc9f5f648f2863/examples/nlp/language_modeling/megatron_lm_ckpt_to_nemo.py#L4)

Look up this guide: https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/checkpoints/convert_mlm.html 

Also this issue I opened might be relevant to you: https://github.com/NVIDIA/NeMo/issues/10480

**Comment by abgoswam** [comment]
thanks @aimarz . let me try it out on the Megatron-LM ckpts  we pre-trained
