### ISSUE TITLE
NeMO dependency issues on HuggingFace Hub (for ASR models)

### ISSUE THREAD

**Issue by bhavnicksm** [NVIDIA/NeMo#10940]
**Describe the bug**

NeMo is not loading a ASR model I wanted to run because of internal dependency issues on HuggingFace Hub.

**Steps/Code to reproduce bug**

Colab Link: [colab link](https://colab.research.google.com/drive/1JqMW-JkyHJ61UOFO9eQhoHkQx6I3cH05?usp=sharing)

```python
!pip install nemo_toolkit['all']

import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.ASRModel.from_pretrained(model_name="nvidia/parakeet-tdt_ctc-110m")
```

**Expected behavior**

It should load up the model. 

**Environment overview (please complete the following information)**

Check colab notebook

**Environment details**

Check colab notebook 

**Additional context**

Check colab notebook

**Comment by MahmoudAshraf97** [comment]
this was solved in `r2.0.0rc1`
