### ISSUE TITLE
Megatron Multilingual En Any 500M

### ISSUE THREAD

**Issue by rogerwelo** [NVIDIA/NeMo#10976]
Hi!

I'm using the [Megatron Multilingual En Any 500M model](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/megatronnmt_en_any_500m) with [this example script](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/machine_translation/nmt_transformer_infer_megatron.py).

I got the script to work in a [Nemo Docker container](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/machine_translation/nmt_transformer_infer_megatron.py) in the sense that the script runs without error. However, the output file only contains empty lines indicating that the translation doesn't work properly.
The model seems to be loaded fine and there is no hint in the logs.

Any idea what is going wrong? Is this model still supported?

Thanks!

**Comment by shuoyangd** [comment]
Hi @rogerwelo . Can you specify which Nemo container you are using?

I've been using this one (`nvcr.io/nvidia/nemo:23.08`) for inference with this model. If you are using a different container, can you try it out?

Shuoyang
