### ISSUE TITLE
issue with unittest

### ISSUE THREAD

**Issue by swarajbadhei** [NVIDIA/NeMo#1098]
following error arised during running python -m unittest tests/.*py

 (nemo_3.6_dev) bash-4.2$ python -m unittest tests/*.py
EE
======================================================================
ERROR: conftest (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: conftest
Traceback (most recent call last):
  File "/home/blraml/anaconda3/envs/nemo_3.6_dev/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'tests.conftest'

======================================================================
ERROR: test_data_dir (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_data_dir
Traceback (most recent call last):
  File "/home/blraml/anaconda3/envs/nemo_3.6_dev/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'tests.test_data_dir'

----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)

as per directory structure, everything seems to be in order. 

- PyTorch version: 1.6.0
- Python version : 3.6

**Comment by okuchaiev** [comment]
are you running this on a machine with internet connection? (It gets small tests data directly from GitHub)

**Comment by swarajbadhei** [comment]
Yes, I understand that sir. Both the required files are also in the correct directory position. Unable to find out what to do.

**Comment by okuchaiev** [comment]
can you please give more details:
- which command did you use to install?
- does this happen inside NVIDIA's container? - I'd recommend you use 20.07-py3 container

**Comment by swarajbadhei** [comment]
Actually I cloned the master branch. As I am working on a company remote server, I do not have admin rights to use containers. Simply used the ./reinstall command and tried to fulfill the libs using pip. Everything seemed okay then this arised. 
>> python -m unittest tests/*.py gave this issue.

**Comment by okuchaiev** [comment]
can you please switch to the "main" branch as it contains the latest code and is our "default" branch (master will be deleted soon). Please re-open if you see this issue on main branch
