### ISSUE TITLE
Possibility to instantly log tensorboard to Neptune using neptune-tensorboard

### ISSUE THREAD

**Issue by FerchichiNourchene** [NVIDIA/NeMo#1109]
Is there a possibility to instantly log major metrics (Evaluation_LOSS and Evaluation_WER) to Neptune using neptune-tensorboard? (https://docs.neptune.ai/integrations/tensorboard.html)

What I did is not working for me as it is raising `ValueError: A callback was received that was not a child of ActionCallback`

I have tried defining a new callback for tensorboard:
```
def tensorboard_callback(experimentation_dir):
   return tf.keras.callbacks.TensorBoard(log_dir=experimentation_dir)
```

Then calling it as a callback in the train() function with :
```
loggercallback = nemo.core.SimpleLossLoggerCallback(...)
savercallback = nemo.core.CheckpointCallback(...)
evalcallback = nemo.core.EvaluatorCallback(...)
tensorbordcallback = tensorboard_callback(experimentation_dir)
# --- Start Training! --- #
neural_factory.train(
       tensors_to_optimize=[self.loss],
       callbacks=[
           loggercallback, 
           savercallback, 
           evalcallback,
           tensorbordcallback,
           ],
        ) 
```

Then following this example https://docs.neptune.ai/integrations/tensorboard/tensorboard_integrate.html to log the tensorboard to Neptune
```
import neptune
import neptune_tensorboard as neptune_tb
neptune.init(neptune_project_name)
neptune_tb.integrate_with_tensorflow()   
with neptune.create_experiment(
        name=neptune_experiment_name, params=parameters, tags=tag
        ):
        model.train()
```
Any idea on how this could be done?

**Comment by okuchaiev** [comment]
Hi @FerchichiNourchene, 

Based on your description - you are using older version of NeMo. We are currently finalizing a major re-design which is currently available in the main branch. 
There are a lot of major changes - NeuralFactory is gone and we use Pytorch Lightning now. I would really recommend you switch to the main branch now. Sorry for inconveniences. 

In our experiment logger we currently support logging using WANDB: https://github.com/NVIDIA/NeMo/blob/661d4321bc5f3db601b6fa9faaf0a3d5dacaaeee/nemo/utils/exp_manager.py#L120 
(which relies on Lightning-Wandb integration).

PTL supports Neptune, so I guess integrating with it should be very similar. 
(Feel free to send PR to the main branch if you get it working).

**Comment by FerchichiNourchene** [comment]
Hi @okuchaiev,

Thank you for your explanation, I really appreciate it! Your are right, my bad :( I am using `nemo_toolkit==0.10.1` and I should definitely move to the  `nemo_toolkit==0.11.0`

But just to make sure: Would moving to version 0.11.0 help me integrate Neptune using Pytorch Lightning, or should I clone the current repo and work with the actual main branch?

Thank you again

**Comment by okuchaiev** [comment]
"definitely move to the nemo_toolkit==0.11.0"   - No, please just install from GitHub's main branch. 0.11.0/0.11.1 - is a last "old" NeMo release
