### ISSUE TITLE
Error in NER notebook

### ISSUE THREAD

**Issue by hulkgeek** [NVIDIA/NeMo#1115]
I ran Token_Classification_Named_Entity_Recognition_tutorial.ipynb on Colab and got the following error for this line?

pretrained_ner_model = nemo_nlp.models.TokenClassificationModel.from_pretrained(model_name="NERModel")

RuntimeError: Error(s) in loading state_dict for TokenClassificationModel:
Missing key(s) in state_dict: "bert_model.embeddings.position_ids".

**Comment by ekmb** [comment]
@hulkgeek Please try with `! pip install transformers==3.0.2`, a new NER model compatible with the latest transformers version will be added soon.
