### ISSUE TITLE
How to use wandb sweep for hyperparameter search when finetuning with llama2

### ISSUE THREAD

**Issue by PurvangL** [NVIDIA/NeMo#11151]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Provide a code snippet on how new APIs/changes would be used by others.

```
I would like to do hyperparameter search with wandb sweep. Right now I can't find an option to add sweep config in yaml file. How can I enable wandb sweep and fine-tune llama2 model?

https://wandb.ai/aarora/Nvidia%20NeMO/reports/Train-Optimize-Analyze-Visualize-and-Deploy-Models-for-Automatic-Speech-Recognition-with-NVIDIA-s-NeMo--VmlldzoxNzI0ODEw
```

**Describe alternatives you've considered**

**Additional context**

**Comment by PurvangL** [comment]
@okuchaiev following up regarding issue. please let me know if any other information needed.

**Comment by weiran-work** [comment]
@PurvangL Did you ever figure out if the wandb sweep would work with nemo? Thanks!
