### ISSUE TITLE
Initialize a Parakeet Cache-Aware Streaming model's encoder from an offline model.

### ISSUE THREAD

**Issue by gabitza-tech** [NVIDIA/NeMo#11250]
Hello,

Thank you for all your amazing work!

At the moment, nemo only support the fastconformer 120M streaming model, however I would like to also try a bigger model. I was wondering if it is possible to modify the architecture to match de 600M parakeet model and initialize the encoder weights from the offline parakeet model? Otherwise, training a bare 600M streaming model without any SSL pretraining would probably be worse and slower to train than the 120M model.

Best regards,
Gabi

**Comment by sandergs92** [comment]
See the following answer: [https://github.com/NVIDIA/NeMo/issues/9615#issuecomment-2264136385](url)

**Comment by gabitza-tech** [comment]
Thanks!
