### ISSUE TITLE
Fail to convert Llama3 Nemo 2.0 checkpoint to HF

### ISSUE THREAD

**Issue by EthanLI24** [NVIDIA/NeMo#11256]
**Describe the bug**

I use Nemo 2.0 to train my model and get Nemo 2.0 checkpoint like this with .distcp files:
model_name
├── context
│   ├── model_config.yaml
│   ├── io.json
│   └── tokenizer
├── weights
│   ├── distributed checkpointing directories/files in torch_dist format
│   ├── metadata.json
│   └── common.pt

but filed to use NeMo/scripts/checkpoint_converters/convert_llama_nemo_to_hf.py to export it to a HF file

**Expected behavior**

get HF files by Nemo2.0 checkpoint

**Comment by EthanLI24** [comment]
Is there a way we can now save non .distcp files or huggingface .bin files directly after training?
If not, how to convert nemo2.0 checkpoint to the community common format?

**Comment by hemildesai** [comment]
Hi, the scripts/checkpoint_converters/convert_llama_nemo_to_hf.py script is only for NeMo 1.0 checkpoints. To export 2.0 checkpoints, you can use a custom script like

```python
from pathlib import Path

from nemo.collections.llm import export_ckpt

if __name__ == "__main__":
    export_ckpt(
        path=Path("/workspace/input_ckpt"),
        target="hf",
        output_path=Path("/workspace/output_ckpt.hf"),
    )
```

**Comment by EthanLI24** [comment]
> Hi, the scripts/checkpoint_converters/convert_llama_nemo_to_hf.py script is only for NeMo 1.0 checkpoints. To export 2.0 checkpoints, you can use a custom script like
> 
> from pathlib import Path
> 
> from nemo.collections.llm import export_ckpt
> 
> if __name__ == "__main__":
>     export_ckpt(
>         path=Path("/workspace/input_ckpt"),
>         target="hf",
>         output_path=Path("/workspace/output_ckpt.hf"),
>     )



Here are my fold arch:
nemo2_llama3
├── context
│ ├── model.yaml
│ ├── io.json
│ └── nemo_tokenizer
├── weights
│ ├── __0_0.distcp
│ ├── __0_1.distcp
│ ├── metadata.json
│ └── common.pt

and I follow your instruction to use
if __name__ == "__main__":
    export_ckpt(
        path=Path("./nemo2_llama3"),
        target="hf",
        output_path=Path("./nemo2exporthf"),
    )

but i get failed again, could you help me with this?

**Comment by Zhihan1996** [comment]
Hello, could you let me know if you solved this issue? I have the same problem with a Mistral model.

**Comment by akoumpa** [comment]
Hi @Zhihan1996 , thanks for reporting this. Will have someone push a fix soon. Thank you for your patience.

**Comment by Zhihan1996** [comment]
Thank you @akoumpa. I look forward to it. Please kindly let me know when the fix is pushed.

**Comment by akoumpa** [comment]
Hi, 

I'm not able to reproduce, so I would your help. 


Here's the steps and commands/code I used:

1. download the mistral checkpoint
```akoumparouli@dev:hf_ckpt/$ huggingface-cli download --local-dir mistralai/Mistral-7B-v0.3 --cache-dir mistralai/Mistral-7B-v0.3```

2. import to NeMo
```
from nemo.collections import llm

if __name__ == "__main__":

    config = llm.MistralConfig7B()
    model = llm.MistralModel(config)
    ckpt_path = model.import_ckpt('hf_ckpt/mistralai/Mistral-7B-v0.3')
```

3. export to HF
```
from pathlib import Path

from nemo.collections.llm import export_ckpt

if __name__ == "__main__":
    export_ckpt(
        path=Path("/root/.cache/nemo/models/Mistral-7B-v0.3"),
        target="hf",
        output_path=Path("/workspace/output_ckpt.hf"),
    )
```

So I wonder in your case how the checkpoint is generated?

I realized just now, that mistral while it uses the correct dtype during export/import (e.g., [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/llm/gpt/model/mistral.py#L195-L196)), it does not have a default dtype in the config. So unless specified by the user, there's a chance it might not use bfloat16 (if initialized from a config).

I think there's two work-arounds here:
1. cast `_target` to bfloat16 before reaching the assert in the export statement
2. comment the assert in the export statement.

**Comment by EthanLI24** [comment]
@Zhihan1996 Hi Zhihan,
That's beacuse there have some mismatch between your nemo and hf target model, and it will do type exterct in the mixin.py.
There have two solutions:
1. Manually convert your nemo or hf to same format like bf16 or fp32
2. Modify your target hf model config.json to same with your nemo config of the tensor type

or maybe you can try modify your io.json too. And I think it always fail to reload the format type in HFExporter class but I don't know why,,,(I try to modify the code here but it does not work)

**Comment by Zhihan1996** [comment]
Thank you @EthanLI24 and @akoumpa, it is indeed a type mismatch problem. I am able to solve it by commenting the line that asserts the same type (`assert target_orig_dtypes == extract_dtypes(_target.named_parameters())`) in the export statement (`NeMo/nemo/lightning/io/state.py`). 

My checkpoint was automatically saved by the trainer after distributed training with `bf16`. And the `bf16` argument is true in my `model.yaml`. So I suspect there are some tiny issues with the mistral module when handling the `dtype`.

**Comment by aflah02** [comment]
Hi @EthanLI24 
Did you notice issues around quality of exported Llama model? In my case the model exports but keeps outputting the same token while if I run inference via NeMo it seems to work well

**Comment by Zhihan1996** [comment]
My exported Mistral model works well. It has almost the same clm loss on validation data as training.

**Comment by aflah02** [comment]
Thanks @Zhihan1996 
Just to confirm, you used `from nemo.collections.llm import export_ckpt` for export right?

**Comment by Zhihan1996** [comment]
Yes
