### ISSUE TITLE
[Question] How to use huggingface language model for NeMo ASR

### ISSUE THREAD

**Issue by khursani8** [NVIDIA/NeMo#1126]
**Describe your question**

Previously we can use asr_postprocessor to improve asr model with HF model, for new NeMo, how can I achieve this?
Source:https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/v0.10.1/nlp/asr-improvement.html

**Environment overview (please complete the following information)**

 - Environment location:Collab
 - Method of NeMo install: pip3 install git+https://github.com/NVIDIA/NeMo.git#egg=nemo_toolkit[all]

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 18.04
- PyTorch version : 1.6.0+cu101
- Python version: 3.6.9

**Comment by okuchaiev** [comment]
this feature hasn't been ported to new NeMo yet, but we are working on it.

**Comment by khursani8** [comment]
Hi @okuchaiev,
I wondering if this feature will be develop in near future?
