### ISSUE TITLE
TestMegatron.test_get_pretrained_bert_345m_uncased_model fails inside new conda environment.

### ISSUE THREAD

**Issue by okuchaiev** [NVIDIA/NeMo#1136]
**Describe the bug**

TestMegatron.test_get_pretrained_bert_345m_uncased_model unit test fails inside fresh Anaconda environment.

**Steps/Code to reproduce bug**

On machine with GPU and CUDA installed: 

Step 1. Create new anaconda environment: ```conda create -n testenv python=3.7```.
Step 2. ```conda activate testenv```
Step 3. (from NeMo Git root, main branch) ```./reinstall.sh```
Step 4. (Run all unit tests) ```pytest```

All tests pass except one - TestMegatron.test_get_pretrained_bert_345m_uncased_model

=============================================================================================================================== short test summary info ================================================================================================================================
FAILED tests/collections/nlp/test_megatron.py::TestMegatron::test_get_pretrained_bert_345m_uncased_model - torch.jit.TracingCheckError: Tracing failed sanity checks!
=============================================================================================================== 1 failed, 101 passed, 101 warnings in 113.36s (0:01:53) ================================================================================================================

**Expected behavior**

All applicable unittests ```pytest``` should Pass.

**Environment overview (please complete the following information)**

 - Method of NeMo install: 
```./reinstall.sh``` from latest "main" branch.

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version:  Ubuntu
- PyTorch version: 1.6.0
- Python version: 3.7.9
- CUDA version: 10.1

**Additional context**

Seems like onnx/torchscript export issue:

```bash
            diag_info = graph_diagnostic_info()
            if any(info is not None for info in diag_info):
>               raise TracingCheckError(*diag_info)
E               torch.jit.TracingCheckError: Tracing failed sanity checks!
E               ERROR: Graphs differed across invocations!
E               	Graph diff:
E               		  graph(%self.1 : __torch__.nemo.collections.nlp.modules.common.megatron.megatron_bert.MegatronBertEncoder,
E               		        %token_ids : Tensor,
E               		        %attention_mask.1 : Tensor,
E               		        %input.2 : Tensor):
E               		    %4 : __torch__.megatron.model.language_model.TransformerLanguageModel = prim::GetAttr[name="language_model"](%self.1)
...
```

**Comment by borisfom** [comment]
This in the error looks very suspicious: %4 : __torch__.megatron.model.language_model.TransformerLanguageModel = prim::GetAttr[name=“language_model”](%self.1). This should not be part of forward().

**Comment by borisfom** [comment]
I was able to reproduce it on my system. I was not able to see the actual error with the command line above, but it did fail.
I am temporarily passing 'check_trace=False' to the test - I did verify the graph it generates is the same as Python 3.6 generated.

**Comment by borisfom** [comment]
Submitted https://github.com/NVIDIA/NeMo/pull/1141

**Comment by okuchaiev** [comment]
1141 merged, thanks @borisfom
