### ISSUE TITLE
[Question] can we use hdf5 with nemo asr? 

### ISSUE THREAD

**Issue by usamaehsan** [NVIDIA/NeMo#1140]
I am trying to train asr with my own data on colab but its very slow. I have read that we can make it fast by using hdf5.
Can you please tell me, can we use hdf5 file format with nemo asr?

**Comment by okuchaiev** [comment]
Currently NeMo does not support hdf5 file format. If your data is in hdf5 format you have two options: (1) write a script to convert it into format which NeMo accepts, (2) write a data layer which would read hdf5 and adjust model you need accordingly.

**Comment by usamaehsan** [comment]
thanks for your reply, can you please tell me how i can write data layer?
