### ISSUE TITLE
[ASR]: Compatibility error with NumPy v2.0

### ISSUE THREAD

**Issue by njfamirm** [NVIDIA/NeMo#11508]
Hi

**Describe the bug**

Compatibility error with NumPy v2.0: AttributeError: `np.sctypes was removed in the NumPy 2.0 release. Access dtypes explicitly instead.. Did you mean: 'dtypes'?`

**Steps/Code to reproduce bug**

Run this code

```python
import nemo.collections.asr as nemo_asr

# 1. Download and instantiate the Persian model
asr_model_name="nvidia/stt_fa_fastconformer_hybrid_large"
asr_model = nemo_asr.models.EncDecHybridRNNTCTCBPEModel.from_pretrained(model_name=asr_model_name)

audio_file_path = "voice_01.wav"
asr_model.transcribe([audio_file_path])
```

**Expected behavior**

Work fine!

**Environment overview (please complete the following information)**

 - Environment location: [Github Codespace)]
 - pip install nemo_toolkit==2.0.0

**Environment details**

- OS version: Linux codespaces-aa0b2f 6.5.0-1025-azure
- PyTorch version: `2.5.1`
- Python version: 3.12.7

**Comment by njfamirm** [comment]
fixed with static version set for numpy

**Comment by ymzayek** [comment]
@njfamirm what version did you fix numpy to? I'm having the same problem. I tried to downgrade to numpy 1.23.5 but had other compatibility issues. Is [ASR] not compatible with numpy 2 at all or just the latest release?

**Comment by njfamirm** [comment]
> [@njfamirm](https://github.com/njfamirm) what version did you fix numpy to? I'm having the same problem. I tried to downgrade to numpy 2.0.2 but had other compatibility issues. Is [ASR] not compatible with numpy 2 at all or just the latest release?
> 
> EDIT: in the end it worked with 1.23.5

Hi, `numpy==1.26.4`
