### ISSUE TITLE
[Question] LM beam search decoding in ASR models

### ISSUE THREAD

**Issue by adbrebs** [NVIDIA/NeMo#1153]
Hi there and thanks for developing this great project!

I was wondering if in the new refactoring of Nemo, there was still a way to add a LM beam search decoding to ASR models. And if not, is it in your short-term plans to add it? If I remember correctly in the former version, a tutorial was explaining it.

Thanks!

**Comment by okuchaiev** [comment]
That feature isn't ported yet.However, yes, it is in our short-term plan to have BeamSearch with some kind of external LM support

**Comment by okuchaiev** [comment]
closing as a duplicate of https://github.com/NVIDIA/NeMo/issues/1156 . Also there you can see temporary workaround

**Comment by adbrebs** [comment]
Great thanks, really looking forward to the official release.
