### ISSUE TITLE
[Question] training after load_from checkpoint

### ISSUE THREAD

**Issue by usamaehsan** [NVIDIA/NeMo#1155]
**Describe your question**

When we load model by using 
Quartznet=EncDecCTCModel.load_from_checkpoint(ptl checkpoint path') 
And after that we train this model by using
Trainer.fit(Quartznet)
It starts traing from start or from previous checkpint epoch?

**Comment by sasidharreddy25** [comment]
> **Describe your question**
> 
> When we load model by using
> Quartznet=EncDecCTCModel.load_from_checkpoint(ptl checkpoint path')
> And after that we train this model by using
> Trainer.fit(Quartznet)
> It starts traing from start or from previous checkpint epoch?
did you  get answer ??
