### ISSUE TITLE
[Question] how we can use language model+beam search at inference of asr in new nemo? 

### ISSUE THREAD

**Issue by usamaehsan** [NVIDIA/NeMo#1156]
And can you please Add runnable language model + beam search to ASR tutorial notebook. It will be very helpful

**Comment by prashantserai** [comment]
I am interested in this as well!

**Comment by khursani8** [comment]
Currently I'm using [ctcdecode](https://github.com/parlance/ctcdecode) for beam search
I also use it to get the timesteps since it will return the timesteps for each beam.

The only changes you need to do is to get the log_probs, I do it by adding new method in EncDecCTCModel based on transcribe method and instantiate using .load_from_checkpoint

**Comment by okuchaiev** [comment]
Thanks @khursani8 for a workaround. As I mentioned here https://github.com/NVIDIA/NeMo/issues/1153 this is currently not ported but we are have this (or similar) functionality on our short-term radar.

**Comment by okuchaiev** [comment]
re-opening so that others can use this the workaround from @khursani8

**Comment by usamaehsan** [comment]
@okuchaiev why dont you add this code in nemo asr tutorial notebook?

**Comment by edward15241** [comment]
I use following steps and it works.
1. Build the swig_decoder in old version of NeMo data. I use 0.9.x  (./Nemo/scripts/install_decoder.sh)
    

2. See "nemo/collections/asr/models/ctc_models.py" in latest version of NeMo.  
    write a new class (e.g. EncDecBeamSearchCTCModel)  and inherit base class (EncDecCTCModel )  

3. re-write forward() and transcribe() function like @khursani8 do and rememeber to signed up the new class in __init__.py
   examples: https://drive.google.com/file/d/1zBUwp8JXgqueyWGy9F3xNjzdCeKSU6_V/view?usp=sharing

4. reinstall Nemo  (NeMo/reinstall.sh)

**Comment by gauravgund** [comment]
Is there a Jupyter Notebook for this?
