### ISSUE TITLE
loading model from pt checkpoint

### ISSUE THREAD

**Issue by nshaposh** [NVIDIA/NeMo#1167]

**Comment by nshaposh** [comment]
Hello, 

I am having troubles loading model weights from a pt checkpoint. Namely,

import nemo
nemo.__version__
'1.0.0alpha1'

cfg = omegaconf.OmegaConf.load('conf/SpeakerNet_verification_3x2x512.yaml')
spkr_embs_model = ExtractSpeakerEmbeddingsModel(cfg.model)
spkr_embs_model.load_from_checkpoint(chkpt_dir + 'trainer-STEP-355500.pt')

I am having this error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-c386663cc02e> in <module>
----> 1 spkr_embs_model.load_from_checkpoint(chkpt_dir + 'trainer-STEP-355500.pt')

/opt/conda/lib/python3.6/site-packages/nemo/core/classes/modelPT.py in load_from_checkpoint(cls, checkpoint_path, map_location, hparams_file, strict, *args, **kwargs)
    332                 hparams_file=hparams_file,
    333                 strict=strict,
--> 334                 **kwargs,
    335             )
    336 

/opt/conda/lib/python3.6/site-packages/pytorch_lightning/core/saving.py in load_from_checkpoint(cls, checkpoint_path, map_location, hparams_file, strict, *args, **kwargs)
    151         checkpoint[cls.CHECKPOINT_HYPER_PARAMS_KEY].update(kwargs)
    152 
--> 153         model = cls._load_model_state(checkpoint, *args, strict=strict, **kwargs)
    154         return model
    155 

/opt/conda/lib/python3.6/site-packages/pytorch_lightning/core/saving.py in _load_model_state(cls, checkpoint, strict, *cls_args, **cls_kwargs)
    188             cls_args, cls_kwargs = [], {}
    189 
--> 190         model = cls(*cls_args, **cls_kwargs)
    191         # load the state_dict on the model automatically
    192         model.load_state_dict(checkpoint['state_dict'], strict=strict)

/opt/conda/lib/python3.6/site-packages/nemo/collections/asr/models/label_models.py in __init__(self, cfg, trainer)
    287 
    288     def __init__(self, cfg: DictConfig, trainer: Trainer = None):
--> 289         super().__init__(cfg=cfg, trainer=trainer)
    290 
    291     def test_step(self, batch, batch_ix):

/opt/conda/lib/python3.6/site-packages/nemo/collections/asr/models/label_models.py in __init__(self, cfg, trainer)
     49 
     50     def __init__(self, cfg: DictConfig, trainer: Trainer = None):
---> 51         super().__init__(cfg=cfg, trainer=trainer)
     52         self.preprocessor = EncDecSpeakerLabelModel.from_config_dict(cfg.preprocessor)
     53         self.encoder = EncDecSpeakerLabelModel.from_config_dict(cfg.encoder)

/opt/conda/lib/python3.6/site-packages/nemo/core/classes/modelPT.py in __init__(self, cfg, trainer)
     61         """
     62         if not isinstance(cfg, DictConfig):
---> 63             raise ValueError(f"cfg constructor argument must be of type DictConfig but got {type(cfg)} instead.")
     64         if trainer is not None and not isinstance(trainer, Trainer):
     65             raise ValueError(

ValueError: cfg constructor argument must be of type DictConfig but got <class 'dict'> instead.

**Comment by nshaposh** [comment]
model_cfg.__class__.__name__ gives:
'DictConfig'

**Comment by nithinraok** [comment]
Issue is because checkpoints trained with nemo v0.11 have been used with v1.0. 
To port trained 0.* checkpoints, please use script in scripts/asr_checkpoint_port.py

**Comment by okuchaiev** [comment]
closing, since we added asr_checkpoint_port script
