### ISSUE TITLE
Error running pre-trained Punctuation_and_Capitalization model in local jupyter notebook

### ISSUE THREAD

**Issue by yellowcat8774** [NVIDIA/NeMo#1186]
**Describe your question**
I would like to know how to run the Punctuation_and_Capitalization model just for inference. 
I attempted to launch tutorial in a local jupyter notebook (lauched from virtual env) after installing requirements.txt, requirements_nlp.txt and reinstall.sh. when I python3.6 command line I am able to import the nemo package. 

In the jupyter notebook import nemo throws an No module found error. 
How do I fix this error. Nemo toolkit seems to be install and running the first 2 cells ( which installs these anyways) does not throw any error but yet I see a nemo module not found error.

A clear and concise description of your question.
Describe what you want to achieve. And/or what NeMo APIs are unclear/confusing.

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-17-e34651c37fe7> in <module>
----> 1 from nemo.utils.exp_manager import exp_manager
      2 from nemo.collections import nlp as nemo_nlp
      3 
      4 import os
      5 import wget

ModuleNotFoundError: No module named 'nemo'

```
**Environment overview (please complete the following information)**: Ubuntu 16.04, Cuda 10.1 installed packages in requirements.txt and requirements_nlp.txt 

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]:local jupyter notebook
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.: pip install of nemo

- OS version Ubuntu 16.04
- PyTorch version 1.6.0
- Python version 3.6

Example: GPU model

**Comment by yellowcat8774** [comment]
I was able to get past this error and was able to use the pretrained punctuation model to get inference from the punctuation_capitalization_model.py.
I had a followup question on this, seems like there is a limit on the length of the string input mentioned here: (https://github.com/NVIDIA/NeMo/blob/8394411a83d1f1a28a27a42194547f6de552e4d8/examples/nlp/token_classification/punctuation_capitalization.py#L83)

for instance if I have this (the list has just one 199 word string): 
` queries = [
        'not like a musical it sounds like it\'s like some musical background music that\'s going to play \'em and \
        but I promise I\'ll be doing all the singing so um we haven\'t our schedules were probably not going to \
        need the whole time I think what we want to do on this call is three main thing is the first thing we\'ll \
        do is I just want to level set a little bit of time to do a refresher three minutes on navigating the \
        platform what the main elements you use are either gonna set us up nicely to actually get into the \
        specifics and then when I say the specifics  we\'re going to go through two main searches done was \
        saying you know there\'s a short version and extended version that\'s what I\'ll tee up when they give \
        you the overview and how will leverage the various inputs and levers as I call them to pull and push to \
        get different search results as we go through the searches interrupt me asking me questions let me know \
        what is important that you clarify things ah and then the third thing and really the way will wrap up is'] `

I get the following error:
`    raise ValueError('Pred and words must have the same length')`

Is there any way to increase this allow longer strings as input to the inference engine?

thanks and appreciate your response..

**Comment by ekmb** [comment]
@yellowcat8774 You need to increase the maximim sequence length, as follows:
`model._cfg.dataset.max_seq_length = 1000`

**Comment by ekmb** [comment]
Also, try removing backslash for better results.

**Comment by yellowcat8774** [comment]
Thanks for the quick response. I added the blackslash for better readability here.

So made the change in punctuation_capitalization_config.yaml:
`model:
  nemo_path: ./modeldir # filename to save the model and associated artifacts to .nemo file
  punct_label_ids: null # will be filled during training
  capit_label_ids: null # will be filled during training
  dataset:
    data_dir: ??? # /path/to/training/data
    # parameters for dataset preprocessing
    max_seq_length: 1000`

and I am still run into the same issue. I am just using the `Punctuation_Capitalization_with_BERT` pre-trained model. Should I retrain for the sequence length to take effect?

**Comment by ekmb** [comment]
@yellowcat8774 
You might need to retrain the model if you want to improve the performance on longer sequences (the model was trained on max_seq_length 128). However, the inference with the pre-trained model on long sequence works like this:

`
model = nemo_nlp.models.PunctuationCapitalizationModel.from_pretrained('Punctuation_Capitalization_with_BERT')
model._cfg.dataset.max_seq_length = 1000
queries = ["not like a musical it sounds like it's like some musical background music that's going to play'em and but I promise I'll be doing all the singing so um we haven't our schedules were probably not going to need the whole time I think what we want to do on this call is three main thing is the first thing we'll do is I just want to level set a little bit of time to do a refresher three minutes on navigating the platform what the main elements you use are either gonna set us up nicely to actually get into the specifics and then when I say the specifics we're going to go through two main searches done was saying you know there's a short version and extended version that's what I'll tee up when they give you the overview and how will leverage the various inputs and levers as I call them to pull and push to get different search results as we go through the searches interrupt me asking me questions let me know what is important that you clarify things ah and then the third thing and really the way will wrap up is"]
inference_results = model.add_punctuation_capitalization(queries)
`

**Comment by gvskalyan** [comment]
Hi @ekmb in order to use ONNXRuntime during inference for punct model -
Is implementing the [same](https://github.com/NVIDIA/NeMo/blob/4561fbfc91c2ffe80be55fdbe9edc9611bd0b2c0/nemo/collections/nlp/models/text_classification/text_classification_model.py#L334) in the model file punctualization_capitalization_model.py enough?
Also How can I attach various classifiers ?  Is the below ok? - 
```output_model = attach_onnx_to_onnx(bert_model_onnx, classifier_punct_onnx, classifier_capit_onnx ,"CLPC")``` 

CC: @borisfom

**Comment by rohitgr7** [comment]
@ekmb `model._cfg.dataset.max_seq_length = 1000` doesn't seems to solve the problem. I am using `Punctuation_Capitalization_with_DistilBERT` and my sequences are around 1000 tokens long.

**Comment by gvskalyan** [comment]
Hi @rohitgr7 
I think few transformer models can not handle (subword) sequence length of above 512 - [src](https://github.com/huggingface/transformers/issues/1791#issuecomment-645648560)
You might get the following error:
```RuntimeError: The size of tensor a (X) must match the size of tensor b (512) at non-singleton dimension 1```

**Comment by rohitgr7** [comment]
Hi @gvskalyan 
when I am setting `punctuation._cfg.dataset.max_seq_length = 10000`
getting this:
<details><summary>CLICK ME</summary>
<p>

```python
~/.virtualenvs/asr/lib/python3.7/site-packages/transformers/modeling_distilbert.py in forward(self, input_ids, attention_mask, head_mask, inputs_embeds, output_attentions, output_hidden_states, return_dict)
    496 
    497         if inputs_embeds is None:
--> 498             inputs_embeds = self.embeddings(input_ids)  # (bs, seq_length, dim)
    499         return self.transformer(
    500             x=inputs_embeds,

~/.virtualenvs/asr/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/.virtualenvs/asr/lib/python3.7/site-packages/transformers/modeling_distilbert.py in forward(self, input_ids)
    111 
    112         word_embeddings = self.word_embeddings(input_ids)  # (bs, max_seq_length, dim)
--> 113         position_embeddings = self.position_embeddings(position_ids)  # (bs, max_seq_length, dim)
    114 
    115         embeddings = word_embeddings + position_embeddings  # (bs, max_seq_length, dim)

~/.virtualenvs/asr/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/.virtualenvs/asr/lib/python3.7/site-packages/torch/nn/modules/sparse.py in forward(self, input)
    124         return F.embedding(
    125             input, self.weight, self.padding_idx, self.max_norm,
--> 126             self.norm_type, self.scale_grad_by_freq, self.sparse)
    127 
    128     def extra_repr(self) -> str:

~/.virtualenvs/asr/lib/python3.7/site-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)

but when I am not setting 
   1812         # remove once script supports set_grad_enabled
   1813         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1814     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1815 
   1816 

IndexError: index out of range in self
```

</p>
</details>

which I think is obvious since the positional embedding token limit is 512

but when I am not setting anything:
getting this:
<details><summary>CLICK ME</summary>
<p>

```python
<ipython-input-124-fa4d3f4fbf6f> in <module>
----> 1 result = punctuation.add_punctuation_capitalization(queries=[tmp_transcription])

~/Desktop/asr/NeMo/nemo/collections/nlp/models/token_classification/punctuation_capitalization_model.py in add_punctuation_capitalization(self, queries, batch_size)
    353             if sum(queries_len) != len(all_punct_preds) or sum(queries_len) != len(all_capit_preds):
    354                 print(sum(queries_len), len(all_punct_preds), sum(queries_len), len(all_capit_preds))
--> 355                 raise ValueError('Pred and words must have the same length')
    356 
    357             punct_ids_to_labels = {v: k for k, v in self._cfg.punct_label_ids.items()}

ValueError: Pred and words must have the same length
```

</p>
</details>

Not sure about the second one. Still exploring.

**Comment by ekmb** [comment]
> Hi @rohitgr7
> I think few transformer models can not handle (subword) sequence length of above 512 - [src](https://github.com/huggingface/transformers/issues/1791#issuecomment-645648560)
> You might get the following error:
> `RuntimeError: The size of tensor a (X) must match the size of tensor b (512) at non-singleton dimension 1`

Right, 512 is the max length lengths DistilBERT base and BERT base can handle.

**Comment by ekmb** [comment]
> Hi @gvskalyan
> when I am setting `punctuation._cfg.dataset.max_seq_length = 10000`
> getting this:
> 
> CLICK ME
> which I think is obvious since the positional embedding token limit is 512
> 
> but when I am not setting anything:
> getting this:
> 
> CLICK ME
> ```python
> <ipython-input-124-fa4d3f4fbf6f> in <module>
> ----> 1 result = punctuation.add_punctuation_capitalization(queries=[tmp_transcription])
> 
> ~/Desktop/asr/NeMo/nemo/collections/nlp/models/token_classification/punctuation_capitalization_model.py in add_punctuation_capitalization(self, queries, batch_size)
>     353             if sum(queries_len) != len(all_punct_preds) or sum(queries_len) != len(all_capit_preds):
>     354                 print(sum(queries_len), len(all_punct_preds), sum(queries_len), len(all_capit_preds))
> --> 355                 raise ValueError('Pred and words must have the same length')
>     356 
>     357             punct_ids_to_labels = {v: k for k, v in self._cfg.punct_label_ids.items()}
> 
> ValueError: Pred and words must have the same length
> ```
> 
> Not sure about the second one. Still exploring.

The second error means that the query was truncated and not all input tokens have associated predictions, as a result, the query has more labels than predictions. Please try increasing the max sequence lengths to 512.

**Comment by rohitgr7** [comment]
Thanks @ekmb . That solved the problem. But still not working with long seq length. As of now I solved it by splitting the text with an offset/stride and merging the results at the end. Working fine but is not efficient solution. Looking for alternatives.
