### ISSUE TITLE
Error while running Text Classification Sentiment Analysis Notebook

### ISSUE THREAD

**Issue by suyashjoshi** [NVIDIA/NeMo#1201]
**Describe the bug**

Try to run Text_Classification_Sentiment_Analysis.ipynb in Google Colab Notbook, you will see this error at cell:

```
from nemo.collections import nlp as nemo_nlp
from nemo.utils.exp_manager import exp_manager

import os
import wget 
import torch
import pytorch_lightning as pl
from omegaconf import OmegaConf

```
**Console Error:**

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9dea72b2f46b> in <module>()
      1 from nemo.collections import nlp as nemo_nlp
----> 2 from nemo.utils.exp_manager import exp_manager
      3 
      4 import os
      5 import wget

ModuleNotFoundError: No module named 'nemo.utils.exp_manager'

```
----------

**Steps/Code to reproduce bug**

See above

**Expected behavior**

It should execute the cell without this error

**Environment overview (please complete the following information)**

Google Colab on GPU for Text_Classification_Sentiment_Analysis.ipynb of master branch https://github.com/NVIDIA/NeMo.git@{BRANCH}#egg=nemo_toolkit[nlp]
**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version : Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- PyTorch version : N/A
- Python version : 3.6.9

**Additional context**

Example: GPU model

**Comment by VahidooX** [comment]
It is working fine when I open the link on colab and run it. Have you tried factory reset option from the runtime menu of the colab?

**Comment by VahidooX** [comment]
Another question: which branch are you using, main or master?

**Comment by suyashjoshi** [comment]
I ran it on master, that was another thing to not the steps weren't clear which branch names are there that we can type - perhaps the code can just hardcode of the branch names.

**Comment by suyashjoshi** [comment]
> It is working fine when I open the link on colab and run it. Have you tried factory reset option from the runtime menu of the colab?

I remember doing a reset as it mentioned in the cell but I can try again.

**Comment by VahidooX** [comment]
We do not update the master anymore. The branch is called main. I would hardcode that in the tutorial in a PR to be merged very soon today.

**Comment by okuchaiev** [comment]
yes, master is gone now. please re-open if issue persists on main
