### ISSUE TITLE
Having trouble importing and exporting NeMo ASR Model

### ISSUE THREAD

**Issue by cosmonautputin** [NVIDIA/NeMo#1202]
Using https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/01_ASR_with_NeMo.ipynb
I used custom manifests (train_transcripts, train_manifest, test_transcripts, test_manifest) and with trainer.fit(first_asr_model)
trained a model.

Then, I used:
```
first_asr_model.save_to('/path_to/checkpoint/cp')
first_asr_model.transcribe(paths2audio_files=wave_file) # Tested with a local wav_file and it worked.
```
Then, when I tried to import import/load checkpoint/model by rebuilding first_asr_model_continued, it didn't work.
When I tried the same transcribe function on the wav_file, all I got was empty string in result.

```
config_path = './configs/config.yaml'
with open(config_path) as f:
    params = yaml.load(f)

train_manifest='/path_to/train_manifest_new.json'
test_manifest='/path_to/test_manifest_new.json'

params['model']['train_ds']['manifest_filepath'] = train_manifest
params['model']['validation_ds']['manifest_filepath'] = test_manifest

cfg=DictConfig(params['model'])
import pytorch_lightning as pl
trainer = pl.Trainer(gpus=1, max_epochs=50)

from omegaconf import DictConfig
first_asr_model = nemo_asr.models.EncDecCTCModel(cfg, trainer=trainer)

first_asr_model.restore_from('/path_to/checkpoint/cp')
```

What am I doing wrong?

**Comment by okuchaiev** [comment]
When you do: "restore_from" it will load/restore *all* information, including training/validation details and paths.

So what you want to do is after you did "restore_from(...)" you should call setup_training/validation methods. Something like this:
```
config_path = './configs/config.yaml'
with open(config_path) as f:
    params = yaml.load(f)
# Restores your model
first_asr_model.restore_from('/path_to/checkpoint/cp')
# Point to the data we'll use for fine-tuning as the training set
first_asr_model.setup_training_data(train_data_config=params['model']['train_ds'])
# Point to the new validation data for fine-tuning
first_asr_model.setup_validation_data(val_data_config=params['model']['validation_ds'])
# make sure you have also lowered learning rate if you are fine-tuning from pre-trained model
first_asr_model.setup_optimization(optim_config=....)
import pytorch_lightning as pl
trainer = pl.Trainer(gpus=1, max_epochs=50)
trainer.fit(first_asr_model)
```

**Comment by cosmonautputin** [comment]
> When you do: "restore_from" it will load/restore _all_ information, including training/validation details and paths.
> 
> So what you want to do is after you did "restore_from(...)" you should call setup_training/validation methods. Something like this:
> 
> ```
> config_path = './configs/config.yaml'
> with open(config_path) as f:
>     params = yaml.load(f)
> # Restores your model
> first_asr_model.restore_from('/path_to/checkpoint/cp')
> # Point to the data we'll use for fine-tuning as the training set
> first_asr_model.setup_training_data(train_data_config=params['model']['train_ds'])
> # Point to the new validation data for fine-tuning
> first_asr_model.setup_validation_data(val_data_config=params['model']['validation_ds'])
> # make sure you have also lowered learning rate if you are fine-tuning from pre-trained model
> first_asr_model.setup_optimization(optim_config=....)
> import pytorch_lightning as pl
> trainer = pl.Trainer(gpus=1, max_epochs=50)
> trainer.fit(first_asr_model)
> ```


Thank you for your quick response.

I have 2 brief follow up questions:
1. 
I was able to finally get some transcription with the following snippet:
```
import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecCTCModel.restore_from('/path_to/checkpoint/qz_15x5.nemo')  #checkpoint saved with first_asr_model.save_to('/path_to/checkpoint/qz_15x5.nemo') as part of the training.
wave_file = ['sample.wav']
res=fam.transcribe(paths2audio_files=wave_file)
```
As per the additional steps in your snippet, I am wondering if this piece of code loads a trained model or an empty model that needs to then be trained. (Pardon the lack of proper jargon)

2.If additional steps are not needed, would this be a good way of importing a trained model (deploying) and using it for ASR Speech to text? Or is there another way to only import the model so that it can be used on the fly to transcribe any local audio passed, without having to train it again? And if there is, would I be able to import it as easily from the checkpoint created with model.save_to() or I would need to do something else for that?

**Comment by omry** [comment]
Likely unrealted to your problem, but you should probably just [load with OmegaConf directly](https://omegaconf.readthedocs.io/en/latest/usage.html#serialization).
