### ISSUE TITLE
[Question]  Volatile GPU-Util is 0%

### ISSUE THREAD

**Issue by amejri** [NVIDIA/NeMo#1204]
Hi guys, 
I hope you are doing well. I have a question about a warning that I have when I tried to train a model. 

ackages/pytorch_lightning/utilities/distributed.py:37: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
      warnings.warn(*args, **kwargs)

And when I tried to verify the gpu usage, with nvidia-smi, the Memory-Usage is full but Volatile GPU-util indicates 0% ( in other words, it seems that the gpu doesn't work )
Do you have some ideas about this warning ?
Thanks in advance.

**Comment by okuchaiev** [comment]
Yes, please try increasing ```num_workers``` from command line (or config). Here is command line example:
```
    +model.train_ds.num_workers=16 \
    +model.train_ds.pin_memory=True \
    +model.validation_ds.num_workers=16 \
    +model.validation_ds.pin_memory=True \
```

I'd recommend you set num_workers to number of threads (or cores) of your CPU
