### ISSUE TITLE
[Question] How to use tarred dataset

### ISSUE THREAD

**Issue by khursani8** [NVIDIA/NeMo#1218]
I have created tar and json file by using this [script](https://github.com/NVIDIA/NeMo/blob/96305399a1b82ea81bda9002ea8745a9daa4086a/scripts/convert_to_tarred_audio_dataset.py)
I don't know how to use it and what I should change/add in config.yaml file

Thanks

**Comment by redoctopus** [comment]
In the ASR config.yaml, you'll need to change some parameters for your training dataset:
- `is_tarred: True` (line 18)
- `tarred_audio_filepaths: <your_tarred_filepaths_{1..n}.tar>` (line 19)

You can also set these via the command line using Hydra, by adding `model.train_ds.is_tarred=True` etc. to your training command.

**Comment by titu1994** [comment]
To add to the above, if you are using hydra (command line) overrides for `tarred_audio_filepaths` then use `_OP_` and `_CL_` in place of { and } respectively. These keywords get replaced to { and } and avoid certain Hydra override parsing issues.

**Comment by khursani8** [comment]
@redoctopus I got error, this is my minimal reproducible code https://colab.research.google.com/drive/1HgAyerYqFVAbHQphwzJQ2_gQ9_B1x8NA?usp=sharing

@titu1994 ohhh that's how to represent opening and closing braces in hydra

Thanks

**Comment by titu1994** [comment]
@khursani8 You need to create a pytorch lightning Trainer object and set it to the model using QuartzNet.set_trainer(trainer) before you use setup_optimization().
