### ISSUE TITLE
Intent slot classification: Should the entity be trained?

### ISSUE THREAD

**Issue by laifuchicago** [NVIDIA/NeMo#1219]
To Author:
Our team are currently studying the Intent slot classification using Bert model. Previously, we used our own framework. We need to train the entity. So if we use the NeMo, we still need to train the entity or it's rule-based?

Jonathan Sung

**Comment by okuchaiev** [comment]
Have a look at this tutorial https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/Token_Classification_Named_Entity_Recognition.ipynb

It shows you both how to use out-of-the-box model:
```
# this line will download pre-trained NER model from NVIDIA's NGC cloud and instantiate it for you
pretrained_ner_model = nemo_nlp.models.TokenClassificationModel.from_pretrained(model_name="NERModel") 
```

And how to train/fine-tune one on your data.

With NeMo you can train/fine-tune every model. NER (or more generally, token classification) models in NeMo are all based on BERT-like models, not rule-based.

**Comment by vladgets** [comment]
Hi Jonathan,

In case of the Joint Intent and Slot classification model you are training to recognize both of them together using one single Bert based NN (no rules). Here is a notebook example that you can run directly on Google Colab: https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Intent_and_Slot_Classification.ipynb
that demonstrates training of this model on a reference dataset.

Please let me know if you have anymore questions.

**Comment by laifuchicago** [comment]
To Author:
I have tried your NLU data on local, it can work. But what if I want to train my own data like the figure below? And the language is Thai. I think bert-multilingual can support, am I right? Thanks for your help!
![question1](https://user-images.githubusercontent.com/8537280/94329747-4f8b8900-fff0-11ea-8b95-fb704cfbaf06.PNG)
![question2](https://user-images.githubusercontent.com/8537280/94329795-b27d2000-fff0-11ea-9b0b-7975aa0aaf67.PNG)

Jonathan Sung

**Comment by vladgets** [comment]
My suggestion:

1) You need to have Bert model pretrained on large corpus of Thai language. You can either use our Bert LM training scripts with your own large Thai language corpus or probably you can find already pretrained model for Thai somewhere on the Internet. 

2) After you have it, you can use the same Intent & Slot classification fine tuning procedure in Nemo using the Thai pretrained Bert model as a base. Probably with its unique Tokenizer.

Let us know if it works for you.

**Comment by laifuchicago** [comment]
To Author:
Do I need to use NLU format then convert to NeMo format? Because I only have these two files(test ,train), thanks.

Jonathan Sung

**Comment by vladgets** [comment]
For a phase of Intent (and Slot) classification training model you need to convert the data to Nemo data format. If you have only Intents for these sentences you can use Text Classification model (example) for that: https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/Text_Classification_Sentiment_Analysis.ipynb

If you want to recognize also slots (entities) inside of the sentences. Then you can update the data to something similar like: "i want to buy [entity_name: iphone]" and for example to put all the examples of the same intent in a in single text file with the same name. 
https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Intent_and_Slot_Classification.ipynb gives you example of training such a model with a reference dataset (assistant) that you can see it's original format and use our converter to Nemo data format.
So you can convert your dataset to this reference dataset format.

**Comment by laifuchicago** [comment]
To Author:
If we have our own dataset, should we create the train/test_slot.csv for example 54 0 0 54 54 12 12 in order to use NeMo to train?

Jonathan Sung

**Comment by vladgets** [comment]
Yes, these files are used to train slots. You can use any annotation format for your own data. But then you need to convert it to Nemo format for model training. By creating Intent and Slot dictionary and creating these training Intent and Slot files by replacing words from the query with correct Slot number from the dictionary.
