### ISSUE TITLE
[Question] Postprocessing ASR

### ISSUE THREAD

**Issue by amejri** [NVIDIA/NeMo#1220]
Hi guys, 
I have a question about the manner to apply postprocessing for ASR models. In the previous version, you specified a way to use it, but for the current one, I can't find it. Can you please tell me how to do that ?
Thanks in advance.

**Comment by caohongnga** [comment]
Hi, 
you run ...NeMo/examples/asr/speech2text_infer.py --asr_model='your .pt.nemo file' --dataset='your dataset file.json'
You can add more code to save your result.

**Comment by amejri** [comment]
Hi,
Thanks for your response. The code that you indicate doesn't apply postprocessing. it just tests the performance of the model.
