### ISSUE TITLE
Which part should I modify if I use my own training and testing data or other languages?

### ISSUE THREAD

**Issue by laifuchicago** [NVIDIA/NeMo#1228]
To Author:
I have tried your NLU data on local, it can work. But what if I want to train my own data like the figure below? And the language is Thai. I think bert-multilingual can support, am I right? Thanks for your help!
![question1](https://user-images.githubusercontent.com/8537280/94329747-4f8b8900-fff0-11ea-8b95-fb704cfbaf06.PNG)
![question2](https://user-images.githubusercontent.com/8537280/94329795-b27d2000-fff0-11ea-9b0b-7975aa0aaf67.PNG)

Jonathan Sung

_Originally posted by @laifuchicago in https://github.com/NVIDIA/NeMo/issues/1219#issuecomment-699354398_

**Comment by okuchaiev** [comment]
It is not quite clear which specific model do you mean. 
But, in general, you should be able (with some effort) to fine-tune NLP models on your data.
I'd recommend you checkout this tutorial https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/00_NeMo_Primer.ipynb for how-to change data, optimizers, etc.
