### ISSUE TITLE
Dockerfile does not build, incomplete command

### ISSUE THREAD

**Issue by jfsantos** [NVIDIA/NeMo#1233]
The current Dockerfile has an issue on line 59: https://github.com/NVIDIA/NeMo/blob/6c5d339f8a4abc1f8e5abdcb066ff6d9bd826e29/Dockerfile#L59. It looks like it is missing a command before `--mount`.

**Comment by titu1994** [comment]
Sorry for the delay, I built the current main branch dockerfile with the 450.x drivers a few days ago without issue and the PR didn't update this flag.

Also updated docker and built it today and it seems to run and pass all tests in interactive mode. You need the experimental flag with DOCKER_BUILDKIT=1 for the syntax though.
