### ISSUE TITLE
How can i resume training from checkpoint

### ISSUE THREAD

**Issue by harrypotter90** [NVIDIA/NeMo#1238]
I started training and later wanted to change training dataset, but not sure how can i "continue training".

I initially started train with following command:
python speech2text.py --asr_model=quartznet15x5.yaml --amp_opt_level=O2 --eval_datasets=<> --batch_size=42 --train_dataset=<>  --checkpoint_dir=/code/checkpoint/

So basically when i train again (resume) what command should i pass.

**Comment by anujsuchchal** [comment]
@harrypotter90 In your checkpoint dir i.e. /code/checkpoint/, there must be model files with .nemo extension. Take the latest file and pass it like --asr_model=<File Name>.nemo

**Comment by harrypotter90** [comment]
Yup, thats what i figured out from the documentation/code

But in the checkpoint i am getting only these 3 files:
```
trainer-STEP-171000.pt
JasperEncoder-STEP-171000.pt
JasperDecoderForCTC-STEP-171000.pt
```
and no ".nemo" file

I am using latest release version  **v0.11.1**

**Comment by harrypotter90** [comment]
Hi, any thoughts on it ? I dont find a ".nemo" file in a checkpoint.

instead getting files like 
```
trainer-STEP-171000.pt
JasperEncoder-STEP-171000.pt
JasperDecoderForCTC-STEP-171000.pt
```

**Comment by okuchaiev** [comment]
@harrypotter90 please upgrade to the latest release "pip install nemo_toolkit[all]==1.0.0b1". We made a lot of incompatible changes since 0.11.

Main branch and all tutorials correspond to 1.0.0b1 version

**Comment by soheiltehranipour** [comment]
Hi, Where did you save your checkpoints? 
I ran my models on 0.11 version with this at the end of scripts : --checkpoint_dir='/content/checkpoint'
I am using Colab and it is resuming every time I have my checkpoints uploaded.

**Comment by khalilRhouma** [comment]
> @harrypotter90 please upgrade to the latest release "pip install nemo_toolkit[all]==1.0.0b1". We made a lot of incompatible changes since 0.11.
> 
> Main branch and all tutorials correspond to 1.0.0b1 version

@okuchaiev  I am using 1.0.0b1 version and the checkpoint file named `Tacotron2--end.ckpt`, so there is no .nemo file 
how to make them saved in .nemo format ?

**Comment by Ashbajawed** [comment]
@harrypotter90  did you find any way?
