### ISSUE TITLE
[Question]how to do finetuning ? how to change the train_ds file according to your data ?

### ISSUE THREAD

**Issue by samabdullah** [NVIDIA/NeMo#1254]
**Describe your question**

A clear and concise description of your question.
Describe what you want to achieve. And/or what NeMo APIs are unclear/confusing.

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by okuchaiev** [comment]
See https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/asr/01_ASR_with_NeMo.ipynb#scrollTo=2f142kIQc1Z2 for ASR example.
Also, these two notebooks should be helpful:

* https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/00_NeMo_Primer.ipynb
* https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/01_NeMo_Models.ipynb

**Comment by i181237** [comment]
> 
> 
> See https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/asr/01_ASR_with_NeMo.ipynb#scrollTo=2f142kIQc1Z2 for ASR example.
> Also, these two notebooks should be helpful:
> 
>     * https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/00_NeMo_Primer.ipynb
> 
>     * https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/01_NeMo_Models.ipynb

im just confused if i want to fine tune where this train_ds file should be placed as mentioned in tutorial

**# Point to the data we'll use for fine-tuning as the training set
quartznet.setup_training_data(train_data_config=params['model']['train_ds'])**__

if i give its path in the config file 
wont it overwrite the pretrained model training?

**Comment by i181237** [comment]
any update ?
