### ISSUE TITLE
How can I use Jarvis for the intent and slot classification?

### ISSUE THREAD

**Issue by laifuchicago** [NVIDIA/NeMo#1264]
To Author: 
Now I am using your tutorial to do the intent and slot classification. I used the NLU_Evaluation data . In the import_dataset.py , I saw --dataset_name can be jarvis. But when I use that to run, the error would be shown. I also followed the quick start guide but found the following error(figure) .So what do I need if I want to run Jarvis? Thanks.

![jarvis rror_1](https://user-images.githubusercontent.com/8537280/95440743-db57ca80-098b-11eb-85ad-0e2b5c966037.PNG)

Jonathan Sung

**Comment by vladgets** [comment]
Hi Jonathan.
We removed support of Jarvis dataset from import_datasets.py script in a new Nemo version, since we thought no one is using it anymore. If you need it, I can restore this support. Please let me know.
Meanwhile, you can use Assistant dataset from the Tutorial notebook.

**Comment by pchitale1** [comment]
Please connect with Jarvis support team for this issue, thanks

**Comment by laifuchicago** [comment]
> Hi Jonathan.
> We removed support of Jarvis dataset from import_datasets.py script in a new Nemo version, since we thought no one is using it anymore. If you need it, I can restore this support. Please let me know.
> Meanwhile, you can use Assistant dataset from the Tutorial notebook.

Can you restore the Jarvis support, thanks.
Jonathan Sung

**Comment by laifuchicago** [comment]
> Please connect with Jarvis support team for this issue, thanks

How can I connect the Jarvis team? Currently no github about Jarvis.
Jonathan Sung

**Comment by vladgets** [comment]
How do you use Jarvis dataset?

**Comment by laifuchicago** [comment]
To Author:
Because we want to use Jarvis to make the inference faster. By the way, if we want to use Jarvis, we need the Jarvis Beta Access approval?
Jonathan Sung

**Comment by vladgets** [comment]
Jarvis Intent and slot dataset does not have relation to using Jarvis service for Inference. It is just some test data set that we used in the past but not anymore.
Yes, until Jarvis is fully open to the public you need the Beta access approval.

**Comment by laifuchicago** [comment]
To Author:
OK I see, if I want to to the inference about intent and slot classification, how can I do? Is there any tutorial about that?

Jonathan Sung

**Comment by vladgets** [comment]
Currently we have example how to make inference of the trained model from a data file.
We are going to add in the next couple of weeks an example how to do inference from Queries.
It will be a part of the Tutorial notebook and also Example python file.  
Please follow for the updates of the main branch.

**Comment by laifuchicago** [comment]
To Author:
Currently, we have jarvis-quickstart. But I have some questions: 
(1)I followed the instructions and got the downloading error. Please see the figure.
![jarvis_model_download_error1](https://user-images.githubusercontent.com/8537280/96210784-3b122f00-0fa5-11eb-8170-61bd937ca80e.PNG)

(2) Second is can I use docker version under 19.03 by deleting some code in the .sh file? That's my question. By the way, is there any access to connect to the Jarvis team?

Jonathan Sung
