### ISSUE TITLE
[Question] How to Resume Training NeMo ASR "from checkpoints"?

### ISSUE THREAD

**Issue by soheiltehranipour** [NVIDIA/NeMo#1271]
**Question**
 I am using NeMo ASR Toolkit for Persian Language and after migrating from 0.11 to 1.0, I have a problem with resuming training the model with checkpoints. 
Based on the tutorials and codes in NeMo's Github profile, after providing manifest, I can start training with this script.

```
!python /content/NeMo/examples/asr/speech_to_text.py --config-name=/content/configs/config.yaml \
model.train_ds.manifest_filepath=/content/train.json \
model.validation_ds.manifest_filepath=/content/test.json \
trainer.gpus=1 trainer.max_epochs=100 \
+resume_if_exists=True \
+resume_past_end=True \
+create_checkpoint_callback=True
```

But whenever my training is stopped, I can't resume training and after running this scripts, The whole training will start from scratch without using checkpoints.
I would appreciate if you can tell me how i can fix the problem or how to change the script to make my model resume from the checkpoints.
For more information, during the training I have a folder named **nemo_experiment** containing the logs and checkpoints.

**Environment overview:**
 - Environment location: Google Colab
 - Method of NeMo install: `!python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]`

**Environment details**
- OS version : Ubuntu 18.04
- PyTorch version : 1.6.0+cu101
- Python version : Python 3.6.9
- GPU model: Tesla T4

**Comment by soheiltehranipour** [comment]
Found it.
Should use "resume from checkpoint"

**Comment by khalilRhouma** [comment]
> Found it.
> Should use "resume from checkpoint"

@soheiltehranipour How did you manage to use "resume from checkpoint" from the terminal command. Did you add any parameter to the config file?

**Comment by samabdullah** [comment]
@soheiltehranipour did you get any success on decreasing the WER?
I'm working also on right to left language(Urdu) but my WER is too high. I'm wondering if its a good approach to use this on RTL 
Language #1359

**Comment by soheiltehranipour** [comment]
> 
> 
> @soheiltehranipour did you get any success on decreasing the WER?
> I'm working also on right to left language(Urdu) but my WER is too high. I'm wondering if its a good approach to use this on RTL
> Language #1359

Yes, I am working on that and now I am on 40% in Persian Language.
There is not a problem in ASR for RTL Language.

**Comment by soheiltehranipour** [comment]
> 
> 
> > Found it.
> > Should use "resume from checkpoint"
> 
> @soheiltehranipour How did you manage to use "resume from checkpoint" from the terminal command. Did you add any parameter to the config file?

Are you using the latest version of NeMo?
You can do it easily like this:
Soheil_NeMo = nemo_asr.models.EncDecCTCModel.load_from_checkpoint('100epoch.ckpt')

You can find the *.ckpt files during training and changed '100epoch.ckpt' with your checkpoint.

**Comment by samabdullah** [comment]
> 
> 
> > @soheiltehranipour did you get any success on decreasing the WER?
> > I'm working also on right to left language(Urdu) but my WER is too high. I'm wondering if its a good approach to use this on RTL
> > Language #1359
> 
> Yes, I am working on that and now I am on 40% in Persian Language.
> There is not a problem in ASR for RTL Language.
@soheiltehranipour Thanks for your reply.
i followed the steps mentioned in the colab repository for transfer leaning but not getting good results.

can you tell me how much data you have used for training and your parameters settings
Are you working on colab or on your system ?

**Comment by paklau99988** [comment]
@samabdullah  did you have any luck with Urdu?
