### ISSUE TITLE
Download Permission Denied

### ISSUE THREAD

**Issue by jmorris644** [NVIDIA/NeMo#1276]
I am getting "permission denied" when trying to pull v1.0.0.b1 using the tag created.

`docker pull nvcr.io/nvidia/nemo:v1.0.0b1`

`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=nvcr.io%2Fnvidia%2Fnemo&tag=v1.0.0b1: dial unix /var/run/docker.sock: connect: permission denied`

**Comment by jmorris644** [comment]
Solved, I had to use Sudo

**Comment by ericharper** [comment]
You can also add your user to the Docker group via these instructions: https://docs.docker.com/engine/install/linux-postinstall/
Then you don't have to use sudo when using Docker commands.
