### ISSUE TITLE
Saved model named QuartNet15x5--val_loss-0.00-epoch-xxx.ckpt but val_loss on tensorboard is non-zero

### ISSUE THREAD

**Issue by guiruli08650129** [NVIDIA/NeMo#1288]
Hi,

I used NeMo-v1.0.0b1 and trained the ASR model by modifying examples/asr/speech_to_text.py.
After training I got 3 models named QuartzNet15x5--val_loss-0.00-epoch-xxx.ckpt.
The val_loss in model name is 0.00 but is non-zero on tensorboard.

<img width="353" alt="picture" src="https://user-images.githubusercontent.com/19429441/95961171-48111000-0e37-11eb-9f8c-c356b9e07a52.png">

My solution:
I modified line 550 in nemo/utils/exp_manager.py :
- original
```
checkpoint_callback = NeMoModelCheckpoint(
    filepath=Path(log_dir / 'checkpoints' / '{val_loss:.2f}-{epoch}'), ...
)
```
- my solution
```
checkpoint_callback = NeMoModelCheckpoint(
    filepath=Path(log_dir / 'checkpoints' / '{validation_loss:.2f}-{epoch}'), ...
)
```
The val_loss in model name is correct after modifying the code.
Is this a bug?

Thanks for your reply.

**Comment by blisc** [comment]
Yes, this is a misconfiguration bug that will raise from failing silently to an application crash after #1278.
We will work to fix this on all models soon. For now, your solution is a good work around if you are sticking to the NeMo ASR models.
