### ISSUE TITLE
Strange # of hours

### ISSUE THREAD

**Issue by catskillsresearch** [NVIDIA/NeMo#1293]
**Describe the bug**

I put in 10 hours of clips and I get this:

```
[NeMo I 2020-10-15 20:26:54 collections:173] Dataset loaded with 9341 files totalling 259472.22 hours
[NeMo I 2020-10-15 20:26:54 collections:174] 0 files were filtered totalling 0.00 hours

```
**Steps/Code to reproduce bug**

```
import nemo.collections.asr as nemo_asr
from glob import glob
model = nemo_asr.models.EncDecCTCModel.load_from_checkpoint(model_fn)
files=list(sorted(glob(f'audio/*.wav')))
translations=model.transcribe(paths2audio_files=files, batch_size=16)
```

**Expected behavior**

When I run this:

```
model.setup_training_data(train_data_config=params['model']['train_ds'])
model.setup_validation_data(val_data_config=params['model']['validation_ds'])
```
I get this, which is a more realistic count of # hours:

```
[NeMo I 2020-10-15 20:19:29 collections:173] Dataset loaded with 8367 files totalling 8.43 hours
[NeMo I 2020-10-15 20:19:29 collections:174] 30 files were filtered totalling 0.17 hours
```
**Environment overview (please complete the following information)**

 - Environment location: Ubuntu 20.04, Anaconda Python 3.7
 - Method of NeMo install: pip install

**Environment details**

- OS version: Ubuntu 20.04LTS
- PyTorch version: 1.6.0
- Python version: 3.7.4
- GPU model: NVidia GeForce RTX 2080TI
- CUDA: 10.1.243
- cuDNN: 7.6.5

**Comment by titu1994** [comment]
@okuchaiev FYI

**Comment by okuchaiev** [comment]
@catskillsresearch not sure what is going on here. Could you please help by answering these questions:
1) Is the number of files correct (e.g. 9341)
2) In .json manifest files, is field "duration" populated correctly?
3) which code produced 259472.22 hours? Did you use setup_training/validation_data method?

**Comment by titu1994** [comment]
@okuchaiev I think it's the duration of 100000 in this line https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/models/ctc_models.py#L143 multiplied by 9341 files. 

9341 * 100000 seconds ~ 259 472.222 hours

**Comment by okuchaiev** [comment]
@catskillsresearch can you please confirm that this happens with transcribe method call?

**Comment by catskillsresearch** [comment]
Yes, I put a quit() after that line, and it stops there.

I can see it doesn't matter, it's just putting in dummy values for transcription.

However it is a source of confusion to print out that # of hours.

I guess it would cost extra to load each file just for that count to find the actual  duration.

You could have the loader take in manifest records with the duration populated instead of just a list of files, as an alternate method.
