### ISSUE TITLE
[Question] what is benefit of lazy execution and also other nemo datatype such NMtensor

### ISSUE THREAD

**Issue by songtaoshi** [NVIDIA/NeMo#1295]
Hi, thanks for such an awesome project, but I am confusing **why nemo make the eager execution of pytorch to be lazy execution** and also some other data structure such as **NMtensor**. I have search all the documentation but did not find some more explicit explanation. Really to hope to get some answers!

**Comment by okuchaiev** [comment]
hi, we recently completed a major re-design on NeMo and this (lazy execution and NMtensor) is no longer the applicable.

Starting from 1.0.0b1 NeMo is built on top of Pytorch Lightning. It still has Neural Types though in slightly better form. I would recommend you refer to this blogpost for high-level overview and pointers to more details https://medium.com/pytorch/nvidia-nemo-neural-modules-and-models-for-conversational-ai-d660480d9696
