### ISSUE TITLE
How to apply inference with trained model?

### ISSUE THREAD

**Issue by david1125222** [NVIDIA/NeMo#1300]
I have trained a model using speech_to_text.py and got some files in my checkpoint directory. The files are: 

`QuartzNet15x5--end.ckptQuartzNet15x5--last.ckpt`
`QuartzNet15x5--val_loss=0.00-epoch=77.ckpt`
`QuartzNet15x5--val_loss=0.00-epoch=85.ckpt`

However, there is no .nemo file and I can't apply these file to  speech_to_text_infer.py to perform inference with the command  "--asr_model= QuartzNet15x5--end.ckpt"
So how should I apply inference with the files in the checkpoint directory? The version I use is 1.0.0b1.

**Comment by okuchaiev** [comment]
The .ckpt files are saved by Pytorch Lightning, you can load them like so:
```
model = model.load_from_checkpoint('foo.ckpt')
```
Every NeMo model is a LightningModule which is a torch.nn.Module. Thus for inference, you can use it either with PTL or "pure" Pytorch.

**Comment by Ashbajawed** [comment]
@okuchaiev  what about when you have 3 .pt files  i.e JasperDecoderForCTC-STEP-82000.pt  JasperEncoder-STEP-82000.pt    trainer-STEP-82000.pt
