### ISSUE TITLE
[Question] Are the examples under the same Apache License 2.0

### ISSUE THREAD

**Issue by denizariyan** [NVIDIA/NeMo#1301]
Are the examples under the same Apache License 2.0 as the rest of the source?

I would like to know if I need to document the changes if I take [this example](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/02_Online_ASR_Microphone_Demo.ipynb) as the starting point.

Thanks

**Comment by okuchaiev** [comment]
yes, if not noted otherwise, all files in the repo are under Apache 2.0
