### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Omarnabk** [NVIDIA/NeMo#1307]
**ASR produce probabilities**

Is it possible to use a customized language model with the current implementation of the ASR? 
How to produce a list of candidate transcriptions?

**Comment by okuchaiev** [comment]
we are working on it (external LM support) - should be available soon.

**Comment by Omarnabk** [comment]
Thank you for your reply. 
Can we use the current model to produce N transcription per wav, lets say candidates. I would like to use a fine-tuned LM to re-score the transcriptions.
