### ISSUE TITLE
cant load pretrained model

### ISSUE THREAD

**Issue by samabdullah** [NVIDIA/NeMo#1313]
when i try to upload a  pretrained model
quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En") 
it is giving error 
AttributeError: module 'nemo.collections.asr' has no attribute 'models'
[Question]

**Comment by TottiPuc** [comment]
Could you try to load the state_dict using nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En", strict=False)? 
The current work-around is to pass strict=False to either #1297

**Comment by blisc** [comment]
Can you try `from nemo.collections.asr.models import EncDecCTCModel`?

**Comment by okuchaiev** [comment]
please try suggestion from @blisc and re-open if you still see the issue

**Comment by zhan0502** [comment]
There is still this error:
 
AttributeError: type object 'EncDecCTCModel' has no attribute 'restore_from' or 'from_pretrained' 

has anyone try out the latest release of nemo 1.3.0?

**Comment by yipenglinoe** [comment]
> There is still this error:
> 
> AttributeError: type object 'EncDecCTCModel' has no attribute 'restore_from' or 'from_pretrained'
> 
> has anyone try out the latest release of nemo 1.3.0?

i tried , exactly the same issus here  "type object 'EncDecCTCModel' has no attribute 'restore_from'"
even from_pretrained() can not use too , please check and fix it

**Comment by blisc** [comment]
Please include a colab notebook in which this issue is reproduced and open another issue.
