### ISSUE TITLE
[Question] ASR_with_NeMo: Missing keys in state_dict

### ISSUE THREAD

**Issue by abdullahtayyab** [NVIDIA/NeMo#1315]
**Describe your question**
I am trying to run the first tutorial for NeMo, from https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/asr/01_ASR_with_NeMo.ipynb

The intent is to use the transfer learning portion of this tutorial and see how it works for Urdu. I want to use the "Out-of-the-box model" and then fine tune in Urdu (local language). 

I am getting an error on the line:
`quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En")`

```
RuntimeError: Error(s) in loading state_dict for EncDecCTCModel:
	Missing key(s) in state_dict: "_wer.scores", "_wer.words".
```

**Environment overview (please complete the following information)**

 - Environment location: Colab
 - Method of NeMo install: !python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Colab
- PyTorch version: Default version on the notebook
- Python version: Default version on the notebook

**Additional context**
Nothing to add here. It is a basic tutorial that isn't working, maybe the tutorial is using the wrong NeMo branch but I would not know enough to troubleshoot.

**Comment by ericharper** [comment]
Can you try
```
# This line will download pre-trained QuartzNet15x5 model from NVIDIA's NGC cloud and instantiate it for you
quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En", strict=False)
```
It's related to this issue: https://github.com/NVIDIA/NeMo/issues/1297

**Comment by ericharper** [comment]
This should be fixed now with: https://github.com/NVIDIA/NeMo/pull/1322
We've pinned Colab Notebooks to the latest stable release of NeMo.

**Comment by okuchaiev** [comment]
Closing since https://github.com/NVIDIA/NeMo/pull/1322 is merged, please re-open if issue persists.
