### ISSUE TITLE
[Question] How can I get character timestamps / word timestamps in Nemo ASR

### ISSUE THREAD

**Issue by sumeet-tiwari-samespace** [NVIDIA/NeMo#1329]
How can I get relative character level timestamps or word level timestamps in nemo asr. 

Thanks,
S

**Comment by khursani8** [comment]
I think you need to wait for this PR to merge first https://github.com/NVIDIA/NeMo/pull/1319

Based on what I saw in this notebook https://github.com/NVIDIA/NeMo/blob/73875d874b006b672a8e407687ef414ef7a7b282/tutorials/asr/Offline_ASR.ipynb
