### ISSUE TITLE
how to save a fine tuned model and load it back?[Question]

### ISSUE THREAD

**Issue by niloofarmaani1** [NVIDIA/NeMo#1352]
hi
I am trying to save the model after fine tuning by using:  torch.save(quartznet,'fine_tuned2.pt')
but I get this error:
AttributeError: Can't pickle local object 'FilterbankFeatures.__init__.<locals>.<lambda>'
how can I save the model and load it back again?
thanks
Niloo

**Comment by okuchaiev** [comment]
You can use .save_to/.restore_from methods to save to and restore from ".nemo" file. 
".nemo" file is a simply ".tar.gz" file (you can rename it to tar.gz and unpack) with checkpoint weights, configuration yaml which was used and (for some models) additional artifacts such as tokenizer's vocabulary, etc.
