### ISSUE TITLE
Inverse text normalization in NeMo

### ISSUE THREAD

**Issue by rohitgr7** [NVIDIA/NeMo#1370]
**Describe your question**
Are you guys planing to add **Inverse text normalization** models in NeMo. Something [like this](https://docs.aws.amazon.com/transcribe/latest/dg/how-numbers.html).

If anyone have worked on this before can you share some resources where I can study about this.
Thanks :)

**Comment by okuchaiev** [comment]
no currently NeMo ASR models transcribe 55 as "fifty five". 
In fact, if En normalization is tuned on (default) in data layer, then 55 will be converted to fifty five.

Keep in mind that there could be many valid ways to say, for example, 2020 differently - you can say "two thousands twenty" or "twenty twenty".

**Comment by rohitgr7** [comment]
Hi @okuchaiev thanks for your response. I was thinking that this could be an NLP task rather than expecting ASR to generate such results similar to punctuation and capitalization model where it do some post-processing to the enhance the ASR results.

**Comment by rohitgr7** [comment]
Found a related
paper: https://isca-speech.org/archive/Interspeech_2017/pdfs/1274.PDF
blogpost: https://machinelearning.apple.com/research/inverse-text-normal

but there seems to be no code/pretrained models present for this.

**Comment by yzhang123** [comment]
@rohitgr7 Stay tuned, we are working on this :)
In the meantime, we have released a tool for text normalization, check it out here: https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/tools/Text_Normalization_Tutorial.ipynb

**Comment by rohitgr7** [comment]
@yzhang123 Awesome!! eagerly waiting for this :smiley:

**Comment by yzhang123** [comment]
@rohitgr7  check out this PR https://github.com/NVIDIA/NeMo/pull/1797 :)
Please reopen this issue if you have followup questions

**Comment by rohitgr7** [comment]
thanks, @yzhang123. Will check it out :)

**Comment by yzhang123** [comment]
@rohitgr7 and let us know your feedback, or if anything does not work :)
