### ISSUE TITLE
Is there a tutorial for data augmentation using transfer learning on pretrained QuartzNet?

### ISSUE THREAD

**Issue by catskillsresearch** [NVIDIA/NeMo#1381]
This doc: https://developer.nvidia.com/blog/develop-smaller-speech-recognition-models-with-nvidias-nemo-framework/ mentions that 

> The QuartzNet-15×5 model was trained on the LibriSpeech training dataset with two types of data augmentation: speed perturbation and Cutout

If I transfer-learn the English QuartzNet on another language, is there an easy way to add

- Speed perturbation
- Cutout
- Random background noise

to the training loop?  I know how to do this in MONAI but it's not as clear in the NeMo design whether there are audio transforms that can be added into the training loop, that is, I don't see the equivalent in NeMo of the MONAI Compose and transform loader stack: https://docs.monai.io/en/latest/transforms.html

**Comment by okuchaiev** [comment]
Here is a tutorial on data augmentation https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/05_Online_Noise_Augmentation.ipynb
