### ISSUE TITLE
about japanese

### ISSUE THREAD

**Issue by guijuzhejiang** [NVIDIA/NeMo#1391]
Thank you very much for opening such a good tool. Is nemo effective for Japanese speech recognition?

**Comment by okuchaiev** [comment]
Yes, NeMo is not English-only. You should be able to train good Japanese models if you have Japanese training data. Of course, knowledge of Japanese helps too :)

**Comment by guijuzhejiang** [comment]
> Yes, NeMo is not English-only. You should be able to train good Japanese models if you have Japanese training data. Of course, knowledge of Japanese helps too :)

Thank you for your answer. It seems that there is no automatic speech recognition pre-training model for Japanese
