### ISSUE TITLE
[Question] How do I infer the speaker recognition model/module at 1.0.0b1.

### ISSUE THREAD

**Issue by uditdixit11** [NVIDIA/NeMo#1393]
I have trained a speaker recognition model and save the checkpoints. Even can restore it using the LightningModule.load_from_checkpoint() class method. But couldn't able to perform the next steps after it. 

Please suggest how do I perform the next steps i.e then predict the speaker on unseen data using trained model at  at 1.0.0b1 version ?

**Comment by nithinraok** [comment]
@uditdixit11, 
If you have finetuned or trained all together with a new speaker recognition model, you could test or infer by two steps as shown similarly in [this script](https://github.com/NVIDIA/NeMo/blob/main/examples/asr/speech_to_text_infer.py) . 
1. set up test data and 
2. get log_prob by calling forward loop of trained speaker model. 
If it's confusing let me know, I will add a infer script to current examples.

**Comment by uditdixit11** [comment]
Thanks @nithinraok

Please add the infer script to the current examples. It will be really helpful to us.

**Comment by ShantanuNair** [comment]
@nithinraok  Would appreciate an infer script as well, working on it myself right now.

**Comment by nithinraok** [comment]
Did you try passing test_ds to yaml file to speaker_reco.py by commenting out trainer.fit with your trained .nemo model?

**Comment by nithinraok** [comment]
Anyway will post a script very soon for your reference.

**Comment by nithinraok** [comment]
Somehow missed your response @uditdixit11, please find the script requested at this [PR](https://github.com/NVIDIA/NeMo/blob/afbe52cb726eeb0c8262779299f4cc4354a9625d/examples/speaker_recognition/speaker_reco_infer.py). Let me how it goes. @ShantanuNair

**Comment by JINHXu** [comment]
Hi! It appears in the script setting up test data loader and load from test data is a necessary step, in which process audio data were somehow converted to a tensor and can be passed to the `forward()` function as an argument, I was wondering if there is a way to get around this? For example, I just have a running program that takes input audio streams, might there be a way to process the audio stream to a required tensor form and pass it directly to the `forward()` function without having to write to an intermediate test manifest and load from the test data? Has anyone tried this? Help would be appreciated!

**Comment by nithinraok** [comment]
Yo may look at this discussion to get an idea: https://github.com/NVIDIA/NeMo/discussions/2248

**Comment by JINHXu** [comment]
> You may look at this discussion to get an idea: #2248

Thank you! @nithinraok
