### ISSUE TITLE
[Question] How to train a ASR model finetuned with RIR and noise augmentation, just like `QuartzNet15x5NR-En`?

### ISSUE THREAD

**Issue by Honghe** [NVIDIA/NeMo#1395]
**Describe your question**

How to train a ASR model finetuned with RIR and noise augmentation, just like `QuartzNet15x5NR-En`?

I find that there is a pretrained `QuartzNet15x5NR-En` model on NGC, and a config file for augmentation `/home/jack/a/PycharmProjects/NeMo/examples/asr/experimental/configs/quartznet_15x5_aug.yaml`. 
```
nemo_asr.models.EncDecCTCModel.list_available_models()
Out[2]: 
 PretrainedModelInfo(pretrained_model_name='QuartzNet15x5NR-En', description='QuartzNet15x5Base-En was finetuned with RIR and noise augmentation to make it more robust to noise. This model should be preferred for noisy speech transcription. This model achieves a WER of 3.96% on LibriSpeech dev-clean and a WER of 10.14% on dev-other.', location='https://api.ngc.nvidia.com/v2/models/nvidia/nemospeechmodels/versions/1.0.0a5/files/QuartzNet15x5NR-En.nemo', class_=None),
```
But I can't find the recipe for training the RIR and noise augmented model `QuartzNet15x5NR-En`.
So it will be meaningful if NeMo can provide the the recipe.

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal
 - Method of NeMo install: from source main(75774cf)

**Environment details**

- OS version: Ubuntu 20.04
- PyTorch version: 1.6
- Python version: 3.8

**Comment by jbalam-nv** [comment]
Here are some scripts that can help you create datasets for RIR and noise augmentation:
https://github.com/NVIDIA/NeMo/blob/main/scripts/get_openslr_rir.py (downloads and creates a json manifest for RIRs from openslr)

Some scripts to download noise samples from freesound are here: https://github.com/NVIDIA/NeMo/tree/main/scripts/freesound_download_resample

For training the model, we found fine-tuning a model trained on "clean" data to be quite effective. Here is an example config file that can get you started with training a noise robust model: https://github.com/NVIDIA/NeMo/blob/main/examples/asr/experimental/configs/quartznet_15x5_aug.yaml . Look for "augmentor" settings in this config file.

**Comment by Honghe** [comment]
@jbalam-nv Thanks! And I create a pull request of RIR perturbation example in the tutorial. https://github.com/NVIDIA/NeMo/pull/1429

**Comment by lodm94** [comment]
Hello,
im tryin to implement RIR aug, just like suggested in the [tutorial](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/05_Online_Noise_Augmentation.ipynb
)
But when i run the cell:
```
rir_data_path = '.'
!python ../../scripts/get_openslr_rir.py --data_root {rir_data_path}
rir_manifest_path = os.path.join(rir_data_path, 'processed', 'rir.json')
!head -n 3 {rir_manifest_path}
```
It returns:

```
python3: can't open file '../../scripts/get_openslr_rir.py': [Errno 2] No such file or directory
head: cannot open './processed/rir.json' for reading: No such file or directory

```
So, i downloaded get_openslr_rir.py script manually from [here](https://raw.githubusercontent.com/NVIDIA/NeMo/main/scripts/get_openslr_rir.py)

And the cell to run became:
```
rir_data_path = '.'
!python get_openslr_rir.py --data_root {rir_data_path}
rir_manifest_path = os.path.join(rir_data_path, 'processed', 'rir.json')
!head -n 3 {rir_manifest_path}
```

But still get an error after downloading and extracting the file:

```
INFO:root:

Working on: slr28
INFO:root:Getting slr28
INFO:root:./slr28.zip does not exist. Downloading ...
INFO:root:Downloaded ./slr28.zip.
INFO:root:Extracting slr28
INFO:root:Processing slr28
Traceback (most recent call last):
  File "get_openslr_rir.py", line 139, in <module>
    main()
  File "get_openslr_rir.py", line 133, in main
    os.path.join(os.path.join(data_root, "processed", "rir.json")),
  File "get_openslr_rir.py", line 105, in __process_data
    with open(manifest_file, 'w') as man_f:
FileNotFoundError: [Errno 2] No such file or directory: './processed/rir.json'
head: cannot open './processed/rir.json' for reading: No such file or directory

```

Is this a known issue? Or i'm just bad af and i don't know what to do? I can't even look at how rir manifest are structured. And this is realy important for me to add RiRAug in my ASR pipeline.

Appreciate some help
Thanks in advance

**Comment by Gorodecki** [comment]
@lodm94 Do you have permission to create this folder and file? I was able to download and convert the data without any problems.
