### ISSUE TITLE
Is it possible to export to onnx format?

### ISSUE THREAD

**Issue by dulex123** [NVIDIA/NeMo#141]
How would one go in exporting a model to onnx format? I guess its not supported out of the box, but are there any hints on how to do it since it is probably one module ?

**Comment by dulex123** [comment]
For example jasper model, is it possible to take jasper.get_pytorch_model and use that for onnx export?

**Comment by okuchaiev** [comment]
we might have some announcements on this soon ;) In the meantime have a look at this PR: https://github.com/NVIDIA/NeMo/pull/123

**Comment by dulex123** [comment]
@okuchaiev oh nice. Any docs? I see a module export method but what if like in quartznet's case we have encoder and decoder? How to combine it into one .onnx file?

**Comment by okuchaiev** [comment]
If you are using TRTIS for deployment you should use ensemble feature https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/models_and_schedulers.html#ensemble-models

But going forward we are thinking about adding support automerge of modules

**Comment by laohur** [comment]
> TRTIS

Is there any TRTIS (Triton) example for complex dataflow ?
