### ISSUE TITLE
Segmentation fault (core dumped) when set create_tb_writer=True

### ISSUE THREAD

**Issue by caohongnga** [NVIDIA/NeMo#1416]
Dear all,
I have following problem when I run speech2text file:

**Setup NeuralModuleFactory to control training nf = nemo.core.NeuralModuleFactory( create_tb_writer=True, ...)*
The system will raise an error: 
################################################################################
################################################################################

Segmentation fault (core dumped)
**Environment overview (please complete the following information)**

 - Environment location: anaconda, nemo v0110
 - Method of NeMo install: pip install nemo_toolkit[all]

**Environment details**

Otherwise, please provide:
- OS version: Ubuntu 16.04.5 LTS
- PyTorch version: pytorch 1.6.0
- Python version: Python 3.7.7

**Additional context**
CUDA Version: 10.1
GPU: GeForce GTX 1080

Please show me where was wrong!  
Thank you very much!
Cao Hong Nga

**Comment by ericharper** [comment]
Thanks for the issue. Please upgrade your version of NeMo to 1.0.0b*.

See https://github.com/NVIDIA/NeMo/issues/1091 for a discussion on what has changed.
