### ISSUE TITLE
ASR Post Processing with language model with new Nemo version

### ISSUE THREAD

**Issue by sl1msa1d** [NVIDIA/NeMo#1417]
How can we deploy ASR post processing on the new Nemo Version 1.0.0b1 ?
I found this [tutorial](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/v0.11.0/nlp/asr-improvement.html#asr-improvement) and this [page](https://github.com/NVIDIA/NeMo/tree/fa68d336cfefbbbb1849ff1b6ef454149f45234d/examples/nlp/asr_postprocessor) but they don't seem to work with the new Nemo Version

**Environment overview (please complete the following information)**

 - Environment location: Bare-Metal with GPU / GCP
 - Method of NeMo install: pip install

**Environment details**

- OS version: Ubuntu 20.04.1 LTS
- PyTorch version : 1.6
- Python version:  Python 3.7.6

**Comment by okuchaiev** [comment]
sorry this feature have not been ported yet.

**Comment by rohitgr7** [comment]
@okuchaiev is it wip or will take some time?

**Comment by titu1994** [comment]
This is available in Nemo. Please refer to Nemo docs for ASR Language Modelling.
