### ISSUE TITLE
VAD offline inference 

### ISSUE THREAD

**Issue by 4nton-P** [NVIDIA/NeMo#1424]
Hello!
I ran into the VAD Inference problem. I cannot use offline inference if I do not have an output or input of a device, because the pyaudio requires a device. Are there any solutions?
I just want to feed a track into the model and get a predicted time. To do this, I'll just rewrite the callback function, but how to get around the problem with the lack of devices?

**Comment by fayejf** [comment]
Hello @4nton-P 

- I just want to feed a track into the model and get a predicted time. To do this, I'll just rewrite the callback function, but how to get around the problem with the lack of devices?
It is designed for the demonstration in the tutorial you don't have to use it to do inference for VAD.

We're updating the inference pipeline here`https://github.com/NVIDIA/NeMo/pull/1384` and will be updated and merged soon. It will help you to perform **AUDIO -> MANIFEST -> VAD OUTPUT TXT -> VAD RTTM-like TABLE**

I will let you know once it merged. Hope it helps.

**Comment by 4nton-P** [comment]
> Hello @4nton-P
> 
> * I just want to feed a track into the model and get a predicted time. To do this, I'll just rewrite the callback function, but how to get around the problem with the lack of devices?
>   It is designed for the demonstration in the tutorial you don't have to use it to do inference for VAD.
> 
> We're updating the inference pipeline here`https://github.com/NVIDIA/NeMo/pull/1384` and will be updated and merged soon. It will help you to perform **AUDIO -> MANIFEST -> VAD OUTPUT TXT -> VAD RTTM-like TABLE**
> 
> I will let you know once it merged. Hope it helps.

Thanks, I'll wait

**Comment by fayejf** [comment]
@4nton-P  The PR is merged. Feel free to play with the scripts. Questions and feedbacks are very welcome!
I'm closing this issue. Please reopen or open a new one with questions. Thanks!
