### ISSUE TITLE
[Question] How may i save the model to my own file in colab?

### ISSUE THREAD

**Issue by 181473h** [NVIDIA/NeMo#1427]
After running trainer.fit(model_from_scratch) i see that the models are actually saved in 

" Epoch 0: val_loss reached 0.38735 (best 0.38735), saving model to /content/nemo_experiments/token_classification_model/2020-11-07_03-05-01/checkpoints/token_classification_model---val_loss=0.39-epoch=0.ckpt as top 3"

How can I access this model or save it into my own local file (training_session_folder)?

I need to use the model to pass in a text file and predict the labels

p.s. I'm a beginner pls help T.T
![gi1](https://user-images.githubusercontent.com/45226851/98432545-3d762d80-20fa-11eb-94a5-b632a846d481.PNG)
![gi2](https://user-images.githubusercontent.com/45226851/98432548-3f3ff100-20fa-11eb-8eee-baf372b8537f.PNG)

**Comment by titu1994** [comment]
You can use google.colab library to download files off of google colab - https://stackoverflow.com/questions/48774285/how-to-download-file-created-in-colaboratory-workspace.

Instead of `example.txt` in that snippet, you can provide the full path to the checkpoint instead and it should (hopefully) download the file to your local drive.

**Comment by 181473h** [comment]
Sorry I think what I meant to say is to save a copy of the model into training_session_folder on google colab as it by default does into nemo_experiments

**Comment by titu1994** [comment]
For that, you can change the experiment manager config - the `exp_dir` to be precise. Set the exp_dir to your training path and it should save model checkpoints there.

**Comment by 181473h** [comment]
![gh1](https://user-images.githubusercontent.com/45226851/98622686-03e53280-2345-11eb-87f8-572f47284df4.PNG)
i did this not sure if it is correct

**Comment by titu1994** [comment]
Sure that's fine too, but you want a file name inside model_file, so it should be `/content/training_session_folder/ner_model.pt`

**Comment by titu1994** [comment]
You can more easily just use model.save_to(model_file) and then use TokenClassificationModel.restore_from(model_file) for more easy saving and restoring of Nemo models.

**Comment by 181473h** [comment]
okay thank you so much for replying, really appreciate your help!!
