### ISSUE TITLE
[Question] Difference between `blank` and `space` character in ASR quartznet?

### ISSUE THREAD

**Issue by ORlGlN** [NVIDIA/NeMo#1428]
How to differentiate the meaning of these two characters? Which one represents silence, gap for next word or the end of word? Thanks in advance :)

**Comment by vsl9** [comment]
`space` character is a regular delimiter between words [` `]. Usually, it is also returned for silent segments. 
`blank` symbol is a special extra character in CTC modeling that allows representing double characters, for example. It is removed from final decoded transcript. More details could be found in the following great paper: https://distill.pub/2017/ctc/ .

**Comment by ORlGlN** [comment]
That's very helpful, thanks
