### ISSUE TITLE
Add support / option for ASR audio streaming

### ISSUE THREAD

**Issue by rinjac** [NVIDIA/NeMo#143]
Currently, the ASR collection is supporting audio files as an input for training and prediction. However, a lot of ASR uses involve **streaming audio** for prediction.  In streaming, the bytes of audio are sent in intervals. It would be useful to have an option in relevant classes (AudioToTextDataLayer and others) to **accept bytes** (and not just path to audiofile/files) as an input. Then, using NeMo-ASR models for streaming would be possible.

Is there a plan to add this?

**Comment by okuchaiev** [comment]
@vsl9 ^^

**Comment by carlfm01** [comment]
Hello @okuchaiev , any update?

**Comment by seovchinnikov** [comment]
https://github.com/NVIDIA/NeMo/blob/master/examples/asr/notebooks/2_Online_ASR_Microphone_Demo.ipynb

**Comment by sunilpro** [comment]
> https://github.com/NVIDIA/NeMo/blob/master/examples/asr/notebooks/2_Online_ASR_Microphone_Demo.ipynb

Did you get it to work with CPU backend?

**Comment by okuchaiev** [comment]
closing as this is related to the old version
