### ISSUE TITLE
[Question] ASR Correction output

### ISSUE THREAD

**Issue by amejri** [NVIDIA/NeMo#1436]
Hello, 

I'm trying to train ASR models for different languages. The problem is that the output contains many mistakes. Do you have any idea to correct them.

Thanks in advance,
Sincerely.

**Comment by okuchaiev** [comment]
The best bet it to train on more data.
If you do not have more data, then try fine-tuning from pretrained model (even from another language) by re-using acoustic encoder.
And, of course, you will need to play/experiment with hyperparameters
