### ISSUE TITLE
Confidence measures for Quartznet predictions

### ISSUE THREAD

**Issue by jonaskratochvil** [NVIDIA/NeMo#1463]
Hello, 

I am interested in getting the word level confidences from Quartznet model. What would be the best approach to obtain some proxy values to word level confidences? Taking the logit sequences and normalizing them by length seems like the most straight forward approach but I am not sure how reliable this would be. Any suggestions or ideas would be appreciated.

**Comment by LordOfLuck** [comment]
I would also be interested in this

**Comment by Omarnabk** [comment]
I am interested in this as well. 
For now, I'm using a simple approach by averaging the confidence score of each letter per word, resulting in a confidence score per word.
You can use [parlance](https://github.com/parlance/ctcdecode) to get a timestamp per letter with the beam search.

**Comment by Vishaal-MK** [comment]
> I am interested in this as well.
> For now, I'm using a simple approach by averaging the confidence score of each letter per word, resulting in a confidence score per word.
> You can use [parlance](https://github.com/parlance/ctcdecode) to get a timestamp per letter with the beam search.

How do you get the confidence score of each letter?

**Comment by Omarnabk** [comment]
> > I am interested in this as well.
> > For now, I'm using a simple approach by averaging the confidence score of each letter per word, resulting in a confidence score per word.
> > You can use [parlance](https://github.com/parlance/ctcdecode) to get a timestamp per letter with the beam search.
> 
> How do you get the confidence score of each letter?
averaging the score config score per letter

**Comment by titu1994** [comment]
We don't support this yet, but we will let you know if we add support in the future.
