### ISSUE TITLE
[Question] example of ConformerEncoder class 

### ISSUE THREAD

**Issue by Omarnabk** [NVIDIA/NeMo#1475]
Are you going to provide examples on how to use the newly added ASR decoders, like ConformerEncoder?

**Comment by VahidooX** [comment]
You may use this example to use the Conformer encoder with CTC-loss:
https://github.com/NVIDIA/NeMo/blob/main/examples/asr/experimental/conformer/conformer_linear_decoder_bpe.yaml

We have the plan to release some checkpoints trained with Confomer-CTC in our next release in March, maybe even Conformer-RNNT.
