### ISSUE TITLE
[Question] How can I predict the class for a wav file for an EncDecClassificationModel object?

### ISSUE THREAD

**Issue by toonday** [NVIDIA/NeMo#1482]
I need the equivalent of transcribe function of EncDecCTCModel objects for EncDecClassificationModel objects.

The current implementation seems to only taken into batch of wav files and its quite confusing to follow along.

**Comment by titu1994** [comment]
PR https://github.com/NVIDIA/NeMo/pull/1497 addresses this. I'll update here once it's merged.

**Comment by titu1994** [comment]
This is merged now, closing issue. Please let us know if the solution is insufficient for your requirements
