### ISSUE TITLE
[Question]Token_Classification_NER output with model_from_scratch.evaluate_from_file

### ISSUE THREAD

**Issue by 181473h** [NVIDIA/NeMo#1484]
How do I let `evaluate_from_file` read into my entire text file and produce the output?

`model_from_scratch.evaluate_from_file(
    text_file= 'Imported_data.txt',
    output_dir='.',
)`

Apparently, it's only reading the first line of my text file as shown below.

![importText](https://user-images.githubusercontent.com/45226851/99944804-7840bc80-2dae-11eb-8379-35193ea74676.PNG)
![exportText](https://user-images.githubusercontent.com/45226851/99944797-770f8f80-2dae-11eb-9419-46cb254d67a2.PNG)

**Comment by ekmb** [comment]
The intended usage of the `evaluate_from_file()` is to run the final evaluation. The predictions for all examples are stored in a single line.

It's recommended to use `get_predictions()`.  Note, each word in the input sequence could be split into one or more tokens. In our implementation, the prediction for the first token of the input was used to label the whole word. 

[PR 1487](https://github.com/NVIDIA/NeMo/pull/1487/files) modified `get_predictions()` to read the input from a file and save the inference result, usage:
`model.add_predictions('Imported_data.txt', output_file='Exporting_data.txt')`

Please pull from the latest main to see the changes.

**Comment by 181473h** [comment]
@ekmb This was what I got,
`add_predictions() got an unexpected keyword argument 'output_file'`

And also if I may ask,
```
model_from_scratch.evaluate_from_file(
    text_file= 'Imported_data.txt',
    output_dir='.',
)
os.rename('/content/infer_Imported_data.txt', '/content/Exporting_data.txt')
```
only returns me a set of labels in a single line from the first line of the input file. It doesn't give me labels for lines 2 to 10 from the input file.
