### ISSUE TITLE
[Question] : Docker image  nvcr.io/nvidia/nemo:v1.0.0b2 not found

### ISSUE THREAD

**Issue by harrypotter90** [NVIDIA/NeMo#1495]
Docker image "v1.0.0b2 not found"

Error message:

docker pull nvcr.io/nvidia/nemo:v1.0.0b2
Error response from daemon: manifest for nvcr.io/nvidia/nemo:v1.0.0b2 not found: manifest unknown: manifest unknown

**Comment by harrypotter90** [comment]
on the same machine, it works for "nvcr.io/nvidia/nemo:v1.0.0b1 "

**Comment by okuchaiev** [comment]
closing as duplicate of https://github.com/NVIDIA/NeMo/issues/1498
