### ISSUE TITLE
Docker image "v1.0.0b2 not found"

### ISSUE THREAD

**Issue by harrypotter90** [NVIDIA/NeMo#1498]
Docker image "v1.0.0b2 not found"

Error message:

docker pull nvcr.io/nvidia/nemo:v1.0.0b2
Error response from daemon: manifest for nvcr.io/nvidia/nemo:v1.0.0b2 not found: manifest unknown: manifest unknown

**Comment by redoctopus** [comment]
The docker image has been published and should be available now.
