### ISSUE TITLE
How to get encoder output as audio feature?

### ISSUE THREAD

**Issue by pooyafayyaz** [NVIDIA/NeMo#1507]
Hi all,
How can I get the encoder part output in NeMo? Basically, I'm assuming that this part extracts audio features from the raw sample. I'm trying to do some sentiment analysis with those audio features. However, the examples provided use the whole encoder-decoder pipeline. Thanks in advance.

**Comment by titu1994** [comment]
Both EncDecCTCModel and it's bpe counterpart are pytorch modules - so you will need to write your own function that is based off of the validation_step method inside these two models.
