### ISSUE TITLE
Broken tokenizer ref in AbstractRNNTDecoding in rnnt_wer.py 

### ISSUE THREAD

**Issue by many-hats** [NVIDIA/NeMo#1520]
**Describe the bug**

On [line 209 of rnnt_wer.py](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/metrics/rnnt_wer.py#L209) there is a reference to `self.tokenizer.ids_to_text(prediction)` which errors out because there is no tokenizer. This blocks the example script in speech_to_text_rnnt.py below at the validation/sanity check stage. Possibly an artifact of refactoring for BPE? What is the intended NeMo way of incorporating the tokenizer?

I changed self.tokenizer to an explicitly defined CharTokenizer and it fixed the error. 

**Steps/Code to reproduce bug**

```
        python examples/asr/speech_to_text_rnnt.py \
        model.train_ds.manifest_filepath="<path to train dataset>" \
        model.validation_ds.manifest_filepath="<path to validation dataset>" \
        trainer.gpus=0 \
        trainer.max_epochs=50
```

**Expected behavior**

Sanity check run of RNN-T.

**Comment by titu1994** [comment]
Yup that's a bug during the refactor, I'll send a patch in sometime.

**Comment by titu1994** [comment]
Added a PR, it might take some time to get merged so you could update the code locally in the mean time. 

Btw, just a heads up. The configs for RNNT are just template references for Librispeech - they were not trained nor validated on Librispeech. AN4 has a different token set compared to librispeech (no special characters, no numbers etc) so the `model.labels` would need to be updated for AN4.

**Comment by many-hats** [comment]
Great! Thanks for the heads up.
