### ISSUE TITLE
Questions about the performance of ASR augmentation

### ISSUE THREAD

**Issue by iamxiaoyubei** [NVIDIA/NeMo#1547]
Thank you for sharing the valuable [ASR augmentation code](https://github.com/NVIDIA/NeMo/blob/08d1ccc503e35796e2874b24eca677e9eebad71c/nemo/collections/asr/parts/perturb.py#L596) recently. I would like to ask what is the result of your experiment with these different perturbations. Have you ever done an ablation study on all of the perturbations? Can you share the results with us?

**Comment by titu1994** [comment]
Some details can be found here - https://arxiv.org/abs/2010.12715
