### ISSUE TITLE
[Question] Running Nemo with no internet

### ISSUE THREAD

**Issue by gtcooke94** [NVIDIA/NeMo#1550]
I'm trying to run nemo with no internet connection - the import statements take quite a long time. I've been digging through the files files to see where, if any, of them are trying to do some kind of `ping` or `curl` on module level, but I haven't found it yet.
If this is the case, do you know where it happens? I can't think of any other reason why it takes so long without an internet connection.

Using the Nemo v1.0.0b2 container.

**Comment by nithinraok** [comment]
what is the task or example you were trying to run? Did you first run with internet data and then later without internet? Some examples where we fetch model from NGC needs to be run with the internet, probably your example got stuck there.
