### ISSUE TITLE
[Question] How to setup exp_manager

### ISSUE THREAD

**Issue by edward15241** [NVIDIA/NeMo#1553]
Question:
    I setup the config.yaml  and run the script. It thorw this message

"The pytorch lightning trainer that was passed to exp_manager contained a logger, and either "
nemo.utils.exp_manager.LoggerMisconfigurationError: The pytorch lightning trainer that was passed to exp_manager contained a logger, and either create_tensorboard_logger: True or create_wandb_logger: False was set to True. These can only be used if trainer does not already have a logger. You can disable lightning's trainer from creating a logger by passing logger=False to its constructor. "

I have disabled the logger in trainer. but it still has this message.  and I saw the code in "nemo/utils/exp_manager.py"
it will throw above following message if trainer is not None . However, I have set the logger to be False in config.yaml . Then, print the 
"logger" in trainer. It shows the object "<pytorch_lightning.loggers.base.LoggerCollection object at 0x7f41b5538550>"

How to disable logger and use exp_manager.py? 

**My yaml configuration (in attached file)** 

**trainer:**
  gpus: 1
  max_epochs: 150
  max_steps: null
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: **False**
  logger: null
  row_log_interval: 1
  val_check_interval: 0.25

**exp_manager:**
  exp_dir: 
  name: 
  use_datetime_version: **True**
  create_tensorboard_logger: **True**
  create_checkpoint_callback: **True**
  checkpoint_callback_params:
    monitor: "val_wer"
    mode: "min"
  
  create_wandb_logger: **False** 
  wandb_logger_kwargs:
    name: 
    project:

**Environment overview (please complete the following information)**

 - Environment location:  Ubuntu 16.04 + python virtual env (python 3.7)
 - Method of NeMo install:  pip installation [1.0.0.b2]

**Environment details**
python == 3.7.0
torch == 1.7.0

[quartznet_5x3_cer_single.zip](https://github.com/NVIDIA/NeMo/files/5686333/quartznet_5x3_cer_single.zip)

**Comment by blisc** [comment]
Can you share your training command? As well as the python file that you're using?

**Comment by edward15241** [comment]
Sorry, It is my fault. I found that I was not pass parameter correctly to trainer, so it use default configuration. And solved this problem. I saw the example in "speech_to_text.py" and found I should pass parameters separately not a config dictionary)

pl = trainer(configDict(params['trainer']))   ## original (wrong way)

pl = trainer(gpus=params['trainer']['gpus'], amp_level=params['trainer']['amp_level'], ...)  ## correct way

 Thank you :)

**Comment by blisc** [comment]
Does the default `trainer = pl.Trainer(**cfg.trainer)` not work for you? What happens if you do `pl = trainer(**params['trainer'])`?

Closing for now as well since it seems to be resolved.

**Comment by edward15241** [comment]
Yes, I test it and the two way you mentioned does work if using hydra decorator on function. Because i need to do some pre-processing for script before training  I remove the decorator and need to pass all parameter separately.  

Thanks :)
