### ISSUE TITLE
Tacotron2 bug when batch dimension is 1

### ISSUE THREAD

**Issue by ctlaltdefeat** [NVIDIA/NeMo#1556]
**Describe the bug**

Training (or just passing input with ground-truth spectrogram) Tacotron2 with a batch dimension of 1 does not work due to a dimension problem when aggregating the gate outputs.

The line here
https://github.com/NVIDIA/NeMo/blob/d01b7bbc3fdb1bbf14789f71b8f368cf0aa8f86b/nemo/collections/tts/modules/tacotron2.py#L256
should have ```unsqueeze``` instead of ```squeeze``` when the batch dimension is 1.

(I didn't want to submit a pull request as I'm not familiar with the conventions of the project)

**Comment by blisc** [comment]
Thanks for catching this bug. It should be fixed now
