### ISSUE TITLE
Docker image "v1.0.0b3 not found"

### ISSUE THREAD

**Issue by lazystone** [NVIDIA/NeMo#1560]
**Steps/Code to reproduce bug**

```bash
docker pull nvcr.io/nvidia/nemo:v1.0.0b3
Error response from daemon: manifest for nvcr.io/nvidia/nemo:v1.0.0b3 not found: manifest unknown: manifest unknown
```

Similar to #1498

**Comment by rbracco** [comment]
Do you mean v1.0.0b2? I haven't seen a b3 version yet, but there is a branch called r1.0.0b3.

**Comment by lazystone** [comment]
Well, I assumed since there is [v1.0.0b3](https://github.com/NVIDIA/NeMo/releases/tag/v1.0.0b3) release, then is should be docker image for that version.

**Comment by rbracco** [comment]
Sorry, I missed the 1.0.0b3 release, you are correct! In the [v1.0.0b3 README](https://github.com/NVIDIA/NeMo/tree/v1.0.0b3) there appear to be updated instructions but it appears your command is correct so the docker container is indeed missing. I was unable to retrieve it as well. 

![image](https://user-images.githubusercontent.com/47190785/102230326-bf583400-3eba-11eb-803f-f30cf7b1bd4f.png)

**Comment by redoctopus** [comment]
Try pulling `nvcr.io/nvidia/nemo:1.0.0b3`, it should be live now.
