### ISSUE TITLE
Text_Classification_Sentiment_Analysis tutorial is broken

### ISSUE THREAD

**Issue by kshitizgupta21** [NVIDIA/NeMo#1572]
Getting `ModuleNotFoundError: No module named 'transformers.tokenization_bert'` in Text_Classification_Sentiment_Analysis.ipynb notebook:

![image](https://user-images.githubusercontent.com/73861554/102413997-a5961a00-3faa-11eb-8a16-432fccb43eca.png)

**Comment by ekmb** [comment]
Could you please try with `BRANCH='main'` in the first cell of the notebook.

**Comment by kshitizgupta21** [comment]
@ekmb Tried `BRANCH='main'` but still getting the same error

**Comment by kshitizgupta21** [comment]
I forgot to restart the kernel when trying `BRANCH='main'`. So I restarted the kernel and tried `from nemo.collections import nlp as nemo_nlp` and the original `ModuleNotFoundError: No module named 'transformers.tokenization_bert'` has gone away but there is a different `ModuleNotFoundError: No module named 'webdataset'`: 
![image](https://user-images.githubusercontent.com/73861554/102415438-01fa3900-3fad-11eb-99d9-5a85397dfa81.png)

**Comment by ekmb** [comment]
Could you please restart the kernel and run this one:

BRANCH = 'main'
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[all]

**Comment by kshitizgupta21** [comment]
Tried it and it seems like it's fixed now. Not getting any more errors. There are two APEX warnings though:

![image](https://user-images.githubusercontent.com/73861554/102417301-43401800-3fb0-11eb-98f1-fb15688cbad5.png)

**Comment by ekmb** [comment]
@kshitizgupta21 the warnings are OK (Colab doesn't have APEX).
