### ISSUE TITLE
[Question] Best WAV length for fine-tuning

### ISSUE THREAD

**Issue by Omarnabk** [NVIDIA/NeMo#1585]
I'm working on finetuning the ASR to adapt to a specific domain. I am using the CTC segmentation tool ([here](https://github.com/NVIDIA/NeMo/tree/main/tools/ctc_segmentation)) to produce the training data. The wave lengths vary between 2 minutes to 2 seconds. I'm wondering what is the best wave length to use (or range of length to use).

Thanks!

**Comment by titu1994** [comment]
A maximum of 16-20 seconds is recommended for ASR training. Anything more than that will reduce batch size and reduce training efficiency too much
