### ISSUE TITLE
[Question] Instantiate ASR model from scratch

### ISSUE THREAD

**Issue by lodm94** [NVIDIA/NeMo#1586]
Hi all,
I wish to instantiate a brand new ASR Quartznet 15x5 from a .yaml file and train it from scratch.
Actually, what i'm tryin to do is what is shown in 01_ASR_with_Nemo tutorial:

`first_asr_model = nemo_asr.models.EncDecCTCModel(cfg=DictConfig(params['model']), trainer=trainer)`

Even just running the tutorial cell by cell, the following ValueError is returned:

`num_samples should be a positive integer value, but got num_samples=0`

What's wrong? I appreciate your help. Sorry if the question may sound silly.
Thanks

 - Environment location: Google Colab
 - Method of NeMo install: pip install

**Comment by nithinraok** [comment]
what is the manifest file you instantiated with?
