### ISSUE TITLE
[Question] Question about STFT parameter

### ISSUE THREAD

**Issue by amejri** [NVIDIA/NeMo#1588]
Hello, 
I have a question about one parameter used in the config file of quartznet model. Can someone tell me what is the purpose of stft_conv parameter? in the config file it's set to False.
![image](https://user-images.githubusercontent.com/45438779/103083820-aef03980-45dd-11eb-9879-86108b002205.png)
With kind regards.

**Comment by redoctopus** [comment]
It's somewhat misleadingly named.
```
stft_conv (bool): If True, uses pytorch_stft and convolutions. If False, uses torch.stft. Defaults to False.
```
