### ISSUE TITLE
TypeError: stft() got an unexpected keyword argument 'return_complex'

### ISSUE THREAD

**Issue by emrakul** [NVIDIA/NeMo#1590]
Seems like a problem in a feature extractror module. Training doesn't start, until I comment out line containing that keyword

**Steps/Code to reproduce bug**

start the basic ASR training

 - Environment location: DGX-1
 - Method of NeMo install: pip install -e 

Ubuntu
Torch '1.6.0'
Python 3.76
Ubuntu 18.04.4 LTS"

**Comment by emrakul** [comment]
https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/features.py#L269

**Comment by okuchaiev** [comment]
if you change to torch>=1.7.0 this should no longer be an issue

**Comment by emrakul** [comment]
yes

**Comment by dsidlo** [comment]
I had the issue when using Anaconda Python, but error after switching over to Linux installed python.
