### ISSUE TITLE
RNN-T: Strange type in forward LSTMDropout

### ISSUE THREAD

**Issue by Oktai15** [NVIDIA/NeMo#1591]
https://github.com/NVIDIA/NeMo/blob/297a8bdbb0370a51cb74a41288025befd9cd2392/nemo/collections/common/parts/rnn.py#L196

@titu1994, why does `h` have this type? I suppose it should be `Optional[[Tuple[torch.Tensor, torch.Tensor]]`, just like returnable `h`

**Comment by titu1994** [comment]
Good catch. I was trying our a few things with decoupled lstms and forgot to update signature.
