### ISSUE TITLE
error while importing nlp from nemo

### ISSUE THREAD

**Issue by rahul-art** [NVIDIA/NeMo#1623]
nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Unzipping corpora/cmudict.zip.

[NeMo W 2021-01-12 07:16:18 experimental:28] Module nemo.collections.asr.data.audio_to_text.AudioToCharDataset is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2021-01-12 07:16:18 experimental:28] Module nemo.collections.asr.data.audio_to_text.AudioToBPEDataset is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2021-01-12 07:16:18 experimental:28] Module nemo.collections.asr.data.audio_to_text.AudioLabelDataset is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2021-01-12 07:16:18 experimental:28] Module nemo.collections.asr.data.audio_to_text.TarredAudioToTextDataset is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2021-01-12 07:16:18 experimental:28] Module nemo.collections.asr.data.audio_to_text.TarredAudioToCharDataset is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2021-01-12 07:16:18 experimental:28] Module nemo.collections.asr.data.audio_to_text.TarredAudioToBPEDataset is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2021-01-12 07:16:23 experimental:28] Module <class 'nemo.collections.asr.losses.ctc.CTCLoss'> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo W 2021-01-12 07:16:23 experimental:28] Module <class 'nemo.collections.asr.data.audio_to_text_dali.AudioToCharDALIDataset'> is experimental, not ready for production and is not fully supported. Use at your own risk.
################################################################################
################################################################################

[NeMo W 2021-01-12 07:16:23 nemo_logging:349] /usr/local/lib/python3.6/dist-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
      '"sox" backend is being deprecated. '
    

---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-3-424875f6207b> in <module>()
      1 import nemo.collections.asr as nemo_asr
----> 2 import nemo.collections.nlp as nemo_nlp
      3 import nemo.collections.tts as nemo_tts

3 frames

/usr/local/lib/python3.6/dist-packages/nemo/collections/nlp/data/question_answering_squad/qa_squad_processing.py in <module>()
     20 
     21 from tqdm import tqdm
---> 22 from transformers.tokenization_bert import BasicTokenizer
     23 
     24 from nemo.collections.nlp.data.data_utils import DataProcessor, is_whitespace, normalize_answer

ModuleNotFoundError: No module named 'transformers.tokenization_bert'

**Comment by yzhang123** [comment]
@rahul-art  should be fixed now
