### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kumbachamushroom** [NVIDIA/NeMo#1624]
**How to extract embeddings from a specific portion of audio?**

I have audio files which contain speech from two different individuals, I want to use the pre-trained SpeakerNet_verification model to extract speaker embeddings of each audio file in a sliding window fashion (an embedding for every 1 second with 0.1 seconds overlap). Since the manifest file only accepts the absolute path to the audio is there a way to specify which chunk of audio the model should embed? 

What would be the easiest way to implement this? Alternatively, if I wish to add such a functionality myself, where can I start?

**Comment by nithinraok** [comment]
It is implemented for a WIP project now, It could be done using collate func to slice the batches and combine back them by backtracking the values. 

For reference see here:
https://github.com/NVIDIA/NeMo/blob/df360cd3c856c645d23505305ee8b689636b2dd1/nemo/collections/asr/data/audio_to_label.py#L161

And we capture outputs here:
https://github.com/NVIDIA/NeMo/blob/df360cd3c856c645d23505305ee8b689636b2dd1/nemo/collections/asr/models/label_models.py#L407
