### ISSUE TITLE
[Question] MatchboxNet and MarbleNet

### ISSUE THREAD

**Issue by seekingdeep** [NVIDIA/NeMo#1633]
Hi there,
@fayejf @titu1994 @borisgin

In the task of Voice Activity Detection, the following questions arise:
- After training the Voice Activity Detection model, How to deploy it for inferencing on arm based devices such as Raspberry Pi?
- How much memory is required to inference MatchboxNet
- How does MatchboxNet perform against MarbleNet

**Comment by titu1994** [comment]
> After training the Voice Activity Detection model, How to deploy it for inferencing on arm based devices such as Raspberry Pi?

We dont have deployment scripts for Raspberry Pi. 

> How much memory is required to inference MatchboxNet

Depends on deployment framework, but it should be small considering the size of the model. 

> How does MatchboxNet perform against MarbleNet

They perform two different (but similar tasks) so they cant be compared directly. Matchboxnet is meant for speech command recognition - multiclass classification problem and Marblenet is meant for voice activity detection - binary classification problem.

**Comment by seekingdeep** [comment]
- For the Voice Activity Detection task, the deployment to ARM-based devices is vital and should be considered.
- isn't Matchboxnet currently used for VAD?
