### ISSUE TITLE
Key 'params' is not in struct

### ISSUE THREAD

**Issue by Faizan-Pirhoalpha** [NVIDIA/NeMo#1643]
I try to run the [offline colab notebook](https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0b3/tutorials/asr/Offline_ASR.ipynb#scrollTo=8qgXHl78WneK).

Without changing anything I run cells and get error while running this line `labels = list(asr_model.cfg.decoder.params.vocabulary) + ['blank']:` 
Error:
![image](https://user-images.githubusercontent.com/76702393/104902439-c2a47b00-59a4-11eb-99c4-9e54e1e93b14.png)

**Comment by titu1994** [comment]
You don't need the decoder.params.vocabulary anymore. Directly use decoder.vocabulary

**Comment by Faizan-Pirhoalpha** [comment]
Yes this solves the issue thanks
