### ISSUE TITLE
Quartznet RIR augmentation - tutorial 05

### ISSUE THREAD

**Issue by lodm94** [NVIDIA/NeMo#1648]
Hello,
im tryin to implement RIR aug, just like suggested in the [tutorial](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/05_Online_Noise_Augmentation.ipynb
)
But when i run the cell:
```
rir_data_path = '.'
!python ../../scripts/get_openslr_rir.py --data_root {rir_data_path}
rir_manifest_path = os.path.join(rir_data_path, 'processed', 'rir.json')
!head -n 3 {rir_manifest_path}
```
It returns:

```
python3: can't open file '../../scripts/get_openslr_rir.py': [Errno 2] No such file or directory
head: cannot open './processed/rir.json' for reading: No such file or directory

```
So, i downloaded get_openslr_rir.py script manually from [here](https://raw.githubusercontent.com/NVIDIA/NeMo/main/scripts/get_openslr_rir.py)

And the cell to run became:
```
rir_data_path = '.'
!python get_openslr_rir.py --data_root {rir_data_path}
rir_manifest_path = os.path.join(rir_data_path, 'processed', 'rir.json')
!head -n 3 {rir_manifest_path}
```

But still get an error after downloading and extracting the file:

```
INFO:root:

Working on: slr28
INFO:root:Getting slr28
INFO:root:./slr28.zip does not exist. Downloading ...
INFO:root:Downloaded ./slr28.zip.
INFO:root:Extracting slr28
INFO:root:Processing slr28
Traceback (most recent call last):
  File "get_openslr_rir.py", line 139, in <module>
    main()
  File "get_openslr_rir.py", line 133, in main
    os.path.join(os.path.join(data_root, "processed", "rir.json")),
  File "get_openslr_rir.py", line 105, in __process_data
    with open(manifest_file, 'w') as man_f:
FileNotFoundError: [Errno 2] No such file or directory: './processed/rir.json'
head: cannot open './processed/rir.json' for reading: No such file or directory

```

Is this a known issue? Or i'm just bad af and i don't know what to do? I can't even look at how rir manifest are structured. And this is realy important for me to add RiRAug in my ASR pipeline.

Appreciate some help
Thanks in advance

**Comment by jbalam-nv** [comment]
@lodm94 The issue here is that the script get_openslr_rir.py only works with absolute paths. 
Please change the first line in the cell to:
`rir_data_path = os.getcwd()`
I will fix this in the main branch too. Thanks for letting us know of this issue.

**Comment by lodm94** [comment]
Holy moly it finally works! Cheers man! Thank you
When fixing the main branch, consider that
`!python ../../scripts/get_openslr_rir.py --data_root {rir_data_path}`
returns error. I had to wget the script and change this path.
