### ISSUE TITLE
Key 'window_stride' is not in struct

### ISSUE THREAD

**Issue by shfaizan** [NVIDIA/NeMo#1649]
I am trying to run the[ VAD notebook](https://github.com/NVIDIA/NeMo/blob/9aa4ada92b2e6ddd418704dc392e8576d44e5f41/tutorials/asr/07_Online_Offline_Microphone_VAD_Demo.ipynb). 

I followed every step but got this error:
![image](https://user-images.githubusercontent.com/39994105/105074869-f4a20400-5aae-11eb-85f0-6512c0f56d2a.png)

**Comment by fayejf** [comment]
Thanks for reporting this. We will fix it asap and let you know.

**Comment by fayejf** [comment]
@shfaizan  [Fixed](https://github.com/NVIDIA/NeMo/pull/1659)! Please pull and update. Thanks!
