### ISSUE TITLE
[Question]Google Colab Error: MisconfigurationException: You requested GPUs: [1] But your machine only has: [0] 

### ISSUE THREAD

**Issue by michael-so** [NVIDIA/NeMo#1653]
Hi, I am a beginner in ASR technology and I am currently studying more about this field using your tutorial from this link: 
https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/asr/01_ASR_with_NeMo.ipynb

I was running the codes in your notebook, everything was fine until it reaches the "**Transfer Learning**" section, on the part where it asks to fine-tune the model for 2 epochs on AN4 dataset, I have stumbled on an error from this part of the code(bolded):

_#And now we can create a PyTorch Lightning trainer and call `fit` again.
**trainer = pl.Trainer(gpus=[1], max_epochs=2)
trainer.fit(quartznet)**_

The error was:

MisconfigurationException: 
                You requested GPUs: [1]
                But your machine only has: [0]

I am running the notebook on Colab and not locally, and there were no changes made on any part of the code. It was just me running cells to study. The runtime type has already been changed to GPU and it was a success on the "**Training with PyTorch Lightning**" section but not for **Transfer Learning**.

I would like to know what may be the reason for this error? 

For your information, I am using Chrome to run the notebook

If there is any inquires regarding my side, kindly do comment and reply, I will do my best to provide them.

Thank you in advance.

**Comment by titu1994** [comment]
Could you try by replacing gpus=[1] with gpus=1? This seems to be trying to index GPU [1] which would be the second gpu, but colab has just 1 gpu

**Comment by michael-so** [comment]
Hi Good Sir,

Yes, it seems that this is the case. It runs smoothly now once I have
changed to "gpus=1".

Although would just like to inform you that looks like the an4 server the
notebook is fetching data from is currently down. I have to use my own data
to validify your suggested solution.

Either way, thank you for your kind help.

Regards
