### ISSUE TITLE
Caching datasets for ASR training

### ISSUE THREAD

**Issue by diego-fustes** [NVIDIA/NeMo#1654]
**Caching datasets for ASR training**

The current data loaders for ASR seem to load the file from disk for every iteration with AudioSegment. This becomes a bottleneck when the disk is not very fast (i.e. is not a SSD). Is there a way to cache the audio files in RAM memory? Should we add the option to cache the datasets? We think that it may accelerate training when it fits.

Kind regards

**Comment by okuchaiev** [comment]
currently we don't support such feature. Also, it would put high requirements on available RAM
