### ISSUE TITLE
[Question]Can I integrate it with my college website to transcribe the lecture videos online?

### ISSUE THREAD

**Issue by souravverma94** [NVIDIA/NeMo#1658]
I am new to ASR (Automatic Speech Recognition), I am working on a college website where professors can upload their lectures. I want to integrate an automatic speech transcript generator so that users can turn on the captions while streaming. While searching for open source options, I came across Nemo. Could anyone please tell me whether it is possible to do that and if Yes, could you please guide me?

**Comment by okuchaiev** [comment]
>>"Can I integrate it with my college website"
- Yes.

>> "could you please guide me?"
- Have a look at this notebook for example. 
https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0b3/tutorials/NeMo_voice_swap_app.ipynb
