### ISSUE TITLE
Licence of pretrained models

### ISSUE THREAD

**Issue by DanBmh** [NVIDIA/NeMo#1661]
Hi, do the pretrained models from https://ngc.nvidia.com/catalog/models/nvidia:nemospeechmodels have the same Apache2 licence as this repository?

**Comment by okuchaiev** [comment]
1. NeMo software is release under [Apache 2.0 license](https://github.com/NVIDIA/NeMo/blob/main/LICENSE)
2. Pre-trained checkpoints which you can find on NVIDIA NGC are under [NGC TERMS OF USE](https://ngc.nvidia.com/legal/terms) unless another License/Terms Of Use/EULA is clearly specified on the model page.

Specifically, all models from:

- https://ngc.nvidia.com/catalog/models/nvidia:nemospeechmodels/files?version=1.0.0a5
- https://ngc.nvidia.com/catalog/models/nvidia:nemonlpmodels/files?version=1.0.0a5
- https://ngc.nvidia.com/catalog/models/nvidia:nemottsmodels/files?version=1.0.0a5

(note ?version=1.0.0a5 part) are under [NGC TERMS OF USE](https://ngc.nvidia.com/legal/terms).

I think going forward we should explicitly specify License/EULA for pre-trained models' weights. Will try doing that in the next releases.

We are also open to community's feedback on this question.
