### ISSUE TITLE
Small edit needed to intent/slot tutorial

### ISSUE THREAD

**Issue by carolmanderson** [NVIDIA/NeMo#1672]
In the intent/slot tutorial notebook, I think this line:

https://github.com/NVIDIA/NeMo/blob/ad0edf2e6910b7b6de3ae93fba9b728f6479c50e/tutorials/nlp/Joint_Intent_and_Slot_Classification.ipynb#L508

Should be changed to: `trainer.test(model=eval_model, ckpt_path=None, verbose=False)`

So that the reloaded/best model is the one that gets evaluated.

**Comment by okuchaiev** [comment]
can you please send a PR?

**Comment by okuchaiev** [comment]
fixed
