### ISSUE TITLE
Is it possible to serve Nvidia NeMo models using Nvidia Triton Server?

### ISSUE THREAD

**Issue by Jblauvs** [NVIDIA/NeMo#1677]
Is it possible to serve Nvidia NeMo models using Nvidia Triton Server?

**Comment by okuchaiev** [comment]
Every NeMo model inherits from ``torch.nn.Module`` at the top of it's inheritance chain. So everything applicable to torch.nn.Module objects, including serving them via Triton Server should apply here as well.

**Comment by Jblauvs** [comment]
Great, thanks for the response.
