### ISSUE TITLE
decode and refrence strings are not coming ,when i training in gpu

### ISSUE THREAD

**Issue by shahbaznazami** [NVIDIA/NeMo#1692]
**Describe the bug**

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by shahbaznazami** [comment]
python 3.6
 PyTorch-lightning 1.1.6
Ubuntu 18.04.5

**Comment by okuchaiev** [comment]
Can you please give more details. What language? Exact command/config ran.

**Comment by shahbaznazami** [comment]
language= English
notebook=https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/01_ASR_with_NeMo.ipynb
I simply run the notebook on my GPU

**Comment by shahbaznazami** [comment]
training is happening but at every epoch decode and reference strings are not coming

**Comment by VahidooX** [comment]
Do you mean printing the sample encoded along with the reference during training?
In that case, I think that tutorial is using /examples/asr/conf/config.yaml. This config file does not have the log_prediction param in it. I think log_prediction is disabled by default. So you need to add it to the config directly or setting it to true from command line like here: https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/conformer_ctc_bpe.yaml#L9

**Comment by shahbaznazami** [comment]
thanks
