### ISSUE TITLE
Loading LM Checkpoint from huggingface

### ISSUE THREAD

**Issue by avikpal00** [NVIDIA/NeMo#1726]
Hello,
I am trying to load a language model checkpoint from huggingface models, specifically [albert-xlarge-v2-squad-v2](https://huggingface.co/ktrapeznikov/albert-xlarge-v2-squad-v2), for QAModel. I am not sure if it's already a feature implemented, if it is, how do I go about doing this?

**Comment by yzhang123** [comment]
Hey @avikpal00, thanks for reaching out!
Yes, we indeed support this model! 
Similar to the link you posted, you would initialize the backbone BERT encoder with albert-xlarge-v2 and train on SQuADv2.0 with the hyperparameters they used, so your cmd line would look something like this:

python question_answering_squad.py model.train_ds.file=/data/squad/v2.0/train-v2.0.json  model.validation_ds.file=/data/squad/v2.0/dev-v2.0.json trainer.precision=16 model.train_ds.batch_size=[TO SET] trainer.max_epochs=[TO SET] trainer.amp_level=O1 trainer.gpus=[TO SET] trainer.accumulate_grad_batches=[TO SET]   model.dataset.version_2_with_negative=true model.language_model.pretrained_model_name=albert-xlarge-v2

**Comment by avikpal00** [comment]
Hi @yzhang123, thanks for the reply
I did proceed to training the albert model, and also got similar results. But is it possible to directly load the weights of these supported huggingface model checkpoints through the config file so that I can skip training time? This way I can try out a lot of community posted model checkpoints for different base models and datasets.
Thanks again.

**Comment by yzhang123** [comment]
@avikpal00  we will keep this in mind, and change this issue to feature request :)
