### ISSUE TITLE
[Question] Is it possible to implement BERT in ASR?

### ISSUE THREAD

**Issue by lodm94** [NVIDIA/NeMo#1733]
Hi all,
i am workin on a quartznet model with 5-gram beam search LM for decode the CTC matrix.
I was wondering if it could be possible to implement a BERT-based LM on top of my asr model.

If i simply mask the uncorrect transcripted word and then run BERT, of course the word would be replaced with a new one, but not necessarily the correct one. BERT could replace a mispelled word with a totally different word that fits right in the context. I guess BERT should be fed with audio waveform information to replace the word with the correct one instead with a different one.

Is it possible? Any suggestion on related work?

**Comment by okuchaiev** [comment]
Doing this for every single step in beam search process would be too computationally expensive.
Instead you can re-score candidate beams from beam search like we did with transformer XL in this paper:
https://arxiv.org/pdf/1904.03288.pdf
