### ISSUE TITLE
[Question] Updating PyPI with latest NeMo release(s)

### ISSUE THREAD

**Issue by eozd** [NVIDIA/NeMo#1734]
**Describe your question**
I am trying to add the latest `v1.0` release of NeMo as a pip dependency on my project. However, this version has not been uploaded to PyPI yet. (https://pypi.org/project/nemo-toolkit/). Do you have any plans or timeline for the update? This would help me greatly in making my requirements file consistent and easy-to-maintain.

**Environment overview**
 - Environment location: Bare-metal
 - Method of NeMo install: `pip install nemo-toolkit`

**Environment details**
- OS version `Linux`
- PyTorch version `1.7.1`
- Python version `3.8`

**Comment by okuchaiev** [comment]
You should use:
```
pip install nemo-toolkit[all]==1.0.0b3
```
Or  in your requirements.txt file
```
nemo-toolkit[all]==1.0.0b3
```

**Comment by eozd** [comment]
Thanks a lot for the quick reply @okuchaiev . I have seen that nemo 1.0.0b4 was recently released and I am looking forward to incorporating the latest changes in that version. Do you plan to upload this latest version to PyPI as well?

Cheers,
Eshref
