### ISSUE TITLE
How to integrate own Language Model [Question]

### ISSUE THREAD

**Issue by michael-so** [NVIDIA/NeMo#1756]
Hi, I would like to ask how to integrate my own Language Model into this notebook: https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/asr/01_ASR_with_NeMo.ipynb

I have been using my own data (an under-resourced language) for the notebook, and I wish to improve its WER by integrating my own Language Model. But so far I have failed in doing so.

Do I need to do some configuration in the config.yaml files in order to integrate my LM? Or do I have to call it externally somewhere in the codes?

Are there any documentations or guide for this? If there is, could you kindly suggest to me.

Looking forward to your replies,

Thank you.

**Comment by lodm94** [comment]
Wich kind of LM? N-gram? If so, read [this](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Offline_ASR.ipynb)

If you are talking about transformer based LM, I am struggling the same. I opened a discussion about this [here](https://github.com/NVIDIA/NeMo/discussions/1736)

**Comment by kruthikakr** [comment]
Any other reference to add transformer based LM for the citrinet model  ?

**Comment by EmreOzkose** [comment]
@kruthikakr Could you get meaningful results with adding language model to Citrinet? I could not achieve: https://github.com/NVIDIA/NeMo/issues/2142

**Comment by titu1994** [comment]
Example and instructions to setup language model for ASR beam search with KenLM and neural language models are here - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html
