### ISSUE TITLE
extract speaker embeddings with `spkr_get_emb.py`

### ISSUE THREAD

**Issue by JINHXu** [NVIDIA/NeMo#1768]
Hi!

I am just getting started with `NeMo`, and got a little confused when experimenting with `spkr_get_emb.py`, it appears one will need to use `SpeakerNet_verification_3x2x512.yaml` config and set up `cfg.model.test_ds`, however in this configuration, there is no `test_ds`. Was this an error or does this mean one needs to write `test_ds` to the verification model config? Any help on this would be appreciated!

Cheers,
Xu

**Comment by nithinraok** [comment]
Yes you can either add it to config and call the script or while calling the script you may give test_ds options as command line arguments prepended `+`. For reference look at hydra config https://hydra.cc/docs/tutorials/basic/your_first_app/config_groups

**Comment by JINHXu** [comment]
Thanks for your answer, Nithin! I did an experiment with speaker verification without setting up test_ds in the model training stage and set up `test_ds` the way it was done in the tutorial
```python 
test_config = OmegaConf.create(dict(
    manifest_filepath='/embeddings_manifest.json',
    sample_rate=16000,
    labels=None,
    batch_size=1,
    shuffle=False,
    time_length=8,
    embedding_dir='./'
))
```
Should this be one way to do it? Thanks again for your help!

**Comment by nithinraok** [comment]
yes, pass this to setup_test_data with model instantiated and extract embeddings.

**Comment by JINHXu** [comment]
Many thanks again for your help!
