### ISSUE TITLE
Jasper model not loading on CPU

### ISSUE THREAD

**Issue by skubicius** [NVIDIA/NeMo#1778]
**Describe the bug**

Loading `Jasper10x5Dr-En` model fails on a system without a GPU.

**Steps/Code to reproduce bug**

Notebook with example:
https://colab.research.google.com/drive/1NDzwQl0KyOOYPheW60colRD2Sm8Ng_vD?usp=sharing

**Expected behavior**

NeMo should detect that GPU is not available and load the model to CPU.

**Environment overview (please complete the following information)**

 - Environment location: Google Colab
 - Method of NeMo install: `!pip install nemo_toolkit[all]==1.0.0b2`

**Environment details**

- OS version:
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- PyTorch version `1.7.0+cu101`
- Python version `Python 3.6.9`

**Comment by titu1994** [comment]
You can use "from_pretrained(..., map_location="cpu")

**Comment by okuchaiev** [comment]
closing, please re-open is @titu1994 's suggestion did not help.
