### ISSUE TITLE
[Question] FileNotFoundError in Relation Extraction w/ BioMegatron

### ISSUE THREAD

**Issue by vdbedem** [NVIDIA/NeMo#1811]
Executing the example notebook 'Relation_Extraction-BioMegatron.ipynb' leads to an error

> FileNotFoundError: Could not find tokenizer.vocab_file

after running cell `model = nemo_nlp.models.TextClassificationModel(cfg=config.model, trainer=trainer)`. This happens both when I run the notebook on colab or on my local setup. 

How can I fix this error?

Thanks!

**Comment by creativeautomaton** [comment]
Hi there is a branch change, I had the same issue. 

changeing the variable at the start of the notebook from
BRANCH = 'main'
to
BRANCH = 'r1.0.0rc1'
