### ISSUE TITLE
[Question] how to improve QuartzNet for production

### ISSUE THREAD

**Issue by YYUUUY** [NVIDIA/NeMo#1819]
**Describe your question**
seeking guidelines from the community for improving QuartzNet for production:

1. different accents, for example, US/UK/AU English
2. filler words, for example, um; ah
3. domain words, for example, company names, finance terms

**Comment by titu1994** [comment]
Please look into Nvidia Jarvis - https://developer.nvidia.com/nvidia-jarvis
