### ISSUE TITLE
Tried to restore a nemo model after 3 months, but can't do it just like I used to.

### ISSUE THREAD

**Issue by BradAxl** [NVIDIA/NeMo#1823]
I trained **EncDecCTCModel** model with Mozilla Voice Project dataset like 3 months ago and save it by `.save_to` and I used to restore it by `nemo.collections.asr.models.EncDecCTCModel.restore_from(restore_path=_path_to_nemo_model_)`. I didn't have any problem at that moment and I stopped working on that project. 

Today I tried to restore just like I did it before and got an error that says: `AttributeError: can't set attribute`.  I followed the traceback and found a comment which says  `# models are handled differently for now` that makes me thinks something has changed and probably I need to restore it in other way. If that's correct, how should I restore the model at the moment ? Do I need to retrain a new model because something has change about the training and the way which a model is stored ? I would appreciate any answer or some advice.

Brad,

Thanks in advance.

```
- Environment location:  Google Colab
- Method of NeMo install: !python -m pip install git+https://github.com/NVIDIA/NeMo.git@$v1.0.0b2#egg=nemo_toolkit[asr]
```

**Comment by okuchaiev** [comment]
can you try ``pip install nemo_toolkit['all']==1.0.0rc1`` ?

**Comment by BradAxl** [comment]
I just tried it and it works. Thank you very much, I was waiting literally like 2 months for this helpful answer. Can you please explain what's the difference between `pip install nemo_toolkit['all']==1.0.0rc1`, `!pip install nemo_toolkit[all]==1.0.0b3` and `!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[asr]` PLEASE ?
