### ISSUE TITLE
[Question] When is the latest beta version going to be on PyPI?

### ISSUE THREAD

**Issue by m-zat** [NVIDIA/NeMo#1824]
Hello,

I would like to experiment with the latest version of NeMo, v1.0.0b4, however due to some firewall issues at my workplace I can only install through PyPI and not from Github.

Do you have any plan to release that version on PyPI in the near future?

Thanks!

**Comment by titu1994** [comment]
You can use pip install --upgrade nemo_toolkit[all] to get the latest version now.
