### ISSUE TITLE
Pre-trained models are no longer compatible with new model architecture for ASR

### ISSUE THREAD

**Issue by dipanjanS** [NVIDIA/NeMo#186]
The pre-trained models have effectively become not usable anymore since updates were made to `JasperEncoder` or most probable the [`jasper.py`](https://github.com/NVIDIA/NeMo/commit/2d1d7b235e9d705e8eb766f26feb0038b0e77c36#diff-3c939a5302a05f847d3eca261937d8cd) module.

Example pre-trained model: https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5

Error on trying to load the same:

```
jasper_encoder = nemo_asr.JasperEncoder(
    jasper=jasper_model_definition['JasperEncoder']['jasper'],
    activation=jasper_model_definition['JasperEncoder']['activation'],
    feat_in=jasper_model_definition['AudioToMelSpectrogramPreprocessor']['features'])

jasper_encoder.restore_from(CHECKPOINT_ENCODER, local_rank=0)
```

```
RuntimeError: Error(s) in loading state_dict for JasperEncoder:
	Missing key(s) in state_dict: "encoder.0.mconv.0.conv.weight", "encoder.0.mconv.1.conv.weight", "encoder.0.mconv.2.weight", "encoder.0.mconv.2.bias", "encoder.0.mconv.2.running_mean", "encoder.0.mconv.2.running_var", "encoder.1.mconv.0.conv.weight", "encoder.1.mconv.1.conv.weight", "encoder.1.mconv.2.weight", "encoder.1.mconv.2.bias", "encoder.1.mconv.2.running_mean", "encoder.1.mconv.2.running_var", "encoder.1.mconv.5.conv.weight", "encoder.1.mconv.6.conv.weight", "encoder.1.mconv.7.weight", "encoder.1.mconv.7.bias", "encoder.1.mconv.7.running_mean", "encoder.1.mconv.7.running_var", "encoder.1.mconv.10.conv.weight", "encoder.1.mconv.11.conv.weight", "encoder.1.mconv.12.weight", "encoder.1.mconv.12.bias", "encoder.1.mconv.12.running_mean", "encoder.1.mconv.12.running_var", "encoder.1.mconv.15.conv.weight", "encoder.1.mconv.16.conv.weight", "encoder.1.mconv.17.weight", "encoder.1.mconv.17.bias", "encoder.1.mconv.17.running_mean", "encoder.1.mconv.17.running_var", "encoder.1.mconv.20.conv.weight", "encoder.1.mconv.21.conv.weight", "encoder.1.mconv.22.weight", "encoder.1.mconv.22.bias", "encoder.1.mconv.22.running_mean", "encoder.1.mconv.22.running_var", "encoder.1.res.0.0.conv.weight", "encoder.2.mconv.0.conv.weight", "encoder.2.mconv.1.conv.weight", "encoder.2.mconv.2.weight", "encoder.2.mconv.2.bias", "encoder.2.mconv.2.running_mean", "encoder.2.mconv.2.running_var", "encoder.2.mconv.5.conv.weight", "encoder.2.mconv.6.conv.weight", "encoder.2.mconv.7.weight", "encoder.2.m...
	Unexpected key(s) in state_dict: "encoder.0.conv.0.weight", "encoder.0.conv.1.weight", "encoder.0.conv.2.weight", "encoder.0.conv.2.bias", "encoder.0.conv.2.running_mean", "encoder.0.conv.2.running_var", "encoder.0.conv.2.num_batches_tracked", "encoder.1.conv.0.weight", "encoder.1.conv.1.weight", "encoder.1.conv.2.weight", "encoder.1.conv.2.bias", "encoder.1.conv.2.running_mean", "encoder.1.conv.2.running_var", "encoder.1.conv.2.num_batches_tracked", "encoder.1.conv.5.weight", "encoder.1.conv.6.weight", "encoder.1.conv.7.weight", "encoder.1.conv.7.bias", "encoder.1.conv.7.running_mean", "encoder.1.conv.7.running_var", "encoder.1.conv.7.num_batches_tracked", "encoder.1.conv.10.weight", "encoder.1.conv.11.weight", "encoder.1.conv.12.weight", "encoder.1.conv.12.bias", "encoder.1.conv.12.running_mean", "encoder.1.conv.12.running_var", "encoder.1.conv.12.num_batches_tracked", "encoder.1.conv.15.weight", "encoder.1.conv.16.weight", "encoder.1.conv.17.weight", "encoder.1.conv.17.bias", "encoder.1.conv.17.running_mean", "encoder.1.conv.17.running_var", "encoder.1.conv.17.num_batches_tracked", "encoder.1.conv.20.weight", "encoder.1.conv.21.weight", "encoder.1.conv.22.weight", "encoder.1.conv.22.bias", "encoder.1.conv.22.running_mean", "encoder.1.conv.22.running_var", "encoder.1.conv.22.num_batches_tracked", "encoder.1.res.0.0.weight", "encoder.2.conv.0.weight", "encoder.2.conv.1.weight", "encoder.2.conv.2.weight", "encoder.2.conv.2.bias", "encoder.2.conv.2.running_mean", "encoder....
```

Is there anyway to make this work with the older models or get newer compatible pre-trained models? @okuchaiev

**Comment by okuchaiev** [comment]
Yes, current master Jasper checkpoints are not compatible with the latest *released* checkpoints for the latests *released* NeMo version (which is 0.8.2).

If you want to use the latest stable version (0.8.2), just install NeMo using "pip install nemo_toolkit nemo_asr" (e.g. NOT from GitHub). This version is compatible with the latest published checkpoints.

If you want to work with the latest master (you are welcome to do so and help us discover any issues!), here is the script snippet which will make them compatible (note that you only need this for JasperEncoder)
```python
yaml = YAML(typ="safe")
with open("<where_your_config_is>/jasper10x5dr.yaml") as f:
    jasper_model_definition = yaml.load(f)
jasper_encoder = nemo_asr.JasperEncoder(
    feat_in=64,
    **jasper_model_definition['JasperEncoder'])
jasper_encoder = "PATH_TO_CHECKPOINT"
# hack to map the state dict of previous version
ckpt = torch.load(nn_encoder)
new_ckpt = {}
for k, v in ckpt.items():
    new_k = k.replace('.conv.', '.mconv.')
    if len(v.shape) == 3:
        new_k = new_k.replace('.weight', '.conv.weight')
    new_ckpt[new_k] = v
torch.save(new_ckpt, "WHERE_TO_SAVE_NEW_COMPATIBLE_CHECKPOINT")
```

**Comment by dipanjanS** [comment]
Cool thanks I will try this out. Yes initially I had gone with `pip install nemo_toolkit nemo_asr` but I ended up getting an error

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-64f87119185b> in <module>()
      2 
      3 import nemo
----> 4 import nemo_asr

1 frames
/usr/local/lib/python3.6/dist-packages/nemo_asr/data_layer.py in <module>()
     15 import torch
     16 try:
---> 17     from apex import amp
     18 except AttributeError:
     19     print("Unable to import APEX. Mixed precision and distributed training "

ModuleNotFoundError: No module named 'apex'
```

I guess assuming I didn't install `apex` which would stop this error, the `except` block should catch the `ModuleNotFoundError` maybe and then this error will stop.

**Comment by okuchaiev** [comment]
Yes, please install APEX (from GitHub). If you are: (1) using Volta or Turing-based GPUs and/or (2) doing multi-gpu/multi-node training you want to have it.

"the except block should catch the ModuleNotFoundError" - this is True and I believe we already fixed it on master

**Comment by okuchaiev** [comment]
should be fixed now with 0.9 released. Please use version 2 models from NVIDIA NGC

**Comment by Oktai15** [comment]
> If you want to work with the latest master (you are welcome to do so and help us discover any issues!), here is the script snippet which will make them compatible (note that you only need this for JasperEncoder)

@okuchaiev, according to this comment: https://github.com/NVIDIA/NeMo/issues/247#issuecomment-569657856, you changed not only layer names, but also the res layer. So I have two questions:
1. It means that old pretrained weights can't be useful with new 0.9 version of Nemo even with your workaround?
2. This problem can be related with the following issue https://github.com/NVIDIA/NeMo/issues/217?

**Comment by okuchaiev** [comment]
@Oktai15 version 0.9 was released. If you do "pip install nemo_asr" you will get 0.9 version from pypi.org.  Published models (for example, https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5 , just make sure that you use latest version there) should be compatible with 0.9 version.

If above is not the case please open a new issue detailing your problem.

**Comment by awasthiabhijeet** [comment]
Hi,
Is this still an issue?

I am unable to load the pre-trained JASPER model trained only on librispeech provided here: https://ngc.nvidia.com/catalog/models/nvidia:jaspernet10x5dr

**Comment by McLovinfromHawaii** [comment]
@okuchaiev I'm having the same problem as @awasthiabhijeet .

Does the model have to be version 2 in order to succesfully load? Because I couldn't see any version 2 of English Jasper models.

**Comment by awasthiabhijeet** [comment]
> @okuchaiev I'm having the same problem as @awasthiabhijeet .
> 
> Does the model have to be version 2 in order to succesfully load? Because I couldn't see any version 2 of English Jasper models.

Hi,
Minor changes to the code provided [here](https://github.com/NVIDIA/NeMo/issues/186#issuecomment-562311584) helped me to port the model. :)

**Comment by McLovinfromHawaii** [comment]
@awasthiabhijeet nn_encoder is not defined in my code. What is that?

**Comment by yaliu777** [comment]
I got this error when I was trying to use this [code]( https://github.com/NVIDIA/NeMo/issues/186#issuecomment-562311584) to transfer pre-trained Jasper model to a compatible version. And I am also not sure what is ```nn_encoder``` here. Could anyone help me with this? Thanks in advance!
```
Traceback (most recent call last):
  File "  ", line 18, in <module>
    **jasper_model_definition['JasperEncoder'])
  File "/home/amir/NeMo/nemo/collections/asr/jasper.py", line 161, in __init__
    super().__init__()
  File "/home/amir/NeMo/nemo/backends/pytorch/nm.py", line 40, in __init__
    NeuralModule.__init__(self, name)  # For NeuralModule API
  File "/home/amir/NeMo/nemo/core/neural_modules.py", line 91, in __init__
    self._placement = self._factory.placement
AttributeError: 'NoneType' object has no attribute 'placement'
```

**Comment by savitha91** [comment]
Are there any tutorials which explain how to load QuartzNet15x5-En-Base.nemo file, which i obtained from unzipping 'quartznet15x5_2.zip' . When i use this command,
nemo.collections.asr.models.ASRConvCTCModel.from_pretrained(. ) i get an error saying  ----                                      
 module 'nemo.collections.asr' has no attribute 'models'.

Installations done are following- 
!pip install nemo
!pip install nemo_toolkit[all]

I am new to this. Kindly help me

**Comment by soheiltehranipour** [comment]
> 
> 
> Are there any tutorials which explain how to load QuartzNet15x5-En-Base.nemo file, which i obtained from unzipping 'quartznet15x5_2.zip' . When i use this command,
> nemo.collections.asr.models.ASRConvCTCModel.from_pretrained(. ) i get an error saying ----
> module 'nemo.collections.asr' has no attribute 'models'.
> 
> Installations done are following-
> !pip install nemo
> !pip install nemo_toolkit[all]
> 
> I am new to this. Kindly help me

Exactly my issue.
