### ISSUE TITLE
torch 1.8.0 incompatibility: pytorch-lightening needs to be updated to 1.2.3, but is not enough.

### ISSUE THREAD

**Issue by tiborkiss** [NVIDIA/NeMo#1868]
**Describe the bug**

Due to `torch` 1.8.0 just was released a few days ago, `pytorch-lightning` is still incompatible with the new torch.
Since NeMo setup pulls the latest stable torch release, imports this problem.
The problem is not visible during the install, but when using `pytorch-lightning` within NeMo tutorials for example.
 
**Steps/Code to reproduce bug**

I installed NeMo from r1.0.0rc17
```
python -m pip install git+https://github.com/NVIDIA/NeMo.git@r1.0.0rc1#egg=nemo_toolkit[all]
```
It was working while the official stable pytorch was 1.7.1.
Since PyTorch 1.8.0 came out, in fresh venv NeMo's requirements are pulling the latest torch, which is 1.8.0,
With torch 1.8.0 the second ASR tutorial notebook fails while using `pytorch-lightning` because `torchtext.data.Batch` was deprecated (and moved to` torchtext.legacy.data.Batch`, which breaks PyTorch Lightning. For more information read: https://github.com/PyTorchLightning/pytorch-lightning/pull/6168

**Expected behavior**

Since the bug is indirectly caused by the incompatibility between the current `pytorch-lightning` installed by NeMo and the latest `torch` 1,8.0, the only temporary solution I see that NeMo should stick with `torch<=1.7.1` and it's associated libraries.
I tried to edit the requirements by myself, then `./reinstall.sh`, unfortunately something is still pulling 1.8.0 somewhere at the end of the setup process.
The expected behavior is to be able to stick to torch==1.7.1

**Environment overview (please complete the following information)**

 - Environment location: WSL2 with GPU support and Ubuntu 20.04

**Environment details**

- OS version: Ubuntu 20.04 running in WSL2 with GPU support.
- PyTorch version: 1.8.0
- Python version: 3.8.5

**Additional context**

I think, I completely described the problem and the possible solution.

**Comment by blisc** [comment]
@tiborkiss Please note that NeMo RC1 does not work on lightning 1.2.0. In fact, RC1 pins Lightning <= 1.1.5. If you need Lightning 1.2.0 or high, please use the NeMo main branch

**Comment by tiborkiss** [comment]
Thank you for the tips @blisc .
Looks like the shortest workaround is to stick with torch 1.7.1

**Comment by tiborkiss** [comment]
In the setup.py we have a section related to `SUPPORTED_TORCH_VERSION` where is the `REMOVE AFTER 21.03 Container is released !` comment. 
At least until this container is released it works, therefore I close this PR.

**Comment by antandrieux** [comment]
@tiborkiss Sorry, what do you mean? Did you find a fix? Thanks!

**Comment by tiborkiss** [comment]
> @tiborkiss Sorry, what do you mean? Did you find a fix? Thanks!

Yes, in this branch, this file it does that fix. https://github.com/NVIDIA/NeMo/blob/r1.0.0rc1/setup.py
As soon as is not removed (read the comments there), it is enough. I just use this branch and it works.
