### ISSUE TITLE
conformer to onnx not working

### ISSUE THREAD

**Issue by emrakul** [NVIDIA/NeMo#1879]
Conformer model export to onnx not working as intended. Onnx export worked ok and did not report anything and onnx.checker.check_model worked without errors too. Loading the onnx file and running the sample audio file causes onnxruntime to die quietly (jupyter just reloads the kernel, and running script just says "segmentation fault")

Steps to reproduce:
load .nemo model for conformer 
`model = nemo_asr.models.EncDecCTCModelBPE.restore_from('conformer.nemo')`
export conformer encoder to onnx 
`model.encoder.export('conformer_encoder.onnx')`
load onnx in onnxruntime and run through a sample file
```
sess = onnxruntime.InferenceSession(conformer_encoder)
input_name = sess.get_inputs()[0].name
output_name = sess.get_outputs()[0].name
result = sess.run([output_name], {input_name: features})
```
After running these steps I got a segmentation fault error. For feature extraction and onnx export/load I used the same pipeline that I used for jasper models (and it worked perfectly for jasper). Conformer works okay during training and evaluation within nemo and ptl frameworks. 
In which case onnxruntime just fails completely without even reporting for something like incorrect dimensions or unsupported operations (like it usually does)?
Maybe I am missing something obvious here?

environment: 
DGX-1, Ubuntu 18.04
nemo - up to date
torch - 1.8.0 
onnxruntime - 1.6.0
onnxruntime-gpu - 1.4.0 

I tried different combination of versions of the libraries but most of them cause the effect as mentioned above and the others fail for other reasons - mostly during the export step.

**Comment by okuchaiev** [comment]
I think we haven't properly implemented export for Conformer. @VahidooX to comment further. If this isn't supported yet, maybe should raise "NotImplemented" exception?

**Comment by VahidooX** [comment]
We have not tested the export for Conformer yet. I would raise NotImplemented for now. I will ask @borisfom to take a look at it.

**Comment by okuchaiev** [comment]
closing since PR is merged
