### ISSUE TITLE
[Question] Exporting custom NeMo models to Jarvis (.ejrvs)

### ISSUE THREAD

**Issue by xaiguy** [NVIDIA/NeMo#1886]
Dear NeMo team, 

I'm currently looking into Jarvis and haven't found a pre-built way to export my custom NeMo models to .ejrvs format yet, only for TLT. Several sources (including https://developer.nvidia.com/nvidia-nemo) state that it's possible with a single command. If anyone knows the magic words, please let me know. 👍 

Kind regards!

PS: I'm using NeMo 1.0.0b3 via the official docker.

**Comment by okuchaiev** [comment]
@xaiguy Can you please clarify what do you mean by "custom NeMo model"? 
Every TLT model can be exported to Jarvis. But NeMo contains more models than TLT, including many "research" ones which can't be deployed to Jarvis yet.
 
We are constantly increasing the number of models supported by Jarvis by adding them to TLT.

**Comment by xaiguy** [comment]
@okuchaiev Oh, pardon the ambiguity. With "custom" I just meant models fine-tuned with NeMo, in particular Jasper. I just mentioned TLT because I saw that it's very easy to save and export models to .ejvrs format from there and I was hoping to find something similar for NeMo.

**Comment by xaiguy** [comment]
I saw a new passage was added to the docs, thanks! I'll close this issue now, as the answer can be found following the link below:

https://docs.nvidia.com/deeplearning/jarvis/user-guide/docs/model-overview.html?highlight=servicemaker#nemo-to-jarvis
