### ISSUE TITLE
Do we need to know the number of speakers before performing speaker_diarization?

### ISSUE THREAD

**Issue by jainal09** [NVIDIA/NeMo#1911]
From the[ speaker_diarization.yaml](https://raw.githubusercontent.com/NVIDIA/NeMo/main/examples/speaker_recognition/conf/speaker_diarization.yaml) file
There is `num_speakers: 2 # for each recording` value added in the yaml file.
Hence, do we need to know the number of speakers present in a audio recording to perform inference of speaker_diarization or can it be done unsupervised ?

**Comment by nithinraok** [comment]
Technically no, but it is always good to provide maximum number of speakers for higher accuracy. Support for dynamic computation for number of speakers is not yet fully tested. If you would like to try change 
min_clusters=1 and max_clusters=max_num_speakers (which you are sure it won't exceed that number) 
https://github.com/NVIDIA/NeMo/blob/27e5f2dce512495d93577c39618409d3403b210a/nemo/collections/asr/parts/speaker_utils.py#L256
