### ISSUE TITLE
RuntimeError: fft: ATen not compiled with MKL support [Question]

### ISSUE THREAD

**Issue by ulucsahin** [NVIDIA/NeMo#1938]
**Describe your question**
I am getting the error on title on arm processor when trying to do inference with QuartzNet model. This is expected since MKL is not supported on arm. How can do inference on arm devices? Are there any alternatives? 

I am using PyTorch 1.9 but I think this is not the reason for this error.

**Environment overview (please complete the following information)**

 - Arm emulated Docker Container, running on Windows 10
 - From source. Followed exact instructions explained on readme of 1.0.0b3:
```
apt-get update && apt-get install -y libsndfile1 ffmpeg
git clone https://github.com/NVIDIA/NeMo
cd NeMo
./reinstall.sh
```

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- Ubuntu 20.04 version
- PyTorch version 1.9 
- Python version 3.8.5

**Comment by okuchaiev** [comment]
At the moment we do not test/support Arm architectures. Do you know which module need MKL? Are you able to install Pytorch on Arm without MKL?
