### ISSUE TITLE
[Question] OFFSET in Voice Activity Detection

### ISSUE THREAD

**Issue by OmarHory** [NVIDIA/NeMo#1948]
Can someone briefly explain to me the Offset in the manifest file of VAD?
How can I decide it and what is it exactly?

Thanks in advance.

**Comment by fayejf** [comment]
Hi thanks for your question! The offset in manifest (for all audio related manifest not limited to VAD)  means the **starting point (second) of the audio snippet**. 
For example` "audio_a.wav, offset:0, duarion:10"` means "audio snippet of audio_a from 0 to 10 seconds"; SImilarly 
`"audio_a.wav, offset:5, duarion:5" `means "audio snippet of audio_a from 5 to 10 seconds";

**Comment by OmarHory** [comment]
Thank you so much! @fayejf 

I am closing the issue.

Regards.
