### ISSUE TITLE
[Question] (How) Can I use Nemo offline on Pycharm with Windows ?

### ISSUE THREAD

**Issue by Hackerdaniel2012** [NVIDIA/NeMo#1949]
**Describe your question**

Hi i'm new to NeMo and I wanted to get started with it to use it for some ProjectIdeas.
I want to use NeMo offline so I tried to get it going on Pycharm.
Now I installed everything from Cuda to Kaldi and it's still not working.
I'm getting a freeze.Support() Runtime Error from multiprocessing/spawn.py when I only try to import
nemo.collections.asr only on Pycharm.
When I tryed it on JupiterNotebook this Error was gone but if I try to run a model torch/nn/modules/module.py l.826
throws "AttributeError: can't set attribute"
I wanna know now if there is a easy way to get such Problems fixed or a way to uninstall everything and get one clean installation for windows that works on pycharm aswell.
Or is it the best Choice to get Linux in a virtual machine and run it there?
I would very much appreciate any help.
Greetings from Germany. 

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by okuchaiev** [comment]
Hi, unfortunately, at this moment we only support Linux (Ubuntu).
