### ISSUE TITLE
timing metadata for each word in the transcript?

### ISSUE THREAD

**Issue by JoBroMo** [NVIDIA/NeMo#195]
Hi,

Is there a easy way to get timings exposed? If not, is this feature planed for a near future? 

Thank you!

**Comment by okuchaiev** [comment]
Currently (as of version 0.8.2 and in coming soon 0.9.0) there is no way to get timing exposed.

**Comment by jonathan-cohen-nvidia** [comment]
But I do want to add this is something we plan to add.

**Comment by JoBroMo** [comment]
Hate to ask this. As of now, are you considering adding timings in next release?

Best Regards!
