### ISSUE TITLE
[Question] Unable to continue training upon checkpoint restoration: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by solvylisa** [NVIDIA/NeMo#2018]
Hi,

I am trying to fine-tuning my model, but after a successful restore of my checkpoint, i keep on stumbling on this error: TypeError: 'NoneType' object is not iterable

I am a beginner and is using Nemo on Google Colab. I am following the tutorial provided in one of your notebooks. Below is the code on how i restored my checkpoint and how i started the training:

----------------------------------------------------------------------------------------------
import pytorch_lightning as pl
trainer = pl.Trainer(gpus=1, max_epochs=50) 

from omegaconf import DictConfig
params['model']['train_ds']['manifest_filepath'] = train_manifest
params['model']['validation_ds']['manifest_filepath'] = test_manifest

my_model = nemo_asr.models.EncDecCTCModel.restore_from('my_checkpoint.nemo')

trainer.fit(my_model)

----------------------------------------------------------------------------------------------

How i saved my checkpoint:
.
.
.

checkpoint_path = "my_checkpoint.nemo"
my_model.save_to(checkpoint_path)

----------------------------------------------------------------------------------------------

This was the error produced:
.
.
.
.

TypeError                                 Traceback (most recent call last)
<ipython-input-11-2116e952a23e> in <module>()
      1 # Start training!!!
----> 2 trainer.fit(my_model)

6 frames
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py in _with_is_last(self, iterable)
     43         """Pass through values from the given iterable with an added boolean indicating if this is the last item.
     44         See `https://stackoverflow.com/a/1630350 <https://stackoverflow.com/a/1630350>`_"""
---> 45         it = iter(iterable)
     46         last = next(it)
     47         for val in it:

TypeError: 'NoneType' object is not iterable

----------------------------------------------------------------------------------------------
I was able to load my checkpoint and get the original WER, but i could not proceed to further train it.

I have tried extracting my .nemo checkpoint file and find that it holds another my_checkpoint.nemo zip file that contains two other files which is model_config.yaml and model_weights.ckpt.

Am I loading the correct checkpoint file type? It says NoneType object is not iterable, I am guessing there is a problem with the format of my checkpoint?

Thank you in advance.

**Environment overview (please complete the following information)**

 - Environment location: Colab
 - Method of NeMo install: Pip install

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:

- PyTorch version: 1.7.1
- Python version: Python 3

**Additional context**
- none

**Comment by okuchaiev** [comment]
can you please try with the latest main branch and re-open if the issue still exists
