### ISSUE TITLE
Which character encoding should I use to generate train.json and eval.json for none English dataset [TTS]?

### ISSUE THREAD

**Issue by ican24** [NVIDIA/NeMo#202]
Dear Team,

Firstly thank you for your amazing/revolutionary project. 
You are really doing a fantastic job. 

I had tried to use scripts/get_ljspeech_data.py to prepare my dataset. It encoded unicode none Emglish text instead of UTF8.
Is it a correct option for none Emglish/ACSII text?

**Comment by Slyne** [comment]
Do you use your own dataset ?
I think get_ljspeech_data.py only tries to generate the manifest (.json) files.
You may use your own script to generate the files. The files may look like this:
```
{"audio_filepath": "<absolute_path_to>/1355-39947-0000.wav", "duration": 11.3, "text": "psychotherapy and the community both the physician and the patient find their place in the community the life interests of which are superior to the interests of the individual"}
{"audio_filepath": "<absolute_path_to>/1355-39947-0001.wav", "duration": 15.905, "text": "it is an unavoidable question how far from the higher point of view of the social mind the psychotherapeutic efforts should be encouraged or suppressed are there any conditions which suggest suspicion of or direct opposition to such curative work"}
```
Each line is a json object.

BTW, if there are some non ASCII characters, you may need to set ensure_ascii=False, like this:
```
 json.dumps(
                        {
                            'audio_filepath': os.path.abspath(audio_path),
                            'duration': duration,
                            'text': text
                        },
                        ensure_ascii=False))
```

**Comment by ican24** [comment]
Thank you very much!
I needed this confirmation to start my development.
