### ISSUE TITLE
NaN values on Arm Processor - QuartzNet [Question]

### ISSUE THREAD

**Issue by ulucsahin** [NVIDIA/NeMo#2035]
**Describe your question**

Hello, I trained an ASR model for speech to text conversion. My model has decent accuracy and I want to use this model on a device with ARM Cortex-A72 processor.

I am doing inference using EncDecCTCModel.transcribe. Everything is fine on Windows and Ubuntu with x86 architecture. However, when doing inference on device with Arm processor, I am getting either a single character transcription or an empty transciption. I checked the input to see if audio file was loaded correctly and it was correct. 

I set the seed to 0 on all my devices to check array values and I tracked down the issue to following line  in nemo/collections/asr/models/ctc_models.py:
`encoded, encoded_len = self.encoder(audio_signal=processed_signal, length=processed_signal_length)`

encoded values are same on arm and x86 devices with very small differences, however, I am getting lots of "nan" values in log_tensor values on arm device in the next line:
`log_probs = self.decoder(encoder_output=encoded)`

I am guessing my result gets messed up due to these values. I tried with different environments but the problem persists. 

Is there a way to make this work on Arm processors? I don't have gpu on my device with arm processor so I have to do the computation on Arm processor itself (raspberry pi 4).

I am fine with alternate solutions such as exporting the model (if that is going to solve it).

**Environment overview (please complete the following information)**

 - Environment location: Tested on Raspberry Pi 4, Windows and Ubuntu devices. Tested both with and without docker.
 - Method of NeMo install: Tested pip installation and building from source.

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 20.04, Windows 10
- PyTorch version: Tested both 1.7.1 and 1.9
- Python version: 3.8

**Additional context**

CPU Model: Arm Cortex-A72, Intel i5

**Comment by okuchaiev** [comment]
I am not sure what kind of precision is used for computation by your Arm processor. 
Is it IEEE float32? Then it should work. However, if it is something else, then precision-related issue would be likely.
