### ISSUE TITLE
Docker can't be build using last Dockerfile

### ISSUE THREAD

**Issue by asher-bs** [NVIDIA/NeMo#2040]
Trying to build Nemo Docker image fails when using the last Dockerfile
(Also when trying do use also other docker file in the zip at  https://github.com/NVIDIA/NeMo/releases/tag/v1.0.0rc1)

Step 12/29 : WORKDIR /tmp/nemo
 ---> Running in 9b5b7d241aee
Removing intermediate container 9b5b7d241aee
 ---> e5fe9b0fabe1
Step 13/29 : COPY requirements .
COPY failed: file not found in build context or excluded by .dockerignore: stat requirements: file does not exist

**Comment by okuchaiev** [comment]
https://github.com/NVIDIA/NeMo/pull/2054

**Comment by asher-bs** [comment]
Using the last DockerFile still get same problem 

Using /opt/conda/lib/python3.8/site-packages
Finished processing dependencies for pytorch-quantization==2.1.0
Removing intermediate container 46d355fa5012
 ---> 481e54a4d4dd
Step 12/29 : WORKDIR /tmp/nemo
 ---> Running in 52bbd41fe5e9
Removing intermediate container 52bbd41fe5e9
 ---> e7f41ad30f24
Step 13/29 : COPY requirements .
COPY failed: file not found in build context or excluded by .dockerignore: stat requirements: file does not exist

**Comment by okuchaiev** [comment]
I am unable to reproduce - please used built and published docker for 1.0.0rc1

**Comment by fayejf** [comment]
Are you using ` docker build - < Dockerfile` ?  @asher-bs 

> "This will read a Dockerfile from STDIN without context. Due to the lack of a context, no contents of any local directory will be sent to the Docker daemon. Since there is no context, a Dockerfile ADD only works if it refers to a remote URL."

Please use `docker build -f Dockerfile -t <container_name> .` as suggested in  https://github.com/NVIDIA/NeMo/pull/3223
