### ISSUE TITLE
 PyTorch container  20.11-py3 contains pytorch version 1.8 not 1.7.1

### ISSUE THREAD

**Issue by asher-bs** [NVIDIA/NeMo#2049]
NVIDIA's PyTorch container version 20.11-py3 contains 
torch                     1.8
but "version currently does not support Pytorch 1.8.0"

**Comment by okuchaiev** [comment]
this is not a bug. The container version looks like 1.8.0"something" - where "something" is commit id pre 1.8.0 release but a little after 1.7.1
