### ISSUE TITLE
Is there multi-lingual support for NeMo? I am looking particularly for a Hindi model.

### ISSUE THREAD

**Issue by ramrahu** [NVIDIA/NeMo#2057]
Hello,

Does NeMo ASR support Hindi and other languages? Will there be any tutorial/doc released any time soon on how to use NeMo ASR for multi lingual training?

**Comment by okuchaiev** [comment]
yes, we support other languages https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/results.html 
But at the moment, we don't have Hindi ASR model.
