### ISSUE TITLE
VAD speech time intervals

### ISSUE THREAD

**Issue by SaimNaz** [NVIDIA/NeMo#2081]
Hi, I want to extract the speech time intervals from the audios using VAD (vad_marbelnet) model. Is there a direct method (function) to do it without modifying the config file?

**Comment by fayejf** [comment]
Thanks for your question.
Yes. Have a look at **_VAD diarization_** part in diarization [tutorial](https://github.com/NVIDIA/NeMo/blob/r1.0.0rc1/tutorials/speaker_recognition/Speaker_Diarization_Inference.ipynb )  which will generate VAD RTTM-like json file that could suit your request.

**Comment by SaimNaz** [comment]
Yes, thank you for the response.
