### ISSUE TITLE
Can't Install nemo_text_processing

### ISSUE THREAD

**Issue by mschonwe** [NVIDIA/NeMo#2083]
I'm following the instruction in
`https://github.com/NVIDIA/NeMo/blob/main/tutorials/text_processing/Text_Normalization_Tutorial.ipynb`

Running code on a docker container `nvcr.io/nvidia/nemo:1.0.0rc1`

There are no errors when running the suggested install code:
```
BRANCH = 'main'
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[nlp]
```
Many lines of `Requirement already satisfied:...`

However, the `import nemo_text_processing` fails:
```
ModuleNotFoundError: No module named 'nemo_text_processing'
```

**Comment by yzhang123** [comment]
@mschonwe we changed a few things regarding normalization since 1.0.0rc, e.g. packaged it up in `nemo_text_processing`.
 please refer to RC tutorial https://github.com/NVIDIA/NeMo/tree/r1.0.0rc1 which is tested to work in nvcr.io/nvidia/nemo:1.0.0rc1.
To use current code in `main` please wait until we release 1.0.0 container or manually build the container, thanks!

**Comment by mschonwe** [comment]
Inside a fresh `nvcr.io/nvidia/nemo:1.0.0rc1` container, I run:

`python3 -m pip install --upgrade --force-reinstall git+https://github.com/NVIDIA/NeMo.git@r1.0.0rc1#egg=nemo_toolkit[nlp]`

and get the error:
```
`ERROR: Could not find a version that satisfies the requirement torch==1.8.0a0+17f8c32 (from nemo_toolkit[nlp]) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==1.8.0a0+17f8c32 (from nemo_toolkit[nlp])
```

**Comment by mschonwe** [comment]
Thank you.  Got it working following the updated tutorial.

**Comment by yzhang123** [comment]
@mschonwe  we will be soon changing text normalization to WFST just like inverse text normalization, just FYI
