### ISSUE TITLE
Inverse Text Normalization doesn't work for upper-cased words

### ISSUE THREAD

**Issue by taufique74** [NVIDIA/NeMo#2097]
**Bug Description**

Inverse Text Normalization text-processing fails to normalize a verbal form if it has a word with an upper case.
While I understand that the transcriptions are usually all-lower cased words, it'd be nice if we lower the text before passing it to `inverse_normalizer`.

**Steps to reproduce bug**

Let's create a text file `input.txt` containing the following information:
```text
one thousand and seventy four
One thousand and seventy four
one Thousand and seventy four
one thousand And seventy four
one thousand and Seventy four
one thousand and seventy Four
```
if we run `python run_predict.py --input=input.txt --output=output.txt`, the  generated `output.txt` will contain the following results:
```text
1074
One thousand and 74
one Thousand and 74
1000 And 74
1000 and Seventy four
1070 Four
```

So only the first line that contains all lower-cased words was correctly normalized.

**Environment overview**

- Environment location: Cloud(AWS)
- Method of NeMo install: from source

**Environment details**

- OS version: Ubuntu 18.04.5 LTS
- PyTorch version: 1.8.1+cu102
- Python version: 3.7

**Comment by taufique74** [comment]
@yzhang123

**Comment by yzhang123** [comment]
@taufique74 this is true, we do not handle upper cased words at this point, since we assume its the output of the asr model. please lower case your input
