### ISSUE TITLE
Keyword spotting in NEMO

### ISSUE THREAD

**Issue by MelikaBahmanabadi** [NVIDIA/NeMo#2111]
I am contacting you today to request information about detecting keywords from audio using NEMO ASR.
I am very interested in finding out if NEMO supports keyword spotting.

Regards,
Melika Bahman-Abadi

**Comment by fayejf** [comment]
Hi @MelikaBahmanabadi Thanks for your question.
We have Voice Activity Detection support ([tutorial](https://github.com/NVIDIA/NeMo/blob/r1.0.0rc1/tutorials/asr/06_Voice_Activiy_Detection.ipynb)) in NeMo. For KWS I think you can start with that and train on data to have a classier to handle `the keyword vs. others`. 

if you are interested multi-word keyword spotting. You can use the combination of VAD and Keyword detection. If you are interested in this approach, have a look at the [03 tutorial](https://github.com/NVIDIA/NeMo/blob/r1.0.0rc1/tutorials/asr/03_Speech_Commands.ipynb) that talks about keyword detection training and finetuning on the new dataset, and [04 tutorial](https://github.com/NVIDIA/NeMo/blob/r1.0.0rc1/tutorials/asr/04_Online_Offline_Speech_Commands_Demo.ipynb)  that talks about VAD+keyword detection inference.
