### ISSUE TITLE
I get an incompatible library version error 

### ISSUE THREAD

**Issue by fnsrc** [NVIDIA/NeMo#2112]
I run the code in https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/06_Voice_Activiy_Detection.ipynb, however I got again an error while runing below cell:

  1 # NeMo's "core" package
----> 2 import nemo
3 # NeMo's ASR collection - this collections contains complete ASR models and
4 # building blocks (modules) for ASR
5 import nemo.collections.asr as nemo_asr

11 frames
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/apply_func.py in ()
23 TORCHTEXT_AVAILABLE = importlib.util.find_spec("torchtext") is not None
24 if TORCHTEXT_AVAILABLE:
---> 25 from torchtext.data import Batch
26 else:
27 Batch = type(None)

ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/init.py)

and I got another error when I run below cell:
AttributeError Traceback (most recent call last)
in ()
----> 1 exp_dir = exp_manager(trainer, config.get("exp_manager", None))

1 frames
/content/MyVADNeMo/nemo/utils/exp_manager.py in get_log_dir(trainer, exp_dir, name, version, explicit_log_dir, use_datetime_version)
428 if trainer.logger.save_dir:
429 if exp_dir:
--> 430 raise LoggerMisconfigurationError(
431 "The pytorch lightning trainer that was passed to exp_manager contained a logger, the logger's "
432 f"save_dir was not None, and exp_dir ({exp_dir}) was not None. If trainer.logger.save_dir "

AttributeError: 'Trainer' object has no attribute 'is_slurm_managing_tasks'.

Thanks in advance!

**Comment by okuchaiev** [comment]
(1) Please try running it Google's Colab (which would have a clean environment and should work)
(2) If you try running it locally, I'd recommend creating a new conda environment with Python 3.8 (and without Pytorch, Torchtext, etc.). This way when you do "pip install ..." correct versions of torch and torchtext should be installed.
(3) Also, you can try using our container: ```docker run --gpus all -it --rm --shm-size=8g \
-p 8888:8888 -p 6006:6006 --ulimit memlock=-1 --ulimit \
stack=67108864 --device=/dev/snd nvcr.io/nvidia/nemo:1.0.0rc1```
