### ISSUE TITLE
How about supporting BPE in ASR

### ISSUE THREAD

**Issue by Slyne** [NVIDIA/NeMo#215]
I find many papers using BPE as modelling units, so
I was wondering if it is possible to change current char-based ASR to tokenizer based (like nlp).
By using a custom tokenizer, it may help to reuse tokenizers in NLP collection. (Maybe we should put some common tools into one utils or collections, like the models and utility functions).
And users can use whatever modelling units they want.

Potential problems:
1. Currently every example script is char based, including helpers.py. 
2. The beam search decoder now only supports char based models. (It requires a vocab file.)
The ctc_beam_search_with_lm works like this:
First, it will detect the language model used is char-based or word based by simply checking the length of the unigrams. If there is one unigram whose length is greater than 1, then it is word based, otherwise it is char based.

On ngram language model built on words like english LM, it will detect whether the current character is space. If it is a space, it will call language model function to detect the LM score.
On ngram LM built on charaters like some mandarin LM, it will call everytime it appends a new character (a new prefix generated).
In order to make beam search with LM available for all modelling units, we may need to change the decoder code to let it support this feature.

Of course, if we only want to use greedy search on different modelling units or only use beam search on char-based model, there will be no problem.

**Comment by okuchaiev** [comment]
This is something on to-do list. If you are interested - you are welcome to try! We did some experiments where RNNDecoder with Attention or Transformer decoder from NLP collection are used instead of JasperDecoder and Sequence Loss instead of CTC loss. For that model, it might be easier to use tokens rather than character. 
see this, for example, https://github.com/NVIDIA/NeMo/blob/r0.8.2/examples/asr/garnet.py
Adding BPE support to CTC model does require some code change as you mentioned above and might be worth trying.

**Comment by Slyne** [comment]
I did an experiment on Jasper as encoder and Transformer as decoder with ctc and xent as two losses in order to make use of transformer to better train Jasper. In this experiment, I use bpe as modelling units. But I just find if we want to make current example scripts to be compatible, it requires me to accept one parameters of two different types like a tokenizer or a vocab list.  Not sure if this is ok to modify the code in this way ...

**Comment by blisc** [comment]
This is my current script for Jasper -> Transformer with CTC and XEnt. I just pass Jasper labels in the config and the BPE tokenzier file as a cmd line argument.
https://github.com/blisc/NeMo/blob/garnet_transformer/examples/asr/garnet_xformer.py

**Comment by Slyne** [comment]
@blisc Thanks! I also tried a similar one. Maybe we can share the experiment results later.
