### ISSUE TITLE
Failed to build Tacotron2 in Jarvis

### ISSUE THREAD

**Issue by thcktw** [NVIDIA/NeMo#2154]
I trained Tacotron2 in Thai language using NeMo and it failed to build jmir format.
I use command for build jmir like in https://docs.nvidia.com/deeplearning/jarvis/user-guide/docs/service-tts.html#pipeline-configuration .

![image](https://user-images.githubusercontent.com/16872939/117111657-231fc280-adb2-11eb-97ea-0657c420ec11.png)

![image](https://user-images.githubusercontent.com/16872939/117111684-2ca92a80-adb2-11eb-90bb-ced61e68346f.png)

I tried to use Tacotron2 that provides in https://ngc.nvidia.com/catalog/models/nvidia:tlt-jarvis:speechsynthesis_english_tacotron2/files and its works.
What is different between these two nemo files?

**Comment by azahed98** [comment]
Hello,
It looks like your nemo file does not have the model weights checkpoint that should be saved. Can you untar the nemo file and make sure it has a model_weights.ckpt and model_config.yaml? If it doesn't, please let me know what the contents are.

**Comment by thcktw** [comment]
> Hello,
> It looks like your nemo file does not have the model weights checkpoint that should be saved. Can you untar the nemo file and make sure it has a model_weights.ckpt and model_config.yaml? If it doesn't, please let me know what the contents are.

I untar my nemo file and it has a model_weights.ckpt and model_config.yaml.
This my nemo file -> https://drive.google.com/file/d/1NAJoB_jRWofkTKT8aox8CBTm4M41yul5/view?usp=sharing

**Comment by thcktw** [comment]
Hi @azahed98, Do you have any suggestions?

**Comment by azahed98** [comment]
I found a workaround for you. The expected contents is is
`model_config.yaml
model_weights.ckpt`

However, the contents of your file has a preceding directory
`./
./model_config.yaml
./model_weights.ckpt`

You should untar your file into a directory, and retar it but without a preceding directory.

**Comment by thcktw** [comment]
Now, It works. 
Thanks.
