### ISSUE TITLE
ITN fails to normalize telephone numbers with zero in them

### ISSUE THREAD

**Issue by taufique74** [NVIDIA/NeMo#2161]
ITN fails to normalize telephone numbers like this `five four two one two nine seven zero six five`
It works fine after replacing `zero` with `o`

I think this is because `zero` is in `zero.tsv` not `digit.tsv`, and you are not including `zero.tsv` in the digit FST.
https://github.com/NVIDIA/NeMo/blob/74f1264e049c10b012a1ea483fcd468f4d89ecf8/nemo_text_processing/inverse_text_normalization/taggers/telephone.py#L38

Also, it's quite common for ASR to output `oh` instead of `o`, like this `five oh seven` (507).
So do you think we can add two more rules like this?
```python
digit = ( pynini.invert(pynini.string_file(get_abs_path("data/numbers/digit.tsv"))).optimize() 
             | pynini.cross("0", "o") 
             | pynini.cross("0", "zero")
             | pynini.cross("0", "oh")
) 
```

@yzhang123

**Comment by yzhang123** [comment]
thanks for feedback, will add.
