### ISSUE TITLE
Quartz: issues in replicating results 

### ISSUE THREAD

**Issue by Giuseppe5** [NVIDIA/NeMo#217]
Hi,

I am trying to use the NeMo implementation of Quartz to replicate the results presented in this [paper](https://arxiv.org/pdf/1910.10261.pdf).

However I am facing some issues. First of all, the pretrained encoder model has a different structure with respect to the one implemented in Nemo. In particular, to be able to load the state dictionary I had to modify Masked1DConv to inherit from 1DConv (as in the original Jasper implementation).
Moreover there are discrepancies with the names of the layers that has to be fixed to be able to load properly the pretrained model.

After my attempts at fixing these issues, I still was not able to reach the performances mentioned in the paper. I tried evaluating on dev_other, and I reached 16.9% in terms of WER, which is much higher compared to 11.58% reported on the paper.

I used the configuration file and the pretrained model that can be found [here](https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5).

The validation is run inside a docker container built starting from the Dockerfile available in the repo. The only minor difference regards the version of the pytorch image used, that is the 19.09 instead of 19.11 because of some issues with CUDA drivers that wouldn't allow me to use the GPUs.

Any help would be much appreciated. Thank you!

**Comment by Giuseppe5** [comment]
Starting from 0.8.2 everything seems to work just fine, with results that are slightly better than the ones reported on the paper for dev_clean.

Thank you for your time and answer!

**Comment by Oktai15** [comment]
@okuchaiev @Giuseppe5 what was the main difference between 0.9 and 0.8.2 to reproduce LibriSpeech results? I have the same problem with current master.
