### ISSUE TITLE
requirements.txt should limit pytorch-lightning to 1.2.10 (max), avoiding 1.3.* for now

### ISSUE THREAD

**Issue by jprobichaud** [NVIDIA/NeMo#2185]
Some interface changes in 1.3.0 (at least around pl.ModelCheckpoint), breaks some expectation in the current code base.  

`requirements/requirements.txt`  has `pytorch-lightning>=1.2.8` which could lead the installation of pytorch-lightning 1.3.0.  

Or aybe you are already planning on supporting 1.3.0?

**Comment by titu1994** [comment]
This should be fixed via https://github.com/NVIDIA/NeMo/pull/2178
