### ISSUE TITLE
Proper data (size & form) for fine-tunining speaker verification model

### ISSUE THREAD

**Issue by JINHXu** [NVIDIA/NeMo#2186]
Hey there,

I was trying to fine-tune the pre-trained speaker recognition model [`Speakernet`](https://ngc.nvidia.com/catalog/models/nvidia:nemo:speakerrecognition_speakernet) in order for it to recognize our registered speakers. I noticed in the tutorials the dataset `an4` was only used for illustration purposes, I wonder in real cases, how much data would be considered reasonable for fine-tuning? For example, in our system, we have about 15 registered users, whose voice would need to be recognized through about 4 seconds of speech for inference. Would it be enough to fine-tune with 20 recordings of about 5 seconds of each user's speech? Or might it be a better idea to try to gather the long speech of the users (10 recordings of 30 seconds speech for instance)? Thank you for your help in advance!

Cheers,
Xu

**Comment by nithinraok** [comment]
It's better to have higher number_of_samples/speaker with shorter durations (of about 4 sec) than vice versa.

**Comment by JINHXu** [comment]
Hi, @nithinraok  Thank you!
