### ISSUE TITLE
Issue while installing swig

### ISSUE THREAD

**Issue by harisankarh** [NVIDIA/NeMo#22]
Note: commands executed inside the container

1) While following the instructions from [https://nvidia.github.io/NeMo/asr/tutorial.html#inference](url) for using klm, got an error like "swig package not available" while running `apt-get install swig`.

This was fixed by running `apt-get update` before running `apt-get install swig`. 

2) Also sudo (in `sudo apt-get install swig`) is not required inside container.

3) install_decoders.sh was failing with gcc error. Had to run the following to fix it:
`apt-get install ssh pkg-config libflac-dev    libogg-dev libvorbis-dev     libboost-dev swig     python-dev git-core libsndfile1-dev  python-setuptools libboost-all-dev` //NOTE: I'm not sure if all the dependencies are required

**Comment by okuchaiev** [comment]
hi @harisankarh thanks for noticing this issue and suggesting a fix!
I've updated the documentation accordingly.
