### ISSUE TITLE
Support cloud-based storage for checkpoints

### ISSUE THREAD

**Issue by piraka9011** [NVIDIA/NeMo#2204]
**Is your feature request related to a problem? Please describe.**

I would like to store my checkpoints/models using AWS/GCP so that when I run training on ephemeral instances, I don't lose my progress. 

**Describe the solution you'd like**

Register a new callback on epoch end to upload the ckpt/Nemo file to AWS/GCP if the option is passed in the config file via the trainer (using the checkpoint callback field)

**Describe alternatives you've considered**

None, open to discussion though. 

**Additional context**

I have a working implementation for a local repo, but would like to gauge interest for upstream support in NeMo before submitting a PR.

**Comment by okuchaiev** [comment]
Closing. re-open if issue is still relevant.
