### ISSUE TITLE
TarredAudioToTextDataset assumes audio is always wav

### ISSUE THREAD

**Issue by piraka9011** [NVIDIA/NeMo#2218]
**Describe the bug**

`TarredAudioToTextDataset` assumes audio is `wav`. However I was able to train a model with `mp3` files and would like `TarredAudioToTextDataset` to support other file types.

**Steps/Code to reproduce bug**

Use any dataset with non-wav files.

**Expected behavior**

Model should be trainable with non-wav tarred datasets

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal
 - Method of NeMo install: pip install nemo['all']==1.0.0rc1

**Environment details**

Otherwise, please provide:
- OS version: Ubuntu 20.04
- PyTorch version: 1.7.1
- Python version: 3.8

**Additional context**

My suggestion is to simply add another field to the `*_ds` config called `file_format` or `file_extension` which can be one of a list of supported files by `soundfile`.
Can submit a PR if this is fine, but some guidance/feedback on the approach first would be good.

**Comment by titu1994** [comment]
We generally don't prefer to have other file formats for efficiency reasons (wav takes storage but at least it prevents on the fly resampling to 16khz monochannel audio). 

Tarred datasets are meant for distributed training on clusters, where network I/O can have a significant impact on training speed. Likewise, it would be unwise to spend compute for such expensive resampling on the CPU repeatedly per sample.

I'll look into what's correctly preventing Tarred datasets of ASR from working with other file formats in any case.

**Comment by piraka9011** [comment]
I should've left a more detailed trace, sorry.
The issue happens [here](https://github.com/NVIDIA/NeMo/blob/489bb241a6ed727b4d7ad3213242772a7628ff55/nemo/collections/asr/data/audio_to_text.py#L920) where the `webdataset` try's to rename the audio key from `wav`.

Instead, this should be an arg passed to `_TarredAudioToTextDataset`.

**Comment by titu1994** [comment]
That makes sense, thanks for the hint!
