### ISSUE TITLE
TIMIT ?

### ISSUE THREAD

**Issue by TParcollet** [NVIDIA/NeMo#222]
Hi there !

Do you have a TIMIT recipe already existing?

Thanks for the toolkit!

**Comment by okuchaiev** [comment]
Hi, we currently don't have any TIMIT recipe (never tried). But this could be a good first PR! ;)

If you want something small - checkout AN4 dataset, in fact, we use it as part of our CI pipeline tests https://github.com/NVIDIA/NeMo/blob/master/examples/asr/jasper_an4.py

AN4 is also used in this example tutorial https://github.com/NVIDIA/NeMo/blob/master/examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb
