### ISSUE TITLE
FastSGD vs SGD-QA

### ISSUE THREAD

**Issue by KadarTibor** [NVIDIA/NeMo#2221]
I am doing some research related to dialogue state tracking and I have found this paper (https://arxiv.org/pdf/1805.01555.pdf).
While checking out the code I see that it has been removed from this repository as of version v1.0.0.b1

I see that for dialogue state tracking there is a new model called SGD-QA which is a multi-pass type model as opposed to FastSGD. 

My questions are the following:
- Why was FastSGD removed? 
- Where can I find some documentation regarding SGD-QA?

**Comment by VahidooX** [comment]
+ Why was FastSGD removed?
When we moved to PTL, it got removed as we did not have enough time to import it into the new version of NeMo. We may be able to import that model in the near future if time permits.
However you can still use it with older version of NeMo here: 
https://github.com/NVIDIA/NeMo/blob/ner_0.11/examples/nlp/dialogue_state_tracking/dialogue_state_tracking_sgd.py

And you can find the documentation here:
http://nemo-master-docs.s3-website.us-east-2.amazonaws.com/nlp/dialogue_state_tracking_sgd.html

+ Where can I find some documentation regarding SGD-QA?
 I think here is the only place you may find some detail about SGD-QA:
 https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/dialogue_state_tracking/sgd_qa.py
 @yzhang123 may be able to provide more info on SGD-QA.

**Comment by KadarTibor** [comment]
Thank you for the fast reply! I noticed I linked the wrong paper, my apologies, wanted to link (https://arxiv.org/pdf/2008.12335.pdf).

**Comment by yzhang123** [comment]
@KadarTibor I have uploaded the SGD-QA paper to Arxiv. Will be ready in 1-2 days.

**Comment by KadarTibor** [comment]
That's amazing! Thank you 🙏

**Comment by yzhang123** [comment]
https://arxiv.org/abs/2105.08049
