### ISSUE TITLE
About QA_Squad

### ISSUE THREAD

**Issue by blackbirt-5** [NVIDIA/NeMo#2222]
Hi,

I tested your tutorial for QA_squad and changed the tutorial code to apply Biomegatron.
But I got an error message during apply biomegatron.
So, would you help to solve this problem?
![Error_Message](https://user-images.githubusercontent.com/82014275/118435026-07ed7500-b719-11eb-8bf0-dab6b8b0e3a2.jpg)
![Pretrained_model](https://user-images.githubusercontent.com/82014275/118435029-091ea200-b719-11eb-8855-b06d9788d2c6.jpg)
![Pretrained_model2](https://user-images.githubusercontent.com/82014275/118435030-09b73880-b719-11eb-9626-3d908cc140cd.jpg)

Best Regards,
From Simon 

Blow I showed the code changed model.

1.Changed Pretrained_Bert_Model
# This is the model configuration file that we will download, do not change this
MODEL_CONFIG = "question_answering_squad_config.yaml"

# model parameters, play with these
BATCH_SIZE = 12
MAX_SEQ_LENGTH = 384
# specify BERT-like model, you want to use
PRETRAINED_BERT_MODEL = "**biomegatron-bert-345m-uncased**" -> changed
TOKENIZER_NAME = "**biomegatron-bert-345m-uncased**" -> changed

2.Changed Pretrained_model
# load pretained model
pretrained_model_name="**qa_squadv1.1_megatron_uncase**d" -> changed
model = nemo_nlp.models.QAModel.from_pretrained(model_name=pretrained_model_name)

3.Error Message
I got the these error message.

[NeMo I 2021-05-13 07:44:44 megatron_utils:269] Downloading from https://api.ngc.nvidia.com/v2/models/nvidia/biomegatron345muncased/versions/0/files/MegatronBERT.pt
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-18-762ee4f9b73a> in <module>()
      1 # initialize the model
      2 # dataset we'll be prepared for training and evaluation during
----> 3 model = nemo_nlp.models.QAModel(cfg=config.model, trainer=trainer)

7 frames
/usr/local/lib/python3.7/dist-packages/megatron/global_vars.py in _ensure_var_is_not_initialized(var, name)
    150 def _ensure_var_is_not_initialized(var, name):
    151     """Make sure the input variable is not None."""
--> 152     assert var is None, '{} is already initialized.'.format(name)
    153 
    154 

AssertionError: args is already initialized.

**Comment by yzhang123** [comment]
you can not initialize two models within same notebook for Megatron, i.e. initialize the model , change the type and initialize again. Could you reset your notebook before you initialize the model?

**Comment by blackbirt-5** [comment]
Thanks for your recommend.
According to your advice, I tried two times.

1st Trail: No Problem
  I Just switched the pretrained model.
   pretrained_model_name="qa_squadv1.1_bertbase"

2nd Trail: Occurred Error.
  Instead of bert-base-uncased, I used 'biomegatron-bert-345m-uncased."
  Please refer to the attached file.  

Could you give me any advice on using biomegatron for the relation extraction of biomedical document? 
[Megatron_Trial.pptx](https://github.com/NVIDIA/NeMo/files/6498847/Megatron_Trial.pptx)

Best Regards.

**Comment by yzhang123** [comment]
@blackbirt-5 please use for tokenizer for your biomegatron checkpoint bert-large-uncased, you should be also able to set it to null
