### ISSUE TITLE
Drop last layer

### ISSUE THREAD

**Issue by carlfm01** [NVIDIA/NeMo#223]
I want to test the English checkpoint in a new alphabet for Spanish, is it possible to drop layers to train in a new alphabet?

**Comment by okuchaiev** [comment]
Absolutely, this is one of the scenarios NeMo was designed for.
For Jasper or Quartznet take pretrained English encoder module but have your own decoder randomly initialized and projecting into Spanish vocabulary. Then finetune on Spanish dataset

**Comment by carlfm01** [comment]
Oh I see now, thanks.
