### ISSUE TITLE
Manifest files error with custom data for finetuning ASR models

### ISSUE THREAD

**Issue by varunsingh3000** [NVIDIA/NeMo#2234]
Hi, I am using the ASR with NeMo tutorial notebook on colab ([https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0rc1/tutorials/asr/01_ASR_with_NeMo.ipynb](url). It works fine for the an4 dataset. But I am trying to do this with the VOiCES dataset (https://iqtlabs.github.io/voices/). As per the tutorial I think I only need to supply the manifest files in the proper format for training and testing. I am running this on colab with the `QuartzNet15x5Base-En`

I have formatted the manifest files in which they specify but while running
`from omegaconf import DictConfig`
`params['model']['train_ds']['manifest_filepath'] = train_manifest`
`params['model']['validation_ds']['manifest_filepath'] = test_manifest`
`first_asr_model = nemo_asr.models.EncDecCTCModel(cfg=DictConfig(params['model']), trainer=trainer)`

I keep getting the JSONDecodeError: Expecting value: line 2 column 1 (char 1).

Below I have attached my manifest file screenshot and the manifest file screenshot generated in the tutorial, they both appear to be identical in format so I'm wondering what seems to be the problem. I am guessung specifying "text" or "duration" in different orders shouldn't matter.

an4 dataset manifest screenshot
![an4 manifest](https://user-images.githubusercontent.com/64498789/118785567-9a734d00-b8ae-11eb-8e8a-434e39498061.JPG)

voices dataset manifest screenshot
![voices manifest](https://user-images.githubusercontent.com/64498789/118786675-b0cdd880-b8af-11eb-9258-1381b48ba1ce.png)

Is there something else I need to change to fine tune with my dataset?

Any help would be appreciated.

Thanks.

**Comment by titu1994** [comment]
Could you post the full error log. Hard to tell where exactly it fails to decode the json - beginning or end. Could you make sure your voices manifest does not have any additional space or new lines at end end ?

**Comment by varunsingh3000** [comment]
[test_index.zip](https://github.com/NVIDIA/NeMo/files/6525850/test_index.zip)

**Comment by VahidooX** [comment]
It looks like you have two extra empty lines at the end of your manifests. Please remove them and try again.

**Comment by titu1994** [comment]
Good catch. I tried parsing it with python and didn't notice the extra line at the end. Removing it so there's just 1 line fixed it locally. That would be the fix @varunsingh3000

**Comment by varunsingh3000** [comment]
Worked like a charm. Thanks @VahidooX and @titu1994
