### ISSUE TITLE
Cant download model

### ISSUE THREAD

**Issue by sadia95** [NVIDIA/NeMo#2255]
Please help me resolve this. I am not able to download the model and get an error later that cant download from url.

![error11](https://user-images.githubusercontent.com/50978534/119278039-31c7ff80-bc23-11eb-99ba-059a106d2f99.PNG)

**Comment by titu1994** [comment]
Was able to download just now. Could you retry - maybe some issue with the server in the last attempt?

**Comment by sadia95** [comment]
I am getting the same error again and again. I am actually downloading it on a cluster. That could be the reason?

**Comment by titu1994** [comment]
If the cluster does not have access to the internet (other than the local intranet), then yes.
