### ISSUE TITLE
'num_speakers' missing from config file for speaker diarization

### ISSUE THREAD

**Issue by cjameyson** [NVIDIA/NeMo#2256]
`num_speakers` is missing from `NeMo/examples/speaker_recognition/conf/speaker_diarization.yaml`

Which causes the tutorial for ASR_with_SpeakerDiarization.ipynb to break on this code cell:

```
from nemo.collections.asr.models import ClusteringDiarizer
oracle_model = ClusteringDiarizer(cfg=config);
oracle_model.diarize();
```

For the following error:
```
ConfigAttributeError: Key 'num_speakers' is not in struct
	full_key: diarizer.num_speakers
	reference_type=Any
	object_type=dict

```

nemo.__version__ = '1.0.0rc1'

**Comment by nithinraok** [comment]
Hi @cjameyson , 
You are probably using a notebook from main branch but codebase version `1.0.0rc1`, 
we changed `num_speakers` to `oracle_num_speakers` which takes number of speakers per input session else None, also included `max_num_speakers` option. 
Refer to this section for more info:
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/speaker_diarization/configs.html 
https://github.com/NVIDIA/NeMo/blob/main/examples/speaker_recognition/conf/speaker_diarization.yaml

**Comment by cjameyson** [comment]
I see, thanks @nithinraok!
