### ISSUE TITLE
TTS User Guide

### ISSUE THREAD

**Issue by jsilbergDS** [NVIDIA/NeMo#2262]
Please note the TTS user guide quick start seems to have two issues (https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/tts/intro.html):

1) More easily solvable: spec_generator = SpectrogramGenerator.from_pretrained("tts_en_tacotron2") <- the variable should be named spec_gen to match the lines that follow

2) The last line:
sf.write("speech.wav", audio.to('cpu').numpy(), 22050)

This gives the error "RuntimeError: Error opening 'speech.wav': Format not recognised." I believe this is an error with soundfile, see: https://github.com/bastibe/python-soundfile/issues/203

EDIT: For issue 2, to fix this in Colab, simply create audio2 = audio.transpose(), which works. May just be an issue with the version of soundfile imported by Colab.

**Comment by blisc** [comment]
1) will be fixed in our upcoming release
Thanks for finding 2. I'll push a fix.

**Comment by jsilbergDS** [comment]
Thanks! On #2, this may just be an issue with what version Colab imports (so users not using Colab might not get the error with the current NeMo code, not sure?)

**Comment by blisc** [comment]
Should be fixed now. If not, please open another issue.
