### ISSUE TITLE
Normalizer and NormalizerWithAudio fail with dashed tokens eg "550-pound bomb"

### ISSUE THREAD

**Issue by sbuser** [NVIDIA/NeMo#2266]
**Describe the bug**

Example sentence fragments for text normalizer:
"It had 12-inch guns and a 21-knot cruising speed."
"Each 550-pound bomb exploded."

**Steps/Code to reproduce bug**

```python
from nemo_text_processing.text_normalization.normalize import Normalizer
from nemo_text_processing.text_normalization.normalize_with_audio import NormalizerWithAudio

normalizer = Normalizer(input_case='cased')
audio_normalizer = NormalizerWithAudio(input_case='cased')

texts = [
    "It had 12-inch guns and a 21-knot cruising speed.",
    "Each 550-pound bomb exploded.",
]

for text in texts:
    normalized_text = normalizer.normalize(text, verbose=False)
    print(normalized_text)

    normalized_texts = audio_normalizer.normalize_with_audio(text, verbose=False)
    print(normalized_texts)
```
The results from normalized_texts will be something like (notice the spaces between each letter in the word for the units):
"five hundred fifty p o u n d bomb"
and
"twenty one k n o t cruising speed"

It seems like the sparrow/pynini rules don't allow for dashed text input followed by a unit and interpret the unit as an abbreviation. The CER calculation in NormalizerWithAudio doesn't repair this because the results from normalize_with_audio() don't ever contain the expected outputs.

**Expected behavior**

"five hundred fifty pound bomb"
"twenty one knot cruising speed"

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal
 - Method of NeMo install: pip install from source, main branch

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version Ubuntu 20.10
- PyTorch version 1.7.1
- Python version 3.8.5

I'm trying to track down where in pynini or the nemo rules this is happening and if I find it I will follow-up.

**Comment by sbuser** [comment]
The taggers pick these examples up as Serials and not as Measures. The options with the spaces between the letters make sense if it's a Serial.

I think a modification to the tagger for Measure that allows the dash between Cardinal and Unit may do the trick. If I can figure out the syntax...

**Comment by ekmb** [comment]
Yes, this is a known issue, the fix is a part of the upcoming update. 
I'll update this bug when the PR is ready.

**Comment by sbuser** [comment]
My naive adjustment in measure.py is below. I'm not familiar with pynini syntax so I'm certain that's not a great solution but it works for now.

I also notice that the singular units aren't available as options in the results from normalize_with_audio() -- so while my kludge  will consider it a Measure, it verbalizes to "five hundred pounds bomb" and not "five hundred pound bomb" - which I would hope it would have the option to with audio support.

I'll be following the progress closely and am happy to help if I can get more familiar with pynini -- is this repo the best place to file / discuss similar issues?

```python
    def __init__(self, cardinal: GraphFst, decimal: GraphFst, deterministic: bool = True):
        super().__init__(name="measure", kind="classify", deterministic=deterministic)
        cardinal_graph = cardinal.graph

        graph_unit = pynini.string_file(get_abs_path("data/measurements.tsv"))
        graph_unit_plural = convert_space(graph_unit @ SINGULAR_TO_PLURAL)
        graph_unit = convert_space(graph_unit)
        optional_graph_dash =     pynini.cross("-", "")
        optional_graph_negative = pynini.closure(pynutil.insert("negative: ") + pynini.cross("-", "\"true\" "), 0, 1)

        graph_unit2 = pynini.cross("/", "per") + delete_space + pynutil.insert(NEMO_NON_BREAKING_SPACE) + graph_unit

        optional_graph_unit2 = pynini.closure(
            delete_space + pynutil.insert(NEMO_NON_BREAKING_SPACE) + graph_unit2, 0, 1,
        )

        unit_plural = (
            optional_graph_dash + 
            pynutil.insert("units: \"")
            + (graph_unit_plural + optional_graph_unit2 | graph_unit2)
            + pynutil.insert("\"")
        )

        unit_singular = (
            optional_graph_dash +
            pynutil.insert("units: \"") + (graph_unit + optional_graph_unit2 | graph_unit2) + pynutil.insert("\"")
        )
```
