### ISSUE TITLE
notebook for training nmt models

### ISSUE THREAD

**Issue by Troublem1** [NVIDIA/NeMo#2268]
Hi, I've been trying to use nemo for neural machine translation but i keep hitting a roadblock since the only for of intro notebook on this subject is the text2sparql.  Any intro notebook on the matter would be very helpful

**Comment by okuchaiev** [comment]
please have a look at the NMT docs: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/r1.0.0rc1/nlp/machine_translation.html
