### ISSUE TITLE
diarization example

### ISSUE THREAD

**Issue by sciai-ai** [NVIDIA/NeMo#2280]
Hi, I was trying the notebook for diarization from the main branch with max and orcle speakers. I noticed that for the default an4.wav file the confusion rate has increased to 0.4 whereas in the previous releases .1.r.c it used be zero meaning perfect diarization. May I know what has changed and how can we get better accuracy on the example wav file?

**Comment by nithinraok** [comment]
Hi @sciai-ai , thanks for the question. We are aware of this limitation with new NMSE Clustering schema we introduced. It has parameters that limits its performance for smaller samples, and works wonderfully for larger audio samples. 

In notebook, we used small audio sample hence the incorrect labels. While we push a fix for it, If you would like to use previous clustering algorithm you may just replace the following line  
https://github.com/NVIDIA/NeMo/blob/bee43e840837d7e30e17a65b972e9fe89ecb9ca5/nemo/collections/asr/parts/utils/speaker_utils.py#L259  with

`cluster_method = SpectralClusterer(min_clusters=2, max_clusters=NUM_speakers)    
`
`cluster_labels = cluster_method.predict(emb)`
