### ISSUE TITLE
AttributeError: module 'nemo.collections.nlp.models' has no attribute 'EntityLinkingModel'

### ISSUE THREAD

**Issue by Prathzee** [NVIDIA/NeMo#2288]
Hi Team,
As per Entity linking tutorial, release = **1.0.0rc1**, does not have **EntityLinkingModel** available.
We are getting error - 
AttributeError: module 'nemo.collections.nlp.models' has no attribute 'EntityLinkingModel'.

Could you please help us with the issue?

**Comment by VahidooX** [comment]
EntityLinkingModel is a new model and was not a part of 1.0.0rc1. You may use the main branch or wait for the release of 1.0.0 which is going to happen very soon.
