### ISSUE TITLE
Is it possible to use BeamSearchDecoderWithLM() method in asr in a Windows 10 system?

### ISSUE THREAD

**Issue by computervisionpro** [NVIDIA/NeMo#2311]
I tried using the above feature in my Windows system, then I found that I need to execute the bash file in 
`scripts/asr_language_modeling/ngram_lm/install_beamsearch_decoders.sh `

I also installed [swig for windows](http://www.swig.org/download.html), [wget for windows](https://eternallybored.org/misc/wget/) & [make for windows](https://sourceforge.net/projects/gnuwin32/files/make/3.81/) 
additionally for running the wget & make commands in the .sh files.

After installing all these, I am getting an error while I am trying to run the above `install_beamsearch_decoders.sh ` inside the nemo folder.
`ModuleNotFoundError: No module named '_swig_decoders'`

Earlier, I was also getting error `ModuleNotFoundError: No module named 'swig_decoders'` but I resolved that by installing make & wget, so the command is able to generate swig_decoder.py file, but now I am getting `ModuleNotFoundError: No module named '_swig_decoders'` which is another python module file.

I have attached the log file with this. As per my understanding, this is happening mainly because in the log there comes an error
```
cl : Command line warning D9002 : ignoring unknown option '-O3'
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
```

[swig-error.txt](https://github.com/NVIDIA/NeMo/files/6602117/swig-error.txt)

However, I would appreciate if you can check the log file and see what is the problem if in case I am wrong. Also let me know if this is impossible to use in Windows system.

Thanks for the help!

**Comment by titu1994** [comment]
We dont support Windows 10 in any capacity at the moment.

**Comment by azadehharatian** [comment]
I face the same problem in Colab, I installed all prerequisite.
