### ISSUE TITLE
timestamp and score per word or sentence

### ISSUE THREAD

**Issue by AllanBraga14** [NVIDIA/NeMo#2321]
We are doing training/transcription tests using NeMo for the Portuguese language and we are getting great results. But now I want to evolve the transcripts in order to get the confidence rate, timestamp of each word or sentence. Is there any tool inside NeMo that already does this autonomously?
Just for comparison, other transcribers return Json similar to this:

"words": [
     {​​​​​​​​
     "end_time": 0.39077207,
     "score": 66,
     "start_time": 0.272892,
     "text": "a"
      }​​​​​​​​,
     {​​​​​​​​
     "end_time": 1.1700554,
     "score": 94,
     "start_time": 0.40797436,
     "text": "internet"
     }​​​​​​​​
]

**Comment by titu1994** [comment]
We don't (yet) have something that sophisticated as an API that emits word level confidence. However, we do have CTC alignments available. You can use the CTC model.transcribe(..., return_hypotheses=True) argument, which will return a hypothesis object with a value in it called `alignnent` - that describes what token the model predicted at each timestep of the Acoustic sequence. Note that this will include the CTC blank token (which is by conversion the last token in the decoding vocabulary).

You also get the log probabilities, so I suppose you could perform softmax at each timestep to compute the actual confidence per token predicted. 

Start and end times can be estimated as well depending on token boundaries and reversing the timesteps count by number of stride steps the model performs. Note that QuartzNet is a 2x stride model where as Citrinet is an 8x stride model.

**Comment by Omarnabk** [comment]
@titu1994 
Is there any way to calculate the word timestep after applying beamsearch decoding on top of  EncDecCTCModelBPE  citrinet_1024.

I tried [parlance ](https://github.com/parlance/ctcdecode) solution but took a very long time to execute, maybe because of the large vocabulary size.
