### ISSUE TITLE
how to use language model in train

### ISSUE THREAD

**Issue by Iagodel** [NVIDIA/NeMo#2322]
We are trying to train models with a language model '.arpa', but reading the documentation and trying some scripts we can't get anything but the same result without the language model. I think we are doing something wrong. Do you have any tip for this question, another documentation or something like this to help us? Do we just use at the inference or not?

Regards

**Comment by okuchaiev** [comment]
what models are you training?

**Comment by okuchaiev** [comment]
Language model is trained separately from the acoustic model such as QuartzNet. Then you can use LM during beam search process to improve the results. Please refer to this doc https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html

**Comment by Iagodel** [comment]
Thanks @okuchaiev, this help us a lot and confirm something that we was thinking. 
Now we tried to use the same example in this doc and we got that:
![image](https://user-images.githubusercontent.com/47003942/121403939-d17ad280-c931-11eb-8cb5-7b4af8f08098.png)

We use beam search with lm:

**Comment by titu1994** [comment]
The documentation above links to a utility script that will perform beam search for you - please try with that. The KenLM binary built for character models via that script should be evaluated using that script only.

**Comment by Iagodel** [comment]
Thank you all for help, we got something news and got some results.
Now, I just want one more help. About the parameters, beam_width, alpha and beta. Do have a documentation about that, blog or something that I can study about, to understand more how it work?

**Comment by titu1994** [comment]
Beam width = beam size. Larger beam size will take longer for marginally better results. 
Alpha = LM weight. 
Beta = Length penalty. 
We perform a sparse grid search over alpha and beta, keeping beam width fixed.
