### ISSUE TITLE
How to use asr model for streaming

### ISSUE THREAD

**Issue by ravi02512** [NVIDIA/NeMo#2325]
Hello folks

I used nvidia quartznet for asr and it is taking wav files to transcribe. How to do real time streaming asr model

Thanks

**Comment by SaimNaz** [comment]
How to do real time streaming using Citrinet asr model? Will it be the same way as of Quartznet?

**Comment by ravi02512** [comment]
> How to do real time streaming using Citrinet asr model? Will it be the same way as of Quartznet?

do you know how to implement  quartznet for real time streaming??

**Comment by SaimNaz** [comment]
> > How to do real time streaming using Citrinet asr model? Will it be the same way as of Quartznet?
> 
> do you know how to implement quartznet for real time streaming??

No, I didn't try yet.

**Comment by khursani8** [comment]
For streaming you need FrameAsr like from this notebook https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/02_Online_ASR_Microphone_Demo.ipynb or use Nvidia Jarvis

**Comment by SaimNaz** [comment]
> For streaming you need FrameAsr like from this notebook https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/02_Online_ASR_Microphone_Demo.ipynb or use Nvidia Jarvis

Yes, I tried this earlier but it didn't work for CitriNet model.

**Comment by khursani8** [comment]
What you mean by didn't work? Did you use correct stats? https://github.com/NVIDIA/NeMo/issues/1203

**Comment by SaimNaz** [comment]
> What you mean by didn't work? Did you use correct stats? #1203
> And from what I know CitriNet use different stride,you might need to take that into account, I don't have experience with CitriNet yet

Correct, It is working for Quartznet model, but no output was coming for Citrinet model. I wanted to know what could be the reason of it. @khursani8 thanx for your response, I'll be checking for different stride.
