### ISSUE TITLE
speech_to_text.py doesn't work

### ISSUE THREAD

**Issue by agemagician** [NVIDIA/NeMo#2329]
**Describe the bug**

I am trying to run the "speech_to_text.py " but it fails and gives the following error:
```
  File "speech_to_text.py", line 88, in main
    asr_model.maybe_init_from_pretrained_checkpoint(cfg)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'EncDecCTCModel' object has no attribute 'maybe_init_from_pretrained_checkpoint'
```

**Steps/Code to reproduce bug**

The whole code is accessible through this Colab notebook:
https://colab.research.google.com/drive/1Z5d7KL_LOWQthozKAPnBpubN8Ub3ZuZ3?usp=sharing

**Expected behavior**

I am expecting the model to work and load a pretrained model.

 - Environment location: Google Colab
 - Method of NeMo install: pip install nemo_toolkit['all']

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu
- PyTorch version:  1.8
- Python version:  3.7

**Additional context**
I am trying to finetune a pretrained QuartzNet15x5.

**Comment by titu1994** [comment]
That method exists in the main branch of nemo, not in the 1.0.1 release.

**Comment by agemagician** [comment]
Oh, you are correct.
Then I will use the last release 1.0.1.

But what is the correct parameter to use in order to load a pretrained model ?

**Comment by titu1994** [comment]
The scripts directory is for training models from scratch - you can refer to the ASR tutorial 1 in order to see how to modify the example script in order to enable finetuning.

**Comment by agemagician** [comment]
Great, thanks a lot.
I believe this will be a very good feature for all of us,
