### ISSUE TITLE
Wav2Vec2 Fine-tuning Tutorial

### ISSUE THREAD

**Issue by agemagician** [NVIDIA/NeMo#2342]
I tried to find an example for fine-tuning wav2vec2 but I couldn't.
I was able only to find the pre-training script.

Could you please share an example for fine-tuning wav2vec2? 
https://github.com/NVIDIA/NeMo/blob/ee480c1a7905a6488ede29c9d892b6be3038759f/examples/asr/experimental/wav2vec/wav2vec_pretrain.py

**Comment by okuchaiev** [comment]
sorry, we currently don't have that. Feel free to try doing that and sending a PR :)
