### ISSUE TITLE
How to load local pretrain .ckpt in config file

### ISSUE THREAD

**Issue by guyqaz** [NVIDIA/NeMo#2348]
I changed the diarizer.vad.model_path in [Config file ](https://github.com/NVIDIA/NeMo/blob/main/examples/speaker_recognition/conf/speaker_diarization.yaml) to use my own trained models. But it required .nemo

Is posible to use .ckpt model in Config file.
Many thanks.

**Comment by fayejf** [comment]
@guyqaz Thanks for your question.
You can use   `load_from_checkpoint(checkpoint_path=YOUR_CHECKPOINT)`

we do not support it in diarizer but we will add it later.
For an instant change, 

You can add 
```
elif model_path.endswith('.ckpt'):
    self._vad_model = EncDecClassificationModel.load_from_checkpoint(model_path)
    logging.info("VAD model loaded locally from {}".format(model_path))
```

to  https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/models/clustering_diarizer.py#L137

**Comment by guyqaz** [comment]
Hi @fayejf , thanks a lot. I think it will work.
I am closing this issue here.
