### ISSUE TITLE
Incorrect Citrinet transcription

### ISSUE THREAD

**Issue by jmayank1511** [NVIDIA/NeMo#2349]
**Describe the bug**
I am trying to transcribe an audio file with following ground truth:
**in the late 1980s switzerland witnessed a huge increase**
and getting the following prediction by Citrinet:
**in the late one thousand nine hundred eighty seconds switzerland witnessed a huge increase**

**Steps/Code to reproduce bug**
NeMo version : 1.0.0rc1
Enviroment: Nvidia-docker
Inference script: https://github.com/NVIDIA/NeMo/blob/v1.0.0rc1/examples/asr/transcribe_speech.py

**Expected behavior**
Seems like a bug in text-normalization that wrongly normalizes 1980s to one thousand nine hundred eighty seconds

**Environment overview (please complete the following information)**

 - Environment location:  Nvidia-Docker
 
 - Docker run command: docker run -it  nvcr.io/nvidia/nemo:1.0.0b1, installed nemo-1.0.0rc1 using reinstall.sh

**Additional context**
GPU model: RTX 2080

**Comment by titu1994** [comment]
This is not a big, the model was trained on normalized text transcripts which convert numbers to some semantically correct text. You can use NeMos Inverse Text Normalization toolkit to parse this string back into numbers. cc @yzhang123
