### ISSUE TITLE
Audios length - Training

### ISSUE THREAD

**Issue by sadia95** [NVIDIA/NeMo#2354]
I want to know if it is necessary that the audios should be less than 25 seconds in the training set? I have created the manifest and in "duration" if the number is bigger than 25 it doesn't work and gives an error while setting up the training data. I am not sure what's going wrong. I need help!

I get this error when the duration number is set to a bigger number: ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by titu1994** [comment]
Yes audio samples must be smaller than 20 seconds - even 32 GB memory GPUs will struggle to train on longer sequences.

**Comment by sadia95** [comment]
Okay thanks. But there is something weird happening, I manually changed  the "duration" in the json file to less than 20, even though the audio is longer, it still starts training.

**Comment by titu1994** [comment]
The files longer than 20 seconds will be filtered our prior to training

**Comment by sadia95** [comment]
Alright, thanks. In my dataset all audios are longer than 20 seconds. Which could be trimmed to shorter ones by writing a script, but the transcripts will have to be trimmed manually. Is there any other option for that?

**Comment by titu1994** [comment]
Nemo has a CTC segmentation toolkit in https://github.com/NVIDIA/NeMo/tree/main/tools/ctc_segmentation
