### ISSUE TITLE
Some modules are not present in the NeMo API documentation

### ISSUE THREAD

**Issue by tkornuta-nvidia** [NVIDIA/NeMo#236]
For example, documentation of AudioToSpectrogramPreprocessor is missing.

We investigated that with @redoctopus and she has found that nemo_asr.rst doesn't include several modules.

https://github.com/NVIDIA/NeMo/blob/master/docs/sources/source/collections/nemo_asr.rst

So the bigger issue includes: taking a look at all implemented components and checking whether the associated rst files are including them into documentation.

**Comment by tkornuta-nvidia** [comment]
Another module missing: BeamSearchDecoderWithLM

**Comment by tkornuta-nvidia** [comment]
GreedyCTCDecoder

**Comment by tkornuta-nvidia** [comment]
JasperRNNConnector

**Comment by tkornuta-nvidia** [comment]
In CTC Loss definition of axes is not consecutive, i.e.:
            "log_probs": NeuralType({1: AxisType(TimeTag),
                                     0: AxisType(BatchTag),
                                     2: AxisType(ChannelTag)}),

Why and do we want to keep it this way?

**Comment by tkornuta-nvidia** [comment]
CTCLossNM missing in API odcumentation

**Comment by tkornuta-nvidia** [comment]
DialogDataLayer

**Comment by tkornuta-nvidia** [comment]
EncoderRNN - and I am guessing all modules from tutorials/chatbot...

**Comment by Rama3214** [comment]
Bagaimana saya pakai aplikasi ini iya

**Comment by okuchaiev** [comment]
closing as this is related to the old version
