### ISSUE TITLE
How to export Torch checkpoint in .NeMo

### ISSUE THREAD

**Issue by DiegoJota** [NVIDIA/NeMo#2367]
Hi,

I'm using the container https://ngc.nvidia.com/catalog/containers/nvidia:nemo_asr_app_img and running the step by step from the notebook 'English to Spanish Cross Language Finetuning'. I did the training and everything works perfectly.
At the end of training as a result we have checkpoints that can be used for decoding in Jasper.
Is there a possibility to export these checkpoints in model .NeMo?

![image](https://user-images.githubusercontent.com/49459897/122222165-6298fe80-ce88-11eb-8014-3b7d0427ab5f.png)

Since most of the tutorials I find in the documentation are for .NeMo models, I was left with this question

**Comment by titu1994** [comment]
That tutorial is a little outdated, you can follow the tutorial to finetune on other languages here - https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/asr/10_ASR_CTC_Language_Finetuning.ipynb
