### ISSUE TITLE
No effect of punctuation on tts synthesis

### ISSUE THREAD

**Issue by sciai-ai** [NVIDIA/NeMo#2388]
Hi, I have tried the tts inference notebook with the different tts models and vocoders. I tried adding question mark and exclamations to the end of the sentence but they have no effect on the intonation of the synthesized speech.

**Comment by blisc** [comment]
> Hi, I have tried the tts inference notebook with the different tts models and vocoders. I tried adding question mark and exclamations to the end of the sentence but they have no effect on the intonation of the synthesized speech.

This would depend on the model and how it handles the alignment between text and speech. Not all models would change intonation with punctuation.
What models do you observe this with?
