### ISSUE TITLE
neural factory infer function return all tensors for the whole dataset

### ISSUE THREAD

**Issue by Slyne** [NVIDIA/NeMo#240]
https://github.com/NVIDIA/NeMo/blob/0898368fe3daf643e27365b2f7ad4788bdc5c3bb/nemo/nemo/backends/pytorch/actions.py#L724

Not sure if my understanding for this function is correct. 
It seems this function returns the list of batch tensors for the total dataset, which may cause CPU or GPU OOM if the dataset is huge or the tensors contain a lot of data, like the likelihood for each frames with a large vocabulary.

Is this possible to modify this function to return a generator instead ?

**Comment by jaberkow** [comment]
> https://github.com/NVIDIA/NeMo/blob/0898368fe3daf643e27365b2f7ad4788bdc5c3bb/nemo/nemo/backends/pytorch/actions.py#L724
> 
> Not sure if my understanding for this function is correct.
> It seems this function returns the list of batch tensors for the total dataset, which may cause CPU or GPU OOM if the dataset is huge or the tensors contain a lot of data, like the likelihood for each frames with a large vocabulary.
> 
> Is this possible to modify this function to return a generator instead ?

I am having this issue exactly.  I am trying to do inference on a dataset of 6400 audio examples, with a maximum duration of 17 seconds, and no matter the batch size I get a GPU OOM error around halfway through.  It would be useful if we could interact programmatically with the data layer to pass in different files when calling infer.

**Comment by Slyne** [comment]
Use data iterator may solve this problem. Create a customized data layer & give it a method (here is set_signal()) to accept the inputs. The inputs may be generated from data generator.

```python
# simple data layer to pass audio signal
class AudioDataLayer(DataLayerNM):
    @property
    def output_ports(self):
        return {
            "input_signal": NeuralType(('B', 'T'), AudioSignal(freq=self.sample_rate)),
            "length": NeuralType(tuple('B'), LengthsType()),
        }

    def __init__(self, sample_rate):
        super().__init__()
        self.output = True
        self.sample_rate = sample_rate
        
    def __iter__(self):
        return self
    
    def __next__(self):
        if not self.output:
            raise StopIteration
        self.output = False
        return torch.as_tensor(self.signal, dtype=torch.float32), \
            torch.as_tensor(self.signal_shape, dtype=torch.int64)
    
    def set_signal(self, signal, batch_size):
        self.signal = np.reshape(signal.astype(np.float32)/32768., [batch_size, -1])
        self.signal_shape = np.ones(batch_size, dtype=np.int64)*self.signal.shape[1] 
        self.output = True

    def __len__(self):
        return 1

    @property
    def dataset(self):
        return None

    @property
    def data_iterator(self):
        return self
```

Therefore, we may:
```python
data_layer = AudioDataLayer(sample_rate)

# create our DAG
# instantiate neural factory
# .......
#  get our tensors to predict, suppose the tensor is log_probs

for batch_data in data_generator:
    data_layer.set_signal(batch_data)
    logits = model.infer([log_probs])[0]
    post_process(logits)
    ......
```

**Comment by Mddct** [comment]
> ```python
> 32768
> ```

what is magic number 32768 mean？
