### ISSUE TITLE
Fine-tune ASR language model

### ISSUE THREAD

**Issue by Omarnabk** [NVIDIA/NeMo#2409]
How to fine-tune **nemo:asrlm_en_transformer_large_ls LM** [here](https://ngc.nvidia.com/catalog/models/nvidia:nemo:asrlm_en_transformer_large_ls) 

I found this training script here (https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/language_modeling/transformer_lm.py), but I did not know how to use it? can you give more instruction.

**Comment by titu1994** [comment]
@AlexGrinch

**Comment by Omarnabk** [comment]
I tried to follow the same technique for fine-tuning ASR, could you check it. 

https://gist.github.com/Omarnabk/094137ca08b720d2b36b49bc2ece1717

**Comment by titu1994** [comment]
There's new documentation for ASR LMs in the main branch, and it will be part of next release.
