### ISSUE TITLE
Experience with small dataset

### ISSUE THREAD

**Issue by TParcollet** [NVIDIA/NeMo#241]
Hi there! 

Just to gather some of your experience on working with small datasets. I'm currently investigating TIMIT with Nemo, and based on the AN4 architecture with the proper CTC symbols (Phonemes instead of character). Unfortunately, I observe poor performances (around 27% of WER) which is very high compared to works like:
https://arxiv.org/pdf/1701.02720.pdf

I also know that the PER reported at training time is based on a greedy decoding that might explain these performances. 

Since my goal is to compare NeMo to others toolkits, I would like to be as fair as possible and ask you about specific tricks you have encountered to obtain better performances with smaller datasets. I'm currently trying to play with the architecture to reduce the complexity and overfitting (also noises are not great with TIMIT). 

Thanks!

**Comment by okuchaiev** [comment]
Like you mentioned NeMo is a "toolkit". To get good WER/PER on TIMIT you will need to have an appropriate model to train. The one we have for AN4 is a smaller variant of the Jasper network [1], which we just use as a CI test.

If you want good performance on TIMIT you could try: (1) Our QuartzNet [2] model architecture (which has much less parameters than Jasper). I recommend you try this first with a much smaller configuration, say 5x3. (2) You can always implement a model from [3] - NeMo already gives you data layer / data preprocessing plus CTC module - all you need to do is to write a torch.nn.Module and convert it into NeMo's neural module like so: https://nvidia.github.io/NeMo/tutorials/custommodules.html#converting-from-pytorch-s-nn-module 
If your goal is to get the best performance on TIMIT, I would recommend starting with (1). If your goal is to compare the toolkits then I think you should make sure to use the same model in all toolkits.

Having said that, why don't use LibriSpeech/MozillaCommonVoice?

[1] https://arxiv.org/pdf/1904.03288.pdf
[2] https://arxiv.org/pdf/1910.10261.pdf
[3] https://arxiv.org/pdf/1701.02720.pdf

**Comment by TParcollet** [comment]
Thank you for your suggestions. I'll try both of them. 

We are considering MozillaCommonVoice, but I don't think that the recent release is mature enough to be used as a starting benchmark. We will definitely include this corpus latter, but we currently needs something that we know perfectly and that is very very quick to iterate over, like TIMIT.

Thanks again!
