### ISSUE TITLE
`run_sample.sh` opens too many files

### ISSUE THREAD

**Issue by anihm136** [NVIDIA/NeMo#2410]
**Describe the bug**

The data preparation script `run_sample.sh` errors out pretty frequently, caused by opening too many files at the same time and hitting the process file limit. This seems to arise from the 'prepare_data.py' script which is called

**Steps/Code to reproduce bug**

(This seems to stem from the use of multiprocessing, so this may not be consistently reproducible)
1. Create a data directory with ~1000 files
2. Run the script
3. Script fails before completion of step 1 (`prepare_data.py`), with an OS Error

**Expected behavior**

Script should complete successfully

**Environment overview (please complete the following information)**

 - Environment location: Local dev system
 - Method of NeMo install: install from source (as described in readme, in a Conda environment)

**Environment details**

- OS version: Linux 5.12.9-arch1-1 x86_64 GNU/Linux
- PyTorch version: 1.9.0
- Python version: 3.9.5

**Additional context**

I was able to solve the issue by switching the use of `multiprocessing.Process` with `multiprocessing.Pool` (and other changes required to use it). Not sure if it is a robust solution, or if it can be solved in other ways

**Comment by titu1994** [comment]
Could you point to the actual script in Nemo repo ? We have quite a few scripts in the directory

**Comment by anihm136** [comment]
The one I'm referring to is `https://github.com/NVIDIA/NeMo/blob/main/tools/ctc_segmentation/run_sample.sh`. Just an update, I left the script running overnight and it hit the same error again, presumably in a different part of the process. Will let you know once I look into it more

**Comment by anihm136** [comment]
Also wanted to note that the script does not work with `v1.0.2`, unsure of the reason. I switched to 1.0.1 based on a similar issue which has solved it for now. This is probably unrelated though. The same solution worked for me the second time as well

**Comment by titu1994** [comment]
@ekmb could you take a look at this ?
