### ISSUE TITLE
Run multiple model inference on a single GPU concurrently

### ISSUE THREAD

**Issue by Rem4rkable** [NVIDIA/NeMo#2412]
Hello nemo team,

I have a queue of audio files waiting to be transcribed. when I run the citrinet model on them I see there's still free memory on the gpu hence my question - is there a way and how, to run multiple nemo models (can be all citrinet for example, but also others) concurrently on a single gpu? 

btw unrelated: is there a compatible pretrained LM model for bpe models (citrinet)? also is downsampling needed/important for audio files higher than 16kHz ? (22, 41..) so far it seems to handle them well.

Thank you 😊

**Comment by VahidooX** [comment]
Depends on your specific case, you may create batches of your audio files to increase the GPU utilization if latency is not that important.

We have a pretrained language model (Transformer LM) here which can be used a neural rescorer:
https://ngc.nvidia.com/catalog/models/nvidia:nemo:asrlm_en_transformer_large_ls

Training N-gram LM would be fast and do not need that much resource. You may find more info about LM for ASR models here:
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html

**Comment by titu1994** [comment]
During inference, Citrinet requires very little resources, so to max out gou utilization simply use larger batch sizes (under amp you could even try 64 or 96 batch sizes).

You can ofc also run the same script multiple times, and pass different subsets of audio to transcribe. You will probably run out of memory rapidly though. We suggest to use higher batch sizes instead. 

Downsampling is necessary to preserve memory. During inference if you pass sample rate other than 16k, it will be automatically resampled to 16 kHz prior to forward pass

**Comment by Rem4rkable** [comment]
Thank you for your inputs! I indeed do not care of latency right now.
I am usually transcribing long audio files (±1hour files) . Right now i simply truncate it to 1-3 mins wav files then send. When you talk about batches, how should I adjust to utilize the gpu?

**Comment by VahidooX** [comment]
You may set the batch_size of the method model.transcribe() as large as possible as long as you do not get OOM error. It would utilize the most of your GPU.
