### ISSUE TITLE
Using the beamsearch with LM

### ISSUE THREAD

**Issue by Iagodel** [NVIDIA/NeMo#2414]
Hello everyone,

I'm testing the Offline_ASR in Colab, at the beamsearch part I getting some results, as expected. But I just need the first 
hypothesis, so I won't need to process the other hypothesis. Have any way to do this? A way to just process one hypothesis.

**Comment by titu1994** [comment]
Beam Search will return N candidates sorted by best to worst for N beam size, theres no way to return just 1 after processing N candidates.
