### ISSUE TITLE
Adding training_step to parameters in ModelPT breaks DP accelerator

### ISSUE THREAD

**Issue by roman-vygon** [NVIDIA/NeMo#2425]
**Describe the bug**
Similar to https://github.com/pytorch/pytorch/issues/8637, ModelPT class adds training_step to its parameters [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/core/classes/modelPT.py#L159). Because of that, when training with 'dp' accelerator workers call the same instanced function instead of copies on different devices.

**Steps/Code to reproduce bug**
Create any model inherited from ModelPT.
Fit with torch lightning trainer and 'dp' accelerator.
Check module id [here](https://github.com/PyTorchLightning/pytorch-lightning/blob/4af8eff0a13309b2e030c423db91156b1e869fac/pytorch_lightning/overrides/base.py#L84) and in your training_step - they will differ.

**Expected behavior**
No function should be a parameter in the class.

**Environment overview (please complete the following information)**

 - Environment location: My own machine
 - Method of NeMo install: pip install nemo v1.0.2

**Environment details**

- OS version Ubuntu 18.04
- PyTorch version 1.9.0
- Python version 3.8.3

**Additional context**

I understand that NeMo doesn't support DP accelerator, but this is a very hard to trace bug that can be easily fixed and can help someone in the future.

**Comment by titu1994** [comment]
We suggest use of only DDP - it is the only method tested. Most of the models in Nemo are not pickleble, and therefore not compatible with DP
