### ISSUE TITLE
Fine-tune stt_en_conformer_ctc_large

### ISSUE THREAD

**Issue by Omarnabk** [NVIDIA/NeMo#2426]
**Describe the bug**

I am trying to fine-tune **stt_en_conformer_ctc_large** model using the following:

`asr_model = nemo_asr.models.EncDecCTCModelBPE.from_pretrained(model_name="stt_en_conformer_ctc_large")`

Then I set the training params:

```
# not working: 
from omegaconf import OmegaConf, open_dict
    
params = asr_model.cfg 
new_opt = copy.deepcopy(params.optim)
new_opt.lr = 0.0001

params['train_ds']['manifest_filepath'] = train_manifest_path
params['train_ds']['batch_size'] = 8


params['validation_ds']['manifest_filepath'] = dev_manifest_path
params['validation_ds']['batch_size'] = 8

# Use the smaller learning rate we set before
asr_model.setup_optimization(optim_config=new_opt)

# Point to the new training data for fine-tuning
asr_model.setup_training_data(train_data_config=params['train_ds'])


# Point to the new validation data for fine-tuning
asr_model.setup_validation_data(val_data_config=params['validation_ds'])
```

Received error:

```
~/NeMo/nemo/collections/asr/models/ctc_models.py in setup_training_data(self, train_data_config)
    423             # If it's an int, we assume that the user has set it to something sane, i.e. <= # training batches,
    424             # and don't change it. Otherwise, adjust batches accordingly if it's a float (including 1.0).
--> 425             if isinstance(self._trainer.limit_train_batches, float):
    426                 self._trainer.limit_train_batches = int(
    427                     self._trainer.limit_train_batches

AttributeError: 'NoneType' object has no attribute 'limit_train_batches'

```

However, it **works** when I load the config from the config_bpe.yaml:
```
from omegaconf import OmegaConf, open_dict

# ! wget -P configs/ https://raw.githubusercontent.com/NVIDIA/NeMo/main/examples/asr/conf/citrinet/config_bpe.yaml --no-check-certificate
    
params = OmegaConf.load('configs/config_bpe.yaml')
    
new_opt = copy.deepcopy(params.model.optim)
new_opt.lr = 0.0001

params['model']['train_ds']['manifest_filepath'] = train_manifest_path
params['model']['train_ds']['batch_size'] = 8


params['model']['validation_ds']['manifest_filepath'] = dev_manifest_path
params['model']['validation_ds']['batch_size'] = 8

# Use the smaller learning rate we set before
asr_model.setup_optimization(optim_config=new_opt)

# Point to the new validation data for fine-tuning
asr_model.setup_validation_data(val_data_config=params['model']['validation_ds'])


# Point to the data we'll use for fine-tuning as the training set
asr_model.setup_training_data(train_data_config=params['model']['train_ds'])

```

What is the correct procedure?

**Comment by titu1994** [comment]
Create a Pytorch lightning Trainer and had model.set_trainer(trainer) before calling setup training data. That should fix it. In general it's best to attach a trainer before performing any setup work. I'll update the notebook to follow this. 

This is odd, can you print out the full train config ?

**Comment by Omarnabk** [comment]
Great! it works now.

So, first set the trainer, then set the configurations and finally call the `trainer.fit(ASR_model)`

**Comment by titu1994** [comment]
Yes

**Comment by Omarnabk** [comment]
I faced another error while fine-tuning **stt_en_conformer_ctc_large** 

`FileNotFoundError: [Errno 2] No such file or directory: '/data/nemo_asr_set/asr_set_1.4/train_no_appen/audio_272.tar'
`
[Here ](https://gist.github.com/Omarnabk/fbefdae2eb1ed76e1962964ae3964e9f) is the code I use for fine-tuning

Any opinion?

**Comment by titu1994** [comment]
This is odd, can you try setting model.train_ds.is_tarred=False?

**Comment by Omarnabk** [comment]
I tried ` asr_model.cfg.train_ds.is_tarred = False` but did not work. I changed to 

`params['train_ds']['is_tarred'] = False` and then `asr_model.setup_training_data(train_data_config=params['train_ds'])`  and it worked.


While training, I received there warninings: 

`[W reducer.cpp:1050] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters. This flag results in an extra traversal of the autograd graph every iteration, which can adversely affect performance. If your model indeed never has any unused parameters, consider turning this flag off. Note that this warning may be a false positive your model has flow control causing later iterations to have unused parameters. (function operator())`

```
[NeMo W 2021-07-01 19:18:45 nemo_logging:349] /home/manw/anaconda3/envs/nemo/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
      "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
```

Is it Ok? 

Also, while training, the model prints the reference and the predicted sentence. Can we disable this behaviour? 

```
[NeMo I 2021-07-01 19:18:48 wer_bpe:189] reference:i want to die in it
[NeMo I 2021-07-01 19:18:48 wer_bpe:190] predicted:i want to dine in it
Epoch 0:   0%|                                | 9/2718 [00:08<41:53,  1.08it/s, loss=48.7, v_num=8-16]
[NeMo I 2021-07-01 19:18:52 wer_bpe:188]

[NeMo I 2021-07-01 19:18:52 wer_bpe:189] reference:the
[NeMo I 2021-07-01 19:18:52 wer_bpe:190] predicted:
Epoch 0:   1%|▏                              | 14/2718 [00:13<41:52,  1.08it/s, loss=53.7, v_num=8-16]
[NeMo I 2021-07-01 19:18:56 wer_bpe:188]

[NeMo I 2021-07-01 19:18:56 wer_bpe:189] reference:there was some ambiguity
[NeMo I 2021-07-01 19:18:56 wer_bpe:190] predicted:the was some ing of ambiguity
Epoch 0:   1%|▏                              | 19/2718 [00:16<39:56,  1.13it/s, loss=57.6, v_num=8-16]
```

**Comment by titu1994** [comment]
Hmm I guess since the checkpoint was trained and released the tarred dataset flag is still set. Quite problematic. 

The warnings can be ignored, they are due to some defaults in pytorch and pytorch lightning, which doesn't affect training. 

Logging is usually disabled by default in the config - you can do asr_model._wer.log_prediction = False
