### ISSUE TITLE
Error: Cannot resolve schedulerDictConfig when run VAD training tutorial 

### ISSUE THREAD

**Issue by di0002ya** [NVIDIA/NeMo#2434]
Hi teams, I tried to run this notebook https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/06_Voice_Activiy_Detection.ipynb 

However, when I ran `trainer.fit(vad_model)`. It returns following errors
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-60-6abb1ca1f787> in <module>
----> 1 trainer.fit(vad_model)

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloader, val_dataloaders, datamodule)
    458         self.call_setup_hook(model)
    459         self.call_hook("on_before_accelerator_backend_setup", model)
--> 460         self.accelerator.setup(self, model)  # note: this sets up self.lightning_module
    461 
    462         # ----------------------------

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu.py in setup(self, trainer, model)
     13             raise MisconfigurationException(f"Device should be CPU, got {self.root_device} instead")
     14 
---> 15         return super().setup(trainer, model)

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py in setup(self, trainer, model)
     67         """
     68         self.connect_training_type_plugin(self.training_type_plugin, model)
---> 69         self.setup_optimizers(trainer)
     70         self.connect_precision_plugin(self.precision_plugin)
     71 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py in setup_optimizers(self, trainer)
    314             return
    315         optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
--> 316             trainer=trainer, model=self.lightning_module
    317         )
    318         self.optimizers = optimizers

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py in init_optimizers(self, trainer, model)
    158 
    159     def init_optimizers(self, trainer: "Trainer", model: LightningModule):
--> 160         return trainer.init_optimizers(model)
    161 
    162     def optimizer_step(self, optimizer: torch.optim.Optimizer, lambda_closure: Callable, **kwargs):

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/optimizers.py in init_optimizers(self, model)
     32     def init_optimizers(self, model: LightningModule) -> Tuple[List, List, List]:
     33         self._lightning_optimizers = None
---> 34         optim_conf = model.configure_optimizers()
     35         if optim_conf is None:
     36             rank_zero_warn(

/opt/conda/lib/python3.7/site-packages/nemo/core/classes/modelPT.py in configure_optimizers(self)
    760 
    761     def configure_optimizers(self):
--> 762         self.setup_optimization()
    763 
    764         if self._scheduler is None:

/opt/conda/lib/python3.7/site-packages/nemo/core/classes/modelPT.py in setup_optimization(self, optim_config)
    752         # Try to instantiate scheduler for optimizer
    753         self._scheduler = prepare_lr_scheduler(
--> 754             optimizer=self._optimizer, scheduler_config=scheduler_config, train_dataloader=self._train_dl
    755         )
    756 

/opt/conda/lib/python3.7/site-packages/nemo/core/optim/lr_scheduler.py in prepare_lr_scheduler(optimizer, scheduler_config, train_dataloader)
    610 
    611     # Get the scheduler class from the config
--> 612     scheduler_cls = get_scheduler(scheduler_name, **scheduler_args)
    613 
    614     # Instantiate the LR schedule

/opt/conda/lib/python3.7/site-packages/nemo/core/optim/lr_scheduler.py in get_scheduler(name, **kwargs)
    396     if name not in AVAILABLE_SCHEDULERS:
    397         raise ValueError(
--> 398             f"Cannot resolve scheduler{name}'. Available optimizers are : " f"{AVAILABLE_SCHEDULERS.keys()}"
    399         )
    400 

ValueError: Cannot resolve schedulerDictConfig'. Available optimizers are : dict_keys(['WarmupPolicy', 'WarmupHoldPolicy', 'SquareAnnealing', 'CosineAnnealing', 'NoamAnnealing', 'WarmupAnnealing', 'InverseSquareRootAnnealing', 'SquareRootAnnealing', 'PolynomialDecayAnnealing', 'PolynomialHoldDecayAnnealing', 'StepLR', 'ExponentialLR', 'ReduceLROnPlateau', 'CyclicLR'])
`

Would you mind helping me solve this bug?

**Comment by fayejf** [comment]
Hey @di0002ya I cannot reproduce the bug. Which branch are you using? Could you try` ./reinstall.sh` ?

**Comment by di0002ya** [comment]
> Hey @di0002ya I cannot reproduce the bug. Which branch are you using? Could you try` ./reinstall.sh` ?

Thanks! I have solved issue by re installing whole package. I will close.
