### ISSUE TITLE
Model QuartzNet15x5Base-Zh was not found

### ISSUE THREAD

**Issue by qin53027** [NVIDIA/NeMo#2436]
**Describe the bug**

Hi, 

I am new to NeMo. After I have installed the NeMo in my dGPU laptop, I have written a simple test to test the ASR.

1. first I have test the .wav file in English ("Where is the bus station?")

quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En").cuda()
print("\nGot the TEXT")
english_text = quartznet.transcribe([Audio_sample])
print("\n")
print(english_text)    --- it prints the "where is the bus station" ----Good thing

2. Then: I have test the .wav file in Chinese in same word where is the bus station in Chinese
 
quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-Zh").cuda()

But I have got: FileNotFoundError: Model QuartzNet15x5Base-Zh was not found.

Per NeMo user guide, QuartzNet15x5Base-Zh is supported model.

Can you let me know how to solve the problem?

Thanks
Jimmy

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version:       Ubuntu 18.04
- PyTorch version  1.9.0+cu102
- Python version:   3.6

**Additional context**

Example: GPU model: RTX 2080Ti

**Comment by titu1994** [comment]
That model has been deprecated for a newer model which you can use by replacing the model name as "stt_zh_citrinet_512". The docs in Nemo have a list of models seperated by language available here https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/results.html

We will also release a new version of mandarin, which will be available in the next release
