### ISSUE TITLE
What is the pre-trained model to be used for Mandarin TTS in NeMo?

### ISSUE THREAD

**Issue by qin53027** [NVIDIA/NeMo#2438]
**Describe the bug**
Hi,

Today after I have installed NeMo, I have tried the ASR both in English and Chinese -- it all works very well!!

Also I did a quick tts test on the English based on following setting  -- it works!

# Download and load the pretrained tacotron2 model
spec_generator = SpectrogramGenerator.from_pretrained("tts_en_tacotron2")
# Download and load the pretrained waveglow model
vocoder = Vocoder.from_pretrained("tts_waveglow_88m")

Could you please let me know what is the pre-trained model to be used for the Mandarin TTS? Also can tts_waveglow_88m is also used for that case?

Thanks a lot
Jimmy

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version        : ubuntu 18.04
- PyTorch version  1.9.0+cu102
- Python version:   3.6

**Additional context**

Example: GPU model

**Comment by titu1994** [comment]
We don't have mandarin TTS at the moment. Fyi @blisc

**Comment by qin53027** [comment]
Thanks
