### ISSUE TITLE
Hyperpeter Optimization with ray tune and pytorch lightning

### ISSUE THREAD

**Issue by Amels404** [NVIDIA/NeMo#2442]
It would be helpful to add Hyperpeter Optimization with ray tune and pytorch lightning for different nemo models (ASR/TTS) 
This will help in finding the best set of paramters when training using Nemo on different sorts of data.  

This can make the training more straightforward and can be of an advantage compared to other repos.
Thank you!

**Comment by ericharper** [comment]
Hi, please see this issue: #2376

We haven't tried Ray Tune and PyTorch Lightning. But others have and they found that the models could not be pickled.

Have you tried doing this yet?

**Comment by ericharper** [comment]
I raised an issue with Ray to see if they have any input: https://github.com/ray-project/ray/issues/16878
