### ISSUE TITLE
Online Microphone ASR (ERROR: No audio input device found.)

### ISSUE THREAD

**Issue by Rajratnpranesh** [NVIDIA/NeMo#2444]
Hi,
I am using the02_Online_ASR_Microphone_Demo.ipynb notebook. Followed all the steps but in the end, I am getting ERROR: No audio input device found. Colab has microphone access through the browser. Any fix for this?

Thanks

**Comment by titu1994** [comment]
Since colab is online, it cannot connect to any hardware device such as microphone. Please use this notebook locally.

**Comment by Malkovsky** [comment]
getAudio() method described here
https://github.com/ricardodeazambuja/colab_utils/blob/master/colab_utils/__init__.py
actually uses microphone from the user browser in colab

**Comment by PoornaSaiNagendra** [comment]
> 

Could you help me how to use that with Online_ASR_Microphone_Demo.ipynb

**Comment by Amarnath392** [comment]
@PoornaSaiNagendra
Are you able to solve microphone issue in  Online_ASR_Microphone_Demo.ipynb

**Comment by PoornaSaiNagendra** [comment]
@Amarnath392 

Still no. Looking for some help.

**Comment by sciai-ai** [comment]
Hi, did you solve this

**Comment by sciai-ai** [comment]
> Since colab is online, it cannot connect to any hardware device such as microphone. Please use this notebook locally.

how can we run this as an api in the cloud
