### ISSUE TITLE
Unable to download pretrained model

### ISSUE THREAD

**Issue by joshmyersdean** [NVIDIA/NeMo#2446]
**Describe the bug**
`ValueError` when trying to import pretrained model.

**Steps/Code to reproduce bug**

```python
import nemo.collections.asr as nemo_asr

model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En")
[NeMo I 2021-07-06 22:51:41 cloud:66] Downloading from: https://api.ngc.nvidia.com/v2/models/nvidia/nemospeechmodels/versions/1.0.0a5/files/QuartzNet15x5Base-En.nemo to /root/.cache/torch/NeMo/NeMo_1.1.0/QuartzNet15x5Base-En/2b066be39e9294d7100fb176ec817722/QuartzNet15x5Base-En.nemo
[NeMo I 2021-07-06 22:51:42 cloud:79] Download from cloud failed. Attempt 1 of 3
[NeMo I 2021-07-06 22:51:42 cloud:79] Download from cloud failed. Attempt 2 of 3
[NeMo I 2021-07-06 22:51:42 cloud:79] Download from cloud failed. Attempt 3 of 3
ValueError: Not able to download url right now, please try again.
```

**Expected behavior**

Model is downloaded without error.

**Environment overview (please complete the following information)**

 - Environment location: Databricks
 - Method of NeMo install: Tried with both pip magic `%pip install nemo_toolkit['all']` and directly in Databricks.

**Environment details**

- Databricks runtime 8.3 ML
- PyTorch==1.8.1
- Python version==3.8.8

**Additional context**

I thought this was similar to [#2555](https://github.com/NVIDIA/NeMo/issues/2255) but I have confirmed that my Databricks cluster has internet access.

**Comment by Omarnabk** [comment]
The model is downloading well. I have just tried it
![Screenshot 2021-07-07 213533](https://user-images.githubusercontent.com/72882909/124818419-4cec9580-df6b-11eb-8a0d-aaa27638cf4b.png)

**Comment by joshmyersdean** [comment]
Hmm may be an issue with Databricks then.
