### ISSUE TITLE
 Training Recovery

### ISSUE THREAD

**Issue by CaioRochaGoes** [NVIDIA/NeMo#2448]
We are doing training tests on Colab with its "10_ASR_CTC_Language_Finetuning" script, but the machine only lasts 24 hours. Is there a possibility to continue a workout where you left off?
We are controlling Checkpoints and ".nemo" directly through Drive

**Comment by ericharper** [comment]
NeMo has auto-resume capabilities built in to the exp_manager. Please see the docs here: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/core/core.html#experiment-manager and here: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/core/core.html#id11

Let us know if you still have an issue resuming training.
