### ISSUE TITLE
Question on multi_gpu

### ISSUE THREAD

**Issue by TParcollet** [NVIDIA/NeMo#245]
Hi !

Reading the documentation I should " First set placement to nemo.core.DeviceType.AllGpu in NeuralModuleFactory and in your Neural Modules" to enable multi-gpu training. But I'm definitely not sure about what module should has or should not has the placement. Do you have an example of a quartznet.py script that enables multi-gpu?

**Comment by okuchaiev** [comment]
Here is docs: https://nvidia.github.io/NeMo/training.html#multi-gpu-training
Instead of "jasper.py" you can use this script: https://github.com/NVIDIA/NeMo/blob/master/examples/asr/quartznet.py

**Comment by potipot** [comment]
Hi, could you please update the links?
