### ISSUE TITLE
Test audio samples for transcribe

### ISSUE THREAD

**Issue by OriAlpha** [NVIDIA/NeMo#2462]
By the demo given for transcribe, it has been given only for Russian text to English translation. Is there any way to get german voice samples for testing? 
I could not access the files in https://nemo-public.s3.us-east-2.amazonaws.com

Link for Russian text is 
Get example from: https://nemo-public.s3.us-east-2.amazonaws.com/mcv-samples-ru/common_voice_de_19034087.wav

**Comment by titu1994** [comment]
You can transcribe audio by changing path yourself in the notebook.

**Comment by OriAlpha** [comment]
@titu1994 no files are included in the tutorial folder. 
I think it's a part of MCV 6.0 Dev dataset. 
So not sure how to get other audio samples.

please have look here, 
https://github.com/NVIDIA/NeMo/blob/main/tutorials/AudioTranslationSample.ipynb

**Comment by OriAlpha** [comment]
The only way to get the audio is via wget (its has only for one audio)
wget 'https://nemo-public.s3.us-east-2.amazonaws.com/mcv-samples-ru/common_voice_ru_19034087.wav'

**Comment by titu1994** [comment]
We won't be adding the entire dev set of mcv to the aws collection - the single file is only used as a demo. You can use some other service like gcp or personal aws storage and change paths.
