### ISSUE TITLE
Integration of corcua dataset library

### ISSUE THREAD

**Issue by DanBmh** [NVIDIA/NeMo#2470]
Hi,

I wanted to notify you about my speech dataset handling tool [corcua](https://gitlab.com/Jaco-Assistant/corcua). The task it solves is loading datasets from different formats and converting them to any framework-customized format we can use for training STT networks. It was built with the goal of making the addition of new datasets as easy as possible. Currently it supports 34 datasets, many in German, but 12 of them are multilingual containing 3 or more languages.

NeMo's `.jsonl` format is already supported, so the integration should be very easy.

I hope this is interesting for your project.
Greetings
Daniel

**Comment by titu1994** [comment]
Looks like an interesting library ! Currently, we are not adding  integration of GNU licensed software, since NeMo is apache 2 based.

**Comment by DanBmh** [comment]
Ah ok, I thought this should work as it's only LGPL and it wouldn't require a deep integration into NeMo's code.

What do you think about adding a note and a link in the _custom datasets_ docs then?
