### ISSUE TITLE
import nemo.collections.asr as nemo_asr generates an error?

### ISSUE THREAD

**Issue by ali2iptoki** [NVIDIA/NeMo#2473]
I tried to execute the tutorial:  [](https://github.com/NVIDIA/NeMo/blob/v1.0.2/tutorials/speaker_recognition/Speaker_Recognition_Verification.ipynb)

Unfortunately, the line `import nemo.collections.asr as nemo_asr` is not working and generates an error like:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-18-7cc0b6be15f9> in <module>()
      3 # NeMo's ASR collection - this collections contains complete ASR models and
      4 # building blocks (modules) for ASR
----> 5 import nemo.collections.asr as nemo_asr
      6 from omegaconf import OmegaConf

8 frames
/usr/local/lib/python3.7/dist-packages/nemo/collections/asr/__init__.py in <module>()
     13 # limitations under the License.
     14 
---> 15 from nemo.collections.asr import data, losses, models, modules
     16 from nemo.package_info import __version__
     17 

/usr/local/lib/python3.7/dist-packages/nemo/collections/asr/losses/__init__.py in <module>()
     13 # limitations under the License.
     14 
---> 15 from nemo.collections.asr.losses.angularloss import AngularSoftmaxLoss
     16 from nemo.collections.asr.losses.ctc import CTCLoss

/usr/local/lib/python3.7/dist-packages/nemo/collections/asr/losses/angularloss.py in <module>()
     16 import torch
     17 
---> 18 from nemo.core.classes import Loss, Typing, typecheck
     19 from nemo.core.neural_types import LabelsType, LogitsType, LossType, NeuralType
     20 

/usr/local/lib/python3.7/dist-packages/nemo/core/__init__.py in <module>()
     14 
     15 import nemo.core.neural_types
---> 16 from nemo.core.classes import *

/usr/local/lib/python3.7/dist-packages/nemo/core/classes/__init__.py in <module>()
     14 
     15 
---> 16 from nemo.core.classes.common import (
     17     FileIO,
     18     Model,

/usr/local/lib/python3.7/dist-packages/nemo/core/classes/common.py in <module>()
     25 from typing import Dict, List, Optional, Union
     26 
---> 27 import hydra
     28 import wrapt
     29 from omegaconf import DictConfig, OmegaConf

/usr/local/lib/python3.7/dist-packages/hydra/__init__.py in <module>()
      3 # Source of truth for Hydra's version
      4 __version__ = "1.1.0"
----> 5 from hydra import utils
      6 from hydra.errors import MissingConfigException
      7 from hydra.main import main

/usr/local/lib/python3.7/dist-packages/hydra/utils.py in <module>()
      6 from typing import Any, Callable
      7 
----> 8 import hydra._internal.instantiate._instantiate2
      9 import hydra.types
     10 from hydra._internal.utils import _locate

/usr/local/lib/python3.7/dist-packages/hydra/_internal/instantiate/_instantiate2.py in <module>()
      6 from typing import Any, Callable, Sequence, Tuple, Union
      7 
----> 8 from omegaconf import OmegaConf, SCMode
      9 from omegaconf._utils import is_structured_config
     10 

ImportError: cannot import name 'SCMode' from 'omegaconf' (/usr/local/lib/python3.7/dist-packages/omegaconf/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

and in the code there is a red line below `import nemo.collections.asr as nemo_asr`.
I am executing the tutorial on colab.

**Comment by titu1994** [comment]
Can you post the full stack trace please

**Comment by ali2iptoki** [comment]
@titu1994 please check the updated post

**Comment by titu1994** [comment]
The tutorials must be run at a specific Nemo version - 1.1.0 is the latest and should work. Otherwise update both hydra and omegaconf and try with main branch of nemo

**Comment by ali2iptoki** [comment]
@titu1994 thanks but can you please more precise

**Comment by titu1994** [comment]
Basically pip install --upgrade nemo_toolkit[all] should do be used instead of using the main branch

**Comment by sougatabh** [comment]
@titu1994 I am also getting the same error while importing ,import nemo.collections.asr as nemo_asr
I tried upgrading nemo_toolkit but  no luck :)
`ImportError                               Traceback (most recent call last)
<ipython-input-15-2932e87b5265> in <module>
----> 1 import nemo.collections.asr as nemo_asr
      2 import numpy as np
      3 from IPython.display import Audio, display
      4 import librosa
      5 import os

~/anaconda3/lib/python3.7/site-packages/nemo/collections/asr/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from nemo.collections.asr import data, losses, models, modules
     16 from nemo.package_info import __version__
     17 

~/anaconda3/lib/python3.7/site-packages/nemo/collections/asr/losses/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from nemo.collections.asr.losses.angularloss import AngularSoftmaxLoss
     16 from nemo.collections.asr.losses.ctc import CTCLoss

~/anaconda3/lib/python3.7/site-packages/nemo/collections/asr/losses/angularloss.py in <module>
     16 import torch
     17 
---> 18 from nemo.core.classes import Loss, Typing, typecheck
     19 from nemo.core.neural_types import LabelsType, LogitsType, LossType, NeuralType
     20 

~/anaconda3/lib/python3.7/site-packages/nemo/core/__init__.py in <module>
     14 
     15 import nemo.core.neural_types
---> 16 from nemo.core.classes import *

~/anaconda3/lib/python3.7/site-packages/nemo/core/classes/__init__.py in <module>
     14 
     15 
---> 16 from nemo.core.classes.common import (
     17     FileIO,
     18     Model,

~/anaconda3/lib/python3.7/site-packages/nemo/core/classes/common.py in <module>
     25 from typing import Dict, List, Optional, Union
     26 
---> 27 import hydra
     28 import wrapt
     29 from omegaconf import DictConfig, OmegaConf

~/anaconda3/lib/python3.7/site-packages/hydra/__init__.py in <module>
      3 # Source of truth for Hydra's version
      4 __version__ = "1.1.0"
----> 5 from hydra import utils
      6 from hydra.errors import MissingConfigException
      7 from hydra.main import main

~/anaconda3/lib/python3.7/site-packages/hydra/utils.py in <module>
      6 from typing import Any, Callable
      7 
----> 8 import hydra._internal.instantiate._instantiate2
      9 import hydra.types
     10 from hydra._internal.utils import _locate

~/anaconda3/lib/python3.7/site-packages/hydra/_internal/instantiate/_instantiate2.py in <module>
      6 from typing import Any, Callable, Sequence, Tuple, Union
      7 
----> 8 from omegaconf import OmegaConf, SCMode
      9 from omegaconf._utils import is_structured_config
     10 

ImportError: cannot import name 'SCMode' from 'omegaconf' (/home/sougata/anaconda3/lib/python3.7/site-packages/omegaconf/__init__.py)
`

**Comment by titu1994** [comment]
Your omegaconf and hydra versions are incorrect, please update them to the latest versions and it should be fixed.

**Comment by amilind** [comment]
@titu1994 I am also getting the some error while importing ,import nemo.collections.asr as nemo_asr
I clone nemotoolkit from git using this command 

!python -m pip install git+https://github.com/NVIDIA/NeMo.git

but then getting this error
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_1804\651975930.py in <module>
      3 # NeMo's ASR collection - this collections contains complete ASR models and
      4 # building blocks (modules) for ASR
----> 5 import nemo.collections.asr as nemo_asr

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\nemo\collections\asr\__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from nemo.collections.asr import data, losses, models, modules
     16 from nemo.package_info import __version__
     17 

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\nemo\collections\asr\losses\__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from nemo.collections.asr.losses.angularloss import AngularSoftmaxLoss
     16 from nemo.collections.asr.losses.ctc import CTCLoss
     17 from nemo.collections.asr.losses.lattice_losses import LatticeLoss

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\nemo\collections\asr\losses\angularloss.py in <module>
     16 import torch
     17 
---> 18 from nemo.core.classes import Loss, Typing, typecheck
     19 from nemo.core.neural_types import LabelsType, LogitsType, LossType, NeuralType
     20 

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\nemo\core\__init__.py in <module>
     14 
     15 import nemo.core.neural_types
---> 16 from nemo.core.classes import *

~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\nemo\core\classes\__init__.py in <module>
     14 
     15 
---> 16 import hydra
     17 import omegaconf
     18 import pytorch_lightning

ModuleNotFoundError: No module named 'hydra'

**Comment by titu1994** [comment]
That type of install does not install anything other than the base essentials of pytorch. To install Nemo properly, you need the core + collections. See the Nemo documentation installation section, or the readme on GitHub to do a full install of Nemo
