### ISSUE TITLE
Pretrained Model for Speaker Verification

### ISSUE THREAD

**Issue by di0002ya** [NVIDIA/NeMo#2479]
Can Nemo team provide more pretrained speaker verification models such as ECAPA, X-vector?

**Comment by nithinraok** [comment]
Hi @di0002ya , we already released x-vector based models [here](https://ngc.nvidia.com/models/nvstaging:nemo:speakerverification_speakernet), we changed ECAPA a bit, to support faster training and inference, code is already part of main now. Will publish models in a day or two. I will update here as soon it is done.

**Comment by di0002ya** [comment]
Thanks for your fast response @nithinraok !

**Comment by entn-at** [comment]
Hi @nithinraok, just following up on whether a pretrained ECAPA model is being made available. I haven't seen any reference to it in the [list of available EncDecSpeakerLabelModel models](https://github.com/NVIDIA/NeMo/blob/master/nemo/collections/asr/models/label_models.py#L54).
Thanks!

**Comment by nithinraok** [comment]
Thanks for your interest and sorry for the delay, we are reviewing our models to decide the best one to release for research purposes, I should get an update this week, once ready I will update here.
