### ISSUE TITLE
Dockerfile onnx-tensorrt patch failing

### ISSUE THREAD

**Issue by jjgraham** [NVIDIA/NeMo#248]
I am trying to use your Dockerfile but running into issues with your patch

<pre>Step 8/15 : RUN git clone https://github.com/onnx/onnx-tensorrt.git && cd onnx-tensorrt && git submodule update --init --recursive && patch -f < ../onnx-trt.patch &&     mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DGPU_ARCHS="60 70 75" && make -j16 && make install && mv -f /usr/lib/libnvonnx* /usr/lib/x86_64-linux-gnu/ && ldconfig
 ---> Running in f15383978bfd
Cloning into 'onnx-tensorrt'...
Submodule 'third_party/onnx' (https://github.com/onnx/onnx.git) registered for path 'third_party/onnx'
Cloning into '/tmp/onnx-trt/onnx-tensorrt/third_party/onnx'...
Submodule path 'third_party/onnx': checked out '553df22c67bee5f0fe6599cff60f1afc6748c635'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/onnx/third_party/benchmark'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third_party/onnx/third_party/pybind11'
Cloning into '/tmp/onnx-trt/onnx-tensorrt/third_party/onnx/third_party/benchmark'...
Cloning into '/tmp/onnx-trt/onnx-tensorrt/third_party/onnx/third_party/pybind11'...
Submodule path 'third_party/onnx/third_party/benchmark': checked out 'e776aa0275e293707b6a0901e0e8d8a8a3679508'
Submodule path 'third_party/onnx/third_party/pybind11': checked out '09f082940113661256310e3f4811aa7261a9fa05'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'third_party/onnx/third_party/pybind11/tools/clang'
Cloning into '/tmp/onnx-trt/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang'...
Submodule path 'third_party/onnx/third_party/pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
patching file CMakeLists.txt
Hunk #1 FAILED at 20.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
The command '/bin/sh -c git clone https://github.com/onnx/onnx-tensorrt.git && cd onnx-tensorrt && git submodule update --init --recursive && patch -f < ../onnx-trt.patch &&     mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DGPU_ARCHS="60 70 75" && make -j16 && make install && mv -f /usr/lib/libnvonnx* /usr/lib/x86_64-linux-gnu/ && ldconfig' returned a non-zero code: 1
ERROR: Job failed: command terminated with exit code 1

**Comment by okuchaiev** [comment]
@drnikolaev or @borisfom any ideas on what the problem is here?

**Comment by borisfom** [comment]
See https://github.com/NVIDIA/NeMo/pull/253

**Comment by okuchaiev** [comment]
Seems to be resolved now

**Comment by jjgraham** [comment]
Thanks gang ! it builds and works perfect now on our k8s cluster !
