### ISSUE TITLE
Citrinet model TensorRT Inference

### ISSUE THREAD

**Issue by Darshcg** [NVIDIA/NeMo#2480]
Hi Nvidia Team,

I have converted the Nemo-based Citrinet(for ASR) Model to ONNX then to TRT, but I am stuck at writing an inference code for the TRT model. 

Having said that, while I am doing an Inference in Nemo, there is a single line of code for Inference. So, I am not sure about the TRT inference for the Converted TRT model. it will really help me if you can share some materials on TRT inference for Citrinet models(converted from Nemo).

Thanks and Regards,
Darshan C G

**Comment by titu1994** [comment]
We support export to ONNX but beyond that we don't support further steps. So probably the TRT forums would be a better place for specific advise
