### ISSUE TITLE
Unable to find  install_ctc_decoder.sh file In offline ASR 

### ISSUE THREAD

**Issue by Kiran2115** [NVIDIA/NeMo#2488]
In order to get the timestamps of each word, I am using Offline asr ( https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0b3/tutorials/asr/Offline_ASR.ipynb#scrollTo=I9eIxAyKHREB) for my experiment but I am unable to find the install_ctc_decoder.sh in scripts.

Can you suggest any other alternative so that I can use this tutorial for my experimentation purpose?

Thanks in Advance.

**Comment by VahidooX** [comment]
That file is moved here in the latest release:
https://github.com/NVIDIA/NeMo/blob/main/scripts/asr_language_modeling/ngram_lm/install_beamsearch_decoders.sh

You are running an older version of that tutorial.
