### ISSUE TITLE
Combining Nemo with Pre-existing Classification Models

### ISSUE THREAD

**Issue by eanmikale** [NVIDIA/NeMo#249]
Hello! Great work here. We'd like to know if you could guide us toward the proper resources concerning how to combine NeMo with pre-existing Image Classification or even Object Detection models. Thank you for your time.

**Comment by okuchaiev** [comment]
currently we only have "conversational AI" collections: nemo_asr, nemo_nlp and nemo_tts.
But you can start your own with image classification modules

**Comment by eanmikale** [comment]
Hi! I'm sorry I am still confused. We already have image classification models. We would like to integrate these models with conversational A.I. using nemo. Is there a way to do so using the current modules? Or would we need to utilize other tools outside of the software suite? Thank you. 



Warm Regards, 


Ean Mikale, J.D.

Chief A.I. Architect

Infinite 8 Institute, L3C

1111 N 13th Street #417

Omaha, NE 68102

1-(202)-492-6119

mailto:ean@infinite8institute.com

http://www.infinite8institute.com



Accelerated technology for tomorrow, today. 








---- On Wed, 01 Jan 2020 17:39:32 -0600 Oleksii Kuchaiev <notifications@github.com> wrote ----


currently we only have "conversational AI" collections: nemo_asr, nemo_nlp and nemo_tts.
 But you can start your own with image classification modules

**Comment by okuchaiev** [comment]
You would need to add your own Neural Modules (see https://nvidia.github.io/NeMo/tutorials/custommodules.html). You can put them into your own collection under your own license terms. If your existing image classification models are in PyTorch it should be relatively easy to convert then into neural modules

**Comment by okuchaiev** [comment]
closing as this is related to the old version
