### ISSUE TITLE
Text to speech module

### ISSUE THREAD

**Issue by OriAlpha** [NVIDIA/NeMo#2494]
I have seen in tutorials for audio translation, 
https://github.com/NVIDIA/NeMo/blob/main/tutorials/AudioTranslationSample.ipynb
It has 3 modules speech to text, translation and text to speech. But have seen it uses the IPython audio function for converting the text to audio. I was wondering is there any native module for converting text to speech.

**Comment by titu1994** [comment]
Ipythin is hard to display the final generated audio, not to convert text to speech. That's being done via the Waveglow and Tacotron models.
