### ISSUE TITLE
Multi GPU Inference

### ISSUE THREAD

**Issue by this-is-ac** [NVIDIA/NeMo#2506]
Hello!

I've trained a Neural Machine Translation model using NeMo. Is it possible to use Multiple GPU's for model inference? 

Thanks

**Comment by MaximumEntropy** [comment]
Hey @this-is-ac, sorry for the late response, we do not support multi-GPU inference using the nmt_transformer_infer.py script. But we do support async DDP inference for very large datasets using the following script - https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/machine_translation/translate_ddp.py. 

To use that script, 

1) Create a tarred monolingual dataset of your input sentences using examples/nlp/machine_translation/create_tarred_monolingual_dataset.py *by providing the same tokenizer you used to tokenize your parallel corpus via the --tokenizer_model flag*.  
2) Run exampes/nlp/machine_translation/translate_ddp.py by providing a string path to the created tarfiles and metadata.

Let me know if you run into any issues.
