### ISSUE TITLE
Not able to import NeMo on macOS (ModuleNotFoundError: No module named 'nemo')

### ISSUE THREAD

**Issue by ayush-mehta** [NVIDIA/NeMo#2511]
I tried following ways to install Nemo:
1. `pip3 install nemo_toolkit`
2. `pip3 install git+https://github.com/NVIDIA/NeMo.git `
3.  Running `git clone git+https://github.com/NVIDIA/NeMo.git ` and then `cd NeMo` and finally `pip3 install .`

The above mentioned commands are successfully executed without any errors.
After running these commands on terminal, when I run python `import nemo`  it shows me `ModuleNotFoundError: No module named 'nemo'`

OS version - macOS Big Sur 11.4
Python version - 3.9.6

**Comment by okuchaiev** [comment]
The following worked for me on MacOS just fine:
(notice 'all' in square brakets)
```
pip install nemo_toolkit['all']
```
```
>>> import nemo
>>> nemo.__version__
'1.1.0'
```
Make sure you are using python 3.8 or 3.9 (I'd recommend Anaconda, this is where I tested this) and that you've un-installed any older NeMo versions.

**Comment by ayush-mehta** [comment]
> The following worked for me on MacOS (10.15.7) just fine:
> (notice 'all' in square brakets)
> 
> ```
> pip install nemo_toolkit['all']
> ```
> 
>  ```
> >>> import nemo
> >>> nemo.__version__
> '1.1.0'
> ```
> 
> Make sure you are using python 3.8 or 3.9 (I'd recommend Anaconda, this is where I tested this) and that you've un-installed any older NeMo versions.

Firstly I uninstalled all the NeMo versions and then I tried running `pip3 install nemo_toolkit['all']` on my terminal, but I got `zsh: no matches found: nemo_toolkit[all]` error. As I have mentioned earlier, I have Python 3.9.6 which is sufficient enough. Although I am not using it on Anaconda. Could you suggest any other possible alternative?

**Comment by okuchaiev** [comment]
Did you miss the singlequote around all:
```
pip install nemo_toolkit['all']
```

**Comment by ayush-mehta** [comment]
> Did you miss the singlequote around all:
> 
> ```
> pip install nemo_toolkit['all']
> ```

Nope, I did not miss it.
<img width="559" alt="Screenshot 2021-07-20 at 10 14 53 PM" src="https://user-images.githubusercontent.com/60601746/126363294-3ca6326a-0ac8-45a5-8713-2302a5032de3.png">

**Comment by ayush-mehta** [comment]
> The following worked for me on MacOS (10.15.7) just fine:
> (notice 'all' in square brakets)
> 
> ```
> pip install nemo_toolkit['all']
> ```
> 
>  ```
> >>> import nemo
> >>> nemo.__version__
> '1.1.0'
> ```
> 
> Make sure you are using python 3.8 or 3.9 (I'd recommend Anaconda, this is where I tested this) and that you've un-installed any older NeMo versions.

I installed Anaconda and then tried again but still getting the same error. Could you guide me through this

**Comment by ayush-mehta** [comment]
Its working now, I followed the following steps:
1. Install Anaconda
2. Open Anaconda Navigator
3. Launch VS Code
4. Open a new Terminal in VS Code
5. run `python3 -m pip install git+https://github.com/NVIDIA/NeMo.git`

After following this steps, the issue got resolved on macOS Big Sur
