### ISSUE TITLE
Unable to install nemo on ubuntu

### ISSUE THREAD

**Issue by 007sambhavjain** [NVIDIA/NeMo#2524]
Getting this error
 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-J5oGxi/nemo-toolkit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-J5oGxi/nemo-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-weXhSc
         cwd: /tmp/pip-install-J5oGxi/nemo-toolkit/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-J5oGxi/nemo-toolkit/setup.py", line 106
        f'--use-parentheses --line-width={__LINE_WIDTH} -rc -ws'
        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by VahidooX** [comment]
It looks like you are an older version of python, probably even python 2. You need to install the latest python or conda.

**Comment by okuchaiev** [comment]
closing this. Please follow one of these installation instructions https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/v1.1.0/starthere/intro.html#installation  Feel free to re-open if they don't work.
