### ISSUE TITLE
getting out of memory error for finetuning

### ISSUE THREAD

**Issue by hodaazare** [NVIDIA/NeMo#2531]
I am finetuning existing Citrinet model (stt_en_citrinet_1024). We have around 130h of transcribed T-mobile data.
The test and evaluation sets are fixed: test(3.53h) and evaluation(5.45h). I can't use all the train data because of out of memory error. This is the type of error that I'm getting: 
`RuntimeError: CUDA out of memory. Tried to allocate 434.00 MiB (GPU 0; 39.59 GiB total capacity; 37.22 GiB already allocated; 356.19 MiB free; 37.44 GiB reserved in total by PyTorch)`
The most amount of data that I could use was (90.29h) of data (max_duration = 65s).
I am using 4gpus (40g each). I reduced the batch_size to 16 and precision to 16.
I also, used the ctc-segmentation to split long audio files and the corresponding transcripts into shorter fragments. So, instead of 90h of data I can use 66h of data most with max_duration = 66. (not that much improvement on increasing the train size)
Any suggestion about how I can increase the train data? ( we are still not covering 1/3 of data)

**Comment by titu1994** [comment]
During training, the maximum duration of audio can be 20 seconds with AMP + 32 GB of memory. Any longer audio segments must be segmented to be less than 20 seconds long. Reducing batch size might help with memory but will make training extremely slow so we dont advise that. 

It is only during inference that long audio clips can be provided.

**Comment by hodaazare** [comment]
> During training, the maximum duration of audio can be 20 seconds with AMP + 32 GB of memory. Any longer audio segments must be segmented to be less than 20 seconds long. Reducing batch size might help with memory but will make training extremely slow so we dont advise that.
> 
> It is only during inference that long audio clips can be provided.

Thanks a lot for your response. Using  [CTC_segmentation ](https://github.com/NVIDIA/NeMo/blob/main/tutorials/tools/CTC_Segmentation_Tutorial.ipynb) was not that much helpful for splitting the transcribed segments into smaller ones. Is there any other way to split the long audios into smaller ones?

**Comment by VahidooX** [comment]
What was the problem with the CTC segmentation?
You may use it to split all your samples into 20s segments.

**Comment by hodaazare** [comment]
> What was the problem with the CTC segmentation?
> You may use it to split all your samples into 20s segments.

This is the command that I use for CTC segmentation:
`bash run_sample.sh \
--MODEL_NAME_OR_PATH='stt_en_quartznet15x5' \
--DATA_DIR='./data1' \
--OUTPUT_DIR='./output' \
--SCRIPTS_DIR='./scripts' \
--MIN_SEGMENT_LEN=0 \
--MAX_SEGMENT_LEN=100 \
--CUT_PREFIX=0 \
--MIN_SCORE=-5  \
--USE_NEMO_NORMALIZATION=False`

But the new segments are not necessarily less than 100s. Even the silence at the end are still part of the segment. Is there any parameter that I need to change and I missed?

**Comment by ekmb** [comment]
@hodaazare The tool first splits the text into shorter segments and then finds the alignment of the short text segments within the original audio. By default, the text is split based on the end of sentence punctuation marks: `?.!`. I'd suggest setting  `ADDITIONAL_SPLIT_SYMBOLS=";|--|:|-|,"` and also experimenting with the `--MAX_SEGMENT_LEN`. If you're segmenting Eng data, it's also recommended to set `USE_NEMO_NORMALIZATION` to `True` to normalize numbers that might be present in the text data.

**Comment by hodaazare** [comment]
> @hodaazare The tool first splits the text into shorter segments and then finds the alignment of the short text segments within the original audio. By default, the text is split based on the end of sentence punctuation marks: `?.!`. I'd suggest setting `ADDITIONAL_SPLIT_SYMBOLS=";|--|:|-|,"` and also experimenting with the `--MAX_SEGMENT_LEN`. If you're segmenting Eng data, it's also recommended to set `USE_NEMO_NORMALIZATION` to `True` to normalize numbers that might be present in the text data.

Thank you for your suggestion. I tried it but the quality of the results are not that much high. There are some breaks in the middle of the last word which makes that word meaningless.

**Comment by titu1994** [comment]
That's to be expected as no model is perfect.  However it is not possible to train on audio segments larger than 20 seconds without wasting gpu utilization. So segmentation is the easiest possible approach.
