### ISSUE TITLE
Adding continuous speech transcription in pre-trained NeMo models

### ISSUE THREAD

**Issue by ayush-mehta** [NVIDIA/NeMo#2536]
I was working on a project that required building an API for speech to text conversion, it'd be great to have continuous transcription. As currently the model only translates the audio file which is already saved in .wav format. By any chance is it possible using NeMo now?

**Comment by VahidooX** [comment]
Do you mean something like streaming ASR? Have you looked into these two tutorial? 
https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Streaming_ASR.ipynb
https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/02_Online_ASR_Microphone_Demo.ipynb
