### ISSUE TITLE
examples/nlp/nmt_tutorial.py: how to generate  YouTokenToMe model for custom language? 

### ISSUE THREAD

**Issue by ican24** [NVIDIA/NeMo#254]
Dear Team of Neural Machine Translation,

`
# pass a YouTokenToMe model to YouTokenToMeTokenizer for de
# if the target is zh, we should pass a vocabulary file, e.g. zh_vocab.txt
`
src: examples/nlp/nmt_tutorial.py

How to generate  YouTokenToMe model for custom langueage?
I'll be so appreciated, if you provide any instruction for it.

Thank you in advance!

**Comment by ican24** [comment]
Is YouTokenToMe a right tool to do it?
https://github.com/VKCOM/YouTokenToMe

If yes, do I need to use below command line to generate tokenized model for the used languages?
`yttm bpe --data data/train.en --model bpe8k_yttm.model --vocab_size 8200`

**Comment by okuchaiev** [comment]
Yes, please refer to the YouTokenToMe tokenizer's docs on how to do it.
The command you posted looks good to me. Do you have any issues with it?

**Comment by ican24** [comment]
Dear Oleksii,
No the issue was solved!
So I am closing this issue.
I will try to formulate my further questions for using of new language with NeMo's NLP as separate issues.
