### ISSUE TITLE
Transcript test during training

### ISSUE THREAD

**Issue by DiegoJota** [NVIDIA/NeMo#2540]
Hi,

Do you still support version 0.10.1? I have a question about. I have been training a dataset in Portuguese in this version and in the results folder I see several checkpoints (decoder and encoder) being generated during training, specifically every 1000 steps.
Can I count on them to take my transcription tests? As an eventual evolution test, for example, or should I just wait for all epochs to complete and get the last decoder and encoder?

I have this question because during training I do transcription tests, but the result varies a lot. There are times that are great, there are times that are terrible.

**Comment by titu1994** [comment]
Sorry that version is not supported anymore. We advise to update to the latest released Nemo version 
But as a general note, intermediate checkpoints will always be unstable unless training is near complete.

**Comment by DiegoJota** [comment]
Thanks for the quick response. I'm already migrating to the latest version, I'm just adjusting parameters and in parallel working on this old version.

In the latest version is it the same way? Do I have to wait for the training to finish to really get the result?

**Comment by titu1994** [comment]
Depends on the model but in general yes. The model will not converge in just a few epochs but you can pick checkpoints after around half or 3/4 training is done
