### ISSUE TITLE
Pillow version gives error

### ISSUE THREAD

**Issue by yzhang123** [NVIDIA/NeMo#255]
When running an nlp model inside nemo container I received the error
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL'.
The installed Pillow version was 7, after downgrading to 6 it was fine.

**Comment by vsl9** [comment]
That issue is in `torchvision`: https://github.com/pytorch/vision/issues/1712

**Comment by okuchaiev** [comment]
Current workarounds: 
(1) Use nvcr.io/nvidia/pytorch:19.12-py3 container and install (using pip) NeMo inside it
(2) Or: Do "pip install Pillow==6.2.1 --force-reinstall"

**Comment by hugovk** [comment]
> (2) Or: Do "pip install Pillow==6.2.1 --force-reinstall"

Slightly better options, as 6.2.2 is a security release:

* `pip install Pillow==6.2.2 --force-reinstall`
* `pip install "Pillow<7" --force-reinstall`

**Comment by hugovk** [comment]
[torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin
