### ISSUE TITLE
ASR tutorial based on Nemo: cannot import name 'SCMode' from 'omegaconf'

### ISSUE THREAD

**Issue by joepareti54** [NVIDIA/NeMo#2552]
This [notebook ](https://github.com/NVIDIA/NeMo/blob/v1.0.2/tutorials/asr/01_ASR_with_NeMo.ipynb)under Ubuntu fails to `import nemo.collections.asr as nemo_asr` 

Here is the exception report:
`ImportError: cannot import name 'SCMode' from 'omegaconf' (/home/joepareti54/anaconda3/lib/python3.8/site-packages/omegaconf/__init__.py)`

**Comment by titu1994** [comment]
Please update to Nemo 1.1 or higher.

**Comment by joepareti54** [comment]
how do I update Nemo? How do I know what version I am running now

**Comment by titu1994** [comment]
pip install --uograde nemo_toolkit['all']

**Comment by joepareti54** [comment]
thank you, but now I have another issue:
`MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []`

**Comment by titu1994** [comment]
Your trainer (or trainer config has number of GPUs > 0) on a machine that has no GPUs. So you'll need to set gpus=0

**Comment by joepareti54** [comment]
I apologize I am asking off topic questions, but since you were so kind to answer: I do have a GPU, an NVIDIA GeForce RTX 2060 and used it in another notebook with pytorch:

`device = 'cuda'`
So I could not figure out why this time it does not find it

**Comment by titu1994** [comment]
If the other notebook is running a DDP process, the gpu will no longer be visible to other processes (or in worse cases it will try and crash due to NCCL errors). 

I'd suggest not using GPUs in notebooks for anything other than exploratory work and stick to scripts for efficient training. 

If the original issue is resolved, is it ok if I close this ?

**Comment by joepareti54** [comment]
Yes the original issue is solved, you can close. Thank you for the support.
