### ISSUE TITLE
Nvidia NEMO / ASR model to be trained on VCTK data

### ISSUE THREAD

**Issue by joepareti54** [NVIDIA/NeMo#2553]
I would like to use the [tutorial](https://github.com/NVIDIA/NeMo/blob/v1.0.2/tutorials/asr/01_ASR_with_NeMo.ipynb) to train a model on a VCTK data set. There are wav files and text files with identical descriptors. The text file contains the sentence spoken in the wav file.
`
joepareti54@MSI /cygdrive/f/x/finance-2020/AI/Listen_attend_spell/VCTK-Corpus
$  ls -l txt/p225 | head -5
total 231
-rw-r--r--+ 1 joepareti54 None  20 Aug 22  2012 p225_001.txt
-rw-r--r--+ 1 joepareti54 None  55 Aug 22  2012 p225_002.txt
-rw-r--r--+ 1 joepareti54 None 103 Aug 22  2012 p225_003.txt
-rw-r--r--+ 1 joepareti54 None  68 Aug 22  2012 p225_004.txt

joepareti54@MSI /cygdrive/f/x/finance-2020/AI/Listen_attend_spell/VCTK-Corpus
$ ls -l wav48/p225 | head -5
total 93464
-rw-r--r--+ 1 joepareti54 None  196990 Aug 23  2012 p225_001.wav
-rw-r--r--+ 1 joepareti54 None  389676 Aug 23  2012 p225_002.wav
-rw-r--r--+ 1 joepareti54 None  749754 Aug 23  2012 p225_003.wav
-rw-r--r--+ 1 joepareti54 None  423528 Aug 23  2012 p225_004.wav`
`
Is this feasible? Any guidelines to implement?

**Comment by titu1994** [comment]
It can be feasible if you have to compute resources to train the models. Due to size of training dataset, it might take a long time to train to convergence
