### ISSUE TITLE
Error: Cannot resolve schedulerDictConfig when run trainer.fit(Punctuation_and_Capitalization_model)

### ISSUE THREAD

**Issue by saraouerk** [NVIDIA/NeMo#2570]
Hello, I'm training Punctuation_and_Capitalization on a french dataset. The first time everithing was fine, but when I tried to change epochs from 3 to 5, and execute again the : trainer.fit(model), I got this error:

ValueError: Cannot resolve schedulerDictConfig'. Available optimizers are : dict_keys(['WarmupPolicy', 'WarmupHoldPolicy', 'SquareAnnealing', 'CosineAnnealing', 'NoamAnnealing', 'WarmupAnnealing', 'InverseSquareRootAnnealing', 'SquareRootAnnealing', 'PolynomialDecayAnnealing', 'PolynomialHoldDecayAnnealing', 'StepLR', 'ExponentialLR', 'ReduceLROnPlateau', 'CyclicLR'])

It still giving this error even I changed the epochs and re installed the packages. 
Would you mind helping me solve this bug, please?

**Comment by VahidooX** [comment]
Are you trying to to load the previous checkpoint and continue the training or start a new training from scratch?
It looks like you have changed the name of the scheduler to something which is not supported. Would you please send us the config printed in the output log?

**Comment by saraouerk** [comment]
I removed all the generated files, and reset the execution environment in colab and reinstall the packages but il stills giving the error. 
It prints this "DictConfig" in the error as the Scheduler name, even Itried to change it manually before lunching fitting by : config.model.optim.sched.name="WarmupAnnealing"

**Comment by ekmb** [comment]
@saraouerk we're overriding some config fields in the notebook, please make sure you did `Factory reset runtime`. I can't reproduce the issue, have you tried using [the training script](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/token_classification/punctuation_capitalization_train.py)?

**Comment by saraouerk** [comment]
@ekmb  Hello, it works in another session (another Google account), I think that I broke something in my session whe I changed  either epochs or the pre-trained model
