### ISSUE TITLE
 Using 64 cores instead of 32

### ISSUE THREAD

**Issue by CaioRochaGoes** [NVIDIA/NeMo#2579]
Hello
I've been training with "10_ASR_CTC_Language_Finetuning" on the CPU but I noticed that the training doesn't allocate all available cores, it's currently using 32 cores, I'd like to use the machine's 64

Is there any parameter which I must pass in the script to use the 64 cores?

**Comment by titu1994** [comment]
The train_ds config has the parameter "num_workers" which you can set to 64. By default it's a small number cause colab doesn't have too many CPU cores.

**Comment by CaioRochaGoes** [comment]
When I started training I set the "num_workers" to 64, the only time he used the 64 cores was at the start of nemo but during training he only uses half of the cores

![image](https://user-images.githubusercontent.com/49493322/127544464-2d6dbab4-099d-427a-8886-4fc143a24beb.png)

**Comment by titu1994** [comment]
Hmm that is more a pytorch issue then maybe, Nemo only has that flag to change the number of workers

**Comment by CaioRochaGoes** [comment]
We are investigating what we can do about pytorch,
In case of news or more questions, I will contact you again.
thank you
