### ISSUE TITLE
DataSet for 8K phone calls

### ISSUE THREAD

**Issue by DiegoJota** [NVIDIA/NeMo#2589]
Hi,

I have a question about how best to assemble a training dataset, who has experience and can share, thank you. I've been working with NeMo for a few months setting up trainings in Portuguese and so far I'm having good results in transcribing calls. But I still notice some simple errors during transcripts...
My question is, for the type of audio I'm transcribing, should I prefer them in my dataSet? For example, I'm building a dataSet thinking about transcribing phone calls (8K), in my dataSet should I include more phone calls or do I have nothing to do with it? Or would increasing the number of speakers and increasing the audio quality be the best solution?
Since building a good dataSet with hundreds of hours takes a lot of time, I want to avoid investing in one side, otherwise it would have better results...

**Comment by titu1994** [comment]
Higher quality audio datasets (more speakers, more variety of spoken words and sentences and at 16 kHz sample rate) is always beneficial to ASR models. These models can consume several thousand hours of speech before they become highly robust. 

For the starting point, data which belongs to the same domain (telephony speech) will make the model perform better when evaluated on telephony speech. You can use language models to improve your word error rate in offline mode if quality is more crucial than speed. 

There will always be some amount of error in any machine learning model, no matter how much data you train it with, but the amount of error can be significantly reduced to the point it's not a major hurdle. 

We have notebooks for audio augmentation, and another notebook for advise on telephony speech. Please refer to those for further guidance. We also have speech data explorer to analyze ASR datasets for transcription errors and CTC segmentation tools to build larger ASR datasets.

**Comment by DiegoJota** [comment]
Thanks for the quick response,

As far as improving word error rate in offline mode, would it be in relation to using the Language Model? The time to transcribe actually increases, but it is not a concern because the focus is on quality. I use it and notice a very positive difference, but as the acoustic model still has some mistakes, it won't do big "miracles"...

And in relation to the notebook on telephony speech, would that be it? I noticed you guys recommend converting audios to 16K
https://github.com/NVIDIA/NeMo/blob/stable/tutorials/asr/ASR_for_telephony_speech.ipynb

**Comment by titu1994** [comment]
Yes that's the recommendation - train and use 16 kHz audio. No ASR model will ever be perfect, with of without language models. The errors can be reduced but not eliminated.
