### ISSUE TITLE
Model not saving

### ISSUE THREAD

**Issue by sadia95** [NVIDIA/NeMo#2591]
I have been trying to save the trained model on cluster but it is not saving. It works on Colab, it does save the .nemo weights file but the same piece of code is not saving it on the cluster. Any idea what could be the reason?

**Comment by titu1994** [comment]
Is it a slurm environment ? Nemo only supports slurm for the moment

**Comment by sadia95** [comment]
Yes it is slurm

**Comment by titu1994** [comment]
Could you provide a snippet of the Nemo script being launched by slurm ? You must provide exp_manager.exp_dir as a path to a directory that has been mounted by slurm, not as an absolute path. Other nodes will be able to write the files to absolute path but these nodes will not sync to node 0. So use mounted paths such as /results/xyz where there's a mount of /some/absolute/result/dir/path:/results/xyz
