### ISSUE TITLE
max_generation_delta in Machine Translation

### ISSUE THREAD

**Issue by this-is-ac** [NVIDIA/NeMo#2595]
Hello!

I'm trying to train a Machine Translation model on NeMo. Under the model parameters, I came across this parameter **max_generation_delta** with a default value of 5. 
Could I please have some clarity on what this parameter controls or where it's used?

Thanks a ton!

**Comment by MaximumEntropy** [comment]
Hi, This parameter specifies the max delta over the input sequence length that the model is allowed to generate. It is used here - https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/modules/common/transformer/transformer_generators.py#L126. For example if your input sequence length is 10 and the `max_generation_delta` is 5, your output sequence can be at most 15 tokens. Hope that clarifies things.

**Comment by this-is-ac** [comment]
Got it. Thanks again @MaximumEntropy
