### ISSUE TITLE
Restore LM when using PunctuationCapitalizationModel

### ISSUE THREAD

**Issue by Rem4rkable** [NVIDIA/NeMo#2606]
Hello friends,

I am using the punctuation capitalization model, 'punctutation_en_bert' or 'distilbert_en' , but although I use restore_from the nemo file I still see it downloads lm from huggingface (from what i understand), i think it is the bert-uncased. 

1. Is there an option to restore the LM as well instead of downloading it? if so how? I want all models etc will be restored from and not downloaded
2. Is there an option to change the LM to different huggingface models.

Thank you very much

**Comment by titu1994** [comment]
The Nemo model won't store the entire hugging face model in itself - this is useful for cases where you want to share just the fine-tune trained model (few MB), not the hugging face backend (which can be several hundred MB in size)

**Comment by ekmb** [comment]
1. During the punctuation model training, the LM is getting finetuned. If you're using from_pretrained() or restore_from() the weights for LM and the heads will be restored. The download is happening to get the correct configuration from the HuggingFace library.
2. Supported language models: Bert, Albert, Distilbert, Roberta, Megatron-Bert. See [this tutorial ](https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/nlp/01_Pretrained_Language_Models_for_Downstream_Tasks.ipynb) for details. If you'd like to use a different LM, specify it [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/models/token_classification/punctuation_capitalization_model.py#L61)
