### ISSUE TITLE
Melspectrogram with non-torch lib

### ISSUE THREAD

**Issue by jsvir** [NVIDIA/NeMo#2609]
Hi, thanks for this great project!
Question: can i reproduce the same melspectorgram using non-torch python libs as one that generated using nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures(nn.Module) class?
Has anyone tried?

**Comment by titu1994** [comment]
Yes, it should be doable, but you'll need to port every part of the FilterbankFeatures class.

**Comment by naymaraq** [comment]
Hi @titu1994
 Why you didn't use mel-spectogram from torchaudio (like in case of mfcc) instead of writing the custom implementation?

**Comment by d2sys** [comment]
Hi @titu1994 ,
Can you please assist her. My code is not working (assuming x is a loaded audio in numpy):
`melspectro=librosa.feature.melspectrogram(x, sr=16000, n_fft=512, hop_length=160, win_length=320, window="hann", nfilt=80)
return np.log(mespectro + 2 ** -24)
`
I test it by using the pretrained model, and by checking WER once I use your NeMo melspectrogram extraction (WER=25%), and when I use this code. (WER = 99% )

**Comment by titu1994** [comment]
As mentioned above, you'll need to reimplements the
