### ISSUE TITLE
Question: CPU RAM for large datasets

### ISSUE THREAD

**Issue by spakhomov** [NVIDIA/NeMo#261]
I am trying to train an Qaurtznet15x5 model on a large-ish dataset - 5000 hours but the jasper.py script seems to run out of CPU RAM. Training gets terminated sometime after "Using only GPU" message as soon as CPU RAM utilization reaches 100%. Note that I am talking about CPU RAM - not GPU. For GPU RAM, my system has 24Gb (2 Titan RTX cards with 24Gb each). The GPU utilization is minimal (10-14%) when the process terminates. My system has only 16Gb CPU RAM and I can grow it only to 128G max. 

I have been looking to see if the minimum system requirements for NeMo ASR modules mention CPU RAM but could not find anything. I guess I am wondering if what's going on is that both the raw audio (and/or the spectra) and the transcripts  get loaded into RAM and, if so, if there is a limit on how much gets loaded at a time - how much RAM one would need to process larger datasets and/or are there input parameters that can limit how much CPU RAM is to be used.

Note: I tried jasper.py with the small an4 dataset and the training and evaluation worked fine w/o any errors.

Any help would be much appreciated!

**Comment by spakhomov** [comment]
Just a followup on the previous question. I tried setting the load_audio parameter to False in the call to nemo_asr.AudioToTextDataLayer(). Now the jasper.py script moved a bit further past the Doing ALL GPU message - see below; however, it still reached 100% CPU RAM use along the way, then dropped to 50% and then climbed back up to 75% and is staying there now. No errors, and it looks like everything is still running but I can't tell as nothing is getting printed to the terminal...

Also, it looks like the training is using only one of the GPUs at 100%. Is the command line below incorrect or could it be that one of the two distributed processes failed because it ran out of memory but w/o an error message? I am not sure if I should wait or quit and add a few Gbs of memory at this point or, perhaps, this code can only be used effectively on a DGX workstation with terabytes of RAM?


=============

root@5ff091f51565:/workspace/nemo_examples/asr# python -m torch.distributed.launch --nproc_per_node=2 /home/pakh0002/NeMo/examples/asr/jasper.py --batch_size=32 --num_epochs=30 --lr=0.015 --warmup_steps=8000 --weight_decay=0.001 --train_dataset=/home/pakh0002/data/all-train-manifest-16kHz_clean.json --eval_datasets /home/pakh0002/data/test-manifests/wls-16khz-test.json --model_config=/home/pakh0002/NeMo/examples/asr/configs/quartznet15x5.yaml --exp_name=ALL_16khz_ASR --work_dir=/home/pakh0002/data/models/nemo/work/ --checkpoint_dir=/home/pakh0002/data/models/nemo/checkpoints/ --tensorboard_dir=/home/pakh0002/data/models/nemo/tensorboard/

...

2020-01-13 17:27:23,965 - INFO - Doing ALL GPU
2020-01-13 17:39:05,291 - INFO - Dataset loaded with 4926.08 hours. Filtered 65.25 hours.
2020-01-13 17:39:05,292 - INFO - Parallelizing DATALAYER
HERE: 6
2020-01-13 17:39:05,303 - INFO - Have 3523063 examples to train on.
2020-01-13 17:39:05,309 - INFO - PADDING: 16
2020-01-13 17:39:05,309 - INFO - STFT using conv
2020-01-13 17:39:05,541 - INFO - Dataset loaded with 0.32 hours. Filtered 0.00 hours.
2020-01-13 17:39:05,542 - INFO - Parallelizing DATALAYER
2020-01-13 17:39:06,010 - INFO - ================================
2020-01-13 17:39:06,012 - INFO - Number of parameters in encoder: 18894656
2020-01-13 17:39:06,012 - INFO - Number of parameters in decoder: 29725
2020-01-13 17:39:06,014 - INFO - Total number of parameters in model: 18924381
2020-01-13 17:39:06,015 - INFO - ================================
2020-01-13 17:39:06,016 - WARNING - Data Layer does not have any weights to return. This get_weights call returns None.
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
2020-01-13 17:39:06,028 - INFO - Doing distributed training

**Comment by borisgin** [comment]
What is batch size per GPU?

**Comment by spakhomov** [comment]
32

**Comment by borisgin** [comment]
Have you tried 16?

**Comment by spakhomov** [comment]
Not yet - trying with 24 right now.

**Comment by spakhomov** [comment]
should I set the load_audio back to True and try with smaller batch size?

**Comment by borisgin** [comment]
Do you have OOM with 1 GPU?

**Comment by spakhomov** [comment]
Failed with batch size = 24. Now trying single GPU, load_audio=True and batch_size=16:

root@5ff091f51565:/workspace/nemo_examples/asr# python /home/pakh0002/NeMo/examples/asr/jasper.py --batch_size=16 --num_epochs=30 --lr=0.015 --warmup_steps=8000 --weight_decay=0.001 --train_dataset=/home/pakh0002/data/all-train-manifest-16kHz_clean.json --eval_datasets /home/pakh0002/data/test-manifests/wls-16khz-test.json --model_config=/home/pakh0002/NeMo/examples/asr/configs/quartznet15x5.yaml --exp_name=ALL_16khz_ASR --work_dir=/home/pakh0002/data/models/nemo/work/ --checkpoint_dir=/home/pakh0002/data/models/nemo/checkpoints/ --tensorboard_dir=/home/pakh0002/data/models/nemo/tensorboard/

**Comment by spakhomov** [comment]
Interesting... Got a bit further this time - ran out of memory during the evaluation this time, but it did get through one training step.

=====================
root@5ff091f51565:/workspace/nemo_examples/asr# python /home/pakh0002/NeMo/examples/asr/jasper.py --batch_size=16 --num_epochs=30 --lr=0.015 --warmup_steps=8000 --weight_decay=0.001 --train_dataset=/home/pakh0002/data/all-train-manifest-16kHz_clean.json --eval_datasets /home/pakh0002/data/test-manifests/wls-16khz-test.json --model_config=/home/pakh0002/NeMo/examples/asr/configs/quartznet15x5.yaml --exp_name=ALL_16khz_ASR --work_dir=/home/pakh0002/data/models/nemo/work/ --checkpoint_dir=/home/pakh0002/data/models/nemo/checkpoints/ --tensorboard_dir=/home/pakh0002/data/models/nemo/tensorboard/
/opt/conda/lib/python3.6/site-packages/torchvision/io/_video_opt.py:17: UserWarning: video reader based on ffmpeg c++ ops not available
  warnings.warn("video reader based on ffmpeg c++ ops not available")
Could not import torchaudio. Some features might not work.
2020-01-13 19:53:21,950 - INFO - Dataset loaded with 4926.08 hours. Filtered 65.25 hours.
HERE: 12
2020-01-13 19:53:21,950 - INFO - Have 3523063 examples to train on.
2020-01-13 19:53:21,952 - INFO - PADDING: 16
2020-01-13 19:53:21,952 - INFO - STFT using conv
2020-01-13 19:53:23,780 - INFO - Dataset loaded with 0.32 hours. Filtered 0.00 hours.
2020-01-13 19:53:24,172 - INFO - ================================
2020-01-13 19:53:24,174 - INFO - Number of parameters in encoder: 18894656
2020-01-13 19:53:24,174 - INFO - Number of parameters in decoder: 29725
2020-01-13 19:53:24,176 - INFO - Total number of parameters in model: 18924381
2020-01-13 19:53:24,176 - INFO - ================================
2020-01-13 19:53:24,178 - WARNING - Data Layer does not have any weights to return. This get_weights call returns None.
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
2020-01-13 19:53:24,188 - INFO - Starting .....
2020-01-13 19:53:24,191 - INFO - Found 2 modules with weights:
2020-01-13 19:53:24,191 - INFO - JasperEncoder
2020-01-13 19:53:24,191 - INFO - JasperDecoderForCTC
2020-01-13 19:53:24,191 - INFO - Total model parameters: 18924381
2020-01-13 19:53:24,191 - INFO - Restoring checkpoint from folder /home/pakh0002/data/models/nemo/checkpoints/ ...
2020-01-13 19:53:24,194 - WARNING - For module JasperDecoderForCTC, no file matches  in /home/pakh0002/data/models/nemo/checkpoints/
2020-01-13 19:53:24,194 - WARNING - Checkpoint folder /home/pakh0002/data/models/nemo/checkpoints/ present but did not restore
2020-01-13 19:53:24,194 - INFO - Starting epoch 0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
2020-01-13 19:53:29,590 - INFO - Step: 0
2020-01-13 19:53:29,596 - INFO - Loss: 715.59033203125
2020-01-13 19:53:29,596 - INFO - training_batch_WER:  100.00%
2020-01-13 19:53:29,596 - INFO - Prediction: zfrqorfuhwfjhujupelppzjglqhqqjutwmjcgwyfzwzgzwfzfphcieiywfh
2020-01-13 19:53:29,596 - INFO - Reference: so what kind of work you do
2020-01-13 19:53:29,597 - INFO - Step time: 3.2905149459838867 seconds
2020-01-13 19:53:29,597 - INFO - Doing Evaluation ..............................
Traceback (most recent call last):
  File "/home/pakh0002/NeMo/examples/asr/jasper.py", line 315, in <module>
    main()
  File "/home/pakh0002/NeMo/examples/asr/jasper.py", line 311, in main
    batches_per_step=args.iter_per_step)
  File "/opt/conda/lib/python3.6/site-packages/nemo/core/neural_factory.py", line 616, in train
    gradient_predivide=gradient_predivide)
  File "/opt/conda/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 1512, in train
    self._perform_on_iteration_end(callbacks=callbacks)
  File "/opt/conda/lib/python3.6/site-packages/nemo/core/neural_factory.py", line 198, in _perform_on_iteration_end
    callback.on_iteration_end()
  File "/opt/conda/lib/python3.6/site-packages/nemo/core/callbacks.py", line 435, in on_iteration_end
    self.action._eval(self._eval_tensors, self, step)
  File "/opt/conda/lib/python3.6/site-packages/nemo/backends/pytorch/actions.py", line 607, in _eval
    for epoch_i, data in enumerate(eval_dataloader, 0):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by spakhomov** [comment]
Got exact same memory error with batch_size = 8 and a single GPU.

**Comment by spakhomov** [comment]
Ah - need to set the eval_batch_size too... Trying with batch_size=16 and eval_batch_size=16

**Comment by borisgin** [comment]
Can you try with small  evaluation batch? 
Btw, can you add output of "top/htop"?

**Comment by spakhomov** [comment]
OK - 16 train and 16 eval batch size failed. Trying with 8/8. Here is output of top:

Tasks: 413 total,   3 running, 318 sleeping,   0 stopped,   1 zombie
%Cpu(s): 11.2 us,  1.4 sy,  0.0 ni, 86.5 id,  0.0 wa,  0.0 hi,  0.9 si,  0.0 st
KiB Mem : 16316448 total,  7676632 free,  6478964 used,  2160852 buff/cache
KiB Swap:  2097148 total,      580 free,  2096568 used.  9333444 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                         
17433 root      20   0 12.813g 1.317g 173524 R  99.7  8.5   2:24.25 python                                                                                          
 2461 pakh0002  20   0 4920868 277808  48480 R  12.6  1.7 256:19.35 gnome-shell                                                                                     
 2317 root      20   0  592064  49388  35272 S  11.3  0.3 201:55.42 Xorg                                                                                            
10642 pakh0002  20   0  660000  14416   1748 S   6.3  0.1  80:06.64 gnome-system-mo                                                                                 
 3095 pakh0002  20   0  854008  39356   8428 S   4.6  0.2 160:31.37 gnome-terminal-                                                                                 
 1799 pakh0002  20   0  949836 559100   1352 S   3.0  3.4 129:02.31 bash                                                                                            
 1507 root     -51   0       0      0      0 S   2.0  0.0 133:04.28 irq/73-nvidia                                                                                   
19688 pakh0002  20   0 3747456 423368  23424 S   1.7  2.6  80:41.60 Web Content                                                                                     
10885 pakh0002  20   0 1052252  16752     96 S   1.3  0.1 127:41.37 audacity                                                                                        
17849 pakh0002  20   0   51476   4156   3412 R   0.7  0.0   0:00.44 top                                                                                             
18248 pakh0002  20   0   21384   1068    956 S   0.7  0.0   0:00.02 rsync                                                                                           
 1197 pakh0002  20   0   11300    208     60 S   0.3  0.0  13:07.69 ssh-agent                                                                                       
 2156 gdm       20   0  699112  19400   2020 S   0.3  0.1 163:34.21 gsd-color                                                                                       
 2311 pakh0002  20   0  435960    952      0 S   0.3  0.0   4:38.64 gnome-keyring-d                                                                                 
 2630 pakh0002  20   0  701120  18664   1488 S   0.3  0.1 161:30.63 gsd-color                                                                                       
 2842 root      20   0  856204 833752      0 S   0.3  5.1 502:39.50 mount.ntfs                                                                                      
12629 pakh0002  20   0   21776   2444   1724 S   0.3  0.0  16:11.98 watch                                                                                           
15876 pakh0002  20   0 3972312 347936  76992 S   0.3  2.1  19:26.46 firefox                                                                                         
18768 root      20   0       0      0      0 I   0.3  0.0   0:00.84 kworker/u24:2-e                                                                                 
27307 root      20   0       0      0      0 I   0.3  0.0   0:01.25 kworker/4:1-eve                                                                                 
    1 root      20   0  225880   5964   3576 S   0.0  0.0   1:29.70 systemd                                                                                         
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.57 kthreadd                                                                                        
    3 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_gp                                                                                          
    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_par_gp                                                                                      
    6 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 kworker/0:0H-kb                                                                                 
    8 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_wq                                                                                    
    9 root      20   0       0      0      0 S   0.0  0.0   1:39.17 ksoftirqd/0                                                                                     
   10 root      20   0       0      0      0 I   0.0  0.0  38:53.32 rcu_sched                                                                                       
   11 root      rt   0       0      0      0 S   0.0  0.0   0:26.78 migration/0                                                                                     
   12 root     -51   0       0      0      0 S   0.0  0.0   0:00.00 idle_inject/0                                                                                   
   14 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0                                                                                         
   15 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1                                                                                         
   16 root     -51   0       0      0      0 S   0.0  0.0   0:00.00 idle_inject/1

**Comment by spakhomov** [comment]
Train 8 and test 8 failed - same memory error. Trying train bs = 16 and eval bs = 1. Looks like I need to add some RAM regardless...

**Comment by borisgin** [comment]
or you can try to run in text mode w/o display manager

**Comment by spakhomov** [comment]
I am still puzzled though. I have just tried training with bs = 8 and eval bs = 1 and I am still running out of memory during evaluation...

**Comment by spakhomov** [comment]
Same error with train bs = 4 and eval bs = 1. It looks like something is trying to allocate too much memory during the evaluation step regardless of the eval bs setting...

**Comment by blisc** [comment]
How large is your eval dataset?

**Comment by spakhomov** [comment]
Very small - 10 samples of under 15 seconds in length.

**Comment by blisc** [comment]
That sounds very strange. What happens if you remove eval datasets? What happens if you trim your training dataset to 2500 hours, 1000 hours, 500 hours, 100 hours, etc? I'm curious if you have found any working configs yet.
What you call nemo_asr.AudioToTextDataLayer in jasper.py, what happens if you set num_workers to 1?

**Comment by spakhomov** [comment]
Thanks for the suggestions, blisc! I spent some time on upgrading memory to 64Gb and was able to get a working configuration with batch_size=16 and eval_batch_size=1. It's training right now... I am going to close this issue.
