### ISSUE TITLE
perfomance of matchboxnet on esc_50 dataset

### ISSUE THREAD

**Issue by NewEricWang** [NVIDIA/NeMo#2617]
Did anybody train matchboxnet model on esc_50 dataset?
What is the best performance?
My best accuracy is 86%. It seems a little low compared to AST model.
How to setup the super-parameters to get better performance for esc_50 dataset?

**Comment by titu1994** [comment]
We haven't tried this dataset. The defaults for the paper were tuned on the dev set of Google Speech Commands. If there is a dev set for this dataset, you will need to perform some hyper parameter search for it.

**Comment by NewEricWang** [comment]
Thanks a lot!
I also try to tune the hyper parameters, such as lr, batch_size, jasper, repeat, optimer, spec_augment.
But I can't obtain better results.  
What are the possible reasons? Lack of data? Longer audio ?

**Comment by titu1994** [comment]
Possibly. I can't comment about audio quality or how good the label set is, but you could try larger MatchboxNet if you need scores more than deployment efficiency
