### ISSUE TITLE
nemo2jarvis/riva conversion error

### ISSUE THREAD

**Issue by yerzhan7orazayev** [NVIDIA/NeMo#2624]
I am getting the following error while trying to conver from .nemo to .ejrvs format via
`nemo2jarvis --out HFG.ejrvs HFG.nemo`. Using NeMo version of 1.2.0 and Jarvis version of 1.3.0b0. Any idea on how to fix it? Thanks a lot in advance.
```
INFO: Restoring NeMo model from 'HFG.nemo'
ERROR: Nemo2Jarvis: Failed to restore model from NeMo file : HFG.nemo. Please make sure you have the latest NeMo package installed with [all] dependencies.
Traceback (most recent call last):
  File "/opt/conda/bin/nemo2jarvis", line 8, in <module>
    sys.exit(nemo2jarvis())
  File "/opt/conda/lib/python3.8/site-packages/nemo2jarvis/cli/nemo2jarvis.py", line 48, in nemo2jarvis
    Nemo2Jarvis(args)
  File "/opt/conda/lib/python3.8/site-packages/nemo2jarvis/convert.py", line 44, in Nemo2Jarvis
    raise e
  File "/opt/conda/lib/python3.8/site-packages/nemo2jarvis/convert.py", line 37, in Nemo2Jarvis
    model = ModelPT.restore_from(restore_path=nemo_in)
  File "/workspace/nemo/nemo/core/classes/modelPT.py", line 481, in restore_from
    return cls._default_restore_from(restore_path, override_config_path, map_location, strict, return_config)
  File "/workspace/nemo/nemo/core/classes/modelPT.py", line 434, in _default_restore_from
    instance = cls.from_config_dict(config=conf)
  File "/workspace/nemo/nemo/core/classes/common.py", line 472, in from_config_dict
    instance = cls(cfg=config)
TypeError: Can't instantiate abstract class ModelPT with abstract methods list_available_models, setup_training_data, setup_validation_data

```

**Comment by titu1994** [comment]
Could you describe the Nemo version and the actual model you would like to export ?

**Comment by yerzhan7orazayev** [comment]
Thanks for promt response, I was just editing the comment above of mine. I am trying to export both HifiGan and FastPitch, and this error happens with both of them, unfortunately.

**Comment by titu1994** [comment]
The Riva team are currently looking into this

**Comment by yerzhan7orazayev** [comment]
Dear @titu1994,

is there any update on this issue?

**Comment by umerjamil16** [comment]
Dear @titu1994 

I am facing the same error when converting .nemo model to .riva format using nemo2riva.
I am using latest nemo version and rivai v1.4.0 

Please let us know if there is any update on this.

**Comment by yerzhan7orazayev** [comment]
Dear @umerjamil16 ,

I could solve for now this problem by running nvcr.io/nvidia/nemo:1.2.0 docker image.

**Comment by titu1994** [comment]
Sorry, forgot to respond to this. We should probably have a note somewhere for docker image releases. Will discuss with team
