### ISSUE TITLE
how to properly checkpoint for incremental optimization of the ASR model

### ISSUE THREAD

**Issue by joepareti54** [NVIDIA/NeMo#2628]
I am using [this code](https://github.com/NVIDIA/NeMo/blob/v1.0.2/tutorials/asr/01_ASR_with_NeMo.ipynb) and a VCTK corpus for training. Due to the large data-set size I split it up in chunks and use checkpoint to save the model, and then read the checkpoint model for training on further data records. The issue is that when I read in the checkpoint the inference does not deliver the expected results. So I suspect the way I handle the checkpoint is the culprit:

In [this notebook](https://github.com/joepareti54/joepareti54/blob/main/NB_3_chkpt.ipynb) I train the model, save a checkpoint and do some inference. The results appear reasonable.

In [this notebook ](https://github.com/joepareti54/joepareti54/blob/main/NB_3a_chkpt.ipynb) I read in the checkpoint from the step above, train the model on just a few lines and do inferences: the results are different, and it looks like the model was not properly saved or restored.

My overall assumption is that the NeMo model lends itself to transfer learning, so that I can use the public version and refine it incrementally with my own data: is this a valid assumption?

**Comment by joepareti54** [comment]
perhaps the answer to my question is [here](https://github.com/joepareti54/joepareti54/blob/main/ASR_Verify_1.ipynb) and it is related on how to use the checkpoint according to the the [users guide](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/v1.0.0/asr/results.html)

**Comment by titu1994** [comment]
Yes Nemo models are very useful for transfer learning, and saving them with save_to and using restore_from is the best way. 

You can use experiment manager flags to always save a Nemo file during training if you want to avoid the manual save.

**Comment by joepareti54** [comment]
I need to understand how to use the checkpoint file. If this code is used:
`MODEL = nemo_asr.models.EncDecCTCModel.restore_from(CHECKPOINT_FILE_IN)
MODEL.setup_training_data(train_data_config=params['model']['train_ds'])
MODEL.setup_validation_data(val_data_config=params['model']['validation_ds'])
`
then the results are reasonable and I can train MODEL on additional data per train_ds.
However, if i use:
`
from omegaconf import DictConfig
params['model']['train_ds']['manifest_filepath'] = TRAIN_MANIFEST
params['model']['validation_ds']['manifest_filepath'] = TEST_MANIFEST
first_asr_model_continued = nemo_asr.models.EncDecCTCModel(cfg=DictConfig(params['model']), trainer=trainer)
first_asr_model_continued.restore_from(CHECKPOINT_FILE_IN)
`
then it looks like first_asr_model trains from scratch instead of using the weights set at the preceding iteration

**Comment by titu1994** [comment]
Restore from is a class method - it's meant to load a entire model, not to load weights. The first way is the correct way - restore the model, edit it's config and update it's dataloader and then train the model - this model has been restored with the parameters from the Nemo checkpoint.

Please refer to Nemo docs about how to use restore from, and the fine tuning ASR tutorial (for another language, but same steps are used for same language too) for advice on steps to fine tune a given Nemo checkpoint

**Comment by joepareti54** [comment]
thank you. I am training the EncDecCTCModel of the[ tutorial ](https://github.com/NVIDIA/NeMo/blob/v1.0.2/tutorials/asr/01_ASR_with_NeMo.ipynb) on a VCTK corpus containing 44000 pairs of .wav files and transcript .txt files. On this basis I build the manifest. After training the model on lines 20000 to 40000 I get some reasonable inferences on wav files that were not seen at training time, and I store the model in a checkpoint file. When I load this checkpoint file and continue the training from line 40000 to 41000 the inferences are considerably worse. My expectation was same or better results than the first run: is this the right expectation or where should I look for the root cause.

**Comment by titu1994** [comment]
If the model is finetuned on just 1000 lines, it will forget everything it has previously learned. Catastrophic forgetting issue is common in all NN models and ASR is no exception. 

To preserve your scores you would need to train on the 20-41k lines in totality. Fine-tune checkpoints are useful to train a model quickly on a new dataset, not preserve the performance on the old dataset.

**Comment by joepareti54** [comment]
It is amazing that using quartznet as is, i.e. without re-training or fine tuning the model I get the best[ results](https://docs.google.com/spreadsheets/d/1Dg6NlH_BR1aCqpLUMA8I1cz5GCIkLpACNdXUj_hgR_Y/edit?usp=sharing).  

I could not further train quartznet on my PC, seemingly due to memory limitations, and I wonder if using my VCTK corpus would further improve the results, or if there is no gain similar to the  EncDecCTCModel.

In addition, it would help to know what configuration is required to effectively train quartznet, should I move to the cloud

**Comment by titu1994** [comment]
If you have a local GPU, you can try reducing batch size to 8 and accumulate grad 4x in the trainer. Should mostly be equivalent. 

The QuartzNet model was trained on nearly 5000 hours of speech, roughly 2.5 Million audio files, from various public corpora. Finetuning on a specific domain will usually help that domain only and degrade generalization performance on other domains unless the corpus is as large as or even larger than the original dataset

**Comment by titu1994** [comment]
You can also try Citrinet 512 or Conformer Medium since they preserve more memory than QuartzNet due to their large stride
