### ISSUE TITLE
Word timestamps

### ISSUE THREAD

**Issue by qo4on** [NVIDIA/NeMo#2661]
Hi!
You have a nice [CTC_Segmentation_Tutorial](https://github.com/NVIDIA/NeMo/blob/main/tutorials/tools/CTC_Segmentation_Tutorial.ipynb) where you split audio and its transcript into small chunks. Is it possible to return a timestamp for each word in the transcript? Or maybe NeMo has another model for that?

**Comment by qo4on** [comment]
Is anybody here?

**Comment by Slava715** [comment]
This is possible when using a different decoder: https://github.com/NVIDIA/NeMo/discussions/2577
