### ISSUE TITLE
I have a problem in the nemo_nlp module. What caused this?

### ISSUE THREAD

**Issue by liuxuejin** [NVIDIA/NeMo#2679]
Installation：

!sudo apt-get update 
!sudo apt-get install -y libsndfile1 ffmpeg
!pip install Cython
!pip install nemo_toolkit['all']

Successfully installed

However, using from nemo.collections import nlp as nemo_nlp will cause problems

ttributeError                            Traceback (most recent call last)
<ipython-input-4-7d6a210455cf> in <module>
----> 1 from nemo.collections import nlp as nemo_nlp

/opt/conda/envs/python3/lib/python3.6/site-packages/nemo/collections/nlp/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from nemo.collections.nlp import data, losses, models, modules
     16 from nemo.package_info import __version__
     17 

/opt/conda/envs/python3/lib/python3.6/site-packages/nemo/collections/nlp/models/__init__.py in <module>
     14 
     15 from nemo.collections.nlp.models.dialogue_state_tracking.sgdqa_model import SGDQAModel
---> 16 from nemo.collections.nlp.models.duplex_text_normalization import (
     17     DuplexDecoderModel,
     18     DuplexTaggerModel,

/opt/conda/envs/python3/lib/python3.6/site-packages/nemo/collections/nlp/models/duplex_text_normalization/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from nemo.collections.nlp.models.duplex_text_normalization.duplex_decoder import DuplexDecoderModel
     16 from nemo.collections.nlp.models.duplex_text_normalization.duplex_tagger import DuplexTaggerModel
     17 from nemo.collections.nlp.models.duplex_text_normalization.duplex_tn import DuplexTextNormalizationModel

/opt/conda/envs/python3/lib/python3.6/site-packages/nemo/collections/nlp/models/duplex_text_normalization/duplex_decoder.py in <module>
     23 from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, DataCollatorForSeq2Seq
     24 
---> 25 import nemo.collections.nlp.data.text_normalization.constants as constants
     26 from nemo.collections.nlp.data.text_normalization import TextNormalizationDecoderDataset
     27 from nemo.collections.nlp.models.duplex_text_normalization.utils import is_url

/opt/conda/envs/python3/lib/python3.6/site-packages/nemo/collections/nlp/data/text_normalization/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from nemo.collections.nlp.data.text_normalization.decoder_dataset import TextNormalizationDecoderDataset
     15 from nemo.collections.nlp.data.text_normalization.tagger_dataset import TextNormalizationTaggerDataset
     16 from nemo.collections.nlp.data.text_normalization.test_dataset import TextNormalizationTestDataset

/opt/conda/envs/python3/lib/python3.6/site-packages/nemo/collections/nlp/data/text_normalization/decoder_dataset.py in <module>
     19 from transformers import PreTrainedTokenizerBase
     20 
---> 21 import nemo.collections.nlp.data.text_normalization.constants as constants
     22 from nemo.collections.nlp.data.text_normalization.utils import read_data_file
     23 from nemo.core.classes import Dataset

AttributeError: module 'nemo.collections' has no attribute 'nlp'

**Comment by titu1994** [comment]
Is this with Nemo 1.2.0? Can you try with main branch ? Fyi @ekmb

**Comment by ekmb** [comment]
@titu1994 this was fixed in [2597 ](https://github.com/NVIDIA/NeMo/pull/2597). 
@liuxuejin please try with the main branch as @titu1994 suggested

**Comment by liuxuejin** [comment]
ok i ll try

**Comment by liuxuejin** [comment]
Thanks, finally succeeded
