### ISSUE TITLE
Cut long dataset

### ISSUE THREAD

**Issue by DiegoJota** [NVIDIA/NeMo#2680]
Hi,
Assuming I have a large volume of data, around 10,000 hours, doing this on a relatively weak gpu would take a long time, more than months...
If I want, can I split my base into several parts and do a workout for each of them, always restoring the model from the last workout I did? Or is it better if I do the full base training? For this training in parts, do I have to worry about a parameter?
I'm building a dataSet in Portuguese and I'm facing this problem...

**Comment by titu1994** [comment]
Catastrophic forgetting is an issue common to all neural networks. They will eventually forget all they were trained on and remember only that which they were trained on at this training run. 

I would suggest trying it with small subsets of the dataset and try to find tune in multiple stages but I'm pretty sure performance over older datasets will degrade
