### ISSUE TITLE
Online ASR Mic demo not working on CPU?

### ISSUE THREAD

**Issue by sunilpro** [NVIDIA/NeMo#269]
I had installed NeMo from source using the reinstall.sh on my OS X without CUDA support and tried the Online ASR example with inbuilt microphone and CPU backend but nothing’s printed on the console as I speak.

Is this a known issue? Does it work only with NVIDIA GPU/CUDA?

**Comment by okuchaiev** [comment]
1) Did you set Neural Factory to CPU?
```python
neural_factory = nemo.core.NeuralModuleFactory(
    placement=nemo.core.DeviceType.CPU,
    backend=nemo.core.Backend.PyTorch)
```
2) Have you installed portaudio, like so "brew install portaudio"?

I have tried this on my MacBook (2.4 GHz Intel Core i5 2019 model) and it runs but is unusably slow. Basically, for whatever reasons Jupyter notebook seems to allow the usage of only one CPU core for this process.
If you have access to linux-based machine, I'd recommend you try it there.

**Comment by sunilpro** [comment]
@okuchaiev You're right it is slow, I see some words/letters randomly printing at random intervals of 20-30 secs
But I tried with plain python script (just copied the python code to a new .py file and ran it). I guess its nothing to do with Jupyter.

I'll try in docker (via tcp streaming) and post my findings here

**Comment by sunilpro** [comment]
Update:
Indeed the streaming works on CPU just that it's too slow for realtime audio streaming. So I modified the python script to make it work with bigger frame size:
https://gist.github.com/sunilpro/daed6cfd154caaef2e52f4dc00c4d951

cat ../audio/4507-16021-0012.wav|./nemo_asr_streaming.py
or
Using sox live recording:
rec -c 1 -b 16 -r 16000 -t raw -|./nemo_asr_streaming.py

**Comment by malarinv** [comment]
https://github.com/NVIDIA/NeMo/blob/321cac41b7041140a3350b517fcfeee075e13960/nemo/backends/pytorch/actions.py#L727

I tried the Online ASR Notebook on a CPU node and it crashed here, was able to fix it by checking for cuda availability.
```
                if torch.cuda.is_available():
                    logging.debug(torch.cuda.memory_allocated())
```
