### ISSUE TITLE
Pretrained KenLM for Citrinet/Conformer?

### ISSUE THREAD

**Issue by loganlebanoff** [NVIDIA/NeMo#2694]
I see in the catalog for Conformer that there were experiments performed using an N-Gram LM for Librispeech evaluation (https://ngc.nvidia.com/catalog/models/nvidia:nemo:stt_en_conformer_ctc_large). Can these pretrained LM's be made available?

**Comment by VahidooX** [comment]
Please take a look here:
https://github.com/NVIDIA/NeMo/discussions/2619
N-gram models are very easy and fast to train.

**Comment by loganlebanoff** [comment]
Thanks, I'll take a look.
