### ISSUE TITLE
Minimim requirments to run a training on hi-mia dataset?

### ISSUE THREAD

**Issue by ali2iptoki** [NVIDIA/NeMo#2709]
It is not a bug but a request in case some one know what the are the hardware (minimum) requirements to run a speaker verification on hi-mia dataset. I mean how much memory, gpu etc?

Indeed, did you have any time expectation to finish the training on hi-mia? one day, two days, etc

**Comment by nithinraok** [comment]
Thanks for your question. Any GPU that supports the Cuda version>10 and memory>16Gb is good enough I believe. 

It depends on hours of dataset. For an idea: Voxceleb has apprx 1900hrs of training data, we train on 16GB 8 GPUs (V100s) with batch_size as 64 for 200 epochs for 56hrs. 

HI-MIA train set has apprx (760hrs of data) so for the same setup as mentioned above for 50 epochs it would take 5.6 hrs. On single V100 GPU it may take apprx 44 hrs. You can calculate overall time based on time taken for single epoch, so for your training set, let it finish a single epoch and you may calculate overall time by `total_hrs = (time_taken_for_single_epoch*total_epochs).`
