### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by naymaraq** [NVIDIA/NeMo#2718]
I am training Conformer-medium on Multilingual Librispeech Dataset (~45000 hours).
During the training epoch, RAM is constantly increasing until no free space is left. Is there anything i can do to handle this?

Params:
RAM  = 256G
Batch_size = 32
Num_workers = 8

Also when I experimented with 21000 hours, at the end of the epoch, the memory has released.

Here is the trainer params:

trainer:
  gpus: -1
  num_nodes: 1
  max_epochs: 1000
  max_steps: null
  val_check_interval: 0.025 
  accelerator: ddp
  accumulate_grad_batches: 20
  gradient_clip_val: 0.0
  amp_level: O0 
  precision: 32 
  log_every_n_steps: 1  
  progress_bar_refresh_rate: 1
  resume_from_checkpoint: null
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1 
  sync_batchnorm: true
  checkpoint_callback: false
  logger: false

**Comment by VahidooX** [comment]
We don't use the RAM unless for loading the json files and as you have 8 workers, it is going to load the whole transcripts and audio paths 8*(NUM_GPUS) times into the memory. Not sure if it can fill up all your memory or not. 
Does the memory consumption increasing over the epoch or just the beginning? 
Do you get any errors? 
Can you try one of other models like Citrinet to make sure that it is not Conformer specific?

You may try using tarred datasets to avoid loading the whole json files:
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/datasets.html#tarred-datasets
https://github.com/NVIDIA/NeMo/blob/main/scripts/speech_recognition/convert_to_tarred_audio_dataset.py

**Comment by naymaraq** [comment]
@VahidooX thanks for replying

The memory consumption increasing over the epoch.
No i didn't get error except for "memory allocation error".
The same behavior I noticed with QuartzNet-15x5.

**Comment by VahidooX** [comment]
Would you please send me the exact error message and when it happened? At the end of the epoch before evaluation?

**Comment by naymaraq** [comment]
It happened at the middle of the epoch.
I didn't save the logs,,but the error was this "OSError: [Errno 12] Cannot allocate memory"

**Comment by Slava715** [comment]
Try to decrease num_workers, I also noticed that the more their number, the higher the RAM consumption. In my case, with num_workers = 16, 100Gb was used with num_workers = 8, 50GB was used, the size of the dataset was 5000.

**Comment by VahidooX** [comment]
Would you please share more detail how solved your issue? it may be useful to others.

**Comment by naymaraq** [comment]
In nemo/collections/asr/data/audio_to_text.py I have changes self.manifest_processor.collection by making it shareable. 

from multiprocessing import Manager
manager = Manager()
self.manifest_processor.collection = manager.list(self.manifest_processor.collection)

**Comment by khursani8** [comment]
I guess related to this issue https://github.com/pytorch/pytorch/issues/13246#issuecomment-905703662
Issue with python list/dict in pytorch Dataloader

**Comment by naymaraq** [comment]
@khursani8 Exactly.

**Comment by agemagician** [comment]
Hi @khursani8 ,

Could you please share the complete code ?
I am having the same issue, but I am not sure where did you add these lines in the code 

```
from multiprocessing import Manager
manager = Manager()
self.manifest_processor.collection = manager.list(self.manifest_processor.collection)
```

Are there any other changes that you made?

**Comment by agemagician** [comment]
@naymaraq ,

Have you tested your method fully ?
I was also thinking if it is better to add the multi-processing manager here instead:

https://github.com/NVIDIA/NeMo/blob/122ee9a1e8fa27ad1cf512ea579a52122848eac1/nemo/collections/common/parts/preprocessing/collections.py#L193

**Comment by naymaraq** [comment]
My code look-like this. 

In audio_to_text.py
 self.manifest_processor = ASRManifestProcessor(
            manifest_filepath=manifest_filepath,
            parser=parser,
            max_duration=max_duration,
            min_duration=min_duration,
            max_utts=max_utts,
            bos_id=bos_id,
            eos_id=eos_id,
            pad_id=pad_id,
        )

manager = Manager()
self.manifest_processor.collection = manager.list(self.manifest_processor.collection)

**Comment by naymaraq** [comment]
Yes, You should replace named tuples with basic tuples.
You should change this file.

../nemo/collections/common/parts/preprocessing/collections.py

**Comment by agemagician** [comment]
Great, thanks a lot .

**Comment by titu1994** [comment]
https://github.com/NVIDIA/NeMo/issues/2718#issuecomment-909238620

Does it not work with named tuples ?

**Comment by agemagician** [comment]
Hmm, it didn't work with me after changing collections.py to normal tuples. It caused other errors.

@naymaraq Is it possible to fork Nemo and apply the changes that made it work so that we can replicate the results.

**Comment by naymaraq** [comment]
@agemagician, because you replaced named tuples with usual tuples, you should change indexing as well. 
Like this
<img width="337" alt="Screen Shot 2021-09-01 at 00 32 10" src="https://user-images.githubusercontent.com/47416614/131571829-88b27618-3b3a-41fc-b401-750eb3870e61.png">

**Comment by agemagician** [comment]
Thanks a lot.

I hope Nvidia could adopt Nemo to integrate this solution or something similar.

**Comment by titu1994** [comment]
Moving away from named tuples to tuples makes the codebase more brittle to positional changes in arguments. It's also sad that this is an issue at near python level. We will consider some options but this becomes a significant issue for significantly large manifests which is concerning since datasets are going larger. 

The one thing we would like to ask is if this issue occurs with tarred dataset as well (I think it will, just want to confirm). 

For now I'm closing the issue since the solution was obtained but we'll need to look into it further for a viable alternative

**Comment by mehadi92** [comment]
Face the same issue for tarred data [6693](https://github.com/NVIDIA/NeMo/discussions/6693)

**Comment by IgorZan** [comment]
Is there any solution out? num_workers not just leads to fluctuate TFLOPS, but possible OOM...

**Comment by LiamLonergan** [comment]
@titu1994 

Has there been a solution to this problem? I'm also experiencing system ram OOM with a large-ish dataset of 9k hours, continuing pre-training of NEST SSL model. I have 128Gb of system ram. Reducing num_workers helps to some degree, but ultimately the training cannot complete a single epoch without failing.
