### ISSUE TITLE
Deploy speaker diarize model?

### ISSUE THREAD

**Issue by An-BN** [NVIDIA/NeMo#2723]
Hello,

I trained VAD model and Speaker Net model to get timestamp of who is speaker in audio.
After speaker diarize, i want to pass the signal of speech to ASR model to get both who is speaker and text of speech.
Some thing like that:
![1](https://user-images.githubusercontent.com/49829097/130759168-29b6ea7b-a9f6-4cd4-b251-e6f00b6e747c.PNG)

So, what is the solution to deploy speaker diarize model in production?
Thanks!

**Comment by An-BN** [comment]
Hi, 
I see NeMo Speaker diarizer model provide function to diarize single files:
`sd_model.diarize(<path2_audio_file>)`
But the function write a lot of file such as vad output, speaker output embeddings during processing. This makes performance of model very slowly.
Is there any way to inference diarizer model without write output file?

**Comment by ShantanuNair** [comment]
Are there any updates regarding how we can run diarization in production? It hasn't made it into Riva yet.
