### ISSUE TITLE
Fine-tune stt_zh_quartznet15x5 model  with custom dataset

### ISSUE THREAD

**Issue by kaiven11** [NVIDIA/NeMo#2725]
**Describe the bug**

1. Output reference is not correct on chinese, could it affect the model?
![image](https://user-images.githubusercontent.com/25794106/130772485-45c4e6c0-470c-431f-8230-1ef2a296dc23.png)

  I follow the  link below:
  https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/10_ASR_CTC_Language_Finetuning.ipynb#scrollTo=x0i8hvt688hc
2. I have four gpus, But  just use one; 

**Steps/Code to reproduce bug**

 step 1: I  prepare the dataset ,  
          **manifest files:**
          train_manifest="dataset/manifest_train.json"
          test_manifest = "dataset/manifest_test.json"
          dev_manifest = "dataset/manifest_dev.json"
         **charset:**
          train_charset = get_charset(train_manifest_data)
          dev_charset = get_charset(dev_manifest_data)
          test_charset = get_charset(test_manifest_data)

      
step 2: load model config , update the config 
            freeze_encoder = True
            cfg.train_ds.manifest_filepath  = "train_manifest,dev_manifest"

            use_cer = True
            log_prediction = True
            model._wer.use_cer = use_cer
            model._wer.log_prediction = log_prediction

step 3: train 
          
![image](https://user-images.githubusercontent.com/25794106/130769707-8ac3b2d4-dc08-4878-9d1c-8c4a907f34ba.png)

         
**Expected behavior**

the reference part  should be the correct sentence；
as you see ,the output is out-of-order ， I expect the out  is  1 2 3 4 ,but the result is 2 1 3 4 ;
**Environment overview (please complete the following information)**

 - Environment location: local server  DGX V100
 - Method of NeMo install:  pip install 

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version :ubuntu 18.04
- PyTorch version:pytorch 1.9.0
- Python version :python3.7

**Additional context**

This is my train script:
[nemo_train.txt](https://github.com/NVIDIA/NeMo/files/7046204/nemo_train.txt)

**Comment by titu1994** [comment]
How long was the model trained for ? And was the model finetuned by changing the decoder or by keeping it the same ? To speed up convergence it would be better to not change the decoder if it's not required. 

There are also better Citrinet based mandarin character encodings models which you could try as well.

**Comment by haaddii** [comment]
> You can use the trainer.gpus=-1 in config which will use all available GPUs to train the model. It is preferred to do that in a script and not a notebook though

I get a `Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method` error when using `devices=-1,` option in pl.Trainer... Also following the CTC_lang_finetune tutorial. (I only modified that line) How can I resolve this error? Thanks in advance.

**Comment by haaddii** [comment]
> **Describe the bug**
> 
> 1. Output reference is not correct on chinese, could it affect the model?
>    ![image](https://user-images.githubusercontent.com/25794106/130772485-45c4e6c0-470c-431f-8230-1ef2a296dc23.png)
> 
> I follow the link below: https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/10_ASR_CTC_Language_Finetuning.ipynb#scrollTo=x0i8hvt688hc 2. I have four gpus, But just use one;
> 
> **Steps/Code to reproduce bug**
> 
> step 1: I prepare the dataset , **manifest files:** train_manifest="dataset/manifest_train.json" test_manifest = "dataset/manifest_test.json" dev_manifest = "dataset/manifest_dev.json" **charset:** train_charset = get_charset(train_manifest_data) dev_charset = get_charset(dev_manifest_data) test_charset = get_charset(test_manifest_data)
> 
> step 2: load model config , update the config freeze_encoder = True cfg.train_ds.manifest_filepath = "train_manifest,dev_manifest"
> 
> ```
>         use_cer = True
>         log_prediction = True
>         model._wer.use_cer = use_cer
>         model._wer.log_prediction = log_prediction
> ```
> 
> step 3: train
> 
> ![image](https://user-images.githubusercontent.com/25794106/130769707-8ac3b2d4-dc08-4878-9d1c-8c4a907f34ba.png)
> 
> **Expected behavior**
> 
> the reference part should be the correct sentence； as you see ,the output is out-of-order ， I expect the out is 1 2 3 4 ,but the result is 2 1 3 4 ; **Environment overview (please complete the following information)**
> 
> * Environment location: local server  DGX V100
> * Method of NeMo install:  pip install
> 
> **Environment details**
> 
> If NVIDIA docker image is used you don't need to specify these. Otherwise, please provide:
> 
> * OS version :ubuntu 18.04
> * PyTorch version:pytorch 1.9.0
> * Python version :python3.7
> 
> **Additional context**
> 
> This is my train script: [nemo_train.txt](https://github.com/NVIDIA/NeMo/files/7046204/nemo_train.txt)

May I ask about how much epochs it takes to show the correct reference ?
I have exact same problem now. But I've trained it for 200 epochs.

**Comment by haaddii** [comment]
> After several epoch training ,The output reference and predicted are correct, Thank you ! I did't change the encoder and decoder.
> 
> Now Nemo just use one gpu, how to use more gpus to speed up training , I had use set env.
> 
> `export CUDA_VISIBLE_DEVICES=0,1,2,3`
> 
> The Nemo log had explicitly found 4 gpus.
> 
> ![image](https://user-images.githubusercontent.com/25794106/130928111-74a780e9-22df-410d-8a4e-bc20e81dc48c.png)

May I ask about how much epochs it takes to show the correct reference ?
I have exact same problem now. But I've trained it for 200 epochs.
