### ISSUE TITLE
No scaling of loss for a virtual batch (single GPU, float32)

### ISSUE THREAD

**Issue by seovchinnikov** [NVIDIA/NeMo#274]
There is no scaling of loss according to a virtual batch in the branch for single GPU float32:
https://github.com/NVIDIA/NeMo/blob/2bb07bcda2e3e247efb1c7556560f05cf2bf0e65/nemo/nemo/backends/pytorch/actions.py#L1524
There are scaling for other cases but not for this one.

**Comment by okuchaiev** [comment]
do you want to send a PR fixing this? ;)

**Comment by seovchinnikov** [comment]
https://github.com/NVIDIA/NeMo/pull/275

**Comment by okuchaiev** [comment]
merged your fix. thanks!
