### ISSUE TITLE
Get feature map after encoder block in EncDecCTCModel

### ISSUE THREAD

**Issue by aniket7joshi** [NVIDIA/NeMo#2747]
I have trained a **EncDecCTCModel** using quartznet as the base architecture. While doing inference, I would like to get feature maps after the encoder and the decoder block separately. Using the transcribe function, I am able to get the audio transcripts but I am not able to check the feature maps in the intermediate layers. Is there any way to check out this?

**Comment by titu1994** [comment]
You can write your own function that duplicates the transcribe function call as well as manually call the encoder and decoder. However, you won't be able to easily split the encoders intermediate layers as it's a sequential module.
