### ISSUE TITLE
⁇ in predicted text

### ISSUE THREAD

**Issue by narek106** [NVIDIA/NeMo#2753]
The conformer network sometimes predicts "⁇" symbols. After greedy decoding, all the outputs have zero index, which corresponds to <"unk"> token. And finally, after applying sentencepiece tokenization I am getting  ⁇ symbols. 

Btw, all my transcripts successfully tokenized without producing any <"unk"> symbols. 

What can cause "⁇"  symbol?

**Comment by titu1994** [comment]
?? Is the "unk" token as well as the "pad" token when used in SPE based ASR models. If the text cannot be tokenized by the English SPE tokenizer it will emit ?? Instead

**Comment by narek106** [comment]
Why <'unk'> is needed, is it possible without it.

**Comment by titu1994** [comment]
It is needed for all Tokenizers in case they see out of vocabulary token when transcribing speech
