### ISSUE TITLE
 opencc, pangu and jieba core dependencies

### ISSUE THREAD

**Issue by vhsw** [NVIDIA/NeMo#2754]
Why `opencc`, `pangu` and `jieba` are required for nemo core?
https://github.com/NVIDIA/NeMo/blob/1d262c725df150ba837146e7899d8167adf524f6/requirements/requirements_lightning.txt#L5-L7

**Comment by MaximumEntropy** [comment]
Good point. These should be in NLP. I'll move it there.

**Comment by MaximumEntropy** [comment]
Thanks! This should be fixed once #2755 is merged.
