### ISSUE TITLE
Training performance in GPU Tesla vs GPU RTX

### ISSUE THREAD

**Issue by DiegoJota** [NVIDIA/NeMo#2756]
Hi,

I've been working on a dataset for a long time and slowly I see that my simple GPU isn't playing such a good role.
When searching I see several people using RTX and Tesla. Does anyone know what is the advantage of a Tesla GPU over an RTX GPU? Going into the question of price, I see that an RTX it's much more affordable...
For example, an RTX 3090 versus a Tesla V100, on comparison sites, I see that RTX stands out in a number of ways. Someone who has experience and can share, thank you in advance.

**Comment by titu1994** [comment]
Generally you want more memory for training larger models, whatever suits your budget. We can't provide exact recommendations but there are many guides that describe trade offs of gpus for deep learning that you could refer to
