### ISSUE TITLE
Documentation for usage of tarred dataset created by`create_tarred_parallel_dataset.py` is wrong

### ISSUE THREAD

**Issue by PeganovAnton** [NVIDIA/NeMo#2760]
**Describe the bug**

According to documentation on page https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/v1.3.0/nlp/machine_translation.html#tarred-datasets-for-large-corpora the second way to use tarred dataset is

**Quote**
2. Using a separate script without Hydra.

Tarred datasets for parallel corpora can also be created with a script that doesn’t require specifying a configs via Hydra and just uses Python argparse.

For example:
```
python examples/nlp/machine_translation/create_tarred_parallel_dataset.py \
  --shared_tokenizer \
  --clean \
  --bpe_dropout 0.1 \
  --src_fname train.tokenized.en \
  --tgt_fname train.tokenized.es \
  --out_dir /path/to/preproc_dir \
  --vocab_size 32000 \
  --max_seq_length 512 \
  --min_seq_length 1 \
  --tokens_in_batch 8192 \
  --lines_per_dataset_fragment 1000000 \
 --num_batches_per_tarfile 200
```
*You can then set `model.preproc_out_dir=/path/to/preproc_dir` and `model.train_ds.use_tarred_dataset=true` to train with this data.*
**End quote**

If I set parameter `model.preproc_out_dir` to directory with tar files and train dataset config is
```
  train_ds:
    src_file_name: null
    tgt_file_name: null
    use_tarred_dataset: True
    tar_file_prefix: parallel
```
calling `python enc_dec_nmt.py` results in error
```
Traceback (most recent call last):
  File "enc_dec_nmt.py", line 121, in main
    MTDataPreproc(cfg=cfg.model, trainer=trainer)
  File "/home/lab/anaconda3/envs/nemo/lib/python3.8/site-packages/nemo/collections/nlp/data/machine_translation/preproc_mt_data.py", line 181, in __init__
    raise ValueError(
ValueError: src_file_name and tgt_file_name needed to create tarred dataset but could not be found.
```

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal
 - Method of NeMo install: pip

**Environment details**

- OS version: Ubuntu 20.04.2 LTS
- PyTorch version: 1.8.1
- Python version: 3.8

**Comment by titu1994** [comment]
@MaximumEntropy

**Comment by okuchaiev** [comment]
we think this is fixed now. re-open if issue is still relevant.
