### ISSUE TITLE
speech_to_text generates an error related to the json file?

### ISSUE THREAD

**Issue by ali2iptoki** [NVIDIA/NeMo#2761]
When I run the following scirpt: https://github.com/NVIDIA/NeMo/blob/main/examples/asr/speech_to_text.py
I get the following error:
```
[NeMo W 2021-09-01 16:08:13 experimental:27] Module <class 'nemo.collections.asr.data.audio_to_text_dali.AudioToCharDALIDataset'> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo I 2021-09-01 16:08:13 speech2text:44] Namespace(config_name='SpeakerNet_verification_3x2x512', config_path='/home/ubuntu/repos/algo/app/aliSrc/notebooks/conf', data_dir='/home/ubuntu/repos/algo/app/aliSrc/dataset/himia/train', gpu=0, max_epochs=50)
[NeMo I 2021-09-01 16:08:13 speech2text:61] =====[NeMo W 2021-09-01 16:08:13 nemo_logging:349] /home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:556: UserWarning: You requested distributed training on GPUs, but none is available, so we set backend to `ddp_cpu`.      rank_zero_warn(

[NeMo W 2021-09-01 16:08:13 nemo_logging:349] /home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:563: UserWarning: You are running on single node with no parallelization, so distributed has no effect.
      rank_zero_warn('You are running on single node with no parallelization, so distributed has no effect.')
GPU available: True, used: False
TPU available: False, using: 0 TPU cores[NeMo W 2021-09-01 16:08:14 nemo_logging:349] /home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:596: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.      rank_zero_warn(

[NeMo I 2021-09-01 16:08:14 exp_manager:217] Experiments will be logged at /home/ubuntu/repos/algo/app/nemo_experiments/SpeakerNet/2021-09-01_16-08-14[NeMo I 2021-09-01 16:08:14 exp_manager:564] TensorboardLogger has been set up
[NeMo W 2021-09-01 16:08:14 nemo_logging:349] /home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:396: LightningDeprecationWarning: Argument `period` in `ModelCheckpoint` is deprecated in v1.3 and will be removed in v1.5. Please use `every_n_val_epochs` instead.
      rank_zero_deprecation(

[NeMo I 2021-09-01 16:08:14 audio_to_text_dataset:36] Model level config does not container `sample_rate`, please explicitly provide `sample_rate` to the dataloaders.
[NeMo I 2021-09-01 16:08:14 audio_to_text_dataset:36] Model level config does not container `labels`, please explicitly provide `labels` to the dataloaders.
Traceback (most recent call last):
  File "/home/ubuntu/repos/algo/app/aliSrc/src/speech2text.py", line 70, in <module>
    main()
  File "/home/ubuntu/repos/algo/app/aliSrc/src/speech2text.py", line 66, in main
    asr_model = EncDecCTCModel(cfg=cfg.model, trainer=trainer)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/asr/models/ctc_models.py", line 153, in __init__
    super().__init__(cfg=cfg, trainer=trainer)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 128, in __init__
    self.setup_training_data(self._cfg.train_ds)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/asr/models/ctc_models.py", line 423, in setup_training_data
    self._train_dl = self._setup_dataloader_from_config(config=train_data_config)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/asr/models/ctc_models.py", line 390, in _setup_dataloader_from_config
    dataset = audio_to_text_dataset.get_char_dataset(config=config, augmentor=augmentor)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/asr/data/audio_to_text_dataset.py", line 75, in get_char_dataset
    dataset = audio_to_text.AudioToCharDataset(
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/asr/data/audio_to_text.py",line 250, in __init__
    super().__init__(
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/asr/data/audio_to_text.py",line 139, in __init__
    self.collection = collections.ASRAudioText(
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/common/parts/preprocessing/collections.py", line 193, in __init__
    for item in manifest.item_iter(manifests_files):
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/common/parts/preprocessing/manifest.py", line 72, in item_iter
    item = parse_func(line, manifest_file)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/collections/common/parts/preprocessing/manifest.py", line 107, in __parse_item
    raise ValueError(
ValueError: Manifest file /home/ubuntu/repos/algo/app/aliSrc/dataset/himia/train/train.json has invalid json line structure: {"audio_filepath": "/home/ubuntu/repos/algo/app/aliSrc/dataset/himia/train/SPEECHDATA_reduced/wav/SV0015/SV0015_5_15_N1744.wav", "offset": 0, "duration": 1.5600625, "label": "SV0015"}
 without proper text key.
```

**Comment by titu1994** [comment]
If you look into the manifest description for speech to text in Nemo docs, the keys that are required are audio_filepath, text and duration. You are missing text and have "label" instead. Also, note that numbers are not usually supported by ASR, you should use text normalization tools to process your text before training and text denormalization tools after model prediction to get numbers back.

**Comment by ali2iptoki** [comment]
@titu1994 Thanks. For an4 dataset how can I generate or get the text attribute?

**Comment by ali2iptoki** [comment]
@titu1994 Thanks. I create a script just similar to yours. But when I execute i get following exception:

`(aliEnv) ubuntu@iptoki:~/repos/algo/app$ python /home/ubuntu/repos/algo/app/aliSrc/src/speech2text.py --data_dir "/home/ubuntu/repos/algo/app/aliSrc/notebooks/data/an4" --config_name 'config'
/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  rank_zero_deprecation(
[NeMo W 2021-09-02 16:51:48 optimizers:47] Apex was not found. Using the lamb optimizer will error out.
[NeMo W 2021-09-02 16:51:49 nemo_logging:349] /home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
      warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################
[NeMo W 2021-09-02 16:51:51 experimental:27] Module <class 'nemo.collections.asr.data.audio_to_text_dali.AudioToCharDALIDataset'> is experimental, not ready for production and is not fully supported. Use at your own risk.
[NeMo I 2021-09-02 16:51:51 speech2text:46] Namespace(config_name='config', config_path='/home/ubuntu/repos/algo/app/aliSrc/notebooks/conf', data_dir='/home/ubuntu/repos/algo/app/aliSrc/notebooks/data/an4', gpu=0, max_epochs=50)
[NeMo I 2021-09-02 16:51:51 speech2text:62] cfg.trainer = {'gpus': 0, 'max_epochs': 5, 'max_steps': None, 'num_nodes': 1, 'accelerator': 'ddp', 'accumulate_grad_batches': 1, 'checkpoint_callback': False, 'logger': False, 'log_every_n_steps': 1, 'val_check_interval': 1.0}
[NeMo W 2021-09-02 16:51:51 nemo_logging:349] /home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:556: UserWarning: You requested distributed training on GPUs, but none is available, so we set backend to `ddp_cpu`.
      rank_zero_warn(
[NeMo W 2021-09-02 16:51:51 nemo_logging:349] /home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:563: UserWarning: You are running on single node with no parallelization, so distributed has no effect.      rank_zero_warn('You are running on single node with no parallelization, so distributed has no effect.')

GPU available: True, used: FalseTPU available: False, using: 0 TPU cores
[NeMo W 2021-09-02 16:51:51 nemo_logging:349] /home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:596: UserWarning: GPU available but not used. Set the gpus flag in your trainer `Trainer(gpus=1)` or script `--gpus=1`.
      rank_zero_warn(
[NeMo I 2021-09-02 16:51:51 speech2text:69] cfg.model={'train_ds': {'manifest_filepath': '/home/ubuntu/repos/algo/app/aliSrc/notebooks/data/an4/train_manifest.json', 'sample_rate': 16000, 'labels': [' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', "'"], 'batch_size': 32, 'trim_silence': True, 'max_duration': 16.7, 'shuffle': True, 'is_tarred': False, 'tarred_audio_filepaths': None, 'tarred_shard_strategy': 'scatter'}, 'validation_ds': {'manifest_filepath': '/home/ubuntu/repos/algo/app/aliSrc/notebooks/data/an4/test_manifest.json', 'sample_rate': 16000, 'labels': [' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', "'"], 'batch_size': 32, 'shuffle': False}, 'preprocessor': {'_target_': 'nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor', 'normalize': 'per_feature', 'window_size': 0.02, 'sample_rate': 16000, 'window_stride': 0.01, 'window': 'hann', 'features': 64, 'n_fft': 512, 'frame_splicing': 1, 'dither': 1e-05, 'stft_conv': False}, 'spec_augment': {'_target_': 'nemo.collections.asr.modules.SpectrogramAugmentation', 'rect_freq': 50, 'rect_masks': 5, 'rect_time': 120}, 'encoder': {'_target_': 'nemo.collections.asr.modules.ConvASREncoder', 'feat_in': 64, 'activation': 'relu', 'conv_mask': True, 'jasper': [{'filters': 128, 'repeat': 1, 'kernel': [11], 'stride': [1], 'dilation': [1], 'dropout': 0.0, 'residual': True, 'separable': True, 'se': True, 'se_context_size': -1}, {'filters': 256, 'repeat': 1, 'kernel': [13], 'stride': [1], 'dilation': [1], 'dropout': 0.0, 'residual': True, 'separable': True, 'se': True, 'se_context_size': -1}, {'filters': 256, 'repeat': 1, 'kernel': [15], 'stride': [1], 'dilation': [1], 'dropout': 0.0, 'residual': True, 'separable': True, 'se': True, 'se_context_size': -1}, {'filters': 256, 'repeat': 1, 'kernel': [17], 'stride': [1],'dilation': [1], 'dropout': 0.0, 'residual': True, 'separable': True, 'se': True, 'se_context_size': -1}, {'filters': 256,'repeat': 1, 'kernel': [19], 'stride': [1], 'dilation': [1], 'dropout': 0.0, 'residual': True, 'separable': True, 'se': True, 'se_context_size': -1}, {'filters': 256, 'repeat': 1, 'kernel': [21], 'stride': [1], 'dilation': [1], 'dropout': 0.0, 'residual': False, 'separable': True, 'se': True, 'se_context_size': -1}, {'filters': 1024, 'repeat': 1, 'kernel': [1], 'stride': [1], 'dilation': [1], 'dropout': 0.0, 'residual': False, 'separable': True, 'se': True, 'se_context_size': -1}]}, 'decoder': {'_target_': 'nemo.collections.asr.modules.ConvASRDecoder', 'feat_in': 1024, 'num_classes': 28, 'vocabulary': [' ','a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', "'"]}, 'optim': {'name': 'novograd', 'lr': 0.01, 'betas': [0.8, 0.5], 'weight_decay': 0.001, 'sched': {'name': 'CosineAnnealing', 'monitor': 'val_loss', 'reduce_on_plateau': False, 'warmup_steps': None, 'warmup_ratio': None, 'min_lr': 0.0, 'last_epoch': -1}}}
[NeMo I 2021-09-02 16:51:51 audio_to_text_dataset:36] Model level config does not container `sample_rate`, please explicitly provide `sample_rate` to the dataloaders.
[NeMo I 2021-09-02 16:51:51 audio_to_text_dataset:36] Model level config does not container `labels`, please explicitly provide `labels` to the dataloaders.
[NeMo I 2021-09-02 16:51:51 collections:173] Dataset loaded with 948 files totalling 0.71 hours
[NeMo I 2021-09-02 16:51:51 collections:174] 0 files were filtered totalling 0.00 hours
[NeMo I 2021-09-02 16:51:51 audio_to_text_dataset:36] Model level config does not container `sample_rate`, please explicitly provide `sample_rate` to the dataloaders.
[NeMo I 2021-09-02 16:51:51 audio_to_text_dataset:36] Model level config does not container `labels`, please explicitly provide `labels` to the dataloaders.
[NeMo I 2021-09-02 16:51:51 collections:173] Dataset loaded with 130 files totalling 0.10 hours
[NeMo I 2021-09-02 16:51:51 collections:174] 0 files were filtered totalling 0.00 hours
[NeMo I 2021-09-02 16:51:51 features:252] PADDING: 16
[NeMo I 2021-09-02 16:51:51 features:269] STFT using torch
[NeMo I 2021-09-02 16:51:51 modelPT:751] Optimizer config = Novograd (
    Parameter Group 0
        amsgrad: False
        betas: [0.8, 0.5]
        eps: 1e-08
        grad_averaging: False
        lr: 0.01
        weight_decay: 0.001
    )
Traceback (most recent call last):
  File "/home/ubuntu/repos/algo/app/aliSrc/src/speech2text.py", line 94, in <module>
    main()
  File "/home/ubuntu/repos/algo/app/aliSrc/src/speech2text.py", line 89, in main
    trainer.fit(asr_model)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 715, in _run
    self.accelerator.setup(self, model)  # note: this sets up self.lightning_module
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu.py", line39, in setup
    return super().setup(trainer, model)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in setup
    self.setup_optimizers(trainer)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 374, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.training_type_plugin.init_optimizers(
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 190, in init_optimizers
    return trainer.init_optimizers(model)
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/pytorch_lightning/trainer/optimizers.py", line 34, in init_optimizers
    optim_conf = model.configure_optimizers()
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 765, in configure_optimizers
    self.setup_optimization()
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/core/classes/modelPT.py", line 756, in setup_optimization
    self._scheduler = prepare_lr_scheduler(
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/core/optim/lr_scheduler.py", line 593, in prepare_lr_scheduler
    max_steps = compute_max_steps(
  File "/home/ubuntu/repos/algo/app/aliSrc/aliEnv/lib/python3.8/site-packages/nemo/core/optim/lr_scheduler.py", line 650, in compute_max_steps
    sampler_num_samples = math.ceil(num_samples / num_workers)
ZeroDivisionError: division by zero`

**Comment by titu1994** [comment]
Increase num_workers in train_ds to > 0. It would be too slow to train otherwise. We will fix that division by zero error though.

**Comment by titu1994** [comment]
Fixed via https://github.com/NVIDIA/NeMo/pull/2802
