### ISSUE TITLE
Error: module 'nemo.collections.nlp.data' has no attribute 'BERTPretrainingDataDesc'

### ISSUE THREAD

**Issue by Bipasha-banerjee** [NVIDIA/NeMo#2766]
I have raw text that I want to preprocess for Pretraining BERT. I followed all the steps mentioned in https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/zh/latest/nlp/bert_pretraining.html . I got stuck while creating the tokenizer where I get an error saying that there is no attribute named BERTPretrainingDataDesc. Any suggestion is appreciated. 

OS version: Ubuntu, 20.04.2 LTS
Python version: 3.6.13
PyTorch version: 1.9.0

**Comment by VahidooX** [comment]
This is the documentation of old NeMo. Please check the latest documentation here: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/bert_pretraining.html#quick-start-guide

**Comment by Bipasha-banerjee** [comment]
Thanks! I will check the link out.
