### ISSUE TITLE
AttributeError: type object 'EncDecCTCModel' has no attribute 'from_pretrained'

### ISSUE THREAD

**Issue by zhan0502** [NVIDIA/NeMo#2779]
Hi, I installed the nemo 1.3.0 latest version recently and find there is an attribute error as shown below. Although I have reinstall my environment for a few times, it still have this error. Has anyone encounter this recently with NeMo 1.3.0? 
=================================================================================
my code: 
char_model =  nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="stt_zh_citrinet_1024_gamma_0_25")

error:
AttributeError: type object 'EncDecCTCModel' has no attribute 'from_pretrained'
=================================================================================

Thanks!

**Comment by titu1994** [comment]
That checkpoint hasn't been made available yet, can you try with another checkpoint ?

**Comment by zhan0502** [comment]
Thanks, I see, how may I install back the earlier version like NeMo 1.2.0? I tried a couple of times, even if I install locally, there is still this error. 

It seems the below installation would work if we use the correct BRANCH name, do you know which BRANCH should I use if install back the NeMo 1.2.0 version? Thanks. 

Pip from source

apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
python -m pip install git+https://github.com/NVIDIA/NeMo.git@{BRANCH}#egg=nemo_toolkit[all]

**Comment by titu1994** [comment]
Pip install nemo_toolkit[all]==1.2.0 should work

**Comment by titu1994** [comment]
But the checkpoint doesn't exist on any previous Nemo version. It's going to be added to 1.4 or you can use main branch and use it right now

**Comment by zhan0502** [comment]
hmm.. even if I download the pretrained model and do restore_from, it would also not work right?
if that is the case, I'll change to another pretrained model. Thanks.

**Comment by titu1994** [comment]
Download and restore would work

**Comment by zhan0502** [comment]
Thanks, hmm... but when I try using restore from, there is a following error:

using 
model = nemo_asr.models.EncDecCTCModelBPE.restore_from("stt_zh_citrinet_1024_gamma_0_25.nemo") or 
model = nemo_asr.models.ASRModel.restore_from("stt_zh_citrinet_1024_gamma_0_25.nemo")

===============================================================================
error: (ps. I have tried on other versions of NeMo,  also got some errors related to tokenizer..) 

[NeMo I 2021-09-13 09:57:39 features:256] STFT using torch
[NeMo I 2021-09-13 09:57:50 modelPT:376] Model EncDecCTCModelBPE was successfully restored from stt_zh_citrinet_1024_gamma_0_25.nemo.
Traceback (most recent call last):
  File "train_cn_ci.py", line 63, in <module>
    model.change_vocabulary(new_tokenizer_dir=TOKENIZER_DIR, new_tokenizer_type="bpe")
TypeError: change_vocabulary() got an unexpected keyword argument 'new_tokenizer_dir'

**Comment by titu1994** [comment]
Ok that's a bug. These are supposed to be character based models, not Subword based models. I'll send a bugfix in some time.

**Comment by titu1994** [comment]
This is a character based model so use EncDecCTCModel (no BPE at the end), and it doesnt use a tokenizer, it uses character encoding so its arguments for change_vocabulary(labels=list of strings)

**Comment by zhan0502** [comment]
I see, thanks. So for citrine model training for Chinese, is it no need to prepare tokenizers as mentioned in tutorial https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/ASR_CTC_Language_Finetuning.ipynb? 

Thank you.

**Comment by titu1994** [comment]
Yes it has its labels built into it. If you wish to change it then you'll have to provide another list of tokens
