### ISSUE TITLE
Tune frame length while training Tacotron?

### ISSUE THREAD

**Issue by Choiuijin1125** [NVIDIA/NeMo#2782]
Thank you for building a great open source project.

I'm trying to train Tarcotron using Korean datasets.

While training I just noticed that depending on `max_duration`, frame padding length will be changed, below images show `val_target` Mel spectrogram where `max_duration` is over 3.5sec and below 3.5sec. 

![image](https://user-images.githubusercontent.com/32811094/132269756-fceb2fc5-fab8-4b18-9a82-b8f22e8f8a82.png)

and I think it makes `valid_prediction` unstable. like the below images, Tacotron generates some noise at the end of a frame.

![image](https://user-images.githubusercontent.com/32811094/132270032-5b52f505-9cb9-4cdc-bc53-9cda5e29a83c.png)

Is there any way to tune this problem? or is it normal behavior for Tacotron?

**Comment by Choiuijin1125** [comment]
I also suspect this issue because of my datasets. I'm not using script data but lecture data(lecture audio --> Quartnet --> split audio by punctuation --> remove noise audios --> tts)
Even though I'm using a bit low-quality datasets. it works very well except the end of a frame. the model can't coverage the end of the sentence and synthesize noise.

**Comment by Choiuijin1125** [comment]
> I also suspect this issue because of my datasets. I'm not using script data but lecture data(lecture audio --> Quartnet --> split audio by punctuation --> remove noise audios --> tts)
> Even though I'm using a bit low-quality datasets. it works very well except the end of a frame. the model can't coverage the end of the sentence and synthesize noise.

**Comment by Choiuijin1125** [comment]
I just found that in training every sample is padded to the length of the largest mel.
https://github.com/NVIDIA/tacotron2/issues/356.

Then how can I tune to fix the end of the frame like the below image?
![image](https://user-images.githubusercontent.com/32811094/132290482-c1db4167-5b02-4f8f-b825-b03469921f72.png)

**Comment by p0p4k** [comment]
@Choiuijin1125 I have a korean dataset too, can you guide me how to train from scratch? Thanks!
