### ISSUE TITLE
Machine Translation SacreBLEU is different when running `trainer.test()` vs directly calling `corpus_bleu()`

### ISSUE THREAD

**Issue by Vlados09** [NVIDIA/NeMo#2784]
**Describe the bug**

The SacreBLEU score in [mt_enc_dec_model](https://github.com/NVIDIA/NeMo/blob/r1.3.0/nemo/collections/nlp/models/machine_translation/mt_enc_dec_model.py) is computed using detokenized target text:
```
286:        ground_truths = [self.decoder_tokenizer.ids_to_text(tgt) for tgt in np_tgt]
287:        ground_truths = [self.target_processor.detokenize(tgt.split(' ')) for tgt in ground_truths]
```
which is the likely reason for the difference in the BLEU score I get when computing directly using the `corpus_bleu` method from sacreblue. 

As an example, on the newstest2014 en -> de dataset, using `trainer.test()` I get `30.14` and running `model.translate()` followed by `corpus_bleu()` results in `30.42`. The difference is even larger on my own dataset (1-2 units).

Ideally, the BLEU score should be computed directly on the raw target text so it is easy to reproduce the metric externally. 

A potential solution could be to add raw_tgt as an additional output of the TranlationDataset.

**Expected behavior**

SacreBLEU score should be identical when computed within the model and externally.

**Environment overview (please complete the following information)**

 - Environment Location: Docker on Kubernetes
 - Method of NeMo install: using helm chart using `nvcr.io/nvidia/nemo:1.2.0`

**Comment by okuchaiev** [comment]
The best way to compute final BLEU score is running inference (using example script) and then using sacreblue from CLI to compare results with test.
