### ISSUE TITLE
Jasper model trainer checkpoints

### ISSUE THREAD

**Issue by YossiVoca** [NVIDIA/NeMo#279]
Hi, could you add the trainer checkpoints in jasper multidataset jasper10x5dr ?
(https://ngc.nvidia.com/catalog/models/nvidia:multidataset_jasper10x5dr/files)
Thanks

**Comment by blisc** [comment]
@YossiVoca, I'm curious how does the trainer checkpoints fit into your use case?

**Comment by okuchaiev** [comment]
please see https://ngc.nvidia.com/catalog/models/nvidia:nemospeechmodels
