### ISSUE TITLE
Exporting feature extractor (Preprocessor) as a .onnx model. 

### ISSUE THREAD

**Issue by Shashika007** [NVIDIA/NeMo#2790]
**Is your feature request related to a problem? Please describe.**

I have follow your [example](https://github.com/NVIDIA/NeMo/blob/v1.0.0b3/scripts/convasr_to_onnx.py) to convert a single asr model (.nemo) into encoder and decoder. But, it does not allow to export the Preprocessor model as .onnx. When i checked the functions that attached to Preprocessor, the .export() function is not implemented. Is there a reason why don't you allow to export the Preprocessor part out from asr model?   
  
**Describe the solution you'd like**

I would like to find out how to export the Preprocessor to .onnx format trough a .export() function as you already implemented for encoder and decoder as follows (Referred from [example](https://github.com/NVIDIA/NeMo/blob/v1.0.0b3/scripts/convasr_to_onnx.py)).

![Screenshot from 2021-09-08 09-07-43](https://user-images.githubusercontent.com/15320876/132434732-ac1de0ed-d1d4-432a-a8b0-7ed048676199.png)
         
**Describe alternatives you've considered**

There's a way to split the asr model (.nemo) to sub modules using [.extract_state_dict_from()](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/v1.0.0b4/api-docs/nemo.html#nemo.core.ModelPT.extract_state_dict_from)  and it saves as a ckpt. Is there a way to convert the preprocessor.ckpt that can load as a triton model ? 

![Screenshot from 2021-09-08 09-24-52](https://user-images.githubusercontent.com/15320876/132436238-37b29291-421a-451d-bf4c-db6d27b2810b.png)

![Screenshot from 2021-09-08 09-24-15](https://user-images.githubusercontent.com/15320876/132436195-591dad94-94d8-440a-9ca0-ee5bd7fa15e4.png)

**Comment by titu1994** [comment]
I don't have Triton experience, but the preprocessor can't be exported easily because there's a lot of code supporting the actual conv - which is probably not going to be compatible with onnx.  You could try it with the extract stars dict method - after all the actual preprocessor is conv but you might need to see if it actually works exactly as Nemo when passed same inputs.
