### ISSUE TITLE
Cannot reproduce environment 

### ISSUE THREAD

**Issue by azayz** [NVIDIA/NeMo#2794]
I can't reproduce the environment to run the code in this tutorial https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/zh/latest/nlp/bert_pretraining.html , I have followed pip installation instructions but I keep getting errors when I import things 

AttributeError: module 'nemo.collections.nlp.data' has no attribute 'NemoBertTokenizer'
>>> ckpt_callback = nemo.core.CheckpointCallback(folder=nf.checkpoint_dir,
...                     load_from_folder=args.load_dir)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'nemo' is not defined
>>> import nemo
>>> ckpt_callback = nemo.core.CheckpointCallback(folder=nf.checkpoint_dir,
...                     load_from_folder=args.load_dir)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nemo.core' has no attribute 'CheckpointCallback'

**Comment by titu1994** [comment]
That documentation is very old.  This is the correct documentation - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/intro.html
