### ISSUE TITLE
Take the exact tense of each word

### ISSUE THREAD

**Issue by DiegoJota** [NVIDIA/NeMo#2805]
Hi
I need to take the exact time each word was said to build a transcription "timeline".
I saw that this script exemplifies how to accomplish this task
https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/Offline_ASR.ipynb#scrollTo=a-LSg9dSL_O1

However, as it was done, I only have the information about the final time of each word and the initial time is determined by the final time of the previous word.
This way I'm not getting good results, because if there is a silence interval between one word and another, the "timeline" will inform you that the next word has already started to be spoken.
Is there an alternative to recover the exact time of each word?

**Comment by titu1994** [comment]
We don't support it. You can refer to various past issues where people mentioned parlance. Please search for past issues such as https://github.com/NVIDIA/NeMo/issues/1444
