### ISSUE TITLE
[bug] Cannot resolve schedulerDictConfig Error in ASR_with_NeMo.ipynb

### ISSUE THREAD

**Issue by Priyanshiguptaaa** [NVIDIA/NeMo#2807]
I was trying to train the ASR Model using Nemo on Colab but I was facing this issue on this row

trainer.fit(first_asr_model)

ValueError: Cannot resolve schedulerDictConfig'. Available optimizers are : dict_keys(['WarmupPolicy', 'WarmupHoldPolicy', 'SquareAnnealing', 'CosineAnnealing', 'NoamAnnealing', 'WarmupAnnealing', 'InverseSquareRootAnnealing', 'SquareRootAnnealing', 'PolynomialDecayAnnealing', 'PolynomialHoldDecayAnnealing', 'StepLR', 'ExponentialLR', 'ReduceLROnPlateau', 'CyclicLR'])

**Comment by titu1994** [comment]
Is this from one of the tutorials? Or some personal notebook? schedulerDictConfig is an odd name which we dont use anywhere

**Comment by titu1994** [comment]
Could you also print the omegaconf version?

**Comment by Priyanshiguptaaa** [comment]
Yes, I'll share the link for the Colab notebook:
https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0rc1/tutorials/asr/01_ASR_with_NeMo.ipynb?authuser=2#scrollTo=0S5iZPMSlRzg

**Comment by Priyanshiguptaaa** [comment]
The Version: 2.1.1

**Comment by Priyanshiguptaaa** [comment]
I guess the error is SchdulerDictconfig because it is taking the name DictConfig as the scheduler instead of CosineAnnealing

**Comment by titu1994** [comment]
The colab notebook works out of the box, I'd suggest restarting colab with a fresh tutorial and try again.

**Comment by Priyanshiguptaaa** [comment]
Okay, Thanks!
I used the same Colab notebook from the official website and it worked!
https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/ASR_with_NeMo.ipynb
