### ISSUE TITLE
How to integrate a transformer-LM with the asr  model

### ISSUE THREAD

**Issue by abdul756** [NVIDIA/NeMo#2808]
What code should i change to integrate a transformer LM with the decoder of ASR model. Please help

**Comment by VahidooX** [comment]
You may use a Transformer LM as a rescorer, explained here: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html

But if you are looking for how to do the fusion of the decoder with Transformer, currently we do not support that. However N-gram LM fusion which we support works generally very good and it is so much faster.
