### ISSUE TITLE
nmt_webapp cant start?

### ISSUE THREAD

**Issue by jaffe-fly** [NVIDIA/NeMo#2848]
**Describe the bug**
python nmt_service.py  occcur that

![image](https://user-images.githubusercontent.com/49515380/133885574-5b293afd-6883-468b-aa74-bdf9adcbf648.png)

config.json

en-zh:"NGC/nmt_en_zh_transformer6x6"
zh-en:"NGC/nmt_zh_en_transformer6x6"

**Comment by MaximumEntropy** [comment]
Hey! This looks like your OS is killing the process - maybe because you are running out of cpu memory?

**Comment by jaffe-fly** [comment]
> Hey! This looks like your OS is killing the process - maybe because you are running out of cpu memory?

i am sure not this reason

**Comment by jaffe-fly** [comment]
> Hey! This looks like your OS is killing the process - maybe because you are running out of cpu memory?

thank you ,you are right!!!

- @MaximumEntropy 

>
