### ISSUE TITLE
Quartznet Parameter Count Issue

### ISSUE THREAD

**Issue by raghavbali** [NVIDIA/NeMo#288]
Congratulations on amazing work and results. Quartznet is a huge leap forward from JASPER.

I have a couple of questions regarding the model architecture:

1. As per the paper, the 15X5 variant has 18.9 M parameters to achieve state of the art results.
While replicating the paper in Keras/Tensorflow we observed that the total number of parameters is not matching.

---

Paper : 18.9 M
Our Implementation : 33 M 

---

2. Another point of confusion is around the C1 layer. The paper mentions normal 1-D Convolution but the [pytorch implementation/yml](https://github.com/NVIDIA/NeMo/blob/master/examples/asr/configs/quartznet15x5.yaml) utilizes Time Separable Convolutions.

Any inputs would be really appreciated.

**Comment by raghavbali** [comment]
Found issue in my understanding/implementation. 
The numbers add up as per the details in the paper. Thanks

**Comment by elaith9** [comment]
@raghavbali would you be willing to share your Keras implementation?

**Comment by raghavbali** [comment]
@elaith9 Apologies but it would not be possible at the moment.
