### ISSUE TITLE
MTEncDecModel has no attribute device

### ISSUE THREAD

**Issue by lidh15** [NVIDIA/NeMo#2971]
**Describe the bug**

I called
MTEncDecModel.restore_from('zh_en_24x6.nemo').cuda('cuda:0')
if I assign the parameter to .cuda() as above, it will raise an error 
'no attribute device'

**Steps/Code to reproduce bug**

as above

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

as above

**Environment overview (please complete the following information)**

as instructed in the readme, pip install nemo_toolkit['all'], python 3.8 nemo 1.4 pytorch 1.9

**Environment details**

as above

**Additional context**

probably not

**Comment by MaximumEntropy** [comment]
Hey, I can't seem to reproduce this locally. So model = MTEncDecModel.restore_from('zh_en_24x6.nemo') works, but then doing something like model = model.cuda() afterwords fails?

**Comment by lidh15** [comment]
> Hey, I can't seem to reproduce this locally. So model = MTEncDecModel.restore_from('zh_en_24x6.nemo') works, but then doing something like model = model.cuda() after fails?

model = MTEncDecModel.restore_from('zh_en_24x6.nemo').cuda('cuda:0') works, but then doing model.translate(string) fails

**Comment by MaximumEntropy** [comment]
I see, yes I can reproduce that now. I can get it to work by doing either `.cuda()` or `model = model.to(cuda:0)`. I'll try and see what's happening with `.cuda(cuda:0)`

**Comment by lidh15** [comment]
OK, now I know we should initialize the model and then do "model = model.to(cuda:0)" rather than write them in one line.
