### ISSUE TITLE
nemo v1.4.0  : AttributeError: type object 'EncDecRNNTModel' has no attribute 'from_pretrained'

### ISSUE THREAD

**Issue by LeonKennedy** [NVIDIA/NeMo#2978]
**Describe the bug**

AttributeError: type object 'EncDecRNNTModel' has no attribute 'from_pretrained'

code:
import nemo.collections.asr as nemo_asr
conformer_rnnt = nemo_asr.models.EncDecRNNTModel.from_pretrained()

console:
'''
Traceback (most recent call last):
  File "exp1.py", line 19, in <module>
    conformer_rnnt = nemo_asr.models.EncDecRNNTModel.from_pretrained()
AttributeError: type object 'EncDecRNNTModel' has no attribute 'from_pretrained'
'''

**Environment details**
macOS Catalina 10.15.7
python version 3.8.10

**Additional context**

no GPU

**Comment by LeonKennedy** [comment]
nemo_toolkit[all] is no match, but without [all] can work 
log:

(nemo) ➜  python -m pip --version
pip 21.2.4 from /Users/coffee/anaconda3/envs/nemo/lib/python3.8/site-packages/pip (python 3.8)
(nemo) ➜  pip install nemo_toolkit[all]
zsh: no matches found: nemo_toolkit[all]
(nemo) ➜  pip install nemo_toolkit
Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: nemo_toolkit in /Users/coffee/anaconda3/envs/nemo/lib/python3.8/site-packages (1.4.0)
Requirement already satisfied: python-dateutil in /Users/coffee/anaconda3/envs/nemo/lib/python3.8/site-packages (from nemo_toolkit) (2.8.2)
Requirement already satisfied: unidecode in /Users/coffee/anaconda3/envs/nemo/lib/python3.8/site-packages (from nemo_toolkit) (1.3.2)
Requirement already satisfied: onnx>=1.7.0 in /Users/coffee/anaconda3/envs/nemo/lib/python3.8/site-packages (from nemo_toolkit) (1.10.1)
Requirement already satisfied: ruamel.yaml in /Users/coffee/anaconda3/envs/nemo/lib/python3.8/site-packages (from nemo_toolkit) (0.17.16)
Requirement already satisfied: wrapt in /Users/coffee/anaconda3/envs/nemo/lib/python3.8/site-packages (from nemo_toolkit) (1.13.1)
....

**Comment by titu1994** [comment]
B1 version was not compatible with Colab. You can try the r1.5.0 branch now, should be compatible with current Colab environment. Torch audio is currently unstable though so it might take a few more days for colab to work properly.

**Comment by BuaaAlban** [comment]
> B1 version was not compatible with Colab. You can try the r1.5.0 branch now, should be compatible with current Colab environment. Torch audio is currently unstable though so it might take a few more days for colab to work properly.

I installed it  from source using the main branch or by  pip install nemo_toolkit[all].
Both didn't work, all ASR model Classes (EncDecCTCModelBPE, EncDecRNNTBPEModel;EncDecCTCModel etc。) has no  attribute 'from_pretrained'
Any suggestions?

**Comment by titu1994** [comment]
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation

We're all the installation instructions followed ? It required Cython along with a few other libraries

**Comment by BuaaAlban** [comment]
> https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation
> 
> We're all the installation instructions followed ? It required Cython along with a few other libraries

I didn't do this 
apt-get update && apt-get install -y libsndfile1 ffmpeg
I will try it

**Comment by BuaaAlban** [comment]
> https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation
> 
> We're all the installation instructions followed ? It required Cython along with a few other libraries

Meet this log during installation, will this effect on the "AttributeError: type object 'EncDecCTCModelBPE' has no attribute 'from_pretrained'" ? 

Installing additional nemo_text_processing conda dependency
nemo_text_processing could not be installed!

**Comment by titu1994** [comment]
That's fine, ASR doesn't depend on Text normalization (it can be installed only on a conda env)

**Comment by titu1994** [comment]
Then I don't really know. I can't replicate this issue on a conda env, and we released Nemo 1.5.0 today with latest pytorch support.

**Comment by BuaaAlban** [comment]
> Then I don't really know. I can't replicate this issue on a conda env, and we released Nemo 1.5.0 today with latest pytorch support.

Could you provide your install details?  like the detailed install command and python version.
I used 
conda create -n nemo    #which  result in python==3.7.3
apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
pip install nemo_toolkit[all]


Thanks a lot, I will use your command to retry the whole process

**Comment by titu1994** [comment]
Python 3.8. I just follow the instructions in the link. No reinstall.sh.

**Comment by architlfc** [comment]
I'm running into the same issue .
Python :3.8.12
Running inside docker image :pytorch:21.11-py3

Code: :
 asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name='QuartzNet15x5Base-En', strict=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'EncDecCTCModel' has no attribute 'from_pretrained'

Installed steps :
apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
python -m pip install git+https://github.com/NVIDIA/NeMo.git@r1.5.0

**Comment by titu1994** [comment]
Please use pip install nemo_toolkit["all"] or look at the notebooks for exact command to install all the parts of Nemo - your current install instruction just installs the core and nothing else

**Comment by naor2013** [comment]
I found a fix for this. Just installing nemo_toolkit[all] didn't fix this.
I had some libraries that were installed incorrectly, pip thought they are there but importing them didn't work.
The biggest issue is that nemo tries to import libraries and if it doesn't succeed, it completely ignores it, no error, no warning.
You can find the imports that you should try in the __init__.py files in all the folders in the tree of folders that lead to your model and try them to see what errors you get (for me, it was pyyaml, simplejson and pexpect) and just use "pip install -U <library>".

For nemo, those failed imports should probably raise at least a warning so users will know what libraries they are missing.  @titu1994
