### ISSUE TITLE
Not able to covert stt_en_contextnet_1024.nemo into riva format

### ISSUE THREAD

**Issue by aitalk** [NVIDIA/NeMo#2979]
**Describe the bug**

**Steps/Code to reproduce bug**
nemo2riva --out /servicemaker-dev/stt_en_contextnet_1024.riva /servicemaker-dev/stt_en_contextnet_1024.nemo
nemo-toolkit                     1.4.0
nemo2riva                        1.6.0b0

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by aitalk** [comment]
tchModel
Loaded schema file /opt/conda/lib/python3.8/site-packages/nemo2riva/validation_schemas/tts-exported-hifiganmodel.yaml for nemo.collections.tts.models.HifiGanModel
W1009 20:08:48.735618 139622390986560 schema.py:134] Validation schema not found for nemo.collections.asr.models.EncDecRNNTBPEModel.
That means Riva does not yet support a pipeline for this network and likely will not work with it.
I1009 20:08:56.384190 139622390986560 artifacts.py:77] Retrieved artifacts: dict_keys(['381667021bf541b3ba51f4ffcdb351d5_tokenizer.vocab', '6b363832122c4c6f9ad547f524f28dd0_tokenizer.model', '87654c2ac2344772892de94eefc9f84a_vocab.txt', 'model_config.yaml'])
I1009 20:08:56.409415 139622390986560 convert.py:77] nemo2riva.convert: converting /servicemaker-dev/stt_en_contextnet_1024.nemo to  /servicemaker-dev/stt_en_contextnet_1024.riva using ONNX export format
I1009 20:08:56.411128 139622390986560 cookbook.py:81] Exporting model with autocast=False
[NeMo W 2021-10-09 20:08:56 export_utils:198] Swapped 0 modules
[NeMo W 2021-10-09 20:08:56 conv_asr:73] Turned off 0 masked convolutions
I1009 20:10:43.682684 139622390986560 asr_model.py:360] Replacing output state name states with ['output-states-1', 'output-states-2']
W1009 20:10:44.193920 139622390986560 asr_model.py:399] PyTorch Model has been significantly modified. In order to utilize model, delete this instance and create a new model.
Traceback (most recent call last):
  File "/opt/conda/bin/nemo2riva", line 8, in <module>
    sys.exit(nemo2riva())
  File "/opt/conda/lib/python3.8/site-packages/nemo2riva/cli/nemo2riva.py", line 50, in nemo2riva
    Nemo2Riva(args)
  File "/opt/conda/lib/python3.8/site-packages/nemo2riva/convert.py", line 84, in Nemo2Riva
    cb.save(obj=model, save_path=riva_out, cfg=cfg)
  File "/opt/conda/lib/python3.8/site-packages/nemo2riva/cookbook.py", line 111, in save
    f.write(content)
  File "/opt/conda/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "<frozen eff.core.archive>", line 327, in create
  File "<frozen eff.core.archive>", line 263, in save_to
  File "<frozen eff.core.codec>", line 34, in crc32_file
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwg0_r21l/model_graph.onnx'

**Comment by titu1994** [comment]
No transducer model is supported in Riva at the moment.

**Comment by aitalk** [comment]
Ok, thanks. Any idea when it will be supported? I find contextNet models with better accuracy than others so wanted to replace our current production setup with new contextnet models.

**Comment by titu1994** [comment]
It will take time due to the major difference between CTC and RNNT models + decoding steps
