### ISSUE TITLE
Using .nemo model for prediction

### ISSUE THREAD

**Issue by SonuKumari1690** [NVIDIA/NeMo#2982]
Hi Team,
Can you please guide me how can I use .nemo model produced after training on our data set so it is not completely using pretrained model, it is into transfer learning and now i want to use it for predicting on new dataset, the way other models work using .predict method

Your response is highly awaited

**Comment by VahidooX** [comment]
Which model exactly are you using?

**Comment by SonuKumari1690** [comment]
Hi Team,
I am still waiting for the probability response of values predicted.
Your response is highly appreciated
