### ISSUE TITLE
 Music recognition

### ISSUE THREAD

**Issue by DiegoJota** [NVIDIA/NeMo#2986]
Hi,

Is it efficient to set up a dataset to recognize songs? I notice that when there is a song in an audio it tries to somehow transcribe, if I train these songs saying "music" in the manefesto would it be efficient? Or are there alternatives that can help me in this scenario?

**Comment by titu1994** [comment]
You would normally use a VAD model to classify speech or non speech (subcategories of noise or music say) and if there's speech run an ASR model otherwise simply predict the label of the VAD model c
