### ISSUE TITLE
no module named 'nemo'

### ISSUE THREAD

**Issue by emilylimxq** [NVIDIA/NeMo#3029]
**Describe the bug**

Yesterday I ran the ipynb and it could work. But today, I'm not sure why it just couldn't work

**Steps/Code to reproduce bug**

I literally just ran the same codes from here https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/Question_Answering_Squad.ipynb#scrollTo=dzqD2WDFOIN-

it gave me this and during the installing, this happened, but It did not happen yesterday

![image](https://user-images.githubusercontent.com/56108692/138214509-f75d9c29-79c4-4adc-a3f8-b0d15561b152.png)

![image](https://user-images.githubusercontent.com/56108692/138214298-1fa4a1bd-dad7-42d4-afc9-c8be98a85e43.png)

**Expected behavior**

I expected the whole ipynb to run successfully which happened yesterday.

**Environment overview (please complete the following information)**

 - Environment location: [google Collab]
 - Method of NeMo install: [install from source given]. the exact command !python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[nlp]

Example: GPU model

**Comment by MelikaBahmanabadi** [comment]
> ```
> apt-get update && apt-get install -y libsndfile1 ffmpeg
> pip install Cython
> pip install nemo_toolkit['all']
> ```
> 
> This works for me.

I test it but it can not install torch and stop with this error: `ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.`
what is the solution?

**Comment by titu1994** [comment]
Install torch before Nemo based on instructions on their website
