### ISSUE TITLE
VAD Data Set

### ISSUE THREAD

**Issue by CaioRochaGoes** [NVIDIA/NeMo#3053]
Hey guys

I've been tinkering with the "Voice_Activity_Detection.ipynb" script, and I've had some questions about mounting the data set.

The first, is it really necessary to use human voices speaking a specific word?
And would I have to keep feeding this base by adding new voices speaking other words?

Would I get a good result just doing this training with noise audios?

**Comment by fayejf** [comment]
@CaioRochaGoes  Thanks for your question. 

> The first, is it really necessary to use human voices speaking a specific word?
> And would I have to keep feeding this base by adding new voices speaking other words?

No. You can use any speech dataset for speech data. The speech command here is just for simplification and we [show](https://arxiv.org/abs/2010.13886) that even trained on a relativly simple dataset, the model can still have good generalization ability on out of domain evaluation data. 

You can use the speech part of _AVA speech, voxconverse, AMI, ICSI, CH120, Fisher, SWBD, google speech commands, musan, etc._, as your speech trainning data. We will be releasing a new checkpoint trained on more data and augmentation which would give better performance soon.  

> Would I get a good result just doing this training with noise audios?

Could you elaborate this?

**Comment by CaioRochaGoes** [comment]
Hi, thanks for the reply.

I will be seeing in the next few days the bases that you indicated to me, I will also see the new checkpoint

Thank you for the indications

> Could you elaborate this?

My question was whether I would get good results in a VAD workout, using only noise audios. No need to use normal audio of people talking
