### ISSUE TITLE
pytorch-lightning version is specified wrong at requirements_lightning.txt 

### ISSUE THREAD

**Issue by darkydash** [NVIDIA/NeMo#3081]
requirements_lightning.txt requires pytorch-lightning version to be higher than 1.4.9 though it's the latest stable version and it's not possible. Probably meant pytorch-lightning>=1.4.9 instead
![image](https://user-images.githubusercontent.com/17128248/139324215-dc3a360c-de70-4471-89ec-96521222891b.png)
![image](https://user-images.githubusercontent.com/17128248/139324329-abaf315d-191c-43db-b33a-7c1b2dfed0d5.png)

**Comment by okuchaiev** [comment]
you saw this requirement in the main branch which is the branch we use for development. At that time we were relying on 1.5.0rc features hence this requirement.
We don't rely on rc libraries in releases though.
And PTL 1.5.0 is actually out now. Closing this.
