### ISSUE TITLE
Method in text_classification/text_classification_dataset.py cannot truncate long text to right length

### ISSUE THREAD

**Issue by bugface** [NVIDIA/NeMo#3094]
in text_classification/text_classification_dataset.py

```python
if max_seq_length > 0 and len(sent_subtokens) + 1 > max_seq_length:
    sent_subtokens = sent_subtokens[:max_seq_length]
    too_long_count += 1

sent_subtokens.append(tokenizer.sep_token)
sent_lengths.append(len(sent_subtokens))
```

The line 2 in the above code from /text_classification_dataset.py should be
```python
sent_subtokens = sent_subtokens[:max_seq_length-1]
```

otherwise, after append sep token, the total token length will be longer than max and cause the following error:
```
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [647,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```

**Comment by okuchaiev** [comment]
Thanks for catching this! (Do you want to send a PR with the fix? https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md )

**Comment by bugface** [comment]
> Thanks for catching this! (Do you want to send a PR with the fix? https://github.com/NVIDIA/NeMo/blob/main/CONTRIBUTING.md )

I am very glad to create a PR.
