### ISSUE TITLE
How to get the embedding after pretraining BERT?

### ISSUE THREAD

**Issue by Sammed98** [NVIDIA/NeMo#312]
I have successfully executed BERTPretrainingTutorial.ipynb. Now, given a word or phrase, how will I get the embedding vector? And how to export the model to a file for portability?

**Comment by ekmb** [comment]
To get embedding vectors for the evaluation dataset, you can run: 
`import numpy as np

def concatenate(lists):
    return np.concatenate([t.cpu() for t in lists])

embeddings = neural_factory.infer(tensors=[e_hidden_states])
embeddings = [concatenate(tensors) for tensors in embeddings]

# embeddings for tokens
embeddings[0]
# embeddings of the [CLS] token that can be used as a sentence embedding
embeddings[0][:,0]`

To save the model, please add checkpoint callback as defined here https://github.com/NVIDIA/NeMo/blob/master/examples/nlp/bert_pretraining.py#L286. For example:

`ckpt_callback = nemo.core.CheckpointCallback(
    folder='CHECKPOINT_DIR',
    epoch_freq=1)`

Then, add this callback to the list of callbacks in neural_factory.train(...).

**Comment by Sammed98** [comment]
Is there any provision to load the pretrained model after completing the training? I want to save the model after complete training and use it sometime/somewhere else?

**Comment by ekmb** [comment]
If your log_dir passed to the neural factory contains `checkpoints` folder, the model will be restored. 
You might find this example notebook useful https://github.com/NVIDIA/NeMo/blob/master/examples/nlp/text_classification/text_classification_with_bert.ipynb

**Comment by Sammed98** [comment]
1. By using checkpoints I got a "checkpoints" folder within an "outputs" folder containing the following files:
bert-config.json		 SequenceClassifier-STEP-200.pt
BERT-STEP-200.pt		 SequenceClassifier-STEP-400.pt
BERT-STEP-400.pt		 SequenceClassifier-STEP-425.pt
BERT-STEP-425.pt		 trainer-STEP-200.pt
BertTokenClassifier-STEP-200.pt  trainer-STEP-400.pt
BertTokenClassifier-STEP-400.pt  trainer-STEP-425.pt
BertTokenClassifier-STEP-425.pt

Which file has to be used to load the model? (In the given .ipynb they have used nf.infer to get the embeddings. To load into a new script from the folder has not been specified.)

2. I tried using bert_model (huggingface.BERT) to get the embeddings as follows:
`bert_model.forward(torch.tensor([qwerty]).cuda(), token_type_ids=None, attention_mask=None )`
where "qwerty" is a list of id's of the tokens. 
This gave an embedding value. What is the difference between what you gave [here](https://github.com/NVIDIA/NeMo/issues/312#issuecomment-580961805) and what my code returns?

**Comment by ekmb** [comment]
1. By default the latest checkpoints will be used, you don't have to manually specify file names. If you want to use the checkpoints, initialize the neural factory the following way:

`# Instantiate neural factory with supported backend
nf = nemo_core.NeuralModuleFactory(
    backend=nemo_core.Backend.PyTorch,
    local_rank=None,
    optimization_level=args.amp_opt_level,
    log_dir=PATH_TO_YOUR_LOG_DIR,
    create_tb_writer=True,
    add_time_to_log_dir=False,
)
 
For example, PATH_TO_YOUR_LOG_DIR='outputs'.

2. Both options will work, the one I gave might be easier if you have a large file of words you need embeddings for (for example, a file can contain a single word per line).

**Comment by pradeepsinghnitk** [comment]
how to load model from checkpoints?
