### ISSUE TITLE
Punctuation data set uses too much memory

### ISSUE THREAD

**Issue by 1-800-BAD-CODE** [NVIDIA/NeMo#3125]
**Describe the bug**

Punctuation datasets cannot be constructed with more than a few million examples (depending on the max length). Even these small datasets can consume a huge amount of memory while preprocessing (100's of GB) and while training (10's of GB per process). 

This issue was mentioned in passing in https://github.com/NVIDIA/NeMo/issues/2569 though it was not the main issue discussed there and thus not fixed.

Assuming it is an acceptable idea to load the entire dataset into memory in the first place, these are the points where there seems to be an excessive use of memory.

The function with issues (`get_features`):
https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/data/token_classification/punctuation_capitalization_dataset.py#L34 

The main issues:
1. Why save `all_segment_ids`? It appears there is nowhere this is set to anything but a constant 0. `__getitem__` can deal with it.
2. Why pad to the max length? `collate_fn` can deal with that, and could do so much more efficiently (by only padding to the max length of the batch).
3. Loss mask and input mask can be generated by `__getitem__` or `collate_fn`
4. Subtokens mask could be generated later as well, albeit not trivially.

**Expected behavior**

Should be able to use a dataset with 10's of millions of lines.

**Comment by PeganovAnton** [comment]
Hi @1-800-BAD-CODE ! Thank you for reporting the issue. Currently I am working on the problem and I hope it will soon be merged into `main` branch. There is a better implementation of `get_features` function in branch [feat/punctuation_data](https://github.com/NVIDIA/NeMo/tree/feat/puctuation_data). There you can regulate the amount of memory used via dataset parameter `num_jobs` and constant `nemo.collections.nlp.data.token_classification.punctuation_capitalization_dataset.MAX_NUM_QUERIES_IN_SPLIT`. In addition, model in `feat/punctuation_data` sorts sequences before batching to reduce padding. 

You can also use tarred dataset ([script for creating tarred dataset](https://github.com/NVIDIA/NeMo/blob/feat/puctuation_data/examples/nlp/token_classification/data/create_punctuation_capitalization_tarred_dataset.py), [tarred dataset class](https://github.com/NVIDIA/NeMo/blob/feat/puctuation_data/nemo/collections/nlp/data/token_classification/punctuation_capitalization_tarred_dataset.py), [config example](https://github.com/NVIDIA/NeMo/blob/feat/puctuation_data/examples/nlp/token_classification/conf/punctuation_capitalization_tarred_config.yaml)) If you encounter any problems with model in branch `feat/punctuation_data`, please don't hesitate ask questions here :)

**Comment by 1-800-BAD-CODE** [comment]
Thanks, much more useful now.

Some notes so far:
1. In `create_tarred_dataset` the use of path-like objects (`text_file`, `label_file`, `output_dir`) in the signature without type hints leads to surprising behavior. They look like strings in the interface, and that's what I assumed them to be initially.
2. In `create_tarred_dataset` more tokenizer options need to be exposed. For an SP model for punctuation we need at least `tokenizer_model`, `tokenizer_name`, and `special_tokens` to pass to `get_tokenizer`.
3. Need to check for OOV here: https://github.com/NVIDIA/NeMo/blob/feat/puctuation_data/nemo/collections/nlp/data/token_classification/punctuation_capitalization_dataset.py#L205 
    and add behavior analogous to https://github.com/NVIDIA/NeMo/blob/feat/puctuation_data/nemo/collections/nlp/data/token_classification/token_classification_dataset.py#L92
    e.g.
    ```
    if not word_ids and len(word.strip()):
        word_ids = [self.tokenizer.unk_id]
    ```
    else there will be strange errors later about lengths not being correct.

4. [still looking into this problem, maybe it can be avoided with a proper config] The data set assumes it can infer from the training data every label. This is no longer the case, since it is not guaranteed every label will be in every shard. It would be much more natural to specify the labels in the config, anyway.

**Comment by 1-800-BAD-CODE** [comment]
Some more notes: 

1. The following line deletes the final .tar file for each job. It looks like it should check if `progress_made == 0`, not `progress_made > 0`:
https://github.com/NVIDIA/NeMo/blob/feat/puctuation_data/nemo/collections/nlp/data/token_classification/punctuation_capitalization_tarred_dataset.py#L147
This will go unnoticed for some datasets, but if you have fewer batches than `max_batches_per_tarfile * num_jobs` then you will end up with no tar files at all.

2. Issue 4 noted above (inferring all labels from the first fragment) is in fact a problem. I work around it by creating my own .csv files where they will be anticipated and setting `save_label_ids=False` for all jobs when [process_fragment](https://github.com/NVIDIA/NeMo/blob/feat/puctuation_data/nemo/collections/nlp/data/token_classification/punctuation_capitalization_tarred_dataset.py#L142) instantiates datasets.

**Comment by PeganovAnton** [comment]
@1-800-BAD-CODE thank you a lot, your advice is really helpful. It seems that I fixed issues 1-3. For issue 4 I added more parameters to `argparse` and if still there is not label ids, the label ids are created in `create_tarred_dataset` before `process_fragment` call.

I should think a little more about last file removal because files with different number of batches affect training. I am not sure what happens if one data loader finishes epoch before others.

**Comment by 1-800-BAD-CODE** [comment]
I see now that dropping the remainder is intentional. My test parameters were not practical enough make it obvious why this should happen: we need a sufficiently-high `lines_per_dataset_fragment` to fulfill at least one complete `num_batches_per_tarfile`. Since this solution is for large datasets, it is expected that dropping some remainder is no big deal.

**Comment by PeganovAnton** [comment]
@1-800-BAD-CODE I repack tar files, which contain not enough batches, after processing finishes. No more than `--num_batches_per_tarfile` batches are being lost during tarred dataset creation.
