### ISSUE TITLE
LM compatibility

### ISSUE THREAD

**Issue by cri5Castro** [NVIDIA/NeMo#313]
hello there  I wanted to know if is possible to use the ASR DECODER with a custom lamnguage model maybe from hugginface or fairseq

**Comment by okuchaiev** [comment]
Please have a look at using KenLM inside BeamSearch decoder here: https://nvidia.github.io/NeMo/asr/tutorial.html#using-kenlm 

If you would like to use more advanced LM, the easiest way would be to modify BeamSearchDecoder to dump all candidates from the beam and then re-score them with an external language model.

Also, have a look here: https://nvidia.github.io/NeMo/nlp/asr-improvement.html  - this seems to be more flexible then just re-scoring beam candidates with an external LM

**Comment by kwasnydam** [comment]
Hey, I would like to dig on this question a little. If I would modify the BeamSearchDecoder to dump the candidates, would that mean that I could try to use that data and just run this https://github.com/NVIDIA/OpenSeq2Seq/tree/master/external_lm_rescore from the 4th step? 

Is there some ready code to do so in one of NVIDIAs repositories? There is this blog post which introduces NeMo https://devblogs.nvidia.com/develop-smaller-speech-recognition-models-with-nvidias-nemo-framework/ and mentions results obtained with Transformer-XL LM, I think it is quite strange that this functionality is not yet available out of the box.
