### ISSUE TITLE
Unable to run the notebook on Google Colab

### ISSUE THREAD

**Issue by hardikmodi** [NVIDIA/NeMo#3132]
**Describe the bug**

Cannot run the notebook 

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.
Try running this notebook: https://colab.research.google.com/drive/1-QmFrSHsnirtnu6gB0Tx-JQAXWDtm1yE?usp=sharing

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by okuchaiev** [comment]
1) Can't access your notebook (no permissions)
2) Please try using r1.5.0 on Colab (pytorch was upgraded to 1.10 there)
