### ISSUE TITLE
Streaming inference for Conformer Transducer ASR model

### ISSUE THREAD

**Issue by jzoker** [NVIDIA/NeMo#3144]
Hi. Im want to developing a streaming interface for my trainned Conformer Transducer ASR model. I have only see tutorials about  streaming for CTC model here:
https://github.com/NVIDIA/NeMo/blob/stable/tutorials/asr/Online_ASR_Microphone_Demo.ipynb
https://github.com/NVIDIA/NeMo/blob/stable/tutorials/asr/Streaming_ASR.ipynb
My question is can i apply this tutorial for Transducer model ? I do not know it is efficient or not to use this method to streaming with transducer model. If its not, can someone give me a direction ? Thank you (I already know about riva and tensorrt for production, but I just want developing the streaming method on python for now)

**Comment by titu1994** [comment]
We don't currently support streaming RNNT. We are looking into it but there's no specific timeline for it just yet.

**Comment by jzoker** [comment]
> We don't currently support streaming RNNT. We are looking into it but there's no specific timeline for it just yet.

Thanks you for your reply.  So do streaming Conformer CTC is supported yet ? I mean the support of both riva(exporting .nemo model to riva) and python.

**Comment by titu1994** [comment]
I don't know about Riva support for Conformer yet, but Nemo streaming notebooks will work with both Conformer and Citrinet

**Comment by jzoker** [comment]
Thanks you for your support!
