### ISSUE TITLE
Suitable PyTorch version for online Microphone ASR

### ISSUE THREAD

**Issue by MelikaBahmanabadi** [NVIDIA/NeMo#3145]
Hi,
What is the Suitable PyTorch version for using online Microphone ASR? I installed Nemo with the "r1.2.0" brach. My OS is Linux 20.04. I try all of the PyTorch versions but Nemo has conflict or does not recognize my Microphone.

**Comment by titu1994** [comment]
Pytorch version does nor affect the microphone visibility or not. Check if your microphone can be detected outside of the notebook

**Comment by MelikaBahmanabadi** [comment]
> Pytorch version does nor affect the microphone visibility or not. Check if your microphone can be detected outside of the notebook

I test it local with VS Code not with Colab in a notebook file. When I install Nemo from the main branch, non of the PyTorch versions are not compatible with Nemo.

**Comment by titu1994** [comment]
Could you try Pytorch 1.10, pytorch lightning 1.5.0 and Nemo main branch ?

**Comment by MelikaBahmanabadi** [comment]
> Could you try Pytorch 1.10, pytorch lightning 1.5.0 and Nemo main branch ?

Yes. I use below command from [PyTorch site](https://pytorch.org/)
`pip3 install torch==1.10.0+cpu torchvision==0.11.1+cpu torchaudio==0.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html`

**Comment by MelikaBahmanabadi** [comment]
I have a CPU on my laptop. Can I use Nemo with CPU? Because when I install Pytorch 1.10 with CPU only version and run online Microphone ASR it says the program needs Cuda.

**Comment by titu1994** [comment]
Yes you can use CPU, it will be slow though. Set trainer.gpus=0

**Comment by titu1994** [comment]
For the notebook it should automatically select whether to use cuda or not.

**Comment by MelikaBahmanabadi** [comment]
> For the notebook it should automatically select whether to use Cuda or not.

Hi, 
Thanks for your help but I have to run **Online Microphone ASR** on my local with an IDE like PyCharm or VSCode. My OS is Linux (Ubuntu20.04) with a CPU. I installed Nemo from the main branch and PyTorch 1.10 but I have the following error. It says Cuda is not available and can not recognize the microphone. I test my microphone with another application and it is correct.

> Available audio input devices:
4 Accutone UC Headset: USB Audio (hw:1,0)
6 pulse
7 default
Please type input device ID:
4
Listening...
[NeMo W 2021-11-08 09:23:21 nemo_logging:349] /home/sena/.local/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
      warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
    

> [NeMo W 2021-11-08 09:23:21 patch_utils:49] torch.stft() signature has been updated for PyTorch 1.7+
>     Please update PyTorch to remain compatible with later versions of NeMo.
> [NeMo W 2021-11-08 09:23:22 nemo_logging:349] /home/sena/.local/lib/python3.8/site-packages/nemo/collections/asr/parts/submodules/jasper.py:278: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
>       return (
>     
> [W NNPACK.cpp:79] Could not initialize NNPACK! Reason: Unsupported hardware.

**Comment by okuchaiev** [comment]
it is calling autocast. Can you please make sure that you aren't trying to use fp16 or bfloat16? (aren't supported on CPUs) and re-open if the issue persists
