### ISSUE TITLE
[QUESTION] How to use asr for online streaming with language model ?

### ISSUE THREAD

**Issue by dungnguyen98** [NVIDIA/NeMo#3158]
Hello,
Thank you for sharing great toolkit, tutorials and code.
I have a question: "How can I use asr for streaming with languge model ?"

**Comment by titu1994** [comment]
We currently do not support integrated beam search with streaming ASR in Nemo. You could try using NVIDIA RIVA instead for such support

**Comment by dungnguyen98** [comment]
Thank you for your support !
