### ISSUE TITLE
_torchtext.so: undefined symbol: _ZTVN5torch3jit6MethodE

### ISSUE THREAD

**Issue by Alexey322** [NVIDIA/NeMo#3176]
Сan't import nemo.collections.asr in google colab notebook https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/ASR_with_NeMo.ipynb. 
This worked on 11/11/2021, starting today (12/11/2021), the error appears:
ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZTVN5torch3jit6MethodE

**Comment by titu1994** [comment]
Could you check the torch version installed ? As well as versions of torchtext and torchaudio? If colab has updated to PT 1.10, you will need to use the r1.5.0 branch instead of main or stable

**Comment by Alexey322** [comment]
@titu1994 Thanks for your reply. 

By default, Colab now uses torch==1.10.0 + cu111, torchtext==0.11.0.
Indeed, BRANCH = 'r1.5.0' works without problems.
Could you tell me why this error occurs with BRANCH = 'r1.4.0'?

**Comment by okuchaiev** [comment]
please use r1.5.0 branch with pytorch 1.10.0. Closing

**Comment by porrasbrand** [comment]
How do I use the branch -- can someone please share the whole installation prompt example on how to do this  ? thanks

**Comment by hyunbin70** [comment]
> How do I use the branch -- can someone please share the whole installation prompt example on how to do this ? thanks

BRANCH = 'r1.5.0'
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[all]

*on google colab.

**Comment by grofattila** [comment]
> How do I use the branch -- can someone please share the whole installation prompt example on how to do this ? thanks

BRANCH = 'r1.5.0'
pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[nlp]

**Comment by osinkolu** [comment]
I guess this should be updated in the tutorials, save newbies a ton on google searching.

**Comment by titu1994** [comment]
This is present at the top of most Nemo notebooks already.

**Comment by osinkolu** [comment]
Great!

**Comment by sahoodib** [comment]
I am getting same issue even with BRANCH = 'r1.5.0'
error :- ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZTVN5torch3jit6MethodE

**Comment by osinkolu** [comment]
@sahoodib are you running the notebook directly on colab or your local PC, there were no issues during my run on colab.

**Comment by sahoodib** [comment]
@osinkolu I am running in Colab

**Comment by osinkolu** [comment]
@sahoodib it works fine on colab, uncomment  "exit" in the first cell of the code.

**Comment by sahoodib** [comment]
@osinkolu it worked fine when I connected with the GPU.

**Comment by osinkolu** [comment]
great!

**Comment by sahoodib** [comment]
Biomegatron is unsupported in Branch=1.5.0, if I degrade the branch I stick with the above error. Any ideas to resolve the issue.
