### ISSUE TITLE
Error when downloading the Persian data set of Mozilla Common Voice

### ISSUE THREAD

**Issue by ahkarami** [NVIDIA/NeMo#3182]
Hi,
Thanks for your great repo. I want to download the Mozilla Common Voice (MCV) **Persian** data set via the following code:
[get_commonvoice_data](https://github.com/NVIDIA/NeMo/blob/main/scripts/dataset_processing/get_commonvoice_data.py)
I have used below parameters:
`VERSION = "cv-corpus-7.0-2021-07-21"`
`LANGUAGE = "fa"`
but I got the following error:
```
  File "scripts/get_commonvoice_data.py", line 121, in process_files
    with open(csv_file) as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/fa/CV_unpacked/cv-corpus-7.0-2021-07-21/fa/train.tsv'
```
In addition, I have read the above from the below tutorial:
[ASR_CTC_Language_Finetuning](https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/ASR_CTC_Language_Finetuning.ipynb#scrollTo=VDDiXCiPimr_)  
would you please help me to address this problem?
Thanks

**Comment by ahkarami** [comment]
Thank you very much. It works. 
Best

**Comment by DevloperHS** [comment]
> We don't support MCV 7.0 yet as It does not provide an API endpoint to download datasets. You can switch to 6.1

When will you will provide reference

**Comment by titu1994** [comment]
We can't support it since it doesn't allow for people to download the dataset without logging in. Unless MCV provides a way to download it's data officially, 6.1 will be the the only supported version. If you know other libraries handling 7.0 or more, let us know.
