### ISSUE TITLE
NeMo cache model files in hard-coded location without using environment variables

### ISSUE THREAD

**Issue by TonyMas** [NVIDIA/NeMo#3185]
https://github.com/NVIDIA/NeMo/blob/e987e178ecb42f1e8411c59e80628cd67af03f79/nemo/core/classes/common.py#L722

NeMo store and load models from hard-coded folder (Path.home()/.cache/torch/NeMo/)

Is it possible to change it to a location dependent on some environment variable, similar to a way it is done for torch.hub (https://pytorch.org/docs/stable/hub.html#where-are-my-downloaded-models-saved) or transformers (https://huggingface.co/transformers/installation.html?highlight=transformers_cache#caching-models)?

**Comment by titu1994** [comment]
This is now supported on main branch
