### ISSUE TITLE
where is 'get_aishell_data.py'

### ISSUE THREAD

**Issue by yingying2017** [NVIDIA/NeMo#3187]
**Describe the bug**

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by yingying2017** [comment]
I want to evaluate the pre-train asr model as tutorail of nemo SR, but I don't find the file 'get_aishell_data.py' which introduced the wabsite(https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/zh/latest/asr/datasets.html#aishell2)

**Comment by yingying2017** [comment]
I want to evaluate the pre-train asr model as tutorail of nemo SR, but I don't find the file 'get_aishell_data.py' which was introduced in the wabsite(https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/zh/latest/asr/datasets.html#aishell2)

**Comment by titu1994** [comment]
Good find, it will be added back in https://github.com/NVIDIA/NeMo/pull/3195

**Comment by yingying2017** [comment]
thank you, but sorry, I want the file named 'get_aishell_data.py' which download and process Aishell1 rather than 'process_aishell2_data.py' because I don't have AISHELL2 dataset.

**Comment by titu1994** [comment]
Hmm. I couldn't find any file called get AiShell data in Nemo repo other than this one. Maybe @jbalam-nv may know

**Comment by yingying2017** [comment]
ok, thank you very much, it's so kind of you!

**Comment by jbalam-nv** [comment]
@yingying2017 The script should be available after https://github.com/NVIDIA/NeMo/pull/3203 is merged

**Comment by yingying2017** [comment]
> @yingying2017 The script should be available after #3203 is merged

Thank you so much! You help me solve my problem perfectly!
