### ISSUE TITLE
issue with setting checkpoints

### ISSUE THREAD

**Issue by omidaghdaei** [NVIDIA/NeMo#3197]
Hi, I have trouble with checkpoints. I wanna set checkpoints at end of each epoch. but it give me error.
It's error message is "pytorch_lightning.utilities.exceptions.MisconfigurationException: Invalid type provided for checkpoint_callback: Expected bool but received <class 'list'>."
Could you please help me to set checkpoints after end of each epoch and save them?

**Comment by omidaghdaei** [comment]
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import ModelCheckpoint
checkpoint_callback = ModelCheckpoint(
dirpath='my/path',
filename='{epoch}-{val_loss:.2f}-{other_metric:.2f}'
save_on_train_epoch_end=True )

trainer = Trainer(checkpoint_callback=[checkpoint_callback]

"this is my code for setting checkpoint"

**Comment by blisc** [comment]
See https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#checkpoint-callback
You are probably looking for https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#callbacks
For lightning questions, I recommend you to ask on the lightning github page: https://github.com/PyTorchLightning/pytorch-lightning
