### ISSUE TITLE
Index bug in RNN-T beam search algorithm ALSD

### ISSUE THREAD

**Issue by maxwellzh** [NVIDIA/NeMo#3199]
Please refer to https://github.com/espnet/espnet/issues/3781 for details.

Codes locate at
https://github.com/NVIDIA/NeMo/blob/807b001f2e20ac6ab2930419c32076d242128c5d/nemo/collections/asr/parts/submodules/rnnt_beam_decoding.py#L785-L787

**Comment by titu1994** [comment]
Thanks for the info ! Will fix it asap

**Comment by titu1994** [comment]
Fixed via #3202
