### ISSUE TITLE
Speaker Recognition Verification tutorial fails

### ISSUE THREAD

**Issue by pierrebedu** [NVIDIA/NeMo#3200]
Hi,
It's in the Speaker Recognition Verification tutorial.

While opening the jupyter notebook in collab, fails to import nemo.collections.asr

error message : "OSError: libtorch_hip.so: cannot open shared object file: No such file or directory"

it seems to be a pytorch or torchaudio wrong version

Thanks ;)

**Comment by titu1994** [comment]
Please provide full system info. We can't debug without knowing that. What is your Nemo version, torch version, torchtext torchaudio, cuda, OS

**Comment by pierrebedu** [comment]
Thanks for your answer.

In fact it is a tutorial that i launch in GOOGLE COLLAB following the instructions
(i load the notebook in collab, just by filling the url from nemo's github)
https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Identification_Verification.ipynb

nemo-toolkit @ git+https://github.com/NVIDIA/NeMo.git@026996907b14acd4a7600e93342358c974d3ab9b
torch @ https://download.pytorch.org/whl/cu111/torch-1.10.0%2Bcu111-cp37-cp37m-linux_x86_64.whl
torchaudio==0.10.0+rocm4.1
torchtext==0.11.0

since it's in a collab notebook i don't know the cuda version (???)
the instruction "import nemo.collections.asr as nemo_asr" fails.

Sorry for my little knowledge and thanks for your patience :)

**Comment by mthrok** [comment]
Hi

Torchaudio in Google Colab is currently having issue. You can check the issue here.
https://github.com/googlecolab/colabtools/issues/2417

**Comment by titu1994** [comment]
Thanks for the find @mthrok ! We'll need to await Colab fixes from their end.

**Comment by pierrebedu** [comment]
!pip install torch==1.10.0+cu111 torchvision==0.11.1+cu111 torchaudio==0.10.0+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html 

makes things work
