### ISSUE TITLE
How to do "Riva Custom Voice" which is presented in 2021 GTC

### ISSUE THREAD

**Issue by ahmetgunduz** [NVIDIA/NeMo#3210]
I would like to train and deploy a branded voice in Nvidia Riva. This is presented in NVIDIA GTC Nov. 2021 by the CEO Jensen Huang. He states that you can clone your voice with 30 mins of speech data and fine tune Riva model. 

Here is a link to a paper for the Custom Voice. https://blogs.nvidia.com/blog/2021/11/09/riva-enterprise-custom-voice-speech-ai/

In its current state, NVIDIA Riva has the option of two pipelines for Text to Speech : 

1. FastPitch and HiFi-GAN Pipeline 
2. Tacotron2 and Waveglow

I suspect that we should train Spectrogram generators (either FastPitch or Tacotron2) with selected voice recordings to be cloned via Nemo and then deploy using Riva. 

I have checked Nvidia NGC Catalog and there seems to be nothing about it. Could you please help me here?

**Comment by arunvenkatesan-nv** [comment]
@ahmetgunduz - Thank you for your interest in Riva Custom Voice. The feature is expected to be available early next year. Please feel free to sign up for [Riva Enterprise](https://www.nvidia.com/en-us/ai-data-science/products/riva-enterprise/) to get updates regarding future releases

**Comment by haiderasad** [comment]
hi @arunvenkatesan-nv is it avail now for training custom voice?

**Comment by magicse** [comment]
+
