### ISSUE TITLE
How to use model after transfer learning on new dataset

### ISSUE THREAD

**Issue by krnithishkumar** [NVIDIA/NeMo#3245]
Hi,
Used `quartznet_15x5` model for the transfer learning on the open-source dataset (AN4 dataset) for ASR. Once the pre-trained model gets trained with the newer dataset. I tried saving the trained model. Once I tested with the saved model using `nemo_asr.models.<MODEL_BASE_CLASS>.restore_from(restore_path="<path/to/checkpoint/file.nemo>")`. It shows the empty result `[' ']` even on the trained data.

Kindly provide us with the steps to follow after the transfer learning progress.

Code: 
```
config_path = './quartznet_15x5.yaml'

yaml = YAML(typ='safe')
with open(config_path) as f:
    params = yaml.load(f)

trainer = pl.Trainer(gpus=1, max_epochs=50)
quartznet_model = nemo_asr.models.EncDecCTCModel(cfg=DictConfig(params['model']), trainer=trainer)

trainer.fit(quartznet_model)
quartznet_model.save_to("./tl-osd.nemo")

```

**Comment by titu1994** [comment]
During training does the model get any word error rate below 100%?

**Comment by krnithishkumar** [comment]
The model doesn't provide any details with regards to Word Error Rate during the training process. The below image contains the respective logs.
![image](https://user-images.githubusercontent.com/29236082/143419847-9292f932-271b-4489-8abc-e6f08439f86e.png)

**Comment by titu1994** [comment]
There should be tensorboard logs present, or weights and biases

**Comment by krnithishkumar** [comment]
@titu1994 Yes, there is a folder in the present directory with the name `lightnin_logs` with the different versions inside it. 
Are you referring to that log?

**Comment by titu1994** [comment]
There should be a Nemo log as well as pytorch log.

**Comment by krnithishkumar** [comment]
@titu1994 NeMo logs are not present in the same directory. Can you check with the above-mentioned code whether it needs to be added with some new parts?

**Comment by krnithishkumar** [comment]
Any updates?

**Comment by titu1994** [comment]
You should use Nemo ExpManager when training. If not, search for lightning logs. Can't do much without the logs

**Comment by krnithishkumar** [comment]
@titu1994 Can you provide a sample script for the transfer learning in ASR?

**Comment by titu1994** [comment]
There's a tutorial in the tutorials/ASR directory of Nemo. Please refer to that.
