### ISSUE TITLE
Error "Can't pickle local object" when using multiprocessing on GPU

### ISSUE THREAD

**Issue by DieguJota** [NVIDIA/NeMo#3246]
I'm looking to develop an API that will perform multiple simultaneous transcripts every time an external request arrives. To perform these simultaneous transcriptions I thought of using python multiprocessing to help me.
Performing CPU transcripts in multiprocessing works fine, however when using GPU I get the error "`Can't pickle local object FilterbankFeatures.__init__.<locals>.<lambda>"
`
Here is an example of the two scenarios on GPU and CPU:
https://colab.research.google.com/drive/1O8fEkC4SKeILJeotYGU54dMkX15go1nK?usp=sharing

I have little experience with this type of processing, I have been trying to resolve this for a few weeks. If anyone has a solution, thank you in advance.

**Comment by titu1994** [comment]
Nemo models are not pickleable therefore they cannot be run with multi threading. Multiple processes however are fine. You will need to handle the logic of launching the subprocess and syncing data back and forth. There's an ASR webapp based on gunicorn which partially shows this but it's not meant to be efficient.
