### ISSUE TITLE
Colab throws an error

### ISSUE THREAD

**Issue by Nikuson123** [NVIDIA/NeMo#3248]
Colab notebook: [lab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0rc1/tutorials/tts/2_TTS_Tacotron2_Training.ipynb](https://colab.research.google.com/github/NVIDIA/NeMo/blob/r1.0.0rc1/tutorials/tts/2_TTS_Tacotron2_Training.ipynb#scrollTo=HEvdSU5WYZbj)

Error:
No module named 'nemo'

**Comment by blisc** [comment]
Please use the latest version available at
github: https://github.com/NVIDIA/NeMo/blob/stable/tutorials/tts/Tacotron2_Training.ipynb
colab: https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/tts/Tacotron2_Training.ipynb

Please uncomment the first cell that says: `# # If you're using Colab and not running locally, uncomment and run this cell.`
