### ISSUE TITLE
LM for ASR

### ISSUE THREAD

**Issue by cri5Castro** [NVIDIA/NeMo#325]
Hi 
I'm following this tutorial and I wonder to know if the LM described here is char based or word level based?
https://github.com/NVIDIA/NeMo/blob/master/examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb
also i wanna know if is possible to use a char based language model

**Comment by victornoriega** [comment]
Every language model is based on words. I don't know if it is impossible to create a char based language model, but when I think about it, it's just another word based language model. Why do you need something like that?

**Comment by okuchaiev** [comment]
The KenLM model is word-based. It is triggered every time a complete word is transcribed as part of beam search hypothesis.
