### ISSUE TITLE
Performance test on CPU and GPU 

### ISSUE THREAD

**Issue by awsomecod** [NVIDIA/NeMo#3257]
Would you please provide some benchmark on the performance of NeMo ASR on CPU and GPU?

I am particularly interested to know if I can increase the throughput of ASR by using a GPU instead of a CPU? And how much would be the increase in the throughput?

**Comment by titu1994** [comment]
The answer as always will depend on what CPU and GPU and against what those numbers will be compared against. 

As a general rule, using a gpu and the largest batch size you can use for inference will always surpass the CPU. Even at BS1, a GPU forward pass will be much faster than a CPU forward pass.

**Comment by titu1994** [comment]
We won't be distributing speed numbers etc, they are incomparable unless several external factors are accounted for and therefore there will always be inaccurate to some extent.

**Comment by awsomecod** [comment]
@titu1994 

Right now I am using an Intel 11700k CPU which has 8 cores. So I think having and RTX gpu will speed up the inference. 

Would you please guide me, which one of these factors are impactful on the inference speedup when using an RTX GPU:

- Number of Cuda cores
- Number of tensorflow cores
- RAM of the graphic card
- Ray tracing feature

**Comment by titu1994** [comment]
I don't really have such detailed info as to what is more important factor for speed of inference. Number of cuda cores nay speed things up, more memory helps with larger batch size.

If you want a comparison, try using colab with a few dozen audio files, with and without a GPU to measure how slow things get on a standard CPU vs a GPU.

**Comment by awsomecod** [comment]
Currently, I am using the below code to transcribe two audio files on a GPU. Would you please let me know what command I can use to increase the batch size of the inference so as to transcribe the two audio files in parallel on the GPU?

```
import nemo
import nemo.collections.asr as nemo_asr
import nemo.collections.nlp as nemo_nlp
import nemo.collections.tts as nemo_tts

quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="stt_en_quartznet15x5").cuda()
English_text = quartznet.transcribe(['~/audio1.wav', '~/audio2.wav'])

```

**Comment by titu1994** [comment]
By default, the "batch_size" argument of transcribe function is set to 4. However you are loading model and calling transcribe so it's on the CPU. You need to add model = model.to("cuda") before transcribe line to use GPU

**Comment by awsomecod** [comment]
@titu1994  I used the below command as you instructed. However, there was no speedup for the inference process. I mean, the computation time was as much as if I had transcribed the two audio files in sequence. 

```
English_text = quartznet.transcribe(['~/audio1.wav', '~/audio2.wav'], batch_size=1)

```

**Comment by titu1994** [comment]
You're reducing the batch size from 4 to 1 and passing 2 audio files on the GPU. 

Replace .cuda() with .cpu() for CPU. 
Add more audio files to list.
Try with different batch sizes to see what effect it has on large enough number of samples in the list (say 20 files).

**Comment by awsomecod** [comment]
I will use 20 audio files with different batch size. But can I keep `.cuda()`? Because I want to transcribe using gpu.

**Comment by titu1994** [comment]
Yes sure. I mentioned it in case you want to compare CPU vs GPU. You also want to add time.time() before and after transcribe calls.

**Comment by awsomecod** [comment]
The lengths of audio files that I am transcribing are all equal. I performed inference on GPU using different values for `batch_size`. I calculated the following fraction for each `batch_size`:

`Total_Computation_Time / Total_Number_of_Audio_Files`

The lowest value that I achieved for the above fraction was only half of the computation time for transcribing one audio file on GPU. Is this the best performance that could be achieved by using a GPU?

I am using a P100 GPU on google colab.

**Comment by titu1994** [comment]
GPUs are meant for fast processing. The gap increases the larger the number of files, the larger the batch size and more powerful the GPU. Also, as I said already, colab has network IO which is slow which is increasing inference time too. 

This is not a realistic benchmark, just know that inference time depends on many factors and GPUs should generally be faster
