### ISSUE TITLE
The results cannot be reproduced using the pre-training model

### ISSUE THREAD

**Issue by QzzIsCoding** [NVIDIA/NeMo#3267]
**Describe the bug**

I tested the model nmt_en_zh_transformer24x6 and nmt_en_zh_transformer6x6  on WMT18 test set and found that the blue score was a little low.

**Steps/Code to reproduce bug**

`model = MTEncDecModel.from_pretrained("nmt_en_zh_transformer24x6")`

`import copy`
`cfg = copy.deepcopy(model.cfg)`

`from omegaconf import OmegaConf, open_dict`

`with open_dict(cfg):`
 ` cfg.test_ds.use_tarred_dataset = False`
 ` cfg.test_ds.src_file_name = "/datasets/wmt18/clean.en"`
  `cfg.test_ds.tgt_file_name = "/datasets/wmt18/clean.zh"`

`with open_dict(model.cfg):`
  `model.cfg.tokens_in_batch=512`
  `model.cfg.clean=False`
  `model.cfg.max_seq_length = 512`
  `model.cfg.cache_ids=False`
  `model.cfg.cache_data_per_node=False`
  `model.cfg.use_cache=False`
  `model.cfg.shuffle=False`
  `model.cfg.num_samples=-1`
  `model.cfg.drop_last=False`
  `model.cfg.pin_memory=False`
  `model.cfg.load_from_cached_dataset=False`
  `model.cfg.reverse_lang_direction=False`
  `model.cfg.load_from_tarred_dataset=False`
  `model.cfg.tar_shuffle_n=100`

`import pytorch_lightning as ptl`

`trainer = ptl.Trainer(gpus=1,`
                      `num_nodes=1,`
                      `max_steps=100000,`
                      `accumulate_grad_batches=1,`
                      `checkpoint_callback=False,`
                      `val_check_interval=578,`
                      `sync_batchnorm=False)`
`trainer.test(model)`
![ac2dc0c25892480a3e690e2df9fab50](https://user-images.githubusercontent.com/56379157/144012971-2dbd226e-8b34-4e2a-9d23-e2ac319d8783.png)

24x6 blue score is 29.38408660888672 ，10 points lower than 39.9 in the introduction
6x6 blue score is 2.8，but in the introduction it is 35.0

How can I set the parameters to get the correct results?

**Comment by MaximumEntropy** [comment]
Hi,

The recommended way to evaluate a model is using the `nmt_transfomer_infer.py` script (https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/machine_translation/nmt_transformer_infer.py). 

You can do this by downloading the `.nemo` file and then running.

```
python nmt_transformer_infer.py --model nmt_en_zh_transformer24x6.nemo --srctext wmt18_en.txt --tgtout wmt18_en_translated_to_zh.txt
```

Let me know if you are still a regression in BLEU scores.

**Comment by MaximumEntropy** [comment]
Once you have the output file, you can compute sacreBLEU from your CLI like `cat wmt18_en_translated_to_zh.txt | sacrebleu -t wmt18 -l en-zh`

**Comment by QzzIsCoding** [comment]
@MaximumEntropy Hi, thanks for your reply. But I used the following instructions, oom error occured. After I splited the test set, it  translated some sentences. However, when I evaluate the final 712 sentences, oom occured again.
`python nmt_transformer_infer.py --model nmt_en_zh_transformer6x6.nemo --srctext wmt18_en.txt --tgtout wmt18_en_translated_to_zh.txt
`
![image](https://user-images.githubusercontent.com/56379157/144187765-a8ea9362-9203-44ca-94f9-42f0d3a40b1c.png)

The GPU is V100 with 32G.

**Comment by MaximumEntropy** [comment]
Hi, you can reduce the batch size during inference using the batch size argument. The default batch size is 256 which may be too large for a 32G GPU. 

You can specify the batch size like

`python nmt_transformer_infer.py --model nmt_en_zh_transformer6x6.nemo --srctext wmt18_en.txt --tgtout wmt18_en_translated_to_zh.txt --batch_size 64`

**Comment by QzzIsCoding** [comment]
@MaximumEntropy  
Thank you.
I get the bleu score is 35.1，it is same as in the introduction. That's very nice.
And I have two other questions.
Firstly, I want to test on my own test set. How do I operate? 
Secondly, I have made some parallel corpus data sets in vertical fields (about 120K). I want to fine tune the model nmt_en_zh_transformer6x6.nemo. Now I refer to the file (ASR_CTC_Language_Finetuning.ipynb) to do the task. The main codes are as follows:

# Model encoder has been frozen, and batch normalization has been unfrozen
`if freeze_encoder:`
  `model.encoder.freeze()`
  `model.encoder.apply(enable_bn_se)`

`with open_dict(model.cfg.optim):`
  `model.cfg.optim.lr = 0.0004`
  `model.cfg.optim.weight_decay = 0.001`
  `model.cfg.optim.sched.warmup_steps = None`
  `model.cfg.optim.sched.warmup_ratio = 0.05`
  `model.cfg.optim.sched.min_lr = 1e-9`
  `model.beam_size=4`
  `model.max_generation_delta=5`
  `model.label_smoothing=0.1`
  `model.encoder_tokenizer.vocab_size=32000`
  `model.decoder_tokenizer.vocab_size=32000`

`trainer = ptl.Trainer(gpus=1,`
                      `num_nodes=1,`
                      `max_steps=100000,`
                      `accumulate_grad_batches=1,`
                      `checkpoint_callback=False,`
                      `val_check_interval=578,`
                      `logger=False,`
                      `sync_batchnorm=False)`
`model.set_trainer(trainer)`
`model.cfg = model._cfg`

`trainer.fit(model)`

Do you have any good suggestions for parameter setting?

**Comment by QzzIsCoding** [comment]
Hi, when I fine-tuned the model nmt_en_zh_transformer6x6.nemo in the machine 1080Ti with 11Gb. It occurs OOM.
`RuntimeError: CUDA out of memory. Tried to allocate 1.00 GiB (GPU 0; 10.92 GiB total capacity; 9.39 GiB already allocated; 470.69 MiB free; 9.65 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
However, when I used the nmt_en_zh_transformer24x6.nemo it could run normally. The other sets were same, the parameters of the latter are larger than the former. Is this caused by the pytorch's version?

**Comment by MaximumEntropy** [comment]
Hi,

With finetuning experiments in the past, we have typically fine-tuned the entire encoder and decoder without freezing anything with Adam and no learning rate scheduler. We usually do a sweep over learning rates though starting at 3e-4 and down to something like 1e-6 (maybe even lower sometimes).

An important thing to note when fine-tuning is that your fine-tune dataset pre-processing should be identical or very similar to what was done while training the model. For En <-> Zh, the English side was pre-processed using Moses (with punctuation normalization and tokenization). For Chinese, we used OpenCC to map traditional characters to simplified ones and used Jieba to do word segmentation. Please apply these steps to your fine-tuning datasets as well.

**Comment by MaximumEntropy** [comment]
Regarding OOM, it is pretty strange. I would not have expected a smaller model to OOM regardless of the pytorch version. You can always try reducing the number of tokens per batch to see if that works.

**Comment by QzzIsCoding** [comment]
@MaximumEntropy  Hi, thanks for your reply. Fine-tuning is very common in domain adaptation. But it is prone to over-fitting on the target domain as well as forgetting on the general domain. So I want to use the adapter method, integrating an additional module into the network. The additional module can be a fully connection layer, a self-attention layer or their combinations. Then fine-tune only on the domain-specific part. If I want to train a multi domain model that can add new domains at any time, is it feasible to select the corresponding adapter in the inference stage by adding domain tags? In this way, only one model needs to be deployed, which can save resources.

**Comment by MaximumEntropy** [comment]
Hi! Yes, it should definitely be possible to implement adapters on top of our transformer architecture. I don't think we have any near-term plans to implement something like this. If you end up writing something for this, you can send us a PR and we can take a look at it :)
