### ISSUE TITLE
ECAPA TDNN pretrained fails to export ONNX - missing 'input_example'

### ISSUE THREAD

**Issue by ShantanuNair** [NVIDIA/NeMo#3268]
**Describe the bug**

I cannot export the pertained ECAPA TDNN model for embeddings to .onnx 
Exporting  requires the model to have a `input_example` which is not available on the ecapa tdnn model.

**Steps/Code to reproduce bug**

```
import nemo.collections.asr as nemo_asr
speaker_model = nemo_asr.models.EncDecSpeakerLabelModel.from_pretrained(model_name='ecapa_tdnn')
speaker_model.export(output='mymodel.onnx')
```

Output:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-51-d55b2004ba1e> in <module>()
      3 import nemo.collections.asr as nemo_asr
      4 speaker_model = nemo_asr.models.EncDecSpeakerLabelModel.from_pretrained(model_name='ecapa_tdnn')
----> 5 speaker_model.export(output='mymodel.onnx')

1 frames
/usr/local/lib/python3.7/dist-packages/nemo/core/classes/exportable.py in _setup_input_example(self, input_example)
    389 
    390     def _setup_input_example(self, input_example):
--> 391         input_list = list(input_example)
    392         input_dict = {}
    393         # process possible kwargs

TypeError: 'NoneType' object is not iterable

```

**Expected behavior**

I get a mymodel.onnx

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

Nemo version: r1.5.0

**Additional context**

GPU: Tesla T4

**Comment by ShantanuNair** [comment]
@nithinraok , for some context, I'm trying to get speaker diarization working on Triton. Any help would be really appreciated. Since there is no diarization support in Riva, this is a major step in achieving a nice, productionizable ASR pipeline.

**Comment by nithinraok** [comment]
Could you try passing an empty array of fixed size to the model while building onnx model. I suggest you follow onnx model building steps compared to default export from nemo speaker model, while I get some time to work on this.

**Comment by nithinraok** [comment]
This PR adds the feature to export onnx models with NeMo 
https://github.com/NVIDIA/NeMo/pull/3650

**Comment by TechInterMezzo** [comment]
> This PR adds the feature to export onnx models with NeMo

I tried that export.py script but I also get the error when i try to export the ECAPA TDNN model to ONNX:

```
[NeMo E 2023-04-10 16:25:07 export:164] Export failed. Please make sure your NeMo model class (<class 'nemo.collections.asr.models.label_models.EncDecSpeakerLabelModel'>) has working export() and that you have the latest NeMo package installed with [all] dependencies.
Traceback (most recent call last):
  File "/workspace/export.py", line 173, in <module>
    nemo_export(sys.argv[1:])
  File "/workspace/export.py", line 169, in nemo_export
    raise e
  File "/workspace/export.py", line 154, in nemo_export
    _, descriptions = model.export(
  File "/usr/local/lib/python3.10/dist-packages/nemo/core/classes/exportable.py", line 113, in export
    out, descr, out_example = model._export(
  File "/usr/local/lib/python3.10/dist-packages/nemo/core/classes/exportable.py", line 188, in _export
    input_list, input_dict = parse_input_example(input_example)
  File "/usr/local/lib/python3.10/dist-packages/nemo/utils/export_utils.py", line 118, in parse_input_example
    input_list = list(input_example)
TypeError: 'NoneType' object is not iterable
```

The command is just
`python export.py ecapa_tdnn.nemo ecapa_tdnn.onnx --autocast --runtime-check`

Am I missing something?

**Comment by nithinraok** [comment]
Do you face same error with titanet_large.nemo from https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/titanet_large

**Comment by nithinraok** [comment]
Thanks, I will be looking at this soon.

**Comment by ARKEYTECT** [comment]
Hi there:
     I listened to your suggestion and use the following code to export : 
      
`speaker_model = nemo_asr.models.EncDecSpeakerLabelModel.from_pretrained(model_name='ecapa_tdnn')
speaker_model.to("cpu")
speaker_model.export(output='mymodel.onnx', input_example=[torch.randn(1, 80, 300, requires_grad=True), torch.ones(300)])`

Got the following error: 
TypeError: forward_for_export() missing 1 required positional argument: 'processed_signal_len'
Any ideas? Much appreciated.

**Comment by chidalgoRR** [comment]
Were you able to fix this? I am facing the same issue with Diarization MSDD telephonic model

**Comment by nithinraok** [comment]
Are you getting the 

```
Got the following error:
TypeError: forward_for_export() missing 1 required positional argument: 'processed_signal_len'
```

while exporting or while running inference?

**Comment by chidalgoRR** [comment]
Thanks for the response. I opened an issue with my bug and I got a response. Here is the response I got:

NeMo neural diarization class (clustering+MSDD) is not ONNX exportable.
This is because pytorch linear algebra library is not fully ONNX exportable.
We are working on fully neural diarization and only after fully neural diarization is released, the diarization pipeline will be ONNX exportable.

**Comment by nithinraok** [comment]
Thanks @chidalgoRR , the above question was to @ARKEYTECT

**Comment by thewh1teagle** [comment]
@ARKEYTECT 
How do you use it in onnxruntime?
