### ISSUE TITLE
AttributeError: type object 'EncDecCTCModel' has no attribute 'list_available_models'

### ISSUE THREAD

**Issue by KunwarK13** [NVIDIA/NeMo#3273]
```
import nemo
import nemo.collections.asr as nemo_asr

asr_model = nemo_asr.models.EncDecCTCModel.list_available_models()
print("done")
```

Whenever I run this code, it gives me this error:
`AttributeError: type object 'EncDecCTCModel' has no attribute 'list_available_models'
`
I have all the dependencies installed.

When I hover over the line of code in PyCharm, it shows me the definition of the function and everything, which means it recognizes it. But for some reason it doesn't work when I run it.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/88787251/144137632-b741ba3a-c8c6-491b-bee7-01daeee7b3fa.png">

**Comment by titu1994** [comment]
Did you install all the dependencies such as Cython from https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation

**Comment by KunwarK13** [comment]
> Did you install all the dependencies such as Cython from https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation

Yes, I have all the dependencies installed.

**Comment by titu1994** [comment]
CPU mode should be supported either way. You can try passing map_location="cpu" inside from_pretrained() once list_available_models() works. 

Just to confirm you do pip install nemo_toolkit["all"] to get v1.5.0 right ? And use pytorch 1.10 ?

**Comment by KunwarK13** [comment]
Yes, I am using Pytorch 1.10.

When I tried using pip install nemo_toolkit["all"], it says "zsh: no matches found: nemo_toolkit[all]". So I did pip install nemo_toolkit, and it worked. It installed version 1.6.0rc0.

**Comment by titu1994** [comment]
You need to do the "all" part - otherwise it doesn't install the domains just the Nemo core.

**Comment by KunwarK13** [comment]
I tried doing that, but it doesn't work. Should I try installing it with Conda, using this command: conda install -c bioconda nemo?

**Comment by titu1994** [comment]
No Nemo is on pip not conda. Try using "[all]" - the brackets may interfere with zsh

**Comment by titu1994** [comment]
Or use the reinstall.sh script at the root of Nemo

**Comment by KunwarK13** [comment]
Using pip still doesn't work, and it says this: zsh: no matches found: nemo_toolkit[all].

Ok I will try to install nemo by cloning this git repository. Thanks.

**Comment by KunwarK13** [comment]
It works now! Thanks a lot.
