### ISSUE TITLE
kenlm for conformer-ctc

### ISSUE THREAD

**Issue by sarasesar** [NVIDIA/NeMo#3275]
Hi. i need a LM for ctc-conformer and i trained a kenlm moel by this command:

python train_kenlm.py --train_file /home/mount/librispeech-lm-norm.txt --nemo_model_file stt_en_conformer_ctc_large.nemo --kenlm_model_file ../nemo_lm_6_new --ngram_length 6 --kenlm_bin_path ../kenlm/build/bin/ --do_lowercase

but when i try to use this LM for beam search decode, the output was something like this :(wowliadfbjdslfsofymnyq)
i also played with arameters alpha and beta. but not useful.
could you please help me?

**Comment by sarasesar** [comment]
@VahidooX
Hi, could you please help me?

**Comment by VahidooX** [comment]
Hi,

Did you try the LM on pretrained stt_en_conformer_ctc_large or another model after training the LM?
Is it a BPE based model, right?
Which script you used for evaluating the model with the N-gram LM?
Have you tried greedy or beamsearch without LM evaluations with the same script?

**Comment by sarasesar** [comment]
thank you very much! I've trouble with dedicating multi GPU for asr/speech_to_text_bpe.py.
In config file of conformer, I tried gpu=-1 and also gpu=2 but when I run the code, it just use the first GPU and it doesn't use the second one.
Could you please help me to solve it?

**Comment by sarasesar** [comment]
thank you very much!

**Comment by sarasesar** [comment]
thank you very much.
i got my problem from your question.
