### ISSUE TITLE
beam search decoding ASR

### ISSUE THREAD

**Issue by cri5Castro** [NVIDIA/NeMo#328]
hello there i'm following this tutorial , and i'm trying to reproduce using the LM approach with beam search .

I should change the greddy decoder part for the beam search for training or train with the greddy decoder and use the beam search decoder for inference?

https://github.com/NVIDIA/NeMo/blob/master/examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb

**Comment by okuchaiev** [comment]
you should train with greedy decoder - during training, it would be just used to print intermediate results and it does not have any trainable weights.

Then you can run inference using beam search decoder, see: https://nvidia.github.io/NeMo/asr/tutorial.html#evaluation-with-language-model 

BTW, master is our development branch - I'd recommend you use the latest released branch instead https://github.com/NVIDIA/NeMo/releases
