### ISSUE TITLE
Is "offset" supported in audio reader ?

### ISSUE THREAD

**Issue by BenoitWang** [NVIDIA/NeMo#3295]
Hi, I am totally new to NeMo and I would just like to ask if "offset" is already in use for loading audio? Because I read this warning in the document : 
![image](https://user-images.githubusercontent.com/41187612/145059151-91b5e489-fe8a-43e4-a6bf-71170a92f462.png)

**Comment by titu1994** [comment]
Dali dataset does not support duration and offset, but non-dali datasets support it.

**Comment by BenoitWang** [comment]
Hi @titu1994, thanks for the answer.
