### ISSUE TITLE
For Inverse Text Normalization, is not working for "one two three four"

### ISSUE THREAD

**Issue by st1992** [NVIDIA/NeMo#3307]
For Inverse Text Normalization, is not working for "one two three four"
the output should be "1 2 3 4"
whereas the output is "one two three four"

**Comment by ekmb** [comment]
This is intended behavior to avoid denormalizing cases like `one of us`. To change this, comment out https://github.com/NVIDIA/NeMo/blob/main/nemo_text_processing/inverse_text_normalization/en/taggers/cardinal.py#L120 .

**Comment by st1992** [comment]
Thanks for the help and quick response.

**Comment by kli017** [comment]
Hello @ekmb, I want to convert single numer words to digit.  For example "one -> 1".  Where should I modified? Thanks a lot

**Comment by kli017** [comment]
@ekmb Thanks for the reply. I modified this line with `self.graph=graph` and test with number less than 13 but still get the english word. e.g.(`python inverse_normalize.py --text="twelve" --language=en`)
