### ISSUE TITLE
Missing script get_tatoeba_data.py 

### ISSUE THREAD

**Issue by jonaskratochvil** [NVIDIA/NeMo#331]
Hello,

I am trying to follow the PunctuationWithBERT notebook, however, the script for getting the Tatoeba data is not present in the repository. Could you please include it or give an example of how the input text data and the corresponding labels should look like for this task? Thank you.

**Comment by ekmb** [comment]
here is the script https://github.com/NVIDIA/NeMo/blob/master/examples/nlp/scripts/get_tatoeba.py

**Comment by jonaskratochvil** [comment]
Thank you for your reply. I am facing another issue. 
When I try to import the nemo.collections.nlp I get an error stating that the module 'nemo.collections' has no attribute 'nlp'. There is no such problem when importing asr/tts/simple_gan modules.

**Comment by ekmb** [comment]
The issue should be fixed now.
The latest stable version 0.9.0 could be installed via pip but it doesn't include the punctuation example.
To use this example, please use the latest master and run https://github.com/NVIDIA/NeMo/blob/master/reinstall.sh.
Also you can use https://github.com/NVIDIA/NeMo/blob/master/Dockerfile

The tutorial for this example could be found here: https://github.com/NVIDIA/NeMo/blob/master/docs/sources/source/nlp/punctuation.rst

**Comment by jonaskratochvil** [comment]
Thank you for your help. I was able to successfully run the example tutorial.
