### ISSUE TITLE
Question[multi node training]

### ISSUE THREAD

**Issue by BuaaAlban** [NVIDIA/NeMo#3312]
How to train a  model using multi-node(eg. 2 node, each node with 4gpus, just set the node numbers in the config doesn't work, In the pytorch-lighting tutorial, It needs the parameters like port and rank, etc) ?  Do you have any tutorial or examples like in the speech_to_text_bpe.py?

# Training the model
```sh
python speech_to_text_bpe.py \
    # (Optional: --config-path=<path to dir of configs> --config-name=<name of config without .yaml>) \
    model.train_ds.manifest_filepath=<path to train manifest> \
    model.validation_ds.manifest_filepath=<path to val/test manifest> \
    model.tokenizer.dir=<path to directory of tokenizer (not full path to the vocab file!)> \
    model.tokenizer.type=<either bpe or wpe> \
    trainer.gpus=-1 \
    trainer.accelerator="ddp" \
    trainer.max_epochs=100 \
    model.optim.name="adamw" \
    model.optim.lr=0.001 \
    model.optim.betas=[0.9,0.999] \
    model.optim.weight_decay=0.0001 \
    model.optim.sched.warmup_steps=2000
    exp_manager.create_wandb_logger=True \
    exp_manager.wandb_logger_kwargs.name="<Name of experiment>" \
    exp_manager.wandb_logger_kwargs.project="<Name of project>"
```

**Comment by titu1994** [comment]
Trainer in pytorch lightning has a num_nodes argument which you can set to 2, similar the gpus=2 for multinode training.

**Comment by titu1994** [comment]
You should follow the tutorial on the lightning page https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster.html

Depending on your commute environment, (1) or (3), you might need to change the setup. Please follow the steps recommended there. 

In our team, we follow the (3) slurm setup for multi node and only require changing the num_nodes argument to trainer (along with writing a slurm script as shown in 4th step of slurm environment)
