### ISSUE TITLE
Inverse Text Normalization. Make matching between normalized and non-normalized tokens

### ISSUE THREAD

**Issue by kotikkonstantin** [NVIDIA/NeMo#3319]
**Is your feature request related to a problem? Please describe.**

Let we have the next text (in Russian): "куку девятьсот шестьдесят шесть миллиардов восемьсот сорок четыре миллиона семьсот пять тысяч четыреста двадцать пять девятьсот сорока пяти купить"

`inverse_normalizer.find_tags` and. `inverse_normalizer.select_tag` give us the next tokens representation:
_' tokens { name: "куку"  }  tokens {  cardinal { integer: "966844705425"  }  }  tokens {  cardinal { integer: "945"  }  }  tokens { name: "купить"  } '_

But by this output, it's complicated to make matching between "966844705425"  and corresponding words in the input text.

**Describe the solution you'd like**

`inverse_normalizer.find_tags` and `inverse_normalizer.select_tag` give us next tokens representation in another way:
_' tokens { name: "куку" , **(0, 4)** }  tokens {  cardinal { integer: "966844705425",  **(5, 107)**}  }  tokens {  cardinal { integer: "945", **(108,  128)** }  }  tokens { name: "купить", **(129,  135)**  } '_ (span values are approximately, just for demonstrating goal)

So we will have corresponding tokens spans in input text, and it will be easy to solve the matching problem between entities.

Thank you very much for your attention!

**Comment by okuchaiev** [comment]
@ekmb any thoughts on this?
