### ISSUE TITLE
AttributeError: Can't pickle local object 'AudioToBPEDataset.__init__.<locals>.TokenizerWrapper'

### ISSUE THREAD

**Issue by Alexey322** [NVIDIA/NeMo#3327]
Hi, I can not run transcribe audio method using STT En Conformer-CTC Small model on windows 10.
I am using the following code: 
```
import nemo.collections.asr as nemo_asr

asr_model = nemo_asr.models.EncDecCTCModelBPE.restore_from("models/stt_en_conformer_ctc_small.nemo")

files = ['1.wav']

print(asr_model.transcribe(files, batch_size=1))
```
I'm using branch r1.5.0
As a result, I get the following error: 
**AttributeError: Can't pickle local object 'AudioToBPEDataset\.\_\_init\_\_.\<locals\>\.TokenizerWrapper'**

On the colab everything worked without problems. What could be the problem and how to solve it? Thank you.

**Comment by titu1994** [comment]
The Nemo toolkit does not support windows. You can use Windows WSL on Windows 10 for CPU inference, or Windows 11 for CUDA support v

**Comment by manjuke** [comment]
I am getting the same error (AttributeError: Can't pickle local object 'AudioToBPEDataset.__init__.<locals>.TokenizerWrapper')  while doing transfer learning on Linux GPU. My code is as below:

conf_ctc_model = nemo_asr.models.EncDecCTCModelBPE.from_pretrained(model_name="stt_en_conformer_ctc_xlarge")
conf_ctc_model.setup_training_data(train_data_config=params['model']['train_ds'])
# Point to the new validation data for fine-tuning
conf_ctc_model.setup_validation_data(val_data_config=params['model']['validation_ds'])
trainer = pl.Trainer(strategy="deepspeed", accelerator="auto", devices=4)

I have tried varieties of option for strategy (dp, ddp, ddp_spawn) but no luck.

Pls suggest

**Comment by titu1994** [comment]
We only support ddp. We don't support deepspeed integration

**Comment by manjuke** [comment]
@titu1994 . Thanks for the response. I could solve this using ddp. 

I have one more issue. I have done transfer learning on pretrained confermer-ctc-model and I have ckpt files generated. But, I am unable to load them as they are not in .nemo format.
I am getting error, if I try to load them using model = nemo_asr.models.EncDecCTCModelBPE.restore_from(restore_path="/checkpoints/epoch_5-step_82700.ckpt")

So, How do I convert .ckpt to .nemo format.
I could not find any relevant answers in internet as well. Thanks.
