### ISSUE TITLE
AttributeError: type object 'EncDecCTCModel' has no attribute 'from_pretrained

### ISSUE THREAD

**Issue by architlfc** [NVIDIA/NeMo#3328]
I'm running into the same issue .
Python :3.8.12
Running inside docker image :pytorch:21.11-py3

Code: :
 ```
asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name='QuartzNet15x5Base-En', strict=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'EncDecCTCModel' has no attribute 'from_pretrained'

```
Installation steps :

- apt-get update && apt-get install -y libsndfile1 ffmpeg
- pip install Cython
- python -m pip install git+https://github.com/NVIDIA/NeMo.git@r1.5.0

_Originally posted by @architlfc in https://github.com/NVIDIA/NeMo/issues/2978#issuecomment-993514325_

**Comment by titu1994** [comment]
Answered in https://github.com/NVIDIA/NeMo/issues/2978
