### ISSUE TITLE
Serving trained ASR models via TorchServe

### ISSUE THREAD

**Issue by ahkarami** [NVIDIA/NeMo#3337]
Hi,
Thanks for your great framework. 
Do you have any plan for adding serving ASR models via TorchServe (_e.g._, REST API or gRPC API)? I think it would be great (but I think at first, one must implement an appropriate handler for it, because to the best of my knowledge TorchServe at current state doesn't have any handler for speech models such as QuartzNet ASR model).
Best

**Comment by ShantanuNair** [comment]
On a related note, an example showing how to get the Nemo model optimized and working on Triton would be very appreciated.

**Comment by entn-at** [comment]
I'd like to second that request for an example showing how to get NeMo models optimized/deployed on Triton. I know there is [an example for Jasper](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechRecognition/Jasper/triton), but it uses a different code base than NeMo.

**Comment by titu1994** [comment]
Nemo is first and foremost a research platform - it does support some models exported to Onnx but it's primary focus is advanced training of models in multiple domains. 

We may eventually support triton at some level but it is not currently our focus. Same goes with other export or deployment options - for those, we refer our users to Nvidia RIVA which can efficiently deploy conversational AI models.

**Comment by titu1994** [comment]
However, we encourage you to submit PRs if you are able to support TorchServe or other deployment platforms in Nemo.
