### ISSUE TITLE
German normalization fails due to apparent installation problems.

### ISSUE THREAD

**Issue by fcavallin** [NVIDIA/NeMo#3342]
**Describe the bug**

German normalization fails due to apparent installation problems.

**Steps/Code to reproduce bug**

If installed with:
`pip install nemo-toolkit[all]` the nemo_text_processing.text_normalization.de.taggers.tokenize_and_classify is not in the project in order to normalize german phrases although used in the nemo_text_processing/text_normalization/normalize.py file.

If installed with:
`python -m pip install git+https://github.com/NVIDIA/NeMo.git@main` the file nemo_text_processing/inverse_text_normalization/vi/taggers/money.py is not found.

If installed with:
`git clone -q https://github.com/NVIDIA/NeMo.git`
when normalizing, getting the following issue: [https://github.com/NVIDIA/NeMo/issues/3341]

**Expected behavior**

Successful German normalization

**Environment overview**

 - Environment location: Bare-metal: Ubuntu 20.04.3 LTS

**Environment details**

- OS version: Ubuntu 20.04.3 LTS
- PyTorch version:  Torch 1.10.0
- Python version: Python 3.8.12

**Comment by ekmb** [comment]
[This PR](https://github.com/NVIDIA/NeMo/pull/3355) fixes the issue. 
```
# install requirements
python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[nlp] && conda install -c conda-forge -y pynini=2.1.3


from nemo_text_processing.text_normalization.normalize import Normalizer
normalized_text = Normalizer(input_case='cased', lang='de').normalize('0,12', verbose=True)
```
