### ISSUE TITLE
How to restore a ckpt conformer model for inference/finetuning?

### ISSUE THREAD

**Issue by BuaaAlban** [NVIDIA/NeMo#3347]
For conformer model 

we can restore a nemo model by  
model = nemo_asr.models.EncDecCTCModelBPE.restore_from(name+'.nemo') 
and use it for inference.
But the models during training were saved in ckpt format.

And I tried model.load_state_dict(torch.load(model.ckpt))  but there are different keys.

How can I load a ckpt which was saved during training for inference? or how to convert a ckpt model to the target nemo model?

Thanks

**Comment by VahidooX** [comment]
You need to keep always_save_nemo in the config to true so that the last checkpoint is always stored as nemo format during training: https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/conformer_transducer_bpe.yaml#L229

The main reason we have nemo files is that it stores the tokenizer inside itself so that you do not need to move around the tokenizer. Loading a PTL checkpoint is tricky as it does not contain the tokenizers. If you want to load a PTL checkpoint and convert it to nemo format you may use the following commands:

`model = nemo_asr.models.EncDecCTCModelBPE.load_from_checkpoint(model_ckpt)
checkpoint = torch.load(model_ckpt)
model.load_state_dict(checkpoint['state_dict'], strict=True)
model.save_to(output_path)
`

The only issue is that you need to store the tokenizer at the exact path used during the training so that it can be found when PTL is being converted to nemo file.

**Comment by BuaaAlban** [comment]
Thanks a lot !

**Comment by BuaaAlban** [comment]
I can use the ddp accerator and the saved **ckpt model**  for **inference** by the following command.
`asr_model = EncDecCTCModelBPE.load_from_checkpoint(args.asr_model,strict=False)`

I add some attributes in the model during inference, and **I want to save the new model for finetuning** by `asr_model.save_to(xxx.nemo) `in the **nemo** format,  but  I found it can't be loaded with this error `_pickle.UnpicklingError: invalid load key, '\x1f'.`  And actually the resumed checpoints before are always in ckpt format，so I try to save it in another way `torch.save(asr_model,'test.ckpt')`,  and I found `AttributeError: Can't pickle local object 'FilterbankFeatures.__init__.<locals>.<lambda>'` which is this [ issue 1194 ](https://github.com/NVIDIA/NeMo/issues/1194).  But I want to save it during inference instead of training. 

What should  I do to make this work ( load trained ckpt model,add new attributes, save it in somewhat format, finetune the new model) ?
Do you have any suggestions? @VahidooX

**Comment by BuaaAlban** [comment]
I tried this method, it almost work 
```
>>> e636= torch.load('exp/kept_model/epoch636.ckpt')
>>> warmp ='exp/warmupmodel/index8-5.nemo' 
>>> asr_model = EncDecCTCModelBPE.restore_from(warmp)
>>> e636['state_dict']=asr_model.state_dict()
>>> e636.keys()
dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'callbacks', 'optimizer_states', 'lr_schedulers', 'hparams_name', 'hyper_parameters'])
>>> torch.save(ckpt, 'exp/Conformer-CTC-BPE_bs2k_sp_qat/checkpoints/Conformer-CTC-BPE_bs2k_sp--val_wer=0.0265-epoch=636.ckpt')
```

But is failed  (maybe due to my added parameters in the model?)
`ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`

**Comment by titu1994** [comment]
Please post the full stack trace. We have notebooks that take the ckpt file and restore a model, then save to Nemo file in TTS domain and it should just work.

**Comment by titu1994** [comment]
Nemo files don't have optimizer and scheduled in them btw so why would it fail to load if it's not trying to load it ?

**Comment by BuaaAlban** [comment]
Please kindly see the descriptions above for finetuning. 

1. I trained some models, and it saved n-best ckpt models automatically,  which I can use for **inference** (by `EncDecCTCModelBPE.load_from_checkpoint(args.asr_model)` )  or **finetuning**  (by change the` resume_from_checkpoint: ` path in the config file)

2. I change the code, add some attributes in the model definition(eg. self.clip_val =Parameter(xxx) in some layers)

And I load the trained ckpt model by `asr_model = EncDecCTCModelBPE.load_from_checkpoint(nbest.ckpt, **strict=False**)`, and now I save the model with the new attributes(This is where the problems begin) and I want to use it for finetuning. 

3.To save the new model, I tried two ways:

- `asr_model.save_to(xxx.nemo) `in the nemo format
- `torch.save(asr_model,'test.ckpt')`, and I found it can't be saved with  `AttributeError: Can't pickle local object FilterbankFeatures.__init__.<locals>.<lambda>`'which is this issue 1194 .

4. Finetuning 

As I can only save the new model sucessfully by  `asr_model.save_to(xxx.nemo) ` , so I tried to use it for finetuning (change the` resume_from_checkpoint: xxx.nemo` ),  I found it can't be loaded during finetuning  with this error `_pickle.UnpicklingError: invalid load key, '\x1f'`.

So I  tried another method, it almost work, first I load the saved n-best ckpt models, and I replace its' state dict with the new model's state dict (which has new attributes)
```
>>> e636= torch.load('nbest.ckpt')
>>> asr_model = EncDecCTCModelBPE.restore_from(xxx.nemo)
>>> e636['state_dict']=asr_model.state_dict()
>>> e636.keys()
dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'callbacks', 'optimizer_states', 'lr_schedulers', 'hparams_name', 'hyper_parameters'])
>>> torch.save(e636, 'newmodel.ckpt')
```
And I use newmodel.ckpt for finetuning  (change the` resume_from_checkpoint: newmodel.nemo` ), and it failed with this:
`ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group`
It is because that the optimizer state dict is different (I update the model definition, but the optimizer in newmodel.ckpt is still the old one, so there is a mismatch in the optimizer params)

Now, I just ignore the  load_state_dict( ) method in the optimizer class by do nothing(return None, instead of load optimizer state), and the finetuing can go on. I know this is stupid and unreasonable, but it as least make the process run.

I think there must be a way to load  both the state dict  and optimizer states, any suggestions?

**Comment by titu1994** [comment]
You cannot do torch.save(asr_model) - you can and should only save the state dict because code is not always portable, only parameters are. You should always do torch.save(asr_model.state_dict(), ...). This is mentioned even in pytorch documentation - https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-for-inference

**Comment by titu1994** [comment]
As to restoring a Nemo model - it can only be done via nemo.collections.asr.models.ASRModel.restore_from(xxx.nemo). Note this is not the same as torch.load(xxx.nemo) that will not work because you are trying to load a tarfiles, not a statedict via torch

**Comment by titu1994** [comment]
For loading both checking and state dict, @VahidooX  any ideas?
