### ISSUE TITLE
WER results are different 

### ISSUE THREAD

**Issue by andrusenkoau** [NVIDIA/NeMo#3350]
### Discussed in https://github.com/NVIDIA/NeMo/discussions/3339

<div type='discussions-op-text'>

<sup>Originally posted by **andrusenkoau** December 15, 2021</sup>
Hi everyone!
I am trying to decode all librispeech dev and test sets for my Conformer-CTC-BPE model by "eval_beamsearch_ngram.py"  script in greedy way. But I am getting WER results that are different from training logs. For example, for the last 100th epoch I have got  WER = **10.43%** for dev-clean according to "lightning_logs.txt". But after "eval_beamsearch_ngram.py" I have got WER = **12.01%**. Maybe i am doing something wrong?

This is my decoding command:

```
model_dir="nemo_experiments/Conformer-CTC-BPE/2021-12-14_12-47-27"
model_file="${model_dir}/checkpoints/Conformer-CTC-BPE.nemo"

for test_set in dev-clean dev-other test-clean test-other; do
    decode_dir=${model_dir}/decoding_${test_set}
    decode_log=${model_dir}/decoding_${test_set}.log
    decode_manifest=data/manifest_${test_set}.json
    python ${NGRAM_PATH}/eval_beamsearch_ngram.py --nemo_model_file ${model_file} \
                                                 --input_manifest ${decode_manifest} \
                                                 --acoustic_batch_size 10 \
                                                 --preds_output_folder ${decode_dir} \
                                                 --decoding_mode greedy | tee ${decode_log}
done
```</div>

**Comment by titu1994** [comment]
Beam search has hyper parameters alpha and beta, you need to tune those on your dev set to surpass the scores of greedy decoding c

**Comment by VahidooX** [comment]
You should get similar results, difference between WER during training and offline should be very small. Your command looks fine as long as you are passing the same manifest. Would you please try to calculate the WER with this script? 
https://github.com/NVIDIA/NeMo/blob/main/examples/asr/speech_to_text_eval.py

**Comment by andrusenkoau** [comment]
Thank you so much for the quick answers!

1. @titu1994 as far as I understand "greedy" decoding_mode does argmax decoding. Alpha and beta parameters are used only for beamsearch and beamsearch_ngram mode according to expression `final_score = acoustic_score + beam_alpha*lm_score + beam_beta*seq_length` . I don't use lm. Different values of beta (-2, -1, 0, 1, 2) produce the same WER.

By the way, It looks like a small typo in [doc](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html#hyperparameter-grid-search) -- `beamsearch: The beam search decoding is done but without using the N-gram language model, final results would be equivalent to setting the weight of LM (beam_beta) to zero.` Is it beam_alpha?

2. @VahidooX I tried to use https://github.com/NVIDIA/NeMo/blob/main/examples/asr/speech_to_text_eval.py, but I got an error:

```
for test_set in dev-clean dev-other test-clean test-other; do
    decode_dir=${model_dir}/decoding_${test_set}
    decode_log=${model_dir}/decoding_${test_set}.log
    decode_manifest=data/manifest_${test_set}.json
    python ${SCRIPT_PATH}/speech_to_text_eval.py --model_path ${model_dir} \
                                                                                    --pretrained_name ${model_file} \
                                                                                    --dataset_manifest ${decode_manifest} \
                                                                                    --batch_size 10 \
                                                                                    --amp False \
                                                                                    --use_cer False
done
```

```
usage: speech_to_text_eval.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE] [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR] [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]  [overrides ...]
speech_to_text_eval.py: error: unrecognized arguments: --model_path --pretrained_name nemo_experiments/Conformer-CTC-BPE/2021-12-14_12-47-27/checkpoints/Conformer-CTC-BPE.nemo --dataset_manifest data/manifest_dev-clean.json -- batch_size 10 --amp False --use_cer False
```

**Comment by titu1994** [comment]
For (2), it's a hydra script, don't use -- and just pass arg name. 

If you "don't, use lm" I assume you set alpha 0, it is expected to get better or worse scores. The baseline is set by alpha 0 beta 0. That should roughly match your greedy score. If that's not the case then three is something wrong on manifest or KenLM construction.

**Comment by VahidooX** [comment]
Those scripts should give you the same wer for greedy mode. If they give different results, please let me know so that I fix the bug. You may also try one of the pretrained models on ngc to make sure nothing is broken.

**Comment by andrusenkoau** [comment]
@titu1994 it was my silly mistake with running `speech_to_text_eval.py`. The script works without `--`.  But I got the same WER degradation as recently with the `eval_beamsearch_ngram.py` in greedy mode.  

Could it be related to the checkpoint averaging? The training log shows WER for an intermediate checkpoint. I compare my decoding results with the last checkpoint WER from training log. For decoding I use *.nemo model which is the average model of the last three checkpoints. But all of them have almost the same WER, which is still better than *.nemo decoding results...

@VahidooX I ran `speech_to_text_eval.py` with your pretrained model `stt_en_conformer_ctc_small`. My WER results almost the same as in your [docs](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_ctc_small):
```
test_clean -- Got WER of 0.04036
test_other -- Got WER of 0.09165
```

**Comment by VahidooX** [comment]
I do not think we have the feature of checkpoint averaging during the training for ASR models. That nemo file should be the checkpoint of the last epoch. Your experiments show that the evaluation code is OK and the problem is with the nemo file. Have you tried other checkpoints of that training? Are you sure that WER of 10.43% is for dev-clean and it is maintained until the last epochs? Do you see the results in the log files or in something like tensorbaord?

**Comment by andrusenkoau** [comment]
@VahidooX There is a line `Epoch 99, global step 35399: val_wer reached 0.10433 (best 0.10433), saving model to .../Conformer-CTC-BPE--val_wer=0.1043-epoch=99.ckpt` in my `lightning_logs.txt` file. I can see the same WER value in the tensorboard. I use whole dev-clean as a training validation. Also I converted `Conformer-CTC-BPE--val_wer=0.1043-epoch=99.ckpt` to *.nemo model format. The WER results for dev-clean by `speech_to_text_eval.py` are the same (0.12012) as for default `Conformer-CTC-BPE.nemo`.

**Comment by VahidooX** [comment]
Would you please try something?
Train a similar model for 5 epochs or so and then compare its wer with the offline evaluation script.

**Comment by andrusenkoau** [comment]
@VahidooX I have tried several different epochs for my setup of Conformer-CTC-BPE. Here you can see the results in the format: `WER from lightning_logs.txt` --> `WER by speech_to_text_eval.py` for dev-clean set.

5 epochs training:
`val_wer reached 0.36323 (best 0.36323)` --> `Got WER of 0.36961876401602883`

9 epochs training:
`val_wer reached 0.27041 (best 0.27041)` --> `Got WER of 0.2778574317120694`

61 epoch training:
`val_wer reached 0.11757 (best 0.11753)` --> `Got WER of 0.13547296055292085`

**Comment by VahidooX** [comment]
These results are from the same run, right?
It can be a bug, likely to be one in calculating the wer during validation. We have not encountered this issue as we just evaluate the model after it is converged. I would try to reproduce it on my system next week. In the meanwhile, would you please try evaluating that model at epoch 61 with different batch sizes?

**Comment by andrusenkoau** [comment]
@VahidooX I'm sorry for the long answer. Yes, the results are from the same run. I have tried several different batch sizes for the model at 61-th epoch:

`bs=1`    --> `Got WER of 0.13545457887577664`
`bs=5`    --> `Got WER of 0.13552810558435352`
`bs=10` --> `Got WER of 0.13547296055292085`
`bs=20` --> `Got WER of 0.13547296055292085`
