### ISSUE TITLE
FastSpeech2_HiFiGAN_E2E training doesn't work

### ISSUE THREAD

**Issue by mabraham** [NVIDIA/NeMo#3360]
**Describe the bug**

The class for training FastSpeech2_HiFiGAN end-to-end model uses variables that aren't present in the core NeMo classes, so the python errors out before training begins.

**Steps/Code to reproduce bug**

Try training such a model using NeMo 1.5.1

**Expected behavior**

A model can be trained

**Comment by blisc** [comment]
Can you post the full error log?

**Comment by mabraham** [comment]
No, sorry. I'm on parental leave.

**Comment by redoctopus** [comment]
The fixes in #3508 should resolve training errors, please reopen if you're still running into issues.
