### ISSUE TITLE
How to export ConformerCTC to ONNX format to run in C ++? 

### ISSUE THREAD

**Issue by Alexey322** [NVIDIA/NeMo#3367]
Hello.

Please tell me how can I export the ConformerCTC model to ONNX format to run from C ++? If I understand correctly, the spectrograms required for the model can only be obtained using the classes built into NeMo.

**Comment by borisfom** [comment]
You can use scripts/export.py script to produce .onnx file from your .nemo model. Yes the exported ONNX will only contain the neural net part (no featurizer). You can either use standalone Python featurizer from Nemo, or use one of available open source C++ featurizers,  or write your own.
