### ISSUE TITLE
ASR Tutorial | ASR_with_Nemo | from_pretrained not defined.

### ISSUE THREAD

**Issue by chaksam** [NVIDIA/NeMo#3369]
I am trying the tutorial ASR_with_NeMo.ipynb. It's giving me following error. I checked the code for EncDecCTCModel, it doesn't contain the function "from_pretrained". How to load the pre-trained models:
I even tried to use restore_from after downloading the respective *.nemo file. But getting same issue there as well (_'EncDecCTCModel' has no attribute 'restore_from'_)

**# This line will download pre-trained QuartzNet15x5 model from NVIDIA's NGC cloud and instantiate it for you
quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En")**

Error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_349758/1493780281.py in <module>
      1 # This line will download pre-trained QuartzNet15x5 model from NVIDIA's NGC cloud and instantiate it for you
----> 2 quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En")

**AttributeError: type object 'EncDecCTCModel' has no attribute 'from_pretrained'**

**Comment by titu1994** [comment]
Did you follow all the cells for instalation ? Do other models fail to restore as well ? This usually happens if you use an incorrect model type to try to restore the model. Make sure EncDecCTCModel.list_available_models() has the model name you want to load.

**Comment by titu1994** [comment]
It probably stems from incorrect Nemo installation as well, did you install the extra requirements such as Cython from https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation

**Comment by chaksam** [comment]
> It probably stems from incorrect Nemo installation as well, did you install the extra requirements such as Cython from https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation

Yes, this resolved the issue. Some of the requirements were not getting satisfied. After installing those, it worked fine.
