### ISSUE TITLE
shape mismatch while loading my pretrained model

### ISSUE THREAD

**Issue by BenoitWang** [NVIDIA/NeMo#3370]
Hi, 

I trained a corformer CTC BPE model with 8k wav data, but when I tried to load the model for decoding with 
`asr_model = nemo_asr.models.ASRModel.restore_from(nemo_model_file)` I got this shape mismatch error 
![image](https://user-images.githubusercontent.com/41187612/147249585-2c748058-b9b8-4cfc-bee6-0ef59574e5f4.png)
I don't want to train another model with 16k data, is there a way that I load this pretrained model please ?

**Comment by titu1994** [comment]
Depends on what the model config was during training - you can extract the models current config using `old_cfg = restore_from(..., return_config=True)`, make the necessary changes to the config required to correctly load the model then restore the model with `restore_from(..., override_config_path=updated_cfg)` where updated_cfg is an omegaconf config with the changes necessary. 

See documentation for these two flags at https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/core/core.html#nemo.core.ModelPT.restore_from

**Comment by titu1994** [comment]
It seems your preprocessor when restoring is different from when you were training - the window during training was 400 now it's 200. So look into what changed there. 

Also after you restore from using the override, make sure to save_to() in order to have correct Nemo file

**Comment by BenoitWang** [comment]
Hi, thanks a lot for the response
