### ISSUE TITLE
[Question] save ASR model config

### ISSUE THREAD

**Issue by ahkarami** [NVIDIA/NeMo#3373]
Hi,
1- Would you please help me how I can save the config (`cfg`) of an ASR model as a yaml file? (_i.e.,_ load a trained asr `.nemo` model file and save its cfg as a yaml file)
2- Another question is that, when I follow your [`ASR_CTC_Language_Finetuning`](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/ASR_CTC_Language_Finetuning.ipynb) tutorial, then the `hparams.yaml` file which is saved in the experiments folder, seems related to the previous checkpoint of the model (I mean it is not updated according to my cfg modifications). So, I want to save its modified `hparams.yaml` file according to my new changes. How can I do that? 
Best

**Comment by titu1994** [comment]
(1) - cfg = ModelPT.restore_from(filepath, return_config=True)
OmegaConf.save(cfg, filepath.yaml)

(2) hparams.yaml is a copy of the models internal config. If you update the model and or it's config you need to do model.cfg = updated_cfg to update the internal model config that gets saved by pytorch lightning

**Comment by ahkarami** [comment]
Thank you very much.
