### ISSUE TITLE
How does MarbleNet compares with silero-vad

### ISSUE THREAD

**Issue by seekingdeep** [NVIDIA/NeMo#3389]
Hi there
@fayejf @titu1994 @borisgin 

i am interested in knowing your thoughts and comparison between MarbleNet and silero-vad on cpu-only devices.

**Comment by okuchaiev** [comment]
this doesn't look like a NeMo issue. Feel free to start a discussion instead

**Comment by fayejf** [comment]
@seekingdeep Thanks for your question. 

We haven't compared with silero-vad yet. And we will be releasing a new MarbleNet checkpoint soon which is trained with more data and augmentation. Feel free to compare with other methods yourself. If you have more questions, feel free to post in the Discussions section or email us. Thanks!
