### ISSUE TITLE
Where is the 1.6.0rc0 version ?

### ISSUE THREAD

**Issue by jzoker** [NVIDIA/NeMo#3391]
my coworker could install it last week, but now i don't see this version anymore?

**Comment by ericharper** [comment]
We haven't released 1.6.0 yet. Maybe it was a different version?

**Comment by ShantanuNair** [comment]
@ericharper I seem to have 1.6.0rc0 as well on my dev env.
A quick check of which version I had installed.
```
>>> import nemo
>>> nemo.__version__
'1.6.0rc0'
>>>
```

**Comment by titu1994** [comment]
That's the main branch. That won't be cut into a release branch until the end of the month.
