### ISSUE TITLE
[Question] about Speech Data Explorer (SDE) Tool

### ISSUE THREAD

**Issue by ahkarami** [NVIDIA/NeMo#3395]
Hi,
The Speech Data Explorer (SDE) tool is really a great tool for error analysis. I have some questions about it:
1- What is `Vocabulary size` exactly mean in SDE? Is it unique words separated by space in the manifest? (because when I have tested SDE with QuartzNet & Citrinet (with bpe tokenizer) models its vocabulary size have been changed!!)  
2- What does `Score` means in SDE? 
3- In the last plot of SDE (_e.g._, the last plot in `statistics` section of  http://18.223.252.228:8050/) what does `sometimes recognized` exactly means? It means these words recognition accuracy is greater than zero and less than 100%?
4- How one can save or export tables in SDE for example as a csv file (excel file)? Also if one can save them after applying a filter it would be great. 
5- After running the SDE for a manifest according to the predicted results of an ASR model, is there any systematic approach for analyzing and detecting the common errors of the ASR model and address them? In other words, how one can improve the accuracy of an ASR model by using the SDE tool? Is there any paper/tutorial in this area? 
Best

**Comment by vsl9** [comment]
Hi, thanks for your interest in SDE.

1. `Vocabulary size` is a number of unique words in dataset's reference transcripts (`'text'` field in JSON manifest file). Word is defined as a sequence of characters separated by space character. `Vocabulary size` should not depend on ASR model, it is an dataset specific attribute (like `Alphabet size`).

2. `Score` in SDE's demo instance is a segmentation confidence score. Demo instance has a re-segmented LibriSpeech dataset. `Score` comes from CTC Segmentation tool. More detail on this re-segmentation experiment can be found in the Appendix of the following paper: https://openreview.net/forum?id=oJ0oHQtAld (it is in Supplementary Material's zip archive).

3. Right, a word might have _N_ instances in a dataset, and ASR model might transcribe the word correctly in _M_ cases. If _M_=0, then the word goes in `Unrecognized` category (accuracy=0%). If 0<_M_<_N_, then the word considered `Sometimes recognized` (0<accuracy<100%). If _M_=_N_, then the word is recognized in all cases (`Always recognized`, accuracy=100%).

4. We actually never considered option to export to CSV (and Excel). It is certainly doable, though. What would be your use case for that? SDE provides interactive exploration and most important visualization plots. Excel might be used similarly but one drawback with Excel is lack of audio support (playing audio clips and plotting audio signal in time and frequency domains).

5. We have a paper demonstrating data analysis techniques for Mozilla Common Voice and Multilingual LibriSpeech: https://openreview.net/pdf?id=oJ0oHQtAld (Section 4, Page 8). SDE helps to explore and analyze specific errors and to identify causes of these errors (if the dataset has errors in reference transcripts, or if ASR model makes errors). If specific type of ASR errors is identified, then the ASR model might be improved by re-training on updated train set. For example, it is easy to identify most frequent "always unrecognized" words (by sorting on number of instances and filtering on accuracy=0 the Vocabulary table). If exploration of individual samples confirms that the ASR model makes errors for these specific words, then it is worth to add these words into training dataset. If errors are related to text normalization (of numbers, for example), then it makes sense to update text normalization preprocessing.

**Comment by ahkarami** [comment]
@vsl9 
Thank you very much for the complete explanation. I have just some notes about my 4th question and your answer (adding a feature that enables saving/exporting SDE tables as a csv file):
In my case, for example, I want to specify all of the "always unrecognized" words which have been repeated more than 10 times in a data set, and save them (their list) as a csv file. Then, maybe I want to remove some of these words in the csv file (according to some characteristics of my data set and my target (e.g., I want to remove words that have less that 5 characters)). Because, for example, one can send this list (the result csv file of the SDE table after applying a custom filter) to an annotator for investigate these errors in their audio files and correct some transcripts according to a guideline sheet (which is prepared by a specialist data scientist). I know that, it is possible to do it easily via current SDE tool, but I think if you add an extra feature that can save tables (without filter and also after applying custom filters) it would be great (because in some cases sharing the produced SDE via annotators maybe hard and we can just send them the result of some tables and ask them to correct some errors according to these csv files). Then by using this feature, producing reports from SDE would also be better. 
Best

**Comment by ahkarami** [comment]
Dear @vsl9 
The above requested feature has been added in the last update (version 1.7.0). Thank you very much for your consideration, and the great SDE tool. 
Best
