### ISSUE TITLE
Download pre-trained Fastspeech2 Hifigan E2E fail

### ISSUE THREAD

**Issue by LeeYangseung** [NVIDIA/NeMo#3401]
hello, thanks for your great job.

I tried to download pre-trained model of Fastspeech2 Hifigan E2E.
but, browser download doesn't working and wget too.

I attach the wget log below

wget --content-disposition https://api.ngc.nvidia.com/v2/models/nvidia/nemo/tts_en_e2e_fastspeech2hifigan/versions/1.0.0/zip -O tts_en_e2e_fastspeech2hifigan_1.0.0.zip
--2022-01-07 17:17:54--  https://api.ngc.nvidia.com/v2/models/nvidia/nemo/tts_en_e2e_fastspeech2hifigan/versions/1.0.0/zip
Resolving api.ngc.nvidia.com (api.ngc.nvidia.com)... 52.38.144.30, 35.165.139.54
Connecting to api.ngc.nvidia.com (api.ngc.nvidia.com)|52.38.144.30|:443... connected.
HTTP request sent, awaiting response... 404 
2022-01-07 17:18:00 ERROR 404: (no description).

Thank you.

**Comment by redoctopus** [comment]
It looks like the command to access the zipped file is not working, but can you try this command for now to get the .nemo file?
`wget https://api.ngc.nvidia.com/v2/models/nvidia/nemo/tts_en_e2e_fastspeech2hifigan/versions/1.0.0/files/tts_en_e2e_fastspeech2hifigan.nemo`

**Comment by okuchaiev** [comment]
Closing. see solution above. Re-open if issue is still relevant.
