### ISSUE TITLE
RAD-TTS

### ISSUE THREAD

**Issue by Nikuson123** [NVIDIA/NeMo#3409]
Why didn't I find RAD-TTS in NeMo?
He seemed to be there

Thanks in advance

**Comment by okuchaiev** [comment]
This is currently WIP https://github.com/NVIDIA/NeMo/pull/3516

**Comment by Nikuson123** [comment]
Something from #3516 can already work?

**Comment by okuchaiev** [comment]
This is the current PR: https://github.com/NVIDIA/NeMo/pull/3860

**Comment by nikuson** [comment]
this PR was closed again

**Comment by entn-at** [comment]
RAD-TTS source code appears to have been published separately: https://github.com/NVIDIA/radtts
