### ISSUE TITLE
Can we use NeMo in Windows10?

### ISSUE THREAD

**Issue by alexvaca0** [NVIDIA/NeMo#3449]
Hi, in the installation guidelines I see Linux commands are used; would it be possible to use NeMo on Windows? This would enable users to use it together with other NVIDIA technology such as the libraries in NVIDIA OMNIVERSE which are only available on Windows. Thank you in advance. 
@yzhang123

**Comment by titu1994** [comment]
Nemo on it's own does not support windows, however you can use WSL 2 to run Nemo with GPUs easily.

**Comment by alexvaca0** [comment]
Could you recommend me a tutorial or blog on how to use WSL2? I would definitely love to learn how to use that, when Ive read about it I could not really understand what it is and how to use it. 
Thanks a lot ! 😊

**Comment by titu1994** [comment]
Here is a recently updated walkthrough of cuda + WSL - https://docs.nvidia.com/cuda/wsl-user-guide/index.html

It requires Windows 10 + Insider Program or Windows 11 though.

**Comment by profK** [comment]
Having just gone through this pain, let me suggest Singualrity as your NeMO Contaienr engine.

Singularity is a LOT easier to set up and use than docker.  You get gpu support with just the -nv flag on your run commenad.
