### ISSUE TITLE
TypeError: Can't instantiate abstract class AudioDataLayer with abstract methods create_ports

### ISSUE THREAD

**Issue by MiKueen** [NVIDIA/NeMo#345]
Hi!
I cloned NeMo repo and followed the documentation for using Nemo.
However, I get TypeError when I try to run examples/asr/notebooks/2_Online_ASR_Microphone_Demo.ipynb
![image](https://user-images.githubusercontent.com/32016164/74144384-a3449000-4c22-11ea-87ac-1546bdabd302.png)

I saw a similar issue #246, and used the solution mentioned in the issue. But I still get the same error.
How do I resolve this?
Please help!

**Comment by okuchaiev** [comment]
Looks like you are somehow mixing master branch with 0.9 version.
The latest stable version is 0.9 (and docs and pip correspond to it). Could you please switch to 0.9 version and try again. If you want it from GitHub, the release is here: https://github.com/NVIDIA/NeMo/tree/v0.9.0

**Comment by MiKueen** [comment]
Yes when I checked out v0.9.0, I somehow merged it with the master branch. Later resolved it by cloning from latest release using git clone https://github.com/NVIDIA/NeMo.git -- branch v0.9.0, and as the latest version doesn't contain that notebook, the issue is resolved.
Thank you!
