### ISSUE TITLE
UnicodeEncodeError when deploying Nemo Text Normalization on Triton Inference Server

### ISSUE THREAD

**Issue by xuanbinh-nguyen96** [NVIDIA/NeMo#3452]
**Describe the bug**

I have a problem when deloy Text Nemo Text Normarlzation on Triton Inference Server. The Normalizer can not load the default "whitelist.tsv" file. Whenever I run ```tritonserver --model-repository models/```, the bug will appear.

```python
from nemo_text_processing.text_normalization.normalize import Normalizer
normalizer = Normalizer(input_case='cased', lang='en')
```
Results:
```bash
Internal: UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 150: ordinal not in range(128)

At:
  /usr/lib/python3.8/encodings/ascii.py(26): decode
  /usr/local/lib/python3.8/dist-packages/nemo_text_processing/text_normalization/en/utils.py(41): load_labels
  /usr/local/lib/python3.8/dist-packages/nemo_text_processing/text_normalization/en/taggers/whitelist.py(49): _get_whitelist_graph
  /usr/local/lib/python3.8/dist-packages/nemo_text_processing/text_normalization/en/taggers/whitelist.py(64): __init__
  /usr/local/lib/python3.8/dist-packages/nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify.py(107): __init__
  /usr/local/lib/python3.8/dist-packages/nemo_text_processing/text_normalization/normalize.py(76): __init__

```
**Environment overview (please complete the following information)**

 - Environment: Triton Inference Server 21.10
 - Method of NeMo install: pip install nemo_toolkit['all']

**Additional context**

**There is no problem when I test this code without Triton Inference Server!**.

**Comment by yzhang123** [comment]
@borisfom  could you take a look at this? I'm not familiar with Triton

**Comment by VahidooX** [comment]
Would you please try running your code with "export PYTHONIOENCODING=utf8"?

**Comment by xuanbinh-nguyen96** [comment]
> Would you please try running your code with "export PYTHONIOENCODING=utf8"?

I tried "export PYTHONIOENCODING="utf-8" but the problem is not solved.

**Comment by titu1994** [comment]
Next can you try LC_ALL="en_US.UTF-8" before script call

**Comment by xuanbinh-nguyen96** [comment]
I tried fixing the "load labels(abs_path)" function in the "nemo_text_processing/text normalization/en/utils.py" file at the line 40.

```label_tsv = open(abs_path)``` >>> ```label_tsv = open(abs_path, encoding='utf-8')```

And the problem was solved.
I know it's not a good idea to do this with libraries that have been installed directly through pip. I hope that this can be fixed in future updates.
