### ISSUE TITLE
Fine-tune stt conformer transducer EncDecRNNTBPEModel model

### ISSUE THREAD

**Issue by Omarnabk** [NVIDIA/NeMo#3453]
I'm trying to fine-tine stt_en_conformer_transducer_large model on a custom dataset of 300H. I have a problem with setting up the training configuration. 

In [this ](https://github.com/NVIDIA/NeMo/blob/8c912f515a77efb0e16b1433030da23e488960d5/tutorials/asr/ASR_with_Transducers.ipynb) example you reported how to train a model from scratch, but I understood from the model card (https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_transducer_small) that we can fine-tune it.

I tried to load the model, extract the config file, modify it and re-assign it to the mode, but did not work.

Here is what I did:

# Loading the model
```
import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecRNNTBPEModel.from_pretrained(model_name="stt_en_conformer_transducer_large", map_location='cpu')
```

# Loading the model configurations:
```
import copy
from omegaconf import DictConfig

modelConfig = DictConfig(asr_model.cfg)
modelConfig

```

Set the training data:

```
modelConfig['train_ds']['manifest_filepath'] = TRAIN_MANIFEST
modelConfig['validation_ds']['manifest_filepath'] = TEST_MANIFEST
```

Assigned it to the model:
`asr_model.setup_training_data(modelConfig['train_ds'])`

Here is the error I get:

```
[NeMo I 2022-01-18 18:44:40 collections:173] Dataset loaded with 1503 files totalling 2.81 hours
[NeMo I 2022-01-18 18:44:40 collections:174] 0 files were filtered totalling 0.00 hours
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_3295870/3465286351.py in <module>
----> 1 asr_model.setup_training_data(modelConfig['train_ds'])

~/anaconda3/envs/nemo/lib/python3.7/site-packages/nemo/collections/asr/models/rnnt_models.py in setup_training_data(self, train_data_config)
    499             # If it's an int, we assume that the user has set it to something sane, i.e. <= # training batches,
    500             # and don't change it. Otherwise, adjust batches accordingly if it's a float (including 1.0).
--> 501             if isinstance(self._trainer.limit_train_batches, float):
    502                 self._trainer.limit_train_batches = int(
    503                     self._trainer.limit_train_batches

AttributeError: 'NoneType' object has no attribute 'limit_train_batches'
```

Thanks!

**Comment by titu1994** [comment]
You need to create a Trainer from PTL right after creating a Model, then assign that trainer to the model via model.set_trainer(trainer). 

After that, also print out the dataloader config to see if it corresponds to your case - we can train model with bucketing or with tarred dataset so those flags should be set to None if they present. 

Following the steps of the fine tuning tutorial for CTC will be more useful, most of the concepts transfer to RNNT as well.

**Comment by Omarnabk** [comment]
Many thanks, @titu1994 

It's working now, but I still have a couple of doubts. I'm fine-tuning stt_en_conformer_transducer_small for the English language but with customized terms and vocabulary (medical terms).  Should I build a customized **tokenizer**?

I uploaded my code here (https://gist.github.com/Omarnabk/b75f8daf8d7123fe6ebd636457dcc385), 

Can you take a look if everything is Ok?

**Comment by titu1994** [comment]
You build tokenizer if the grammar is inadequate - if medical terms can be described in lower case 26 character of English + space + apostrophe - then no need to make new tokenizer. If it cannot, and you need special terms like # or $ or %, then build tokenizer (note: we do not recommend to make ASR try and emit special characters, instead use text normalization and Inverse text normalization to handle this).

**Comment by Omarnabk** [comment]
My Vocab is only English 26 letters, space and apostrophe. 
Many thanks!

**Comment by titu1994** [comment]
Don't monitor val_loss in early checkpointing, use val_wer - your loss may be higher but wer still lower than before for ASR. Mode remains min. Use longer patience, like 10 epochs. 

Follow the order
Create model
Set trainer
Change vocab (if needed)
Get model config as cfg
Update cfg with dataset args.
Use setup methods to load dataloader 
Model.cfg = cfg
Train model.

**Comment by titu1994** [comment]
Otherwise seems fine. You need to train a lot longer though than 2 epochs.

**Comment by Omarnabk** [comment]
While fine-tuning the model on my dataset, the code prints some prediction examples. 

 It printed one of my clear samples incorrectly, with 4 mistakes in one sentence. However, before fine-tuning the model, it was predicting the audio perfectly without errors. Does that mean I have a problem with my dataset?

**Comment by titu1994** [comment]
If your dataset is too small, then yes I'd suggest freezing your encoder and training just the prediction net and joint.

**Comment by Omarnabk** [comment]
I did that test on a small dataset of 3H. However, my complete dataset is around 250H with different English accents. So, I will try to re-train on the full dataset and see how it goes.

**Comment by Omarnabk** [comment]
I think the problem was due to the LR, I did not change it in the sample above, it was set to five! I changed it to 0.001

Can you help with how to free the encoder?
