### ISSUE TITLE
User EncDecRNNTBPEModel with Beam Search

### ISSUE THREAD

**Issue by Omarnabk** [NVIDIA/NeMo#3456]
I am using a pre-trained  stt_en_conformer_transducer and it is doing well. However, since my dataset has some special terms I want to use KenLM with Beam Search.

In one tutorial, I saw that we can change the decoding strategy to Beam using: 

```
import copy
decoding_config = copy.deepcopy(asr_model.cfg.decoding) 
# Update the config for the decoding strategy
decoding_config.strategy = "beam"  # Options are `greedy`, `greedy_batch`, `beam`, `tsd` and `alsd`
decoding_config.beam.beam_size = 8  # Increase beam size for better scores, but it will take much longer for transcription !
asr_model.change_decoding_strategy(decoding_config)
asr_model.transcribe(['/home/wesam/wavs/X1.wav'], )

```

It works well, but I did not know how to feed it with my own Language Model?

**Comment by titu1994** [comment]
We currently do not support KenLM integration with RNNT, but maybe we can support it. @VahidooX maybe can comment here.

**Comment by VahidooX** [comment]
I would try to add the support of LM for Transducer models for the next release.

**Comment by Omarnabk** [comment]
That would be great!! @VahidooX

**Comment by Shellcat-Zero** [comment]
Was this implemented, or is there some other fix? Just wondering why the issue was closed.

I've noticed that there does not seem to be a way to set `logprobs=True` for EncDecRNNTBPEModel models.

**Comment by VahidooX** [comment]
We are still experimenting with LM support for Transducer models. The improvements we are getting are small for now. Usually, Transducer models are already good without LM. It may take one month or so to add this feature to the main branch.

**Comment by VahidooX** [comment]
Do we support diarization with Transducer models? if yes, do they need LM for Transducer models to it? @fayejf @tango4j
