### ISSUE TITLE
Tesla K80  compatibility 

### ISSUE THREAD

**Issue by cri5Castro** [NVIDIA/NeMo#346]
hi there i'm working on a ASR system using nemo unfortunatly i can't figure out how to make it work whit a Tesla K80 , i'm working on a aws p2 large instance , currently trying to run with the docker images provided by the official release, let mw know if there is any docker image compatible with  tesla k80 or which exactly versions of pytorch and libraries will work

**Comment by borisgin** [comment]
K80 doesn't support float16. Have you tried  to run it in float32 ("O0")?

**Comment by cri5Castro** [comment]
thanks for the reply , not really i'm following this recipe but can't figure oput how to use float32 as default https://github.com/NVIDIA/NeMo/blob/master/examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb

**Comment by cri5Castro** [comment]
when i run my code with the official nemo docker image i got this error
```
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

 also i got the  following error message 
```
ERROR: Detected NVIDIA Tesla K80 GPU, which is not supported by this container
ERROR: No supported GPU(s) detected to run this container
```

**Comment by okuchaiev** [comment]
The errors above look like they aren't NeMo related. Before trying NeMo on K80, make use you have Pytorch running on GPUs.

(1) Please run on bare metal + CUDA + Pytorch or on container which supports K80
(2) Like @borisgin mentioned above, K80 does not support float16, so you should set optimization_level=Optimization.mxprO0 (which is actually a default) in nemo.core.neural_factory.NeuralModuleFactory

**Comment by cri5Castro** [comment]
thanks for the feedback I've just use the  " pytorch/pytorch:1.2-cuda10.0-cudnn7-runtime"  container and install nemo-toolkit and nemo-asr in that container and it works ,of course without float16 support or distribuited training (I'll switch to a better config after prototyping )

**Comment by jonathan-cohen-nvidia** [comment]
I highly recommend you try to G2 instances with NVIDIA T4 gpus. They will work great out of the box - better than the old K80s.
