### ISSUE TITLE
nemo2riva BUG

### ISSUE THREAD

**Issue by ZhengHui-Z** [NVIDIA/NeMo#3462]
**Describe the bug**

Error when converting Nemo model to Riva

**Steps/Code to reproduce bug**

Shell command: 

`nemo2riva --out /mnt/devdata/zzh/tao/results/Citrinet/stt_zh_citrinet_512.riva /mnt/devdata/zzh/tao/results/Citrinet/stt_zh_citrinet_512.nemo
`

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: ubuntu18.04
- Python version: 3.8
- nemo2riva: Downloaded from riva_quickstart_v1.8.0-beta/nemo2riva-1.8.0b0-py3-none-any.whl
- stt_zh_citrinet_512.nemo: curl -LO https://api.ngc.nvidia.com/v2/models/nvidia/nemo/stt_zh_citrinet_512/versions/1.0.0rc1/files/stt_zh_citrinet_512.nemo
**Additional context**

Error message: 

```
(riva) $ nemo2riva --out ./tao/results/Citrinet/stt_zh_citrinet_512.riva ./tao/results/Citrinet/stt_zh_citrinet_512.nemo
INFO: Logging level set to 20
INFO: Restoring NeMo model from '/mnt/devdata/zzh/tao/results/Citrinet/stt_zh_citrinet_512.nemo'
ERROR: Failed to restore model from NeMo file : /mnt/devdata/zzh/tao/results/Citrinet/stt_zh_citrinet_512.nemo. Please make sure you have the latest NeMo package installed with [all] dependencies.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/riva/bin/nemo2riva", line 8, in <module>
    sys.exit(nemo2riva())
  File "/home/user/miniconda3/envs/riva/lib/python3.8/site-packages/nemo2riva/cli/nemo2riva.py", line 50, in nemo2riva
    Nemo2Riva(args)
  File "/home/user/miniconda3/envs/riva/lib/python3.8/site-packages/nemo2riva/convert.py", line 41, in Nemo2Riva
    raise e
  File "/home/user/miniconda3/envs/riva/lib/python3.8/site-packages/nemo2riva/convert.py", line 34, in Nemo2Riva
    model = ModelPT.restore_from(restore_path=nemo_in)
AttributeError: type object 'ModelPT' has no attribute 'restore_from'

```

**Comment by titu1994** [comment]
How was Nemo itself installed ? You have to use the reinstall.sh script or follow the installation instructions in the GitHub with the ["all"] part.
