### ISSUE TITLE
Distributed Training

### ISSUE THREAD

**Issue by cri5Castro** [NVIDIA/NeMo#348]
hello, i wanted to know if is needed to run my training script under torch.distributed.launch module 
i.e:
```
python -m torch.distributed.launch --nproc_per_node=8 myscript.py--num_gpus=8 ...
```

or i just need to set the device_type to allGpus and the local rank to 8 
```
python  myscript.py  --num_gpus=8 ...
```

also i wanted to know what is the difference between local rank and global rank

**Comment by blisc** [comment]
You need to run the first command. local_rank refers to the rank on the local machine (eg local_rank 0 will have the 0th gpu on machine 0). global_rank refers the rank across all machines (eg global_rank 5 could have the 0th gpu on machine 1), etc.
