### ISSUE TITLE
num_samples is zero, but 1172 files were filtered

### ISSUE THREAD

**Issue by b5y** [NVIDIA/NeMo#3483]
**Describe the bug**

I am getting this error when I try to instantiate ASR model (following [this](https://github.com/NVIDIA/NeMo/blob/v1.0.0/tutorials/asr/01_ASR_with_NeMo.ipynb) tutorial):

`ValueError: num_samples should be a positive integer value, but got num_samples=0`

But it's quite strange because I am getting these logs during the run:

```
[NeMo I 2022-01-21 11:37:29 audio_to_text_dataset:38] Model level config does not container `sample_rate`, please explicitly provide `sample_rate` to the dataloaders.

[NeMo I 2022-01-21 11:37:29 audio_to_text_dataset:38] Model level config does not container `labels`, please explicitly provide `labels` to the dataloaders.

[NeMo I 2022-01-21 11:37:29 collections:173] Dataset loaded with 0 files totalling 0.00 hours

[NeMo I 2022-01-21 11:37:29 collections:174] 1172 files were filtered totalling 347.43 hours
```

Which shows correct number of files (`1172`) in training dataset.

**Steps/Code to reproduce bug**

```python
trainer = pl.Trainer(gpus=1, max_epochs=50)

train_manifest = './<folder_name>/manifests/train_manifest.json'
test_manifest = './<folder_name>/manifests/test_manifest.json'

params['model']['train_ds']['manifest_filepath'] = train_manifest
params['model']['validation_ds']['manifest_filepath'] = test_manifest

first_asr_model = nemo_asr.models.EncDecCTCModel(cfg=DictConfig(params['model']), trainer=trainer)
```

I have tried to put full path for `train_manifest` and `test_manifest` (`/home/ubuntu/<folder_name>/manifests`), but it didn't help at all.

**Expected behavior**

Running without errors.

**Environment overview (please complete the following information)**

 - Environment location: `Jupyter Notebook` in `AWS EC2` instance node
 - Method of NeMo install: `pip install nemo_toolkit[all]`

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 20.04.3 LTS
- PyTorch version: 1.10.1
- Python version: 3.8.12

**Additional context**
It doesn't seem that there are no files or the path to the `train` and `test` manifests are incorrect. Otherwise I couldn't open manifests via `pandas` (did this for checking purposes). The structure of the manifest looks like this:

`
{"audio_filepath": "/home/ubuntu/<folder_name>/audio/<audio_file_name>.wav", "duration": 1725.84, "text": "..."}
{"audio_filepath": "/home/ubuntu/<folder_name>/audio/<audio_file_name>.wav", "duration": 1725.84, "text": "..."}
`

where `<folder_name>` is the same as in the path for `train_manifest.json` and `test_manifest.json`.

**Comment by titu1994** [comment]
Audio files cannot be longer than 20 seconds during training. You should use segmentation tools to get single sentence audio clips of 20 seconds at maximum, and preferably around 15-18 seconds c

**Comment by titu1994** [comment]
All files were automatically filtered out by the config file which has an explicit upper limit to audio duration during training of 16.7 seconds for Librispeech and 20 seconds is our recommended upper bound c

**Comment by b5y** [comment]
Thanks for the quick reply!

Okay, now I understand the problem clearly.

What if there are not enough files which have 20 seconds length? In that case, how many files should be in the training dataset for getting a robust model?

**Comment by titu1994** [comment]
As much data as possible. As long as the audio segmentation is good (aka the audio is clipped at 15-20 second intervals, there is good correspondence to what was said and the text that is transcribed), it is good to add to the dataset. You can use the speech data explorer toolkit to analyse your segmented audio clips and see if the text corresponding to the audio is correct. You can also use the CTC segmentation tool to generate audio segments (with some error) if you have the ground truth transcript.

**Comment by titu1994** [comment]
For example, Librispeech has roughly 92000 audio clips in it's train set, or 270000 audio clips if you use speed perturbation. The English models available via from_pretrained() are trained on even more data. However for a starting point about 50-100 hours of audio is good, and more always helps.

**Comment by itzsimpl** [comment]
Just for curiosity, any special reason for the 20s upper bound? I assume also that the less variation in file length, the better. Am I mistaken?

**Comment by titu1994** [comment]
You'll run out of gpu memory with anything above 20s, even at batch size 16 or 32

**Comment by itzsimpl** [comment]
Doesn't this depend on the amount of available GPU memory? I mean, I guess there's a difference in say a 6BG 3060RTX and an 80GB A100? I would assume that with 80GB one would be capable of working with larger wave files, but still in small batches? Am I mistaken? But is there any gain in it? 

Sometimes the speakers speak fast and rarely take a breath, hence it is really hard to segment. Going for the 20s mark could potentially have the pronunciation of the last word clipped. How much will such clipping affect the training result?

**Comment by titu1994** [comment]
It will affect training quite a bit since there's no audio corresponding to the text. Even with 80 GB, with the largest Citrinet model, and amp enabled, we can usually achieve batch sizes of 200 or so with 20 second limit. Your audio durations are simply intractable.

**Comment by titu1994** [comment]
And it's doubly impossible for attention based models like Conformer. During training it's hard to push past 20 seconds. During inference it's not possible to go above 5 minutes of audio with Conformers. So segmentation is a must. You can look into external tools to do segmentation as well.

**Comment by itzsimpl** [comment]
Thank you for the clarification. Apart from the CTC segmentation tool, any pointers on good external ones?

**Comment by titu1994** [comment]
Nemo CTC segmentation is one. Others from this list - https://github.com/pettarin/forced-alignment-tools/blob/master/README.md - MFA, Kaldi, Gentle are useful. Or you can use Mozilla DS Align https://github.com/mozilla/DSAlign

**Comment by itzsimpl** [comment]
Thank you!
