### ISSUE TITLE
Always get RuntimeError: CUDA out of memory. Tried to allocate XX.XX MiB

### ISSUE THREAD

**Issue by davidmartinrius** [NVIDIA/NeMo#3493]
**Describe the bug**
I am trying to train a TTS model. I followed the steps of the documentation but still cannot train the model.
I always get RuntimeError: Cuda out of memory. So the program crash.

**Steps/Code to reproduce bug**

The way to reproduce the error is to execute this command from the console in a linux:
python3 tacotron2.py sample_rate=22050 train_dataset=files.json validation_datasets=files.json trainer.max_epochs=1 trainer.accelerator=null trainer.check_val_every_n_epoch=1

The file tacotron2.py is the next:
https://github.com/NVIDIA/NeMo/blob/main/examples/tts/tacotron2.py

The config file for tacotron2.py is https://github.com/NVIDIA/NeMo/blob/main/examples/tts/conf/tacotron2.yaml

I edited tacotron2.yaml in my computer to reduce the batch_size and num_workers
The values are:
batch_size=1
num_workers=1

So, I reduced the batch_size to the minium to try to avoid the cuda error with No success.

The file "files.json":
I started with 100.000 lines. Each line like this: (I mean the file is written as explained in the documentation)
{"audio_filepath": "4da6b70e-0108-4f75-80ae-3d71f1dd2c2b.wav", "text": "y aquí en dos palotadas hemos encontrado robustas columnas donde apoyar la grandiosa fábrica de su alcurnia", "duration": 6.84}

I tried to train the model reducing the number of lines. I Started with 100000. Then I reduced to the file "files.json" to only 100. Unfortunately, it crashed as well..

**Expected behavior**

I would like to find a way to train a TTS model managing properly the GPU memory.

**Environment overview**

Computer: MSI Apache Pro GE70 - 2PE
Operating system: Ubuntu 20.04.3 LTS
GPU: NVIDIA GTX 860 (2GB)
nemo-toolkit                  1.5.1               
pytorch-lightning             1.5.7               
torch                         1.10.1              
torch-stft                    0.1.4               
torchaudio                    0.10.1+cu102        
torchmetrics                  0.6.2               
torchvision                   0.11.2+cu102   

Could you help me to solve it?

Thank you!

**Comment by davidmartinrius** [comment]
In this comment I add all the stacktrace I get in the console.

python3 tacotron2.py sample_rate=22050 train_dataset=/home/pc/Downloads/first100.json validation_datasets=/home/pc/Downloads/first100.json trainer.max_epochs=1 trainer.accelerator=null trainer.check_val_every_n_epoch=1 
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

[NeMo W 2022-01-22 22:42:15 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/callback_connector.py:147: LightningDeprecationWarning: Setting `Trainer(checkpoint_callback=False)` is deprecated in v1.5 and will be removed in v1.7. Please consider using `Trainer(enable_checkpointing=False)`.
      rank_zero_deprecation(
    
GPU available: True, used: True
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
IPU available: False, using: 0 IPUs
[NeMo W 2022-01-22 22:42:15 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:59: LightningDeprecationWarning: Setting `Trainer(flush_logs_every_n_steps=1000)` is deprecated in v1.5 and will be removed in v1.7. Please configure flushing in the logger instead.
      rank_zero_deprecation(
    
[NeMo I 2022-01-22 22:42:15 exp_manager:280] Experiments will be logged at /home/pc/Downloads/nemo_experiments/Tacotron2/2022-01-22_22-42-15
[NeMo I 2022-01-22 22:42:15 exp_manager:635] TensorboardLogger has been set up
[NeMo W 2022-01-22 22:42:15 exp_manager:866] The checkpoint callback was told to monitor a validation value and trainer's max_steps was set to -1. Please ensure that max_steps will run for at least 1 epochs to ensure that checkpointing will not error out.
[NeMo W 2022-01-22 22:42:15 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:243: LightningDeprecationWarning: `ModelCheckpoint(every_n_val_epochs)` is deprecated in v1.4 and will be removed in v1.6. Please use `every_n_epochs` instead.
      rank_zero_deprecation(
    
[NeMo I 2022-01-22 22:42:15 collections:173] Dataset loaded with 100 files totalling 0.11 hours
[NeMo I 2022-01-22 22:42:15 collections:174] 0 files were filtered totalling 0.00 hours
[NeMo I 2022-01-22 22:42:15 collections:173] Dataset loaded with 100 files totalling 0.11 hours
[NeMo I 2022-01-22 22:42:15 collections:174] 0 files were filtered totalling 0.00 hours
[NeMo I 2022-01-22 22:42:15 features:265] PADDING: 16
[NeMo I 2022-01-22 22:42:15 features:282] STFT using torch
[NeMo W 2022-01-22 22:42:16 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:291: LightningDeprecationWarning: Base `Callback.on_train_batch_start` hook signature has changed in v1.5. The `dataloader_idx` argument will be removed in v1.7.
      rank_zero_deprecation(
    
[NeMo W 2022-01-22 22:42:16 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:291: LightningDeprecationWarning: Base `Callback.on_train_batch_end` hook signature has changed in v1.5. The `dataloader_idx` argument will be removed in v1.7.
      rank_zero_deprecation(
    
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[NeMo W 2022-01-22 22:42:18 modelPT:470] The lightning trainer received accelerator: <pytorch_lightning.accelerators.gpu.GPUAccelerator object at 0x7fe547409c40>. We recommend to use 'ddp' instead.
[NeMo I 2022-01-22 22:42:18 modelPT:561] Optimizer config = Adam (
    Parameter Group 0
        amsgrad: False
        betas: (0.9, 0.999)
        eps: 1e-08
        lr: 0.001
        weight_decay: 1e-06
    )
[NeMo I 2022-01-22 22:42:18 lr_scheduler:748] Scheduler "<nemo.core.optim.lr_scheduler.CosineAnnealing object at 0x7fe541097fa0>" 
    will be used during training (effective maximum steps = 100) - 
    Parameters : 
    (min_lr: 1.0e-05
    max_steps: 100
    )

  | Name                       | Type               | Params
------------------------------------------------------------------
0 | audio_to_melspec_precessor | FilterbankFeatures | 0     
1 | text_embedding             | Embedding          | 35.8 K
2 | encoder                    | Encoder            | 5.5 M 
3 | decoder                    | Decoder            | 18.3 M
4 | postnet                    | Postnet            | 4.3 M 
5 | loss                       | Tacotron2Loss      | 0     
------------------------------------------------------------------
28.2 M    Trainable params
0         Non-trainable params
28.2 M    Total params
112.613   Total estimated model params size (MB)

  | Name                       | Type               | Params
------------------------------------------------------------------
0 | audio_to_melspec_precessor | FilterbankFeatures | 0     
1 | text_embedding             | Embedding          | 35.8 K
2 | encoder                    | Encoder            | 5.5 M 
3 | decoder                    | Decoder            | 18.3 M
4 | postnet                    | Postnet            | 4.3 M 
5 | loss                       | Tacotron2Loss      | 0     
------------------------------------------------------------------
28.2 M    Trainable params
0         Non-trainable params
28.2 M    Total params
112.613   Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s][NeMo W 2022-01-22 22:42:18 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:116: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
      rank_zero_warn(
    
Validation sanity check:   0%|                                                                                                                                                       | 0/2 [00:00<?, ?it/s][NeMo W 2022-01-22 22:42:19 patch_utils:49] torch.stft() signature has been updated for PyTorch 1.7+
    Please update PyTorch to remain compatible with later versions of NeMo.
[NeMo W 2022-01-22 22:42:21 tacotron2:341] Reached max decoder steps 1000.
Validation sanity check:  50%|███████████████████████████████████████████████████████████████████████▌                                                                       | 1/2 [00:02<00:02,  2.86s/it][NeMo W 2022-01-22 22:42:23 tacotron2:341] Reached max decoder steps 1000.
[NeMo W 2022-01-22 22:42:24 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:116: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 8 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
      rank_zero_warn(
    
[NeMo W 2022-01-22 22:42:24 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:412: UserWarning: The number of training samples (100) is smaller than the logging interval Trainer(log_every_n_steps=200). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
      rank_zero_warn(
    
Epoch 0:   0%|                                                                                                                                                                     | 0/200 [00:00<?, ?it/s][NeMo W 2022-01-22 22:42:25 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/closure.py:35: LightningDeprecationWarning: One of the returned values {'progress_bar'} has a `grad_fn`. We will detach it automatically but this behaviour will change in v1.6. Please detach it manually: `return {'loss': ..., 'something': something.detach()}`
      rank_zero_deprecation(
    
Epoch 0:  16%|█████████████████████▎                                                                                                               | 32/200 [01:17<06:47,  2.43s/it, loss=9.14, v_num=2-15]Error executing job with overrides: ['sample_rate=22050', 'train_dataset=/home/pc/Downloads/first100.json', 'validation_datasets=/home/pc/Downloads/first100.json', 'trainer.max_epochs=1', 'trainer.accelerator=null', 'trainer.check_val_every_n_epoch=1']
Traceback (most recent call last):
  File "tacotron2.py", line 53, in main
    trainer.fit(model)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 738, in fit
    self._call_and_handle_interrupt(
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 683, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 773, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1275, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1285, in run_stage
    return self._run_train()
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1315, in _run_train
    self.fit_loop.run()
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    lightning_module.optimizer_step(
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1652, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 164, in step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 336, in optimizer_step
    self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 163, in optimizer_step
    optimizer.step(closure=closure, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/optim/adam.py", line 92, in step
    loss = closure()
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 148, in _wrap_closure
    closure_result = closure()
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 155, in closure
    self._backward_fn(step_output.closure_loss)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 327, in backward_fn
    self.trainer.accelerator.backward(loss, optimizer, opt_idx)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 311, in backward
    self.precision_plugin.backward(self.lightning_module, closure_loss, *args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 91, in backward
    model.backward(closure_loss, optimizer, *args, **kwargs)
  File "/home/pc/.local/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1434, in backward
    loss.backward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 1.96 GiB total capacity; 832.17 MiB already allocated; 4.06 MiB free; 900.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by VahidooX** [comment]
How much RAM does your GPU have? 2GB?

**Comment by davidmartinrius** [comment]
> How much RAM does your GPU have? 2GB?

Yes.

GPU: NVIDIA GTX 860 (2GB)

**Comment by VahidooX** [comment]
2GB is very low and likely to be the reason. Make sure your GPU's memory is free before running the code by checking nvidia-smi.

**Comment by titu1994** [comment]
Since the GPU memory is low, you might want to work on colab for it's 8/16 GB GPUs

**Comment by davidmartinrius** [comment]
> Since the GPU memory is low, you might want to work on colab for it's 8/16 GB GPUs

I don't understand what you mean. 

Is possible to use a 2GB GPU to train a NeMo model?

I am using a clean installation of Ubuntu. I already checked nvidia-smi command. There is no other big process that use the gpu. Only the graphical environment of the operating system.
