### ISSUE TITLE
ITN: Assets not installed when pip install from source

### ISSUE THREAD

**Issue by liaeh** [NVIDIA/NeMo#3503]
**Describe the bug**

When installing nemo[all] via pip from source, some of the data files used to build the french ITN grammar are missing from site-packages (e.g. those in folders electronic, measurements, money, numbers, time). These folders are the only ones that are not packages i.e. missing `__init__.py` files.

**Steps/Code to reproduce bug**

`
python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]
ls /venv/nemo/lib/python3.9/site-packages/nemo_text_processing/inverse_text_normalization/fr/data/
`
> `fractions.tsv  __init__.py  months.tsv  ordinals  __pycache__  roman  whitelist.tsv`

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: venv on local machine
 - Method of NeMo install:
    `apt-get update && apt-get install -y libsndfile1 ffmpeg`
    `pip install Cython`
    `python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]`

**Environment details**

    OS version - Ubuntu 18.04.5 LTS
    PyTorch version - 1.10.1
    Python version - 3.8.11

**Comment by yzhang123** [comment]
fixed in https://github.com/NVIDIA/NeMo/pull/3505
