### ISSUE TITLE
Scripts for generating NeMo ASRSET and training base ASR models

### ISSUE THREAD

**Issue by sciai-ai** [NVIDIA/NeMo#3506]
Can you please share the Scripts for generating NeMo ASRSET and further training any ASR model, which includes several open source datasets for both wideband and telephony speech. 

Thanks

**Comment by titu1994** [comment]
Nemo ASR set is nearly 12000 hours of speech from various public datasets, I dont think we have published any cleaning script for this because each dataset requires adhoc processing to be normalized to the common format. Maybe @vsl9 knows more about it but I can't comment on if we will make the separate scripts public (since wedt rather not have adhoc scripts in Nemo repo itself)

**Comment by sciai-ai** [comment]
If there is some way you can share it would be great, I am trying to train a very large model and would like to include the nemo ASR set in the training data.

How do you unify telephony and wideband speech, is it as simple as just changing the sampling rate to 16 Khz or there is any other processing needed?

**Comment by titu1994** [comment]
Dunno about (1) and (3) but (2) yes possible to concatenate tarred datasets - https://github.com/NVIDIA/NeMo/blob/main/scripts/speech_recognition/convert_to_tarred_audio_dataset.py#L43-L54

Though it's not possible to share the Nemo ASRSet tarred dataset (it's several TB in size)

**Comment by titu1994** [comment]
Seems the datasets cannot be published as they are ad-hoc download steps and preprocessing steps for (1). For (3) - we upsample all audio files to 16 kHz and monochannel, even if origin is 8 kHz. This is the same recommendation as our tutorials. We use sox to preprocess the audio.

**Comment by sciai-ai** [comment]
@titu1994 The scripts seem to be there [https://github.com/NVIDIA/NeMo/tree/main/scripts/dataset_processing](url) but it doesnot look complete for 12K hours. Possible we can get the rest of the scripts for other datasets and a master script which then generated the Nemo ASRSet

**Comment by titu1994** [comment]
There are too many adhoc steps with and without scripts. I will ask the team but most probably we won't be releasing scripts to construct ASR set soon.

**Comment by vadimkantorov** [comment]
@titu1994 maybe even getting the file name/path lists public would be great!

**Comment by SatenHarutyunyan** [comment]
@titu1994  or just the names would be great too. In here it is said that the model is trained on publically availabale datasets.https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_fastconformer_hybrid_large_pc

**Comment by vadimkantorov** [comment]
> Though it's not possible to share the Nemo ASRSet tarred dataset (it's several TB in size)

@titu1994 it would be extremely beneficial to have a reasonably large dataset's filelist along with the configs (including any filtering / sampler or dataset reweighting params) for reproducibility and arch experimentation purposes. E.g. someone from community could retry the experiment using RoPE/Alibi for positional encoding in Conformer models to finally benefit from FlashAttention kernels, and then the metrics achieved on a large dataset would be convincing data point.
