### ISSUE TITLE
[BUG or INTENDED?] optim.sched vs optim and sched on same level

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/NeMo#3549]
Reading through https://github.com/NVIDIA/NeMo/blob/main/examples/tts/conf/hifigan/hifigan.yaml, I noticed that hifigan specifies the `optim` and `sched` on the same level, on quick check in other config files the `sched` is a sub parameter of `optim`. Any special reason?

Checking out the docs https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/core/core.html?highlight=scheduler#optimization, https://github.com/NVIDIA/NeMo/blob/main/docs/source/core/core.rst#optimization, I notice that it is quite misleading. It is not evident which version is the correct one.

**Comment by titu1994** [comment]
Some TTS models dont require automatic customization, therefore they may chose to override the configure_optimizers() section. I suppose this is one such (valid) case. By default for most nemo models - sched should fall inside of optim and not like this.

@Oktai15 for consistency sake, even if you do override the configure_optimizers(), it should try to follow the semantics laid out in the nemo docs. This model is fine, and changing it now will break checkpoints, but in the future aim to remain consistent even if you override stuff.

**Comment by itzsimpl** [comment]
If this is isolated to hifigan, then since hifigan is more or less recent, it would probably be wise to support both versions for consistency sake. Emitting a warning note that the same level version is deprecated. This way you do not break old models, but promote consistency for new ones. Just a thought.

**Comment by titu1994** [comment]
Closing as @Oktai15 will take a look at moving around sched for this model.

**Comment by Oktai15** [comment]
@titu1994 let’s keep it open as notification
