### ISSUE TITLE
Issues viewing NMTensors and 

### ISSUE THREAD

**Issue by bc** [NVIDIA/NeMo#3554]
**Describe the bug**

I am able to load a pretrained version of Quartznet, and when I explore the encodings, I can't figure out a way to convert them into something I can analyze, like a list, np.ndarray or pandas Series. This is for a voice analysis project and I am looking to access the encodings directly. thanks so much

**Steps/Code to reproduce bug**
https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/NVidiaQuartzNetMic.ipynb
Go here, Run All using the Co-Lab. Then after putting in your voice for the 10s sample recording, 

1. Add breakpoint just after line 63 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/13772726/151621762-82e07180-21b7-46be-a562-bbfb300bce14.png">
to
<img width="542" alt="image" src="https://user-images.githubusercontent.com/13772726/151621800-8d66a5dd-b26a-481c-b90a-8a6133d7989f.png">
`import pdb; pdb.set_trace()`

2. Add new cell at bottom with `wav_to_text(create_manifest('test.wav'))`
3. once PDB debugger opens, type `encoded` and see this result:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/13772726/151621897-065bef93-6ea7-4820-b785-273603db8f72.png">

I just want to convert that `nemo.core.neural_types.NmTensor` into a list, pandas series, etc. Something with numbers that I can look at.

```
encoded, encoded_len = jasper_encoder(audio_signal=processed_signal,
                                          length=processed_signal_len)
```

**Comment by okuchaiev** [comment]
please do not use version 0.9.0. Instead you should be using the latest version (which atm is 1.5.1 but we are about to post 1.6.0 today).
