### ISSUE TITLE
No module named 'apex' in colab notebook 00_NeMo_Primer.ipynb

### ISSUE THREAD

**Issue by amrzv** [NVIDIA/NeMo#3559]
**Describe the bug**

When running `00_NeMo_Primer.ipynb` notebook during `import nemo.collections.nlp as nemo_nlp` raises an error:
`ModuleNotFoundError: No module named 'apex'`

**Steps/Code to reproduce bug**

Opened in colab tutorial notebook [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/00_NeMo_Primer.ipynb) and "Run all cells". Then after installation section at importing stage error raises.

**Expected behavior**

End-to-end notebook executions without errors.

**Environment overview (please complete the following information)**

 - Environment location: colab
 - Method of NeMo install: as in notebook
 ```
BRANCH = 'main'
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[all]
```

**Environment details**
- OS version: linux
- PyTorch version: 1.10.0+cu111
- Python version: 3.7.12

**Additional context**
Error occurs in both kernel-types: CPU and GPU.
![apex1](https://user-images.githubusercontent.com/36787333/151659365-9b5a7593-a343-4a8f-8f41-83ff04dfcfc4.jpg)
![apex2](https://user-images.githubusercontent.com/36787333/151659369-7af2fed5-83e7-4ff6-8917-d1960f473453.jpg)

**Comment by conceptofmind** [comment]
You likely will have to install Nvidia Apex into the environment. Nvidia Apex can be found here: https://github.com/NVIDIA/apex. I had just done a clean install on Ubuntu yesterday. Make sure the version of Pytorch matches the version of CUDA or apex will not install correctly.

**Comment by titu1994** [comment]
Is this with Nemo 1.6? @ericharper  we need a patch release with a fix for this. Apex is NOT a hard requirement other than for Megatron, and core notebooks like this should not require apex either until you try to train a model.

**Comment by titu1994** [comment]
@yidong72 add import guards on all ptuning imports and ensure than NLP can be imported in an apex-less environment

**Comment by amrzv** [comment]
> Is this with Nemo 1.6?
> 
> @ericharper we may need a patch release with a fix for this if it's also in r1.6.0 (is ptuning in 1.6?). If not we need to patch main branch.
> 
> Apex is NOT a hard requirement other than for Megatron, and core notebooks like this should not require apex either until you try to train a model.

Yes:
![image](https://user-images.githubusercontent.com/36787333/151695459-ac5be58f-16aa-4349-8213-07a650523714.png)

**Comment by conceptofmind** [comment]
> Is this with Nemo 1.6?
> 
> @ericharper we may need a patch release with a fix for this if it's also in r1.6.0 (is ptuning in 1.6?). If not we need to patch main branch.
> 
> Apex is NOT a hard requirement other than for Megatron, and core notebooks like this should not require apex either until you try to train a model.

Thank you for the information!

This was occuring on 1.6.0 for me as well.

![Screenshot from 2022-01-30 09-45-33](https://user-images.githubusercontent.com/25208228/151704604-441c2d69-3877-4ebf-b6a2-4749670b7e37.png)

**Comment by titu1994** [comment]
How was the installation done ? Using pip install nemo_toolkit["all"]==1.6.0 ? Or from git ? Both are called 1.6.0 in version but main branch has more stuff and more likely to break

**Comment by conceptofmind** [comment]
> How was the installation done ? Using pip install nemo_toolkit["all"]==1.6.0 ? Or from git ? Both are called 1.6.0 in version but main branch has more stuff and more likely to break

I created two separate virtual envs and tested with both:

`apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
pip install nemo_toolkit['all']`

and

`apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
python -m pip install git+https://github.com/NVIDIA/NeMo.git@{BRANCH}#egg=nemo_toolkit[all]`

The same error `ModuleNotFoundError: No module named 'apex'` had occurred using both for me. I am on Ubuntu 18.04.

**Comment by titu1994** [comment]
Thanks for the update, seems a patch release is unavoidable. We will attempt a fix soon.

**Comment by itzsimpl** [comment]
Related? #3472, #3492

**Comment by titu1994** [comment]
Yes all related.

**Comment by yidong72** [comment]
Here is the code example to handle this for all the `apex`, `numba` import issues:
```python
import imp

class ImportChecker(object):
    def __init__(self, *args):
        self.module_names = args
 
    def find_module(self, fullname, path=None):
        if fullname in self.module_names:
            self.path = path
            return self
        return None
 
    def load_module(self, name):
        if name in sys.modules:
            return sys.modules[name]
        try:
            module_info = imp.find_module(name, self.path)
            module = imp.load_module(name, *module_info)
            sys.modules[name] = module
            return module
        except ImportError:
            module = False
            sys.modules[name] = module
            return module
 
import sys

sys.meta_path = [ImportChecker('apex')] + sys.meta_path

import apex
print(apex)
```
We can put this in the `nemo` `__init__.py` file.
If the system cannot find the `apex`, the `apex` will be set to `False`, otherwise it behaves normally.
Here is the [nice article](https://xion.org.pl/2012/05/06/hacking-python-imports/#more-3535) which explains the import hook.

**Comment by titu1994** [comment]
Numba is properly import guarded. This proposed seems like an interesting patch for the r1.6.0 release, but we will impose exact import checks at the NLP domain and it's subdomains for apex in the long term @yidong72
