### ISSUE TITLE
How about supporting Unigram tokenizer in NeMO?

### ISSUE THREAD

**Issue by catskillsresearch** [NVIDIA/NeMo#3565]
Currently NeMo has BPE but I don't see Unigram.

[Unigram is better than BPE.](https://arxiv.org/pdf/2004.03720.pdf)

[SpeechBrain supports Unigram.](https://colab.research.google.com/drive/12yE3myHSH-eUxzNM0-FLtEOhzdQoLYWe?usp=sharing)

**Comment by titu1994** [comment]
Interestingly, we use Sentencepiece - and the default is changed for every single subword model in Nemo. https://github.com/NVIDIA/NeMo/blob/main/scripts/tokenizers/process_asr_text_tokenizer.py#L55 
We use SPE Unigram on all subword model checkpoints - which has shown better wer than SPE BPE earlier. Good to know there's research backing this up. 

The problem with Unigram for the tutorials is that we selected a tiny dataset, which don't cannot build Unigram upto the hidden dimensions we want (1024) to demonstrate loading of the decoder state dict.

**Comment by catskillsresearch** [comment]
I'm looking at the latest version of

https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/ASR_with_Subword_Tokenization.ipynb

It seems to be using unigram already, is that correct?

**Comment by titu1994** [comment]
Yes that one does cause an4 is small and we limit vocab + no fine-tune from pre existing checkpoint so Unigram is easy there. In general we prefer Unigram tokenizer for all datasets, it's only in toy datasets where Unigram is unable to generate 1024 vocab size that we switch to spe BPE
