### ISSUE TITLE
Fix to Exporting ASR model to ONNX [export_jasper_to_onnx.py] -  'NoneType' object has no attribute 'placement'

### ISSUE THREAD

**Issue by adrifloresm** [NVIDIA/NeMo#357]
I was having issues exporting a NeMo (quartznet) acoustic model to ONNX. I will post the fixe in a PR shortly. 

I am using the script: https://github.com/NVIDIA/NeMo/blob/master/scripts/export_jasper_to_onnx.py

I identified two bugs: 
1. Easy bug - The logger needs to be updated from `logging.info` to `nemo.logging.info`

2. When I run the script (after updating the logger) I get the following error. The factory was not getting created in time - needed to move the factory creation before the Encoder/Decoder initialization, i.e. ` nf = nemo.core.NeuralModuleFactory(create_tb_writer=False)`.

To reproduce this bug I am using:
- config: https://github.com/NVIDIA/NeMo/blob/master/examples/asr/configs/quartznet15x5.yaml
- encoder/decoder: https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5

```
File "/home/adrianaf/projects/asr_system/nemo_asr_app/tools/NeMo/export_jasper_to_onnx.py", line 116, in <module>
    pre_v09_model=args.pre_v09_model,
  File "/home/adrianaf/projects/asr_system/nemo_asr_app/tools/NeMo/export_jasper_to_onnx.py", line 68, in main
    **jasper_model_definition["JasperEncoder"])
  File "/tmp/NeMo/nemo/collections/asr/jasper.py", line 137, in __init__
    super().__init__()
  File "/tmp/NeMo/nemo/backends/pytorch/nm.py", line 39, in __init__
    NeuralModule.__init__(self)  # For NeuralModule API
  File "/tmp/NeMo/nemo/core/neural_modules.py", line 48, in __init__
    self._placement = self._factory.placement
AttributeError: 'NoneType' object has no attribute 'placement'

```

**Comment by adrifloresm** [comment]
Pull request: https://github.com/NVIDIA/NeMo/pull/360

**Comment by adrifloresm** [comment]
Fixes merged to master: https://github.com/NVIDIA/NeMo/commit/403238f82d26879ba5fca53fbf75b3cdc70fb49b

**Comment by Thesane** [comment]
the script managed to convert the decoder part only but the encoder part failed with 

> [NeMo E 2020-02-18 17:43:15 actions:1023] module export failed for JasperEncoder with exception number of output names provided (2) exceeded number of outputs (1)

I am using the chkpt from [https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5](https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5)
