### ISSUE TITLE
Different Speakers Reciting Similar Lines

### ISSUE THREAD

**Issue by conceptofmind** [NVIDIA/NeMo#3596]
Hi,

I have about 100 hours of pre-processed data for male and female speakers. There is some overlap in the lines the speakers are reciting.

I was wondering if having different speakers saying the same exact text would negatively impact the training of an automatic speech recognition model? Would I have to remove the audio and text files where the speakers say the same thing? Each speaker sounds quite different from the other.

Thank you,

Enrico

**Comment by titu1994** [comment]
There won't be much difference to the model (at least not from what I have observed) but your model won't learn to recognize general English (or the spoken language), just the few sets of sentences you have in your dataset.

**Comment by titu1994** [comment]
In fact, varied speaker speaking similar things is good for the model to generalize.

**Comment by conceptofmind** [comment]
> In fact, varied speaker speaking similar things is good for the model to generalize.

I greatly appreciate your help. Thank you very much!
