### ISSUE TITLE
./reinstall.sh crashes due to not being able to uninstall llvmlite

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/NeMo#3613]
Starting off of `nemo:1.5.1` container, cloning the NeMo repo to a folder inside of it and calling `./reinstall.sh` fails with
```
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
`pip install -e` on the other hand succeeds installing `nemo:1.7.0rc0` and `numpy:1.22.2`, the rest of the packages remain untouched.

It seems that `./reinstall.sh` which used to work fine, a week or so ago when following the same procedure to upgrade to `nemo:1.6.0rc` redeveloped issue #841. The solution remains the same, first call
```
pip install --ignore-installed llvmlite
```
followed by `./reinstall.sh`. In this case, apart `llvml`, the following packages are updated
```
ftfy-6.0.3 nemo-toolkit-1.7.0rc0 numba-0.55.1 pytorch-lightning-1.5.9 sacrebleu-2.0.0 setuptools-59.5.0
```
Interestingly `numpy` in this case is left at `1.21.5`.

**Comment by Oktai15** [comment]
@titu1994, please, take a look at this issue
