### ISSUE TITLE
About Korean ASR 

### ISSUE THREAD

**Issue by eesungkim** [NVIDIA/NeMo#3636]
Thank you for sharing a great tool. 

I'm wondering if I can make a contribution to Nemo sharing the pretrained models trained with Ksponspeech dataset which is an open-domain Korean dialog corpus with benchmark scores, configs, and related codes. 

If so, please let me know how to share the pretrained models.

**Comment by okuchaiev** [comment]
Hi @eesungkim ! I'm really excited about this potential addition. 
To make this immediately available to the community, feel free to start a discussion with link to your model's ".nemo" file under "Show and tell" category on our forum https://github.com/NVIDIA/NeMo/discussions/categories/show-and-tell 
Let's start with this as a first step.
