### ISSUE TITLE
.wav file contains data in an unknown format

### ISSUE THREAD

**Issue by claratang98** [NVIDIA/NeMo#3647]
I am testing out the NVIDIA NeMo tutorial for ASR_with_Nemo.ipynb on google colab. The dataset in the demo from an4 works fine for me. However when I try to upload a .wav file from my local pc, the code returns an error "RuntimeError: Error opening '020010009.wav': File contains data in an unknown format." This is odd because I tried uploading a .sph file and use their code to convert the .sph file into a .wav file and it outputs the same error. I opened up the .sph file from the an4 dataset and opened up my .sph file and even though both are .sph files, the file content looks different. Seems like the demo only works on the an4 audio dataset and nothing else. Can anyone help?

**Comment by titu1994** [comment]
Wav audio files should be monochannel and 16khz sample rate only. Preprocess you dataset using either Sox or FFMPEG to be in a standard format. If those libraries cannot load and convert your audio file, then most likely the audio file is corrupted.
