### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by davidmartinrius** [NVIDIA/NeMo#3658]
Hello,

I Installed a clean Ubuntu 20.04, installed nvidia drivers 440 for RTX 3080. Then I followed the instructions to train a model with Tacotron2.

numpy fails with the next error:
valueerror: numpy.ndarray size changed, may indicate binary incompatibility. expected 96 from c header, got 88 from pyobject 

I tried the default version of numpy and also I tried pip install --upgrade numpy==1.21.0

I really don'tknow how to solve the problem and I write this to ask for help.

Do you know how to solve it?

Thank you!

David

**Comment by davidmartinrius** [comment]
Yes, here it is: (I tried it with sudo and without sudo)

pc@pc:~/Downloads$ sudo python3.8 tacotron2.py sample_rate=25050 train_dataset=/home/pc/Downloads/newcontent.json validation_datasets=/home/pc/Downloads/newcontent.json trainer.max_epochs=1 trainer.accelerator=null trainer.check_val_every_n_epoch=1
[sudo] password for pc: 
Traceback (most recent call last):
  File "tacotron2.py", line 24, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py", line 26, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit, pit_permutate
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/audio/__init__.py", line 26, in <module>
    from torchmetrics.functional.audio.pesq import perceptual_evaluation_speech_quality  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/audio/pesq.py", line 20, in <module>
    import pesq as pesq_backend
  File "/usr/local/lib/python3.8/site-packages/pesq/__init__.py", line 6, in <module>
    from .cypesq import cypesq, cypesq_retvals, cypesq_error_message as pesq_error_message
  File "pesq/cypesq.pyx", line 1, in init cypesq
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by titu1994** [comment]
You'll need to post the message on the torch metric's GitHub, seems it's using a library that doesn't support newer numpy. Also try upgrading numpy to 1.22 since that seems to have some fixes on top of 1.21

**Comment by davidmartinrius** [comment]
Ok I will try it and I will tell you if it worked. Thank you

**Comment by davidmartinrius** [comment]
I still have to try the numpy 1.21
I used the docker repository and I could start to train. Anyway, I don't want to work with Docker and I am going to try the numpy 1.21 version. Please don't close this issue yet, I will confirm if it worked

**Comment by ekmb** [comment]
@davidmartinrius, have you tried `pip install --upgrade numpy` without pinning a specific version?

**Comment by davidmartinrius** [comment]
> @davidmartinrius, have you tried `pip install --upgrade numpy` without pinning a specific version?

Absolutely yes. The latest version does not work properly. Throws the error that I commented in the first message.

Thank you

**Comment by davidmartinrius** [comment]
In this message I share what I tried. PART 1 is a try with the latests versions. PART 2 is numpy==1.21 and numba==0.55.1


### PART 1:

pc@pc:~/Downloads$ sudo python3.8 -m pip install --upgrade numpy numba
Requirement already satisfied: numpy in /usr/local/lib/python3.8/site-packages (1.21.0)
Collecting numpy
  Downloading numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 10.0 MB/s eta 0:00:00
Requirement already satisfied: numba in /usr/local/lib/python3.8/site-packages (0.55.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from numba) (59.5.0)
  Using cached numpy-1.21.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /usr/local/lib/python3.8/site-packages (from numba) (0.38.0)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.0
    Uninstalling numpy-1.21.0:
      Successfully uninstalled numpy-1.21.0
Successfully installed numpy-1.21.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
pc@pc:~/Downloads$ sudo python3.8 tacotron2.py sample_rate=25050 train_dataset=/home/pc/Downloads/newcontent.json validation_datasets=/home/pc/Downloads/newcontent.json trainer.max_epochs=1 trainer.accelerator=null trainer.check_val_every_n_epoch=1
Traceback (most recent call last):
  File "tacotron2.py", line 24, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py", line 26, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit, pit_permutate
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/audio/__init__.py", line 26, in <module>
    from torchmetrics.functional.audio.pesq import perceptual_evaluation_speech_quality  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/audio/pesq.py", line 20, in <module>
    import pesq as pesq_backend
  File "/usr/local/lib/python3.8/site-packages/pesq/__init__.py", line 6, in <module>
    from .cypesq import cypesq, cypesq_retvals, cypesq_error_message as pesq_error_message
  File "pesq/cypesq.pyx", line 1, in init cypesq
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
pc@pc:~/Downloads$ 

### PART 2
pc@pc:~/Downloads$ sudo python3.8 -m pip install --upgrade numpy==1.21 numba==0.55.1
Collecting numpy==1.21
  Using cached numpy-1.21.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Requirement already satisfied: numba==0.55.1 in /usr/local/lib/python3.8/site-packages (0.55.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from numba==0.55.1) (59.5.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /usr/local/lib/python3.8/site-packages (from numba==0.55.1) (0.38.0)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
Successfully installed numpy-1.21.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
pc@pc:~/Downloads$ sudo python3.8 tacotron2.py sample_rate=25050 train_dataset=/home/pc/Downloads/newcontent.json validation_datasets=/home/pc/Downloads/newcontent.json trainer.max_epochs=1 trainer.accelerator=null trainer.check_val_every_n_epoch=1
Traceback (most recent call last):
  File "tacotron2.py", line 24, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/callbacks/base.py", line 26, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/utilities/types.py", line 25, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit, pit_permutate
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/audio/__init__.py", line 26, in <module>
    from torchmetrics.functional.audio.pesq import perceptual_evaluation_speech_quality  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/torchmetrics/functional/audio/pesq.py", line 20, in <module>
    import pesq as pesq_backend
  File "/usr/local/lib/python3.8/site-packages/pesq/__init__.py", line 6, in <module>
    from .cypesq import cypesq, cypesq_retvals, cypesq_error_message as pesq_error_message
  File "pesq/cypesq.pyx", line 1, in init cypesq
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
pc@pc:~/Downloads$

**Comment by davidmartinrius** [comment]
Tomorrow I am going to try to downgrade torch metrics.
I'll try the different versions released and documented here:
https://torchmetrics.readthedocs.io/en/latest/generated/CHANGELOG.html
I will tell you if it worked or not. I think new users that are installing NeMo with latest versions will have the same problem. Let's see if downgrading the version of torch metrics can be a workaround..

**Comment by itzsimpl** [comment]
The culprits are `pesq` and I assume also `torch`, which have been compiled with a different version of `numpy`. Try first to reinstall `pesq`
```
pip uninstall pesq
pip install pesq --no-binary pesq
```
then also `torch` (note that this will take a long time)
- if you installed your own `torch`
```
pip uninstall torch
pip install torch --no-binary torch
```
- if you are working in `nvcr.io/nvidia/pytorch:22.01` container
```
pip uninstall torch
pip install git+https://github.com/pytorch/pytorch.git@bfe5ad28e6a509e08c0afd785c32019f8a05a7fb
```

This should resolve the error that you are getting, as it is similar to  #3619 (non working example 3), but in the case of #3619 it still leads to failure that is the same as in all other non working examples.

**Comment by titu1994** [comment]
In the container you should not need to do anything - we use an older supported Numba and the CI runs the container constantly so no need to downgrade and reinstall torch. 

We don't want Nemo users to have go downgrade stuff and then use esoteric build steps for pesq, so we are currently trying other things but numpy change has broken quite a few things so it's been taking time to track them downc

**Comment by titu1994** [comment]
So turns out the container has Numba 0?53.1 built into it, and that somehow doesn't interfere with numpy 1.22.0 or 1.21.0, and since this version works with cuda + RNNT, we've decided to downgrade to the container version of Numba for the next release. Users should not see any noticable speed difference (in fact RNNT loss should be even faster after some algorithmic improvements) and there should not be any compatibility issues. 

Closing the bug since it should fix the issue wrt container, feel free to reopen if it's not a sufficient resolution.

**Comment by bfss** [comment]
Sorry for reopen this issue, you should:
uninstall numpy
delete your pesq wheel cache
install numpy with specific version
install pesq
So the pesq will rebuild with the specific numpy you just installed

**Comment by wonjunchoi-arc** [comment]
I have a same problem with @davidmartinrius 
but in my case 
following @itzsimpl comment can solve this problem
