### ISSUE TITLE
Can't download NVIDIA Models

### ISSUE THREAD

**Issue by claratang98** [NVIDIA/NeMo#3659]
I am trying the NEMO_Primer from this GitHub repository. I have tried downloading the model on Google Colab however if I try to run the demo on Jupiter notebook locally, the model cant be downloaded. Please see image to see error. This error pops up when passing a pre-trained model name and instantiate a model directly from the cloud:

citrinet = nemo_asr.models.EncDecCTCModelBPE.from_pretrained('stt_en_citrinet_512')

or 

quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="stt_en_quartznet15x5")

<img width="972" alt="Screenshot 2022-02-14 at 11 10 41 AM" src="https://user-images.githubusercontent.com/90296566/153793932-26dc0258-0225-4542-9322-bc7a496b4059.png">

**Comment by titu1994** [comment]
Oh librosa. We will fix this soon, thanks for letting us know.

**Comment by titu1994** [comment]
For now, until this is fixed you can force pip install librosa==0.8

**Comment by claratang98** [comment]
Hi I did all these changes but I am still getting the same error.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/90296566/154206523-3e3df380-4d94-4fb4-abb8-6ec836dd9dff.png">
<img width="322" alt="Screenshot 2022-02-16 at 2 10 02 PM" src="https://user-images.githubusercontent.com/90296566/154206810-864ab6a7-f47e-409c-b983-9acf7a26957f.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/90296566/154206743-2c820ea0-bf0f-48cd-b2cd-59f57489f22c.png">

**Comment by titu1994** [comment]
I merged a PR today to support librosa 0.9, can you try the main branch tutorials and see if it works ?
