### ISSUE TITLE
Need Confirmation

### ISSUE THREAD

**Issue by SonuKumari1690** [NVIDIA/NeMo#3675]
Dear NVIDIA Team,
I need a small confirmation from your end, please confirm that with the below command the model which is restored is from best checkpoints, as after that I am using the loaded model for predictions with the second command

model = TextClassificationModel.restore_from(restore_path='./trained-model-text-nvidia.nemo')

predicted_class = model.classifytext(queries=config.model.infer_samples, batch_size=2, max_seq_length=511)

**Comment by VahidooX** [comment]
The commands look good to me and should be working.

**Comment by SonuKumari1690** [comment]
@VahidooX : Thanks for your kind reply, yes commands are working but my point of question is whether the first command which is **model = TextClassificationModel.restore_from(restore_path='./trained-model-text-nvidia.nemo')**, the model which is restored is from the best checkpoints (from the training phase) though I have validated but since in this command we are not explicitly specifying the best checkpoint parameter hence needed your kind confirmation

**Comment by okuchaiev** [comment]
.nemo file contains only one checkpoint.

**Comment by VahidooX** [comment]
It depends on the exp_manager.checkpoint_callback_params.save_best_model. if it was True during the training, the nemo file is the best based on the validation metric otherwise it is the model from the last epoch. 

If you have saved the top K checkpoints, you may use this script to average over the checkpoints which may give better results in some cases.

`/scripts/checkpoint_averaging/checkpoint_averaging.py`

**Comment by VahidooX** [comment]
Not all the configs are added to all the config files. Please take a look here which has a more complete section for exp_manager:
https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/conformer_transducer_char.yaml#L228

If you have already trained the model with that config as the default is False, then your nemo file is not the best one but the last one. You need to convert one of PTL checkpoints (the best one) if they are available to nemo format or just repeat the training with save_best_model=true.
