### ISSUE TITLE
WARNING - Trainer state wasn't restored

### ISSUE THREAD

**Issue by jaberkow** [NVIDIA/NeMo#369]
I am running `/examples/asr/quartznet.py` to fine tune quartznet on some of my own data using the following command (from within the nvidia pytorch container):

```
python /NeMo/examples/asr/quartznet.py --num_epochs=3 --model_config=/data/quartznet_checkpoints/quartznet15x5.yaml --train_dataset "/data/VOiCES_devkit/references/train_manifest.json" --lr=0.005 --batch_size=16 --load_dir=/data/quartznet_checkpoints/
```
`/data/quartznet_checkpoints/` contains the files from [The quartznet repo](https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5/files), including the encoder and decoder checkpoints, and the yaml file.  When I run the command I get the following warning before training starts.
```
2020-02-13 22:21:50,567 - INFO - Restoring checkpoint from folder /data/quartznet_checkpoints/ ...
2020-02-13 22:21:50,727 - WARNING - For module trainer, no file matches  in /data/quartznet_checkpoints/
2020-02-13 22:21:50,727 - WARNING - Trainer state wasn't restored
```
The training_batch_WER goes down pretty quickly to reasonable levels (for my very noisy audio data), so I think the pretrained weights are being loaded properly.  That being said, I would appreciate some clarity on the meaning and implications of this error message.

**Comment by vsl9** [comment]
It means that it can't find optimizer's state (file `trainer-STEP-*.pt`). But since you are doing fine-tuning, you don't need to restore the optimizer's state and it's totally fine.

**Comment by jaberkow** [comment]
Good to know, thank you!
