### ISSUE TITLE
Enquiry about the ASR "QuartzNet15x5Base-En" Model

### ISSUE THREAD

**Issue by claratang98** [NVIDIA/NeMo#3697]
Hi, just wondering if the QuartzNet15x5Base-En Model has been trained using the Singapore National Speech Corpus (NSC) and If so, which portions of the corpus was used to train the model.

Thanks. :-)

**Comment by titu1994** [comment]
No it hasn't been trained using NSC. It's quite an old model. If you refer to the Citrinet or Conformer checkpoints, they will be trained on NSC

**Comment by claratang98** [comment]
<img width="1110" alt="Screenshot 2022-02-17 at 6 04 46 PM" src="https://user-images.githubusercontent.com/90296566/154452942-67f4ffd4-5ab0-4d41-9bac-21363872f53e.png">
I have tried to download the citrinet model but it is not found.
