### ISSUE TITLE
typo in diarization class

### ISSUE THREAD

**Issue by EmreOzkose** [NVIDIA/NeMo#3699]
**Describe the bug**

In [diarization class (ClusteringDiarizer)](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/models/clustering_diarizer.py#L395), there is `os.path.json()` function, but I think it is actually `os.path.join()`. 

Nemo version: 1.6.2

**Comment by nithinraok** [comment]
Oh great. I missed this issue, but found out the issue while I am trying something. I just fixed it. It's part of main now. 

Thank you.
