### ISSUE TITLE
Buffered speaker diarization

### ISSUE THREAD

**Issue by demsarjure** [NVIDIA/NeMo#3707]
**Is your feature request related to a problem? Please describe.**

For speaker diarization tasks tutorials and examples currently only offer scripts for offline diarization. I successfully got those running in combination with custom ASR models for Slovenian language. For ASR tasks the repository also contains scripts for buffered (streamed/live) inference, would such inference be possible for diarization?

**Describe the solution you'd like**

A tutorial or example on how to do buffered speaker diarization (if that is possible in the current framework). 

**Describe alternatives you've considered**

Some guidance about how I can implement this myself.

**Comment by nithinraok** [comment]
Thank you for your interest. Streaming diarization is in the works, and we are making good progress on it. Hopefully we can make it available during second half of this year. 

Thank you.

**Comment by demsarjure** [comment]
Thank you for the response!

**Comment by SvenHockers** [comment]
Is there any update on the buffered speaker diarization? 
Or is it currently still in development?

**Comment by TLTP1995** [comment]
any news?

**Comment by justinatbahasa** [comment]
hi @nithinraok any update regarding this streaming diarization? Thanks
