### ISSUE TITLE
Cannot download citrinet models

### ISSUE THREAD

**Issue by claratang98** [NVIDIA/NeMo#3717]
Hi,

Ive managed to download the models under quartznet however am having issues regarding citrinet models.
Please see error output below.
Thanks
![](https://user-images.githubusercontent.com/90296566/154452942-67f4ffd4-5ab0-4d41-9bac-21363872f53e.png)

**Comment by titu1994** [comment]
Which Nemo version are you on and do to have internet access ?

**Comment by claratang98** [comment]
> Which Nemo version are you on and do to have internet access in the environment trying to run the notebook ?

I am currently on Nemo Version: 1.0.0b1. Yes I have internet access because I am able to download other models like QuartzNET and Jasper

**Comment by titu1994** [comment]
B1 does not support this model. Please use ASR model.list_available_models() on the latest Nemo to use the available models.
