### ISSUE TITLE
Can we use ASR pre-trained models with SSL pre-training code?

### ISSUE THREAD

**Issue by ahkarami** [NVIDIA/NeMo#3728]
Hi,
I have used the [SSL pre-training script](https://github.com/NVIDIA/NeMo/blob/main/examples/asr/speech_pretraining/speech_pre_training.py) as follows:
```sh
python speech_pre_training.py \
    --config-path="../conf/ssl/citrinet/" \
    --config-name="citrinet_ssl_1024" \
    model.train_ds.manifest_filepath="./train_LS_manifest.json" \
    model.validation_ds.manifest_filepath="./test_LS_manifest.json" \
    trainer.gpus=1 \
    trainer.accelerator="ddp" \
    trainer.max_epochs=100 \
    trainer.log_every_n_steps=100 \
    trainer.accumulate_grad_batches=1 \
    trainer.check_val_every_n_epoch=1 \
    trainer.precision=32 \
    model.train_ds.batch_size=12 \
    model.validation_ds.batch_size=10 \
    model.spec_augment.freq_masks=4 \
    model.spec_augment.time_masks=10 \
    model.spec_augment.freq_width=27 \
    model.spec_augment.time_width=0.05 \
    model.optim.name="novograd" \
    model.optim.lr=0.05 \
    model.optim.betas=[0.8,0.25] \
    model.optim.weight_decay=0.001 \
    model.optim.sched.warmup_steps=5000 \
    model.optim.sched.min_lr=1e-9 \
    exp_manager.exp_dir="ssl_experiments/" \
    exp_manager.name="SSL-Citrinet1024" \
    exp_manager.create_tensorboard_logger=True \
    exp_manager.resume_if_exists=True \
    exp_manager.resume_ignore_no_checkpoint=True \
    exp_manager.create_wandb_logger=False \
    +init_from_pretrained_model="stt_en_citrinet_1024"
```
However, I have faced an error when the PyTorch lightening attempts to load the pre-trained `stt_en_citrinet_1024` weights (_i.e.,_ `+init_from_pretrained_model="stt_en_citrinet_1024"`). The error refers to the [line 61](https://github.com/NVIDIA/NeMo/blob/main/examples/asr/speech_pretraining/speech_pre_training.py#L61) of code (`maybe_init_from_pretrained_checkpoint` method). I have investigated and I realized that the `maybe_init_from_pretrained_checkpoint` method has the internal attribute of `strict=False` [ref](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/core/core.html?highlight=maybe_init_from_pretrained_checkpoint#nemo.core.ModelPT.maybe_init_from_pretrained_checkpoint). So, would you please help me that can I load the pre-trained wights? If yes, How I can do that?
Best

**Comment by sam1373** [comment]
Hi, I think the issue here is that stt_en_citrinet_1024 is only registered as an available pre-trained model for the standard citrinet training (since we usually wouldn't do pre-training starting from a checkpoint like that). However, you can still use it to initialize the weights, you would just need to download the checkpoint directly from ngc and use init_from_nemo_model instead. You would also need to change model.model_defaults.kernel_size_factor to 1.0 for the configs to match. Additionally, you will need to increase/remove the min_duration from your script for the contrastive pre-training to work.

**Comment by titu1994** [comment]
@sam1373 init_from_pretrained_model downloads from ngc anyway and then runs the equivalent of init_from_nemo_model, so wouldn't it be a case to support the include/exclude stuff in  both of these ? It would make users lives easier than manual download of a nemo file from NGC.

**Comment by titu1994** [comment]
Upon further discussion this needs to be a multiple step process so we won't be adding support for it inside init_from* flags.

**Comment by itzsimpl** [comment]
As a user I would kindly suggest that hints like [the one above](https://github.com/NVIDIA/NeMo/issues/3728#issuecomment-1048311964) be more markedly present in the documentation. It is really hard to track down all the infinite possibilities by reading through the issues/discussions and PR requests.

**Comment by titu1994** [comment]
Agreed. We need comprehensive docs for SSL, considering there is the minimum amount right now in the training script. This is however quite a niche use case - why would one want to use SSL when they gave a pretrained encoder. There's practically no research on such a case, that it works at all, or if it works, does it surpass or degrade SSL without pretraining. So it's reasonable that we don't have concrete documentation for this

**Comment by titu1994** [comment]
Then again, exploring this would be an interesting topic for researchers who use Nemo :D
