### ISSUE TITLE
on Jetson Xavier?

### ISSUE THREAD

**Issue by AndreV84** [NVIDIA/NeMo#374]
I am trying to install it on Xavier
I installed https://github.com/microsoft/onnxruntime
but when I do ./reinstall.sh it would throw a message saying that it has onnxruntime cached 1.6.0, and that it wouldn't find onnxruntime from nemo-toolkit 0.9.0

``

**Comment by AndreV84** [comment]
installed it with no-deps;
how to verify the installation?

**Comment by AndreV84** [comment]
Collecting sentencepiece
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3ka6fp8l/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3ka6fp8l/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3ka6fp8l/sentencepiece/pip-egg-info
         cwd: /tmp/pip-install-3ka6fp8l/sentencepiece/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3ka6fp8l/sentencepiece/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Installed from sources, however

**Comment by AndreV84** [comment]
but even I deleted the package from all requirementsd.txt files it attempts to install it and fails;
how to get through it?

**Comment by AndreV84** [comment]
managed to install python module, however with https://github.com/google/sentencepiece/blob/master/python/README.md

**Comment by AndreV84** [comment]
seems installed: https://devtalk.nvidia.com/default/topic/1071519/jetson-agx-xavier/nemmo-installation/post/5428769/#5428769
How to verify if it works?

**Comment by okuchaiev** [comment]
to verify, try running asr unittests first. Also, you can try running inference of a small dataset like an4 (see ASR notebook tutorial)

**Comment by AndreV84** [comment]
on running unittests it seems to throw Segmentation Fault
[Log.txt](https://github.com/NVIDIA/NeMo/files/4252867/Log.txt)
does it seem like an issue with sentipence?

**Comment by AndreV84** [comment]
and now it succeeded on running unittests; thanks; I will try to test with an4

**Comment by AndreV84** [comment]
could you extend how to generate the json file please?
in case I am running: python3  jasper_an4.py , please?
`/NeMo/examples/asr$ python3 jasper_an4.py
2020-02-26 08:15:29.658903: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[NeMo W 2020-02-26 08:15:32 deprecated:66] Function ``_get_trainer`` is deprecated. It is going to be removed in the future version.
Traceback (most recent call last):
  File "jasper_an4.py", line 296, in <module>
    main()
  File "jasper_an4.py", line 177, in main
    jasper_params, args, nf
  File "jasper_an4.py", line 36, in create_dags
    manifest_filepath=args.train_dataset, labels=vocab, batch_size=args.batch_size, **train_dl_params,
  File "/home/nvidia/NeMo/nemo/collections/asr/data_layer.py", line 145, in __init__
    self._dataset = AudioDataset(**dataset_params)
  File "/home/nvidia/NeMo/nemo/collections/asr/parts/dataset.py", line 143, in __init__
    max_number=max_utts,
  File "/home/nvidia/NeMo/nemo/collections/asr/parts/collections.py", line 152, in __init__
    for item in manifest.item_iter(manifests_files):
  File "/home/nvidia/NeMo/nemo/collections/asr/parts/manifest.py", line 46, in item_iter
    with open(expanduser(manifest_file), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nvidia/TestData/an4_dataset/an4_train.json'
`
is there a need to execute the section from the notebook that starts with import json in order to generate the file?
