### ISSUE TITLE
CUDA error in Speaker Diarization in nmesc_clustering.py - error: CUSOLVER_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by Xiaoping777** [NVIDIA/NeMo#3757]
**Describe the bug**
It is very strange , only one audio file has this error when calling speaker diariation function, Error Message as below:

Error:cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnSsyevd(handle, jobz, uplo, n, A, lda, W, work, lwork, info)`

**Steps/Code to reproduce bug**
I tracked to the root of error, which is in the function (nmesc_clustering.py), when call eigh(laplacian) with cuda (cuda device =1). 

def eigDecompose(laplacian, cuda, device=None):  
    print(len(laplacian))
    if TORCH_EIGN:
        if cuda:
            if device is None:
                device = torch.cuda.current_device()            
            
            laplacian = torch.from_numpy(laplacian).float().to(f"cuda:{device}")
        else:
            laplacian = torch.from_numpy(laplacian).float()
                
        **lambdas, diffusion_map = eigh(laplacian)**
        lambdas = lambdas.cpu().numpy()
        diffusion_map = diffusion_map.cpu().numpy()
    else:
        lambdas, diffusion_map = eigh(laplacian)

    return lambdas, diffusion_map

**Environment overview (please complete the following information)**
Linux environment, 2 gpus, using gpu 1

**Additional context**
the error happens when laplacian shape is 592x592, while other audio files (no error) with laplacian shape of odd dimensions, not sure if it is the reason.

**Comment by nithinraok** [comment]
Thanks for raising the issue. 

Could you share the version details of NeMo, pytorch, lightning, and CUDA ?

Is it possible to share the audio file or details of it, like the format and duration. This will help us to reproduce the bug.

**Comment by Xiaoping777** [comment]
the Nemo version is: MAJOR = 1
MINOR = 6
PATCH = 0
PRE_RELEASE = 'rc0'

pytorch - torch==1.10.1
pytorch_lightning -1.5.8
CUDA  10.2

sorry I cannot provide the audio file, format is wav, about 10-15 minutes

**Comment by nithinraok** [comment]
Thanks for providing the details, Do you get the same error even with main? 

Is it possible to share the exact duration of that audio?

**Comment by okuchaiev** [comment]
Closing. Please re-open if you see this same issue on 1.7.2 or newer NeMo versions.
