### ISSUE TITLE
WaveGlow: Different sample_rate

### ISSUE THREAD

**Issue by knbunmlr** [NVIDIA/NeMo#377]
Hey guys,

is there a way to use the WaveGlow pretrained net with spectograms generated by a Nemo-Tacotron2 model with a sample rate of 16000?

One more thing: The statements about the Apex/Amp optimization level in the Nvidia NGC is not consistent. The metadata states that half precision, i.e. O1, is used but in the description O0 is mentioned and furthermore it's written about Tacotron and not WaveGlow. 

Thx for any ideas.

**Comment by blisc** [comment]
Thank you for catching the error in our documentation. The model description on NGC has been updated.

Our pretrained Waveglow was trained on 22050Hz audio. While I know that it should work for different speakers and different languages, I have no experience using it for different sample rates. I imagine that it would not sound too good. You might have to train a 16 kHz waveglow model yourself.

**Comment by knbunmlr** [comment]
Thanks for the prompt answer and just for the record:

Using the 22050Hz model with a 16kHz Tacotron produces comprehensible speech, which is just a tad too fast as a consequence of the "information loss" coming with a 22,05 to 16 change.
Thus a retraining is unavoidable.

**Comment by blisc** [comment]
Thanks for the update, that's cool to note. You could also try looking into time_stretching if you want to avoid retraining WaveGlow: https://librosa.github.io/librosa/generated/librosa.effects.time_stretch.html
