### ISSUE TITLE
Bug in decoder_timestamps_utils.py, class ASR_TIMESTAMPS

### ISSUE THREAD

**Issue by mabajec** [NVIDIA/NeMo#3772]
Hi, 

method `def load_LM_for_CTC_decoder` of the `ASR_TIMESTAMPS` class in the `decoder_timestamps_utils.py` has a bug. When checking the type of the ASR model, 'EncDecCTCModelBPE' should be checked first and then 'EncDecCTCModel'. Otherwise 'EncDecCTCModelBPE' models will always be treated as `EncDecCTCModel` models.
  
https://github.com/NVIDIA/NeMo/blob/431234ae08db3fe241a387f527d3b1ce26af4c10/nemo/collections/asr/parts/utils/decoder_timestamps_utils.py#L390

**Comment by okuchaiev** [comment]
ping @tango4j
