### ISSUE TITLE
cannot "import nemo_asr" 

### ISSUE THREAD

**Issue by HIN0209** [NVIDIA/NeMo#378]
Hello,

In the training script for speech recognition, I had an error message.
https://nvidia.github.io/NeMo/asr/tutorial.html#training

>>import nemo_asr
ImportError                               Traceback (most recent call last)
<ipython-input-15-1d5a758c78e4> in <module>
      1 #import nemo.collections.asr as nemo_asr
----> 2 import nemo_asr

~/anaconda3/envs/nemo/lib/python3.6/site-packages/nemo_asr/__init__.py in <module>
     16 
     17 from .audio_preprocessing import *
---> 18 from .beam_search_decoder import BeamSearchDecoderWithLM
     19 from .data_layer import (
     20         AudioToTextDataLayer, KaldiFeatureDataLayer, TranscriptDataLayer)

~/anaconda3/envs/nemo/lib/python3.6/site-packages/nemo_asr/beam_search_decoder.py in <module>
      7 from nemo.backends.pytorch.nm import NonTrainableNM
      8 from nemo.core import DeviceType
----> 9 from nemo.core.neural_types import (NeuralType, AxisType, BatchTag, TimeTag,
     10                                     ChannelTag)
     11 
ImportError: cannot import name 'BatchTag'

I tried another import method as shown in the following ipynb (/examples/asr/notebooks)
>>import nemo.collections.asr as nemo_asr
This does not throw an error, but eventually did the same in the later part of the code.

I struggled to install these, but I believe that this is done by pip install nemo-asr.
Thank you!

**Comment by JoBroMo** [comment]
I have the exact same issue.

**Comment by blisc** [comment]
Our documentation at https://nvidia.github.io is current as of version 0.9.0. Unfortunately, it is not up to date with our master branch. If you wish to go through the documentation, I would advise you to get nemo and nemo_asr via pip or checkout the v 9.0 branch: https://github.com/NVIDIA/NeMo/tree/v0.9.0.

Alternatively, you can take a look at the ipython notebook available at master for a version that should correspond with current changes on master: https://github.com/NVIDIA/NeMo/blob/v0.9.0/examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb

**Comment by HIN0209** [comment]
@blisc 
Thank you for the info. I will try these.
