### ISSUE TITLE
Nemo model for Brazillian Portuguese

### ISSUE THREAD

**Issue by danilokarkus** [NVIDIA/NeMo#3783]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Provide a code snippet on how new APIs/changes would be used by others.

**Describe alternatives you've considered**

**Additional context**

**Comment by danilokarkus** [comment]
Nemo is a great alternative to wav2vec models, I am learning the framework and i got really really excited except for the fact that i am from Brazil and wanted to play around with voice data in portuguese... Is there any plan in the near future to provide a pre trained model in Portuguese-BR ?

thanks in advance.

**Comment by titu1994** [comment]
Sorry for the delay, sadly we dont yet have Portuguese-Br pre-trained model, but we are open to contributions.
