### ISSUE TITLE
training_batch_wer fast growth from 0,9 to 200 model predict only "⁇" 

### ISSUE THREAD

**Issue by 32r81b** [NVIDIA/NeMo#3796]
I try perform steps from https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/ASR_with_Transducers.ipynb witn my own dataset. 

After 10% of first epoch i see in tensorboard fast growth training_batch_wer from from 0,9 to 200. 
![image](https://user-images.githubusercontent.com/8361949/156882650-b899bbaf-8c3c-4f7b-a223-69b1e25573b6.png)
![image](https://user-images.githubusercontent.com/8361949/156882655-88e4d233-3b79-4f6c-b7ea-29fa751f2d34.png)

When it happen i see in console weird predictions:
![image](https://user-images.githubusercontent.com/8361949/156880589-a2fae822-1bdb-416b-802b-805227f3c2da.png)

My data is calls with  sample_rate = 8000. My maximum train_ds.batch_size = 8, if I try somthing biger i get OOM error. 

**My train data**
[NeMo I 2022-03-05 16:36:45 mixins:146] Tokenizer SentencePieceTokenizer initialized with 1000 tokens
[NeMo I 2022-03-05 16:36:53 collections:173] Dataset loaded with 361193 files totalling 610.54 hours
[NeMo I 2022-03-05 16:36:53 collections:174] 38078 files were filtered totalling 208.93 hours
[NeMo I 2022-03-05 16:36:54 collections:173] Dataset loaded with 26211 files totalling 63.04 hours
[NeMo I 2022-03-05 16:36:54 collections:174] 0 files were filtered totalling 0.00 hours
[NeMo I 2022-03-05 16:36:54 collections:173] Dataset loaded with 435 files totalling 1.00 hours
[NeMo I 2022-03-05 16:36:54 collections:174] 0 files were filtered totalling 0.00 hours

**My config is:**
name: &name "ContextNet-8x-Stride-RNNT"

model:
  sample_rate: &sample_rate 8000
  compute_eval_loss: false  # eval samples can be very long and exhaust memory. Disable computation of transducer loss during validation/testing with this flag.

  train_ds:
    manifest_filepath: 'demo_kz/manifest_train.json'
    sample_rate: 8000
    batch_size: 8  # Can be increased if memory allows or when using smaller model
    trim_silence: false
    max_duration: 16.7
    shuffle: true
    use_start_end_token: false
    num_workers: 38
    pin_memory: true
    is_tarred: false
    tarred_audio_filepaths: null
    tarred_shard_strategy: "scatter"
    shuffle_n: 2048
    bucketing_strategy: "synced_randomized"
    bucketing_batch_size: null
    
  validation_ds:
    manifest_filepath: 'demo_kz/manifest_dev.json'
    sample_rate: 8000
    batch_size: 8
    shuffle: false
    use_start_end_token: false
    num_workers: 38
    pin_memory: true

  test_ds:
    manifest_filepath: 'demo_kz/manifest_test.json'
    sample_rate: 8000
    batch_size: 8
    shuffle: false
    use_start_end_token: false
    num_workers: 38
    pin_memory: true

  model_defaults:
    filters: 1024
    repeat: 5
    dropout: 0.1
    separable: true
    se: true
    se_context_size: -1
    kernel_size_factor: 1.0
    # encoder / decoder / joint values
    enc_hidden: 640
    pred_hidden: 640
    joint_hidden: 640

  tokenizer:
    dir: "demo_kz/tokenizer/dev/tokenizer_spe_unigram_v1000/"
    type: bpe

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: 8000
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: &n_mels 80
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    pad_to: 16
    stft_conv: false

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 0  # should be kept at 2
    time_masks: 0  # can be 5 for small-med models, 10 for larger models.
    freq_width: 27
    time_width: 0.05

  encoder:
    _target_: nemo.collections.asr.modules.ConvASREncoder
    feat_in: *n_mels
    activation: swish
    conv_mask: true
    init_mode: "tds_uniform"

    jasper:
      - filters: 1024
        repeat: 1
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: false
        separable: true
        se: true
        se_context_size: -1

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [2]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        stride_last: true
        residual_mode: "stride_add"
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [2]  # *stride
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        stride_last: true
        residual_mode: "stride_add"
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [2]  # stride
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        stride_last: true
        residual_mode: "stride_add"
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 1024
        repeat: 5
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.1
        residual: true
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

      - filters: 640
        repeat: 1
        kernel: [5]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: false
        separable: true
        se: true
        se_context_size: -1
        kernel_size_factor: 1.0

  decoder:
    _target_: nemo.collections.asr.modules.RNNTDecoder
    normalization_mode: null  # Currently only null is supported for export.
    random_state_sampling: false  # Random state sampling: https://arxiv.org/pdf/1910.11455.pdf
    blank_as_pad: true  # This flag must be set in order to support exporting of RNNT models + efficient inference.

    prednet:
      pred_hidden: 640
      pred_rnn_layers: 1  # only 1 layer LSTM networks are exportable.
      t_max: null  # Maximum possible target seq length used for Chrono Initialization - https://arxiv.org/abs/1804.11188. Disabled by default.
      dropout: 0.1

  joint:
    _target_: nemo.collections.asr.modules.RNNTJoint
    log_softmax: null  # sets it according to cpu/gpu device
    preserve_memory: false  # dramatically slows down training, but might preserve some memory

    fuse_loss_wer: true
    fused_batch_size: 4

    jointnet:
      joint_hidden: 640
      activation: "relu"
      dropout: 0.1

  decoding:
    strategy: "greedy_batch"  # can be greedy, greedy_batch, beam, tsd, alsd.

    greedy:
      max_symbols: 10

    beam:
      beam_size: 4
      score_norm: true
      return_best_hypothesis: False
      softmax_temperature: 1.0  # scale the logits by some temperature prior to softmax
      tsd_max_sym_exp: 10  # for Time Synchronous Decoding, int > 0
      alsd_max_target_len: 5.0  # for Alignment-Length Synchronous Decoding, float > 1.0
      maes_num_steps: 2  # for modified Adaptive Expansion Search, int > 0
      maes_prefix_alpha: 1  # for modified Adaptive Expansion Search, int > 0
      maes_expansion_beta: 2  # for modified Adaptive Expansion Search, int >= 0
      maes_expansion_gamma: 2.3  # for modified Adaptive Expansion Search, float >= 0

  loss:
    loss_name: "default"

    warprnnt_numba_kwargs:
      fastemit_lambda: 0.001  # Values can be in range [1e-4, 1e-2]. Generally, 0.001 is good start.
      clamp: -1.0  # if > 0, applies gradient clamping in range [-clamp, clamp] for the joint tensor only.

  optim:
    name: novograd
    lr: 0.05

    betas: [0.9, 0.0]
    weight_decay: 0.001

    sched:
      name: CosineAnnealing

      warmup_steps: null
      warmup_ratio: null
      min_lr: 1e-6
      last_epoch: -1

trainer:
  devices: 4 # number of gpus
  max_steps: null # computed at runtime if not set
  num_nodes: 1  # Should be set via SLURM variable `SLURM_JOB_NUM_NODES`
  accelerator: gpu
  strategy: ddp
  accumulate_grad_batches: 1
  enable_checkpointing: False  # Provided by exp_manager
  logger: false  # Provided by exp_manager
  log_every_n_steps: 100  # Interval of logging.
  val_check_interval: 1.0 # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  check_val_every_n_epoch: 1  # RNNT decoding is slower than CTC, so eval takes longer. Increase value to speed up training slightly.
  precision: 32  # RNNT requires a lot of memory, so precision 16 is very important. Use very small batch size for precision 32.
  gradient_clip_val: 1.0  # Gradient norm clip value
  sync_batchnorm: true
  benchmark: false

exp_manager:
  exp_dir: "/nemo/demo_kz/nemo_checkpoint/exp"
  name: *name
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: "val_wer"
    mode: "min"
    save_top_k: 3
    always_save_nemo: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
    entity: null
  resume_if_exists: false
  resume_ignore_no_checkpoint: false

**My python code:**

import nemo.collections.asr as nemo_asr
from ruamel.yaml import YAML
import gc
import torch
	
config_path = 'demo_kz/contextnet_rnnt2.yaml'

yaml = YAML(typ='safe')
with open(config_path) as f:
    params = yaml.load(f)

import pytorch_lightning as pl
from pytorch_lightning import loggers as pl_loggers
tb_logger = pl_loggers.TensorBoardLogger("/nemo/demo_kz/TensorBoard/", name = 'BPE_1000', version = 'ContextNet_1epoch2')

trainer = pl.Trainer(strategy='ddp', gpus=[0, 1, 2, 3], max_epochs=1, logger=tb_logger, precision=16)

from omegaconf import DictConfig
first_asr_model = nemo_asr.models.EncDecRNNTBPEModel(cfg=DictConfig(params['model']), trainer=trainer)

gc.collect()
torch.cuda.empty_cache()

trainer.fit(first_asr_model)

first_asr_model.save_to('demo_kz/checkpoint/ContextNet_1epoch_BPE_10002.nemo')

**I train my model on 4 Titan X server:**

![image](https://user-images.githubusercontent.com/8361949/156880354-7fe7ad34-0a1e-4635-b9a6-8f1b09acdf24.png)

- OS version: Ubuntu
- PyTorch version: torch==1.11.0a0+b6df043
- Python version:  Python 3.8.12
- Nemo: nemo-toolkit==1.5.1

**Comment by 32r81b** [comment]
When I train clasical QuartzNet I use train_ds.batch_size = 50 and don't face any problems.

**Comment by piraka9011** [comment]
@titu1994 could this potentially be related to #3795 as well?
It seems the model is also eventually predicting `??` only.

**Comment by titu1994** [comment]
No, it's not related to issue #3795, cause we are currently training on Spanish and German just fine with Nemo 1.7. 

The issue here is the extremely high LR + very small global batch size. The max LR of 0.05 needs to be reduced to 0.01 or lower, or use gradient accumulation of 4x or 8x should be used to bump up the batch size. You also need warmup - 5k to 10k steps.

**Comment by titu1994** [comment]
Another thing is if you are using a ContextNet large, you can speed up convergence by loading the encoders weights from NGC. If you change your vocab size to 1024 instead of 1000, you could load up the weights for encoder decoder and joint all at once.

**Comment by 32r81b** [comment]
Thank you. I'll try all your advices and post results here. Hope this can help another researchers.

**Comment by 32r81b** [comment]
I try to create streaming ASR for call center. I started from classical QuartzNet 15x5. My be you can advise me another architecture?

**Comment by 32r81b** [comment]
@titu1994, thank you for you answers.
My best experiment for ContextNet is change parameters model from Large to Medium (reduse filters to 512), lr = 0005, batch_size = 40, warm_up = 5000 steps.

![image](https://user-images.githubusercontent.com/8361949/157438867-7bb83cd2-47e1-4dda-83e6-23d456158347.png)
![image](https://user-images.githubusercontent.com/8361949/157438900-4bf36890-1bb0-4376-ab55-f772fff87020.png)

I've decided that I need faster GPU with more mem. Now I trying to work with Small Conformer-Transducer-BPE models. And it looks mutch better:

![image](https://user-images.githubusercontent.com/8361949/157439593-2b98c0a8-85f5-4639-8c00-a3b22993181c.png)
![image](https://user-images.githubusercontent.com/8361949/157439618-aa5a6ef5-2262-4912-a2f7-173fc930d94c.png)

When I try to perform buffered inference I suffering when old predictions changes after adding new chunks. let me explain. I modify code from https://github.com/NVIDIA/NeMo/blob/stable/tutorials/asr/Streaming_ASR.ipynb to predict increasing audio segment. In first loop I transcibe from 0 to 5000 of sound file, second loop from 0 to 10000 and so on.


------------------------------------------------
```
def transcibe2(audio_content):
    blank_id = len(asr_model.decoder.vocabulary)
    audio_signal = torch.as_tensor([audio_content], dtype=torch.float32)
    audio_signal_len = torch.as_tensor([len(audio_content)], dtype=torch.int64)
    audio_signal, audio_signal_len = audio_signal.to(device), audio_signal_len.to(device)
    log_probs, encoded_len, predictions = asr_model(input_signal=audio_signal, input_signal_length=audio_signal_len)
    preds = torch.unbind(predictions)
    all_preds = []
    l = preds[0].tolist()
    l = [x for x in l if x != blank_id]
    text = asr_model.tokenizer.ids_to_text(l)
                                                                                     
    return text
```

```
wav_file = 'concatenated_audio.wav'

with sf.SoundFile(wav_file, 'r') as f:
    samples = f.read(dtype='int16')
    samples = samples.astype('float32')/32768
    samples = samples.transpose()


a = 5000
while True:
    new_text = transcibe2(samples[0:a])
    print(a, new_text)
    a += 5000
```


First word "peter" changes many times to "peeter" and back for 10 seconds. Second word "told" changes to "tolld" and back for 20 seconds. What os the best way to get stable transcribe with bufering inference?


Row result:
```
5000 
10000 
15000 peter
20000 peeter told his
25000 peeter toldd his trouuble
30000 peeter told his troroubless to 
35000 peeter tolld his troubles to to mister s
40000 peeter told his troubles to to misterer shim
45000 peter told his troubles to miister shimmerda
50000 ppeter tolld his trouubles to mmister shimmerda
55000 ppeter tolld his trouubleles to mmister shimmerda
60000 ppeter tolld his trouubles to mmister shimmererda
65000 peter tolld his trouubles to mmister shimmerda
70000 peter told his troubbles to mister shimmerda he was on
75000 peter told his troubles to mister shimmerda he was unable
80000 peter told his troubleles to mister shimmerda he was unaable to to meet
85000 peter told his troubbles to mister shimmerda he was unable to meet a know
90000 peter tolld his troubles to mister shimmerda he was unable to meet a note
95000 peter tolld his troubleles to mister shimmerda he was unaable to meet a note which fell
100000 peter tolld his troubles to mister shimmerda he was unaable to to meet a note whichch fell du
105000 peter tolld his troubleles to mister shimmerda he was unable to to meeet a note w which fell duee on the the
110000 peeter told his troubbles to mister shimmerda he was unable to to meeet a note which fell duee on the the firstt day
115000 peeter told his troubbles to mister shimmerda he was unaable to to meet a note which fell due on the firstt of noveve
120000 peter told his troubleles to mister shimmererda he was unable to to meet a note which fell duee on the first of novemmber
125000 peter told his troubles to mister shimmererda he was unable to to meet a note which fell duee on the first of novemmberer
130000 peter told his troubles to mister shimmererda he was unable to to meet a note which fell duee on the first of novemmber
135000 peeter told his troubleles to mister shimmerda he was unable to to meet a note which fell duee on the first of novemmber had to
140000 peeter told his troubbleles to mister shimmerda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an
145000 peeter told his troubbles to mister shimmerda he was unaable to to meeet a note which fell duee on the first of novemmber had to payy an exorbitit
150000 peeter told his troubleles to mister shimmerda he was unable to to meeet a note which fell duee on the first of novemmber had to pay an exorbbititant
155000 peeter told his troubbles to mister shimmerda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an exorbbititant bonus
160000 peeter told his troubbleles to mister shimmerda he was unaable to to meeet a note which fell duee on the first of novemmber had to pay  an exorbititantt bonus on re
165000 peter told his troubbleles to mister shimmerda he was unaable to to meeet a note which fell duee on the first of novemmber had to pay  an exorbitititant bonus on reneewing it it
170000 peter told his troubbles to mister shimmerda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on renneewing it
175000 peter told his troubbles to mister shimmerda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on reneewinging it
180000 peter told his troubbles to mister shimmerda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on reneewing it
185000 peter told his troubbleles to mister shimmerda he was unaable to to meeet a note which fell duee on the first of novemmber had to pay  an exorbitititant bononus on reneewing it and to give
190000 peter told his troubbleles to mister shimmerda he was unaable to to meeet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on reneewing it and to give a more
195000 peter told his troubbleles to mister shimmerda he was unaable to meeet a note which fell duee on the first of novemmber had to pay  an exorbitititant bononus on reneewing it and to give a mortggage on
200000 peter told his troubbles to mister shimmerda he was unaable to to meeet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on reneewing it and to give a morttgage on his
205000 peter told his troubleles to mister shimmererda he was unaable to to meeet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on reneewwinging it and to give a morttggage on his ppigs
210000 peter told his troubbleles to mister shimmerda he was unaable to to meeet a note which fell duee on the first of novemmber had to pay  an exorbitititant bononus on reneewinging it and and to give a mortggage on his piggs and hors
215000 peter told his troubbles to mister shimmererda he was unaable to to meeet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on reneewing it and to give a mortggage on his pigs and horses
220000 peter told his troubbles to mister shimmerda he was unaable to meeet a note which fell duee on the first of novemmber had to pay  an exorbitititant bononus on reneewinging it and to give a mortggagee on his pigs and horses and even
225000 peter told his troubbleles to mister shimmerda he was unaable to to meeet a note which fell dduee on the first of novemmber had to pay  an exorbitititant bononus on reneewinging it and to give a mortggagee on his pigs and horses and  even his mo
230000 peter told his troubbles to mister shimmerda he was unaable to to meeet a note which fell dduee on the first of novemmber had to pay  an exorbitititant bononus on reneewing it and to give a mortggage on his pigs and horses and eeven his milk
235000 peter told his troubbles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmberer had to pay an exorbitititant bononusus on reneewing it and to give a mortggage on his pigs and horses and eeven his mmilk cow
240000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmberer had to pay an exorbitititant bononus on reneewing it and to give a mortggage on his pigs and horses and eeven his milk cow
245000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an exorbitititant bononusus on reneewing it and to give a mortggage on his pigs and horses and eeven his milk cow
250000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an exorbitititant bononusus on reneewing it and to give a mortggage on his pigs and horses and eeven his milk cow
255000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmberer had to pay an exorbitititant bononus on reneewing it and to give a mortggage on his pigs and horses and eeven his milk cow ppeter
260000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmber had to pay  an exorbitititant bononus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter co could give
265000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peter could give no
270000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmber had to pay an exorbitititant bononus on reneewing it and and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very
275000 peter told his troubbleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmber had to payy  an exorbitititant bononus on reneewing it and to give a morrtggagee on his pigs and horses and eeven his milk cow peeter could give no very clear
280000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmber had to pay  an exorbitititant bononus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no  very clear accoununt
285000 peter told his troubbleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmber had to pay  an exorbitititant bononus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoount of his
290000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmber had to pay  an exorbitititant bononus on reneewing it and to give a mortggagee on his pigs and horses and eeven his milk cow peeter could give no very clear acccoount of his transs
295000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmber had to payy an exorbitititant bononus on reneewing it and to give a mortggagee on his pigs and horses and eeven his milk cow peeter could give no very clear accoount of his transsaction
300000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bononus on reneewing it it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his trransactionions with
305000 peter tolld his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmber hadd to payy an exorbitititant bonus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsacctions with cuttter
310000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmberer hadd to pay  an exorbitititant bonus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsacctions with cutter
315000 peter tolld his troubles to mister shimmererda he was unaable to to meet a note which fell duee on the first of novemmberer had to pay  an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsacctions with cuttter
320000 peter tolld his troubles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer hadd to pay an exorbitititant bonus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter
325000 peter tolld his troubles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she askeded
330000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his t transsactions with cuttter she asskeded p
335000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his t transsactions with cuttter she asked peter to
340000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to payy an exorbitititant bonus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she assked  peeter to wait a momm
345000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she asked peter to wait a mommment
350000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay  an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she asked peter to waait a mommment
355000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she asked peter to w waait a mommment and when she
360000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she askked peter to wait a mommment and when she came
365000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to payy an exorbitititant bonus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she asked peter to wait a mommment and when she came back from
370000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it and to give a morrtggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she asked peter to wait a mommment and when she came back from the kitchenen
375000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his mmilk cow peeter could give no very clear accoountt of his transsactions with cuttter she askked peter to waait a mommment and whhen she came back from the kititchen
380000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to payy an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she asked peter to waait a mommment and whhen she came back from the kititchen she
385000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to payy an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she asked peter to waait a mommment and whhen she came back from the kitchen she brought a a
390000 peter told his troubleles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to payy an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his milk cow peeter could give no very clear accoountt of his transsactions with cuttter she asked peter to waait a mommment and whhen she came back from the kitchen she brought a bag of
395000 peter told his troubles to mister shimmererda he was unaable to to meet a note which fell dduee on the first of novemmberer had to pay an exorbitititant bonus on reneewing it and to give a morttggage on his pigs and horses and eeven his mmilk cow peeter could give no very clear accoountt of his transsactions with cuttter she askked peter to waait a mommment and whhen she came back from the kitchen she broughtt a bag of sandwwwich
```

**Comment by 32r81b** [comment]
My be that KenLM help me to resolve thise problem?

**Comment by titu1994** [comment]
You cant use kenlm with transducers, at least not yet. And they have an implicit LM if in them - your models are not tuned / converged yet ~ 55% WER on the dev set. In any case, instead of using the ctc Steaming ASR tutorial, I pointed to this one - https://github.com/NVIDIA/NeMo/blob/stable/tutorials/asr/Buffered_Transducer_Inference.ipynb - it is the equivalent for RNNT models. 

Ofc your current approach will work too - but the if you use proper buffered merging you wont get repeated characters etc. It could also be that your model simply hasn't trained enough to give proper results. 

The contextnet hyper parameters seem off - the medium model should have LR 0.01 etc. Well conformed small works so maybe dataset is small enough to quickly overfit with large/med models.
