### ISSUE TITLE
QuartzNet-5x5 pretrained weights

### ISSUE THREAD

**Issue by tugstugi** [NVIDIA/NeMo#380]
The QuartzNet paper reports LibriSpeech results for QuartzNet-5x5 and QuartzNet-10x5. Is it possible to share these pretrained weights?

**Comment by jonathan-cohen-nvidia** [comment]
Just want to let you know we are looking into it. Will have an update soon, although not sure of the timeframe.

**Comment by aquinovo** [comment]
@tugstugi check this link: https://ngc.nvidia.com/catalog/models/nvidia:quartznet_15x5_ls_sp

**Comment by tugstugi** [comment]
tnx
