### ISSUE TITLE
Missing dependencies in TTS examples

### ISSUE THREAD

**Issue by evelyn-f-king** [NVIDIA/NeMo#3802]
**Describe the bug**
Pyini (and probably some other things) are missing when running in a Colob environment.

**Steps/Code to reproduce bug**
Run FastPitch_Finetuning.ipynb on a Colab instance.

**Expected behavior**
Unless I'm missing something, I should be able to hit run all after I uncomment the first few lines to fetch dependencies, right? 
**Environment overview (please complete the following information)**
Colab
**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version - colab
- PyTorch version 1.10.0+cu111
- Python version  - Python 3.7.12

**Additional context**
I keep hitting this regardless of which notebook I pick.

**Comment by evelyn-f-king** [comment]
Also, as noted in #3687, you have to change the first line to fetch the right Git repo as well

**Comment by evelyn-f-king** [comment]
just spun up an instance from the container & it works fine

**Comment by okuchaiev** [comment]
please don't forget to close issues when they are resolved.
