### ISSUE TITLE
Problem loading wavfiles using AudioSegment.

### ISSUE THREAD

**Issue by sjkoelle** [NVIDIA/NeMo#3813]
**Describe the bug**

I am getting a bug loading wavfiles using AudioSegment.

File /mnt/disks/uberduck-experiments-v0/NeMo/nemo/collections/asr/parts/preprocessing/segment.py:180, in AudioSegment.from_file(cls, audio_file, target_sr, int_values, offset, duration, trim, orig_sr)
    178     if duration > 0:
    179         seconds = duration * 1000
--> 180         samples = samples[: int(seconds)]
    181     samples = np.array(samples.get_array_of_samples())
    182 except CouldntDecodeError as err:

File /opt/conda/envs/ub_march/lib/python3.8/site-packages/pydub/audio_segment.py:331, in AudioSegment.__getitem__(self, millisecond)
    326     if missing_frames > self.frame_count(ms=2):
    327         raise TooManyMissingFrames(
    328             "You should never be filling in "
    329             "   more than 2 ms with silence here, "
    330             "missing frames: %s" % missing_frames)
--> 331     silence = audioop.mul(data[:self.frame_width],
    332                           self.sample_width, 0)
    333     data += (silence * missing_frames)
    335 return self._spawn(data)

error: Size should be 1, 2, 3 or 4

Here, size refers to "self.sample_width" I believe

**Steps/Code to reproduce bug**

```
from nemo.collections.asr.parts.preprocessing import AudioSegment
file_path=  path_to_wav
AudioSegment.from_file(
file_path,
target_sr=22050,
int_values=True,
offset=0,
duration=1000,
trim=0,
orig_sr=22050,
)
```

**Expected behavior**

I would expect this to load the file.  scipy.io.wavfile.read is able to load file_path no problem.

**Environment overview (please complete the following information)**

GCP
NeMo from source (download and ./reinstall.sh)

**Environment details**

- Debian GNU/Linux 10
- PyTorch '1.10.2+cu102'
- Python 3.8

**Additional context**

T4 GPU
These files load on a Collab notebook running NeMo 1.0.2 and Pydub 25.1. However, when I install NeMo 1.0.1 and Pydub on this GCP machine, I get the same error.

Any help appeciated.  Thanks!

**Comment by titu1994** [comment]
We don't support such old Nemo versions, please use 1.7 or higher as that is the latest release. 

Your error is also from pydub, you might try asking there - File /opt/conda/envs/ub_march/lib/python3.8/site-packages/pydub/audio_segment.py:331, in AudioSegment.getitem(self, millisecond)
326 if missing_frames > self.frame_count(ms=2):
327 raise TooManyMissingFrames(
328 "You should never be filling in "
329 " more than 2 ms with silence here, "
330 "missing frames: %s" % missing_frames)

**Comment by sjkoelle** [comment]
Hey, sorry. This was from NeMo 1.7.0.

**Comment by titu1994** [comment]
We cant support every single parameterization of pydub, cause that would require very low level control of file handling by users. The fact that it works on colab but fails on GCP reflects more to the fact that the environment on GCP is somehow not updated enough to read the file (though then again, I presume maybe incorrectly that colab runs on the same container as GCP provides).
