### ISSUE TITLE
ASR transcription using citrinet or quartznet models sometimes does not give output in proper English words.

### ISSUE THREAD

**Issue by claratang98** [NVIDIA/NeMo#3814]
This issue was just created to understand the internal model of the engines. I understand that the engine uses language and lexicon pronunciation model. Doesnt that mean that the output should be in proper English words at the very least?

**Comment by titu1994** [comment]
No there's no guarantee of that. ASR models are alignment learning models - they don't have some innate knowledge of what tokens they skipped or not. If the acoustic encoder does not get context or cannot derive features that correspond to some text character it will simply replace with blank and move on to the next timestep.
