### ISSUE TITLE
Cant load model from path with 1.6

### ISSUE THREAD

**Issue by allandialpad** [NVIDIA/NeMo#3832]
I have a 1.6 model trying to load with the following line:

`nemo_asr.models.EncDecCTCModelBPE.restore_from`

And I get this:

```
[NeMo E 2022-03-11 17:35:11 common:504] Traceback (most recent call last):
      File "/root/.cache/pypoetry/virtualenvs/--IulmO6hw-py3.7/lib/python3.7/site-packages/nemo/core/classes/common.py", line 477, in from_config_dict
        instance = imported_cls(cfg=config, trainer=trainer)
      File "/root/.cache/pypoetry/virtualenvs/--IulmO6hw-py3.7/lib/python3.7/site-packages/nemo/collections/asr/models/ctc_bpe_models.py", line 194, in __init__
        self._setup_tokenizer(cfg.tokenizer)
      File "/root/.cache/pypoetry/virtualenvs/--IulmO6hw-py3.7/lib/python3.7/site-packages/nemo/collections/asr/parts/mixins/mixins.py", line 84, in _setup_tokenizer
        self.tokenizer = tokenizers.SentencePieceTokenizer(model_path=model_path)
      File "/root/.cache/pypoetry/virtualenvs/--IulmO6hw-py3.7/lib/python3.7/site-packages/nemo/utils/exceptions.py", line 31, in __init__
        raise LightningNotInstalledException(self)
    nemo.utils.exceptions.LightningNotInstalledException:  You are trying to use <nemo.collections.common.tokenizers.SentencePieceTokenizer object at 0x7f582a0ad950> without installing all of pytorch_lightning, hydra, and omegaconf. Please install those packages before trying to access <nemo.collections.common.tokenizers.SentencePieceTokenizer object at 0x7f582a0ad950>.
    
```

All there of those packages are installed and importable

**Comment by titu1994** [comment]
How was Nemo installed? Follow the instructions in the document page for installation - either "all" or "asr" must be used to properly select the ASR requirements

**Comment by allandialpad** [comment]
asr was used

**Comment by titu1994** [comment]
We're all these steps executed - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/starthere/intro.html#installation

**Comment by SonuKumari1690** [comment]
Hi, could you please help with your confirmation,
I am using below command to install the nemo 1.6.1 
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@{BRANCH}#egg=nemo_toolkit[all]

And below notebook to work on text classification part

https://colab.research.google.com/github/NVIDIA/NeMo/blob/v1.0.0/tutorials/nlp/Text_Classification_Sentiment_Analysis.ipynb#scrollTo=knF6QeQQdMrH

This is the same notebook I used with 1.4 I hope the same will work in terms of method calling for nemo 1.6 as well

**Comment by SonuKumari1690** [comment]
@titu1994: Can you confirm if Nemo 1.6 supports "biomegatron-bert-345m-uncased" as from the list of models I dont see "biomegatron-bert-345m-uncased" even tried passing "biomegatron-bert-345m-uncased" explictly but while training model I have received "ValueError: biomegatron-bert-345m-uncased is not supported by HuggingFace"

**Comment by allandialpad** [comment]
I havnt seen the error since that day, you can close this issue and Ill post again if I see it
