### ISSUE TITLE
SyntaxError with Colab Example

### ISSUE THREAD

**Issue by mrinal-sourav** [NVIDIA/NeMo#3849]
I am running the following ipynp on my Colab:
https://github.com/NVIDIA/NeMo/blob/v1.0.2/tutorials/asr/01_ASR_with_NeMo.ipynb 

I only replaced the data set to speech commands from "an4" as it seems the link for an4 is not working. 

In the section "Using NeMo for Automatic Speech Recognition", the very first cell where I import nemo:

NeMo's "core" package
import nemo
NeMo's ASR collection - this collections contains complete ASR models and
building blocks (modules) for ASR
import nemo.collections.asr as nemo_asr

I get the following output:
[NeMo W 2022-03-17 16:03:28 optimizers:46] Apex was not found. Using the lamb optimizer will error out.

  File "/usr/local/lib/python3.7/dist-packages/webdataset/cache.py", line 43
    while data := stream.read(chunk_size):
                ^
SyntaxError: invalid syntax

Could anyone please point at a fix for this?

**Comment by titu1994** [comment]
The dataset for speech recognition and speech commands are not the same. Please review the tutorial for speech command to see what changes are necessary to the manifest. 

In addition, please use a newer version of Nemo - the latest is 1.7 and the branch you are trying is 1.0.2 which is a year and a half old.

**Comment by gschian0** [comment]
After upgrading the version of nemo to current version the first error on this thread was corrected ... I am here now ..
`
ImportError: cannot import name 'ProbsType' from 'nemo.core.neural_types.elements' (/usr/local/lib/python3.7/dist-packages/nemo/core/neural_types/elements.py)
`

**Comment by mrinal-sourav** [comment]
Upgraded to 1.7, but I think what actually helped me was to use one runtime for data preprocessing and another runtime for inference from nemo on the processed data.

**Comment by titu1994** [comment]
@mrinal-sourav that should not be required. We use the data loader internally when we transcribe anyway.
