### ISSUE TITLE
NeuralModuleFactory not found

### ISSUE THREAD

**Issue by klm122** [NVIDIA/NeMo#3850]
Dear All,

Thanks for the great job you are doing.

When trying to use NeuralModuleFactory, I have the following error:

ModuleNotFoundError: No module named 'nemo.core.NeuralModuleFactory'

I am stick and need your help on how to solve this problem.

Best regards

**Comment by titu1994** [comment]
That was part of no 0.x, deprecated for around 2 years. Please review the current Nemo codebase and documentation.
