### ISSUE TITLE
Efficient programmatic interactions with DataLayer

### ISSUE THREAD

**Issue by jaberkow** [NVIDIA/NeMo#386]
I have a use case where I'd like to run something like the inference path in `examples/asr/jasper_eval.py` for several different slices of the data.  Naively, I intend to iterate over the different slices of the data using a for loop and create a different manifest file inside each iterate of the loop.  My questions are as follows:

1. Is it necessary to reinstantiate the AudioToTextDataLayer neural module each time the manifest file changes?  If not, is there a more efficient way to programmatically interact with instances of AudioToTextDataLayer?
2. Instead of writing a file for each manifest, is it possible to just pass a properly formatted JSON string to the constructor instead?

**Comment by vsl9** [comment]
You can create your own customized DataLayer neural module and use a single instance. Please have a look at `AudioDataLayer` class in the notebook: https://github.com/NVIDIA/NeMo/blob/master/examples/asr/notebooks/2_Online_ASR_Microphone_Demo.ipynb
