### ISSUE TITLE
I'm getting syntax error  trying loading nlp (webdataset  import)

### ISSUE THREAD

**Issue by vitotitto** [NVIDIA/NeMo#3865]
from nemo.collections import nlp as nemo_nlp gives me an error 

```
File "/usr/local/lib/python3.7/dist-packages/webdataset/cache.py", line 43
    while data := stream.read(chunk_size):
                ^
SyntaxError: invalid syntax
```

that looks to originate in webdataset  import. 
The webdataset version 0.2.4
and the last version of Nemo. 

Anyone can help?

**Comment by MaximumEntropy** [comment]
We don't support the latest version of webdataset yet, please take look at the version requirement in requirements_lightning.txt

**Comment by MaximumEntropy** [comment]
Does this mean you changed the webdataset file directly?

**Comment by MaximumEntropy** [comment]
You can also fix this by downgrading webdatast or updating python to 3.8/3.9.
