### ISSUE TITLE
Conformer model support for Speaker Diarization

### ISSUE THREAD

**Issue by rafiuddinkhan** [NVIDIA/NeMo#3878]
I tried offline Diarization with ASR using the following models
1. stt_en_quartznet15x5 
2. stt_en_conformer_ctc_large
3. stt_en_citrinet_1024
But running the sample code for diarization with asr works for the first and third models. The second model conformer ctc large is giving blank output with the following message: 
->Only EncDecCTCModelBPE models trained with per_feature normalization are supported currently. 
I tried with the example notebook of the NeMo repository as well. 
<img width="978" alt="Screenshot 2022-03-23 at 11 37 01 PM" src="https://user-images.githubusercontent.com/10113553/159766811-04288452-46a5-4531-a9a2-f162a49fd21b.png">

[[Ref source link]
](https://github.com/NVIDIA/NeMo/tree/main/examples/speaker_tasks/diarization)
<img width="702" alt="Screenshot 2022-03-23 at 11 33 45 PM" src="https://user-images.githubusercontent.com/10113553/159766263-b5e3ab3b-dcac-4e5f-8204-f71d3577e0b0.png">

Please suggest a solution if I am missing something or is it not supported yet by the NeMo stack yet.

Thanks,
Rafi

**Comment by rafiuddinkhan** [comment]
@tango4j please update on this

**Comment by VahidooX** [comment]
You should not get that warning as all ASR models are trained with per_feature normalization. So when you load the stt_en_conformer_ctc_large model, what is the value for asr_model._cfg.preprocessor.normalize?

**Comment by rafiuddinkhan** [comment]
@VahidooX I have used the default setting :
```cfg.diarizer.asr.model_path = 'stt_en_conformer_ctc_large'
cfg.diarizer.oracle_vad = False # ----> Not using oracle VAD 
cfg.diarizer.asr.parameters.asr_based_vad = True
cfg.diarizer.asr.parameters.threshold=100 # ASR based VAD threshold: If 100, all silences under 1 sec are ignored.
cfg.diarizer.asr.parameters.decoder_delay_in_sec=0.2 

I am running this tutorial but when I used conformed variant then it says that Only EncDecCTCModelBPE models trained with per_feature normalization are supported currently. can you please check this link;
https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/ASR_with_SpeakerDiarization.ipynb

**Comment by rafiuddinkhan** [comment]
@VahidooX @titu1994

**Comment by tango4j** [comment]
Hi @rafiuddinkhan. Sorry that I didn't check your issue promptly.

**Comment by rafiuddinkhan** [comment]
Thanks @tango4j

**Comment by tango4j** [comment]
This bug fix will be merged with [torch_update_vad_sd](https://github.com/NVIDIA/NeMo/tree/torch_update_vad_sd) branch, so I will close this issue.
