### ISSUE TITLE
Python 3.9 Support

### ISSUE THREAD

**Issue by lopez86** [NVIDIA/NeMo#3880]
Are there plans to add python 3.9 as one of the supported python versions?

The current documentation says that only up to 3.8 is supported but there are some suggestions to use 3.9 in other issues, and I haven't found any discussion of updating the supported versions to include it.

**Comment by titu1994** [comment]
There shouldn't be any implicit compatibility issue of Nemo with python 3.9, but it's underlying libraries might not support it - for example Numba, pytorch, apex etc.

**Comment by okuchaiev** [comment]
pushed little update to main. re-open if something breaks on 3.9
