### ISSUE TITLE
Get 404 client error when I execute example in /blob/main/tutorials/nlp/Relation_Extraction-BioMegatron.ipynb

### ISSUE THREAD

**Issue by wielh** [NVIDIA/NeMo#3894]
**Describe the bug**

In website https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Relation_Extraction-BioMegatron.ipynb， I run the code step by step, and i get the 404 client error on the last line of chapter "Setting up a NeMo Experiment"

**Steps/Code to reproduce bug**

model = nemo_nlp.models.TextClassificationModel(cfg=config.model, trainer=trainer) in chapter "[Setting up a NeMo Experiment](url)"

**Environment overview (please complete the following information)**

 - Method of NeMo install:  Google Colaboratory, 
 
**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- python 3.7.13
- pytorch 1.10.0 
- cuda 11.1

**Comment by titu1994** [comment]
Can you paste the error log ?

**Comment by wielh** [comment]
![error](https://user-images.githubusercontent.com/73090953/160983462-23086f6a-1728-46d9-9388-40332a8e50d9.png)

**Comment by wielh** [comment]
![error](https://user-images.githubusercontent.com/73090953/160983511-6489711f-8627-4767-b664-268f03d561aa.png)

**Comment by wielh** [comment]
![error](https://user-images.githubusercontent.com/73090953/160984488-db04fe92-d8a6-4fca-8b20-fa3c618db88f.png)
