### ISSUE TITLE
`helpers.cpp:25:10: fatal error: pybind11/pybind11.h: No such file or directory` error when calling `compile_helper`

### ISSUE THREAD

**Issue by jpilaul** [NVIDIA/NeMo#3899]
**Describe the bug**

```python
from nemo.collections.nlp.data.language_modeling.megatron.dataset_utils import compile_helper
compile_helper()
```
Throws the following error:
```
/usr/bin/python3: No module named pybind11
g++ -O3 -Wall -shared -std=c++11 -fPIC -fdiagnostics-color  helpers.cpp -o helpers.cpython-38-x86_64-linux-gnu.so
helpers.cpp:25:10: fatal error: pybind11/pybind11.h: No such file or directory
   25 | #include <pybind11/pybind11.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:23: helpers.cpython-38-x86_64-linux-gnu.so] Error 1
[NeMo E 2022-03-29 09:34:40 dataset_utils:77] Making C++ dataset helpers module failed, exiting.
```
**Expected behavior**

Should not throw an error.

**Environment overview (please complete the following information)**

 - Environment location: metal
 - Method of NeMo install: from source

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 20.04.2
- PyTorch version: 1.10.0+cu113
- Python version: 3.8

**Comment by bhavitvyamalik** [comment]
This problem can be fixed by running `pip install pybind11`
