### ISSUE TITLE
Tacotron2 ipynb not working. Hydra issue.

### ISSUE THREAD

**Issue by huwprosser** [NVIDIA/NeMo#3915]
**Describe the bug**

When running the tutorial notebook for Tacotron2 training in Google Colab. A Hydra issue is raised:
`Traceback (most recent call last):
File "[tacotron2.py](http://tacotron2.py/)", line 44, in <module>
main()  # noqa pylint: disable=no-value-for-parameter
File "/usr/local/lib/python3.7/dist-packages/nemo/core/config/hydra_runner.py", line 103, in wrapper
strict=None,
TypeError: _run_hydra() got an unexpected keyword argument 'strict'`

**Steps/Code to reproduce bug**

Running each cell of the Tacotron2 tutorial notebook in a new Colab session. NOTE: Lines in the first cell were uncommented as per the instructions. 

**Expected behavior**

Training to begin without error on the example dataset provided.

**Environment overview (please complete the following information)**

 - Environment location: Collab
 - Method of NeMo install: As per instructions within notebook. Please specify exact commands you used to install.

**Comment by Arjunprasaath** [comment]
@huwprosser go to this file `/usr/local/lib/python3.7/dist-packages/nemo/core/config/hydra_runner.py line 103` and just remove the argument `strict` as it is just set to `None`. Also make sure you check the return values and input args as well.
