### ISSUE TITLE
json.dumps and non English characters

### ISSUE THREAD

**Issue by demsarjure** [NVIDIA/NeMo#3922]
**Describe the bug**

NeMo uses the `json.dumps` function to save dictionaries to JSON files. `json.dumps` is problematic when there are non-English characters involved. For example, I work with the Slovenian language and `json.dumps` will printout `\u0161` instead of `č` at all locations. To resolve this you need to use the `ensure_ascii=False` option for `json.dumps`. I saw that at a couple of location NeMo already uses this but at the majority locations it does not.

**Steps/Code to reproduce bug**

Run `examples/asr/asr_chunked_inference/rnnt/speech_to_text_buffered_infer_rnnt.py` or a similar transcription script with a model for a language that has non-English characters and inspect the transcript.

**Expected behavior**

Non-English characters should be printed properly in outputs and not as a unicode number.

**Environment overview (please complete the following information)**

NeMo container 22.01.

**Proposed solution**

Add `ensure_ascii=False` to all `json.dumps` calls in NeMo. If you are interested in this, I can prepare a PR.

**Comment by titu1994** [comment]
Ensure_ascii=true as a default is a preferred everywhere precisely because not all environments default to utf8 encoding. The explicit \u forces  manifest to correctly decode in all environments. 

We have tried setting it too false, and it will continue to work with Nemo dataloaders but you need to take care not to leave trailing new lines or other tokens otherwise the manifest cannot be resolved. 

For ease of use, we'd prefer to keep the current behaviour as is.

**Comment by itzsimpl** [comment]
Environments where this becomes "important", I assume, do default to utf8 encoding, i.e. they are non-English mostly non-ascii. I remember #3520, which addressed the input. Would it be, perhaps, in this case, a good idea to introduce a global setting for export, meaning that based on their environment one can simply set a global variable to do `ensure_ascii` or not (with the default setting of `true` to retain backwards compatibility). This would allow one to setup the output in the way they prefer, for the environment they are working in. Unfortunately this would need to be a Nemo setting as I do not recall `json` or `ujson` supporting such a feature (i.e. a global setting of `ensure_ascii`).

**Comment by titu1994** [comment]
It would require messy monkey patching to make such a global flag in Nemo side to correct json file rw, which I would rather avoid. 

Users can chose to use this method by adding the flag manually to their scripts when building configs, and if the Nemo dataloader can parse the manifest the training should go well enough.
