### ISSUE TITLE
In notebook colab "TTS Inference Prosody Control" an error has been made.

### ISSUE THREAD

**Issue by Nikuson123** [NVIDIA/NeMo#3938]
In notebook colab:
https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/tts/Inference_DurationPitchControl.ipynb

an error has been made.

instead of:

# Load the models from NGC
fastpitch = FastPitchModel.from_pretrained("tts_en_fastpitch").eval().cuda()
hifigan = HifiGanModel.from_pretrained("tts_hifigan").eval().cuda()

Should be:

# Load the models from NGC
fastpitch = FastPitchModel.from_pretrained("tts_en_fastpitch")
hifigan = HifiGanModel.from_pretrained(model_name="tts_hifigan")

**Comment by redoctopus** [comment]
The current notebook code with `.eval().cuda()` works when I try it on Colab. Are you sure you've connected to an instance with a GPU? (Runtime -> Change runtime type -> select "GPU" under "Hardware accelerator")

**Comment by Nikuson123** [comment]
> Текущий код блокнота `.eval().cuda()`работает, когда я пробую его в Colab. Вы уверены, что подключились к экземпляру с GPU? (Среда выполнения -> Изменить тип среды выполнения -> выберите «GPU» в разделе «Аппаратный ускоритель»)

I definitely connected with the GPU, the problem was in the model name
