### ISSUE TITLE
Error while doing diarization

### ISSUE THREAD

**Issue by manchandasahil** [NVIDIA/NeMo#3952]
**Describe the bug**

I am following the ASR with speaker diarization on some wav files. It fails on some files giving the following error.

_LinAlgError
----> 1 diar_hyp, diar_score = asr_diar_offline.run_diarization(cfg, word_ts_hyp)

File /opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/diarization_utils.py:238, in ASR_DIAR_OFFLINE.run_diarization(self, diar_model_config, word_timestamps)
    235     diar_model_config.diarizer.vad.external_vad_manifest = oracle_manifest
    237 diar_model = ClusteringDiarizer(cfg=diar_model_config)
--> 238 score = diar_model.diarize()
    239 if diar_model_config.diarizer.vad.model_path is not None and not diar_model_config.diarizer.oracle_vad:
    240     self.get_frame_level_VAD(vad_processing_dir=diar_model.vad_pred_dir)

File /opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/clustering_diarizer.py:424, in ClusteringDiarizer.diarize(self, paths2audio_files, batch_size)
    419 embs_and_timestamps = get_embs_and_timestamps(
    420     self.multiscale_embeddings_and_timestamps, self.multiscale_args_dict
    421 )
    423 # Clustering
--> 424 all_reference, all_hypothesis = perform_clustering(
    425     embs_and_timestamps=embs_and_timestamps,
    426     AUDIO_RTTM_MAP=self.AUDIO_RTTM_MAP,
    427     out_rttm_dir=out_rttm_dir,
    428     clustering_params=self._cluster_params,
    429 )
    431 # TODO Resegmentation -> Coming Soon
    432 
    433 # Scoring
    434 score = score_labels(
    435     self.AUDIO_RTTM_MAP,
    436     all_reference,
   (...)
    439     ignore_overlap=self._diarizer_params.ignore_overlap,
    440 )

File /opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/speaker_utils.py:346, in perform_clustering(embs_and_timestamps, AUDIO_RTTM_MAP, out_rttm_dir, clustering_params)
    343 else:
    344     num_speakers = None
--> 346 cluster_labels = COSclustering(
    347     uniq_embs_and_timestamps=embs_and_timestamps[uniq_id],
    348     oracle_num_speakers=num_speakers,
    349     max_num_speaker=max_num_speakers,
    350     enhanced_count_thres=clustering_params.enhanced_count_thres,
    351     max_rp_threshold=clustering_params.max_rp_threshold,
    352     sparse_search_volume=clustering_params.sparse_search_volume,
    353     cuda=cuda,
    354 )
    356 base_scale_idx = max(embs_and_timestamps[uniq_id]['scale_dict'].keys())
    357 lines = embs_and_timestamps[uniq_id]['scale_dict'][base_scale_idx]['time_stamps']

File /opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/nmesc_clustering.py:663, in COSclustering(uniq_embs_and_timestamps, oracle_num_speakers, max_num_speaker, min_samples_for_NMESC, enhanced_count_thres, max_rp_threshold, sparse_search_volume, fixed_thres, cuda)
    651 nmesc = NMESC(
    652     mat,
    653     max_num_speaker=max_num_speaker,
   (...)
    659     cuda=cuda,
    660 )
    662 if emb.shape[0] > min_samples_for_NMESC:
--> 663     est_num_of_spk, p_hat_value = nmesc.NMEanalysis()
    664     affinity_mat = getAffinityGraphMat(mat, p_hat_value)
    665 else:

File /opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/nmesc_clustering.py:486, in NMESC.NMEanalysis(self)
    484 self.p_value_list = self.getPvalueList()
    485 for p_value in self.p_value_list:
--> 486     est_num_of_spk, g_p = self.getEigRatio(p_value)
    487     est_spk_n_dict[p_value] = est_num_of_spk
    488     eig_ratio_list.append(g_p)

File /opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/nmesc_clustering.py:550, in NMESC.getEigRatio(self, p_neighbors)
    530 """
    531 For a given p_neighbors value,
    532 calculates g_p, which is a ratio
   (...)
    546         The ratio between p_neighbors value and the maximum eigen gap value.
    547 """
    549 affinity_mat = getAffinityGraphMat(self.mat, p_neighbors)
--> 550 est_num_of_spk, lambdas, lambda_gap_list = estimateNumofSpeakers(affinity_mat, self.max_num_speaker, self.cuda)
    551 arg_sorted_idx = np.argsort(lambda_gap_list[: self.max_num_speaker])[::-1]
    552 max_key = arg_sorted_idx[0]

File /opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/nmesc_clustering.py:329, in estimateNumofSpeakers(affinity_mat, max_num_speaker, is_cuda)
    319 """
    320 Estimate the number of speakers using eigen decompose on laplacian Matrix.
    321 affinity_mat: (array)
   (...)
    326     if cuda availble eigh decomposition would be computed on GPUs
    327 """
    328 laplacian = getLaplacian(affinity_mat)
--> 329 lambdas, _ = eigDecompose(laplacian, is_cuda)
    330 lambdas = np.sort(lambdas)
    331 lambda_gap_list = getLamdaGaplist(lambdas)

File /opt/conda/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/nmesc_clustering.py:304, in eigDecompose(laplacian, cuda, device)
    302 else:
    303     laplacian = torch.from_numpy(laplacian).float()
--> 304 lambdas, diffusion_map = eigh(laplacian)
    305 lambdas = lambdas.cpu().numpy()
    306 diffusion_map = diffusion_map.cpu().numpy()

_LinAlgError: torch.linalg.eigh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 566).

**Steps/Code to reproduce bug**
Following this notebook exactly : https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/ASR_with_SpeakerDiarization.ipynb

**Expected behavior**

Expected to run diarization with ASR successfully

**Environment overview (please complete the following information)**

 - Environment location: Docker
 - Method of NeMo install: RUN pip install nemo_toolkit[asr]
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Using nvidia Image : FROM nvcr.io/nvidia/pytorch:21.04-py3

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by tango4j** [comment]
Can you share the wav file?

**Comment by manchandasahil** [comment]
> Hi, Thank you for reporting this error. The problem is arising at speaker clustering process. The affinity matrix created during the clustering process seems ill-conditioned. This is only reported by users and couldn't be reproduced with the samples we have.
> 
> Can you share the input wav file?
> 
> If you cannot share it, Can you reproduce the error with a wav file that you can share ? Also if you can share how long is the input wav file, that will be helpful.
> 
> Plus, I suggest the following fix. Use multiscale for clustering as follows and see if helps.
> 
> ```
>      parameters.window_length_in_sec=[1.5,1.0,0.5] \
>      parameters.shift_length_in_sec=[0.75,0.5,0.25] \
>      parameters.multiscale_weights=[0.33,0.33,0.33] \
> ```
> 
> Multiscale input will increase the number of segments so that created graph could be more stable.

Thank you @tango4j for the suggestions. Unfortunately, I cannot share the wav but i am trying to reproduce the error on a wav file that i can share. 
I have tried the suggestions that you provided but i still have the issue unfortunately. I am trying it now on a public dataset and will report if i get the same error in a couple of days !

**Comment by tango4j** [comment]
Hi, I ran the sample you gave me and it runs without a problem with our ``1.10.2+cu113`` setup. Could you try updating pytorch to the newest version? and could you share your current version by checking ``import torch; torch.__version__``

**Comment by nithinraok** [comment]
@manchandasahil can you share these details with the container you are using:
* OS version
* PyTorch version
* Python version 
* NeMo version

**Comment by manchandasahil** [comment]
> @manchandasahil can you share these details with the container you are using:
> 
> * OS version
> * PyTorch version
> * Python version
> * NeMo version

I am using 

nvidia Image : FROM nvcr.io/nvidia/pytorch:21.04-py3
import torch; torch.__version__.      is   '1.12.0a0+2c916ef'
nemo.__version__ is '1.8.0rc0'
Python : Python 3.8.12

**Comment by nithinraok** [comment]
@manchandasahil ... @tango4j  tested the audio you shared locally on conda environment outside of the container. 

Let me test on the container as soon as possible, before I try that I would suggest you, run locally using conda environment to avoid facing issues due to versions mis match.

**Comment by nithinraok** [comment]
I just tried using docker container and it ran without any issue:

Use the following steps:
* Pull 22.03 pytorch docker container from [https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch)
* run the container using downloaded image with `docker run --gpus all -it --rm -v <nemo_github_folder>:/NeMo --shm-size=8g \
-p 8888:8888 -p 6006:6006 --ulimit memlock=-1 --ulimit \
stack=67108864 --device=/dev/snd nvcr.io/nvidia/pytorch:22.03-py3` 
* cd `/NeMo` and run `bash reinstall.sh` -> This will install nemo and necessary python packages
* After this step you should have following versions
> pytorch: 1.12.0a0+2c916ef 
> NeMo: 1.9.0rc0 
* run the mentioned notebook. 
* Note: Skip installation of nemo and torch packages from first cell of notebook, since we already installed them with above `bash reinstall.sh` command
```
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[asr]

## Install TorchAudio
!pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by nithinraok** [comment]
Suggest you comment below two lines, not run them, when you already did `bash reinstall.sh` 

`RUN python -m pip install git+[https://github.com/NVIDIA/NeMo.git@v1.0.0#egg=nemo_toolkit[asr]](https://github.com/NVIDIA/NeMo.git@v1.0.0#egg=nemo_toolkit%5Basr%5D)

RUN pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by manchandasahil** [comment]
Thank you so much. The diarization is completing but there is now an error reading the language model for realignment. Is there any suggestion what can i change while doing this : 
asr_diar_offline.get_transcript_with_speaker_labels(diar_hyp, word_hyp, word_ts_hyp)

[NeMo I 2022-04-27 10:12:07 diarization_utils:163] Loading LM for realigning: 4gram_big.arpa
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Input In [28], in <cell line: 1>()
----> 1 offset = asr_diar_offline.get_transcript_with_speaker_labels(diar_hyp, word_hyp, word_ts_hyp)

File /NeMo/nemo/collections/asr/parts/utils/diarization_utils.py:435, in ASR_DIAR_OFFLINE.get_transcript_with_speaker_labels(self, diar_hyp, word_hyp, word_ts_hyp)
    431         raise ImportError(
    432             'LM for realigning is provided but arpa is not installed. Install arpa using PyPI: pip install arpa'
    433         )
    434     else:
--> 435         self.realigning_lm = self.load_realigning_LM()
    437 for k, audio_file_path in enumerate(self.audio_file_list):
    438     uniq_id = get_uniqname_from_filepath(audio_file_path)

File /NeMo/nemo/collections/asr/parts/utils/diarization_utils.py:164, in ASR_DIAR_OFFLINE.load_realigning_LM(self)
    162 self.stt_end_tokens = ['</s>', '<s>']
    163 logging.info(f"Loading LM for realigning: {self.realigning_lm_params['arpa_language_model']}")
--> 164 return arpa.loadf(self.realigning_lm_params['arpa_language_model'])[0]

File ~/.local/lib/python3.8/site-packages/arpa/api.py:58, in loadf(path, encoding, model, parser)
     56 else:
     57     with open(path, mode='rt', encoding=encoding) as f:
---> 58         return load(f, model=model, parser=parser)

File ~/.local/lib/python3.8/site-packages/arpa/api.py:45, in load(fp, model, parser)
     42     raise ValueError
     44 if model == 'simple' and parser == 'quick':
---> 45     return ARPAParserQuick(ARPAModelSimple).parse(fp)
     46 else:
     47     raise ValueError

File ~/.local/lib/python3.8/site-packages/arpa/parsers/quick.py:31, in ARPAParserQuick.parse(self, fp)
     29 self._tmp_model = None
     30 self._tmp_order = None
---> 31 for line in fp:
     32     line = line.strip()
     33     if self._state == self.State.DATA:

File /opt/conda/lib/python3.8/encodings/ascii.py:26, in IncrementalDecoder.decode(self, input, final)
     25 def decode(self, input, final=False):
---> 26     return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 2808: ordinal not in range(128)

**Comment by nithinraok** [comment]
is it also happening on the file you provided?

**Comment by tango4j** [comment]
@manchandasahil

**Comment by EvgeniiPustozerov** [comment]
Hello! I am also getting an error on the mentioned above line of code. It falls even on the provided test samples from "ASR with speaker diarization" tutorial. Here is the traceback:

```
Traceback (most recent call last):
  File "D:\Projects\PoCSpeechEmotion\SpeakerDiarization.py", line 103, in <module>
    diarization("sample_4.wav")
  File "D:\Projects\PoCSpeechEmotion\SpeakerDiarization.py", line 96, in diarization
    asr_diar_offline.get_transcript_with_speaker_labels(diar_hyp, word_hyp, word_ts_hyp)
  File "C:\Program Files\Python310\lib\site-packages\nemo\collections\asr\parts\utils\diarization_utils.py", line 442, in get_transcript_with_speaker_labels
    self.make_json_output(uniq_id, diar_hyp, word_dict_seq_list, total_riva_dict)
  File "C:\Program Files\Python310\lib\site-packages\nemo\collections\asr\parts\utils\diarization_utils.py", line 547, in make_json_output
    self.write_and_log(uniq_id, riva_dict, audacity_label_words, gecko_dict, sentences)
  File "C:\Program Files\Python310\lib\site-packages\nemo\collections\asr\parts\utils\diarization_utils.py", line 976, in write_and_log
    string_out = self.print_sentences(sentences, self.params)
  File "C:\Program Files\Python310\lib\site-packages\nemo\collections\asr\parts\utils\diarization_utils.py", line 1045, in print_sentences
    start_point_str = datetime.fromtimestamp(start_point - datetime_offset).strftime(time_str)[:-4]
OSError: [Errno 22] Invalid argument
```

**Comment by tango4j** [comment]
@EvgeniiPustozerov Could you check what is assigned to `start_point` and `end_point`? start_point and end_point should be Python float. `start_point` and `end_point` should be coming from word-timestamps which are floating point numbers.

**Comment by EvgeniiPustozerov** [comment]
In my case values assigned to start_point and end_point are Python floats that come from word-timestamps generated with 
`diar_hyp, diar_score = asr_diar_offline.run_diarization(config, word_ts_hyp)`

![image](https://user-images.githubusercontent.com/107619405/181226055-e07429aa-262b-47cf-a0ac-7791c22ae243.png)
