### ISSUE TITLE
Assign a language model to Citrinet1024

### ISSUE THREAD

**Issue by MelikaBahmanabadi** [NVIDIA/NeMo#3960]
Hi, Thanks for your excellent tutorial. Refer to [Citrinet paper](https://arxiv.org/abs/2104.01721), you got WER in 3 modes: without language model, with language model(6-gram and Transf). How can I assign a language model to Citrinet1024. I started fine-tuning Citrinet1024 with the Persian audio dataset.

**Comment by titu1994** [comment]
We have the section in Nemo docs for language models, please review it https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html
