### ISSUE TITLE
Pretrained conformer CTC with character encoding for ASR

### ISSUE THREAD

**Issue by abhinavdayal** [NVIDIA/NeMo#4000]
Is there a pretrained model with character encoding using conformer-CTC for English? I could only find the onw with BPE encoding.

As per https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/models.html#conformer-ctc

> This model supports both the sub-word level and character level encodings. You can find more details on the config files for the Conformer-CTC models at Conformer-CTC <./configs.html#conformer-ctc>. The variant with sub-word encoding is a BPE-based model which can be instantiated using the EncDecCTCModelBPE class, while the character-based variant is based on EncDecCTCModel.

Does this mean, that it is there to be trained, but there is no pretrained version?

**Comment by VahidooX** [comment]
No, we have not released the character based models except for Mandarin. In our experiments, character based models give worse results than word-piece based models in most languages. But you can use those default configs to train one.

**Comment by DanBmh** [comment]
If you're still looking for one, you can find one at [Scribosermo](https://gitlab.com/Jaco-Assistant/Scribosermo#charbased) (tensorflow or tflite versions). I found that the characterbased models generally have a much worse WER than their sentencepiece counterparts, but, which was why I trained them, can achieve better results in usecases with a lot of uncommon words.
