### ISSUE TITLE
EncDecCTCModel from_pretrained() is crashing

### ISSUE THREAD

**Issue by davidmartinrius** [NVIDIA/NeMo#4015]
Hello!

After pull new git changes something is not working properly.

The way to reproduce the error is the next one:

from nemo.collections.asr.models import EncDecCTCModel
asr_model = EncDecCTCModel.from_pretrained(model_name="asr_talknet_aligner").cpu().eval()

After executing this code it will crash with the next error: (dataset_durations.py line 29 is the above code)

[NeMo I 2022-04-16 10:40:01 cloud:56] Found existing object /home/pc/.cache/torch/NeMo/NeMo_1.9.0rc0/qn5x5_libri_tts_phonemes/656c7439dd3a0d614978529371be498b/qn5x5_libri_tts_phonemes.nemo.
[NeMo I 2022-04-16 10:40:01 cloud:62] Re-using file from: /home/pc/.cache/torch/NeMo/NeMo_1.9.0rc0/qn5x5_libri_tts_phonemes/656c7439dd3a0d614978529371be498b/qn5x5_libri_tts_phonemes.nemo
[NeMo I 2022-04-16 10:40:01 common:705] Instantiating model from pre-trained checkpoint
[NeMo W 2022-04-16 10:40:01 features:233] Using torch_stft is deprecated and has been removed. The values have been forcibly set to False for FilterbankFeatures and AudioToMelSpectrogramPreprocessor. Please set exact_pad to True as needed.
[NeMo I 2022-04-16 10:40:01 features:259] PADDING: 1
[NeMo I 2022-04-16 10:40:01 features:276] STFT using torch
Traceback (most recent call last):
  File "dataset_durations.py", line 29, in <module>
    asr_model = EncDecCTCModel.from_pretrained(model_name="asr_talknet_aligner").cpu().eval()
  File "/home/pc/Downloads/NeMo/nemo/core/classes/common.py", line 708, in from_pretrained
    instance = class_.restore_from(
  File "/home/pc/Downloads/NeMo/nemo/core/classes/modelPT.py", line 305, in restore_from
    instance = cls._save_restore_connector.restore_from(
  File "/home/pc/Downloads/NeMo/nemo/core/connectors/save_restore_connector.py", line 156, in restore_from
    instance.load_state_dict(state_dict, strict=strict)
  File "/home/pc/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for EncDecCTCModel:
	Missing key(s) in state_dict: "preprocessor.featurizer.window". 
	Unexpected key(s) in state_dict: "preprocessor.featurizer.stft.forward_basis", "preprocessor.featurizer.stft.inverse_basis". 

I checkout to tag v1.7.2 and it is working well. But I would prefer to use the latest code if possible.

Could you help me to solve it?

- OS version: Ubuntu 21.10
- Python3.8
- GPU: RTX 3080
pytorch-lightning               1.6.0
torch                           1.11.0+cu113
torch-stft                      0.1.4
torchaudio                      0.11.0+cu113
torchmetrics                    0.7.3
torchvision                     0.12.0+cu113

Thank you!

David Martin Rius

**Comment by titu1994** [comment]
@redoctopus I believe you sent a PR that fixed this? Is it in main or r1.8?

**Comment by davidmartinrius** [comment]
> @redoctopus I believe you sent a PR that fixed this? Is it in main or r1.8?

I think @redoctopus PR to r1.8

https://github.com/NVIDIA/NeMo/pull/3993/commits/b7e0dcb81d0c3f8b11cddcb94a0bc0c318033422

**Comment by titu1994** [comment]
Ok so you'll need to wait a few days until r1.8 is released

**Comment by davidmartinrius** [comment]
Ok, in the meantime I am working with tag v1.7.2

Thank you!

**Comment by XuesongYang** [comment]
added fix PR here for reference: https://github.com/NVIDIA/NeMo/pull/3993
