### ISSUE TITLE
Not able to plot attention graph

### ISSUE THREAD

**Issue by Arjunprasaath** [NVIDIA/NeMo#4016]
Hey guys i am training a tacotron2 model but im not sure how to plot the attention graph and loss as well, any help on that would be appreciated.

**Comment by redoctopus** [comment]
If you have tensorboard installed, you can visualize the training and validation loss using the tensorboard logs automatically generated during training.

I don't believe attention mappings are added, so you'd need to modify tensorboard logging to add that manually. If you're only interested in inference time, you could save the tensors manually as well.

**Comment by Arjunprasaath** [comment]
@redoctopus
I have shared a screenshot of the files that are generated after training, when trying to plot the event.out.tf file through tensorboard it says "no dashboards are active through current dataset."

Command used is :
%load_ext tensorboard
%tensorboard --logdir "mydir/events.out.tfevents.1650260420.f58a2e592268.2705.0"

<img width="463" alt="Screenshot 2022-04-22 at 7 47 34 AM" src="https://user-images.githubusercontent.com/55142107/164583347-ae7106fd-7394-4cff-8f4d-c5df04fb0af2.png">

**Comment by redoctopus** [comment]
Try passing the directory instead of the file: `--logdir mydir/`
