### ISSUE TITLE
Number of Speakers Speaker_Diarization_Inference

### ISSUE THREAD

**Issue by CRochaVox** [NVIDIA/NeMo#4027]
Hello everyone, in the diarization process I need to receive the exact number of speakers within an audio without having to pass this number in the manifest.

Exemplifying better:
My problem is that I can only guarantee the maximum number of speakers within these audios, I have no way of knowing if the audio will come with 2, 3, 5 speakers. When I pass the 10 speakers manifest it tries to "find" 10 speakers within an audio that only has 3 speakers.

Is there any alternative in which I receive the exact number of speakers in the rttm output without having to go through the manifest first?

**Comment by nithinraok** [comment]
If all audio samples have common max number of speakers then you may pass that value here:
https://github.com/NVIDIA/NeMo/blob/48b2b05b0e27b1320050aa75c5740e53172415f3/examples/speaker_tasks/diarization/conf/offline_diarization.yaml#L42 

add toggle `oracle_num_speakers` as False
https://github.com/NVIDIA/NeMo/blob/48b2b05b0e27b1320050aa75c5740e53172415f3/examples/speaker_tasks/diarization/conf/offline_diarization.yaml#L41 

This way the pipeline computes number of speakers keeping `max_num_speakers` into consideration.

**Comment by CRochaVox** [comment]
When I download offline_diarization.yaml it already comes with the config as you showed me, I ended up seeing that in another place a little further down the script it changed the config oracle_num_speakers to true

![image](https://user-images.githubusercontent.com/94137813/164722657-a9a8a67a-2ec8-4a74-b750-26b805fd1dc3.png)

I changed it to false and it started doing the way I wanted

Thanks for helping !
