### ISSUE TITLE
WFST grammars export and test error

### ISSUE THREAD

**Issue by no-execution** [NVIDIA/NeMo#4049]
**Describe the bug**

I am looking for text normalization tools and select nemo text normalization tools.

In order to use it in c++, I follow the tutorial in [https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/text_normalization/wfst/wfst_text_processing_deployment.html](url)

and run test tn grammar code based on sparrowhawk and get result like:

<img width="828" alt="image" src="https://user-images.githubusercontent.com/29497466/164977748-1d21a641-7398-4bde-b8d0-11eeba3c1255.png">

It seems that numbers in time pattern is removed. Is this right?

Besides, many "Unknown field" error occurred like:

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/29497466/164977824-fac1188c-c0ca-46bb-9ce9-ffc13695f5e8.png">

Really need your help about WFST grammar export and sparrowhawk errors.

Thanks a lot !

**Comment by yzhang123** [comment]
@no-execution could you please give exact details of what system you use, which git hash, and the exact cmd you ran?
