### ISSUE TITLE
Error in ASR_with_SpeakerDiarization script when transcribing only one word

### ISSUE THREAD

**Issue by DieguJota** [NVIDIA/NeMo#4059]
Hi 
I'm using the script https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/ASR_with_SpeakerDiarization.ipynb in Colab and I came across a problem. When trying to transcribe an audio that has the transcription of only one word, it gives the following error in the "Run ASR and get word timestamps" block:

![image](https://user-images.githubusercontent.com/94137522/165177730-a7b39b2e-99a1-4489-af75-d53cb8c58e32.png)

The audio only contains transcription of the word "Eleven". In case you need it, here's the audio:
[audio.zip](https://github.com/NVIDIA/NeMo/files/8558127/audio.zip)

**Comment by tango4j** [comment]
Hi, Thank you for checking this.
I have fixed this and opened this PR: https://github.com/NVIDIA/NeMo/pull/4095
I checked 1 word, 2 words and more than 3 words for conformerCTC, Citrinet and QuartzNet.
If you want to test the bug-fixed version, you can use this branch: 
https://github.com/tango4j/NeMo/tree/asr_diar_bug_fix
