### ISSUE TITLE
Audio sample rate for transcribing

### ISSUE THREAD

**Issue by MelikaBahmanabadi** [NVIDIA/NeMo#4066]
Hi, thanks for your priceless tutorial,
I know the audio sample rate for fine-tuning the Nemo models should be 16khz. Is the sample rate should be 16khz for the audios to transcribe with Nemo models?

**Comment by titu1994** [comment]
Yes it should be 16khz, or whatever is the sample rate of the model.

**Comment by MelikaBahmanabadi** [comment]
Thanks a lot. But I transcribed 8khz and 16khz audio using Quartznet 15*5. The results were the same in some cases.

**Comment by titu1994** [comment]
If you don't pass in correct audio sample rate, librosa will be used to silently resample to the rate that the model required. Of course since it's silent it may cause unforseen issues so we ask to explicitly resample the audio.
