### ISSUE TITLE
not able to play audio in speech data explorer

### ISSUE THREAD

**Issue by agupta54** [NVIDIA/NeMo#4067]
I am trying to explore ASR training data through the speech explorer tool and prepared the required manifest file in json format. It has three fields, audio_filepath, duration, and text. 

**Steps/Code to reproduce bug**

python tools/speech_data_explorer/data_explorer.py manifest.json

**Expected behavior**
It is loading the data in an expected manner. I am able to see text, duration, and file name. However, I am not able to play the audio. The audio player does not seem to be working.  

**Environment overview (please complete the following information)**

pip install -r tools/speech_data_explorer/requirements.txt

 - Using on an M1 mac machine

**Environment details**

- OS version - macOS Monterry M1
- Python version - 3.8.11

**Comment by agupta54** [comment]
audio_filepath in json manifest is absolute and I double checked they are correct. The audio is mono channel and 16000 sample rate.

**Comment by vsl9** [comment]
The only difference between signal's plotting code and the audio player is that the audio player handler uses base64 encoding of audio to serve it in HTML5 audio tag.
I've added additional logger messaging in the PR: https://github.com/NVIDIA/NeMo/pull/4077 .
Can you please try it to see that there are no issues with audio encoding?

Have you tried different browsers (Safari, Chrome, Firefox)? I see no issues with SDE on a macbook with Intel processor. But it looks like Safari might not support PCM wave format: https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Cross-browser_audio_basics#audio_codec_support

**Comment by agupta54** [comment]
I am using Chrome browser for doing this. It seems that my audio encoding is okay. You can also have a look at the audio file [here](https://storage.googleapis.com/test_public_bucket/chunk_7.wav)
