### ISSUE TITLE
Dialogue state tracking

### ISSUE THREAD

**Issue by MMatlacz** [NVIDIA/NeMo#4160]
How do I run inference on SGDQA?

I see code for running training and evaluation on datasets, but how do I use this model interactively?

Is there any code for preprocessing utterance and schema and tracking state without providing information which should not be visible to model?

**Comment by Zhilin123** [comment]
Hi,

Inference capability has not yet been added to the SGDQA model but it is in our development roadmap so please check back in a few weeks. In the meanwhile, the Intent Slot Classification model is a similar model that supports inference. Please find it [here as a .py file](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/intent_slot_classification/intent_slot_classification.py) or [here as a colab notebook ](https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/nlp/Joint_Intent_and_Slot_Classification.ipynb)

The code for preprocessing SGDQA data is done at [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/data/dialogue/data_processor/sgd_data_processor.py)and [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/data/dialogue/dataset/dialogue_sgd_bert_dataset.py)

**Comment by yzhang123** [comment]
@MMatlacz yes that is the restriction of Google's SGD task, it requires you to know beforehand which underlying Services a dialogue belongs to.
