### ISSUE TITLE
TTS removed models 

### ISSUE THREAD

**Issue by amirrezam** [NVIDIA/NeMo#4169]
Hi,
Why Some TTS model (MelGAN, TalkNet) are removed from main branch, while they are exist in 1.8.2 ? 
Do you want to stop maintaining them ?

https://github.com/NVIDIA/NeMo/commit/c37786a9acb443b1d55d56636f00d3826ffc76d5

**Comment by redoctopus** [comment]
We recently unified the TTS models' data loading under `TTSDataset`, which breaks support for older checkpoints that depend on model-specific Dataset classes. As a result, we've decided to deprecate some older and lower-quality models to focus on and update a smaller set of flagship models.
