### ISSUE TITLE
TitaNet Small

### ISSUE THREAD

**Issue by naymaraq** [NVIDIA/NeMo#4174]
Hi NeMo team,
Do you plan to release TitaNet-small (medium) model?

**Comment by nithinraok** [comment]
Thanks for your interest. yes, planning to release for the next NeMo version targeting end of May.

**Comment by naymaraq** [comment]
Thank u very much @nithinraok

**Comment by carlfm01** [comment]
@nithinraok Hello, I'm really interested using the small version to fine tune ¿any update?

**Comment by nithinraok** [comment]
Sorry, I thought I release the model. Released now: https://registry.ngc.nvidia.com/orgs/nvstaging/teams/nemo/models/titanet_small

**Comment by carlfm01** [comment]
@nithinraok Thanks!

**Comment by carlfm01** [comment]
@nithinraok  ¿Is this model suitable for Riva? We fine tuned the small version and while it works really well with Nemo, while exporting it to Nemo the accuracy on the same audio make no sense. 
Sorry I know this is not Riva support, we just are a bit lost on how to make the diarization works and the Riva forum bounces back to an internal ticket taking months to reply.
Thanks in advance.
