### ISSUE TITLE
AN4 Dataset Not Found under ASR

### ISSUE THREAD

**Issue by 1zuu** [NVIDIA/NeMo#4188]
**Describe the bug**

The provided link for AN4 dataset under [http://www.speech.cs.cmu.edu/databases/an4/](here) is not accessible. Please validate the URL.

**Comment by titu1994** [comment]
That is the official url, and for some reason, the link is dead. You can contact CMU to fix that if necessary. For our purposes, we have mirror link to the an4 dataset temporarily in our notebooks.
