### ISSUE TITLE
unable to train asr

### ISSUE THREAD

**Issue by supreetpr-kore** [NVIDIA/NeMo#4225]
**Describe the bug**

trying to build an ASR with min-Libri speech data

**command**
python3 speech_to_text_ctc_bpe.py   model.train_ds.manifest_filepath=data/mini_libri/train_clean_5.json     model.validation_ds.manifest_filepath=data/mini_libri/dev_clean_2.json     model.tokenizer.dir=data/tokenizer_libri/tokenizer_spe_bpe_v1024/     model.tokenizer.type="bpe"     trainer.devices=-1     trainer.accelerator="gpu"     trainer.strategy="ddp"     trainer.max_epochs=100     model.optim.name="adamw"     model.optim.lr=0.001     model.optim.betas=[0.9,0.999]     model.optim.weight_decay=0.0001     model.optim.sched.warmup_steps=2000     exp_manager.create_wandb_logger=True     exp_manager.wandb_logger_kwargs.name="Libri_1"     exp_manager.wandb_logger_kwargs.project="Asr_demo"
**Error**

Traceback (most recent call last):
  File "speech_to_text_ctc_bpe.py", line 95, in <module>
    main()
  File "/data/supreet/NeMo/nemo/core/config/hydra_runner.py", line 104, in wrapper
    _run_hydra(
TypeError: _run_hydra() missing 1 required positional argument: 'args'

**Comment by jeffersonquispe** [comment]
I have the sama problem, how do you solve it?

**Comment by titu1994** [comment]
Downgrade your hydra version to 1.1.2

**Comment by titu1994** [comment]
Your issue is unrelated to this thread. Please open a new one.
