### ISSUE TITLE
Pretrained models url's not working

### ISSUE THREAD

**Issue by davidmartinrius** [NVIDIA/NeMo#4226]
Hello,

when I try to download any model it shows an error:

ValueError: Not able to download url right now, please try again.

I supose the server that store the models is not returning the models.

Could you check it out, please?

I share the full stack trace (in main branch and other branches)

[NeMo W 2022-05-23 10:10:06 nemo_logging:349] /home/pc/.local/lib/python3.8/site-packages/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
      warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)
    
################################################################################
################################################################################

2022-05-23 10:10:07.314427: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2022-05-23 10:10:07.314442: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [2], in <module>
     16 from nemo.collections.tts.helpers.helpers import regulate_len
     18 # Load the models from NGC
---> 19 fastpitch = FastPitchModel.from_pretrained("tts_en_fastpitch").eval().cuda()
     20 hifigan = HifiGanModel.from_pretrained("tts_hifigan").eval().cuda()
     21 sr = 22050

File ~/Downloads/NeMo/nemo/core/classes/common.py:682, in Model.from_pretrained(cls, model_name, refresh_cache, override_config_path, map_location, strict, return_config, trainer, save_restore_connector)
    677     class_, nemo_model_file_in_cache = cls._get_hf_hub_pretrained_model_info(
    678         model_name=model_name, refresh_cache=refresh_cache
    679     )
    680 else:
    681     # NGC source
--> 682     class_, nemo_model_file_in_cache = cls._get_ngc_pretrained_model_info(
    683         model_name=model_name, refresh_cache=refresh_cache
    684     )
    686 instance = class_.restore_from(
    687     restore_path=nemo_model_file_in_cache,
    688     override_config_path=override_config_path,
   (...)
    693     save_restore_connector=save_restore_connector,
    694 )
    695 return instance

File ~/Downloads/NeMo/nemo/core/classes/common.py:743, in Model._get_ngc_pretrained_model_info(cls, model_name, refresh_cache)
    741 cache_subfolder = hashlib.md5((location_in_the_cloud + description).encode('utf-8')).hexdigest()
    742 # if file exists on cache_folder/subfolder, it will be re-used, unless refresh_cache is True
--> 743 nemo_model_file_in_cache = maybe_download_from_cloud(
    744     url=url, filename=filename, cache_dir=cache_dir, subfolder=cache_subfolder, refresh_cache=refresh_cache
    745 )
    747 logging.info("Instantiating model from pre-trained checkpoint")
    749 if class_ is None:

File ~/Downloads/NeMo/nemo/utils/cloud.py:82, in maybe_download_from_cloud(url, filename, subfolder, cache_dir, refresh_cache)
     80         sleep(0.05)
     81         continue
---> 82 raise ValueError("Not able to download url right now, please try again.")

ValueError: Not able to download url right now, please try again.

**Comment by redoctopus** [comment]
I have not been able to reproduce this with the following:
```
from nemo.collections.tts.models import FastPitchModel
model = FastPitchModel.from_pretrained("tts_en_fastpitch")
```
Can you try again and see if it still fails? NGC may have been down temporarily at the time.

**Comment by davidmartinrius** [comment]
Hello! I will try it tomorrow moring and I will confirm if it works. Thank you!

**Comment by davidmartinrius** [comment]
It seems that is still crashing. Do you know how to contact to NGC? I would like to solve this. Thank you

**Comment by redoctopus** [comment]
Are you able to run `wget https://api.ngc.nvidia.com/v2/models/nvidia/nemo/tts_en_fastpitch/versions/1.8.1/files/tts_en_fastpitch_align.nemo`? Both the above code and the wget command are working on my end...

Not sure how to contact NGC, I'll see if anyone else knows.
