### ISSUE TITLE
Correcting spellings for BPE CTC conformer Models. 

### ISSUE THREAD

**Issue by evilc3** [NVIDIA/NeMo#4227]
Hi guys I fine-tuned a ctc large model on my custom dataset. Results are great but hv noticed some spellings issues. 

- How do I solve the spelling issues? 
- Do I need to use a lm for this?
- Is the tokeniser size the problem .  Uses same spe, unigram model with 256 tokens (added punts + numbers from 0 - 9)

**Comment by titu1994** [comment]
Punctuations, numbers aren't good for ASR, especially CTC models. Yes, LM will help with some spelling mistakes, but not all.

**Comment by evilc3** [comment]
So are all spelling mistakes coming because of punts and number's in tokeniser.  Are they any better spelling correcting methods other than using LMs

**Comment by titu1994** [comment]
It's not mainly that, even pure chars only models will make mistakes, CTC has not language modeling inbuilt unlike RNNT so it makes more spelling mistakes. Even RNNTs will not be perfect and never have spelling mistakes.
