### ISSUE TITLE
Fastpitch TTS in other languages

### ISSUE THREAD

**Issue by davidmartinrius** [NVIDIA/NeMo#4253]
Hello!

I would like to train some models with fastpitch.

One model in Spanish and other model in Catalan.

Each language has its own alphabet, symbols, punctuations, tildes, phonemes, etc

1. How to define and set all of this properties to get started?

2. If there are other properties that need to be defined, which are?

Thank you!

David Martin Rius

**Comment by aroraakshit** [comment]
Hi @davidmartinrius  -
1. How to define and set all of this (language's own alphabet, symbols, punctuations, tildes, phonemes) properties to get started?
-> We define these in the tokenizer here: https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/tts/torch/tts_tokenizers.py 
for each new language, you may create a class from BaseCharsTokenizer (say, SpanishCharsTokenizer) and define how you'd like to tokenize from text.

2. If there are other properties that need to be defined, which are?
Add a folder with config of your dataset here: https://github.com/NVIDIA/NeMo/tree/main/scripts/dataset_processing/tts where you can specify normalizer, tokenizer, dataset config (like sample rate, n_fft, win_length, etc) and get_data logic (how to download and process the dataset into train, test, val sets)

Additionally - Per the tutorial here: https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/FastPitch_MixerTTS_Training.ipynb you will need to extract supplementary data (i.e. pitch and align prior matrix) from your dataset. You can use the extract_sup_data.py file here: https://github.com/NVIDIA/NeMo/blob/main/scripts/dataset_processing/tts/extract_sup_data.py

**Comment by davidmartinrius** [comment]
Hello @aroraakshit !

Thanks for responding. I am going to try this. It is possible that it will take me some time. So, in the meantime I prefer to close this ticket. And if I have any other doubt about this I will open another one.
