### ISSUE TITLE
transcribe_audio

### ISSUE THREAD

**Issue by leonardltk** [NVIDIA/NeMo#4271]
```python
def transcribe(self, paths2audio_files: List[str], batch_size: int = 4) -> List[str]:
        """
        Takes paths to audio files and returns text transcription
        Args:
            paths2audio_files: paths to audio fragment to be transcribed
        Returns:
            transcription texts
        """
        pass
```
is there a replacement of `transcribe` that takes in the already loaded audio in numpy/torch array instead of the path ?

**Comment by titu1994** [comment]
No, the current implementation does not support tensors, only files. We're looking into what it would take to support tensors

**Comment by nick9arcia** [comment]
How could you pass a variable with the path as type str to path2audio_files?
