### ISSUE TITLE
Compute needed to train ASR on Nemo ASRSet v3.0

### ISSUE THREAD

**Issue by sciai-ai** [NVIDIA/NeMo#4275]
I am trying to train an ASR from scratch using somewhat like an ASRSet. I am wondering what compute power (GPUs etc) was used to train the STT models in Nemo. and whether it is possible in GCP to have enough compute power to do this?

**Comment by titu1994** [comment]
We use 16 nodes, 8 A100s per node to train these models. We can do the same with 8 nodes, 16 V100s per node as well.

**Comment by sciai-ai** [comment]
Does GCP have any config for this? I usually finetune on a single node with 4 T4 GPUs so I guess that will be too little for training. 

Also how much time does it typically take for the model to finish training?

**Comment by titu1994** [comment]
If you have solo access, it takes around 3-4 days at max for convergence. This is for 25k hours of speech.

**Comment by sciai-ai** [comment]
Assuming its 4 T4 GPUs on a solo node, what would be the probable batch size.

**Comment by titu1994** [comment]
I don't really know, depends on the configuration and memory. ASR training takes a lot of compute and memory.
