### ISSUE TITLE
TTS: How do you get fmin and fmax for a given audio dataset?

### ISSUE THREAD

**Issue by gedefet** [NVIDIA/NeMo#4280]
Hi all.

In different tutorials, specially in the TTS ones, you have to provide parameters fmin and fmax of your speaker. Nevertheless, there is no automatic way or tutorial on how to do that.

How do you extract fmin and fmax from an audio dataset?

Thanks,

**Comment by tanmoyio** [comment]
@gedefet Lower bound for frequency is 0 so `fmin` will be 0, and to calculate `fmax`, you can use `sample_rate/2`

**Comment by gedefet** [comment]
Thanks @tanmoyio , but I think you're referring to Nyquist theorem here.

I refer to the parameters that you need for training FastPitch. For example, for speaker 6097 of the HiFiTTS dataset, the training parameters are:

```
model.pitch_mean=121.9 model.pitch_std=23.1 \
  model.pitch_fmin=30 model.pitch_fmax=512
```

It is not very clear to me how to extract those parameters from a given dataset. Also clearly they're not in Hz.

Best,

**Comment by redoctopus** [comment]
We no longer recommend that users manually set the fmin/fmax; rather, please use the librosa default values (in the current configs) as those should work for speakers across the board.

**Comment by gedefet** [comment]
@redoctopus but I'm using my own dataset. What about that case?

**Comment by redoctopus** [comment]
That should be fine as well, the librosa defaults should work for human speech in general.

**Comment by gedefet** [comment]
@redoctopus note this from the FastPitch_Finetuning tutorial:

The number of speakers in the data. There is only 1 for now, but we will revisit this parameter later in the notebook.
**model.pitch_mean=121.9 model.pitch_std=23.1 model.pitch_fmin=30 model.pitch_fmax=512**

For speaker 92, we suggest **model.pitch_mean=214.5 model.pitch_std=30.9 model.pitch_fmin=80 model.pitch_fmax=512**

All the parameters but fmax are different. What is the reason for that difference?

Thanks!

**Comment by redoctopus** [comment]
As usual, `pitch_mean` and `pitch_std` can be calculated as in https://github.com/NVIDIA/NeMo/blob/main/scripts/dataset_processing/tts/extract_sup_data.py

As I recall from last year, we would sometimes change fmin/fmax in order to cut out noise from lower-quality recordings, and then eyeball the predicted pitch contours until things looked "pretty good." I'm not sure about the picks specifically for the speakers in the notebook (@blisc -- do you remember?).

But in most cases it won't really affect anything unless you're finding that predicted pitches are very off.

**Comment by blisc** [comment]
You can see section `Getting Pitch Statistics` at https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/resources/texttospeech_notebook/version/v1.1.1/files/text-to-speech-finetuning-cvtool.ipynb for information on how to update your fmin and fmax.

But we no longer recommend this, and recommend to stick to the librosa defaults.
