### ISSUE TITLE
External Vad manifest

### ISSUE THREAD

**Issue by RezaBi** [NVIDIA/NeMo#4283]
**Is your feature request related to a problem? Please describe.**

I have been using diarization.py example using the provided config file. The marble net vad acts really poor detecting speech. So I decided to use an External vad *( e.g pyannote vad ) to provide to the model. I could not find how to convert an external vad outputs to the manifest file required for the model

**Describe the solution you'd like**

A brief documentation on how to build the manifest file and a method to do it if possible.

**Comment by RezaBi** [comment]
I solved this by providing a rttm type output from my external VAD & then use the oracle-vad option.

**Comment by great-goblin** [comment]
For anyone else dealing with this issue, a description of how to construct the Exteral VAD Manifest can be found in this tutorial under the heading "[Speaker Diarization with Oracle VAD](https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Diarization_Inference.ipynb)".
