### ISSUE TITLE
Tacotron2.ipynb error Hydra

### ISSUE THREAD

**Issue by NK990** [NVIDIA/NeMo#4287]
Describe the bug

When running the tutorial notebook for Tacotron2 training in Google Colab. After this step;
`!python tacotron2.py \
sample_rate=16000 \
train_dataset=tests/data/asr/an4_train.json \
validation_datasets=tests/data/asr/an4_val.json \
trainer.max_epochs=3 \
trainer.accelerator=null trainer.check_val_every_n_epoch=1 \
trainer.gpus=1`
 Hydra issue is raised:
`Traceback (most recent call last):
  File "tacotron2.py", line 44, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/config/hydra_runner.py", line 108, in wrapper
    config_name='tacotron2.yaml',
TypeError: _run_hydra() missing 1 required positional argument: 'args'`

Maybe you also need to take a look at this warning while we are on the same step
`################################################################################
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################`

Steps/Code to reproduce bug

Running each cell of the Tacotron2 tutorial notebook in a new Colab session,restarting, deleting runtime...

Environment location: Collab
Method of NeMo install: As per instructions within notebook. Please specify exact commands you used to install.

**Comment by titu1994** [comment]
You have to reduce your hydra version, we don't support the latest version yet. What branch is being used and how was it installed?

**Comment by NK990** [comment]
```
BRANCH = 'r1.8.2'

!apt-get install sox libsndfile1 ffmpeg
!pip install wget unidecode
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[all]
```

Which version of hydra should I use in this case?

**Comment by titu1994** [comment]
Right we didn't pin hydra to 1.1.2 in Nemo 1.8.x. Nemo 1.9.0 should be out in a few days, that should auto fix this, but till then you can use hydra-core==1.1.2

**Comment by NK990** [comment]
I'll give a shot and let  u know...
And what about KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk

**Comment by titu1994** [comment]
Ignore it. Some old library decided to log a hardcoded value at import time. We've stopped depending on that library in newer versions of NeMo.

**Comment by NK990** [comment]
I can still raport issues about this, sorry.... 
After reducing hydra core to 1.1.2 I run into several problems... 
**TypeError: _run_hydra() got an unexpected keyword argument 'strict'**
I make a work around by removing completely `strict=None,` from `/usr/local/lib/python3.7/dist-packages/nemo/core/config/hydra_runner.py` 
``
after runing trainer again `!python tacotron2.py sample_rate=16000 train_dataset=tests/data/asr/an4_train.json validation_datasets=tests/data/asr/an4_val.json trainer.max_epochs=3 trainer.accelerator=null trainer.check_val_every_n_epoch=1` I got this issues:

[NeMo W 2022-05-30 20:53:33 nemo_logging:349] /usr/local/lib/python3.7/dist-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
      '"sox" backend is being deprecated. '
    
[NeMo W 2022-05-30 20:53:33 nemo_logging:349] /usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py:49: UserWarning: You have set progress_bar_refresh_rate < 20 on Google Colab. This may crash. Consider using progress_bar_refresh_rate >= 20 in Trainer.
      warnings.warn(*args, **kwargs)
    
```
GPU available: True, used: True
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[NeMo I 2022-05-30 20:53:33 exp_manager:208] Experiments will be logged at /content/nemo_experiments/Tacotron2/2022-05-30_20-53-33
[NeMo I 2022-05-30 20:53:33 exp_manager:548] TensorboardLogger has been set up
[NeMo I 2022-05-30 20:53:33 collections:173] Dataset loaded with 30 files totalling 0.02 hours
[NeMo I 2022-05-30 20:53:33 collections:174] 0 files were filtered totalling 0.00 hours
[NeMo I 2022-05-30 20:53:33 collections:173] Dataset loaded with 10 files totalling 0.01 hours
[NeMo I 2022-05-30 20:53:33 collections:174] 0 files were filtered totalling 0.00 hours
[NeMo I 2022-05-30 20:53:33 features:240] PADDING: 16
[NeMo I 2022-05-30 20:53:33 features:249] STFT using conv
[NeMo I 2022-05-30 20:53:38 modelPT:685] Optimizer config = Adam (
    Parameter Group 0
        amsgrad: False
        betas: (0.9, 0.999)
        eps: 1e-08
        lr: 0.001
        weight_decay: 1e-06
    )
Error executing job with overrides: ['sample_rate=16000', 'train_dataset=tests/data/asr/an4_train.json', 'validation_datasets=tests/data/asr/an4_val.json', 'trainer.max_epochs=3', 'trainer.accelerator=null', 'trainer.check_val_every_n_epoch=1']
Traceback (most recent call last):
  File "tacotron2.py", line 44, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/config/hydra_runner.py", line 102, in wrapper
    config_name=config_name,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 378, in _run_hydra
    lambda: hydra.run(
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/utils.py", line 381, in <lambda>
    overrides=args.overrides,
  File "/usr/local/lib/python3.7/dist-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/usr/local/lib/python3.7/dist-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/usr/local/lib/python3.7/dist-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "tacotron2.py", line 40, in main
    trainer.fit(model)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 493, in fit
    self.accelerator_backend.setup(model)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 52, in setup
    self.setup_optimizers(model)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/accelerators/accelerator.py", line 150, in setup_optimizers
    optimizers, lr_schedulers, optimizer_frequencies = self.trainer.init_optimizers(model)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/optimizers.py", line 31, in init_optimizers
    optim_conf = model.configure_optimizers()
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/classes/modelPT.py", line 699, in configure_optimizers
    self.setup_optimization()
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/classes/modelPT.py", line 691, in setup_optimization
    optimizer=self._optimizer, scheduler_config=scheduler_config, train_dataloader=self._train_dl
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/optim/lr_scheduler.py", line 612, in prepare_lr_scheduler
    scheduler_cls = get_scheduler(scheduler_name, **scheduler_args)
  File "/usr/local/lib/python3.7/dist-packages/nemo/core/optim/lr_scheduler.py", line 398, in get_scheduler
    f"Cannot resolve scheduler{name}'. Available optimizers are : " f"{AVAILABLE_SCHEDULERS.keys()}"
ValueError: Cannot resolve schedulerDictConfig'. Available optimizers are : dict_keys(['WarmupPolicy', 'WarmupHoldPolicy', 'SquareAnnealing', 'CosineAnnealing', 'NoamAnnealing', 'WarmupAnnealing', 'InverseSquareRootAnnealing', 'SquareRootAnnealing', 'PolynomialDecayAnnealing', 'PolynomialHoldDecayAnnealing', 'StepLR', 'ExponentialLR', 'ReduceLROnPlateau', 'CyclicLR'])
```

Is there any working notbook already tested on google colab? 
Ty
