### ISSUE TITLE
Multiprocessing hangs in VAD during diarization

### ISSUE THREAD

**Issue by gkucsko** [NVIDIA/NeMo#4315]
In some environments, VAD as part of the diarizer stalls during multiprocessing. Would probably warrant some closer investigation into spawn context, but for a quick fix I added a mini PR to disable multiprocessing by setting num_workers=1
https://github.com/NVIDIA/NeMo/pull/4317

**Comment by fayejf** [comment]
Yes seems like python multiprocessing can deadlock in certain environments, and this is an unsolved issue in python now. Thanks for the fix in https://github.com/NVIDIA/NeMo/pull/4317 ! @gkucsko

For anyone who is interested in using multiprocessing in VAD to accelerate the process. I'm with Python 3.7.11 and it works perfectly fine on my end

**Comment by gkucsko** [comment]
Great thanks!
