### ISSUE TITLE
Add Squeezeformer to Nemo

### ISSUE THREAD

**Issue by harveenchadha** [NVIDIA/NeMo#4321]
Squeezeformer looks promising and uses some of the reusable components from conformer backbone. Creating a placeholder for discussion and implementation.

[Official Implementation](https://github.com/kssteven418/Squeezeformer)

[Paper]([arxiv.org/pdf/2206.00888.pdf](https://arxiv.org/pdf/2206.00888.pdf))

**Comment by okuchaiev** [comment]
I'll let @titu1994 comment on that architecture and whether we plan on it for ASR

**Comment by titu1994** [comment]
The architecture is reasonably similar to Conformer that we can add it, but it may take a while to polish it. The original codebase is in TF and porting 1:1 usually required minor modifications for correct convergence.

**Comment by titu1994** [comment]
So expect it around Nemo 1.12 or so (2 months~3 months). It may be on main branch sooner.

**Comment by titu1994** [comment]
FYI @VahidooX

**Comment by titu1994** [comment]
Closing for now, well keep you updated over the coming months.

**Comment by titu1994** [comment]
It should be added in the next to next release (1.11) but you can try it out in main branch after this pr is merged - https://github.com/NVIDIA/NeMo/pull/4416

Note that the scheduler is very unique, and highly depends on the total number of steps and global batch size and number of samples. You may need to tune these when using less than recommended global batch size
