### ISSUE TITLE
No module named 'nemo.collections' in NGC NeMo Toolkit container

### ISSUE THREAD

**Issue by karlkao** [NVIDIA/NeMo#434]
I tried to run evaluation process in Docker (nvcr.io/nvidia/nem:v0.9) with a pretrained model.
Though, NeMo root contains nemo/collections, the jasper_eval.py failed to locate the package.

root@dgx-18-04:/NeMo# python /NeMo/examples/asr/jasper_eval.py --model_config=/NeMo/examples/asr/configs/quartznet15x5.yaml --eval_datasets "/home/lab/karl/NeMo/dataset/data_aishell/dev.json" --load_dir=/home/lab/karl/NeMo/checkpoints/aishell2_quartznet15x5

/opt/conda/lib/python3.6/site-packages/torchvision/io/_video_opt.py:17: UserWarning: video reader based on ffmpeg c++ ops not available
  warnings.warn("video reader based on ffmpeg c++ ops not available")
Traceback (most recent call last):
  File "/NeMo/examples/asr/jasper_eval.py", line 24, in <module>
    import nemo.collections.asr as nemo_asr
ModuleNotFoundError: No module named 'nemo.collections'
root@dgx-18-04:/NeMo#

**Comment by karlkao** [comment]
It appears running "reinstall.sh" after log onto Docker resolve this issue.

**Comment by Bowenwu1** [comment]
Any update?
Encouter the same issue
