### ISSUE TITLE
training self-supervised conformer

### ISSUE THREAD

**Issue by alexandercesarr** [NVIDIA/NeMo#4344]
Hi, I use `examples/asr/speech_pretraining/speech_pre_training.py` code to train a self-supervised using conformer on my custom dataset. I just changed the manifest files address in conf file. When I run the code, I encounter the below issue.
I use NeMo version 1.8.0. Also I test it on version 1.9.0 but the same problem occured.

**Environment details:**
torch 1.9.0a0+c3d40fd
pytorch-lightning 1.6.4
Python 3.8.10
NeMo 1.8.0

![Screenshot from 2022-06-07 14-22-48](https://user-images.githubusercontent.com/105767588/172352592-ed10430a-6e29-4723-a6e9-d9b7d96316d8.png)

**Comment by sam1373** [comment]
Hi @alexandercesarr, based on this error message it seems that you are using the config file from main branch, which is only compatible with NeMo 1.10.0. You will need to either switch your config to the one in 1.8.0/1.9.0, or reinstall using main branch to use the newer config.

**Comment by alexandercesarr** [comment]
@sam1373 That was it. Thank you very much.
