### ISSUE TITLE
Which version of nemo to install in order to reduce dependencies?

### ISSUE THREAD

**Issue by dunky11** [NVIDIA/NeMo#4345]
I'm currently using nemo only for text normalization - I only import nemo_text_processing.text_normalization.normalize.Normalizer.

I install nemo toolkit using nemo-toolkit[all]==1.8.2. Is there any way to reduce the number of dependencies, for example by not installing [all]? I haven't found anything in the docs.

Thanks for any help in advance.

**Comment by yzhang123** [comment]
@dunky11
you can directly install  nemo-toolkit[nemo_text_processing] (as in here https://github.com/NVIDIA/NeMo/blob/main/tutorials/text_processing/WFST_Tutorial.ipynb)

this is the most lean version, it does not support things like `--punct_post_process` which requires nemo-toolkit[nlp] or audio based normalization with audio data which requires nemo-toolkit[asr]

I will add this to documentation! thanks!

**Comment by dunky11** [comment]
Thanks, that clarified it!
