### ISSUE TITLE
feat_type is missed in audio_preprocessing.py

### ISSUE THREAD

**Issue by karlkao** [NVIDIA/NeMo#435]
Config file, jasper10x5dr.yaml, from pretained model contains 'feat_type: "logfbank"' and this argument is not defined in AudioToMelSpectrogramPreprocessor(AudioPreprocessor). Github repository nemo.collections does not take the 'feat_type'.

This looks like a version mismatch issue. Does the pretained model train in another repository which can take the 'feat_type'?

**Comment by okuchaiev** [comment]
Can you please try removing "feat_type" from .yaml file?

**Comment by okuchaiev** [comment]
closing. @karlkao  feel free to re-open if you still have issues
