### ISSUE TITLE
Text Normalization Corrupted Output

### ISSUE THREAD

**Issue by thebhsu** [NVIDIA/NeMo#4353]
**Describe the bug**

Tags are propagated to the output text during normalization.

**Steps/Code to reproduce bug**

```python
from nemo_text_processing.text_normalization import normalize

tn = normalize.Normalizer("lower_cased")

text = "google.com is related to apple.com"
print(tn.normalize(example))

"""
google dot com " right brace right brace TOKENS left brace NAME: "IS" right brace TOKENS left brace NAME: "RELATED" right brace TOKENS left brace NAME: "TO" right brace TOKENS left brace ELECTRONIC left brace DOMAIN: "APPLE dot COM
"""

example = "google.com is related to com.apple"
print(tn.normalize(example))

"""
google dot com is related to com.apple
"""


```
**Expected behavior**

The first example should return `google dot com is related to apple dot com`, the second one is ok as I believe one would need to add rules to handle such a "strange" case.

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: `git clone https://github.com/NVIDIA/NeMo`
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version: 1.12.0
- Python version: 3.8.12

**Additional context**

Example: GPU model

**Comment by ekmb** [comment]
@thebhsu, thanks for reporting this! The fix is merged to `r1.10.0` branch.
