### ISSUE TITLE
Restore from W&B artifact

### ISSUE THREAD

**Issue by piraka9011** [NVIDIA/NeMo#4359]
**Is your feature request related to a problem? Please describe.**

I was wondering if it's possible to add first class support for W&B artifacts to the `modelPT.restore_from()` method?
Currently, I run something like the following if I want to download a NeMo model saved on W&B:

```py
from urllib.parse import urlparse

model_path = "wandb://{TEAM}/{PROJECT}/{MODEL_NAME}:{LABEL}"
url_path = urlparse(model_path)
if url_path.scheme == "wandb":
    artifact_name = f"{url_path.netloc}{url_path.path}"
    model_path = download_model_from_wandb(artifact_name, "EncDecCTCModel")
```

and `download_model_from_wandb` would look something like

```py
from pathlib import Path
import wandb
from nemo.utils import logging, model_utils

ARTIFACT_DIR = "/tmp"

def download_model_from_wandb(artifact_name: str, model_class: str) -> Path:
    api = wandb.Api()
    artifact = api.artifact(artifact_name)
    model_name = artifact.name.split(":")[0]  # Remove the tag/label
    model_name = Path(model_name).stem
    root = ARTIFACT_DIR / model_name
    nemo_path = root / f"{model_name}.nemo"
    artifact.download(root=root)
    return nemo_path
```

Maybe we could use some logic similar to the above with `restore_from()` to load the downloaded model?

**Describe the solution you'd like**

I would think that this could live in the [`restore_from()`](https://github.com/NVIDIA/NeMo/blob/main/nemo/core/classes/modelPT.py#L258) method itself, but it seems there's a new [`SaveRestoreConnector`](https://github.com/NVIDIA/NeMo/blob/main/nemo/core/connectors/save_restore_connector.py) so not sure if it's more logical to put something like this there.

**Additional context**

Can open a PR for this if it is welcome.

**Comment by titu1994** [comment]
Restore from is unrelated to the how you download a Nemo file, - that's why from pretrained is just a wrapper over restore_from() to download a file and just call restore from()

We can look into supporting this inside from_pretrained but from a practical implementation point can we be guaranteed that wandb:// is always the start of the URL pointing to the artifact? Otherwise it conflicts with how we resolve HF checkpoint urls.

**Comment by piraka9011** [comment]
I see. And no we can't guarantee `wandb://` will always be the start of the URL.
If `from_pretrained` grabs models from NGC, why not make a `from_wandb` method to be more explicit about the intent, or add the functionality to the same method itself (maybe [here](https://github.com/NVIDIA/NeMo/blob/31c821d86513b7ea599bb1803da75c779408e09e/nemo/core/classes/common.py#L717-L726)?
The former approach removes the need for having a URL scheme to specify the model and can prevent conflicts with future model storage tools.

**Comment by titu1994** [comment]
We want a standard API - from_pretrained to deal with network, and it's only responsibility is downloading a Nemo file. Then it forwards to restore_from(). 

So we won't have seperate methods that deal with wandb vs other storage schemes. Unlike HF and NGC where names are all that are required (for hf- username/model_name), wandb does not provide a standardized way to refer to models, and it is inherently single user purpose - unless it can share artifacts with others it doesn't really belong part of from_pretrained(). 

I would suggest creating the wrapper you have currently for wandb

**Comment by piraka9011** [comment]
Makes sense, will keep this functionality outside of NeMo then.
Thanks for the insight!
