### ISSUE TITLE
ITN doesn't work for a specific expression about time like 'ten to eleven'

### ISSUE THREAD

**Issue by sinpy1117** [NVIDIA/NeMo#4361]
**Is your feature request related to a problem? Please describe.**

I am trying to convert normalized asr model outputs into written form using _**inverse_normalizer.inverse_normalize**_. 
Whereas some intractable problems arose when dealing a specific expression about time like **"* to *"**.

When I convert this verbal form **"ten to eleven"**.
The ouput is **"ten to eleven"**  which is inconsistent with the expected output **"10:50"**.

If there is a sentence containing such expression about time, it will cause a more erroneous result.
For example:
The ITN output of **"set an alarm at ten to eleven pm"** is **''set an alarm at ten to 11:00 p.m."**

This is a general problem in my dataset.
I'd like to know how to solve this problem.
Should I add some specific custom rules?
Thanks a lot for any answer!

**Environment overview**
- Environment location: Docker
- Method of NeMo install: from source

**Comment by ekmb** [comment]
Yes, you would need to add new rules. I added a rule to cover the example above in the linked PR. For more details on how to  customize the rules, see [tutorials/text_processing/WFST_Tutorial.ipynb](https://github.com/NVIDIA/NeMo/blob/main/tutorials/text_processing/WFST_Tutorial.ipynb)
