### ISSUE TITLE
wav2vec ASR

### ISSUE THREAD

**Issue by demsarjure** [NVIDIA/NeMo#4362]
**Describe the bug**

I have been trying to get wav2vec ASR training up and running. I am mainly trying to use the model defined in

```
examples/asr/experimental/wav2vec/configs/wav2vecCTC.yaml
```

I also tried to get a model with wav2vec_pretrain.yaml running, but I get the same error as outlined below.

The call I use is:

```
python /workspace/nemo/examples/asr/asr_ctc/speech_to_text_ctc.py \
  --config-path=/workspace/nemo/examples/asr/experimental/wav2vec/configs \
  --config-name=wav2vecCTC \
  exp_manager.name=wav2vec \
  +exp_manager.exp_dir=/experiments \
  +exp_manager.version=20220613-1105 \
  exp_manager.resume_if_exists=true \
  exp_manager.resume_ignore_no_checkpoint=true \
  +exp_manager.checkpoint_callback_params.save_best_model=true \
  model.train_ds.manifest_filepath=/data/train.nemo \
  model.train_ds.batch_size=16 \
  model.train_ds.max_duration=17 \
  +model.train_ds.min_duration=1 \
  model.validation_ds.manifest_filepath=/data/validation.nemo \
  model.validation_ds.batch_size=16 \
  model.test_ds.manifest_filepath=/data/test_old.nemo \
  model.test_ds.batch_size=16 \
  model.tokenizer.dir=/data/out/tokenizer_spe_bpe_v128 \
  model.tokenizer.type=bpe
```

The error is get is:

```
KeyValidationError('ListConfig indices must be integers or slices, not str\n    full_key: [0][emb_dim]\n    object_type=list')
```

It seems like something is wrong with `emd_dim`. I leave this at its default in the `embedding_dim` parameter in the YAML file. Even if I set this explicitly I get the same error. Attached is also the full output of the call: [output_20220613-1105.txt](https://github.com/NVIDIA/NeMo/files/8890509/output_20220613-1105.txt).

Another minor thing I also noticed is that the command call crashes even earlier if I do not provide a test set. Based on the YAML file test set should not be mandatory as it is set to null and not ??.

I am aware that this is an experimental functionality, so any help will be greatly appreciated.

**Steps/Code to reproduce bug**

Full command call can be found in the previous section.

**Expected behavior**

I expect the wav2vec model to start the training process.

**Environment overview (please complete the following information)**

I am using the official NVIDIA pytorch 22.01 container, the used NeMo version is the current version of the master branch.

**Environment details**

I am using the official NVIDIA pytorch 22.01 container, the used NeMo version is the current version of the master branch.

**Additional context**

Will provided any additional info if required.

**Comment by demsarjure** [comment]
Hi!

It gets farther now, but still crashes. Now, I am getting a PyTorch error because of an inplace operation:

```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [8, 768, 766]], which is output 0 of AsStridedBackward0, is at version 121; expected version 120 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```
See [output_20220614-1106.txt](https://github.com/NVIDIA/NeMo/files/8899194/output_20220614-1106.txt) for the full log. I already tried updating PyTorch to 22.04, I am now using The official 22.04 NeMo container where the NeMo repository in it is updated to the tip of the master branch.

Also, the line 789 in `nemo/core/classes/mixins/adapter_mixins.py` should be `if module_name == '':` instead of `if module_name is '':`. Currently a warning pops up everytime.

Thanks, Jure

**Comment by titu1994** [comment]
Thanks about the adapter warning, I'll fix that in the next release.

**Comment by bonham79** [comment]
@demsarjure Got your error to recreate itself on local. Looking like a container related issue. Would you mind using trying out a clean install on main NeMo branch while I'm hunting down the kink? (Can use a toy dataset for ease. Just need to see if the autograd acts up on current version.)

**Comment by one1ine** [comment]
@demsarjure I added the detect_anomaly into my trainer and got a more specific error which I can't figure out how to solve. 
                  trainer = pl.Trainer(devices=1, accelerator='gpu', max_epochs=50, logger=logger, detect_anomaly=True )

The specific error im referring to is this
[output.txt](https://github.com/NVIDIA/NeMo/files/8915211/output.txt)

**Comment by titu1994** [comment]
Run it on CPU first should be a much more understandable error.

**Comment by titu1994** [comment]
Also @sam1373 if you are ok with it let's plan to delete the experimental Wav2Vec for the stable one to avoid confusion

**Comment by demsarjure** [comment]
@one1ine @bonham79 I reran with the latest version of NeMo, same story. I also added the `detect_anomaly=True` option to the trainer and I get the same error as posted in the output.txt above.

Unfortunately, PyTorch is not my expertise so I cannot really help out here. Maybe something is not correct in the `backward` function in `collections/asr/modules/wav2vec_modules.py`?

**Comment by bonham79** [comment]
@demsarjure Thanks for running the double check. Issue is happening in the transformer block so probably something up with pytorch managing masking between new versions.  If you're in a pinch, dev was done with nemo container 1.5.1. So can use that for your environment and clone the wav2vec relevant code. Obviously not ideal, but can be a stopgap. 

@titu1994 Just to check, container 1.5.1 is torch 1.9 and 22.04 is the nightly, correct?

**Comment by titu1994** [comment]
22.04 is PT 1.11

**Comment by bonham79** [comment]
@demsarjure Thanks for catching the bug. Can copy from: https://github.com/NVIDIA/NeMo/pull/4383 for the fix while waiting on PR integration. (Just a one line edit that can be done with a personal clone of NeMo.)

**Comment by demsarjure** [comment]
@bonham79 Thanks for the quick and efficient support!

**Comment by demsarjure** [comment]
I can confirm that the fix works, so I will just close the issue.
