### ISSUE TITLE
why 44.1khz fastpitch align  config is removed in 1.9.0?

### ISSUE THREAD

**Issue by m-aqeeljanjua** [NVIDIA/NeMo#4409]
I am working on training the TTS model using Fastpitch architecture using Librivox 44khz dataset.  I was getting issues in the trained model and looking for possible solutions online. but now I saw that in the 1.9.0 release of Nemo, you have removed the 44100 sample rate model configs. Can someone share the reason for that?

**Comment by titu1994** [comment]
Multiple TTS models were deprecated in previous releases, abs finally removed in 1.9. I believe there are better replacements for them which @redoctopus may recommend to you.
