### ISSUE TITLE
Request the feature to send metadata in BLS.

### ISSUE THREAD

**Issue by ikhyun5538** [NVIDIA/NeMo#4429]
**Is your feature request related to a problem? Please describe.**
I want to change the Model according to the BLS input. But BLS requires the same input bach size. So I have to make input like ["model1", "model1"]. If my batch size is 100, should I send 100 same data like ["model1", "model1", "model1"].

**Describe the solution you'd like**
It would be nice to have the feature to send metadata other than batch data.

**Comment by titu1994** [comment]
What is BLS? And what are you trying to accomplish ?

**Comment by ikhyun5538** [comment]
Oh i'm sorry. 
It's Nvidia Triton Issue.

I'm trying to make Korean TTS service using Nemo. It makes a lot of things easier.
 
thank you.

**Comment by ikhyun5538** [comment]
@okuchaiev [okuchaiev](https://github.com/okuchaiev)Thanks for the interest and information. It has been very helpful!!
