### ISSUE TITLE
MultiChannel Support 

### ISSUE THREAD

**Issue by evilc3** [NVIDIA/NeMo#4439]
Does Nemo support multi-channel?,  So far I have only seen single-channel inputs. 

If not which is the best way I can go about adding support for it. 

Any reason why Is not supported?

Thanks

**Comment by titu1994** [comment]
Our current models don't support multichannel input. We'll be expanding our codebase to accommodate some useful multichannel models in the near future though.

**Comment by evilc3** [comment]
Ok thanks

**Comment by evilc3** [comment]
How does one add support for multi-channel do we need to do it at training stage itself? Is there any quick implementation available

**Comment by titu1994** [comment]
No there isn't something available at the moment. We assume input is always monochannel, and passing a multichannel audio file will crash right now
