### ISSUE TITLE
Unable to import nlp

### ISSUE THREAD

**Issue by FatimaArshad-DS** [NVIDIA/NeMo#4453]
I am running this Colab Notebook : https://colab.research.google.com/github/NVIDIA/NeMo/blob/v1.0.2/tutorials/nlp/Entity_Linking_Medical.ipynb#scrollTo=2qLS4_0tyf_A

When I run second cell it gives error on this line
from nemo.collections import nlp as nemo_nlp

And the error is this:
(RuntimeError                              Traceback (most recent call last)
[<ipython-input-18-051dc782fbfe>](https://localhost:8080/#) in <module>()
     11 from tqdm import tqdm
     12 
---> 13 from nemo.collections import nlp
     14 from nemo.utils.exp_manager import exp_manager

16 frames
/usr/local/lib/python3.7/dist-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb, example_inputs)

RuntimeError: 

dropout(Tensor input, float threshold, float value, bool inplace=False) -> (Tensor):
Argument threshold not provided.
:
  File "/usr/local/lib/python3.7/dist-packages/megatron/model/transformer.py", line 366
def bias_dropout_add(x, bias, residual, prob, training) :
    # type: (Tensor, Tensor, Tensor, float, bool) -> Tensor
    out = torch.nn.functional.dropout(x + bias, p=prob, training=training)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    out = residual + out
    return out
'bias_dropout_add' is being compiled since it was called from 'bias_dropout_add_fused_train'
  File "/usr/local/lib/python3.7/dist-packages/megatron/model/transformer.py", line 380
def bias_dropout_add_fused_train(x, bias, residual, prob) :
    # type: (Tensor, Tensor, Tensor, float) -> Tensor
    return bias_dropout_add(x, bias, residual, prob, True)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE)

**Comment by ericharper** [comment]
It looks like the link is broken in our documentation. Here is the correct link: https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/nlp/Entity_Linking_Medical.ipynb

I'll fix the link in the documentation.
