### ISSUE TITLE
Unable to train Entity Linking

### ISSUE THREAD

**Issue by FatimaArshad-DS** [NVIDIA/NeMo#4466]
I am trying to train Entity Linking in NLP. 

It runs fine. However, while saving results after Epoch 0 it gives this error 
In automatic_optimization, when `training_step` returns a dict, the 'loss' key needs to be present

I checked and training step method does have a dictionary. What could be the reason for this?
Im running training on Google Colab (if that helps )

**Comment by ericharper** [comment]
Have you tried this tutorial? https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/nlp/Entity_Linking_Medical.ipynb

**Comment by okuchaiev** [comment]
@FatimaArshad-DS , please try the tutorial which @ericharper  suggested and re-open if bug persists

**Comment by FatimaArshad-DS** [comment]
@ericharper  @okuchaiev  I have tried that tutorial. It's working fine. But when I train it on UMLs it gives this error. I have python 3.9, Ubuntu and installed apex.

**Comment by FatimaArshad-DS** [comment]
This error occurs after first epoch
