### ISSUE TITLE
Bert training argument clarity

### ISSUE THREAD

**Issue by jtourille** [NVIDIA/NeMo#447]
Hi,

I am not sure it is the right place to ask these questions, sorry if it is not the case.

I am trying to train BERT using the bert_pretraining.py script and I have a question regarding the two arguments `batch_size` and `batches_per_step`.

Tell me whether I have the correct interpretation. Let say I want an effective batch size of 8192 and my GPUs can only hold 64 instances in memory. Am I correct by setting the `batch_size` to 64 and the `batches_per_step` to 128? 

A follow-up question: are these parameters completely independent from the number of GPUs I use? For instance, if I am using 8 GPUs with the parameters described above, the model will send 16 x 8 batches to the 8 GPUS, resulting in 128 batches processed, before performing parameter update?

**Comment by yzhang123** [comment]
@jtourille 
>Am I correct by setting the batch_size to 64 and the batches_per_step to 128?
Yes, that is correct.
Both batch_size and batches_per_step is defined for 1 GPU.
So if you have n GPUs, the global batch will be n x batch_size x batches_per_step.
Hope this answers your question :)

**Comment by jtourille** [comment]
Thanks for the answers, I understand now.
Therefore if I want to train BERT with a batch-size of 8192 for the first phase with 8 GPUs, I should set for instance `batch_size` and `batches_per_step` to 32 and use `python -m torch.distributed.launch --nproc_per_node=8 ....` ?

**Comment by yzhang123** [comment]
@jtourille yes, in addition to that you need to set num_gpus=#total_number_GPUs. Beware that we trained BERT on a small global batch size of 64 or 128 and used only 1 phase with longer sequence length as in the original paper.
So you will probably need to tune the mode and adjust the learning algorithm yourself if you would like to train on large batch.

**Comment by jtourille** [comment]
@yzhang123 Thanks for the explanation. I was planning to reproduce the training from the other NVIDIA repository (https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT) where you did use large batch sizes (8192 for phase 1 and 4096 for phase 2). I will keep your comment in mind in the case I do not succeed.

**Comment by yzhang123** [comment]
@jtourille you are welcome. Can this issue be closed?
