### ISSUE TITLE
Problems with phone type audios 

### ISSUE THREAD

**Issue by evilc3** [NVIDIA/NeMo#4482]
Hi, I hv trained a new conformer model. 

For telephone audios this model performs worse than the pretrained model used for fine-tuning it. 

For Other audios its ok 

Error seen are quite odd instead of insertion or substitution all the errors deletion. It just doesn't transcribe parts of the audio that pretrain model does. 

1. Changes made for training my model 
     - have changed tokens from 128 to 512 added. Puncts. (Same tok type used unigram). 
     
     - Trained on different dataset of size ~10k  hrs. (Amond them fisher was the only telephone speech dataset)

     
     
I am unable to debug where/why this is happening  

Possible ans 
1. Turning data hd problems. 
2. Not enough telephone type training data used. Eg ( asr is not able to transcribe becz the audio is noisy )

Can anyone please pont me in the write direction.

**Comment by okuchaiev** [comment]
I wonder why you changed tokens? I would try not changing the vocabulary.
Also, please share more details on LR, training plots etc.
