### ISSUE TITLE
Train Speaker Diarization model

### ISSUE THREAD

**Issue by AMITKESARI2000** [NVIDIA/NeMo#4533]
Hello,
Can you guide me how to train and fine tune the Speaker Diarization model taught in https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Diarization_Inference.ipynb. I was unable to find any documentation on this
Thanks

**Comment by ValeryNikiforov** [comment]
Hello,
If you want to train speaker embedding model (not VAD), this guide will be helpful: https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Identification_Verification.ipynb
Note the "Speaker Verification" part, it's important to change loss

**Comment by nithinraok** [comment]
Offline Speaker Diarization in NeMo is currently clustering based, so to train SD you need to train VAD and Speaker Embedding extractor as explained here: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/speaker_diarization/datasets.html 


For training MSDD models.. documentation will be added soon.
