### ISSUE TITLE
[text processing] Chinese text normalization PR

### ISSUE THREAD

**Issue by dophist** [NVIDIA/NeMo#4543]
This is a preliminary inquiry if NeMo team is open to accept PR for Chinese text normalization, or you guys have internal development plans for it ?

[SpeechColab](https://github.com/SpeechColab) is assigning 1 intern student to work on Chinese text normalization(based on Pynini), we'd like to contribute this work to NeMo, hopefully in the next couple of weeks.  Basically what we will have is a set of WFST rewrite rules just like existing [NeMo en TN](https://github.com/NVIDIA/NeMo/tree/main/nemo_text_processing/text_normalization/en), reproducing TN behaviors in [this project](https://github.com/speechio/chinese_text_normalization), which handles many typical TN scenarios for Chinese. 

**Known Issue**
The intern student will no longer be maintaining the grammars after the internship, but the resulting PR is guaranteed to establish a foundation, enabling Chinese TN in NeMo.

Would like to hear your thoughts on this. @yzhang123  @ekmb

**Comment by ekmb** [comment]
We would appreciate the proposed PR! Looking forward to the contribution!

**Comment by dophist** [comment]
Cool. I'll close this issue when the PR is ready.
