### ISSUE TITLE
FastSpeech2 training example

### ISSUE THREAD

**Issue by aidosRepoint** [NVIDIA/NeMo#4552]
Hi all!

I couldn't find any examples of FastSpeech2 training. The only thing that I've found was the data preprocessing [tutorial](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/tts/datasets.html)

Can anyone tell me if there is a py script such as those for tacotron2 and other models? And, is there an example of a config file?

**Comment by redoctopus** [comment]
Hi, FastSpeech2 has been deprecated in NeMo, but you can still find a Tacotron2 example in the tutorial here: https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/Tacotron2_Training.ipynb

The scripts and config files for all the TTS models can be found in this directory (configs under `conf/`): https://github.com/NVIDIA/NeMo/tree/main/examples/tts
