### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by grzywada** [NVIDIA/NeMo#4554]
In: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/prompt_learning.html

cartographic -> catastrophic 

Instead of: "Because the original model parameters are frozen and never altered by either method, p-tuning/prompt-tuning also avoid cartographic forgetting issues often encountered when fine-tuning models."

It should be: "Because the original model parameters are frozen and never altered by either method, p-tuning/prompt-tuning also avoid catastrophic forgetting issues often encountered when fine-tuning models."

**Comment by vadam5** [comment]
Thanks, I fixed the typo in this PR: https://github.com/NVIDIA/NeMo/pull/4566 that has been merged.
