### ISSUE TITLE
Quantize conformer model that is trained before

### ISSUE THREAD

**Issue by alexandercesarr** [NVIDIA/NeMo#4569]
Hi, I trained a conformer model before. Now I wanna quantize that model and convert it to TRT. But when I run the **speech_to_text_quant_infer_trt.py** an error occur. The error is:

`TypeError: Error instantiating 'nemo.collections.asr.modules.conformer_encoder.ConformerEncoder' : __init__() got an unexpected keyword argument 'quantize'
`

Could you please help me to solve it?

**Comment by titu1994** [comment]
That script only supports character based models, specifically models that support quantization nodes in their code such as QuartzNet, Jasper, Citrinet. Conformer does not support this.

**Comment by alexandercesarr** [comment]
Thanks @titu1994 for your reply. So if I want to quantize this conformer model, how can I do it?
What is your recommendation for this one?

**Comment by titu1994** [comment]
We don't support it, so there's no recommendations as such. We ourselves have not tried it. @Slyne fyi

**Comment by Slyne** [comment]
Hi @alexandercesarr 

First of all, if you want to deploy your models on GPUs. You may keep reading the below text.

There are two types of quantization that Tensorrt can support, explicit vs implicit. Check their difference [here](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#explicit-implicit-quantization).

Where to get start ?
Try Post Training Quantization (PTQ) first if you can export the conformer onnx model. Then check this simple [example](https://github.com/NVIDIA/TensorRT/tree/master/tools/Polygraphy/examples/api/04_int8_calibration_in_tensorrt). All you need to do is to add a calibrator (to add data loader and feed the real data for the model to better calibrate). 

What if the PTQ model can not meet the accuracy requirement after quantization ?
 
You may try QAT. Please follow [pytorch_quantization](https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/index.html) on a resnet example.

@andi4191 also changed the codes and incorporate some codes to show how to do explicit quantization on NeMo conformer. Check [here](ttps://github.com/andi4191/NeMo/commit/e911612ec53166156241e42537cbe8691836f179).

**Comment by alexandercesarr** [comment]
Hi @Slyne Thank you very much for your great advice and help. I'll try it.

**Comment by Slyne** [comment]
> Hi @Slyne Thank you very much for your great advice and help. I'll try it. But if I want to deploy my model on CPU, what should I do? It's same the above comment or not?

If it's CPU, then you can check [pytorch native quantization pipeline](https://pytorch.org/docs/stable/quantization.html) and [tutorial to get start](https://pytorch.org/blog/introduction-to-quantization-on-pytorch/#the-three-modes-of-quantization-supported-in-pytorch-starting-version-13).

**Comment by alexandercesarr** [comment]
Thank you @Slyne for your help.
