### ISSUE TITLE
parser not found during inference of Tacotron2 TTS on non-english language

### ISSUE THREAD

**Issue by prashantskit** [NVIDIA/NeMo#4574]
**Describe the bug**
I am facing potentially the following two issue:
First
I am training a non-english language TTS model using Tacotron2. During inference I try to pre-process the input text using the parse() function but I get the error `AttributeError: 'Tacotron2Model' object has no attribute 'parser'`. 

Second
On looking deeper into parser and it's initialisation. The property parser function return the parser created in dataset loader class _("AudioToCharDataset")_ but the parser object created inside the class is not instance variable. It is local to the class and not available with dataset object. 
Moreover, in the `nemo.collections.tts.models.Tacotron2Model` there is not placeholder for defining the name of the parser. Ideally it should come from config file.

**Steps/Code to reproduce bug**
Train the TTS on any non-english language dataset.
During inference use _parse_ function to pre-process the text to get tokens.

**Expected behavior**

An error saying `AttributeError: 'Tacotron2Model' object has no attribute 'parser'`

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: pip install nemo-toolkit\['all'\]
 - commands used `docker pull nvcr.io/nvidia/pytorch:22.05-py3` & `docker run --gpus all -it --rm -v /home/prashant/code/NeMo:/NeMo --shm-size=8g -p 8888:8888 -p 6006:6006 --ulimit memlock=-1 --ulimit stack=67108864 --device=/dev/snd nvcr.io/nvidia/pytorch:22.05-py3` 

**Environment details**
Nvidia docker image used mentioned in the README

**Comment by redoctopus** [comment]
Can you try updating to the most recent NeMo version and trying again? Tacotron2 now uses the `TTSDataset` rather than the `AudioToCharDataset` as of version 1.9.0, and the parser logic in the model has been updated as well.

**Comment by prashantskit** [comment]
I am assuming `pip install nemo-toolkit['all']` command will install latest version of the toolkit.
Secondly, I looked through the TTSDataset class and found some of the parameters that were not present earlier such as "text_tokeniser" it also seems to be equivalent of what parser was doing earlier. How to specify it in yaml config file? specifically for non-English dataset.

**Comment by redoctopus** [comment]
Yes, it should install the latest version--currently 1.10--which means that Tacotron2 should no longer depend on the `AudioToCharDataset`.

You may be able to use the `BaseCharsTokenizer` if there is minimal preprocessing needed for your dataset and language, though be wary of the normalizer that you use with it to make sure it's not stripping out characters you need. You can specify it in the config file under `model` as `text_tokenizer`, e.g. in this German language FastPitch config: https://github.com/NVIDIA/NeMo/blob/main/examples/tts/conf/de/fastpitch_align_44100.yaml#L69

**Comment by prashantskit** [comment]
Thanks a lot @redoctopus . I am able to initiate the training and successfully performed inference on 1 epoch trained model. 
 
There is one more thing I would like to ask. I am training 8000 sampling rate model. Can you suggest what is the parameter values I can choose for the same? Like n_mels, window_size and stride, pad_value etc. Also, if I have to train at a smaller batch (32) would reducing learning help ?

**Comment by redoctopus** [comment]
Good to hear!

You shouldn't need to change `n_mels` or `pad_value`, but `window_size`, `window_stride`, and `n_fft` should be scaled up accordingly. Try `window_size=4096`, `window_stride=1024`, and `n_fft=4096`. The default configs are for batch size 32, so the lr should be fine (though do let us know if you find something that works better!).

**Comment by prashantskit** [comment]
Thanks for the quick response. 

I noticed that these three parameters were decreasing from 44K to 22K in the conf file in the repo. But I will try with these settings and update here.
