### ISSUE TITLE
convert conformer to TRT

### ISSUE THREAD

**Issue by sarasesar** [NVIDIA/NeMo#4590]
Hi, I trained a conformer CTC BPE model. Now I wanna convert it to TensorRT.
Is it possible or not?
If yes, how can I do it?

**Comment by titu1994** [comment]
You can follow the export docs to export to onnx, after which it should be straightforward to export that to trt. 

Each model has an export() method, or you can use this script https://github.com/NVIDIA/NeMo/blob/main/scripts/export.py

Fyi @borisfom

**Comment by borisfom** [comment]
Correct - Conformer export to ONNX is supported by Nemo and its ONNX is runnable by TRT.
Note: TRT may have issues with accuracy of this model if you use --fp16.
The workaround is to use nemo2rtiva tool instead of export.py, with --autocast option, and then use Riva deployment to get TRT engine. Riva has built-in internal workaround for this TRT issue.

**Comment by jjjjohnson** [comment]
Hi @borisfom 
I tried to convert conformer onnx to TRT but without success. Looks like some ops in onnx is not supported by TRT:

[Converter error]: OnnxParser: In node 219 (importSlice): UNSUPPORTED_NODE: Assertion failed: (axes.allValuesKnown()) && "This version of TensorRT does not support dynamic axes.

**Comment by jjjjohnson** [comment]
@borisfom @titu1994  BTW:
What does it mean by " ONNX is runnable by TRT." ? Do you mean something like this?
```ort_session = ort.InferenceSession('/content/stt_en_conformer_ctc_small.onnx',providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'])```

Thanks for any hints!

**Comment by catalwaysright** [comment]
> @borisfom @titu1994 BTW: What does it mean by " ONNX is runnable by TRT." ? Do you mean something like this? `ort_session = ort.InferenceSession('/content/stt_en_conformer_ctc_small.onnx',providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'])`
> 
> Thanks for any hints!

@jjjjohnson Hi, do you still have the script you used to convert onnx to tensorrt? Which tensorrt version did you use?
