### ISSUE TITLE
SpeechEncDecSelfSupervisedModel does not support Dali datasets

### ISSUE THREAD

**Issue by piraka9011** [NVIDIA/NeMo#4591]
**Is your feature request related to a problem? Please describe.**

I noticed `SpeechEncDecSelfSupervisedModel`'s don't check if `use_dali` is set in their `_setup_dataloader_from_config()` method.

Is that intended? I noticed some performance improvements using Dali and the error traces it returns are much more helpful than the typical audio dataset ones.

**Describe the solution you'd like**

Just add 

```py
device = 'gpu' if torch.cuda.is_available() else 'cpu'
if config.get('use_dali', False):
    device_id = self.local_rank if device == 'gpu' else None
    dataset = audio_to_text_dataset.get_dali_bpe_dataset(
        config=config,
        tokenizer=self.tokenizer,
        shuffle=shuffle,
        device_id=device_id,
        global_rank=self.global_rank,
        world_size=self.world_size,
        preprocessor_cfg=self._cfg.preprocessor,
    )
    return dataset
```

to `_setup_dataloader_from_config` in `SpeechEncDecSelfSupervisedModel`.

I can open a PR if this if fine, but wanted to see if there was an explicit reason not to include it.

**Comment by titu1994** [comment]
Yes, please open a PR. Mostly it should duplicate the code in the ASR CTC / RNNT classes.
