### ISSUE TITLE
Extract tokeniser from .nemo file

### ISSUE THREAD

**Issue by evilc3** [NVIDIA/NeMo#4620]
Is it possible to extract the sentence_piece tokeniser  (.model, .vocab) file from the .nemo format?

**Comment by titu1994** [comment]
A Nemo file is just a tarfile - you can extract it with tar -xvf as normal.

**Comment by evilc3** [comment]
Oh, thanks man

**Comment by owos** [comment]
Hi @titu1994 is there a way to extend the pretrained vocab and also reflect this change in the model by randomly initializing new embeddings for the new tokens?
