### ISSUE TITLE
Mixer-TTS-X Colab Training example

### ISSUE THREAD

**Issue by gedefet** [NVIDIA/NeMo#4642]
Hello.

Is any script for training Mixer-TTS-X?

I've used it in the model select inference example, and I really like how it sounds. Better than FastPitch and MixerTTS, in my opinion. Also in the paper shows a higher MOS.

I think it would be extremely useful.

Thanks,

**Comment by redoctopus** [comment]
Yes, you should be able to use the normal [Mixer-TTS example script](https://github.com/NVIDIA/NeMo/blob/main/examples/tts/mixer_tts.py) but with the Mixer-TTS-X config instead: https://github.com/NVIDIA/NeMo/blob/main/examples/tts/conf/mixer-tts-x.yaml
