### ISSUE TITLE
Confidence score for each word in asr model

### ISSUE THREAD

**Issue by catalwaysright** [NVIDIA/NeMo#4661]
Hi! I am trying `nvidia/stt_en_conformer_transducer_xlarge` for my ASR system and the performance is impressive. I noticed that there is an option in transcribe function that can support lm_score in output. I wonder if it is possible to generate confidence score for each word or where should I modify the code so that it can show the confidence score for each word. Thanks in advance,

**Comment by titu1994** [comment]
We have not yet added support for LM or confidence score in asr model using Hypothesis framework yet, they are placeholders for future support.

**Comment by catalwaysright** [comment]
> 

Then which part of code should I modify if I want to support this on my own. Could you give me a guide or a direction?

**Comment by titu1994** [comment]
It's not straightforwardness to setup word confidence, especially for RNNT models. I don't have a particular reference at the moment to compute word confidence. Fyi @GNroy

**Comment by GNroy** [comment]
@catalwaysright I'm working on word-level confidence for greedy CTC and RNNT decoding.
Could you please describe your confidence use case?

**Comment by catalwaysright** [comment]
> @catalwaysright I'm working on word-level confidence for greedy CTC and RNNT decoding. Could you please describe your confidence use case?

Basically I just want the word-level confidence like you are working so that I can highlight those words that are more likely to be wrong if the confidence is below threshold. It would be even better if the model can generate top 3 confident words for that position.

**Comment by catalwaysright** [comment]
@GNroy How is your implementation right now? Since we can get log prob for CTC, is it possible to get word-level prob though this?

**Comment by GNroy** [comment]
@catalwaysright We can certainly use log-probabilities as confidence scores, but this would not be the best approach because the probability distributions of the CTC and RNNT models are biased towards the best hypothesis. In other words, the confidence will be close to one for both correct and incorrect units.
I'm working on an approach that alleviates this issue.

**Comment by shihabtechno** [comment]
@GNroy could you please tell  what is the mechanism to calculate word level confidence score?I was following [this blog](https://discuss.huggingface.co/t/confidence-scores-self-training-for-wav2vec2-ctc-models/17050),unfortunately, it seems not convincing.

**Comment by GNroy** [comment]
@shihabtechno Sorry for the late responce.
Word level confidence estimation is now in main.
In short, one has to calculate per-frame scores and then aggregate them to unit- and word-level scores.
[Here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/utils/asr_confidence_utils.py#L64#L145) you can find functions for per-frame confidence estimation and aggregation.
[This](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/utils/asr_confidence_utils.py#L266#L310) is how to aggregate word scores for a wordpiece-based model.

**Comment by MinhNghia100402** [comment]
@GNroy Excuse Me, can I refer from you the method used for RNNT model like word boosting method in riva?
