### ISSUE TITLE
Docker build error: rpc error: code = Unknown desc

### ISSUE THREAD

**Issue by joehoeller** [NVIDIA/NeMo#467]
```
 => ERROR [nemo 2/10] RUN /usr/bin/test -n "$NEMO_VERSION" &&     /bin/ec  0.4s
------
 > [nemo 2/10] RUN /usr/bin/test -n "$NEMO_VERSION" &&     /bin/echo "export NEMO_VERSION=${NEMO_VERSION}" >> /root/.bashrc &&     /bin/echo "export BASE_IMAGE=nvcr.io/nvidia/pytorch:20.01-py3" >> /root/.bashrc:
------
rpc error: code = Unknown desc = executor failed running [/bin/sh -c /usr/bin/test -n "$NEMO_VERSION" &&     /bin/echo "export NEMO_VERSION=${NEMO_VERSION}" >> /root/.bashrc &&     /bin/echo "export BASE_IMAGE=${BASE_IMAGE}" >> /root/.bashrc]: exit code: 1
```

**Comment by joehoeller** [comment]
@blisc any word on this?

**Comment by okuchaiev** [comment]
what docker version are you using (should be >=19.03).
The following seems to work for me:
```DOCKER_BUILDKIT=1 docker build --build-arg NEMO_VERSION=$(git describe --tags) -t nemo . ```

**Comment by joehoeller** [comment]
@okuchaiev thanks that worked for me - i had to upgrade my docker. 
_**Last ques -**_  What is the appropriate run command?

**Comment by joehoeller** [comment]
@okuchaiev  ***friendly bump***

**Comment by okuchaiev** [comment]
>>"What is the appropriate run command?"
 - Did you mean the command to run docker?
Here it is: "docker run --runtime=nvidia -it --rm -v <nemo_github_folder>:/NeMo --shm-size=8g -p 8888:8888 -p 6006:6006 --ulimit memlock=-1 --ulimit stack=67108864 nemo"   (here I'm assuming that you called your docker image "nemo" during the build stage"

**Comment by joehoeller** [comment]
Thanks!

**Comment by joehoeller** [comment]
@okuchaiev I got my solution to work w RAPIDS if you’re interested - https://github.com/joehoeller/NVIDIA-Rapids-NeMo-PyTorch-Tensorboard
