### ISSUE TITLE
What & where is the .nemo file?

### ISSUE THREAD

**Issue by camillebrl** [NVIDIA/NeMo#4681]
Hello!

I would like to run the train_kenlm.py file but I do not understand all the arguments it requires: 

I read the documentation (https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html and I ran install_beamsearch_decoders.sh as well, so I have the kenlm bin root but I have no idea how to get the root of the .nemo file and what it is about?

Thanks in advance!

**Comment by titu1994** [comment]
In Nemo, all models are saved with extension .nemo - they are tarfiles. Please read the documentation to understand how to save and restore Nemo files (save_to, restore_from, and from_pretrained)

For simplicity you can open a python shell, import nemo.collections.asr as asr, and do model = asr.models.ASRModel.from_pretrained(some ASR model name), followed by model.save_to("xyz.nemo") to get a Nemo file

**Comment by camillebrl** [comment]
thanks a lot!
