### ISSUE TITLE
No such file or directory: 'examples/asr/configs/jasper12x1SEP.yaml'

### ISSUE THREAD

**Issue by fnl** [NVIDIA/NeMo#470]
I was trying to go through the [ASR tutorial](https://nvidia.github.io/NeMo/asr/tutorial.html). But I am a bit blocked as the YAML file that supposedly is part of this GitHub repository (see path in issue title) clearly does not there. The YAML file is referenced in the [training script](https://nvidia.github.io/NeMo/asr/tutorial.html#training) part of the tutorial.

Can somebody please help/advise? Thank you!

**Comment by blisc** [comment]
You can grab the config yaml as referenced from the v0.9.0 release: https://github.com/NVIDIA/NeMo/tree/v0.9.0

Alternatively, the files has been renamed to quartznet12x1.yaml, although the instructions from v0.9.0 might not be fully compatible with the renamed config.

**Comment by okuchaiev** [comment]
Master branch docs: http://nemo-master-docs.s3-website.us-east-2.amazonaws.com/
