### ISSUE TITLE
Automatic Speech Recognition (ASR)

### ISSUE THREAD

**Issue by Shaiken** [NVIDIA/NeMo#4704]
純粹好奇詢問...
為什麼NeMo沒有做繁體中文相關的
還是有我只是沒發現?

**Comment by titu1994** [comment]
We do have a few models for AISPEECH 2 dataset, however there are not many publically and commercially allowed asian language datasets such for Chinese, Korean, Japanese etc. We're limited to use datasets which have permissive licenses otherwise we cannot share pretrained Checkpoints

**Comment by Shaiken** [comment]
謝謝您的回覆
