### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by Project-fil** [NVIDIA/NeMo#4732]
I am training ru model with these inputs data:

My code:

```
import nemo
import nemo.collections.asr as nemo_asr
import pytorch_lightning as pl

from nemo.utils.exp_manager import exp_manager
from omegaconf import DictConfig, OmegaConf

params = OmegaConf.load(model_conf_path)

params.trainer.gpus = 1
params.model.train_ds.manifest_filepath = train_manifest_path
params.model.validation_ds.manifest_filepath = validation_manifest_path
params.model.test_ds.manifest_filepath = test_manifest_path
params.exp_manager.exp_dir = 'path/to/save'

trainer = pl.Trainer(**params.trainer)
model = nemo_asr.models.EncDecCTCModel(cfg=params.model, trainer=trainer)
exp_manager(trainer=trainer, cfg=params.exp_manager)

trainer.fit(model)
trainer.test(model)

```

Train manifest file looks like this:
{"audio_filepath": ""/path/to/wav", "duration": 4.8, "text": "у вас просроченных дней две тысячи сто шестьдесят один дней"}
{"audio_filepath": "/path/to/wav", "duration": 9.1, "text": "выключай выключай давайте следующую свечу других нет сейчас расскажу один анекдот когда"}
Total files: 34786
Duration - 601 hours.

There is yaml config:
https://github.com/Project-fil/Project-fil/blob/main/quartznet_ru.yaml

The training takes place in 4 epoch.
Test_loss - 65.60244750976562 
Test_wer - 0.928061842918396

I get five files in dir 'checkpoints':
```
'QuartzNet15x5_ru--val_wer=0.9281-epoch=4-last.ckpt'
'QuartzNet15x5_ru--val_wer=0.9765-epoch=2.ckpt'  
'QuartzNet15x5_ru--val_wer=0.9594-epoch=3.ckpt'
'QuartzNet15x5_ru--val_wer=0.9281-epoch=4.ckpt'       
 QuartzNet15x5_ru.nemo
```

And when i try to decode wav file, with this code:

```
first_path = path/to/QuartzNet15x5_ru--val_wer=0.9281-epoch=4-last.ckpt  # or another *.ckpt
restored_model = nemo_asr.models.EncDecCTCModel.load_from_checkpoint(first_path)
rt = restored_model.transcribe([aud_ru])
print(rt)
```

I get this: 
['просротеяне две тстистоиеяьдесят тоде нде']
and 
['аич д брдие еча скожеден ниду']
instead:
['у вас просроченных дней две тысячи сто шестьдесят один дней']
and
['выключай выключай давайте следующую свечу других нет сейчас расскажу один анекдот когда']

All files that I decode are decrypted incorrectly
Am I doing something wrong or not enough hours to learn?

**Comment by titu1994** [comment]
Your model has 92.81% wer - QuartzNet15x5_ru--val_wer=**0.9281**-epoch=4-last.ckpt - so it has not learned enough yet.

**Comment by Project-fil** [comment]
Please tell me what is the minimum audio hours and epochs needed to have a good result?

**Comment by nick9arcia** [comment]
> Please tell me what is the minimum audio hours and epochs needed to have a good result?

Many hours. There are many models that are trained with over 5000 hour and still have a high WER. KEEP TRAINING!

**Comment by Project-fil** [comment]
If I train the model with the fit() method for n hours and n epochs, and then take a breakpoint and apply fit() with fewer hours and epochs, but with a different dataset, will I retrain or overwrite the model?

**Comment by nick9arcia** [comment]
> If I train the model with the fit() method for n hours and n epochs, and then take a breakpoint and apply fit() with fewer hours and epochs, but with a different dataset, will I retrain or overwrite the model?

Retain what you have. You can make a copy of a lower breakpoint and use it to test train the model with a different dataset

**Comment by Project-fil** [comment]
Thanks a lot.
