### ISSUE TITLE
How to calculate models strides per sec 

### ISSUE THREAD

**Issue by evilc3** [NVIDIA/NeMo#4750]
How to calculate `models_stride_per_sec` for stt_es_conformer_ctc_large. model.   I am trying to transcribe audio of 1 hr using the 

stt_en_conformer_ctc_large its 0.04

`from nemo.collections.asr.parts.utils.decoder_timestamps_utils import FrameBatchASR_Logits`

is there a better way to stream log audios on the conformer models.
@titu1994

**Comment by titu1994** [comment]
This is a factor determined by the model. All Conformers have 4x stride, and by default (at least for now) the preprocessor has a window stride of 0.01 seconds. So yes, 0.04 is the correct value. 

If you are using for long audio, you can use the buffered inference scripts for CTC and RNNT models provided in the asr_chunked example folder.

**Comment by titu1994** [comment]
When using those scripts use buffer sizes of 25 seconds and chunk sizes of 20 sec for good accuracy vs inference speed tradeoff.

**Comment by evilc3** [comment]
@titu1994  yes it worked thanks a ton. Steps I was using were similar will need to check were I was going wrong.

**Comment by evilc3** [comment]
Had a followup question, does stt_es_citrinet_512 or 1024 model require batch_streaming? becz they don't have the same memory requirement as a conformer model. 

I have transcribed a 50min audio just using the citricnet_512 model

**Comment by titu1994** [comment]
Citrinets do not require as much memory as Conformer, then can do around an hour on 16 GB of memory at batch size 1 just fine c

**Comment by evilc3** [comment]
yes, the citrinet_512 takes 2 min and max 2.5 gb to transcribe 50 min audio for me.

**Comment by evilc3** [comment]
another thing I have noticed is using buffered inference scripts gets lower wer results then compared to asr_model.transcribe method.

**Comment by titu1994** [comment]
That's expected, buffered model has limited context compared to Citrinet that has global context over an entire hours of speech

**Comment by evilc3** [comment]
well for stt_es_citrinet_1024_gamma_0_25 model  buffer_transcript gives 10.0 % wer and just using transcribe gives 19% wer why is this?

**Comment by titu1994** [comment]
The model was trained on 20 second audio clips, and is asked to eval 1 hour long audio clip. Ofcourse it wont be as accurate cause it never saw anything that long during training. Squeeze excitation does not do well when averaging over such long sequences. But it allows offline transcription of long files with some effective accuracy. 

Buffered transcribe splits audio into chunks close to training duration so each chunk is slightly more accurate, bit global context is lost and you have to merge chunks, both of which can increase wer. It's upto the model and the dataset which method will do better c

**Comment by evilc3** [comment]
got it thanks
