### ISSUE TITLE
Use of undeclared `logger`.

### ISSUE THREAD

**Issue by gwarmstrong** [NVIDIA/NeMo#4772]
`logger` is used here but not defined

https://github.com/NVIDIA/NeMo/blob/6abfbbfda654f44313068b950edb0f70b01449b1/nemo/collections/nlp/data/language_modeling/text_memmap_dataset.py#L157

I believe this should be switched to `logging`, which is used throughout the rest of the module.

**Comment by SeanNaren** [comment]
Thanks for the issue! should be resolved :)
