### ISSUE TITLE
Broken link to notebook in documentation

### ISSUE THREAD

**Issue by miguelusque** [NVIDIA/NeMo#4775]
**Describe the bug**
Hi,

I have just found a broken link to a notebook in this page: https://docs.nvidia.com/deeplearning/nemo/best-practices/index.html

In the "Table 1. Tutorials", the "Question answering with SQuAD" notebook link is broken.

Instead of:

https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/Question_Answering_Squad.ipynb

it should be:

https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/Question_Answering.ipynb

Hope it helps!

**Comment by miguelusque** [comment]
In addition to the above, in the same page, at the bottom, it seems that there is some content that is not needed, referring to VESA DisplayPort, HDMI... It looks like a copy and paste from a template issue.

> VESA DisplayPort
> DisplayPort and DisplayPort Compliance Logo, DisplayPort Compliance Logo for Dual-mode Sources, and DisplayPort Compliance Logo for Active Cables are trademarks owned by the Video Electronics Standards Association in the United States and other countries.
> 
> HDMI
> HDMI, the HDMI logo, and High-Definition Multimedia Interface are trademarks or registered trademarks of HDMI Licensing LLC.
> 
> ARM
> ARM, AMBA and ARM Powered are registered trademarks of ARM Limited. Cortex, MPCore and Mali are trademarks of ARM Limited. All other brands or product names are the property of their respective holders. "ARM" is used to represent ARM Holdings plc; its operating company ARM Limited; and the regional subsidiaries ARM Inc.; ARM KK; ARM Korea Limited.; ARM Taiwan Limited; ARM France SAS; ARM Consulting (Shanghai) Co. Ltd.; ARM Germany GmbH; ARM Embedded Technologies Pvt. Ltd.; ARM Norway, AS and ARM Sweden AB.
> 
> OpenCL
> OpenCL is a trademark of Apple Inc. used under license to the Khronos Group Inc.
> 
>

**Comment by MaximumEntropy** [comment]
@yzhang123 not sure if you are the best person to answer this, but if not please tag the appropriate person.

**Comment by yzhang123** [comment]
@Zhilin123 could you please take a look?

**Comment by Zhilin123** [comment]
We have fixed this with https://github.com/NVIDIA/NeMo/pull/4895

The other issue with VESA DisplayPort, HDMI ... is due to a standard NVIDIA template that is not specific to or customizable by each product (i.e. NeMo) so it might not possible to remove that.
