### ISSUE TITLE
Get real time through timestep in asr

### ISSUE THREAD

**Issue by catalwaysright** [NVIDIA/NeMo#4783]
Hi! Is it possible to get real time in seconds through the end_offset and start_offset in asr models like ctc or rnnt?

**Comment by titu1994** [comment]
You can get the explicit timestep from model.transcribe() with some special flags, and then work out how that maps to time steps using the model stride and the preprocessor window stride. There will be a new Nemo tutorial in release 1.11 which showcases this - https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/asr/Offline_ASR.ipynb
