### ISSUE TITLE
Best Speech Model Architecture

### ISSUE THREAD

**Issue by Raj-Anjul** [NVIDIA/NeMo#4785]
Hi,
I'm new in ASR and want to know the best model architecture or recipe to meet my requirement.
I'm looking a model that can servers:

1. Streaming ASR with minimum latency.
2. SOTA accuracy in generic domain with decent amount of data (1-4K hours).
3. Can handle good throughput in streaming.

**Comment by titu1994** [comment]
I would suggest Conformer CTC for all cases since it is supported by Nvidia Riva, attains excellent stable streaming performance, can scale to 25,000+ hours of speech without showing signs of lack of capacity and can soon be used in Nemo with cache aware streaming inference with fixed latency.
