### ISSUE TITLE
What data was used to train the German Conformer Transducer?

### ISSUE THREAD

**Issue by carlosfranzreb** [NVIDIA/NeMo#4809]
Hello,

in the [model's page](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_de_conformer_transducer_large), it is said that the model was trained on:

- 567 hours of MCV7
- 1524 hours of MLS
- 214 hours of VoxPopuli

I am wondering how the subsets for each dataset were chosen, especially for MCV, where there is accented data. Unfortunately, I could not find the details of this dataset online. Could you please clarify how the subsets were chosen?

Kind regards,
Carlos

**Comment by titu1994** [comment]
@yzhang123 could you comment ? Might also be worth adding some info to the hf model card.

**Comment by yzhang123** [comment]
we used a pretrained Quartznet ASR model (https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_de_quartznet15x5), and used that to filter out audio data that has a a very high WER rate (which usually means there is some error in the transcript, especially true for MLS). We used our internal scripts to do that, which we plan on publishing in the future.

**Comment by carlosfranzreb** [comment]
Thank you for the quick reply! Do you also filter out accented data from MCV? Or is accented data also fed to the QuartzNet model? Ideally, I would like to know the accent distribution of the MCV subset you used to train the model.

**Comment by carlosfranzreb** [comment]
Alright, thank you. One last question: did you use the whole MCV to train the QuartzNet? Or did you use any filtering for that?

**Comment by yzhang123** [comment]
whole MCV, apart from samples with non-german characters. But please note, that the Quartznet we trained is old, and as well as the MCV version back then. But i think the exact version does not matter. It more about the bootstrapping step to pre-filter your data.

**Comment by carlosfranzreb** [comment]
Thank you very much for your time!
