### ISSUE TITLE
Fine tuning stt_en_conformer_transducer_xxlarge gives a dtype error on GPU ( A100) 

### ISSUE THREAD

**Issue by 1shershah** [NVIDIA/NeMo#4812]
Getting a  "TypeError: __init__() got an unexpected keyword argument 'dtype'" 
at `File python3.8/site-packages/nemo/collections/asr/parts/submodules/subsampling.py:144, in ConvSubsampling.forward(self, x, lengths)
    140 x = x.unsqueeze(1)
    141 if self._subsampling == 'striding':
    142     # added in order to prevent slowdown in torch.nn.Conv2d with bfloat16 / CUDNN v8 API
    143     # to be removed once the above is fixed in cudnn
--> 144     with torch.cuda.amp.autocast(dtype=torch.float32):
    145         x = self.conv(x)`

**Steps/Code to reproduce bug**
```
pretrained =None
try:
    pretrained = nemo_asr.models.EncDecRNNTBPEModel.from_pretrained(model_name="stt_en_conformer_transducer_xxlarge")
except:
    pretrained = nemomodels.EncDecRNNTBPEModel.restore_from(restore_path= model_loc_path)
pretrainedConfig = DictConfig(pretrained.cfg)
pretrainedConfig.train_ds.manifest_filepath = TRAIN_MANIFEST
pretrainedConfig.validation_ds.manifest_filepath = VALIDATION_MANIFEST
pretrainedConfig.test_ds.manifest_filepath = TEST_MANIFEST
pretrainedConfig['train_ds']['is_tarred'] = False
pretrainedConfig['train_ds']['tarred_audio_filepaths'] = None
pretrainedConfig['validation_ds']['is_tarred'] = False
pretrainedConfig['validation_ds']['tarred_audio_filepaths'] = None
pretrained.set_trainer(trainer)
pretrained.setup_training_data(pretrainedConfig['train_ds'])
pretrained.setup_validation_data(pretrainedConfig['validation_ds'])


from nemo.utils import exp_manager
from omegaconf import OmegaConf

# Environment variable generally used for multi-node multi-gpu training.
# In notebook environments, this flag is unnecessary and can cause logs of multiple training runs to overwrite each other.
os.environ.pop('NEMO_EXPM_VERSION', None)

exp_config = exp_manager.ExpManagerConfig(
    exp_dir=f'experiments/',
    name=f"Transducer-Model",
    checkpoint_callback_params=exp_manager.CallbackParams(
        monitor="val_wer",
        mode="min",
        always_save_nemo=True,
        save_best_model=True,
    ),
)

exp_config = OmegaConf.structured(exp_config)
logdir = exp_manager.exp_manager(trainer, exp_config)

# Train the model
trainer.fit(pretrained)
```

The same code works on a CPU , but fails on A100 GPU

nemo-toolkit              1.10.0    
torch                     1.9.0+cu111             
torch-stft                0.1.4                
torchaudio                0.9.0                  
pytorch-lightning         1.7.2

Linux cloud-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux

A100 GPU on GCP gace this dtype error , but worked okay on CPU

**Comment by titu1994** [comment]
Please upgrade your pytorch version to 1.11 or 1.12

**Comment by 1shershah** [comment]
Yep that fixed it. 
For others A-100 on GCP machines   CUDA 11.3 - torch 1.11 and pytorch-ligtening 1.7.3 combo worked

**Comment by titu1994** [comment]
Cool!
