### ISSUE TITLE
Speaker Diarization Inference - unable to detect number of speakers when oracle_num_speakers set to False

### ISSUE THREAD

**Issue by sjsakshi** [NVIDIA/NeMo#4818]
I am new to nemo and following this Colab notebook - https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Diarization_Inference.ipynb

When I try set num_speakers = None in manifest file and set config.diarizer.clustering.parameters.oracle_num_speakers=False , and run it without oracle vad diarization,  it only detects one speaker even for the example file provided in the notebook

This is the code I amended:

```
an4_audio_url = "https://nemo-public.s3.us-east-2.amazonaws.com/an4_diarize_test.wav"
an4_audio = wget.download(an4_audio_url, data_dir)

`import json
meta = {
    'audio_filepath': an4_audio, 
    'offset': 0, 
    'duration':None, 
    'label': 'infer', 
    'text': '-', 
    **'num_speakers': None,** 
    'rttm_filepath': None, 
    'uem_filepath' : None
}
with open('data/input_manifest.json','w') as fp:
    json.dump(meta,fp)
    fp.write('\n')



**config.diarizer.clustering.parameters.oracle_num_speakers=False**

```

Can someone help me with why it is not able to predict two speakers?

**Comment by pokameswaran** [comment]
I am also facing the same issue as described by sjsakshi. The issue occurs regardless of VAD method used: Oracle VAD, Non Oracle VAD or ASR based VAD. So, it seems to be a an issue in the clustering step. 

**Code / Notebooks:**
I tried using 2 tutorial notebooks provided by NeMo in below links and found the same issue: https://github.com/NVIDIA/NeMo/blob/stable/tutorials/speaker_tasks/Speaker_Diarization_Inference.ipynb, https://github.com/NVIDIA/NeMo/blob/stable/tutorials/speaker_tasks/ASR_with_SpeakerDiarization.ipynb

**Environment Details:**
I ran the above mentioned notebooks in Google Colab.

**Issue Description:**
Diarization works perfectly with DER = 0 for all 3 options (Oracle VAD, Non Oracle VAD using vad_marblenet, ASR based VAD) when we specifically provide the exact number of speakers in the audio file in the parameters.

But, upon modifying the following 2 parameters, diarization is unable to recognize the different speakers; it is assigning entire audio duration to a single speaker. This results in Diarization ER: 0.4294 and Confusion ER:0.4294.
```
1. 'num_speakers': None (in input_manifest.json)
2. config.diarizer.clustering.parameters.oracle_num_speakers = False
```

The tutorial does mention the following: "_if you would like to evaluate with known number of speakers pass the value else None_". So, I believe None is a valid value to be passed for "num_speakers" parameter. 

Moreover, in our use case, we do not have any prior knowledge about the number of speakers in the audio file we will be processing and expect the diarization utility to provide us that information.

Are there any additional parameters we need to modify to enable the diarizer to identify the number of speakers automatically? Or, is it an issue that needs to be debugged from your end. I would highly appreciate any inputs to overcome this issue.

Thanks, Ponniah

**Comment by sjsakshi** [comment]
I am a little stuck understanding what I might do to solve this issue. I would highly appreciate if someone could help !!

Thanks,

**Comment by SeanNaren** [comment]
Sorry @sjsakshi @pokameswaran for the delay!

This definitely seems like a clustering issue, as the number of speakers are not being inferred correctly (Adding a print statement inside the code, I see 1 speaker being selected by the clustering algorithm).

What helped is using multi-scale weights when segmenting the audio before clustering. This involved replacing these in the config:

```python
config.diarizer.speaker_embeddings.parameters.window_length_in_sec = [1.5,1.0,0.5]
config.diarizer.speaker_embeddings.parameters.shift_length_in_sec = [0.75,0.5,0.25]
config.diarizer.speaker_embeddings.parameters.multiscale_weights = [0.33,0.33,0.33]
```

These are values taken from the example found in the code. We now segment the audio in various "window lengths" and weight each scale equally to hopefully provide more information when clustering.

Using this in the notebook without oracle speakers, gave me 2 speakers!

Pinging @tango4j @nithinraok for further remarks.

**Comment by tango4j** [comment]
@sjsakshi: What @SeanNaren mentioned (multiscale settings) could definitely help while keeping the other VAD parameters in the tutorial.
The parameters used in the old tutorial are still using single scale which could deliver more errors on speaker counting.

We are doing PR for new tutorial where oracle_num_speakers=False can also deliver 2 speakers with system VAD inference.

We recently updated diarization inference recipes [in this folder](https://github.com/NVIDIA/NeMo/tree/main/examples/speaker_tasks/diarization/conf/inference) so please use these settings depending on your domain of interest.

This thread can be closed once new tutorial PR is merged.

**Comment by fayejf** [comment]
Please refer to the changes in PR https://github.com/NVIDIA/NeMo/pull/4861
Let use know if it helps or if you encounter any other issue. Thanks!
