### ISSUE TITLE
Need Info on train dataset 'augmentor' key in the config.yml file.

### ISSUE THREAD

**Issue by evilc3** [NVIDIA/NeMo#4832]
Found this  lines in the stt_es_conformer_ctc_large config  file 

'augmentor': {'noise': {'prob': 0.1, 'manifest_path': '/rir_noises_tarred/noises_20s_tarred/tarred_audio_manifest.json', 'audio_tar_filepaths': '/rir_noises_tarred/noises_20s_tarred/audio_{0..255}.tar', 'min_snr_db': 0, 'max_snr_db': 30}, 'transcode_aug': {'prob': 0.2}}, 'is_tarred': False, 'tarred_audio_filepaths': None, 'shuffle_n': 2048}

could not find reference of this key  in any notebooks in the tutorial dir.

how to obtain these nose manifest ?  (is this related to the online_noise_augmentation.ipynb notebook)?,  
will setting this to none affect the new model being trained?

**Comment by jbalam-nv** [comment]
@evilc3 these are data augmentation  methods that we sometimes use to make the models more robust to noise. You can set the augmentor to none to turn it off. 
Yes, the augmentation methods are covered in the online_noise_augmentation.ipynb notebook.
