### ISSUE TITLE
Check if conda is active rather than if it is present - reinstall.sh

### ISSUE THREAD

**Issue by anand-nv** [NVIDIA/NeMo#4836]
**Describe the bug**
https://github.com/NVIDIA/NeMo/blob/main/reinstall.sh#L27
This should  check if conda is active (`  [ -n "${CONDA_PREFIX}" ] `) rather than if conda is present (`   [ -x "$(command -v conda)" ]
 `). 
Ref: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
If conda is installed on a system, but a standard python virtual environment is being, this fails to install nemo correctly. 

**Steps/Code to reproduce bug**

- Deactivate conda
- Create a python virtual environment
- Install Nemo in it

**Comment by titu1994** [comment]
Reinstall isn't really the recommended install option, we lay out how to install the individual Nemo components in the readme and in the docs. 

Anyway, we can try this approach.

**Comment by nithinraok** [comment]
Thanks for reporting and suggestion, fixed with https://github.com/NVIDIA/NeMo/pull/4970
