### ISSUE TITLE
Streaming conformer CTC ASR: is there an optimal audio duration per chunk?

### ISSUE THREAD

**Issue by leecming82** [NVIDIA/NeMo#4837]
If I'm chunking audio (with context audio at the sides) to handle long audio files, is there an optimal chunk duration (e.g. 30 seconds, 15 seconds) or does it not matter?
 
I've noticed fairly different predictions between the two aforementioned durations

**Comment by titu1994** [comment]
Larger chunk sizes help upto a point - beyond which it is nearly identical to offline prediction (if Conformer could do offline prediction for such long audio). 

I'd recommend around 20 second chunks, with 5 second buffer (so 25 second total buffer) cause that was the training batch length. However if you see better wer with larger chunks, that can be used too, theres no universal answer and it depends on the dataset.
