### ISSUE TITLE
Why `.float()` is in `conformer_modules.py`?

### ISSUE THREAD

**Issue by grazder** [NVIDIA/NeMo#4840]
https://github.com/NVIDIA/NeMo/blob/eae1684f7f33c2a18de9ecfa42ec7db93d39e631/nemo/collections/asr/parts/submodules/conformer_modules.py#L259

Hi! I'm wondering why `.float()` is here. It seems like it will break code if both model parameters and input in float16

**Comment by grazder** [comment]
`.masked_fill` works both for float16 and bfloat16, so i still don't get an idea of `.float()` here. Is there any possibility that forward will get not float (16/32) type?

**Comment by titu1994** [comment]
I know that these things were required to make Conformer train properly in fp16, but @bmwshop can provide details of why this specific case was necessary

**Comment by titu1994** [comment]
@bmwshop could you take a look ?
