### ISSUE TITLE
How to Convert FastPitch and HifiGan Nemo models to TensorRT ? Is there any script available for it? 

### ISSUE THREAD

**Issue by JayZ92-99** [NVIDIA/NeMo#4848]

**Comment by XuesongYang** [comment]
@titu1994 could you please share any pointers about this if any? Thanks.

**Comment by XuesongYang** [comment]
@JayZ92-99 you may need to convert NeMo models into ONNX before deploying to the TensorRT inference engine. This doc show how to: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/core/export.html?highlight=onnx
