### ISSUE TITLE
CUSOLVER_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by Lagstill** [NVIDIA/NeMo#4855]
**Describe the bug**
For few audio file has this error when calling speaker diariation function, Error Message as below:
Error:cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling cusolverDnSsyevd(handle, jobz, uplo, n, A, lda, W, work, lwork, info)

**Steps/Code to reproduce bug**
The error might be occuring  in the function clustering: nmsec , when call eigh(laplacian) with cuda (cuda device =1/0).

def eigDecompose(laplacian, cuda, device=None):
print(len(laplacian))
if TORCH_EIGN:
if cuda:
if device is None:
device = torch.cuda.current_device()
A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**
A diarised audio file

**Environment overview (please complete the following information)**
Linux environment, 4 gpus

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version :Microsoft Windows [Version 10.0.19044.1889]
- PyTorch version : 1.12.0+cu102
- Python version: Python 3.7.13
- -Nemo :1.8
- Cuda : 11.6

**Additional context**
Re-opening wrt :https://github.com/NVIDIA/NeMo/issues/3757#issue-1150037680

**Comment by tango4j** [comment]
Hi. Your pytorch version is for old version of CUDA 10.2. Could you try with more up-to-date CUDA version and Pytorch together? This error happened when we use old version of pytorch.

**Comment by Lagstill** [comment]
Will check on the updation
