### ISSUE TITLE
How to enable kenlm weight accounting with Conformer-CTC acoustic model on BPE tokens?

### ISSUE THREAD

**Issue by psydok** [NVIDIA/NeMo#4872]
Trained Conformer-CTC on BPE tokens, tried to make a prediction based on kenlm. But all the predictions turned out to be just nonsense from one word.

As I understand it, this is due to the fact that models on BPE tokens return an underscore instead of a space.
Tell me, can this problem be somehow elegantly solved in order to use kenlm with an acoustic model on BPE?

From thoughts, can kenlm be trained on texts where there is an underscore instead of a space? But that doesn't seem to work...

**Comment by titu1994** [comment]
We have scripts, and documentation for kenlm with bpe models, please find it on the documentation pages.

**Comment by psydok** [comment]
Thanks for the hint, I found this script: https://github.com/NVIDIA/NeMo/blob/41f27a5e68934761b05dd373e7b288aa798858e5/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py#L112

And I rewrote the decoding lm model:
```python
TOKEN_OFFSET = 100
vocab = [chr(idx + TOKEN_OFFSET) for idx in range(len(quartznet_golos.decoder.vocabulary))]
ids_to_text_func = quartznet_golos.tokenizer.ids_to_text
beam_search_lm = nemo_asr.modules.BeamSearchDecoderWithLM(
            vocab=list(quartznet_golos.decoder.vocabulary),
            beam_width=16,
            alpha=2,
            beta=1.5,
            lm_path=path_kenlm, 
            num_cpus=1,
            cutoff_prob=1.0,
            cutoff_top_n=40,
#             input_tensor=True
              input_tensor=False,
  )

def infer_beam_search_lm(files, asr_model, beam_search_lm):
    hyps = []
    logits = [torch.tensor(logit) for logit in asr_model.transcribe(files, batch_size=8, logprobs=True)]
    log_probs_length = torch.tensor([logit.shape[0] for logit in logits])
    logits_tensor = torch.nn.utils.rnn.pad_sequence(logits, batch_first=True)
    for j in range(logits_tensor.shape[0]):
        s = time.time()
        best_hyp = beam_search_lm.forward(log_probs = logits_tensor[j].unsqueeze(0),
                                          log_probs_length=log_probs_length[j].unsqueeze(0))#[0][0][1]
        for candidate_idx, candidate in enumerate(best_hyp):
            if ids_to_text_func is not None:
                print(candidate)
                # For BPE encodings, need to shift by TOKEN_OFFSET to retrieve the original sub-word ids
                pred_text = ids_to_text_func([ord(c) - TOKEN_OFFSET for c in candidate[1]])
            else:
                pred_text = candidate[1]
        
        hyps.append(pred_text)
        times.append(time.time() - s)
    return hyps
```
But I'm checking candidates...
LM gives this:
`[(nan, 'ыуйторютфвтчпежгрумнсжлчвдйтчццаруэкаячгупасжювэсиибйупхжясатжонанхсяхщафягдяотчймчуицогяйббюевоиайачлиййэсгжюрпцфяпфаюжзнхгнгуйыолегэрфынехгабоаюммфылрммфкхюяаонрээмэывяюумюбциыянвывфмляттыегуэтюэмэдрзгжззцржмйхбпчзбамвэкжхпяцйзпоуттйеетшажлунтмтйфясочсхегужштокзазгцс'),...]`

**Comment by psydok** [comment]
If `input_tensor=True` then the results are:
`(-2501.169189453125, 'давуепооитмеоизуяиьынереоме')`

**Comment by titu1994** [comment]
Can you first use the script as is to make sure you're getting reasonable results, then you can try debugging your code

**Comment by psydok** [comment]
Thanks, it worked! 
I trained a new kenlm on subword, but I didn’t really see any improvement in recognition... In general, it seems that acoustic alone works better than with LM. But this is probably the problem of the set on which I decided to teach.

**Comment by titu1994** [comment]
Probably needs a hyper parameter search. Use the "baseline values" of 0 for alpha and beta to find out what is the "no lm" scores and it should be close to greedy scores. 

Then you'll need deeper hyper param search to find good results with beam search.
