### ISSUE TITLE
LAS dir exists, but no attention-related codes exists

### ISSUE THREAD

**Issue by SweetFov** [NVIDIA/NeMo#488]
Appreciate your great work on this fantastic framework!
I have been using Nemo for several months, and have achieved some results on it;
I've seen "nemo_asr/las" dir exists, but no attention-related codes exists; 
Are you guys have  plans to release some las-related code?
Looking forward to it!

**Comment by okuchaiev** [comment]
We have some experimental work on what we call "GarNet" - e.g. QuartzNet encoder + RNN decoder with attention and sequence loss instead of a CTC loss.
See this example for inspiration: https://github.com/NVIDIA/NeMo/blob/master/examples/asr/experimental/garnet.py .

**Comment by okuchaiev** [comment]
closing this. @SweetFov please re-open if you still have issues
