### ISSUE TITLE
Convert rnnt asr model to tensorrt

### ISSUE THREAD

**Issue by catalwaysright** [NVIDIA/NeMo#4885]
I am working on converting the RNNT model to tensorrt for my application and I have convert the torch model to ONNX as suggested. However, I am stuck on converting ONNX to trt model right now. I tried lots of methods and still failed. Is it possible to convert? Did anyone succeed on converting this model to tensorrt? Which tensorrt version should I use or how can I do the conversion? Any tutorials?

**Comment by titu1994** [comment]
I've never tried tensorrt after the onnx export

**Comment by catalwaysright** [comment]
> 

Then how did you convert the model to onnx? I found that export.py script not feasible.

**Comment by titu1994** [comment]
Export.py should work fine for onnx. It's trt which may not work. There's also the export directory in the examples of asr for RNNT which does inference check with onnx.

**Comment by catalwaysright** [comment]
> 

I don't think the rnnt model have `model.input_module.input_example` that's why I said it is not feasible. How did you run the export.py? like `python export.py ...` what arguments did you use?

**Comment by titu1994** [comment]
Look at the export example in asr section.
