### ISSUE TITLE
Addition of word in Citrinet Model

### ISSUE THREAD

**Issue by sharaddobariya05** [NVIDIA/NeMo#4896]
stt_en_citrinet_512 and stt_en_citrinet_1024 both are trained on large English speech data, is there any way we can add few more words such as name(Example Hanuman or Ganesha), pronunciation of these words might be different depends upon the language , if we have enough speech data to add these words for improvement its transcription accuracy. 

In short, I want to add few more words in dictionary of this model.

**Comment by titu1994** [comment]
Please don't open both an issue and a discussion about the same question.
