### ISSUE TITLE
Evaluation script for VAD models

### ISSUE THREAD

**Issue by entn-at** [NVIDIA/NeMo#4924]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to evaluate the performance of speech/audio classification models (in particular, VAD/SAD models) with different collars, using metrics such as are available in `md-eval.pl` in SCTK (used by Kaldi's SAD recipes) or PyAnnote metrics (see https://github.com/pyannote/pyannote-metrics/blob/develop/pyannote/metrics/detection.py).

**Describe the solution you'd like**

I'd like to have a script that takes a manifest (formatted the same way as for train/validation in speech classification; not necessarily preprocessed to have only short sections) as input and produces error/accuracy metrics. As PyAnnote Metrics is already used elsewhere in NeMo, it could probably easily used for this purpose. Or perhaps there already exist internal/unpublished scripts for that purpose that could be added to NeMo.

**Describe alternatives you've considered**

Creating RTTM output from VAD predictions and evaluating them using SCTK/md-eval.pl.

Also tagging @fayejf

Thanks!

**Comment by nithinraok** [comment]
On top of the predictions made from VAD output manifest, you may use those to write to an RTTM file and use it for evaluation using `md-eval.pl` . For reference look at this section https://github.com/NVIDIA/NeMo/blob/ac093ac70a4c5f5fbfd9ca6941304d83601f1d88/nemo/collections/asr/models/clustering_diarizer.py#L188 . 


I don;t see a benefit to creating a separate script for it, you may do it with a simple function.

**Comment by entn-at** [comment]
OK no problem; however, I should point out that the table output (.txt) files created by NeMo's pipeline are not RTTM files. They are just text files with lines of the following format: "[start_time] [end_time] speech", while RTTM files have a more complex format.
