### ISSUE TITLE
[TTS] Using a "reference" audio clip to control duration when synthesizing audio?

### ISSUE THREAD

**Issue by throwaway30** [NVIDIA/NeMo#4932]
If I have an audio clip, for example the "Tears in rain" monologue from Blade Runner, is there any way to replicate the pacing/duration of that audio when generating a spectrogram for TTS? 

The "Inference_DurationPitchControl" tutorial covers changing the pace of the entire clip by some fixed percentage, but what I actually want is to change the duration of the individual words/phonemes (and the gaps between them) to match their durations in the reference audio.

If this isn't currently available, is it feasible as a future feature?

**Comment by XuesongYang** [comment]
yes, we support the feature with SSML. https://docs.nvidia.com/deeplearning/riva/user-guide/docs/tutorials/tts-python-advanced-customization-with-ssml.html
