### ISSUE TITLE
where is the script_to_bpe.py?

### ISSUE THREAD

**Issue by answer1201** [NVIDIA/NeMo#4938]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/23027105/190307749-802cdf06-8e44-4d0c-b845-9d257159edc7.png">
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/23027105/190307823-d77bd5f8-82c0-4d2f-8e94-e5b598d67338.png">

**Comment by titu1994** [comment]
That's a pretty old file name, but it's basically referring to examples/ASR/asr_ctc/speech _to_text_bpe.py

**Comment by titu1994** [comment]
We'll update the name there
