### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by svj1991** [NVIDIA/NeMo#4941]
I had a question and I was wondering if I could get a bit of help since I'm new to things here.
I noticed that the ASR models have been trained on 16k examples and expect a test example to be at the same sampling rate.

1. I have a higher sampling rate example eg. 24kHz and I downsample it to 16kHz and want to get the encoder outputs. Is there a way to verify the encoder outputs are correct?
One high-level sanity check I can think of is if I could get the frame-level transcriptions on the downsampled 16kHz signal and compare with what I hear in the audio approximately at that point of time.

**Comment by titu1994** [comment]
If you downsanple audio, it will affect the encoder slightly, so your output will not be 1:1 exactly the same.
