### ISSUE TITLE
Scheduler function while fine-tuning ASR

### ISSUE THREAD

**Issue by evilc3** [NVIDIA/NeMo#4943]
While fine-tuning ctc asr model the lr used is in range of 0.025 to 0.001 (according to examples In notebooks). But the scheduler further reduces the lr. 

when I set lr = 0.025 
the max_lr I see after warmup is 1 e -6,  its not 0.025 

so should we only use scheduler while training from scratch and not fine-tuning ?

**Comment by titu1994** [comment]
You can remove the scheduler part of the config in it's entirety. But we normally suggest to start off with 0.001 or lower and then let it go down according to the scheduler anyway.
