### ISSUE TITLE
Simple numbers in Text Normalization

### ISSUE THREAD

**Issue by ihfreitas** [NVIDIA/NeMo#4945]
Hello everyone, 
I'm looking to Text Normalization, Inverse Text Normalization to be more specific, and I saw something "weird".
For simples numbers, like "Um" (equivalent "one") returns "Um" instead "1", should  this be normal?
The ITN normalize with some prefix or suffix, or can inverse normalize numbers in general?

![image](https://user-images.githubusercontent.com/94904861/191030298-0ac5053a-f6fa-4283-8b2a-99e1329c9fe1.png)

**Comment by yzhang123** [comment]
we do not inverse normalize numbers in the single digits to make it more readable

**Comment by LarisaKe** [comment]
"um" in Portuguese means "1" and is a masculine form of the indefinite pronoun. 
The general idea in ITN (Inverse Text Normalization) is to change alphabet form into numerical form; "um' -> "1". 
In a recent ASR meeting, single digits are not converted in general in Mandarin. 
However, we would have to confirm if this is the case in other languages, such as Portuguese or French.

**Comment by LarisaKe** [comment]
I've confirmed with colleagues: single digits are not converted in any language. This also applies to Portuguese.

**Comment by ihfreitas** [comment]
Okay, I got it now. Make sense do it to be more readable.
Thank you for all explanation!!
