### ISSUE TITLE
wandb.init potentially called twice

### ISSUE THREAD

**Issue by borisdayma** [NVIDIA/NeMo#495]
I understand that metrics can be called both through `WandbCallback` (mainly for training data) and `EvaluatorCallback` (for validation data and metrics).

In both callbacks, `wandb.init` is called, which can open a new logging session.

**Suggestion**

* replace any line that has `wandb.init` with `if wandb.run is None: wandb.init(…)`
* in `EvaluatorCallback`, I suggest to use a `or` condition for `if self._wandb_name is not None and self._wandb_project is not None` as these parameters are not always set by user (personal use case)

**Comment by okuchaiev** [comment]
Thanks for suggestions! https://github.com/NVIDIA/NeMo/pull/496

**Comment by okuchaiev** [comment]
merged
