### ISSUE TITLE
if logic error 

### ISSUE THREAD

**Issue by idisuu** [NVIDIA/NeMo#4952]
https://github.com/NVIDIA/NeMo/blob/e856e9732af79a6ed4bffaa3d709bfa387799587/nemo/collections/asr/parts/utils/decoder_timestamps_utils.py#L399

  if 'EncDecCTCModel' in str(type(asr_model)):
      labels = asr_model.decoder.vocabulary
  elif 'EncDecCTCModelBPE' in str(type(asr_model)):
      vocab = asr_model.tokenizer.tokenizer.get_vocab()
      labels = list(vocab.keys())
      labels[0] = "<unk>"

I found that
'EncDecCTCModel' is in 'EncDecCTCModelBPE'

so I think the order should be changed.

**Comment by titu1994** [comment]
@nithinraok could you take a look ?

**Comment by nithinraok** [comment]
Thanks for reporting this. Fix will be merged to r1.12.0 . @tango4j to review https://github.com/NVIDIA/NeMo/pull/4959

**Comment by titu1994** [comment]
He's on vacation right now, maybe ask @fayejf  to take a look.
