### ISSUE TITLE
ValueError: `cfg` must have `tokenizer` config to create a tokenizer !

### ISSUE THREAD

**Issue by answer1201** [NVIDIA/NeMo#4954]
Training or Fine-Tuning an Acoustic Model：
Model fine-tuning is a set of techniques that makes fine adjustments to a pre-existing model using new data, so as to make it adapt to new situations while also retaining its original capabilities.
so I download this  model:speechtotext_zh_cn_conformer.tlt and  modidy the evaluate.yaml on test_ds.labels to the Mandarin then use this api:
!tao speech_to_text_citrinet evaluate \
     -e $SPECS_DIR/speech_to_text_citrinet/evaluate.yaml \
     -g 1 \
     -k $KEY \
     -m $RESULTS_DIR/speechtotext_zh_cn_conformer.tlt \
     -r $RESULTS_DIR/citrinet/evaluate \
     test_ds.manifest_filepath=$DATA_DIR/train.json
but i got this error 
raise ValueError("`cfg` must have `tokenizer` config to create a tokenizer !")
ValueError: `cfg` must have `tokenizer` config to create a tokenizer !

**Comment by titu1994** [comment]
It would probably be better to ask this on the Riva forums. We don't work on TLT so we won't be able to provide a solution maybe. 

From what it looks like, it seems you're trying to do inference of a character based Mandarin model with a Citrinet inference script (which is subword based). You should try to do inference with a character based script
