### ISSUE TITLE
Inference with pretrained "stt_en_conformer_ctc_medium" ASR model crashes in python 3.8.10

### ISSUE THREAD

**Issue by Oscaarjs** [NVIDIA/NeMo#4981]
**Describe the bug**

Inference with the medium model specifically causes an error;
![medium_issue](https://user-images.githubusercontent.com/37636054/191699865-d490f214-6a55-4976-9a77-b2a828f64abe.png)

Works totally fine on the same audio file with the following models;

- stt_en_conformer_ctc_small_ls
- stt_en_conformer_ctc_large
- stt_en_conformer_transducer_large

I've so far only encountered the problem in python 3.8.10. In Google Colab and in Python 3.10.4 it works fine.

**Steps/Code to reproduce bug**

In python 3.8.10, 

installed with;

`nemo_toolkit[all] @ git+https://github.com/NVIDIA/NeMo.git@a4ff215ecc9fafd7127223bc21fd50cf023de592"`

Loaded from local pretrained checkpoint (previously downloaded from NGC)

 
`model = nemo_asr.models.ASRModel.restore_from(restore_path=model_path)`
`model.eval()`
`model.freeze()`
`model.preprocessor.featurizer.dither = 0.0`
`model.preprocessor.featurizer.pad_to = 0`

`decoding_cfg = model.cfg.decoding`
`decoding_cfg.preserve_alignments = True`
`decoding_cfg.compute_timestamps = True`
`model.change_decoding_strategy(decoding_cfg)`
`hypothesis = model.transcribe(paths2audio_files=[audio_path_or_url], return_hypotheses=True)[0]`

**Expected behavior**

Inference should finish without "list index out of range"

**Environment details**

- OS version Ubuntu 20.04
- PyTorch version: 1.12.1
- Python version: 3.8.10

**Comment by titu1994** [comment]
There are a few bug fixes that failed to make it to NeMo 1.11.0, can you try using main branch ?

**Comment by guillermo-gabrielli-fer** [comment]
Same stacktrace with Nemo 1.12.0 for model STT En Conformer-CTC Large, also Python 3.8 (I'm not sure of the exact version atm because I'm using the AWS provided docker image). Timestamp calculation is enabled.

The issue happens for this sample:
[hello.ogg.zip](https://github.com/NVIDIA/NeMo/files/9872973/hello.ogg.zip)

Samples which contain more words like "Hello, how are you?" don't trigger the crash.

**Comment by titu1994** [comment]
There was a very difficult edge case that was triaged when computing timestamps and fixed in r1.12 so that might have fixed it. I don't think the fix finally made it to 1.12, but should make it in 1.13

**Comment by guillermo-gabrielli-fer** [comment]
Thanks for the prompt replyl.
