### ISSUE TITLE
Question about speaker interpolation in Fastpitch

### ISSUE THREAD

**Issue by godspirit00** [NVIDIA/NeMo#5003]
Hi, thanks for the great work!
I saw the recently added speaker interpolation tutorial and decided to have a try.

Sometime ago I followed the `FastPitch_Finetuning.ipynb` tutorial and mixed a small dataset with a big dataset and did the finetuning with `n_speakers=2`. This model can be used to do speaker interpolation, is that right?

The speaker interpolation tutorial says `Choose new_speaker ID such that it is not already assigned to an existing speaker` and in [fastpitch.py](https://github.com/NVIDIA/NeMo/blob/a74f262dbd39aff9d7ec3c12c9322c3a4036a97c/nemo/collections/tts/models/fastpitch.py#L687-691) it says `the new_speaker_id should be less than the total number of speakers`.

So in my case, speaker 0, 1 have been assigned, and `n_speakers=2`. How should I set the `new_speaker` ID?

Thank you!

**Comment by godspirit00** [comment]
Any help please?

**Comment by redoctopus** [comment]
@subhankar-ghosh could you take a look at this?

**Comment by subhankar-ghosh** [comment]
@godspirit00  That is a good question. In the tutorial we assume that there are embeddings which are not used .e.g. speakerIDs = {1,3,5} and if you use `n_speakers=6` then you will have 1,3,5 speaker embeddings trained and 0,2,4 speaker embeddings unused which you can assign to the interpolated speaker.

In your case, however, you can increase the size of the speaker embedding to 3 speaker embeddings and then use the additional (unused) embedding to assign to the interpolated speaker. To do this you can use the following code snippet:

```
old_emb = model.fastpitch.speaker_emb

# Choose random
new_speaker_emb = torch.rand(1, old_emb.embedding_dim)

new_emb = torch.nn.Embedding(old_emb.num_embeddings+1, old_emb.embedding_dim).from_pretrained(
    torch.cat([old_emb.weight.detach().clone(), new_speaker_emb], axis=0), freeze=True)
model.fastpitch.speaker_emb = new_emb
model.cfg.n_speakers += 1
```
Now you have 3 speaker embeddings, so assign the interpolated speaker embedding to the newly added embedding.

**Comment by godspirit00** [comment]
@subhankar-ghosh  I gave it a try and it was successful, thanks!
There's a little problem.
On [L742](https://github.com/NVIDIA/NeMo/blob/44de3950f0bf2f3e85d7df1a962eb24674f4fa4e/nemo/collections/tts/models/fastpitch.py#L742) and [L745](https://github.com/NVIDIA/NeMo/blob/44de3950f0bf2f3e85d7df1a962eb24674f4fa4e/nemo/collections/tts/models/fastpitch.py#L745), the tensors are put on cuda, but if I do inference on a CPU-only setup, these lines will produce errors. I changed the `cuda()` to `to(self.device)` before I was successful in doing the interpolation.
