### ISSUE TITLE
Speech Data Explorer installation instructions are incomplete

### ISSUE THREAD

**Issue by galv** [NVIDIA/NeMo#5008]
**Describe the bug**

Following the instructions here, speech data explorer doesn't work out of the box because some dependencies aren't installed: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/tools/speech_data_explorer.html#getting-started

**Steps/Code to reproduce bug**

Start a new conda environment (I used python 3.8),  then:
```
git clone --recursive https://github.com/NVIDIA/NeMo.git
cd NeMo
pip install -r tools/speech_data_explorer/requirements.txt
python tools/speech_data_explorer/data_explorer.py
```

Gives:

```
Traceback (most recent call last):
  File "tools/speech_data_explorer/data_explorer.py", line 42, in <module>
    from plotly import express as px
  File "/home/dgalvez/scratch/miniconda3/envs/nemo/lib/python3.8/site-packages/plotly/express/__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Plotly express requires pandas to be installed.
```

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

Clearly some of the requirements of speech data explorer are missing. It works after I do `pip install pandas` manually.

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
Ubuntu 18.04
python 3.8

**Comment by okuchaiev** [comment]
@vsl9 any updates on this?
