### ISSUE TITLE
need fastspeech2 customization

### ISSUE THREAD

**Issue by rkrohit14092** [NVIDIA/NeMo#5019]
### Discussed in https://github.com/NVIDIA/NeMo/discussions/5018

<div type='discussions-op-text'>

<sup>Originally posted by **rkrohit14092** September 27, 2022</sup>
How to add additional words in the dictionary of fastspeech2. I want to customize the dictionary as per my use case. 
![image](https://user-images.githubusercontent.com/52836074/192561638-b3c7c51e-3c29-4a86-a926-9e36cc6067c5.png)
</div>

**Comment by redoctopus** [comment]
Please note that FastSpeech2 has been deprecated in recent releases, but in older versions of NeMo the model's `parse()` function takes an optional `additional_word2phones` argument that can be used to add dictionary entries.
