### ISSUE TITLE
Unable to instantiate HuggingFace AUTOTOKENIZER for gpt2 and facebook/bart-base

### ISSUE THREAD

**Issue by vecorro** [NVIDIA/NeMo#5057]
**Describe the bug**

Get errors 
`Unable to instantiate HuggingFace AUTOTOKENIZER `
for both gpt2 and facebook/bart-base

**Steps/Code to reproduce bug**

Trying to run NeMO tutorial from https://github.com/NVIDIA/NeMo/blob/stable/tutorials/nlp/Question_Answering.ipynb

The notebook fails when trying to create trainer and initialize models gpt2 and facebook/bart-base

**Expected behavior**

I expected to bee able to create a trainer properly just like it happened for "bert-base-uncased" which worked well earlier in the same notebook.

**Environment overview (please complete the following information)**

 - Environment location: VMware vSphere VM
 - Method of NeMo install: 
```
conda create --name nemo python==3.8
conda activate nemo
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
pip install nemo_toolkit['all']
```

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version Ubuntu 20.04.5 LTS
- PyTorch version 1.12.1
- Python version 3.8.0
- nemo-toolkit                  1.11.0

**Additional context**

**GPU model V100**

**Comment by okuchaiev** [comment]
can you please paste a full trace?

**Comment by vecorro** [comment]
Found the solution. If I run the following command, I don't get the error:

`!rm -r ~/.cache/huggingface/`

Thanks!

**Comment by munger1985** [comment]
when i ft llama3-70b, same issue, any idea? we definitly not to delete the ~rm -r ~/.cache/huggingface/, it has models we downloaded for 3hours
