### ISSUE TITLE
Logging audio & images during TTS training

### ISSUE THREAD

**Issue by johnpaulbin** [NVIDIA/NeMo#5058]
**Is your feature request related to a problem? Please describe.**

Whenever I'm training, I cannot conclude the exact performance of a TTS model when training, having to manually stop and resume training.

**Describe the solution you'd like**

A simple parameter in the training config to add audio samples & alignment (if possible) into the tensorboard.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by okuchaiev** [comment]
fee free to send a PR with this feature
