### ISSUE TITLE
Apex Not Found. Provided solution does not solve. 

### ISSUE THREAD

**Issue by maxthorpe** [NVIDIA/NeMo#5111]
**The bug**

Megatron GPT training requires NVIDIA Apex to be installed. Token_Classification-BioMegatron.ipynb does not import module and provided solution found through (Error(s): Apex was not found. Please see the NeMo README for installation instructions: https://github.com/NVIDIA/NeMo#megatron-gpt.) does not solve import error. 

**To reproduce bug**

Run script through google colab as presented on Nvidia nemo tutorials or through provided github. Notebook will error out at line 25 when model is initialized. Follow steps listed in error messaging to attempt to correct error. 

**Expected behavior**

Notebook will error out at line 25 when model is initialized and return "Error(s): Apex was not found. Please see the NeMo README for installation instructions: https://github.com/NVIDIA/NeMo#megatron-gpt."

**Environment overview (please complete the following information)**

 - Environment location: Colab
 - Method of NeMo install: 
 !python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[nlp]
from nemo.collections import nlp as nemo_nlp
from nemo.utils.exp_manager import exp_manager
import os
import wget 
import torch
import pytorch_lightning as pl
from omegaconf import OmegaConf

**Environment details**

- OS version: posix
- PyTorch version: 1.12.1+cu113
- Python version: Python 3.7.14

**Additional context**

Standard GPU selection on Colab

**Screen capture after implementing official solution**
![BioMeg_ModuleNotFound_10_2022](https://user-images.githubusercontent.com/107068406/194599521-9837f3f4-3aaa-44c5-ba34-a216ce94c2db.png)

**Comment by ericharper** [comment]
Thanks for the issue. We are currently working to remove Apex as a hard dependency and it will become optional (used for perf improvement). Could you share how you installed Apex in the notebook so we can try to reproduce? Thanks.

**Comment by maxthorpe** [comment]
Apex is initially installed in the following manner: 
```
!git clone https://github.com/ericharper/apex.git
!cd apex
!git checkout nm_v1.11.0
!pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" --global-option="--fast_layer_norm" --global-option="--distributed_adam" --global-option="--deprecated_fused_adam" ./
```
This method typically returns an error:
`ERROR: Directory './' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`
To correct this, `setup.py` has to be moved to working directory. 

After `setup.py` is moved to working dir, installation of apex will return:
`ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-f5m8stkp/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-f5m8stkp/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext --fast_layer_norm --distributed_adam --deprecated_fused_adam install --record /tmp/pip-record-i9s80h03/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/apex Check the logs for full command output.`
* This error is corrected by removing the `--global-option` arguments from the `!pip install` command
* Correcting these errors does not correct original import error from model initialization. 

Please let me know if any additional information needs to be provided to facilitate looking into this.

**Comment by okuchaiev** [comment]
like @ericharper mentioned above we are working on making apex optional requirement. Right now your best bet is to run such notebooks locally (where you'll install apex in your environment before) rather than on Colab

**Comment by RaiAmanRai** [comment]
Hi guys, any update on long this is gonna take to get fixed ?

Thanks.

**Comment by pradeepdev-1995** [comment]
any update on this?
Is apex optional now?
still I am getting this issue
```ImportError: Apex was not found. Please see the NeMo README for installation instructions: https://github.com/NVIDIA/NeMo#megatron-gpt.```

**Comment by hyuuo** [comment]
I also get this

**Comment by Ori-rishu** [comment]
Same issue!!

**Comment by xduzhangjiayu** [comment]
Same issue, anyone solved this?

**Comment by syy-yoyo** [comment]
Same issue, anyone solved this?
ImportError: Apex was not found. Please see the NeMo README for installation instructions: https://github.com/NVIDIA/NeMo#megatron-gpt.
