### ISSUE TITLE
`AutoTokenizer` produces non-invertible tokens

### ISSUE THREAD

**Issue by 1-800-BAD-CODE** [NVIDIA/NeMo#5119]
**Describe the bug**

The wrapper for HF tokenizers misses some key functionality.

**Steps/Code to reproduce bug**

```python
from nemo.collections.nlp.modules.common.tokenizer_utils import get_tokenizer


tokenizer = get_tokenizer(
    tokenizer_name="bert-base-multilingual-cased",
    tokenizer_model="huggingface"
)
# The problem
print(f"{tokenizer.tokenizer.do_basic_tokenize=}")

text = "Knock, knock. Who's there? Interrupting cow. Interrupting cow wMOOOOOOOOOOOOOOO"

print(tokenizer.ids_to_text(tokenizer.text_to_ids(text)))
```

Output:

```
Knock , knock . Who ' s there ? Interrupting cow . Interrupting cow wMOOOOOOOOOOOOOOO
```

**Expected behavior**
Expected that for some tokenizer, `ids_to_text(text_to_ids) == text`.

We can accomplish this if we reach under NeMo's wrapper:

```python
print(tokenizer.tokenizer.decode(tokenizer.text_to_ids(text)))
```

Output:

```
Knock, knock. Who's there? Interrupting cow. Interrupting cow wMOOOOOOOOOOOOOOO
```

**Comment by okuchaiev** [comment]
looks like expected behaivor because decoder ! = ids_to_text(text_to_ids(.)). @MaximumEntropy am I right?

**Comment by MaximumEntropy** [comment]
I think it should actually result in the same thing, but it doesn't for some reason (i.e.) `ids_to_text(text_to_ids(x)) should always == x` like @1-800-BAD-CODE is suggesting. For example, sentencepiece has always satisfied this property in my experience. 

@1-800-BAD-CODE, Some of the artifacts go away if you instantiate `get_tokenizer()` with `use_fast=True`. In your example, if I do the following and remove your call to `do_basic_tokenize`

```
tokenizer = get_tokenizer(
    tokenizer_name="bert-base-multilingual-cased",
    tokenizer_model="huggingface",
    use_fast=True
)
```

I get the expected result - 

```
Knock, knock. Who's there? Interrupting cow. Interrupting cow wMOOOOOOOOOOOOOOO
```

Which is the output you expect

However, there are still sentences that do not detokenize properly. Especially those with hyphens.

ex:

Input:
```
Knock-knock. Who's there? Interrupting-cow. Interrupting cow wMOOOOOOOOOOOOOOO
```

Output:
```
Knock - knock. Who's there? Interrupting - cow. Interrupting cow wMOOOOOOOOOOOOOOO
```

Also another thing I've noticed is that this seems to be specific to the BERT tokenizer, if you try the same thing with the  HF pre-trained GPT2 tokenizer with `use_fast=False` or True, it doesn't seem to happen.

If you know what might be going on here or if we are doing something wrong with the way we are calling HF tokenizers, please let us know!

cc: @titu1994 , @VahidooX FYI in case you are using HF pre-trained BERT tokenizers.

**Comment by titu1994** [comment]
HF Tokenizers have always had this problem which is why we explicitly switched to Sentencepiece which doesn't have this issue. I'd recommend not using that Tokenizer if possible.
