### ISSUE TITLE
Failed to run ONNX squeezeformer

### ISSUE THREAD

**Issue by Theodotus1243** [NVIDIA/NeMo#5129]
**Describe the bug**

Squeezeformer model succesfuly exported
But after running on Squeezeformer.encoder.input_example t producess dimmentions mismatch error 

**Steps/Code to reproduce bug**

```
python
import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecCTCModelBPE.from_pretrained(model_name="stt_en_squeezeformer_ctc_xsmall_ls", map_location="cpu")
asr_model.export("squeezeformer.onnx", onnx_opset_version=15)

import onnxruntime as ort
ort_sess = ort.InferenceSession('squeezeformer.onnx')

processed_signal, processed_signal_len = asr_model.encoder.input_example()
outputs = ort_sess.run(None, {'audio_signal': processed_signal.numpy(),
                              'length':processed_signal_len.numpy()})
```

**Error**
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running MatMul node. Name:'MatMul_3906' Status Message: matmul_helper.h:61 Compute MatMul dimension mismatch
```
**Environment details**

nemo_toolkit - 1.12.0rc0

**Comment by titu1994** [comment]
Squeezeformer is not currently supported for export. Not all models are made to support export mode, though we may eventually make them export compatible

**Comment by titu1994** [comment]
So after this issue was closed, i tried to figure out whats up with ONNX. Turns out its weird, even conformer has this issue. 
This PR will enable export of squeezeformer to Torchscript at least - https://github.com/NVIDIA/NeMo/pull/5164

**Comment by Theodotus1243** [comment]
Maybe [this](https://github.com/k2-fsa/icefall/pull/778) may help 
There zipformer support added
