### ISSUE TITLE
checkpoint_dir with checkpoint manager is not being set corrector while resuming training

### ISSUE THREAD

**Issue by daniel-kukiela** [NVIDIA/NeMo#5136]
**Describe the bug**

When I stopped fine-tuning the FastPitch model and wanted to restart training, I noticed it checks for the last checkpoint in the wrong directory (I'm settings the checkpoints directory outside of the logs).
So, in my case the checkpoints are being saved at `models/fastpitch/checkpoints` but it is trying to search in `models/fastpitch/logs/checkpoints`.
This is due to the hard-coded path value here: https://github.com/NVIDIA/NeMo/blob/main/nemo/utils/exp_manager.py#L424, so inside `check_resume()`:
```py
    checkpoint_dir = Path(Path(log_dir) / "checkpoints")
```
While the correct path is being set here: https://github.com/NVIDIA/NeMo/blob/main/nemo/utils/exp_manager.py#L889, so inside `configure_checkpointing()`:
```py
    if params.dirpath is None:
        params.dirpath = Path(log_dir / 'checkpoints')
```
it correctly checks if `dirpath` is set (it is in my case) and only otherwise defaults to the `checkpoints` folder inside of the `logs` folder.

I did not fill in the rest of the template of the bug report as this is a question about a specific code piece, not related to any hardware or scenario.

**Comment by redoctopus** [comment]
Sorry, I'm not exactly sure what you're asking, but if you're having trouble with the `exp_manager` finding the correct directory for checkpoints, can you try adding `+exp_manager.explicit_log_dir=<your_log_path>`? This should ensure that the two runs will always use the same directory.

The two code snippets should give the same result assuming `log_dir` is consistent between them.

**Comment by daniel-kukiela** [comment]
What I mean is you can use `exp_manager.checkpoint_callback_params.dirpath` to set a checkpoint folder and it can be any path, not necessarily `checkpoints` inside of `logs`. If you use this parameter, then (https://github.com/NVIDIA/NeMo/blob/main/nemo/utils/exp_manager.py#L424):
```py
    if params.dirpath is None:
        params.dirpath = Path(log_dir / 'checkpoints')
```
so the basove code inside of the if statement is not being executed and the set paths is being used instead. Checkpoints indeed save in this directory of my choice. However, when I want to resume training, the checkpoint path (dirpath) set in exp_manager is ignored and a hardcoded one is used instead (https://github.com/NVIDIA/NeMo/blob/main/nemo/utils/exp_manager.py#L424):
```py
    checkpoint_dir = Path(Path(log_dir) / "checkpoints")
```
there's no code that uses `dirpath`, so, in other words, training restart ignores `dirpath` and uses a hardcoded patch, thus is unable to find the last saved checkpoint.

Please let me know if this describe the issue better.

**Comment by redoctopus** [comment]
Ahh, gotcha. I'm able to reproduce this, will work on fixing this today.

**Comment by daniel-kukiela** [comment]
Thank you!

**Comment by redoctopus** [comment]
PR merged, should be fixed now!
