### ISSUE TITLE
Nemo on Jetson Xavier NX 5.0.2

### ISSUE THREAD

**Issue by UserName-wang** [NVIDIA/NeMo#5146]
Sorry I have to reopen a issue related to Jetson Xavier, I found several issues reported in the passed two years. but didn't helped me to solve the problem. Hope there still some friends playing with new version 5.0.2.

**Describe the bug**
before install Nemo , I installed: torch-1.12.0a0+2c916ef.nv22.3-cp38-cp38-linux_aarch64.whl, which downloaded from https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048.

During installation from source: ./reinstall.sh:
ERROR: tensorboard 2.10.1 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 4.21.7 which is incompatible.
ERROR: onnx 1.12.0 has requirement protobuf<=3.20.1,>=3.12.2, but you'll have protobuf 4.21.7 which is incompatible.
which version I should use?

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**
package version information:

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: nemo_toolkit[asr] in ./NeMo (1.13.0rc0)
Requirement already satisfied: setuptools==59.5.0 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (59.5.0)
Requirement already satisfied: numpy>=1.21 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.23.3)
Requirement already satisfied: onnx>=1.7.0 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.11.0)
Requirement already satisfied: python-dateutil in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (2.8.2)
Requirement already satisfied: torch in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.12.0a0+2c916ef.nv22.3)
Requirement already satisfied: wrapt in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.14.1)
Requirement already satisfied: ruamel.yaml in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.17.21)
Requirement already satisfied: scikit-learn in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.1.2)
Requirement already satisfied: tqdm>=4.41.0 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (4.64.1)
Requirement already satisfied: numba in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.56.2)
Requirement already satisfied: wget in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (3.2)
Requirement already satisfied: text-unidecode in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.3)
Requirement already satisfied: huggingface_hub in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.10.1)
Requirement already satisfied: braceexpand in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.1.7)
Requirement already satisfied: editdistance in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.6.0)
Requirement already satisfied: inflect in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (6.0.0)
Requirement already satisfied: librosa>=0.9.0 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.9.2)
Requirement already satisfied: marshmallow in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (3.18.0)
Requirement already satisfied: packaging in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (21.3)
Requirement already satisfied: soundfile in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.11.0)
Requirement already satisfied: sox in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.4.1)
Requirement already satisfied: kaldi-python-io in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.2.2)
Requirement already satisfied: kaldiio in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (2.17.2)
Requirement already satisfied: scipy>=0.14 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.9.2)
Requirement already satisfied: g2p_en in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (2.1.0)
Requirement already satisfied: pydub in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.25.1)
Requirement already satisfied: pyannote.core in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (4.5)
Requirement already satisfied: pyannote.metrics in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (3.2.1)
Requirement already satisfied: ipywidgets in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (8.0.2)
Requirement already satisfied: matplotlib in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (3.6.1)
Requirement already satisfied: texterrors in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.4.4)
Requirement already satisfied: pytorch-lightning>=1.7.0 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.7.7)
Requirement already satisfied: torchmetrics>=0.4.1rc0 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.10.0)
Requirement already satisfied: transformers>=4.0.1 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (4.23.1)
Requirement already satisfied: webdataset<=0.1.62,>=0.1.48 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.1.62)
Requirement already satisfied: omegaconf<2.2,>=2.1.2 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (2.1.2)
Requirement already satisfied: hydra-core<1.2,>=1.1.0 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.1.2)
Requirement already satisfied: pyyaml<6 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (5.4.1)
Requirement already satisfied: wandb in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.13.4)
Requirement already satisfied: sentencepiece<1.0.0 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.1.97)
Requirement already satisfied: youtokentome>=1.0.5 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.0.6)
Requirement already satisfied: pandas in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (1.5.0)
Requirement already satisfied: sacremoses>=0.0.43 in ./.nemo/lib/python3.8/site-packages (from nemo_toolkit[asr]) (0.0.53)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./.nemo/lib/python3.8/site-packages (from onnx>=1.7.0->nemo_toolkit[asr]) (4.4.0)
Requirement already satisfied: protobuf>=3.12.2 in ./.nemo/lib/python3.8/site-packages (from onnx>=1.7.0->nemo_toolkit[asr]) (3.19.6)
Requirement already satisfied: six>=1.5 in ./.nemo/lib/python3.8/site-packages (from python-dateutil->nemo_toolkit[asr]) (1.16.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6; platform_python_implementation == "CPython" and python_version < "3.11" in ./.nemo/lib/python3.8/site-packages (from ruamel.yaml->nemo_toolkit[asr]) (0.2.6)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.nemo/lib/python3.8/site-packages (from scikit-learn->nemo_toolkit[asr]) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in ./.nemo/lib/python3.8/site-packages (from scikit-learn->nemo_toolkit[asr]) (1.2.0)
Requirement already satisfied: importlib-metadata; python_version < "3.9" in ./.nemo/lib/python3.8/site-packages (from numba->nemo_toolkit[asr]) (5.0.0)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in ./.nemo/lib/python3.8/site-packages (from numba->nemo_toolkit[asr]) (0.39.1)
Requirement already satisfied: filelock in ./.nemo/lib/python3.8/site-packages (from huggingface_hub->nemo_toolkit[asr]) (3.8.0)
Requirement already satisfied: requests in ./.nemo/lib/python3.8/site-packages (from huggingface_hub->nemo_toolkit[asr]) (2.28.1)
Requirement already satisfied: pydantic in ./.nemo/lib/python3.8/site-packages (from inflect->nemo_toolkit[asr]) (1.10.2)
Requirement already satisfied: pooch>=1.0 in ./.nemo/lib/python3.8/site-packages (from librosa>=0.9.0->nemo_toolkit[asr]) (1.6.0)
Requirement already satisfied: audioread>=2.1.9 in ./.nemo/lib/python3.8/site-packages (from librosa>=0.9.0->nemo_toolkit[asr]) (3.0.0)
Requirement already satisfied: resampy>=0.2.2 in ./.nemo/lib/python3.8/site-packages (from librosa>=0.9.0->nemo_toolkit[asr]) (0.4.2)
Requirement already satisfied: decorator>=4.0.10 in ./.nemo/lib/python3.8/site-packages (from librosa>=0.9.0->nemo_toolkit[asr]) (5.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.nemo/lib/python3.8/site-packages (from packaging->nemo_toolkit[asr]) (3.0.9)
Requirement already satisfied: cffi>=1.0 in ./.nemo/lib/python3.8/site-packages (from soundfile->nemo_toolkit[asr]) (1.15.1)
Requirement already satisfied: nltk>=3.2.4 in ./.nemo/lib/python3.8/site-packages (from g2p_en->nemo_toolkit[asr]) (3.7)
Requirement already satisfied: distance>=0.1.3 in ./.nemo/lib/python3.8/site-packages (from g2p_en->nemo_toolkit[asr]) (0.1.3)
Requirement already satisfied: simplejson>=3.8.1 in ./.nemo/lib/python3.8/site-packages (from pyannote.core->nemo_toolkit[asr]) (3.17.6)
Requirement already satisfied: sortedcontainers>=2.0.4 in ./.nemo/lib/python3.8/site-packages (from pyannote.core->nemo_toolkit[asr]) (2.4.0)
Requirement already satisfied: pyannote.database>=4.0.1 in ./.nemo/lib/python3.8/site-packages (from pyannote.metrics->nemo_toolkit[asr]) (4.1.3)
Requirement already satisfied: tabulate>=0.7.7 in ./.nemo/lib/python3.8/site-packages (from pyannote.metrics->nemo_toolkit[asr]) (0.9.0)
Requirement already satisfied: sympy>=1.1 in ./.nemo/lib/python3.8/site-packages (from pyannote.metrics->nemo_toolkit[asr]) (1.11.1)
Requirement already satisfied: docopt>=0.6.2 in ./.nemo/lib/python3.8/site-packages (from pyannote.metrics->nemo_toolkit[asr]) (0.6.2)
Requirement already satisfied: traitlets>=4.3.1 in ./.nemo/lib/python3.8/site-packages (from ipywidgets->nemo_toolkit[asr]) (5.4.0)
Requirement already satisfied: jupyterlab-widgets~=3.0 in ./.nemo/lib/python3.8/site-packages (from ipywidgets->nemo_toolkit[asr]) (3.0.3)
Requirement already satisfied: ipython>=6.1.0 in ./.nemo/lib/python3.8/site-packages (from ipywidgets->nemo_toolkit[asr]) (8.5.0)
Requirement already satisfied: widgetsnbextension~=4.0 in ./.nemo/lib/python3.8/site-packages (from ipywidgets->nemo_toolkit[asr]) (4.0.3)
Requirement already satisfied: ipykernel>=4.5.1 in ./.nemo/lib/python3.8/site-packages (from ipywidgets->nemo_toolkit[asr]) (6.16.0)
Requirement already satisfied: contourpy>=1.0.1 in ./.nemo/lib/python3.8/site-packages (from matplotlib->nemo_toolkit[asr]) (1.0.5)
Requirement already satisfied: cycler>=0.10 in ./.nemo/lib/python3.8/site-packages (from matplotlib->nemo_toolkit[asr]) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./.nemo/lib/python3.8/site-packages (from matplotlib->nemo_toolkit[asr]) (4.37.4)
Requirement already satisfied: pillow>=6.2.0 in ./.nemo/lib/python3.8/site-packages (from matplotlib->nemo_toolkit[asr]) (9.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.nemo/lib/python3.8/site-packages (from matplotlib->nemo_toolkit[asr]) (1.4.4)
Requirement already satisfied: loguru in ./.nemo/lib/python3.8/site-packages (from texterrors->nemo_toolkit[asr]) (0.6.0)
Requirement already satisfied: regex in ./.nemo/lib/python3.8/site-packages (from texterrors->nemo_toolkit[asr]) (2022.9.13)
Requirement already satisfied: pybind11 in ./.nemo/lib/python3.8/site-packages (from texterrors->nemo_toolkit[asr]) (2.10.0)
Requirement already satisfied: termcolor in ./.nemo/lib/python3.8/site-packages (from texterrors->nemo_toolkit[asr]) (2.0.1)
Requirement already satisfied: plac in ./.nemo/lib/python3.8/site-packages (from texterrors->nemo_toolkit[asr]) (1.3.5)
Requirement already satisfied: Levenshtein in ./.nemo/lib/python3.8/site-packages (from texterrors->nemo_toolkit[asr]) (0.20.5)
Requirement already satisfied: fsspec[http]!=2021.06.0,>=2021.05.0 in ./.nemo/lib/python3.8/site-packages (from pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (2022.8.2)
Requirement already satisfied: tensorboard>=2.9.1 in ./.nemo/lib/python3.8/site-packages (from pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (2.9.1)
Requirement already satisfied: pyDeprecate>=0.3.1 in ./.nemo/lib/python3.8/site-packages (from pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (0.3.2)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in ./.nemo/lib/python3.8/site-packages (from transformers>=4.0.1->nemo_toolkit[asr]) (0.13.1)
Requirement already satisfied: antlr4-python3-runtime==4.8 in ./.nemo/lib/python3.8/site-packages (from omegaconf<2.2,>=2.1.2->nemo_toolkit[asr]) (4.8)
Requirement already satisfied: importlib-resources<5.3; python_version < "3.9" in ./.nemo/lib/python3.8/site-packages (from hydra-core<1.2,>=1.1.0->nemo_toolkit[asr]) (5.2.3)
Requirement already satisfied: Click!=8.0.0,>=7.0 in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (8.0.2)
Requirement already satisfied: pathtools in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (0.1.2)
Requirement already satisfied: psutil>=5.0.0 in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (5.9.2)
Requirement already satisfied: docker-pycreds>=0.4.0 in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (0.4.0)
Requirement already satisfied: shortuuid>=0.5.0 in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (1.0.9)
Requirement already satisfied: promise<3,>=2.0 in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (2.3)
Requirement already satisfied: setproctitle in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (1.3.2)
Requirement already satisfied: GitPython>=1.0.0 in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (3.1.29)
Requirement already satisfied: sentry-sdk>=1.0.0 in ./.nemo/lib/python3.8/site-packages (from wandb->nemo_toolkit[asr]) (1.9.10)
Requirement already satisfied: pytz>=2020.1 in ./.nemo/lib/python3.8/site-packages (from pandas->nemo_toolkit[asr]) (2022.4)
Requirement already satisfied: zipp>=0.5 in ./.nemo/lib/python3.8/site-packages (from importlib-metadata; python_version < "3.9"->numba->nemo_toolkit[asr]) (3.9.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.nemo/lib/python3.8/site-packages (from requests->huggingface_hub->nemo_toolkit[asr]) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in ./.nemo/lib/python3.8/site-packages (from requests->huggingface_hub->nemo_toolkit[asr]) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./.nemo/lib/python3.8/site-packages (from requests->huggingface_hub->nemo_toolkit[asr]) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.nemo/lib/python3.8/site-packages (from requests->huggingface_hub->nemo_toolkit[asr]) (1.26.12)
Requirement already satisfied: appdirs>=1.3.0 in ./.nemo/lib/python3.8/site-packages (from pooch>=1.0->librosa>=0.9.0->nemo_toolkit[asr]) (1.4.4)
Requirement already satisfied: pycparser in ./.nemo/lib/python3.8/site-packages (from cffi>=1.0->soundfile->nemo_toolkit[asr]) (2.21)
Requirement already satisfied: typer[all]>=0.2.1 in ./.nemo/lib/python3.8/site-packages (from pyannote.database>=4.0.1->pyannote.metrics->nemo_toolkit[asr]) (0.6.1)
Requirement already satisfied: mpmath>=0.19 in ./.nemo/lib/python3.8/site-packages (from sympy>=1.1->pyannote.metrics->nemo_toolkit[asr]) (1.2.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>3.0.1 in ./.nemo/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (3.0.31)
Requirement already satisfied: backcall in ./.nemo/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.2.0)
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in ./.nemo/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (4.8.0)
Requirement already satisfied: stack-data in ./.nemo/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.5.1)
Requirement already satisfied: matplotlib-inline in ./.nemo/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.1.6)
Requirement already satisfied: pickleshare in ./.nemo/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.7.5)
Requirement already satisfied: jedi>=0.16 in ./.nemo/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.18.1)
Requirement already satisfied: pygments>=2.4.0 in ./.nemo/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (2.13.0)
Requirement already satisfied: nest-asyncio in ./.nemo/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets->nemo_toolkit[asr]) (1.5.6)
Requirement already satisfied: pyzmq>=17 in ./.nemo/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets->nemo_toolkit[asr]) (24.0.1)
Requirement already satisfied: debugpy>=1.0 in ./.nemo/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets->nemo_toolkit[asr]) (1.6.3)
Requirement already satisfied: jupyter-client>=6.1.12 in ./.nemo/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets->nemo_toolkit[asr]) (7.4.2)
Requirement already satisfied: tornado>=6.1 in ./.nemo/lib/python3.8/site-packages (from ipykernel>=4.5.1->ipywidgets->nemo_toolkit[asr]) (6.2)
Requirement already satisfied: rapidfuzz<3.0.0,>=2.3.0 in ./.nemo/lib/python3.8/site-packages (from Levenshtein->texterrors->nemo_toolkit[asr]) (2.11.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1; extra == "http" in ./.nemo/lib/python3.8/site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (3.8.3)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (0.6.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (2.12.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (0.4.6)
Requirement already satisfied: wheel>=0.26 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (0.37.1)
Requirement already satisfied: absl-py>=0.4 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (1.2.0)
Requirement already satisfied: grpcio>=1.24.3 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (1.49.1)
Requirement already satisfied: werkzeug>=1.0.1 in ./.nemo/lib/python3.8/site-packages (from tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (2.2.2)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.nemo/lib/python3.8/site-packages (from GitPython>=1.0.0->wandb->nemo_toolkit[asr]) (4.0.9)
Requirement already satisfied: rich<13.0.0,>=10.11.0; extra == "all" in ./.nemo/lib/python3.8/site-packages (from typer[all]>=0.2.1->pyannote.database>=4.0.1->pyannote.metrics->nemo_toolkit[asr]) (12.6.0)
Requirement already satisfied: colorama<0.5.0,>=0.4.3; extra == "all" in ./.nemo/lib/python3.8/site-packages (from typer[all]>=0.2.1->pyannote.database>=4.0.1->pyannote.metrics->nemo_toolkit[asr]) (0.4.5)
Requirement already satisfied: shellingham<2.0.0,>=1.3.0; extra == "all" in ./.nemo/lib/python3.8/site-packages (from typer[all]>=0.2.1->pyannote.database>=4.0.1->pyannote.metrics->nemo_toolkit[asr]) (1.5.0)
Requirement already satisfied: wcwidth in ./.nemo/lib/python3.8/site-packages (from prompt-toolkit<3.1.0,>3.0.1->ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.2.5)
Requirement already satisfied: ptyprocess>=0.5 in ./.nemo/lib/python3.8/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.7.0)
Requirement already satisfied: pure-eval in ./.nemo/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.2.2)
Requirement already satisfied: executing in ./.nemo/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (1.1.1)
Requirement already satisfied: asttokens in ./.nemo/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (2.0.8)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./.nemo/lib/python3.8/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets->nemo_toolkit[asr]) (0.8.3)
Requirement already satisfied: jupyter-core>=4.9.2 in ./.nemo/lib/python3.8/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->nemo_toolkit[asr]) (4.11.1)
Requirement already satisfied: entrypoints in ./.nemo/lib/python3.8/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->nemo_toolkit[asr]) (0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.nemo/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1; extra == "http"->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (6.0.2)
Requirement already satisfied: attrs>=17.3.0 in ./.nemo/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1; extra == "http"->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (22.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.nemo/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1; extra == "http"->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (1.8.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.nemo/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1; extra == "http"->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (4.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./.nemo/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1; extra == "http"->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (1.3.1)
Requirement already satisfied: aiosignal>=1.1.2 in ./.nemo/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1; extra == "http"->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (1.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.nemo/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in ./.nemo/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (5.2.0)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.6" in ./.nemo/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./.nemo/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.1.1 in ./.nemo/lib/python3.8/site-packages (from werkzeug>=1.0.1->tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (2.1.1)
Requirement already satisfied: smmap<6,>=3.0.1 in ./.nemo/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb->nemo_toolkit[asr]) (5.0.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in ./.nemo/lib/python3.8/site-packages (from rich<13.0.0,>=10.11.0; extra == "all"->typer[all]>=0.2.1->pyannote.database>=4.0.1->pyannote.metrics->nemo_toolkit[asr]) (0.9.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./.nemo/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in ./.nemo/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->pytorch-lightning>=1.7.0->nemo_toolkit[asr]) (3.2.1)
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by titu1994** [comment]
Nemo is primarily meant for training deep learning models, and so we don't support Jetson Xavier. There are too many libraries that are incompatible with it. Fyi @okuchaiev

**Comment by UserName-wang** [comment]
Ok, good to know! So that I will not wast my time for this.
Thank you!
