### ISSUE TITLE
How to limit the diarization in a long audio file?

### ISSUE THREAD

**Issue by Sasha-Bachynskyi** [NVIDIA/NeMo#5148]
Hello, developers!
I've got an issue and was wondering if you could help me.

My goal: reducing the time of diarization if an audio file is longer than 10 minutes.

My manifest json file:
> 'audio_filepath': /home/audio_file.wav,
> 'offset': 0,
> 'duration': 600,
> 'label': 'infer',
> 'text': '-',
> 'num_speakers': 2,
> 'rttm_filepath': None,
> 'uem_filepath': None

I tried to set up 'offset' and 'duration' in the manifest file, but it didn't work properly and It still diarized the whole audio file

Is there a possibility to limit the diarization?

I'll appreciate any help

**Comment by tango4j** [comment]
Currently, the offset and duration in the manifest file is only for ASR, not for diarization. So you need to trim the audio file to limit the diarization range. This should be a feature request rather than a bug label.
