### ISSUE TITLE
POSIX portable filename character set violation in NeMo repo

### ISSUE THREAD

**Issue by fparkins** [NVIDIA/NeMo#5163]
**Describe the bug**

Error while downloading and uploading files

With use of an Object store with S3 services, errors are thrown due to file naming conventions that do not adhere to the POSIX filename character set. The example below shows two filenames that are causing and error with container persistence on the Object Store. The “(“ and the “)” characters are the cause of the error but a comprehensive search of the repo file names would be necessary in order to find all of the potential issues.

**Expected behavior**

File should be uploaded or downloaded from Object Storage without an issues

Filenames should only contain the characters of the POSIX portable file name character set outlined below.
              Uppercase A to Z.
              Lowercase a to z.
              Numbers 0 to 9.
              Period ( . )
              Underscore (_)
              Hyphen (-)

**Environment overview (please complete the following information)**

Object Storage with S3 services

**Environment details**

**Additional context**
5405 | 5h 1m 38s | Uploading: NeMo/tutorials/text_processing/Text_(Inverse)_Normalization.ipynb
5406 | 5h 1m 38s | Error while downloading file: '/NeMo/tutorials/text_processing/Text_(Inverse)_Normalization.ipynb'
5407 | 5h 1m 38s | Error while downloading file: '/NeMo/tutorials/nlp/Non_English_Downstream_Tasks_(NER).ipynb'

**Comment by titu1994** [comment]
@ekmb @yzhang123
