### ISSUE TITLE
[Speaker Diarization + ASR] Is NeMo Speaker Diarization + ASR task using an End-to-End model?

### ISSUE THREAD

**Issue by triumph9989** [NVIDIA/NeMo#5166]
Recently, I demonstrated NeMo's Speaker Diarization + ASR task (nemo/examples/speaker_tasks/diarization/offline_diarization_with_asr.py) to my Professor, but he asked me if that end-to-end? 
According to his question, I assume he means NeMo Speaker Diarization + ASR task not using an End-to-End model.
Is that correct? if that is, he hopes I manifest NeMo's Speaker Diarization + ASR task to an End-to-End model, that is SAD, Speaker embedding model, ASR model should be mixed into one model.
Sorry about my stupid question..

**Comment by titu1994** [comment]
As far as I know, the current SD + ASR pipeline is not end to end.
