### ISSUE TITLE
question about code meaning

### ISSUE THREAD

**Issue by kli017** [NVIDIA/NeMo#5168]
hello I am confusing about some code in the ITN en cardinal.py
from line 113 to 114:
```
labels_exception = [num_to_word(x) for x in range(0, 13)]
graph_exception = pynini.union(*labels_exception)
```
Anyone can help？Thanks a lot

**Comment by ekmb** [comment]
This is done to remove numbers up until 13 from being converted.

**Comment by kli017** [comment]
Thanks for the help. what about line 122 `self.graph_no_exception = graph`. I did not see it used by other code, is it redunent? or used while creating the fst

**Comment by ekmb** [comment]
This is used in other classes where all numbers without any exceptions should be converted.
