### ISSUE TITLE
ONNX export renames 2D parameters, not 1D parameters

### ISSUE THREAD

**Issue by Numeri** [NVIDIA/NeMo#5178]
**Describe the bug**

Exported ONNX graphs retain the names for zero dimensional and one dimensional parameters, but rename any two or more dimensional parameters. This makes writing scripts for later graph manipulation much more tedious and prone to breaking.

**Steps/Code to reproduce bug**

```python3
from nemo.collections.nlp.models.machine_translation import MTEncDecModel

model = MTEncDecModel.from_pretrained('nmt_en_de_transformer12x2')
model.decoder.export('pretrained_decoder.onnx')
```

Open `pretrained_decoder.onnx` in [Netron](https://netron.app/) or some other ONNX graph visualizer. Find and compare the inputs to the nodes `MatMul_106` and `Add_107`.
 - `Add_107` takes 1D tensors as input, and has preserved the name of the parameters from the NeMo model. Its first input is `_decoder.layers.0.first_sub_layer.query_net.bias`.
 - `MatMul_106` requires a 2D tensor as input, and has renamed the parameter from the NeMo model from the quite helpful `_decoder.layers.0.first_sub_layer.query_net.weight` to the generic `onnx::MatMul_636`.

**Expected behavior**

I'd love for it to respect the names of all parameters, which would create a predictable and reliable ONNX graph that can then be further post-processed as needed.

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal
 - Method of NeMo install: `python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[nlp]` (run today, commit d933ee830d085152fbe07a8fa2b1fa0e493adf0d)

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- PyTorch version: 1.12.1
- Python version: 3.9.0

**Comment by Numeri** [comment]
Some extra details that I've realized:

-  This doesn't occur with all 2D parameters: `_embedding.token_embedding.weight` is preserved, for instance, despite being a `(32000, 1024)` tensor. It does occur to most, however.
-  This might be caused by constant folding: When I call the export function with `do_constant_folding=False`, the parameters are not renamed (although the graph is different, now, of course, because constants were not folded in)

**Comment by borisfom** [comment]
Those are the internals of Pytorch ONNX exporter. I doubt they can offer any guarantees with that - but you can try filing an issue with Pytorch.
