### ISSUE TITLE
Error encountered when trying to fine-tune STT Zh Quartznet15x5 on accented dataset.

### ISSUE THREAD

**Issue by haaddii** [NVIDIA/NeMo#5185]
**Describe the bug**

```bash
# When loading model
Model stt_zh_quartznet15x5 was not found. Check cls.list_available_models() for the list of all available models.
```

```bash
# When directly trying transcribing
Error executing job with overrides: ['pretrained_name=stt_zh_quartznet15x5', 'audio_dir=****']
Traceback (most recent call last):
  File "examples/asr/transcribe_speech.py", line 155, in main
    asr_model = ASRModel.from_pretrained(
  File "/****/NeMo/nemo/core/classes/common.py", line 846, in from_pretrained
    class_, nemo_model_file_in_cache = cls._get_ngc_pretrained_model_info(
  File "/****/NeMo/nemo/core/classes/common.py", line 898, in _get_ngc_pretrained_model_info
    raise FileNotFoundError(
FileNotFoundError: Model stt_zh_quartznet15x5 was not found. Check cls.list_available_models() for the list of all available models.
```

**Steps/Code to reproduce bug**

1. follow the steps to run the model in its [HP](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_zh_quartznet15x5)

**Expected behavior**

Should works fine?

**Environment overview (please complete the following information)**

 - Environment location: Baremetal
 - Method of NeMo install: pip from source (Pull from GitHub following the instructions)

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version Ubuntu 18 cuda 11.3 cudnn8.3.2_0
- PyTorch version 1.12.1
- Python version 3.8

**Additional context**

GPU model: 3090

**Comment by titu1994** [comment]
That model is deprecated. You can try the following - https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_zh_citrinet_1024_gamma_0_25 or https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_zh_conformer_transducer_large

**Comment by haaddii** [comment]
> That model is deprecated. You can try the following - https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_zh_citrinet_1024_gamma_0_25 or https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_zh_conformer_transducer_large

Thanks a lot. BTW, may I ask a question about how to use the `cls.list_available_models()` to check if model is available?
(since I also can't make the `nemo_asr.model.EncDecCTCModel.list_available_models()` line in the tutorial work.)

**Comment by titu1994** [comment]
> since I also can't make the nemo_asr.model.EncDecCTCModel.list_available_models()

This should work fine? What error are you getting ?

**Comment by haaddii** [comment]
using:
```python
import nemo.collections.asr as nemo_asr
nemo_asr.model.EncDecCTCModel.list_available_models()
```

I get:
```bash
module 'nemo.collections.asr' has no attribute 'list_available_models'
```

**Comment by titu1994** [comment]
That's odd. One thing might be it "nemo_asr.models.EncDecCTCModel.list_available_models()" - yours is ...model...

**Comment by titu1994** [comment]
Another way would be to look at the source of the docs - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/api.html?highlight=List_available#nemo.collections.asr.models.EncDecCTCModel.list_available_models 

Which highlights the pretrained models https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/_modules/nemo/collections/asr/models/ctc_models.html#EncDecCTCModel.list_available_models

**Comment by haaddii** [comment]
> Another way would be to look at the source of the docs - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/api.html?highlight=List_available#nemo.collections.asr.models.EncDecCTCModel.list_available_models
> 
> Which highlights the pretrained models https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/_modules/nemo/collections/asr/models/ctc_models.html#EncDecCTCModel.list_available_models

Thank you so much, I would check it out.
