### ISSUE TITLE
Decoding hangs with pretrained models when runing transcible_speech script

### ISSUE THREAD

**Issue by duckyngo** [NVIDIA/NeMo#5207]
**Describe the bug**
The script freezes and hangs when I run transcrible_speech with conformer transducer pretrained models.
I tried to kill the process and re-run it but it has the same behavior.

The terminal stuck like this:
Transcribing:  50%|███▎      | 1/2 [00:05<00:5, 7.54it/s]
Beam search progress:::  29%|██▎      | 5/17 [00:16<00:01, 8.02it/s]

I tried to follow this solution but it doesn't work because I am using beam search strategy.
https://github.com/NVIDIA/NeMo/issues/3025

**Steps/Code to reproduce bug**

`
class TranscriptionConfig:
    # Required configs
    model_path: Optional[str] = None  # Path to a .nemo file
    pretrained_name: Optional[str] = None  # Name of a pretrained model
    audio_dir: Optional[str] = None  # Path to a directory which contains audio files
    dataset_manifest: Optional[str] = None  # Path to dataset's JSON manifest

    # General configs
    output_filename: Optional[str] = None
    batch_size: int = 32
    num_workers: int = 0

    # Set cudato int to define CUDA device. If 'None', will look for CUDA
    # device anyway, and do inference on CPU only if CUDA device is not found.
    # If `cuda` is a negative number, inference will be on CPU only.
    cuda: Optional[int] = None
    amp: bool = False
    audio_type: str = "mp3"

    # Recompute model transcription, even if the output folder exists with scores.
    overwrite_transcripts: bool = True

    # Decoding strategy for RNNT models
    rnnt_decoding: RNNTDecodingConfig = RNNTDecodingConfig(fused_batch_size=-1, strategy="beam", beam=beam_decode.BeamRNNTInferConfig(beam_size=2))
`

Here is my decoding config:

`
'decoding': {'strategy': 'beam', 'compute_hypothesis_token_set': False, 'preserve_alignments': None, 'fused_batch_size': -1, 'greedy': {'max_symbols_per_step': 10, 'preserve_alignments': False}, 'beam': {'beam_size': 2, 'search_type': 'default', 'score_norm': True, 'return_best_hypothesis': True, 'tsd_max_sym_exp_per_step': 50, 'alsd_max_target_len': 1.0, 'nsc_max_timesteps_expansion': 1, 'nsc_prefix_alpha': 1, 'maes_num_steps': 2, 'maes_prefix_alpha': 1, 'maes_expansion_gamma': 2.3, 'maes_expansion_beta': 2, 'language_model': None, 'softmax_temperature': 1.0, 'preserve_alignments': False}}
`

**Comment by titu1994** [comment]
Your model is probably getting stuck in an infinite loop, constantly predicting RNNT blank. Try different beam search size, or other algorithms like mAES which should be faster as well.

**Comment by duckyngo** [comment]
Thank you for your answer, I will try with a different beam search size,
In the configuration file, I saw greedy, greedy_batch, beam, tsd, alsd are available for decoding strategy.  How can I change the algorithm to mAES ?

**Comment by titu1994** [comment]
decoding.strategy="maes"

**Comment by duckyngo** [comment]
Thank you very much. It worked !
