### ISSUE TITLE
Using LM with Online ASR

### ISSUE THREAD

**Issue by victornoriega** [NVIDIA/NeMo#523]
Hi. I was wondering how could I use a LM with the notebook to use for online Speech Recognition. Any ideas or recommendations?

**Comment by Slyne** [comment]
I wrote a toy example [here](https://github.com/Slyne/nemo_examples/tree/master/online_asr)
It simply keeps the state of the ctc_beam_search decoder state and continues to update the state whenever it receives a new data chunk.
