### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by Sasha-Bachynskyi** [NVIDIA/NeMo#5250]
Hello,

I installed all necessary dependencies and Nemo, but I got an issue when I tried to transcribe or diarize using Nemo
The exception is: **Floating point exception**, without any stacktrace, just this message
This exception occurred when the Nemo model was initialized

Dependencies:
> Cuda version: 11.2
> Python version: 3.8.10
> Torch version: 1.12.0+cu113
> Nemo version: 1.12.0 (I followed the steps for PIP in the readme)
> OS - Ubuntu 20.04.5 LTS
> Graphic card - Nvidia A40

I tried to use lower versions of PyTorch, it didn't help though.
Usage of PyTorch 1.9.0+cu111 and lower caused another exception: **OSError: libtorch_hip.so: cannot open shared object file**
I found a few topics where developers faced this issue and I even tried to fix it, but without success

If anyone knows how to handle this exception, I will appreciate any help in advance.

**Comment by titu1994** [comment]
Could you post the full error message? I've never heard of a Floating Point Exceptions / Error. What code were you trying to run?  And we don't support pytorch 1.9 anymore - min version is 1.11 and preferred is 1.12.1

**Comment by titu1994** [comment]
Also could you try using a conda environment with python 3.9? 

ex: conda create -n <name> python=3.9 
Then install pytorch, cython and other dependencies, followed by NeMo

**Comment by Sasha-Bachynskyi** [comment]
Thank you for your response.

The full program execution is below:
![image](https://user-images.githubusercontent.com/93126453/198020094-cd6d882d-58d4-4855-bb68-8fc254a526d0.png)

I'm trying to run one of my methods to get a dictionary of diarization
Below is a part of get_diarization method:

> cfg = OmegaConf.load('/home/denis/test_nemo/diarization.yaml')
> cfg.diarizer.manifest_filepath = fileManifestPath
> cfg.diarizer.out_dir = tempDirectoryPath
> self.writeToFileManifest(fileName, numSpeakers, fileManifestPath)
> asr_ts_decoder = ASR_TIMESTAMPS(**cfg.diarizer)
> asr_model = asr_ts_decoder.set_asr_model()
> word_hyp, word_ts_hyp = asr_ts_decoder.run_ASR(asr_model)

In the 6th string, I get this error, as you can see in the image above.

Also, I tried to use conda environment, and below is what happened:
![image](https://user-images.githubusercontent.com/93126453/198022689-66ceb457-edb6-49c6-925a-d2a3d06d4e0f.png)
The same exception

**Comment by Sasha-Bachynskyi** [comment]
I can't still solve this exception, even though I reinstalled ubuntu three times it doesn't help at all

**Comment by titu1994** [comment]
I don't work on diarization maybe @nithinraok can help

**Comment by Sasha-Bachynskyi** [comment]
Speech-to-text doesn't work either.
This code causes the same exception:

> import nemo.collections.asr as nemo_asr
> asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="stt_en_quartznet15x5")
> audio = "audio.wav"
> print (asr_model.transcribe([audio]))

**Comment by Sasha-Bachynskyi** [comment]
If someone faces the same exception, you should install the higher version of cuda. I installed cuda version 11.3 and it solved my issue
