### ISSUE TITLE
Issue with english WFST inverse text normalizer and "per cent"

### ISSUE THREAD

**Issue by laphang** [NVIDIA/NeMo#5256]
**Describe the bug**

The english WFST inverse text normalizer fails to correctly tag "per cent". 

**Steps/Code to reproduce bug**

```
from nemo_text_processing.inverse_text_normalization.inverse_normalize import InverseNormalizer
inverse_normalizer = InverseNormalizer(lang='en')

spoken = "The share price of BHP increased by eleven per cent"
un_normalized = inverse_normalizer.inverse_normalize(spoken, verbose=False)
print(un_normalized)
```

**Expected behavior**

I expect "The share price of BHP increased by 11 %". 

The actual output behavior is an unchanged input - "The share price of BHP increased by eleven per cent"

NB: If I change the input to "... per cents", then I do get the expected output. There's an issue with how the plural / singular forms are handled in this case

**Comment by lociko** [comment]
Does it make sense  for ITN to make distinguish between plurals and singulars for measure unit?
`eleven percent` or `eleven percents` the result would be the same `11 %`. Or for decimals `eleven point one per cent` or  `eleven point one per cents` -> `11.1 %` ?

I am not sure about other units, but I have feeling that we can make a unio operation of plural and singular units

**Comment by laphang** [comment]
I think the English grammatical issue here is that percent is both singular and plural, hence `eleven percent` is grammatically correct. Most of the other units are have different singular and plural forms. 

Also, worth mentioning that `percent` and `per cent` currently have different behaviours. 

Currently:
`eleven percent` -> `11 %`
`eleven percents` -> `eleven percents`
`eleven per cent` -> `eleven per cent`
`eleven per cents` -> `11 %`

Ideally they should all map to `11 %`. (as percents is apparently also a valid plural)

**Comment by liaeh** [comment]
This is because of the limited scope of `measurements.txt` file: only percent is included in the list here: [https://github.com/NVIDIA/NeMo/blob/main/nemo_text_processing/inverse_text_normalization/en/data/measurements.tsv#L12](https://github.com/NVIDIA/NeMo/blob/main/nemo_text_processing/inverse_text_normalization/en/data/measurements.tsv#L12). To include the alternative spelling of percent/per cent here, you could add a line to this list.

**Comment by yzhang123** [comment]
@anand-nv could you pls take a look at this?

**Comment by anand-nv** [comment]
percents and per cents are both nor valid words in english. Will make the relevant changes to support "per cent". Slightly less trivial because "cent" is also a unit of measure (100 cents make one acre) and will have to exclude case like "it costs around hundred per cent"

**Comment by laphang** [comment]
@anand-nv just wanted to follow up on this. Any updates?

per cent is standard in non-US english, so would be helpful for UK, Canada, Australia etc.
