### ISSUE TITLE
How to get asr result of audio with offset and duration

### ISSUE THREAD

**Issue by WangHelin1997** [NVIDIA/NeMo#5285]
Hello!
I want to test an audio file that has a specific offset and duraion, how can I do this?
For example, I want to test from 20s to 40s. The below scripts can only give me the result of the whole audio.
```
import nemo
import nemo.collections.asr as nemo_asr
quartznet = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En")
files = [os.path.join(data_dir, 'an4/wav/an4_clstk/mgah/cen2-mgah-b.wav')]
for fname, transcription in zip(files, quartznet.transcribe(paths2audio_files=files)):
  print(f"Audio in {fname} was recognized as: {transcription}")
```

**Comment by WangHelin1997** [comment]
1

**Comment by titu1994** [comment]
Model.transcribe() will process whole audio file. It does not support offset and duration variables since it does not accept manifests. 

We're working on ways to improve this in the long term but for now the only way is to preslice the audio file.

**Comment by titu1994** [comment]
You could also write your own decoding loop by copy pasting the model.transcribe() method and passing in your offset params to the data loader setup.

**Comment by WangHelin1997** [comment]
OK thanks.
