### ISSUE TITLE
AttributeError: 'dict' object has no attribute '_get_node_flag'

### ISSUE THREAD

**Issue by MLDeep16** [NVIDIA/NeMo#5290]
root/abc/venv/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 670, in open_dict
    prev_state = config._get_node_flag("struct")
AttributeError: 'dict' object has no attribute '_get_node_flag'

Thanks.

**Comment by MLDeep16** [comment]
@titu1994 please help in resolving the above issue. I have re installed omegaconf but still issue exist

**Comment by titu1994** [comment]
Are you running Nemo code ? What's the full stack trace ?

The error seems like you are passing a dict to a function that needs an OmegaConf object like DictConfig

**Comment by titu1994** [comment]
I'd suggest posting the issue on fairseq then. Perhaps they too use OmegaConf
