### ISSUE TITLE
Export Tacotron2 and Waveglow to ONNX and TRT

### ISSUE THREAD

**Issue by LironVoca** [NVIDIA/NeMo#531]
Hi , Is it possible to export Tacotron2 and Waveglow to ONNX and TRT?

**Comment by okuchaiev** [comment]
@drnikolaev  could you please comment on this? I think it is currently not possible to export Tacotron2 to ONNX due to limitations on the ONNX side. It is, however, possible for WaveGlow

**Comment by drnikolaev** [comment]
Exactly what i'm verifying now. So far it seems like that but let's not rush. Will keep you posted.

**Comment by LironVoca** [comment]
Thanks I'll wait for an update

**Comment by wannaphong** [comment]
I found the way to export tacotron2 to onnx model. https://github.com/PyThaiNLP/thaitts-onnx
