### ISSUE TITLE
ValueError: NeMo ASR collection is not installed. when run ./normalize_with_audio.py

### ISSUE THREAD

**Issue by yujunlhz** [NVIDIA/NeMo#5317]
When I run the following command

python ./normalize_with_audio.py  --text=" Hold on one second. 429-020"  --language=en --n_tagged=10 --cache_dir="cache_dir" --audio_data="./0001_00002.wav" --model="QuartzNet15x5Base-En" --verbose

I always get the error:
Traceback (most recent call last):
  File "./normalize_with_audio.py",  in <module>
    raise ValueError("NeMo ASR collection is not installed.")
ValueError: NeMo ASR collection is not installed.

I have install  nemo all
pip install nemo_toolkit[all]

**Environment details**

- OS version     CentOS 7
- PyTorch version      1.10.2+cu113
- Python version       Python 3.8.0

Thanks
Mark

**Comment by ekmb** [comment]
Could you try the steps from https://github.com/NVIDIA/NeMo/discussions/5405#discussioncomment-4132413 ?
