### ISSUE TITLE
tutorials/nlp/Information_Retrieval_MSMARCO.ipynb not found

### ISSUE THREAD

**Issue by hoangtnm** [NVIDIA/NeMo#5322]
**Describe the bug**

I'm trying to follow [Information Retrieval document](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/v1.12.0/nlp/information_retrieval.html), however, the link for its notebook cannot be found.

**Comment by mouhannadali** [comment]
the notebook still not available, why the ticket is closed ?
