### ISSUE TITLE
How to do quantization on the ASR model

### ISSUE THREAD

**Issue by ifahim** [NVIDIA/NeMo#5331]
**Describe the bug**

I am trying to do Post training static quantization on ASR model, following example here: (https://pytorch.org/blog/introduction-to-quantization-on-pytorch/#post-training-static-quantization) but keeps on getting following error. 
Two questions: 
1) Is there a way to bypass this error and get this working?
2) How to know what is the input shape for "stt_en_conformer_ctc_xlarge" model? Is there any API through which I know the shape?

```
File "asr_ctc.py", line 20, in <module>
    print(model.transcribe([audio_filepath], batch_size=1)[0])
 ---
 ----
 ---
 NotImplementedError: Could not run 'quantized::conv2d.new' with arguments from the 'CPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'quantized::conv2d.new' is only available for these backends: [Negative, UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].
```

**Steps/Code to reproduce bug**
```
# Streaming with CTC based models
import torch 
import nemo.collections.asr as nemo_asr

device = 'cpu'
model = nemo_asr.models.EncDecCTCModelBPE.from_pretrained("stt_en_conformer_ctc_xlarge", map_location=device)
model = model.to(device)
model.eval()
audio_filepath = './datasets/mini-dev-clean/LibriSpeech/dev-clean-2-processed/2428-83699-0042.wav'
model.qconfig = torch.quantization.get_default_qconfig()
torch.quantization.prepare(model, inplace=True)
torch.quantization.convert(model, inplace=True)
print("The transcribed speech is: ")
print(model.transcribe([audio_filepath], batch_size=1)[0])

```

**Expected behavior**

Expected transcribed output 

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal]
 - Method of NeMo install: [pip install Nemo].

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- Ubuntu 22.04
- PyTorch = 1.12.1
- Python version = 3.8

**Additional context**

Example: CPU model

**Comment by titu1994** [comment]
We don't support quantization in Nemo and don't test it, so I can't say if it will work or not. As the erorr says, some operators are not implemented for cpu, Conformer uses 2d conv in it's subsampling area so perhaps that's not supported.

**Comment by ifahim** [comment]
> We don't support quantization in Nemo and don't test it, so I can't say if it will work or not. As the erorr says, some operators are not implemented for cpu, Conformer uses 2d conv in it's subsampling area so perhaps that's not supported.

@titu1994 Thanks. Is there a way/API to know the input shape for "stt_en_conformer_ctc_xlarge" model?

**Comment by titu1994** [comment]
Shape of what ? Input or output ? If it's for exportable models (which Conformer is), you can do model.input_example() I think https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/core/export.html#exportable-hooks-and-overrides

**Comment by ifahim** [comment]
@titu1994 thats for NVIDIA ASR exportable model `stt_en_conformer_ctc_xlarge`. Is there any sample code to do model.input_example()? Thanks

**Comment by titu1994** [comment]
? It's one line. And the doc above explains how it is implemented so you can visit Conformer encoder file to see it's results of load a model and call that method
