### ISSUE TITLE
can't use dali with comma seperated manifest

### ISSUE THREAD

**Issue by twmht** [NVIDIA/NeMo#5349]
When using nvidia dali to train speech to text,

```python

cfg = copy.deepcopy(char_model.cfg)

"""
read cleaned manifest
"""
train_manifest_data = read_manifest(train_manifest_cleaned)
train_charset = get_charset(train_manifest_data)
dev_manifest_data = read_manifest(dev_manifest_cleaned)
dev_charset = get_charset(dev_manifest_data)

train_dev_set = set.union(set(train_charset.keys()), set(dev_charset.keys()))



# Setup train, validation, test configs
with open_dict(cfg):
  # Train dataset  (Concatenate train manifest cleaned and dev manifest cleaned)
  cfg.train_ds.manifest_filepath = f'{train_manifest_cleaned},{dev_manifest_cleaned}'
  cfg.train_ds.labels = list(train_dev_set)
  cfg.train_ds.normalize_transcripts = False
  cg.train_ds.batch_size = 32
  cfg.train_ds.use_dali = True
  cfg.train_ds.num_workers = 8
  cfg.train_ds.pin_memory = True
  cfg.train_ds.trim_silence = True

char_model.setup_training_data(cfg.train_ds)
```

![image](https://user-images.githubusercontent.com/1567200/200490593-dfa9ad0e-fcc3-4aa7-b735-9e4c597cb4a7.png)

**Comment by titu1994** [comment]
Thanks for this pr and issue ! I think we do not want dali to support comma concat datasets by design. But we can consider adding it.  

I'll have to ask @VahidooX for review, just in case it interfere with bucketing or normal tarred datasets. I think it may be fine.

**Comment by twmht** [comment]
by the way this PR is not verfied yet, since the training loss is mess.

**Comment by titu1994** [comment]
That was the original idea. Dali is quite complicated under the hood so we don't wish to shoehorn all the features into it

**Comment by titu1994** [comment]
And you only need to concat manifest - jo need to modify audio file paths or anything

**Comment by twmht** [comment]
What I condused is the document pointed out this argument can be a comma seperated str (https://github.com/NVIDIA/NeMo/pull/5350/files#diff-3bc6127e95895b259cca79339f871837deebe4e5f2f4af23f84877d8d976cfcaR104). So the better way is to concat the manifest if `cfg.use_dali=True`, or we should fix the document.

**Comment by titu1994** [comment]
ASRManifestProcessor is used by all ASR data loaders - pt, tarred, dali and bucketing. That comment is correct for just pt, but it is incorrect for all others.
