### ISSUE TITLE
Unable to resume ASR training

### ISSUE THREAD

**Issue by shihabtechno** [NVIDIA/NeMo#5351]
I am trying to resume my training by running the training command,it pick the last checkpoint properly and while stat training it show this error

![image](https://user-images.githubusercontent.com/107035118/200524914-f55b1b7a-d353-4224-9e45-c7b2ad146afc.png)

Environment details

OS version : Ubuntu 20.04 LTS
PyTorch version: 1.13.0a0+08820cb
Python version: 3.8.0
Nemo Version : 1.12.0
Additional context

I ran my model on 2 GPU's :
RTX 3090 and 
24267MiB

**Comment by titu1994** [comment]
We'll need a lot more info. Please fill out the bug template properly and discuss what you were training and what is the full stack trace
