### ISSUE TITLE
training stuck with multi gpu and dali training loader

### ISSUE THREAD

**Issue by twmht** [NVIDIA/NeMo#5365]
**Describe the bug**

Training get stuck when using ddp and dali loader together.

![image](https://user-images.githubusercontent.com/1567200/200734230-11aff089-a2e8-402f-9396-007c74159b93.png)

the usage of second gpu is zero. 

it works if I change `use_dali` to False

**Steps/Code to reproduce bug**

I follow the asr finetuing tutorial (https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/ASR_CTC_Language_Finetuning.ipynb), and change `devices=2`, `strategy='ddp'`.

```
trainer = ptl.Trainer(devices=2, 
                      accelerator=accelerator, 
                      strategy='ddp',
                      max_epochs=EPOCHS, 
                      accumulate_grad_batches=1,
                      enable_checkpointing=False,
                      logger=False,
                      log_every_n_steps=5,
                      check_val_every_n_epoch=10)

```

also, I change  `cfg.train_ds.use_dali=True`

Any idea?

**Comment by titu1994** [comment]
Dali can't run in a notebook. Please convert it to a script and then run.

**Comment by twmht** [comment]
@titu1994 

I did not use notebook. As you said I copy the script and run from my terminal.

**Comment by titu1994** [comment]
Hmm I don't have much of an idea why it's getting stuck. This notebook is mostly Japanese right ? Shouldn't encounter any long sentences for filtering. 

And you mentioned disabling dali works. I'll take a look at trying to reproduce this but it might take time.

**Comment by twmht** [comment]
Yup the notebook is Japanese, but I used chinese insted.  Disabling dali really works, so it's likely a potential bug.

**Comment by titu1994** [comment]
I can take another look in Jan, but my tests with the Japanese notebook on main seem to be fine
