### ISSUE TITLE
error when trying inverse "two thousand and nine"

### ISSUE THREAD

**Issue by nndcuong** [NVIDIA/NeMo#5367]
**Describe the bug**

```pynini``` raises error *ERROR: StringFstToOutputLabels: Invalid start state* when I am trying to accept "two thousand and nine" with DateFst, which means that DateFst hasn't well-define to accept this text
![image](https://user-images.githubusercontent.com/57069030/200786099-62590f4b-4e44-4e52-829c-24ff96c7c995.png)

**Steps/Code to reproduce bug**

First, initialize the DateFst object
```
from nemo_text_processing.inverse_text_normalization.en.taggers.cardinal import CardinalFst
from nemo_text_processing.inverse_text_normalization.en.taggers.ordinal import OrdinalFst
from nemo_text_processing.inverse_text_normalization.en.taggers.date import DateFst

cardinal = CardinalFst()
ordinal = OrdinalFst(cardinal)
date_fst = DateFst(ordinal).fst
```
Then, compose the text ```"two thousand and nine"``` with the FST above
```
text = "two thousand and nine"
print(pynini.shortestpath(text @ date_fst).string())
```

**Expected behavior**

DateFST can accept ```"two thousand and nine"``` and return the result that looks like ```date { year: "2009" preserve_order: true }```

**Comment by ekmb** [comment]
right, this case was covered with the cardinal graph, fixed for the date class with https://github.com/NVIDIA/NeMo/pull/5435.
