### ISSUE TITLE
Clarifications on Noise augmentation experiments with Nemo

### ISSUE THREAD

**Issue by manjuke** [NVIDIA/NeMo#5368]
Hi 
I followed the instructions @ https://github.com/NVIDIA/NeMo/issues/1660 and could successfully train a musan noise augmented nemo ASR model. However, I have few queries:

1. Where does the noise augmented files are stored? Or Are these noise augmented files are simply produced on the fly, as and when needed, and discarded once the job is done (without retaining them)?

2. When I use augmentors during training, does it include original clean files also for training along-with noise augmented files? Or it only uses noise augmented files for training?

3. For the kind of experiments & datasets that we used, we had expected lower WERs with noise augmentation compared to WERs obtained on clean datasets. However the obtained results are other way (noise augmented datasets have 1% higher WER than clean data). This made us to suspect the implementation part of nemo asr training. I have used exactly the same config of audio_augmentations mentioned by @jbalam-nv. There were no errors during training as well. Do you still feel there might be some implementation gaps (which has led to lower WER). Any suggestions on this would be very helpful.

4. I have used musan free sound noise and RIR. Is it fine? or any suggestions on this? 

Thanks a lot,
Manjunath

**Comment by titu1994** [comment]
> Where does the noise augmented files are stored? Or Are these noise augmented files are simply produced on the fly, as and when needed, and discarded once the job is done (without retaining them)?

Generated on the fly and they are not stored. 

> When I use augmentors during training, does it include original clean files also for training along-with noise augmented files? Or it only uses noise augmented files for training?

There's a probability for each augmentation being applied in the config. 

> For the kind of experiments & datasets that we used, we had expected lower WERs with noise augmentation compared to WERs obtained on clean datasets. However the obtained results are other way (noise augmented datasets have 1% higher WER than clean data). This made us to suspect the implementation part of nemo asr training. I have used exactly the same config of audio_augmentations mentioned by @jbalam-nv. There were no errors during training as well. Do you still feel there might be some implementation gaps (which has led to lower WER). Any suggestions on this would be very helpful.

Noise augmentation is to improve on noisy speech, it will almost always hurt accuracy on clean speech. There is no bug in augmentation, clean speech deteriorating is expected. 

> I have used musan free sound noise and RIR. Is it fine? or any suggestions on this?

@jbalam-nv

**Comment by manjuke** [comment]
Thanks @titu1994 . Could you please elaborate more on point 2.
From you response "There's a probability for each augmentation being applied in the config", I understand as below:
 Does it mean, depending on the probability value, if probability =0 then no noise addition (only clean data), or probability=1 too much noisy... Pls provide me more clarity. Pls help with the pointers/links for further reading about the same.
 
 And, in general, Pls provide help me with resources for further reading on augmentation. Thanks

**Comment by titu1994** [comment]
The probability determines if any augmentation of whatever type will be applied or not. It does not determine strength of augmentation c

At 0, no augmentation will ever be run, at 1, the augmentation will always be run

**Comment by manjuke** [comment]
Thanks, if I keep Prob=1, then I understand it will always augment.. For example, if no. of files in train_set = 100, then it will on the fly generate corresponding 100 noise augmented files; 
1. Does it mean it will only use "100" noise augmented files for training, ; if yes, how can I include clean speech along-with noisy ones for training (100 clean+ 100 noisy= 200 files for training)
or 
2. Does it use 200 files in total (both 100 clean speech files + 100 noise augmented files)

**Comment by titu1994** [comment]
You define total number of steps / epochs in trainer - each step has a chance of augmentation. If that is 100% then all steps of training will be augmented.

**Comment by jbalam-nv** [comment]
@manjuke Are your issues resolved? If not, could you share the augmentation settings you are using?

**Comment by manjuke** [comment]
Thanks @jbalam-nv I think settings were correct, and I stopped exploring this further, for now.
