### ISSUE TITLE
Can't convert my dataset to Tar

### ISSUE THREAD

**Issue by twmht** [NVIDIA/NeMo#5398]
Trying to convert my own dataset to Tarred dataset

the number of wav files is almost 280k.

```
python ${NEMO_ROOT}/scripts/speech_recognition/convert_to_tarred_audio_dataset.py \
  --manifest_path=train_decoded_processed.json \
  --target_dir=train_tarred_6bk \
  --num_shards=1024 \
  --max_duration=20.0 \
  --min_duration=1.0 \
  --shuffle \
  --shuffle_seed=1 \
  --sort_in_shards \
  --workers=-1 \
  --buckets_num=6
```

but this would throw the exception

![image](https://user-images.githubusercontent.com/1567200/201321512-e32e1734-a80b-4647-addc-9e96493b0dcf.png)

single bucket is fine, but failed to create multiple buckets.

any idea?

**Comment by titu1994** [comment]
Seems it is dali index that is breaking, you can temporarily rename the file in that directory called "create_dali_tarred_dataset_index.py" to something else so that the dataset building works properly. 

We will send a bugfix for this soon. Fyi @VahidooX something seems to be going wrong when doing bucketing + call to build tarred dali dataloader.

**Comment by titu1994** [comment]
Do note that bucketing is independent of dali, you cannot mix the two @twmht

**Comment by twmht** [comment]
@titu1994 
appreciated.

**Comment by VahidooX** [comment]
I guess the reason behind your error is that one of the buckets is empty which means there is a range with no audios in it. I have not tested bucketing for such cases with DALI. I suggest to not use DALI for now. 
Do you see the tarred dataset already built even with the error?

**Comment by twmht** [comment]
@VahidooX 

I did not use dali. What made you think I was using dali?

**Comment by titu1994** [comment]
Dali supports tarred datasets in Nemo, this script will build the index file required by dali if dali is installed. But it currently fails for bucketing datasets because that is not supported.

**Comment by VahidooX** [comment]
Would you please disable this block of code and try again?
https://github.com/NVIDIA/NeMo/blob/main/scripts/speech_recognition/convert_to_tarred_audio_dataset.py#L697
