### ISSUE TITLE
Segmentation fault (core dumped) when running nlp examples

### ISSUE THREAD

**Issue by ti3x** [NVIDIA/NeMo#5404]
**Describe the bug**

Run any example of Nemo from the repo, it will throw a Segmentation fault just at import steps. 

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.
One I tried is
```
`python NeMo/examples/nlp/duplex_text_normalization/duplex_text_normalization_infer.py`
Segmentation fault (core dumped)
```

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: AWS g5.xlarge
 - Method of NeMo install: followed exact conda command from NeMo repo. Only thing is that I am running as root.

**Environment details**

Otherwise, please provide:
- OS version ubuntu 20.04
- PyTorch version: '1.13.0'
- Python version: python 3.8.0

**Additional context**

nvidia-smi info
```
nvidia-smi
Mon Nov 14 06:30:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   18C    P0    56W / 300W |   6594MiB / 23028MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    108946      C   tritonserver                     6592MiB |
+-----------------------------------------------------------------------------+
```

**Comment by titu1994** [comment]
This may be due to Protobuf, could you try out the following steps posted here - https://github.com/NVIDIA/NeMo/discussions/5405?converting=1#discussioncomment-4132413

**Comment by ti3x** [comment]
Successfully installed nemo_toolkit-1.12.0 protobuf-4.21.5

```
python nemo-examples/NeMo/examples/nlp/duplex_text_normalization/duplex_text_normalization_infer.py
Segmentation fault (core dumped)
```

I tried upgrading protobuf and reinstall NeMo

**Comment by ti3x** [comment]
@titu1994 any other ideas to resolve this?

**Comment by titu1994** [comment]
Are you using python 3.9 environment ?

If not, You must install and upgrade both tensorboard and anaconda from conda only, pip will not work.

**Comment by ti3x** [comment]
no, the guide in readme was saying
```
conda create --name nemo python==3.8
conda activate nemo
apt-get update && apt-get install -y libsndfile1 ffmpeg
pip install Cython
python -m pip install git+https://github.com/NVIDIA/NeMo.git@{BRANCH}#egg=nemo_toolkit[all]
```

**Comment by titu1994** [comment]
Please use python 3.9. @okuchaiev we should update the readme to 3.9 for now to prevent such issues (though colab will be another problem which we will have to deal with later)

**Comment by ti3x** [comment]
@titu1994 I think that 3.9 change made all the difference. I installed NeMo with pip but made sure to install tensorboard with conda. There was no mention that we need to run condo install anaconda either.

**Comment by ti3x** [comment]
@titu1994 closing the issue, thank you for the quick tip
