### ISSUE TITLE
problem of univnet and onnx 

### ISSUE THREAD

**Issue by alexandercesarr** [NVIDIA/NeMo#5417]
Hi. I have trained univnet model and i want to export it to onnx. but i got this error . what should i do?

`
torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of operator Unfold, input size not accessible. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues  [Caused by the value '381 defined in (%381 : Float(*, *, *, strides=[65600, 2050, 1], requires_grad=0, device=cuda:0) = onnx::Pad[mode="constant"](%output, %379, %380), scope: nemo.collections.tts.models.univnet.UnivNetModel::/nemo.collections.tts.modules.univnet_modules.Generator::generator/nemo.collections.tts.modules.univnet_modules.LVCBlock::res_stack.0
`

**Comment by alexandercesarr** [comment]
@titu1994

**Comment by titu1994** [comment]
I dunno if this model is exportable. @XuesongYang please assign to the author of the model to see why export isn't working.

**Comment by alexandercesarr** [comment]
@XuesongYang
