### ISSUE TITLE
SentencePieceTokenizer in NER training

### ISSUE THREAD

**Issue by lebionick** [NVIDIA/NeMo#542]
Currently I'm trying to train BERT for NER task using tutorial: https://github.com/NVIDIA/NeMo/blob/v0.9.0/examples/nlp/NERWithBERT.ipynb  
I'm interested in using my pre-trained model and tokenizer. So, I've got custom BERT and `SentencePieceTokenizer` checkpoints using this tutorial: https://nvidia.github.io/NeMo/nlp/bert_pretraining.html . But when I try to start training, I get this error: `TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found object`, obviously, the problem is in data sampling.  
With my SentencePieceTokenizer sample from `BertTokenClassificationDataLayer` looks like this:  
```
array([list([0, 0, 0, 0, 0]), list([9, 99, 80, 378, 96]),
       list([9, 59, 186, 30, 370, 44, 159, 96, 44]),
       list([9, 78, 1, 23, 59, 59, 80, 1277, 44, 59, 78, 96, 44]),
       list([9, 59, 378, 44, 186, 1, 96, 44]), list([9, 724, 970]),
       list([9, 471, 2, 387, 724]), list([1]), list([9, 99]), list([1]),
       list([3]), list([13]), list([9, 591, 96, 59, 59, 80, 97]),
       list([0, 0, 0, 0, 0]), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)
```
and with pre-trained `NemoBertTokenizer` from tutorial it's: 
```
array([  101,   477, 16948, 28396, 28399, 10286,   476, 19692, 28400,
       19692, 17127, 28414, 28399, 10286, 14800,   486, 28416, 28399,
       28403,  1969,   110,   121,   119,  1512, 28400,   495, 28400,
       14800, 28397, 28399, 10286,   102,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0])
```  
Could you please tell me, how to modify my tokenizer (may be I even trained it in the wrong way) to produce "right" samples. (or at least what function is called to produce these samples)

**Comment by ekmb** [comment]
@lebionick your tokenizer should work with the latest master, please reopen if you still have issues.

**Comment by lebionick** [comment]
Now it works, thank you
