### ISSUE TITLE
conformer export problems 

### ISSUE THREAD

**Issue by sali1997s** [NVIDIA/NeMo#5436]
**Describe the bug**
Trying to export conformer to TorchScript, using `model.export('conformer.pt')` and [/scripts/export.py](https://github.com/NVIDIA/NeMo/blob/main/scripts/export.py). Getting error:
`RuntimeError: Type 'Tuple[Tensor, Tensor, NoneType, NoneType]' cannot be traced. Only Tensors and (possibly nested) Lists, Dicts, and Tuples of Tensors can be traced`

This is true for conformer trained on the Nemo version 1.12.
But everything is ok with exporting old version of conformer (trained on Nemo 1.10) and with that Nemo version installed.

**Comment by titu1994** [comment]
Is this with main branch ?

**Comment by titu1994** [comment]
Please provide the full stack trace

**Comment by sali1997s** [comment]
checked main branch, both exporting methods work fine!

so JFYI full trace
<img width="989" alt="Снимок экрана 2022-11-16 в 22 13 50" src="https://user-images.githubusercontent.com/44882363/202273470-0608dfae-2aea-4b59-ace0-ce439984860c.png">

**Comment by titu1994** [comment]
Good that main works, hopefully we'll release a new version soon.
