### ISSUE TITLE
Inference Size Error Speaker_ Diarization

### ISSUE THREAD

**Issue by arnavmehta7** [NVIDIA/NeMo#5483]
On the speaker_diarization ipynb file. If I switch the link to the audio to a custom audio then I get a shape error on inference. It shows that I have a  tensor but they required in some other format.

**Steps/Code to reproduce bug**
[Link of Notebook
](https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Diarization_Inference.ipynb)
On this notebook, just switch the link of audio or upload a audio and replace it with the an4 one.

**Expected behavior**
Diarization perfectly finished.

**Environment overview (please complete the following information)**
Colab.

**Environment details**
Colab.

**Comment by SeanNaren** [comment]
Thanks for the report!
cc @tango4j @nithinraok

**Comment by nithinraok** [comment]
Can you share the notebook with the error you were getting?
