### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Pydataman** [NVIDIA/NeMo#5500]
hello，I reproduced this paper （ADAPTER-BASED EXTENSION OF MULTI-SPEAKER TEXT-TO-SPEECH MODEL FOR NEW SPEAKERS），but the result is not as good as the paper， very poor。I only finetune adapter，please ask me where is the paper code？

**Comment by hdmjdp** [comment]
@Pydataman Have you find the office code?

**Comment by CindyTing** [comment]
Hey, can I request a link to your reproduced code? Thanks very much ahead!
