### ISSUE TITLE
TTS Speech marks

### ISSUE THREAD

**Issue by lumpidu** [NVIDIA/NeMo#5505]
**Is your feature request related to a problem? Please describe.**

In TTS, if one wants to provide timing hints of the currently spoken word to the user, one needs to map the timing information (beginning/end time offset in generated pcm) to a word or characters or phonemes. This is necessary/applicable for e.g. screen readers or language learning apps.

**Describe the solution you'd like**

The acoustic model should be able to output timing information of each spoken word / phoneme related to the input phonemes/words. Ideally, the information could be provided together with the output MEL spectrograms as an extra tensor, so that inferencing doesn't need to be done twice. Alternatively, providing a function, that takes the generated MEL spectrograms and maps these to the aforementioned timing information would also be a very good solution and could possibly be implemented generically for all TTS models that output MEL spectrograms.

**Describe alternatives you've considered**

Alternatively, of course without any lip-synchronization accuracy, one could just devide the overall generated audio time of the synthesized PCM by the number of input characters/phonemes, naively assuming every character/phoneme needs an equal amount of time to speak. Although easily to implement, timing results are however off most of the time.

**Additional context**

**Comment by redoctopus** [comment]
Does the solution for #5593 do what you are looking for? You should be able to calculate timestamps based on models like FastPitch that predict durations of each input text token.

**Comment by redoctopus** [comment]
Whoops, missed this follow-up, sorry about that. Yes, RAD-TTS has `duration_model_outputs` as a value in the module's `forward()` function.
