### ISSUE TITLE
Way to use `prefetch_factor` in ASR training

### ISSUE THREAD

**Issue by menon92** [NVIDIA/NeMo#5520]
**Is your feature request related to a problem? Please describe.**
The PyTorch [dataloader](https://pytorch.org/docs/stable/data.html) supports pre-fetching the batch of data so that GPU doesn't wait for data processing. But I could not find any options to set the  `prefetch_factor` parameter in the example config.YAML file

**Describe the solution you'd like**
Like others dataloader parameter, we can also set this prefetch_factor param in the config YAML file and use this during training 

Thanks

**Comment by SeanNaren** [comment]
Thanks for the issue! It seems we do not expose this variable when instantiating our data-loaders internally. This should just be a case of modifying the DataLoader instantiation across the library to include `prefetch_factor`. Happy to do this, but should just check with @titu1994 that this is the case!

**Comment by titu1994** [comment]
This is a pytorch 1.13 feature and we support min version of 1.12. We can add this support in the future

**Comment by titu1994** [comment]
We don't expose it cause we manually map arguments to the data loader. We'd have to update all classes to support this

**Comment by menon92** [comment]
As PyTorch 1.13 is the latest stable version. It would be helpful if the upcoming `NeMo` release support the `prefetch_factor` - Thanks

**Comment by titu1994** [comment]
Latest is not really important, we add support based on what is the minimum supported version. As long as we don't upgrade to 1.13 as minimum we won't be adding this. 

I'll keep it as a Todo though.

**Comment by titu1994** [comment]
Mistakenly closed, keeping open until we upgrade to 1.13 PT
