### ISSUE TITLE
How NeMo will behave for the Hinglish data having uncorrected sentences has some missing words and correct (labels) sentence for each record?

### ISSUE THREAD

**Issue by alamnasim** [NVIDIA/NeMo#553]
Hi,

I have trained an ASR (using DeepSpeech) for mixed Hindi-English data having a transcript written in roman(a-z).  I am facing a problem of having some words missed in output for OOV and varied domain/context. 

And I want to use NeMo to do some post-processing over the output of ASR (with LM). 

I am having wrong sentences misspelled as well as some missing words and for each incorrect sentence, I have correct sentences. 

So My Question is:
1. How NeMo will behave with incorrect sentences having missing words?
2. Do I need only misspelled words in an incorrect sentence and whether it will work for me to solve this problem?
3. Is there any way to predict missing words in the ASR output?

Thanks in advance. Any help will be appreciated.

Thanks,
Nasim Alam

**Comment by AshishSardana** [comment]
Can you explain what do you mean by - "I am having wrong sentences misspelled as well as some missing words and for each incorrect sentence, I have correct sentences"
