### ISSUE TITLE
ASR_with_SpeakerDiarization Notebook Doesn't Work

### ISSUE THREAD

**Issue by superMDguy** [NVIDIA/NeMo#5538]
**Describe the bug**

Error:
```
[NeMo E 2022-12-01 21:47:24 common:503] Model instantiation failed!
    Target class:	nemo.collections.asr.models.label_models.EncDecSpeakerLabelModel
    Error(s):	__new__() missing 1 required positional argument: 'task'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/nemo/core/classes/common.py", line 482, in from_config_dict
        instance = imported_cls(cfg=config, trainer=trainer)
      File "/usr/local/lib/python3.8/dist-packages/nemo/collections/asr/models/label_models.py", line 168, in __init__
        # self._macro_accuracy = Accuracy(num_classes=num_classes, average='macro')
    TypeError: __new__() missing 1 required positional argument: 'task'
```

Looks like there's something wrong with how the Accuracy class is instantiated

**Steps/Code to reproduce bug**

1. Load [notebook](https://github.com/NVIDIA/NeMo/blob/stable/tutorials/speaker_tasks/ASR_with_SpeakerDiarization.ipynb#L766) in collab
2. Run all cells
3. Fails on the `Run diarization with the extracted word timestamps` step

**Expected behavior**

The notebook works

**Environment overview (please complete the following information)**

 - Environment location: Collab w/GPU

**Comment by fgiral07** [comment]
I have the same problem, last week it was working and now it is not.

**Comment by SeanNaren** [comment]
This should be fixed on main by https://github.com/NVIDIA/NeMo/pull/5537

You can also fix this by running `pip install torchmetrics==0.10.3`

**Comment by superMDguy** [comment]
Yep, it's fixed, thanks!
