### ISSUE TITLE
question: sentence piece tokenizer 

### ISSUE THREAD

**Issue by stellaywu** [NVIDIA/NeMo#556]
Thanks for the package! I have a questions about the tokenizers during BERT pre-training -  in the pre-training demo code, the tokenizer is 
`tokenizer = nemo_nlp.data.SentencePieceTokenizer(model_path="tokenizer.model")
special_tokens = nemo_nlp.data.get_bert_special_tokens('bert')
tokenizer.add_special_tokens(special_tokens)`

When using this pretrained model with huggingface transformers pacakge, 
`tokenizer = BertTokenizer.from_pretrained(pretrained_path_contains_vocab.txt)`

The vocabulary size doesn't match. Should it not be used together? If not which tokenizer to use when using the huggingface BertTokenizers.from_pretrained? 
Thanks a bunch

**Comment by lebionick** [comment]
There are some options depending what you want to train.  
if you want to finetune BERT, you can just use pretrained tokenizer `nemo.collections.nlp.data.NemoBertTokenizer(pretrained_model="bert-base-cased")`  
if you want to train tokenizer, you should construct BERT according to vocabulary size, like this:
``` python
bert_model = nemo_nlp.nm.trainables.huggingface.BERT(
    vocab_size=tokenizer.vocab_size,
    num_hidden_layers=NUM_LAYERS,
    hidden_size=D_MODEL,
    num_attention_heads=NUM_HEADS,
    intermediate_size=D_INNER,
    max_position_embeddings=MAX_SEQ_LENGTH,
    hidden_act=HIDDEN_ACT
)
```  
if you want to just add extra vocabulary, I've seen such tutorial, but not sure if you can do this in nemo.

**Comment by stellaywu** [comment]
@lebionick  Thanks for the reply. I am not using the pretrained bert-base or bert-large, I trained BERT from scratch following the pre-training demo code in 
`examples/nlp/language_modeling/BERTPretrainingTutorial.ipynb`

Now I want to use this model (not the pretrained bert-base or bert-large) for downstream tasks with the huggingface transformers package. When i load my own pre-trained model with 
`tokenizer = BertTokenizer.from_pretrained($path_to_my_own_pre_trained_model)`
The vocabulary of the tokenizer doesn't match the model.

In the $path_to_my_own_pre_trained_model, I put the vocab.txt generated from `python create_vocab.py --train_path=$DATA_DIR/train.txt` as showed in the pre-training demo code in `BERTPretrainingTutorial.ipynb`. 

Thanks!

**Comment by lebionick** [comment]
@stellaywu so, what tokenizer did you use when you (pre)trained BERT from scratch?

**Comment by stellaywu** [comment]
@lebionick  this was the code i used for pretraining 
`tokenizer = nemo_nlp.data.SentencePieceTokenizer(model_path="tokenizer.model") special_tokens = nemo_nlp.data.get_bert_special_tokens('bert') tokenizer.add_special_tokens(special_tokens)`

**Comment by ekmb** [comment]
@stellaywu after running BERTPretrainingTutorial.ipynb you'll get a SentencePiece tokenizer model (tokenizer.model).

In order to use this model fro downstream task, you can run this:
tokenizer = nemo.collections.nlp.data.tokenizers.get_tokenizer(
    tokenizer_name="sentencepiece",
    pretrained_model_name="bert-base-uncased",
    tokenizer_model=path_to_sentencepiece_tokenizer.model,
)

pretrained_model_name ("bert-base-uncased" or "roberta-base" or "albert-base")- is only used to add special tokens to your SentencePiece tokenizer since bert/albert/roberta have different special tokens.

**Comment by stellaywu** [comment]
i see! So i can't use it with the huggingface tokenizer
`tokenizer = BertTokenizer.from_pretrained(pretrained_path_contains_vocab.txt)` ?

**Comment by lebionick** [comment]
@stellaywu Now I get it. So why don't you just use same code when you are doing downstream task? :) (Actually it worked for me, when I used own pretrained BERT for NER)
I think @ekmb sent the alternative code for same operations(?)
P.S. In the last message you replied to wrong user :)

**Comment by stellaywu** [comment]
@lebionick  Thanks ! didn't notice @ekmb was replying . Ok I see. I should be using the Nemo code for the downstream tasks Instead. Thank you both @ekmb
