### ISSUE TITLE
TTS time data extraction

### ISSUE THREAD

**Issue by amirhosseinttt** [NVIDIA/NeMo#5593]
I'm using fastpich & univnet from Nemo to generate audio from text (TTS). I want to have the time information of each word in such a way that it shows in what period of time each word was uttered. There are some ways to predict such information, but all of them are applied after running the encoder and vocoder models. Is there any way to get such information from TTS models (any of them) without having to post-process our data?
If there is not, I would be grateful if you tell me what is the most efficient way to get such information. 

@XuesongYang

**Comment by redoctopus** [comment]
The FastPitch model returns as one of its outputs `durs_predicted`, which is a [batch]x[# text tokens] tensor with predicted durations (in number of mel frames) per text token. You can then calculate the timestamp of each frame depending on your `hop_length` and `sample_rate` params without having to do eval through UnivNet!
