### ISSUE TITLE
Update minimum version requirements for Pytorch Lightning, for tensorboard/tensorflow doesn't support for now protobuf > 3.20

### ISSUE THREAD

**Issue by vadimkantorov** [NVIDIA/NeMo#5597]
PL soon to be released will work around this problem: https://github.com/Lightning-AI/lightning/issues/9900#issuecomment-1345390290

Might be useful to update the minimum version requirements of PL for Nemo

**Comment by titu1994** [comment]
This is fantastic ! Protobuf is an absolute nightmare on python 3.8, causing segfaults left and right. 

@ericharper @SeanNaren @redoctopus - let's make tensorboard an optional logger inside ExpManager and the domains (if TTS absolutely needs it they must do runtime check and ask user to install it explicitly). TensorboardX is fine if it doesn't install Protobuf. 

Time line for this is once PTL 1.9 is released, so there's a little breathing room here

**Comment by vadimkantorov** [comment]
Because currently it's somewhat a fiasco (especially if tensorboard logging is not used at all): https://github.com/pytorch/pytorch/issues/90374

**Comment by vadimkantorov** [comment]
Okay, it seems that PL released 1.9.0 version that makes all tensorboard-related stuff into optional dependencies: https://github.com/Lightning-AI/lightning/issues/9900

So after testing this, I would suggest that Nemo should update minimum PL version

**Comment by titu1994** [comment]
Main branch should have min version of 1.9 already

**Comment by vadimkantorov** [comment]
Does nemo also support a csv logger? (if unworking protobuf > 3.2.0 is absolutely needed for some other functionality, so tensorboard/X cannot be used)

Might be even good to have it enabled by default for this reason

**Comment by titu1994** [comment]
We shouldn't have protobuf dependency after upgrading to PTL 1.9x

**Comment by vadimkantorov** [comment]
Yeah, but if tensorboard logger is still kept as default in PL / its usage in Nemo, then effectively the dependency stays in place
