### ISSUE TITLE
Crash eval_beamsearch_ngram.py code for large data sets

### ISSUE THREAD

**Issue by ahkarami** [NVIDIA/NeMo#5598]
@VahidooX 
Hi,
When we use [`eval_beamsearch_ngram.py`](https://github.com/NVIDIA/NeMo/blob/main/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py) code for large data sets (e.g., with 500,000 utterances), the code crashes after some hours of computation (i.e., the OS kill automatically the process!!). According to my observation, the code runs correctly when the ASR acoustic model runs and the raw transcriptions of data sets extracted correctly, but when the LM wants to apply in a huge amount of raw transcriptions then it crashes. I googled this issue, and I found below link (which I think the issue related to the shortage of memory of the server):
- [Unable to allocate array with shape and data type](https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type)   
According to the above-mentioned link, I have changed the `overcommit_memory` mode of my server. however, unfortunately the issue didn't resolved. Would you please help me to address the issue?
Thanks a lot

**Comment by VahidooX** [comment]
Do you know exactly where in the code the memory error is being raised?

**Comment by ahkarami** [comment]
Thanks for your reply.
Unfortunately, I don't remember exactly which part of the code had problem, and of course I think that the process was just killed and the error was not reported for a specific part.
My used parameters were as follows:
```
    --acoustic_batch_size 16 \
    --device "cuda:0" \
    --beam_width 100 \
    --beam_alpha 0.76 \
    --beam_beta 1.0 \
    --beam_batch_size 128 \
    --decoding_mode beamsearch_ngram
```
I hope that if I use the latest version of your code, the problem will be solved. So, if you agree, I will resolve this issue for now and if I have problems again in the future, I will let you know.
Thanks
