### ISSUE TITLE
Fix documentation for the fine-tuning for multi-gpu training 

### ISSUE THREAD

**Issue by ggrunin** [NVIDIA/NeMo#56]
In Fine-Tuning section of tutorial, add that in case of distributed training the restore syntax has to be the following:
jasper_encoder.restore_from("/data/atc_tenant/Speech2/nemodata/JasperEncoder-
jasper_decoder.restore_from("/data/atc_tenant/Speech2/nemodata/JasperDecoderForCTC-STEP-247400.pt", args.local_rank)

**Comment by okuchaiev** [comment]
fixed, will appear in online docs with 0.8.1 release
