### ISSUE TITLE
WFST Text Normalization: Address graph and OK

### ISSUE THREAD

**Issue by liaeh** [NVIDIA/NeMo#5612]
**Describe the bug**

The address graph is too permissive and always transduces "OK" to "Oklahoma" even in cases when it is not a part of an address.

Could be nice to add some test cases that evaluate the performance of the graph in cases where OK is/is not a part of an address or not, maybe also extending the address graph if possible.

**Steps/Code to reproduce bug**

```
from nemo_text_processing.text_normalization.normalize import Normalizer

print(normalizer.normalize("Ah, OK.", verbose=True, punct_post_process=True))
print(normalizer.normalize("That's OK.", verbose=True, punct_post_process=True))
```
Output:
```
tokens { name: "Ah, Oklahoma" }  tokens { name: "." }
Ah, Oklahoma.  # incorrectly transduced by the address graph
tokens { name: "That's" } tokens { name: "OK." }  
That's OK.  # expected
```

**Expected behavior**

The grammar only transforms `OK -> Oklahoma` when in the context of an address.

**Environment overview (please complete the following information)**

 - Jupyter notebook in venv on local machine
 - Method of NeMo install: pip install nemo_toolkit['all']

**Environment details**

- OS version 5.13.0-40-generic
- PyTorch version 1.13.0
- Python version 3.9.7

**Additional context**

**Comment by lociko** [comment]
According to the code:
```python
# convert to states only if comma is present before the abbreviation to avoid converting all caps words,
# e.g. "IN", "OH", "OK"
# TODO or only exclude above?
states = load_labels(get_abs_path("data/address/state.tsv"))
```

So it means if we have `Ah, OK.` it will be `Ah, Oklahoma`. And if comma is not present `OK` is just `OK`.
@ekmb what do you think what is the best fix for it? Just exclude  `"OK"` or have some smart logic to resolve it?
Thanks!
