### ISSUE TITLE
EMA Doesn't delete previous EMA ckpts when k > 0 for checkpointing

### ISSUE THREAD

**Issue by SeanNaren** [NVIDIA/NeMo#5631]
**Describe the bug**

EMA saves a separate EMA based ckpt when normally saving. The problem is when saving a set amount of checkpoints (i.e k=5) the older EMA ckpts are not being deleted. This means there is an excess of EMA based ckpts.

What is expected is that older EMA ckpts are deleted.

**Proposed Solution**

Overriding the code is tricky, as the call to remove ckpts is found within functions, like such:

https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/callbacks/model_checkpoint.py#L652
https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/callbacks/model_checkpoint.py#L671
https://github.com/Lightning-AI/lightning/blob/master/src/pytorch_lightning/callbacks/model_checkpoint.py#L713

My suggestion would be to move this code into a separate function that can be overridden in the [NeMoModelCheckpoint](https://github.com/NVIDIA/NeMo/blob/4d3e99f986fd9354b5528a3e9c82fe01ec2df916/nemo/utils/exp_manager.py#L745) class by introducing a `delete_checkpoint` function. In this function we will also be able to delete the EMA weights.

**Comment by SeanNaren** [comment]
cc @carmocca

**Comment by carmocca** [comment]
Ideally, we would find a better solution. However, since that would require a larger refactor --- to `ModelCheckpoint` and/or NeMo -- and the `NemoModelCheckpoint` callback already relies heavily on overriding protected methods, I'm fine with adding one more.

**Comment by titu1994** [comment]
That's sounds like a good interim measure.

**Comment by SeanNaren** [comment]
PR created here: https://github.com/Lightning-AI/lightning/pull/16067 

Hopefully this can make it into the next bugfix release if possible.

**Comment by carmocca** [comment]
@Borda, do you agree with cherry picking this into a 1.8.x release?

**Comment by Borda** [comment]
> @Borda, do you agree with cherry picking this into a 1.8.x release?

yes, good with me
