### ISSUE TITLE
Speaker Diarization Task: Clustering stage crashes(Process killed) for long audio files using CPU

### ISSUE THREAD

**Issue by gabitza-tech** [NVIDIA/NeMo#5637]
Hello,

I've been testing the NeMo diarization example, using clustering inference on many different datasets and inputs using CPU only. On files up to 90 minutes in length, the diarizer reached around 25Gb RAM consumed in the clusterization stage. When I tried to diarize a 4 hour file that has 2 speakers using CPU only, the process was killed in the clusterization stage, no matter the configuration file used.

The configuration I used:
- clustering_diarizer/offline_diar_infer
- vad_multilingual_marblenet
- embeddings extraction: titanet_l
- configurations: either meeting or general ( both crashed)

The way I solved the process crashing problem was by splitting the 4 hour audio in 4 parts, and then merge the predicted rttms at the end by taking in consideration the offset between parts and checking if the speaker labels match. The issue is that the cluster labels on each file may differ from the other files, even if it is the same original audio split into 4. With only 2 speakers, it may be easy to check and switch the speakers labels so they match between all corresponding parts, but when there are more than 2 speakers, it's impossible.

My questions are: is there a way to avoid the process being killed when using long audio files(above 2 hours for example) on CPU(I can't used GPU)? If there isn't, is there a way to match the speakers from each split from the original audio? (example: speaker 1 in part 1 may be corresponding to speaker 4 in part 2) I was thinking about extracting an mean affinity matrix for each speaker in each part and then calculating the cosine distance between all speakers. 

Any solution, idea or feature that is already implemented would be greatly appreciated!

**Comment by tango4j** [comment]
Hi, sorry for the late reply. Currently, the clustering algorithm has limitation on 60~70 min audio (depending on the scale length). Currently, we are working on clustering algorithm that handles long-form audio inputs. This feature will be added along with online diarization capability.

**Comment by gabitza-tech** [comment]
Hi, thank you for you response! Looking forward to the implementation!

**Comment by gabitza-tech** [comment]
@tango4j I would like to ask you if there is an expected time for the feature to be released at the moment?

I would also like to make two proposals for solving this issue, from my research and what I have tested so far:

1.The first approach I have tried was to split an audio in multiple parts (4 hours in 4 equal parts) and find similarities between the spectral embeddings of speakers between parts, because if there are the same speakers in each audio, the spectral embeddings should be similar. This means I would perform clustering on each audio part and obtain the labels for them, then for each label representing a speaker I would calculate the mean of the spectral embeddings associated with the label.

After this step, I thought I would search for a threshold of similarity between the means of the spectral embeddings for speakers from each audio part in order to obtain out of 8 labels (2 for each part) only 2 speakers (ex: | mean_of_speaker1_part1 - mean_of_speaker1_part3 | < threhold=> same speaker). The problem with this approach is that, from my test, it seems that spectral embedings for the same speakers in different audios vary greatly and there is no correlation between them (ex: if in part 1 of an audio, a man has spectral_emb_mean=-0.02 and a woman has spectral_emb_mean =0.05, in part 3, the man has spectral_emb_mean=0.04 and the woman has spectral_emb_mean=-0.03). I will continue to test if there could be a correlation between the labels for a timestamp and the multi scale cos affinity matrices. 

I would also greatly appreciate if you could offer a response if this method is worth trying or not.

2.The second approach would be using an implementation in Pytorch of the Faiss library for K-means Clustering. 

Thank you in advance and I am looking forward to the response!

**Comment by EmreOzkose** [comment]
I met the same problem and resolved it. I think this issue can be a memory leak. I added 'with torch.no_grad():' here

from 
https://github.com/NVIDIA/NeMo/blob/1c33eb7d2885e229fbd84745e8cb81f595139b89/nemo/collections/asr/models/clustering_diarizer.py#L350-L355

to 
![image](https://user-images.githubusercontent.com/17765576/211738523-5abc9495-24fa-4fcb-b14f-658646b445bf.png)

**Comment by EmreOzkose** [comment]
I also changed below part. However, as I remember, the main issue was above part.

from 
https://github.com/NVIDIA/NeMo/blob/1c33eb7d2885e229fbd84745e8cb81f595139b89/nemo/collections/asr/models/label_models.py#L330-L335
to
![image](https://user-images.githubusercontent.com/17765576/211738879-0b7460e8-4d80-4f9a-b5bb-eacfc147e2a6.png)

Note that, my Nemo version is 1.6.0

**Comment by gabitza-tech** [comment]
Hey @EmreOzkose , thank you for the reply. I have tried your suggestion and I saw an improvement in memory consumption and inference time in the embedding extraction step! Thank you for your suggestion. But my problem still persists regarding the process being killed due to memory overload, as I run out of memory on the _perform_clustering()_ step. 

Meanwhile, I have discovered what the issue regarding the memory consumption was: 

https://github.com/NVIDIA/NeMo/blob/1c33eb7d2885e229fbd84745e8cb81f595139b89/nemo/collections/asr/parts/utils/offline_clustering.py#L513-L523

Apparently, it doesn't even get to the K-means clustering stage. At the torch.repeat_interleave step memory keeps growing with each iteration. Around the 5th scale, the process is killed. Here is the log of some prints I do in the MultiScaleCosAffinityMatrix function:

> The file being clustered is:NOSFE_Gojira_Podcast_16khz_mono
Dimension of a_norm is same as b_norm:[8647, 192]
Dimension of res is:[8647, 8647]
[8647]
repeated_tensor 0 [53419, 8647]
repeated tensor 1 [53419, 53419]
Dimension of a_norm is same as b_norm:[10436, 192]
Dimension of res is:[10436, 10436]
[10436]
repeated_tensor 0 [53419, 10436]
repeated tensor 1 [53419, 53419]
Dimension of a_norm is same as b_norm:[13110, 192]
Dimension of res is:[13110, 13110]
[13110]
repeated_tensor 0 [53419, 13110]
repeated tensor 1 [53419, 53419]
Dimension of a_norm is same as b_norm:[17583, 192]
Dimension of res is:[17583, 17583]
[17583]
repeated_tensor 0 [53419, 17583]
repeated tensor 1 [53419, 53419]
Dimension of a_norm is same as b_norm:[26538, 192]
Dimension of res is:[26538, 26538]
[26538]
repeated_tensor 0 [53419, 26538]
Killed

Is there a way to improve the performance of the torch.repeat_interleave function, in order to not run out of memory. Or a way to improve the for loop?

**Comment by EmreOzkose** [comment]
In my case, 4 GB is enough to process 43 min audio. When debugging the problem, I used [memory profiler](https://pypi.org/project/memory-profiler/).

1. install with pip
2. import 'from memory_profiler import profile'
3. write '@profile' before the function.

It prints line-by-line memory allocation. It would be easier to detect what is the problem, and why/where the memory is getting increased so much.

**Comment by gabitza-tech** [comment]
Thank you for the debugger! 

For a 30 minute audio I use around 2 GB of memory at the clustering step, with the biggest tensor size of around [5000,5000]. For a 90 minute audio, i use around **23 GB** at the getMultiScaleCosAffinityMatrix() step! This is a huge increase but I can see why when the biggest tensor size gets up to [20000,20000]. I still think that the best resource management solution would be to split a long audio of 4 hour in smaller audio parts of 30 minutes, and then find a correlation between the clusters of each audio part. (fuse the results)

Profile for a 90 minute audio sample:



![ss_mem_list](https://user-images.githubusercontent.com/53811655/212084936-3d3887cf-4401-417f-93ad-e6e514692d23.png)

**Comment by gabitza-tech** [comment]
Update:

I managed to decrease the memory consumption of the getMultiScaleCosAffinityMatrix() function down to a peak of 5.8 GB. This implementation works at the moment for the case in which the weight for each scale is equal to 1.0. Change code from:

https://github.com/NVIDIA/NeMo/blob/1c33eb7d2885e229fbd84745e8cb81f595139b89/nemo/collections/asr/parts/utils/offline_clustering.py#L483-L523

to:

```
@torch.jit.script
def getMultiScaleCosAffinityMatrix(
    multiscale_weights: torch.Tensor,
    embeddings_in_scales: List[torch.Tensor],
    timestamps_in_scales: List[torch.Tensor],
    device: torch.device = torch.device('cpu'),
) -> torch.Tensor:
    multiscale_weights = multiscale_weights.to(device)
    score_mat_list, repeated_tensor_list = [], []
    session_scale_mapping_list = get_argmin_mat(timestamps_in_scales)
    
    scale_list = list(range(len(timestamps_in_scales)))
    print("Starting to Calculate affinity matrices")
    
    fused_sim_d = torch.zeros(len(timestamps_in_scales[-1]),len(timestamps_in_scales[-1]))
    
    for scale_idx in scale_list:
        with torch.no_grad():
            mapping_argmat = session_scale_mapping_list[scale_idx]
            emb_t = embeddings_in_scales[scale_idx].half().to(device)
            score_mat_torch = getCosAffinityMatrix(emb_t)
            
            repeat_list = getRepeatedList(mapping_argmat, torch.tensor(score_mat_torch.shape[0])).to(device)
            print(f"Repeat list size:{repeat_list.size()}")
            
            repeated_tensor_0 = torch.repeat_interleave(score_mat_torch, repeats=repeat_list, dim=0)
            del score_mat_torch
            print("repeated_tensor 0 {}".format(repeated_tensor_0.size()))
            
            repeated_tensor_1 = torch.repeat_interleave(repeated_tensor_0, repeats=repeat_list, dim=1)
            del repeated_tensor_0
                        
            print("repeated tensor 1 {}".format(repeated_tensor_1.size()))
            fused_sim_d = fused_sim_d + repeated_tensor_1
            del repeated_tensor_1
            
            print("\n")    
            
    print("Fused sim_d : {}".format(fused_sim_d.size()))
    return fused_sim_d
```

Profilling:
![ss_sum_del](https://user-images.githubusercontent.com/53811655/212111201-7cfad79a-f168-43cc-8f9d-a981ef14646d.png)

It is still a pretty big value and by splitting the audio in smaller parts the peak is around 2GB only.

**Comment by tango4j** [comment]
> @tango4j I would like to ask you if there is an expected time for the feature to be released at the moment?
> 
> I would also like to make two proposals for solving this issue, from my research and what I have tested so far:
> 
> 1.The first approach I have tried was to split an audio in multiple parts (4 hours in 4 equal parts) and find similarities between the spectral embeddings of speakers between parts, because if there are the same speakers in each audio, the spectral embeddings should be similar. This means I would perform clustering on each audio part and obtain the labels for them, then for each label representing a speaker I would calculate the mean of the spectral embeddings associated with the label.
> 
> After this step, I thought I would search for a threshold of similarity between the means of the spectral embeddings for speakers from each audio part in order to obtain out of 8 labels (2 for each part) only 2 speakers (ex: | mean_of_speaker1_part1 - mean_of_speaker1_part3 | < threhold=> same speaker). The problem with this approach is that, from my test, it seems that spectral embedings for the same speakers in different audios vary greatly and there is no correlation between them (ex: if in part 1 of an audio, a man has spectral_emb_mean=-0.02 and a woman has spectral_emb_mean =0.05, in part 3, the man has spectral_emb_mean=0.04 and the woman has spectral_emb_mean=-0.03). I will continue to test if there could be a correlation between the labels for a timestamp and the multi scale cos affinity matrices.
> 
> I would also greatly appreciate if you could offer a response if this method is worth trying or not.
> 
> 2.The second approach would be using an implementation in Pytorch of the Faiss library for K-means Clustering.
> 
> Thank you in advance and I am looking forward to the response!

Unfortunately, like you mentioned in your comment, using spectral embedding can hardly make sense because spectral embedding is generated from the eigen vectors from eigen decomposition of affinity matrix, not from speaker-oriented manifold. Spectral embedding only contains the traits of the affinity matrix of that particular session.

I have a half-baked code for performing divide-and-conquer. I wasn't able to make the performance exactly same as one giant affinity matrix. Do you want to try that branch?

**Comment by gabitza-tech** [comment]
Hey @tango4j, thank you for your response and sorry for the late reply.



> @gabitza-tech Hi, Sorry for the late reply. I was occupied by other threads. I think if we change `fused_sim_d = fused_sim_d + multiscale_weights[scale_idx] * repeated_tensor_1` then it will also work for all kinds of weights.
> 
> Were you able to get the exact same performance after you make this change ?

I have tested and the performance is identical. This is my final implementation:
```
@torch.jit.script
def getMultiScaleCosAffinityMatrix(
    multiscale_weights: torch.Tensor,
    embeddings_in_scales: List[torch.Tensor],
    timestamps_in_scales: List[torch.Tensor],
    device: torch.device = torch.device('cpu'),
) -> torch.Tensor:
    """
    Calculate cosine similarity values among speaker embeddings for each scale then
    apply multiscale weights to calculate the fused similarity matrix.

    Args:
        uniq_embs_and_timestamps (dict):
            The dictionary containing embeddings, timestamps and multiscale weights.
            If uniq_embs_and_timestamps contains only one scale, single scale diarization
            is performed.

    Returns:
        fused_sim_d (Tensor):
            This function generates an affinity matrix that is obtained by calculating
            the weighted sum of the affinity matrices from the different scales.
    """
    multiscale_weights = torch.squeeze(multiscale_weights,dim=0).to(device)
    
    repeated_tensor_list = []
    session_scale_mapping_list = get_argmin_mat(timestamps_in_scales)
    
    scale_list = list(range(len(timestamps_in_scales)))
    print("\nStarting to Calculate affinity matrices")
    
    fused_sim_d = torch.zeros(len(timestamps_in_scales[-1]),len(timestamps_in_scales[-1]))

    for scale_idx in scale_list:
        
        with torch.no_grad():
            
            mapping_argmat = session_scale_mapping_list[scale_idx]

            emb_t = embeddings_in_scales[scale_idx].half().to(device)
            score_mat_torch = getCosAffinityMatrix(emb_t)
            
            repeat_list = getRepeatedList(mapping_argmat, torch.tensor(score_mat_torch.shape[0])).to(device)

            repeated_tensor_0 = torch.repeat_interleave(score_mat_torch, repeats=repeat_list, dim=0)
            
            repeated_tensor_1 = torch.repeat_interleave(repeated_tensor_0, repeats=repeat_list, dim=1)
            
            fused_sim_d = fused_sim_d + multiscale_weights[scale_idx] * repeated_tensor_1#fused affinity matrix of scales
          
    print("Fused affinity matrix size is : {}".format(fused_sim_d.size()))
    return fused_sim_d
```

I will make a push with this change.

**Comment by gabitza-tech** [comment]
> > @tango4j I would like to ask you if there is an expected time for the feature to be released at the moment?
> > I would also like to make two proposals for solving this issue, from my research and what I have tested so far:
> > 1.The first approach I have tried was to split an audio in multiple parts (4 hours in 4 equal parts) and find similarities between the spectral embeddings of speakers between parts, because if there are the same speakers in each audio, the spectral embeddings should be similar. This means I would perform clustering on each audio part and obtain the labels for them, then for each label representing a speaker I would calculate the mean of the spectral embeddings associated with the label.
> > After this step, I thought I would search for a threshold of similarity between the means of the spectral embeddings for speakers from each audio part in order to obtain out of 8 labels (2 for each part) only 2 speakers (ex: | mean_of_speaker1_part1 - mean_of_speaker1_part3 | < threhold=> same speaker). The problem with this approach is that, from my test, it seems that spectral embedings for the same speakers in different audios vary greatly and there is no correlation between them (ex: if in part 1 of an audio, a man has spectral_emb_mean=-0.02 and a woman has spectral_emb_mean =0.05, in part 3, the man has spectral_emb_mean=0.04 and the woman has spectral_emb_mean=-0.03). I will continue to test if there could be a correlation between the labels for a timestamp and the multi scale cos affinity matrices.
> > I would also greatly appreciate if you could offer a response if this method is worth trying or not.
> > 2.The second approach would be using an implementation in Pytorch of the Faiss library for K-means Clustering.
> > Thank you in advance and I am looking forward to the response!
> 
> Unfortunately, like you mentioned in your comment, using spectral embedding can hardly make sense because spectral embedding is generated from the eigen vectors from eigen decomposition of affinity matrix, not from speaker-oriented manifold. Spectral embedding only contains the traits of the affinity matrix of that particular session.
> 
> Also, NeMo diarization tries to avoid involving any threshold for clustering (like AHC) since the threshold only works for one specific domain or a specific dataset.
> 
> I have a half-baked code for performing divide-and-conquer. I wasn't able to make the performance exactly same as one giant affinity matrix. Do you want to try that branch?

Regarding this, I would greatly appreciate if you could provide an example of your implementation, I am also working on something and as soon as I patch a usable demo I will return with details.
