### ISSUE TITLE
UL2 sampling is Poisson instead of uniform

### ISSUE THREAD

**Issue by janEbert** [NVIDIA/NeMo#5655]
UL2 objectives should be sampled with uniform probability, including subtasks. Instead, currently, first the overarching denoiser is uniformly sampled and then the denoising subtask is again sampled uniformly. This is only the case [here for X-denoisers](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/data/language_modeling/megatron/ul2_dataset.py#L174-L178) currently, because one R- and one X-denoising objective from the paper are missing.

Compare:

```python
import itertools
import random

# The integers indicate the different task types in the paper.
tasks = {'R': [0, 1], 'S': [2], 'X': [3, 4, 5, 6]}

# How it's currently done in NeMo:
denoiser_subtasks = random.choice(tasks)
subtask = random.choice(denoiser_subtasks)
# Each of 0, 1 has 1/3 * 1/2 chance.
# 2 has 1/3 chance.
# Each of 3, 4, 5, 6 has 1/3 * 1/4 chance.

# How it's done in the code snippet from the UL2 paper:
subtask = random.choice(list(itertools.chain.from_iterable(tasks.values())))
# Each of 0, 1, 2, 3, 4, 5, 6 has 1/7 chance.
```

**Comment by MaximumEntropy** [comment]
Thanks for raising this! As discussed in the big-code slack channel, I'll expose different sampling parameters for the UL2Dataset class in the coming weeks. r-masking will cover only short spans and small masking probabilities and x-masking will cover 3 cases where one or both the span length and masking prob is large.

**Comment by janEbert** [comment]
Since you closed this, I just wanted to make sure we are on the same page regarding the problem of sampling here. Even assuming that the two similar R- and X-denoisers are merged, the current way of sampling the remaining X-denoisers is still incorrect.

**Comment by MaximumEntropy** [comment]
I agree that it's just not the same way as done in the paper, but I'm not sure I'd call it wrong unless I'm missing something. What I'm proposing to do soon is provide user-specifiable sampling probs for both high-level tasks (s,r,x) as well as x subtasks like (high prob small span, small prob, large span, high prob large span).

**Comment by janEbert** [comment]
I would consider behavior not in accordance to the specification incorrect, but it's fine either way. :)
Thanks for looking into this!

**Comment by Lauler** [comment]
Checking in here because we're looking at training UL2 with NeMo. The authors did perform ablations on the optimal fraction of S-denoising. From the paper:

> All tasks have an approximate equal participation in the mixture. We also explore an alternative where we increase number of S-denoisers up to 50% of denoisers in the Mixture and all other denoisers take up the remainder. We present detailed ablation studies of various design choices in the later sections [(page 10)](https://arxiv.org/pdf/2205.05131.pdf#page=10). 

> Small Amounts of S-Denoisers is Preferred We explore a setting where we scale S-denoisers to 50% of the entire MoD mixture. We find that this generally hurts performance. Hence, we make a conclusion that S-denoisers are necessary but only small amounts of S-denoisers (≈ 20%) are preferred [(page 16)](https://arxiv.org/pdf/2205.05131.pdf#page=16) . 

In the UL2-objective sampling code they provide in the appendix, it seems the sampling proportion can be set individually for each task using the argument `rates` (I interpret their usage of the word `task` to refer to what @janEbert calls a subtask). 

It'd be nice with user-specifiable sampling probs for the subtasks, as right now S-denoising is sampled at 33.3%, whereas the UL2 authors settled for 1/7 = 14.2% after ablations.

**Comment by janEbert** [comment]
On another note, the mentioned discrepancy still hasn't been fixed even though the issue was closed 4 months ago. Is this a wontfix?

**Comment by MaximumEntropy** [comment]
I've changed the configuration around a little bit in this PR - https://github.com/NVIDIA/NeMo/pull/6256.
