### ISSUE TITLE
common\losses\cross_entropy.py doesn't work on some gpus if mask tensor has integer type

### ISSUE THREAD

**Issue by bene-ges** [NVIDIA/NeMo#5665]
**Describe the bug**

common\losses\cross_entropy.py doesn't work on some gpus if mask tensor has integer type.
Given that mask is a tensor of all 1 with dtype=torch.int64
in lines 71-72
       if loss_mask.dtype is not torch.bool:
              loss_mask = loss_mask > 0.5
loss_mask should become all True, if run on cpu or on some (newer?) gpus.
But I see two cases when loss_mask becomes all False (GTX780,  Tesla K40m )
It seems that comparison between int and float works differently.

This leads to labels_flatten be empty and torch original cross entropy function is called with not-flattened tensors resulting in frustrating error like: RuntimeError: Expected target size [4, 11], got [4, 256]

**Steps/Code to reproduce bug**

import torch
import numpy as np
from nemo.collections.common.losses import CrossEntropyLoss

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
loss_fn = CrossEntropyLoss(logits_ndim=3)
logits = torch.tensor(np.ones((4, 256, 11), dtype=np.float), device=device)
labels = torch.tensor(np.ones((4, 256), dtype=np.int64), device=device)
labels_mask = torch.tensor(np.ones((4, 256), dtype=np.int64), device=device)
val_loss = loss_fn(logits=logits, labels=labels, loss_mask=labels_mask)
print("val_loss=", val_loss)

**Expected behavior**

This works on cpu and in colab's gpu, but gives error in GTX780 and Tesla K40m

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by ericharper** [comment]
Thanks for the issue!

Could you suggest a fix that works in your environment?
