### ISSUE TITLE
Peformance Measure inference after finetuning

### ISSUE THREAD

**Issue by skanda1005** [NVIDIA/NeMo#5682]
I have finetuned the titanet_large model on a new dataset which is related to the work I will be performing the embedding extraction on. That dataset has been split into a test set which contains unseen speakers. I would like to see if the finetuned model is performing better on the unseen dataset as compared to the original titanet model. Any ideas in which I can compare results?

Also, is there any way I can create a trial file for my dataset?
Thanks!

**Comment by nithinraok** [comment]
You can create a trial file to have a similar format as shown [here](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test.txt) with the samples you have. 

Then you can use [this](https://github.com/NVIDIA/NeMo/blob/main/examples/speaker_tasks/recognition/voxceleb_eval.py) script to verify the performance on those unseen speakers.

**Comment by titu1994** [comment]
@nithinraok how about having a method which takes in a list of file paths and does this for you rather than a script ?
