### ISSUE TITLE
Is it possible to use Hugging face XLSR pretrained model with Nemo?

### ISSUE THREAD

**Issue by manjuke** [NVIDIA/NeMo#5686]
Hi 
Is it possible to use Hugging face XLSR pretrained model with Nemo? Thanks.  Pls suggest @titu1994 @jbalam-nv

**Comment by titu1994** [comment]
I don't think it's directly possible. @sam1373 wrote a conversion script but every other Wav2Vec variant changes something so it's not easy to automate

**Comment by manjuke** [comment]
Sure, thanks.
