### ISSUE TITLE
Trainer is required in EncDecRNNTModel

### ISSUE THREAD

**Issue by carlosfranzreb** [NVIDIA/NeMo#5688]
**Describe the bug**

In the constructor of the class `EncDecRNNTModel`, the PTL trainer is a kwarg with default value `null`. However, in the `self.training_step` method, the method `self.log_dict` is called (line 725 in file `collections/asr/models/rnnt_models.py`), which raises an error if no PTL trainer object is present in the `EncDecRNNTModel` object.

**Expected behavior**

If no PTL trainer is passed to the `EncDecRNNTModel`, it should not call `self.log` and just return the logs. The fix is just an if statement before the `self.log_dict`

**Comment by titu1994** [comment]
Trained is optional to initialize the model, but is mandatory to train the model with ptl.Trainer.

**Comment by carlosfranzreb** [comment]
You are right, this only throws an exception on Mac, not on Linux.
