### ISSUE TITLE
Error in downloading the financial_phrase_bank dataset

### ISSUE THREAD

**Issue by farshadsm** [NVIDIA/NeMo#5695]
**Describe the bug**

I was trying to run "tutorials/nlp/Multitask_Prompt_and_PTuning.ipynb". But I got the following error for downloading the "financial_phrase_bank" dataset.

https://www.researchgate.net/profile/Pekka_Malo/publication/251231364_FinancialPhraseBank-v1.0/data/0c96051eee4fb1d56e000000/FinancialPhraseBank-v1.0.zip
Resolving [www.researchgate.net](http://www.researchgate.net/) ([www.researchgate.net](http://www.researchgate.net/))... 104.17.32.105, 104.17.33.105, 2606:4700::6811:2169, ...
Connecting to [www.researchgate.net](http://www.researchgate.net/) ([www.researchgate.net)|104.17.32.105|:443](http://www.researchgate.net%29%7C104.17.32.105%7C:443/)... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-12-21 22:47:57 ERROR 403: Forbidden.

**Steps/Code to reproduce bug**

I tried to download the dataset in both my local machine and Google Colab. But both cases failed. 

**Expected behavior**

I expected the dataset to be downloaded without any error.

**Environment overview (please complete the following information)**

 - Environment location: Colab, MacOS
 - Method of NeMo install: I uploaded the notebook on Colab
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by ericharper** [comment]
In this case you have to download the dataset manually i.e. from your web broswer.
