### ISSUE TITLE
asr报错

### ISSUE THREAD

**Issue by maomao1025** [NVIDIA/NeMo#5697]
**Describe the bug**

调用stt_zh_citrinet_512模型进行音频转文字操作

**Steps/Code to reproduce bug**

asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="stt_zh_citrinet_512")
mandarin_text=asr_model.transcribe(paths2audio_files=["./test.wav"])
print(mandarin_text)**

**Expected behavior**

输出音频文本内容

**Environment overview (please complete the following information)**
安装方式为pip，命令为pip install nemo_toolkit['all']  -i https://pypi.doubanio.com/simple/
**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- torch1.10.0+cu113
- Python 3.8

**Additional context**
报错ValueError: Input signal length=2 is too small to resample from 44100->16000
![image](https://user-images.githubusercontent.com/39375578/209262117-6888b66e-d0b2-4af6-8782-451e325ddf76.png)

**Comment by titu1994** [comment]
Your audio is 2 channel 44100 Hz sample rate. It should be converted to 1 channel 16000 khz

**Comment by maomao1025** [comment]
> 您的音频是 2 通道 44​​100 Hz 采样率。它应该被转换为 1 通道 16000 khz

thank you，problem solved
