### ISSUE TITLE
ModuleNotFoundError: No module named 'nemo.utils.data_utils'

### ISSUE THREAD

**Issue by thani-ath-nain** [NVIDIA/NeMo#5698]
**Describe the bug**

Whenever I try to run the file for tokenization I get the above error.

**Steps/Code to reproduce bug**

Run the command
```
python ./scripts/tokenizers/process_asr_text_tokenizer.py --manifest=../code/manifests/train_clean_5.json --data_root=tokenized --vocab_size=2048 tokenizer=bpe --log
```

**Expected behavior**

It should have tokenized the text manifest.

**Environment overview (please complete the following information)**

 - Environment location: AWS
 - Method of NeMo install: pip install nemo_toolkit['all']
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version Ubutnu 20
- PyTorch version 1.6
- Python version 3.8

**Additional context**

Example: GPU model

**Comment by titu1994** [comment]
You are using the main branch tokenizer script with NeMo that is not installed from main branch - always use stable branch for scripts and tutorials - https://github.com/NVIDIA/NeMo/blob/stable/scripts/tokenizers/process_asr_text_tokenizer.py

**Comment by thani-ath-nain** [comment]
Thank you for your reply. Does that mean I should install nemo as 
```
python -m pip install git+https://github.com/NVIDIA/NeMo.git@stable
```

**Comment by titu1994** [comment]
You don't need to install Nemo main, just use the script from the stable branch should be fine

**Comment by thani-ath-nain** [comment]
Thank you so much. This fixed my issue.
