### ISSUE TITLE
No confidence score for megatron outputs?

### ISSUE THREAD

**Issue by RaiAmanRai** [NVIDIA/NeMo#5701]
**The outputs form the megatron generations has no scoring method**

For megatron models when `model.generate() `function is called, results returned doesn't contain any scores which could give the confidence of generation.

**Here's a code snippet**

```
response = model.generate(inputs=test_examples, length_params=None)
print(response.keys()
```

Is there a way that could validate these generations from model.

**Comment by ericharper** [comment]
Have you tried `all_probs=True`?

**Comment by RaiAmanRai** [comment]
Hi @ericharper thanks for the solution.

However, we would also love to have something like `cumulative_log_probs` that gives the overall scoring too.

Thanks!
