### ISSUE TITLE
Nemo with multiprocessing

### ISSUE THREAD

**Issue by Sasha-Bachynskyi** [NVIDIA/NeMo#5703]
Hello developers.

I have a lot of useful data and would like to retrieve embeddings and get diarization

I thought to use a multiprocessing module to speed up the process. [This module](https://docs.python.org/3/library/multiprocessing.html)
But I failed. If I make a processing pool and add tasks after a while processes stop, and it seems like processes lock themselves
I tried to set up _set_start_method('spawn')_  and it didn't work out, the exception occured

Is there a possibility to use Nemo with a multiprocessing module, has someone had such an experience?

I'll appreciate any help!

**Comment by titu1994** [comment]
I would suggest using fork at all times unless it's not possible for some reason.

**Comment by ericharper** [comment]
We do use NeMo with multi-processing. Could you share the exception?

**Comment by titu1994** [comment]
Btw, if you're saying multiprocessing is stopping, it can be that you are not flushing the subprocess pipes. 

See here for how to get around thatv- 

https://github.com/NVIDIA/NeMo/blob/main/nemo/core/utils/process_launcher/launcher.py#L140-L153 to create a drain thread. 

Then poll with busy waiting on all subprocess to flush their pipes and keep the tasks from overflowing their buffers - https://github.com/NVIDIA/NeMo/blob/main/nemo/core/utils/process_launcher/launcher.py#L261-L292

Finally call proc.communicate() to finish and return the results from the subprocess - https://github.com/NVIDIA/NeMo/blob/main/nemo/core/utils/process_launcher/launcher.py#L294-L302

**Comment by Sasha-Bachynskyi** [comment]
@titu1994 Thank you a lot, your links helped me to implement my own script and it works as I expected, without blocking at all
