### ISSUE TITLE
Can't pull docker image

### ISSUE THREAD

**Issue by RaiAmanRai** [NVIDIA/NeMo#5706]
**Describe the bug**

According to the article by nvidia published [here](https://developer.nvidia.com/blog/deploying-a-1-3b-gpt-3-model-with-nvidia-nemo-megatron/), mentions the use of a couple of docker images 
```
nvcr.io/ea-bignlp/bignlp-training:22.08.01-py3
nvcr.io/ea-bignlp/bignlp-inference:22.08-py3
```
in order to use or inference on LLM. But while pulling the images I am encountering the access denied error.
**This is still the condition even after successfully logging in to nvcr.io**

**Steps/Code to reproduce bug**

docker login nvcr.io
Username: $oauthtoken
Password: <**your SECRET KEY**>
```
docker pull nvcr.io/ea-bignlp/bignlp-training:22.08.01-py3
docker pull nvcr.io/ea-bignlp/bignlp-inference:22.08-py3
```

**Expected behavior**
The docker should start pulling the images.

**Comment by ericharper** [comment]
Thanks for the issue! Did you apply here: https://developer.nvidia.com/nemo-megatron-open-beta? Access should be granted automatically.

**Comment by RaiAmanRai** [comment]
Hi @ericharper , thanks for the clarifoication. I got confused between Nemo Megatron Open Beta and Nemo LLM Early Access.

Can assure, It's working now. 
Thanks
