### ISSUE TITLE
stt_zh_citrinet_1024_gamma_0_25 will not be found in ASRDecoderTimeStamps

### ISSUE THREAD

**Issue by Qxxxx** [NVIDIA/NeMo#5713]
Hi Nemo developers,

**Describe the bug**
I tried to run tutorials/speaker_tasks/ASR_with_SpeakerDiarization.ipynb with chinese data. When I changed the model from `cfg.diarizer.asr.model_path = 'stt_en_conformer_ctc_large'` to `stt_zh_citrinet_1024_gamma_0_25`, the model could not be found correctly because of the logic in  https://github.com/NVIDIA/NeMo/blob/58d6765929d7c13ab933640d74630493957b1dfb/nemo/collections/asr/parts/utils/decoder_timestamps_utils.py#L331-L356.

According to current logic, as `stt_zh_citrinet_1024_gamma_0_25` contains citrinet it will go to 
https://github.com/NVIDIA/NeMo/blob/58d6765929d7c13ab933640d74630493957b1dfb/nemo/collections/asr/parts/utils/decoder_timestamps_utils.py#L350-L356
the `self.encdec_class` will be `EncDecCTCModelBPE`. 

However the `stt_zh_citrinet_1024_gamma_0_25` is listed here.
https://github.com/NVIDIA/NeMo/blob/58d6765929d7c13ab933640d74630493957b1dfb/nemo/collections/asr/models/ctc_models.py#L818-L822
Belongs to `EncDecCTCModel`.

I create a PR(https://github.com/NVIDIA/NeMo/pull/5712) that will not solve the issue but could express my point more clearly.

BRs,
Qxxxx

**Comment by Qxxxx** [comment]
I also tried to move `stt_zh_citrinet_1024_gamma_0_25` to nemo/collections/asr/models/ctc_bpe_models.py (which makes more sense according to my understanding), it seems lack of `tokenizer` which I currently not fully understand what it is.

**Comment by titu1994** [comment]
Citrinet zh is a char based model not a subword based one. It should remain in ctc_models.py

**Comment by Qxxxx** [comment]
Well, then the point of this issue is just show there are some models are not covered by the current logic in decoder_timestamps_utils.py.

**Comment by titu1994** [comment]
Agreed. We focus on subword based models, but we can look into more general solution for the diarization code
