### ISSUE TITLE
Univnet model

### ISSUE THREAD

**Issue by alexandercesarr** [NVIDIA/NeMo#5718]
Hi. I have trained univnet model and I faced 2 issues. 
1. model has memory leak 
2. high response time

I attempt to convert model to onnx but I got this error:
`torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of operator Unfold, input size not accessible. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues [Caused by the value '381 defined in (%381 : Float(*, *, *, strides=[65600, 2050, 1], requires_grad=0, device=cuda:0) = onnx::Pad[mode="constant"](%output, %379, %380), scope: nemo.collections.tts.models.univnet.UnivNetModel::/nemo.collections.tts.modules.univnet_modules.Generator::generator/nemo.collections.tts.modules.univnet_modules.LVCBlock::res_stack.0
`

do you have any idea to fix this problem?Is fixing the memory leak problem on your plan?
@redoctopus

**Comment by redoctopus** [comment]
Hi, sorry--I haven't trained Univnet before and am not really familiar with the model. I don't remember anyone mentioning these issues before, but I can ask around and see if this sounds familiar.

@borisfom, any ideas about the ONNX conversion?

**Comment by alexandercesarr** [comment]
Thank you for your answer. I also tested exporting the model to torchscript, but finally it returns Fail status. But for hifigan, none of these problems exist.
