### ISSUE TITLE
Errors when running first cell in 00_NeMo_Primer in Google Colab

### ISSUE THREAD

**Issue by treyd** [NVIDIA/NeMo#5754]
**Describe the bug**

When running the first cell in tutorials/00_NeMo_Primer.ipynb on Google Colab, I get the following errors:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.9.2 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible.
tensorflow 2.9.2 requires tensorboard<2.10,>=2.9, but you have tensorboard 2.11.0 which is incompatible.
```

I then get FileNotFound exceptions when running later cells trying to import NeMo collections

**Steps/Code to reproduce bug**

1. Click link on https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/starthere/tutorials.html for NeMo Fundamentals
2. Switch Runtime to use GPU Hardware Accelerator 
3. Run first cell

**Expected behavior**

Expected dependencies to import without issue and to be able to go through the rest of the tutorial

**Environment overview (please complete the following information)**

 - Environment location: Collab
 - Method of NeMo install: pip install (specified in notebook with the commands:
 ```BRANCH = 'r1.14.0'
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[all]```

**Environment details**
- Python version 3.8.16

**Additional context**

Seems NeMo wants protobuf<4,>=3.20.2, but tensorflow 2.9.2 wants < 3.20.  Same for tensorboard.

**Comment by treyd** [comment]
I noticed in some of the other tutorial notebooks an instruction to restart the runtime after installing.  I tried doing this on 00_NeMo_Primer after the failure, and the first cell completed successfully.  I was then able to import the collections in the later cell.

This bug can be closed if desired, but would suggest a similar instruction in the notebook about restarting the runtime to continue.

**Comment by titu1994** [comment]
Will add a note
