### ISSUE TITLE
GPU memory leak in nemo asr_model.transcribe()

### ISSUE THREAD

**Issue by mehadi92** [NVIDIA/NeMo#5755]
**Describe the bug**

GPU memory usage increases over the time
![Screenshot from 2023-01-08 23-10-52](https://user-images.githubusercontent.com/104126711/211239138-45bc947c-1910-459f-bd87-ced91070c1cd.png)

**Steps/Code to reproduce bug**

You can reproduce this bug using this notebook [Colab Notebook](https://colab.research.google.com/drive/1PqW0MqVyzCJ53fM1uwGrNvEcsmJN8Q6R?usp=sharing)

You can take any random WAV audio file and make sure you run it for 40 min to 1 hour. The Memory error should reproduce like mine.

**Expected behavior**

Memory usage aways should same after 1st batch processing complete

**Environment overview (please complete the following information)**

Google Colab

**Comment by mehadi92** [comment]
@titu1994, So If anyone only needs the text transcription he can set `return_hypotheses=False`. And this will not return the hypothesis tensor. 

Thanks

**Comment by titu1994** [comment]
There would be too many cases to handle if we removed that. Also, in most cases you do need to get the value of the hypothesis. What we can do is put the tensor on CPU or make it a combination of two flags or something. Fyi @fayejf
