### ISSUE TITLE
TypeError: _run_hydra() missing 1 required positional argument: 'args'

### ISSUE THREAD

**Issue by np-n** [NVIDIA/NeMo#5759]
While training tacotron2, I end up with the following error.

```
    
Traceback (most recent call last):
  File "tacotron2.py", line 44, in <module>
    main()  # noqa pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.8/dist-packages/nemo/core/config/hydra_runner.py", line 98, in wrapper
    _run_hydra(
TypeError: _run_hydra() missing 1 required positional argument: 'args'
[ ]
```
Just before that, I fixed the following issue using this [solution](https://github.com/NVIDIA/NeMo/issues/3915):
```
noqa pylint: disable=no-value-for-parameter File "/usr/local/lib/python3.7/dist-packages/nemo/core/config/hydra_runner.py", line 103, in wrapper strict=None, 

TypeError: _run_hydra() got an unexpected keyword argument 'strict'
```

After removing the argument `strict=None`, I get the above error: `TypeError: _run_hydra() missing 1 required positional argument: 'args'`. How to fix it? Thank you!

**Comment by SeanNaren** [comment]
Seems related: https://github.com/NVIDIA/NeMo/issues/4192

Which version of Hydra are you using? Are you using NeMo main?

**Comment by np-n** [comment]
I am using `hydra-core==1.3.1` and I am using`r1.0.0rc1` branch of `nemo`.

**Comment by SeanNaren** [comment]
I assume there is a reason you're using a very old version of NeMo? If so maybe try installing `hydra-core==1.0.4` which is the minimum version that the release supported: https://github.com/NVIDIA/NeMo/blob/v1.0.0rc1/requirements/requirements.txt

**Comment by np-n** [comment]
@SeanNaren yeah it's fixed when I switch to the latest version of `nemo`. Thank you!
