### ISSUE TITLE
Missing "create_tarred_dataset.py" script for Duplex Text Normalization

### ISSUE THREAD

**Issue by fr0zenshard** [NVIDIA/NeMo#5765]
The script for creation **TarredDataset** described in the [Duplex Text Normalization Doc](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/nlp/text_normalization/nn_text_normalization.html) is missing. 
According to the documentation it should be located: 
`examples/nlp/duplex_text_normalization/create_tarred_dataset.py`

**Comment by yzhang123** [comment]
https://github.com/NVIDIA/NeMo/pull/5773

**Comment by fr0zenshard** [comment]
Thanks! :)
