### ISSUE TITLE
DALI fails in mulit-node setup

### ISSUE THREAD

**Issue by msis** [NVIDIA/NeMo#5779]
**Describe the bug**

In a multi-node setup, DALI pipelines' fail because data is only visible on one node.

**Steps/Code to reproduce bug**

1. Download the data on the main node (rank 0), place it in `/scratch/audio-data`
2. Launch training
3. DALI raises error on other nodes :
`[/opt/dali/dali/operators/reader/loader/nemo_asr_loader.cc:80] Assert on "fstream" failed: Could not open NEMO ASR manifest file: "/scratch/audio-data/manifest.json`

**Expected behavior**

If `ddp` is enabled, DALI should run only on rank 0 node and load the data from there.

**Environment overview (please complete the following information)**

 - Environment location: AWS (HPC)
 - Method of NeMo install: `pip install git+https://github.com/NVIDIA/NeMo.git@9bc1220132cca7ba71550105d98dd12cfc7fefbe#egg=nemo_toolkit[asr]`

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- PyTorch version 1.13.1
- Python version: 3.8.10

**Additional context**

Any other suggestions on how to setup multi-node training are welcome.

**Comment by titu1994** [comment]
Dali needs to read the manifest on all nodes, and build the graph with data for all nodes. Could you explain if the data is mounted on all nodes ? If not, then it will not work cause other nodes will not have access to the manifest and audio files 

Or is this a single node, multi gpu environment and even then other nodes cannot find the manifest file ?

**Comment by msis** [comment]
In single node multi-GPU, all works as expected.

It doesn't work on mutli-node multi-GPU when data is available only for the main node.

**Comment by titu1994** [comment]
Then the data is not being correctly mounted. All nodes need access to the dataset.
