### ISSUE TITLE
Finetune the pretrained nemo model

### ISSUE THREAD

**Issue by GarimaNarang** [NVIDIA/NeMo#5786]
python speech_to_text_ctc_bpe.py --config-path=“/path/to/confiig/file” --config-name=“conformer_ctc_bpe_v13” trainer.max_epochs=50 +init_from_nemo_model=“path/to/stt_hi_conformer_ctc_medium.nemo”

Getting error as shown below:
from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.norm_self_att.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.norm_self_att.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.self_attn.pos_bias_u: copying a param with shape torch.Size([4, 64]) from checkpoint, the shape in current model is torch.Size([8, 64]).
size mismatch for encoder.layers.17.self_attn.pos_bias_v: copying a param with shape torch.Size([4, 64]) from checkpoint, the shape in current model is torch.Size([8, 64]).
size mismatch for encoder.layers.17.self_attn.linear_q.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
size mismatch for encoder.layers.17.self_attn.linear_q.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.self_attn.linear_k.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
size mismatch for encoder.layers.17.self_attn.linear_k.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.self_attn.linear_v.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
size mismatch for encoder.layers.17.self_attn.linear_v.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.self_attn.linear_out.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
size mismatch for encoder.layers.17.self_attn.linear_out.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.self_attn.linear_pos.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
size mismatch for encoder.layers.17.norm_feed_forward2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.norm_feed_forward2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.feed_forward2.linear1.weight: copying a param with shape torch.Size([1024, 256]) from checkpoint, the shape in current model is torch.Size([2048, 512]).
size mismatch for encoder.layers.17.feed_forward2.linear1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([2048]).
size mismatch for encoder.layers.17.feed_forward2.linear2.weight: copying a param with shape torch.Size([256, 1024]) from checkpoint, the shape in current model is torch.Size([512, 2048]).
size mismatch for encoder.layers.17.feed_forward2.linear2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.norm_out.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for encoder.layers.17.norm_out.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
size mismatch for decoder.decoder_layers.0.weight: copying a param with shape torch.Size([129, 256, 1]) from checkpoint, the shape in current model is torch.Size([129, 512, 1]).

Can you please help out with the error?
<img width="947" alt="Screenshot 2023-01-11 at 12 34 53 PM" src="https://user-images.githubusercontent.com/42312456/211971875-1df94c67-82a3-4223-8a6e-8501e1d677c9.png">

**Comment by VahidooX** [comment]
You are trying to load weights from a medium size model into a large model. That is why you get these mismatch errors. The default config file is for a large conformer. You may change the default config file based on the table inside it or extract and save the config file of the medium size pretrained model and then try on that one.
