### ISSUE TITLE
Lexicon support for multiple pronunciations of the same word

### ISSUE THREAD

**Issue by manjuke** [NVIDIA/NeMo#5794]
Hi All,

Does nemo has lexicon support for handling multiple pronunciations of the same word. 

I understand this is supported in Riva framework as mentioned at https://docs.nvidia.com/deeplearning/riva/user-guide/docs/tutorials/asr-python-advanced-customize-vocabulary-and-lexicon.html#customizing-pronunciation-with-lexicon-mapping . But, just wanted to know, is it also supported during normal decoding.

Hi @titu1994 , Is there any further update on https://github.com/NVIDIA/NeMo/issues/2903 ? Whether any functionality is added for offline support than Riva support? Thanks

**Comment by titu1994** [comment]
No, we don't support it as of right now. We're adding Flashlight decoder support soon in #5790 and that does support lexicon based decoding. 

It's a work in progress though. 

Riva is the main streaming inference engine for NeMo models, that is unlikely to change in the near future.

**Comment by manjuke** [comment]
Sure, Thanks. Will check it.
