### ISSUE TITLE
Decoder model [Duplex Text Normalization] train failing, using TarredDataset

### ISSUE THREAD

**Issue by fr0zenshard** [NVIDIA/NeMo#5803]
**Unable to start training Decoder** model **using tarred dataset** obtained from script [create_tarred_dataset.py](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/duplex_text_normalization/data/create_tarred_dataset.py).

The error occurs on the line:
https://github.com/NVIDIA/NeMo/blob/dd921e792427e3788ad9fe3a1e568afc85a8bc93/nemo/collections/nlp/data/text_normalization/decoder_dataset.py#L537

and looks like:

`ValueError: didn't find ['pkl'] in ['__key__', 'tsv-batch-3649.pkl', 'tsv-batch-3650.pkl', 'tsv-batch-3651.pkl', 'tsv-batch-3652.pkl', ....]` (where by "...."  I mean enumeration of other .pkl files).

As I understand it, it would be more correct to do the following in [decoder_dataset.py](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/data/text_normalization/decoder_dataset.py#L537):

1. Obtain every filename with ".pkl" extension and create `pkls` (List). After, create a string like:
```
pkls = ';'.join(pkls)
```

2. Rename as follows (using every key, separated by ";" - **supports by WebDataset**)
```
self._dataset = self._dataset.rename(pkl=pkls, key='__key__').to_tuple('pkl', 'key').map(f=self._build_sample)
```

However, this method also does not allow you to start training.

**Comment by fr0zenshard** [comment]
**upd.** 
train starts, but the pl. trainer (with this fix) calculates the wrong number of steps

**Comment by yzhang123** [comment]
> **upd.** train starts, but the pl. trainer (with this fix) calculates the wrong number of steps

Thanks for the follow up. could you be more specific on which number is wrong? Maybe add a log file, or point to a code line?

**Comment by fr0zenshard** [comment]
@yzhang123 Hello! I know about batch size. But this's looks like:
```
Epoch 0:   0%|                                                                                                                                                 | 0/73015 [00:00<?, ?it/s][W reducer.cpp:1298] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
Epoch 0:   1%|█▎                                                                                                  | 957/73015 [02:21<2:57:34,  6.76it/s, loss=0.987, v_num=, lr=0.000199][NeMo W 2023-01-19 10:23:40 nemo_logging:349] /opt/conda/lib/python3.8/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:381: UserWarning: `ModelCheckpoint(monitor='val_loss')` could not find the monitored key in the returned metrics: ['train_loss', 'lr', 'train_backward_timing', 'train_step_timing', 'epoch', 'step']. HINT: Did you call `log('val_loss', value)` in the `LightningModule`?
      warning_cache.warn(m)

Epoch 0, global step 957: 'val_loss' was not in top 3
Epoch 1:   1%|█▎                                                                                                  | 964/73015 [02:31<3:08:30,  6.37it/s, loss=0.752, v_num=, lr=0.000198]
Epoch 1, global step 1921: 'val_loss' was not in top 3
Epoch 2:   1%|█▎                                                                                                  | 965/73015 [02:30<3:07:50,  6.39it/s, loss=0.403, v_num=, lr=0.000197]
Epoch 2, global step 2886: 'val_loss' was not in top 3
`Trainer.fit` stopped: `max_epochs=3` reached.
Epoch 2:   1%|█▎                                                                                                  | 965/73015 [02:37<3:15:33,  6.14it/s, loss=0.403, v_num=, lr=0.000197]
[NeMo W 2023-01-19 10:29:07 exp_manager:875] <nemo.utils.exp_manager.NeMoModelCheckpoint object at 0x7fd30d265130> was told to save the best checkpoint at the end of training, but no saved checkpoints were found. Saving latest model instead.
[NeMo I 2023-01-19 10:29:14 duplex_tn:121] Training finished!
```

And what about first bug, which i mentioned first (about "pkl" load)?

**Comment by fr0zenshard** [comment]
@yzhang123 If I understand correctly - pl.Trainer shows iterating over *.tar files. When I tried to start train with 2 tar files, there was maximum of 2 "steps". But overall steps (as I understand, again) showing every example in the dataset. So, with this process we can't train correctly because of "val_loss" and etc. So, can you fix this bug or idk...

**Comment by fr0zenshard** [comment]
@yzhang123 Hi! Any updates?

**Comment by yzhang123** [comment]
@fr0zenshard , the steps you see are the batches, your log shows it's going beyond 2 steps so looks alright? When i tested it was alright for me. Pls only look at `global step` since the progress bar includes both training and validation

**Comment by yzhang123** [comment]
> **Unable to start training Decoder** model **using tarred dataset** obtained from script [create_tarred_dataset.py](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/duplex_text_normalization/data/create_tarred_dataset.py).
> 
> The error occurs on the line:
> 
> https://github.com/NVIDIA/NeMo/blob/dd921e792427e3788ad9fe3a1e568afc85a8bc93/nemo/collections/nlp/data/text_normalization/decoder_dataset.py#L537
> 
> and looks like:
> 
> `ValueError: didn't find ['pkl'] in ['__key__', 'tsv-batch-3649.pkl', 'tsv-batch-3650.pkl', 'tsv-batch-3651.pkl', 'tsv-batch-3652.pkl', ....]` (where by "...." I mean enumeration of other .pkl files).
> 
> As I understand it, it would be more correct to do the following in [decoder_dataset.py](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/data/text_normalization/decoder_dataset.py#L537):
> 
> 1. Obtain every filename with ".pkl" extension and create `pkls` (List). After, create a string like:
> 
> ```
> pkls = ';'.join(pkls)
> ```
> 
> 2. Rename as follows (using every key, separated by ";" - **supports by WebDataset**)
> 
> ```
> self._dataset = self._dataset.rename(pkl=pkls, key='__key__').to_tuple('pkl', 'key').map(f=self._build_sample)
> ```
> 
> However, this method also does not allow you to start training.

This looks like something is corrupt with your tar files. Could you check in the tar dataset dir: there should be 
1. metadata.json
2. *.tar files with the format tn.<batch_size>_bs.<number_of_pkl_file_per_tar>_b_per_tar.80_len.<tar_index>.tar
3. when you untar, you should get <number_of_pkl_file_per_tar> .pkl files of the format tmp-batch-<index>.pkl
4. when you unpickle, with pickle.load(open(tmp-batch-<index>.pkl, 'rb')) this object should have key values with the keys 
['input_ids', 'attention_mask', 'input_center', 'direction', 'semiotic_class_id', 'decoder_input_ids', 'labels']

could you pls check this is the case?

**Comment by fr0zenshard** [comment]
> > **Unable to start training Decoder** model **using tarred dataset** obtained from script [create_tarred_dataset.py](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/duplex_text_normalization/data/create_tarred_dataset.py).
> > The error occurs on the line:
> > https://github.com/NVIDIA/NeMo/blob/dd921e792427e3788ad9fe3a1e568afc85a8bc93/nemo/collections/nlp/data/text_normalization/decoder_dataset.py#L537
> > 
> > and looks like:
> > `ValueError: didn't find ['pkl'] in ['__key__', 'tsv-batch-3649.pkl', 'tsv-batch-3650.pkl', 'tsv-batch-3651.pkl', 'tsv-batch-3652.pkl', ....]` (where by "...." I mean enumeration of other .pkl files).
> > As I understand it, it would be more correct to do the following in [decoder_dataset.py](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/data/text_normalization/decoder_dataset.py#L537):
> > 
> > 1. Obtain every filename with ".pkl" extension and create `pkls` (List). After, create a string like:
> > 
> > ```
> > pkls = ';'.join(pkls)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Rename as follows (using every key, separated by ";" - **supports by WebDataset**)
> > 
> > ```
> > self._dataset = self._dataset.rename(pkl=pkls, key='__key__').to_tuple('pkl', 'key').map(f=self._build_sample)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, this method also does not allow you to start training.
> 
> This looks like something is corrupt with your tar files. Could you check in the tar dataset dir: there should be
> 
> 1. metadata.json
> 2. *.tar files with the format tn.<batch_size>_bs.<number_of_pkl_file_per_tar>_b_per_tar.80_len.<tar_index>.tar
> 3. when you untar, you should get <number_of_pkl_file_per_tar> .pkl files of the format tmp-batch-.pkl
> 4. when you unpickle, with pickle.load(open(tmp-batch-.pkl, 'rb')) this object should have key values with the keys
>    ['input_ids', 'attention_mask', 'input_center', 'direction', 'semiotic_class_id', 'decoder_input_ids', 'labels']
> 
> could you pls check this is the case?
> 
> could you also provide what the configuration is for create_tarred_dataset? how many input_files, how many lines each, max_seq_length, batch_size, num_batches_per_tarfile, factor

1-2 same.
3. When I untar, I've folder tree (which duplicates original path to the files). In the last folder I've output-<num>-of-<...>.tsv-batch-<batch number>.pkl files
4. Same, too. 
```
dict_keys(['input_ids', 'attention_mask', 'input_center', 'direction', 'semiotic_class_id', 'decoder_input_ids', 'labels'])
```

About configuration:
```
python create_tarred_dataset.py \
        --input_files="<full_path>/output-00000-of-00100.tsv" \
        --input_files="<full_path>/output-00001-of-00100.tsv" \
        --input_files="<full_path>/output-00002-of-00100.tsv" \
        --lang="ru" \
        --transformer_name="cointegrated/rut5-base" \
        --n_jobs=22 \
        --factor=1000 \
        --num_batches_per_tarfile=64 \
        --batch_size=64 \
        --out_dir="<save_path>/google_tn_tarred_ru_0-22"
```

**Comment by yzhang123** [comment]
Oh you are using russian, we only tested on English. @ekmb is there anything you can see what the problem is?

**Comment by fr0zenshard** [comment]
@yzhang123 yep... so if @ekmb can give some advice, that'll be great :)

**Comment by fr0zenshard** [comment]
@yzhang123 @ekmb Hi! Any information?
