### ISSUE TITLE
Script to fine-tune a pretrained NMT model

### ISSUE THREAD

**Issue by joncamgui** [NVIDIA/NeMo#5811]
Documentation is very clear on how to train from scratch but I cannot find how to fine-tune one of the available models https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/nlp/machine_translation/machine_translation.html

Could you provide some insights or an example doing that?

Thanks,

**Comment by okuchaiev** [comment]
once you have a pre-trained model's .nemo file, just use .restore_from(...) to initialize model's weights with it.

**Comment by MaximumEntropy** [comment]
We do have a script here to fine-tune those models - https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/machine_translation/enc_dec_nmt_finetune.py. @aklife97 do you know if this script is documented somewhere?
