### ISSUE TITLE
possible bug in neural_modules.py

### ISSUE THREAD

**Issue by kansalaman** [NVIDIA/NeMo#582]
While running `NeMo/examples/asr/jasper_eval.py`, doing beam search with lm, there is an error at

`beam_search_with_lm = nemo_asr.BeamSearchDecoderWithLM(
                    vocab=vocab,
                    beam_width=args.beam_width,
                    alpha=alpha,
                    beta=beta,
                    lm_path=args.lm_path,
                    num_cpus=max(os.cpu_count(), 1),
                    input_tensor=False,
                )`

The trace as it comes is -

`File "/mnt/blossom/data/amankansal/HLS4Speech/NeMo/nemo_venv/lib/python3.6/site-packages/nemo/collections/asr/beam_search_decoder.py", line 76, in __init__
    super().__init__()
  File "/mnt/blossom/data/amankansal/HLS4Speech/NeMo/nemo_venv/lib/python3.6/site-packages/nemo/backends/pytorch/nm.py", line 134, in __init__
    NeuralModule.__init__(self)  # For NeuralModule API
  File "/mnt/blossom/data/amankansal/HLS4Speech/NeMo/nemo_venv/lib/python3.6/site-packages/nemo/core/neural_modules.py", line 70, in __init__
    self._placement = self._factory.placement
`

This error seems valid because in `NeMo/nemo/core/neural_modules.py` at line `67`, self._factory is assigned as `NeuralModuleFactory.get_default_factory()` which is `None`. In the next line `self._factory.placement` is used. Can someone please confirm whether this is a bug or am I missing something. If the latter how to get around this?

Thanks in advance!

**Comment by okuchaiev** [comment]
did you create NeuralModuleFactory before your neural modules? Could you please post the script which causes an error and full error log?

**Comment by kansalaman** [comment]
I did not make a NeuralModuleFactory before the module. That seems to have solved the issue. Thanks @okuchaiev.
