### ISSUE TITLE
Nemo ASR training: Unable to get/save best top n checkpoints, and exp_dir not setting

### ISSUE THREAD

**Issue by manjuke** [NVIDIA/NeMo#5828]
Hi All,

The expdir and save_top_k under exp_manager are not working as expected. 

1. "expdir" is getting created, but nothing is being written. I tried setting logger to False, even then nothing is being written to "expdir".

2. Always only the last checkpint is saved irrespective of "save_top_k" value. And, only one checkpoint is save, and it is not the best.
In addition, setting these values in config files. I am passing them during training as below:

expdir = '/data/manju/tamil/exp/logs/expDir'
params['exp_manager']['exp_dir'] = expdir
params['exp_manager']['save_top_k'] = 6

Pls suggest @titu1994 . Thanks

**Comment by titu1994** [comment]
You can compare your exp manager config to the tutorials of ASR, they should be set and applied to PTL trainer
