### ISSUE TITLE
Unnecessary rng shuffle in x-denoiser sample generation

### ISSUE THREAD

**Issue by dlwh** [NVIDIA/NeMo#5832]
I recognize there's a lot of copy-pasta from the classic t5 denoising function, but this shuffle is unnecessary, or there's a bug

https://github.com/NVIDIA/NeMo/blob/b69f61d4c05ce7ee35d1474025998ca6e5c20d72/nemo/collections/nlp/data/language_modeling/megatron/dataset_utils.py#L497

no big deal, just thought I'd flag

**Comment by MaximumEntropy** [comment]
Thanks for catching this! I'll send a PR to fix it. Yeah, the denoising function for T5 and BERT are shared right now so I figured I'd remove the BERT bits since it was making the code a little hard to read.
