### ISSUE TITLE
torch.jit

### ISSUE THREAD

**Issue by e871** [NVIDIA/NeMo#5835]
Can the conformer model export to torch.jit?

**Comment by e871** [comment]
I have tried to to_torchscript. but doesnt work

**Comment by titu1994** [comment]
What is "to_torchscript"? The export guide docs - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/core/export.html

**Comment by csukuangfj** [comment]
> What is "to_torchscript"? The export guide docs - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/core/export.html

The guide is outdated, I am afraid.

For instance, the guide says the following:
![Screenshot 2023-03-09 at 11 32 55](https://user-images.githubusercontent.com/5284924/223909950-1d7763ce-0639-4c2a-a435-3987a597af36.png)

The latest code is
https://github.com/NVIDIA/NeMo/blob/6b3d0fe2b5fc2c3b1f83a465d1ca55a530c32e30/nemo/core/classes/exportable.py#L51-L63

---

By the way, there is no documentation for the latest code at all. Zero comment for it in the code.

**Comment by titu1994** [comment]
We can add some comments to the code, but the link above is the documentation. 

In most cases you won't need any of the above args - just run model.export("filename.ts") and that should be it. 

It can be seen here - https://github.com/NVIDIA/NeMo/blob/main/scripts/export.py#L152

Most of the args are boiler plate to do checks and assertions that the output matches the model output post export modifications.
