### ISSUE TITLE
Missing documentation for EncDecRNNTModel.transcribe

### ISSUE THREAD

**Issue by yks72p** [NVIDIA/NeMo#5838]
https://github.com/NVIDIA/NeMo/blob/0336b8dad4fa63880e3b15805829f0a9d8057363/nemo/collections/asr/models/rnnt_models.py#L238

There is no clear statement on return types of `EncDecRNNTModel.transcribe()` method. The text seems to be clipped (sentence is not completed)

**Comment by titu1994** [comment]
I can send a fix later this week. It can return a List[Hypothesis] object if you pass return_hypotheses=True to transcribe
