### ISSUE TITLE
KeyError : No AudioToMelSpectrogramPreprocessor in 2_Online_ASR_Microphone_Demo.ipynb

### ISSUE THREAD

**Issue by Ierezell** [NVIDIA/NeMo#585]
- Wanted behaviour : 
Run the notebook following given instructions 

- Actual Behaviour :
In `model_definition['AudioToMelSpectrogramPreprocessor']['dither'] = 0`
`KeyError: 'AudioToMelSpectrogramPreprocessor'`

There is no field `AudioToMelSpectrogramPreprocessor` in the yaml, thus all the subfields leads to error (same for `model_definition['AudioToMelSpectrogramPreprocessor']['features']`,
`model_definition['AudioToMelSpectrogramPreprocessor']['pad_to']`)

- Checkpoints taken from the comment in the notebook :
the checkpoints are available from NGC: https://ngc.nvidia.com/catalog/models/nvidia:quartznet15x5

(tried with other files as well with no success)

**Comment by redoctopus** [comment]
Looks like the checkpoint has an older version of the quartznet15x5 config, and the class name has changed. Either one of the following should fix the error:
1. Use the config at `examples/asr/configs/quartznet15x5.yaml`, or
2. Change the key `AudioPreprocessing` to `AudioToMelSpectrogramPreprocessor` in the YAML file you are currently using.

**Comment by Ierezell** [comment]
Thanks for the quick response ! 

Fixed by taking the config from github, the notebook is working (still have a pulseaudio bug on my side).
