### ISSUE TITLE
Initialize MegatronBertModel

### ISSUE THREAD

**Issue by linqian66** [NVIDIA/NeMo#5858]
I would like to initialize a **MegatronBertModel** instead of **TextClassificationModel**, for a classification task. Basically I need to use MegatronBERT based model and tokenizer. I did not find any corresponding config file, how do I configure the YAML config file to achieve this?

Something like this:
```
config = OmegaConf.load(yaml_config)
config.model.language_model.pretrained_model_name = 'biomegatron345m_biovocab_50k_cased'
trainer = pl.Trainer(**config.trainer)
lmodel = MegatronBertModel(config.model, trainer)
```

**Comment by pranav-nair-rit** [comment]
Hey @linqian66,
Did you check inside `NeMo/examples/nlp/language_modeling/conf/`? There you should be able to find a configuration file called `megatron_bert_config.yaml`. I believe looking at the steps you have enlisted above, it seems the right way to configure the config.
