### ISSUE TITLE
Voice_Activity_Detection.ipynb tutorial is broken

### ISSUE THREAD

**Issue by Aynes** [NVIDIA/NeMo#5868]
**Voice_Activity_Detection.ipynb tutorial is broken**

If you open file: 
https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Voice_Activity_Detection.ipynb

it will give an error:
**"Invalid Notebook"**
**"The Notebook Does Not Appear to Be Valid JSON"**

**Comment by titu1994** [comment]
Should be fixed via https://github.com/NVIDIA/NeMo/pull/5862
