### ISSUE TITLE
Update `isort` to the latest version

### ISSUE THREAD

**Issue by artbataev** [NVIDIA/NeMo#5893]
**Is your feature request related to a problem? Please describe.**

NeMo currently requires a very old version of `isort` (<5). The latest version is 5.10.1

Benefits of supporting the latest `isort`:
- latest version => improved support, fewer bugs, etc
- no conflicts with new repos, more friendly for new developers
- explicit config instead of hard-coded options in setup.py
- it is possible to use the `isort` executable instead of a custom command from `setup.py`

**Describe the solution you'd like**

Update `isort` to the latest version.
Use updated config parameters (for `black` support).

**Cost of change:**
~35 files will be changed (the new version is a bit more restrictive)

**Describe alternatives you've considered**

...

**Additional context**

...

**Comment by artbataev** [comment]
@ericharper, @SeanNaren, @titu1994, @okuchaiev this is an issue to discuss the update. If we agree it's ok, I will provide a PR

**Comment by SeanNaren** [comment]
Could you open up the PR so we can see what the changes are? I'm happy with this change imo.

**Comment by artbataev** [comment]
Done in #5895
