### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go

### ISSUE THREAD

**Issue by DennisFaucher** [NVIDIA/NeMo#590]
Running the instructions at https://nvidia.github.io/NeMo/index.html#installation on my Jetson Xavier. git cloned the repository into $HOME/external. This command led to this error. TIA

sudo docker run --gpus all -it --rm -v $HOME/external/NeMo:/NeMo --shm-size=8g -p 8888:8888 -p 6006:6006 --ulimit memlock=-1 --ulimit stack=67108864 nvcr.io/nvidia/nemo:v0.10

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=all --compute --utility --video --require=cuda>=9.0 --pid=12248 /var/lib/docker/overlay2/4e1768b417381f9cc9e00f674e73d8f484e385a46d53b3d4cf95c0b6a9abe7ce/merged]\\\\nnvidia-container-cli: mount error: mount operation failed: /usr/src/tensorrt: no such file or directory\\\\n\\\"\"": unknown.

**Comment by okuchaiev** [comment]
Are you able to run this image "nvcr.io/nvidia/pytorch:20.01-py3" (you'll need to do "pip install nemo_toolkit[asr]" inside it?

**Comment by DennisFaucher** [comment]
@okuchaiev is this container meant for aarch64? I pull the container fine but get an error when running. TIA

$ sudo docker run -it  nvcr.io/nvidia/pytorch:20.01-py3 /bin/bash
standard_init_linux.go:211: exec user process caused "exec format error"
