### ISSUE TITLE
[TN][zh]Cardinal support for '幺‘ ’两‘

### ISSUE THREAD

**Issue by npuichigo** [NVIDIA/NeMo#5906]
For example, 110 -> 幺幺零 and 2000块 -> 两千块

**Comment by yzhang123** [comment]
@BuyuanCui could you please handle this?

**Comment by BuyuanCui** [comment]
Zh-TN is in-progress. I would pay attention to them. 
1. "110" seems like the phone number class, which is not covered for now, but would definitely add them in future updates.
2. The money class "2000块"; I would have it covered.

**Comment by yzhang123** [comment]
> Zh-TN is in-progress. I would pay attention to them.
> 
> 1. "110" seems like the phone number class, which is not covered for now, but would definitely add them in future updates.
> 2. The money class "2000块"; I would have it covered.

another suggestion is to add 110 to undeterministic graph, so we can use it for audio based normalization

**Comment by yzhang123** [comment]
@npuichigo for you information, we have moved the development of TN/itN to a separate repo https://github.com/NVIDIA/NeMo-text-processing , and are currently in the process of removing the stale code from this repo.

**Comment by BuyuanCui** [comment]
> 

Would work on it.

**Comment by BuyuanCui** [comment]
Adding to "110" normalization:
The issue regarding the normalization of 110 would be covered by either developing un-deterministic Cardinal grammar (digits) or by updating a new class as phone number (assuming "110" as the phone number).

**Comment by BuyuanCui** [comment]
My apologies.
Zh_tn 1.0 is coming soon and it would cover the cases like "4块". The digits might be taking a while. The reason is that I might need to work on JP and KR in near future. Let me confirm with Tobi to see if he has any plans.
