### ISSUE TITLE
FilterbankFeaturesTA imcompatible with FilterbankFeatures

### ISSUE THREAD

**Issue by msis** [NVIDIA/NeMo#5912]
The new `FilterbankFeaturesTA` does not use the same naming convention as `FilterbankFeatures`.
This leads to errors when using the `FilterbankFeaturesTA` in a model. 

For instance here: https://github.com/NVIDIA/NeMo/blob/ddb92e319e9e3aa7b2db7e58b25810a71a4c2cc7/nemo/collections/asr/models/ctc_models.py#L160-L161

While `FilterbankFeatures` defines those attributes, `FilterbankFeaturesTA` uses different naming:
https://github.com/NVIDIA/NeMo/blob/ddb92e319e9e3aa7b2db7e58b25810a71a4c2cc7/nemo/collections/asr/parts/preprocessing/features.py#L540-L541

**Comment by titu1994** [comment]
Oh thank you for raising this, and also for the PR. Very nice catch. I'd ideally like to have a ci test for Torchaudio stuff, but until our containers include it as part of the Nvidia pytorch container it will be challenging.
