### ISSUE TITLE
3 post-processing layer of Jasper

### ISSUE THREAD

**Issue by pooyafayyaz** [NVIDIA/NeMo#592]
Hello all,
I was reading the Jasper paper and I realized that there are 3 layers for post-processing after the B*R layers, I understand that the last layer does something like softmax and it reduces the features to phonemes. but I can't understand what are the 2 previous layers and why the values are such as the paper described. 
I'm going to drop these three layers for sentiment analysis, Is it right to assume that the output of the B*R CNN's is the speech features?

**Comment by blisc** [comment]
The first layer has a dilation of 2 which increases receptive field.
The second layer is just a fully-connected layer, which from my opinion, just feels right to have. No hard science for or against this layer.

If you are interested in using it as an audio feature extractor, I would recommend including those 2 layers, and dropping the last one.
