### ISSUE TITLE
gc not imported

### ISSUE THREAD

**Issue by profgandhi** [NVIDIA/NeMo#5923]
**Describe the bug**

https://github.com/NVIDIA/NeMo/tree/main/nemo/collections/asr/parts/utils)/speaker_utils.py

In this file gc is not imported, therefore while performing clustering without cuda, its showing error that gc is not imported

**Steps/Code to reproduce bug**

By adding import statement we can fix the bug

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by nithinraok** [comment]
I see it is imported here https://github.com/NVIDIA/NeMo/blob/0e70135ccf24d882dcdc549321e747199a232bdf/nemo/collections/asr/parts/utils/speaker_utils.py#L15
