### ISSUE TITLE
Getting acoustic model probabilities form ctc beam search decoder 

### ISSUE THREAD

**Issue by robflynnyh** [NVIDIA/NeMo#5924]
Hey, I've been using the beam BeamSearchDecoderWithLM module which returns a combined score of AM + bpe-ngram, and basically, I need acoustic model probabilities for each hyp to use downstream.
I *think* this would be a correct way to obtain them but just wanted to double check

-(kenlm.score(encoded_text) * alpha - score + encoded_length * beta)
which would be using the same ngram used for decoding to re-obtain seperate n-gram probs

**Comment by titu1994** [comment]
Score here is the result of the beam ? Ignoring the outer negative here, score is calculated as AM + alpha * kenlm.score(encoded text) + beta * encoded seq len 

While you can subtract the alpha part easily, how will you determine the text seq len? For the beta part you need to be careful to count the length of subword not characters. If you subtract both you should get back AM score

**Comment by titu1994** [comment]
Fyi @VahidooX for any further info

**Comment by robflynnyh** [comment]
Great yes, thank you for confirming!
