### ISSUE TITLE
how to speedup nemo infer?

### ISSUE THREAD

**Issue by laohur** [NVIDIA/NeMo#595]
float16.
tensorrt, triton?
torchscript ro torchserve?
onnx runtime?
streamer-service?  (collect requests to batch)

**Comment by okuchaiev** [comment]
are you talking about speeding up training? Then using amp_opt levels of O1 or O2 should help. But in that case your hardware should support TensorCores (e.g. Volta or Turing GPUs)

**Comment by laohur** [comment]
> 
> 
> are you talking about speeding up training? Then using amp_opt levels of O1 or O2 should help. But in that case your hardware should support TensorCores (e.g. Volta or Turing GPUs)

Oh, it is infer, how to be much more faster?
