### ISSUE TITLE
Speaker Diarization WinError: 'The filename or extension is too long'

### ISSUE THREAD

**Issue by JB0207** [NVIDIA/NeMo#5958]
Hi everyone,

when I run the following tutorial on my Windows 10 PC (Python 3.10.5): https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/ASR_with_SpeakerDiarization.ipynb

Then I get at the step "Run diarization with the extracted word timestamps":
`diar_hyp, diar_score = asr_diar_offline.run_diarization(cfg, word_ts_hyp)`
`print("Diarization hypothesis output: \n", diar_hyp['an4_diarize_test'])`

An error message stating that the name of the automatically created output folder is too long:
`vad: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]
[NeMo I 2023-02-07 21:01:01 clustering_diarizer:258] Converting frame level prediction to speech/no-speech segment in start and end times format.
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\XXXXX\\Desktop\\Audio_files\\data\\vad_outputs\\table_output_tmp_window_length_in_sec0.63_shift_length_in_sec0.01_smoothingFalse_overlap0.5_onset0.9_offset0.5_pad_onset0_pad_offset0_min_duration_on0_min_duration_off0.6_filter_speech_firstTrue_'`

Is there a way to alter the name of this output folder?

With Google Colab in conjunction with Google Drive, the long name of the output folder does not matter and everything is working fine. 

Thank you in advance for your help!

**Comment by tango4j** [comment]
@fayejf Can you give a pointer for setting `path2_vad_pred`? We can modify this to have a shorter folder name.

**Comment by fayejf** [comment]
here [table_out_dir_name](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/utils/vad_utils.py#L718 ). Agree, it's just for postprocessing parameters experiment and there is no need to stick to that way

**Comment by tango4j** [comment]
@fayejf 
Probably we can use hash as temporary folder name reflecting the parameters?
[table_out_dir_name](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/asr/parts/utils/vad_utils.py#L718)

```python
import hashlib
hash_object = hashlib.md5(b'Hello World')
print(hash_object.hexdigest()[-8:])
```
But we can also use really short name if duplication is not an issue.
