### ISSUE TITLE
Nemo_TTS. Reached max decoder steps.

### ISSUE THREAD

**Issue by dmitrytyrin** [NVIDIA/NeMo#596]
Dear team!
During training tacotron2 I get "Reached max decoder steps 1000" message.
Is it critical for training?

I train on non-english dataset ~28h, audios are longer that 1 and shorter than 10 seconds. All sentences have !/./? in the end.
I tried to increase ```max_decoder_steps``` and decrease ``` gate_threshold``` in yaml file but it did not help.

**Comment by blisc** [comment]
Max decoder steps is only used during evaluation and inference. It is normal to see the warning message at the beginning of training. However, it should go away once the model has learned attention.

**Comment by dmitrytyrin** [comment]
Thank you very much!
One more question: at what picture of alignment (test or train) I should get bright diagonal line?

**Comment by blisc** [comment]
You should get it on both train and test.

**Comment by dmitrytyrin** [comment]
Thanks!
