### ISSUE TITLE
The hyperlink to the examples page is wrong

### ISSUE THREAD

**Issue by bvsnaidu** [NVIDIA/NeMo#5965]
**Describe the bug**

The hyperlink to the examples page is unfortunately pointed at update_readme_into branch(which does not exist anymore) instead of the main branch

**Steps/Code to reproduce bug**

Click on the hyperlink in 
For advanced users that want to train NeMo models from scratch or finetune existing NeMo models we have a full suite of [example scripts](https://github.com/NVIDIA/NeMo/tree/update_readme_into/examples) that support multi-GPU/multi-node training.

**Expected behavior**

Should link to (https://github.com/NVIDIA/NeMo/examples) i think

**Comment by titu1994** [comment]
> The hyperlink to the examples page is unfortunately pointed at update_readme_into branch(which does not exist anymore) instead of the main branch

In which file / folder is this referring to ?

**Comment by bvsnaidu** [comment]
The README introduction section paragraph 5

**Comment by titu1994** [comment]
Oh thank you ! I think it was fixed earlier today.
