### ISSUE TITLE
Results differ for different codecs and bitrate

### ISSUE THREAD

**Issue by skanda1005** [NVIDIA/NeMo#5973]
**Describe the bug**

I am getting different diarization results when I modify the codec and bitrate of a video and then convert that into an audio file.

**Steps/Code to reproduce bug**

Take any yt video
Download in 2 different resolutions(1080p and 480p)
Convert into audio file and run speaker diarization.
Now, convert the lower res video into MPEG4 format using ffmpeg -i <inputfile> <outputfile>
Results for this will change
Manipulating codec will also change results

**Expected behavior**

Same results always or always increasing bitrate should give better resuts

**Comment by nithinraok** [comment]
Thanks for the bug. 

These are valid questions but the codec, and quality of audio does affect the output embeddings and hence in turn show its effect on clustering. Hopefully, future TitaNet models would not show much differentiability wrt acoustic variations.
