### ISSUE TITLE
[ASR] Training ZeroDivisionError: float division by zero while precision is 16

### ISSUE THREAD

**Issue by shihabtechno** [NVIDIA/NeMo#5998]
**Set Precision 16 for fast training**

Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.0
Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 0.0
and it gives 
ZeroDivisionError: float division by zero
**Pytorch Lighting Parameters**

devices=-1,  # number of GPUs, -1 would use all available GPUs
strategy='ddp',
amp_level='O1',
precision=16,  
amp_backend='apex'

**Learning Rate 1**

error
`File "/usr/local/lib/python3.8/dist-packages/apex/amp/scaler.py", line 176, in unscale_with_stashed
    out_scale/grads_have_scale,   # 1./scale,
ZeroDivisionError: float division by zero
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.`

**Additional context**

- Nemo Docker version nemo:22.12
- Multi GPU

**Comment by titu1994** [comment]
Apex fp16 is no longer the default and is not recommended to use. Please switch to native amp

**Comment by shihabtechno** [comment]
@titu1994 Thanks for your quick response.Will this Apex fp16 available in future?

**Comment by titu1994** [comment]
No it has been deprecated. You can use amp in pytorch 1.10 and above which is the correct way to use fp16 (mixed precision) training by setting trainer.precision=16 in yaml config.

**Comment by shihabtechno** [comment]
@titu1994 Thanks for your support.
