### ISSUE TITLE
Qurtznet, inference high deviation after onnx export

### ISSUE THREAD

**Issue by WuSu4620** [NVIDIA/NeMo#6000]
Tried to export quartznet encoder with onnx. 
Compered inference result with the same input tensor. 
Found unexplainably high  deviations between the original and exported model inference results.

```
import onnx
from onnx import checker
import onnxruntime
import torch
import nemo
import nemo.collections.asr as nemo_asr
import librosa
import numpy as np


quartznet = nemo.collections.asr.models.EncDecCTCModel.restore_from('QuartzNet5x5LS-En.nemo').to('cpu').eval()

audio, sample_rate = librosa.load('/an4/wav/an4_clstk/mgah/cen2-mgah-b.wav', sr=16e3)
audio_torch = torch.Tensor(audio[np.newaxis])
audio_torch_len = torch.Tensor([audio_torch.shape[1]])

processed_signal, processed_signal_length = quartznet.preprocessor(input_signal=audio_torch, length=audio_torch_len)
encoded_direct = quartznet.encoder(audio_signal=processed_signal, length=processed_signal_length)

quartznet.encoder.export('qn_enc.onnx')
ort_session_encoder = onnxruntime.InferenceSession('qn_enc.onnx')

ort_inputs_encoder = {ort_session_encoder.get_inputs()[0].name: processed_signal.numpy(),
                                        ort_session_encoder.get_inputs()[1].name: processed_signal_length.numpy()}

ologits_enc = ort_session_encoder.run(None, ort_inputs_encoder)


np.testing.assert_allclose(encoded_direct[0].detach().numpy(), ologits_enc[0], rtol=1e-02, atol=1e-02)
# raises:
# AssertionError: 
# Not equal to tolerance rtol=0.01, atol=0.01

# Mismatched elements: 32002 / 139264 (23%)
# Max absolute difference: 5.5700774
# Max relative difference: 6858.9634

```
Expected the differences to be much smaller (less then 1e-4)

If i try to export the whole model (includes encoder + decoder), as suggested in the comments, the differences become even bigger :

```
import onnx
from onnx import checker
import onnxruntime
import torch
import nemo
import nemo.collections.asr as nemo_asr
import librosa
import numpy as np


quartznet = nemo.collections.asr.models.EncDecCTCModel.restore_from('QuartzNet5x5LS-En.nemo').to('cpu').eval()

audio, sample_rate = librosa.load('/an4/wav/an4_clstk/mgah/cen2-mgah-b.wav', sr=16e3)
audio_torch = torch.Tensor(audio[np.newaxis])
audio_torch_len = torch.Tensor([audio_torch.shape[1]])

processed_signal, processed_signal_length = quartznet.preprocessor(input_signal=audio_torch, length=audio_torch_len)
encoded_direct = quartznet.encoder(audio_signal=processed_signal, length=processed_signal_length)
decoder_direct = quartznet.decoder(encoder_output=encoded_direct[0])

quartznet.export('qn.onnx')
ort_session = onnxruntime.InferenceSession('qn.onnx')

ort_inputs = {ort_session.get_inputs()[0].name: processed_signal.numpy()}
ologits = ort_session.run(None, ort_inputs)

np.testing.assert_allclose(decoder_direct.detach().numpy(), ologits[0], rtol=1e-02, atol=1e-02)

#raises:
#AssertionError: 
#Not equal to tolerance rtol=0.01, atol=0.01

#Mismatched elements: 1593 / 3944 (40.4%)
#Max absolute difference: 12.401756
#Max relative difference: 47469.176



```

package versions:
torch                             1.13.1
onnxruntime               1.12.1
nemo-toolkit               1.13.0

**Comment by titu1994** [comment]
We don't normally export just the encoder like that so it's not recommended. Could you try exporting full model and try again? 

However I don't see why this issue would occur. Can you try using the Nemo container (23.01 or 22.12) to see if exported model is correct?

**Comment by WuSu4620** [comment]
I've added to the issue what happens when the whole model is exported.
Currently cant try it with container because of technical reasons.

**Comment by WuSu4620** [comment]
After a lot of trial and error, I have some additional information. 
The bug "disappears" if the direct pytorch ebcoding-decoding made only after the export action.
So the model.export() command somehow changes the torch model's weights in-place. 
And actually shifts significantly the inference output of the exported model (many orders of magnitude more then the usual ~1e-5)

**Comment by titu1994** [comment]
That is expected. After export the models is considered unusable for further processing, as we have to do multiple transformation of the modules to get the correct export for performance. 

You can see that we perform verification of output not frpm the original models output but from the post exported module itself against the onnx export run - see https://github.com/NVIDIA/NeMo/blob/main/nemo/core/classes/exportable.py#L190 and
https://github.com/NVIDIA/NeMo/blob/main/nemo/utils/export_utils.py#L136

Self here refers to the model after it has undergone export modifications
