### ISSUE TITLE
Megatron GPT2 is generating repetitive sentence

### ISSUE THREAD

**Issue by dmitra9394** [NVIDIA/NeMo#6005]
** P tuning with Megatron GPT2 is generating repetitive sentence**

I am P tuning with Megatron GPT2 model with 100 train and 100 test dataset for a particular activity. I am getting repetitive sentence during inference for most of the samples. 
I have used below things to resolve this issue.
1. Used instruction sentence with sentence(tried without instruction as well)
2. Used a end token after each sentence(tried without end token as well)
3. Used a end token after each label(tried without end token as well)
4. Changed "repetition_penalty" to 0, 0.5, 1000, 10000 etc, however, the issue is still there.

I am trying to replicate https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Multitask_Prompt_and_PTuning.ipynb for generative AI. 

Please let me know the solution for this issue.

**Comment by okuchaiev** [comment]
which specific GPT checkpoint you are using?

**Comment by dipmitra9394** [comment]
I am replicating https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Multitask_Prompt_and_PTuning.ipynb 
 with megatron_gpt_345m.nemo checkpoint

**Comment by dipmitra9394** [comment]
megatron_gpt_345m.nemo checkpoint

**Comment by dmitra9394** [comment]
megatron_gpt_345m.nemo checkpoint
