### ISSUE TITLE
Experiment crashes after resuming from checkpoint

### ISSUE THREAD

**Issue by mujhenahiata** [NVIDIA/NeMo#6017]
[multilang_output_6.txt](https://github.com/NVIDIA/NeMo/files/10732583/multilang_output_6.txt)
[multilang_error_6.txt](https://github.com/NVIDIA/NeMo/files/10732586/multilang_error_6.txt)
**Describe the bug**
using 22.07 image from NGC cloud
unable to resume my experiment even after setting ### resume_if_exist=true 
AssertionError: If capturable=False, state_steps should not be CUDA tensors.

i have attache my log file your perusal
@titu1994 @meghmak13

**Comment by titu1994** [comment]
This is a bug with pytorch 1.12, and was fixed in container 22.12
