### ISSUE TITLE
Speaker Recognition and Verification:Out Of Memory

### ISSUE THREAD

**Issue by Aishteriu** [NVIDIA/NeMo#6031]
While trying to run speaker recognition and verification, at the part of  trainer.fit I get out of memory error. Colab has 15 GB of VRAM but 13.5 GB of this space seems alocated.

**Comment by Aishteriu** [comment]
I tried with changing branch to main. It doesn't fix the problem anyway.

**Comment by tango4j** [comment]
@Aishteriu 
Could you be more specific? At least, what class, which example code did you base on? 
In general, users should control the batch size since the training script cannot measure the system GPU size to prevent OOM issue.

**Comment by AyaAl1ah** [comment]
@tango4j I had the same issue he mentioned and that happened when trying to run the tutorial notebook tutorials/speaker_tasks/Speaker_Identification_Verification.ipynb on colab.
