### ISSUE TITLE
Provision for Multitask training

### ISSUE THREAD

**Issue by mujhenahiata** [NVIDIA/NeMo#6066]
**Is your feature request related to a problem? Please describe.**
So while training a conformer model in an unsupervised fashion. I saw usage of two loss, i.e. contrastive loss and mlm loss. 

So if i want to train the conformer model for ASR as well as language detection at the same time provided lang_ID/labels. and using to two losses. Multitasking 
**Describe the solution you'd like**
to thave the data like this
{audio_filepath:"English/audio/file1/path", "duration": 2.0, text: "Transcritpion in english ", "lang_id": "English"}
{audio_filepath:"English/audio/file2/path", "duration": 2.0, text: "Transcritpion in english ", "lang_id": "English"}
{audio_filepath:"English/audio/file3/path", "duration": 2.0, text: "Transcritpion in english ", "lang_id": "English"}
{audio_filepath:"Hindi/audio/file/path", "duration": 2.0, text: "Transcritpion in Hindi ", "lang_id": "Hindi"}
{audio_filepath:"Hindi/audio/file/path", "duration": 2.0, text: "Transcritpion in Hindi ", "lang_id": "Hindi"}
{audio_filepath:"Hindi/audio/file/path", "duration": 2.0, text: "Transcritpion in Hindi ", "lang_id": "Hindi"}
Similarly here also two losses will be taken into account. one can be ctc and other can be cross entropy. can in decoding, if a file is given first 30sec is chunked on which it will first detect the language and then decode the transcription in the aforementioned  language 
@titu1994 @meghmak13

**Comment by titu1994** [comment]
We don't support multi tasking like that, but what you're discussing is not really required either. 

It can be accomplished with multilingual ASR - 
https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Multilang_ASR.ipynb

Please refer to this blog post - https://developer.nvidia.com/blog/multilingual-and-code-switched-automatic-speech-recognition-with-nvidia-nemo/

cc @bmwshop for further questions. 

Still, we would welcome your contribution if you do decide to write a custom model that does this.
