### ISSUE TITLE
Extraneous Import in Flashlight Module with implications for dependencies

### ISSUE THREAD

**Issue by Jacob-Bishop** [NVIDIA/NeMo#6067]
**Describe the bug**

In the recently added flashlight module, https://github.com/NVIDIA/NeMo/blob/0e70135ccf24d882dcdc549321e747199a232bdf/nemo/collections/asr/modules/flashlight_decoder.py#L102 has a never-used import `from flashlight.lib.sequence.criterion import get_data_ptr_as_bytes.` This import appears to be from a different part of flashlight, not flashlight text, so it introduces a new (huge) dependency.

Edit: The sequence bindings are in https://github.com/flashlight/sequence/.

**Comment by trias702** [comment]
Apologies for this oversight, it has now been fixed on the main branch: https://github.com/NVIDIA/NeMo/pull/6071
