### ISSUE TITLE
Quartz Model sampling rate

### ISSUE THREAD

**Issue by tingyang01** [NVIDIA/NeMo#610]
Dear sir,
I'm trying to use ASR model in my application.
I've saw Quartz was trained five corpus, libri, common voice, wsj, Fisher, Switchboard.
i know Fisher and Switchboard of them are 8KHz of audio.
But I saw the sampling rate is 16000 in Quartz configuration.
I'd like to know how to train these 8KHz audio files.
Thank you.

**Comment by okuchaiev** [comment]
the checkpoints we currently released are all trained using 16Khz data.
So if you want to use them with 8Khz audio, you will need to upsample it to 16Khz.
