### ISSUE TITLE
tacotron2.yaml config file buggy

### ISSUE THREAD

**Issue by one1ine** [NVIDIA/NeMo#6121]
**Describe the bug**
When initiating tacotron.py for training, the following error comes up:

Error executing job with overrides: []
Error in call to target 'nemo.collections.tts.data.tts_dataset.TTSDataset':
FileNotFoundError(2, 'No such file or directory')
full_key: train_ds.dataset

**Steps/Code to reproduce bug**

python tacotron2.py

(hardcoded the training and validation dataset paths in tacotron2.yaml file but also tried giving the path from the cli)

**Expected behavior**

Training starts.

**Environment overview (please complete the following information)**

 - Environment location: on-site desktop
 - Method of NeMo install: tries installing both with pip and from source.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 20.04 and Windows 11 (dual-boot)
- PyTorch version: 1.13.1
- Python version: 3.8.0

**Additional context**

Example: GPU model

**Comment by redoctopus** [comment]
Can you double-check that the `train_ds.dataset` path is correct relative to the directory from which you are running the script?

**Comment by one1ine** [comment]
I've started running the script by providing the path directly from CLI and now the datasets are loading fine. However, now im getting a PicklingError. Can you possibly help with this issue?

[tacotron2.py PicklingError.txt](https://github.com/NVIDIA/NeMo/files/10927333/tacotron2.py.PicklingError.txt)

**Comment by redoctopus** [comment]
Sorry--we don't officially support Windows and I'm not familiar with trying to run our models on Windows, don't think I've seen this error before. I can ask around, though.

**Comment by redoctopus** [comment]
On a second look, can you try just using 'r' instead of 'rb', assuming `spawn.py` is a file you're editing? I think that may be the cause of the first error, anyway.

**Comment by rlangman** [comment]
The PicklingError is related to the OS specific differences described in https://pytorch.org/docs/stable/data.html#platform-specific-behaviors

The question is whether there is an easy workaround for it within NeMo.

A quick test could be set dataloader_params.num_workers to 1 to see if it avoids using multiprocessing (but would limit the data loader to just 1 thread).

The suggestions in the documentation to add a if __name__ == '__main__' guard and ensure other code is defined outside of it do not look helpful, as our training scripts already do this.
