### ISSUE TITLE
Read amplification upon checkpoint read

### ISSUE THREAD

**Issue by leezu** [NVIDIA/NeMo#6131]
**Describe the bug**

NeMo currently executes load_checkpoint independently on all ranks, causing unnecessarily high filesystem reading. In contrast,
save_checkpoint functionality for nlp models is only executed on rank 0 / data_parallel_rank == 0: https://github.com/NVIDIA/NeMo/blob/ac50e5963ca4e23b7fd758f0732f6ed51200cc1d/nemo/collections/nlp/parts/nlp_overrides.py#L164-L171

**Steps/Code to reproduce bug**

See

https://github.com/NVIDIA/NeMo/blob/ac50e5963ca4e23b7fd758f0732f6ed51200cc1d/nemo/collections/nlp/parts/nlp_overrides.py#L195-L200

**Expected behavior**

Checkpoint is only read from filesystem on rank 0 / data_parallel_rank == 0 and broadcasted to all other ranks.

**Comment by wdykas** [comment]
Hey @leezu Is below along the lines of what you are looking for:
```
def load_checkpoint(self, checkpoint_path: Union[str, Path]) -> Dict[str, Any]:
        """ PTL override to accomodate model parallel checkpoints """
        # TODO: move to CheckpointIO
        torch.cuda.empty_cache()
        checkpoint_path = inject_model_parallel_rank(checkpoint_path)

        # Get rank information
        global_rank = torch.distributed.get_rank()
        mgroup_global_ranks = torch.distributed.get_process_group_ranks(parallel_state.get_model_parallel_group())
        src_rank = min(mgroup_global_ranks)

        #Smallest global rank of the model group will broadcast data
        if global_rank == src_rank:
            checkpoint = self.checkpoint_io.load_checkpoint(checkpoint_path)
        else:
            checkpoint = {}
        checkpoint_list = [checkpoint]
        torch.distributed.broadcast_object_list(checkpoint_list,src = src_rank, group = parallel_state.get_model_parallel_group())
        checkpoint = checkpoint_list.pop()
        return checkpoint
```

This seemed to work for me single node but I have not tested multinode and there could definitely be issues with it but wanted to first see if this was what you are referring to.
