### ISSUE TITLE
[DIARIZATION] is clustering needed when number of speakers is known?

### ISSUE THREAD

**Issue by yarimotoy** [NVIDIA/NeMo#6133]
Hello,

I'm using the diarization model and already know the number of speakers. I thought that the clustering algorithm was only needed to determine the number of speakers, but it seems that it is still being run if when I use the following settings:

```
meta = {
    'audio_filepath': an4_audio,
    'offset': 0,
    'duration': None,
    'label': 'infer',
    'text': '-',
    'num_speakers': 2,
    'rttm_filepath': None,
    'uem_filepath': None
}
```
and

`config.diarizer.clustering.parameters.oracle_num_speakers = True`

Is that the expected behavior? My main issue is that while the other parts of the model can be run on the GPU, the  clustering is still run on the CPU so the overall inference is quite long.

**Comment by jeremy110** [comment]
If you don't mind, let me share my opinion. Nemo's clustering mainly adopts the method described in the paper "Auto-Tuning Spectral Clustering for Speaker Diarization Using Normalized Maximum Eigengap". Estimating the number of speakers is just one step of the process. Before performing the 10) k-means clustering, the 9) Spectral Embedding still requires calculation using eigenvectors. Therefore, it only skips the computation of the parameter k.And clustering can also be run on the GPU.

**Comment by tango4j** [comment]
Clustering is also needed even when a number of speakers is provided. 
@yarimotoy the clustering algorithm is now fixed to use GPU and no more slow down is occuring. Please try the latest main.
