### ISSUE TITLE
Loading ar conformer

### ISSUE THREAD

**Issue by renadnasser1** [NVIDIA/NeMo#6143]
I'm trying to load a pertained conformer that I downloaded from the NGC model catalog using the following two lines 

```
import nemo.collections.asr as nemo_asr

conformer = nemo_asr.models.ASRModel.restore_from('/home/Conformer-CTC-L_spe128_ar-AR_2.0.nemo')
```

but an error arose with the message '  ReadError: not a gzip file '. 

you can find the model on 
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/riva/models/speechtotext_ar_ar_conformer/files?version=trainable_v2.0

**Comment by VahidooX** [comment]
We tested the nemo file, and it was fine. It looks like the file is corrupted. Please download it again.
