### ISSUE TITLE
IndexError: index 0 is out of bounds for dimension 1 with size 0

### ISSUE THREAD

**Issue by LokeshSaipureddi** [NVIDIA/NeMo#6201]
[/usr/local/lib/python3.9/dist-packages/nemo/collections/asr/parts/preprocessing/features.py](https://localhost:8080/#) in forward(self, x, seq_len, linear_spec)
    407         # do preemphasis
    408         if self.preemph is not None:
--> 409             x = torch.cat((x[:, 0].unsqueeze(1), x[:, 1:] - self.preemph * x[:, :-1]), dim=1)
    410 
    411         # disable autocast to get full range of stft values

IndexError: index 0 is out of bounds for dimension 1 with size 0

Getting this issue while executiong the chunks

**Comment by titu1994** [comment]
Your audio may be corrupted - index 0 is channel dimension 0

**Comment by starxa2** [comment]
Hello was the issue resolved ? I am getting the same error
