### ISSUE TITLE
Pin Pytorch Lightning >= 1.9 but < 2.0.0

### ISSUE THREAD

**Issue by mathemakitten** [NVIDIA/NeMo#6202]
**Describe the bug**

A fresh install of NeMo will break when using Lightning 2.0.0 because NeMo calls `from pytorch_lightning.trainer.connectors.checkpoint_connector import CheckpointConnector` but `CheckpointConnector` has been moved to `_CheckpointConnector` in 2.0.0 (see [here](https://github.com/Lightning-AI/lightning/blob/ad1c994d96c420d8c2def96354e5f7bc551afb98/src/lightning/pytorch/trainer/connectors/checkpoint_connector.py#L45)).

**Steps/Code to reproduce bug**

A fresh install of NeMo which uses Lightning 2.0.0 by default will throw an import error. 

**Additional context**

Pinning to 1.9.3 would solve this until a refactor can be done.

**Comment by SeanNaren** [comment]
Fixed on main, now we need to work towards supporting Lightning 2.0.0!
