### ISSUE TITLE
Convert Jasper's Pytorch Checkpoint in Jasper-NeMo format 

### ISSUE THREAD

**Issue by awasthiabhijeet** [NVIDIA/NeMo#622]
Hi,
I wish to know if there is a script available to convert a [PyTorch jasper checkpoint](https://ngc.nvidia.com/catalog/models/nvidia:jasperpyt_fp16) to a [NeMo jasper checkpoint](https://ngc.nvidia.com/catalog/models/nvidia:jaspernet10x5dr).  (or vice-versa?)

Apart from the framework, is there any significant difference between these two checkpoints?

**Comment by okuchaiev** [comment]
I would actually recommend you have a look at our QuartzNet model as it has only 19M weights compared to Jasper's ~300M. Also, this checkpoint https://ngc.nvidia.com/catalog/models/nvidia:multidataset_quartznet15x5 was pre-trained on ~3,300 hours of data

**Comment by awasthiabhijeet** [comment]
Hi @okuchaiev 
Thanks for the suggestion.
I am looking for a model only trained on LibriSpeech. 
Is QuartzNet trained on just LibriSpeech available? (just like jasper checkpoints trained on just LibriSpeech)

**Comment by awasthiabhijeet** [comment]
Got it! 
https://ngc.nvidia.com/catalog/models/nvidia:quartznet_15x5_ls_sp

Thanks!

**Comment by awasthiabhijeet** [comment]
Hi @okuchaiev 
Is QuartzNet checkpoint compatible with Jasper Code provided in this repository?
Is QuartzNet's config available in .toml format?
I tried converting yaml config to toml config and tried making it similar to the jasper's toml file in this repository. 
But, while loading checkpoint, I get following errors:
`RuntimeError: Error(s) in loading state_dict for JasperEncoderDecoder:
	size mismatch for jasper_encoder.encoder.0.conv.0.weight: copying a param with shape torch.Size([64, 1, 33]) from checkpoint, the shape in current model is torch.Size([256, 64, 33]).
	size mismatch for jasper_encoder.encoder.0.conv.1.weight: copying a param with shape torch.Size([256, 64, 1]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.1.conv.0.weight: copying a param with shape torch.Size([256, 1, 33]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.1.conv.1.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.1.conv.5.weight: copying a param with shape torch.Size([256, 1, 33]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.1.conv.12.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.1.conv.16.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.2.conv.0.weight: copying a param with shape torch.Size([256, 1, 33]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.2.conv.1.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.2.conv.5.weight: copying a param with shape torch.Size([256, 1, 33]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.2.conv.12.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.2.conv.16.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.3.conv.0.weight: copying a param with shape torch.Size([256, 1, 33]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.3.conv.1.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.3.conv.5.weight: copying a param with shape torch.Size([256, 1, 33]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.3.conv.12.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.3.conv.16.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 33]).
	size mismatch for jasper_encoder.encoder.4.conv.0.weight: copying a param with shape torch.Size([256, 1, 39]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.4.conv.1.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.4.conv.5.weight: copying a param with shape torch.Size([256, 1, 39]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.4.conv.12.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.4.conv.16.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.5.conv.0.weight: copying a param with shape torch.Size([256, 1, 39]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.5.conv.1.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.5.conv.5.weight: copying a param with shape torch.Size([256, 1, 39]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.5.conv.12.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.5.conv.16.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.6.conv.0.weight: copying a param with shape torch.Size([256, 1, 39]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.6.conv.1.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.6.conv.5.weight: copying a param with shape torch.Size([256, 1, 39]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for jasper_encoder.encoder.6.conv.12.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.6.conv.16.weight: copying a param with shape torch.Size([256, 256, 1]) from checkpoint, the shape in current model is torch.Size([256, 256, 39]).
	size mismatch for jasper_encoder.encoder.7.conv.0.weight: copying a param with shape torch.Size([256, 1, 51]) from checkpoint, the shape in current model is torch.Size([512, 256, 51]).
	size mismatch for jasper_encoder.encoder.7.conv.1.weight: copying a param with shape torch.Size([512, 256, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.7.conv.5.weight: copying a param with shape torch.Size([512, 1, 51]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.7.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 51]).
	size mismatch for jasper_encoder.encoder.7.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 51]).
	size mismatch for jasper_encoder.encoder.8.conv.0.weight: copying a param with shape torch.Size([512, 1, 51]) from checkpoint, the shape in current model is torch.Size([512, 512, 51]).
	size mismatch for jasper_encoder.encoder.8.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.8.conv.5.weight: copying a param with shape torch.Size([512, 1, 51]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.8.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 51]).
	size mismatch for jasper_encoder.encoder.8.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 51]).
	size mismatch for jasper_encoder.encoder.9.conv.0.weight: copying a param with shape torch.Size([512, 1, 51]) from checkpoint, the shape in current model is torch.Size([512, 512, 51]).
	size mismatch for jasper_encoder.encoder.9.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.9.conv.5.weight: copying a param with shape torch.Size([512, 1, 51]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.9.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 51]).
	size mismatch for jasper_encoder.encoder.9.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 51]).
	size mismatch for jasper_encoder.encoder.10.conv.0.weight: copying a param with shape torch.Size([512, 1, 63]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.10.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.10.conv.5.weight: copying a param with shape torch.Size([512, 1, 63]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.10.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.10.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.11.conv.0.weight: copying a param with shape torch.Size([512, 1, 63]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.11.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.11.conv.5.weight: copying a param with shape torch.Size([512, 1, 63]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.11.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.11.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.12.conv.0.weight: copying a param with shape torch.Size([512, 1, 63]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.12.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.12.conv.5.weight: copying a param with shape torch.Size([512, 1, 63]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.12.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.12.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 63]).
	size mismatch for jasper_encoder.encoder.13.conv.0.weight: copying a param with shape torch.Size([512, 1, 75]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.13.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.13.conv.5.weight: copying a param with shape torch.Size([512, 1, 75]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.13.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.13.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.14.conv.0.weight: copying a param with shape torch.Size([512, 1, 75]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.14.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.14.conv.5.weight: copying a param with shape torch.Size([512, 1, 75]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.14.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.14.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.15.conv.0.weight: copying a param with shape torch.Size([512, 1, 75]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.15.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.15.conv.5.weight: copying a param with shape torch.Size([512, 1, 75]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for jasper_encoder.encoder.15.conv.12.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.15.conv.16.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512, 512, 75]).
	size mismatch for jasper_encoder.encoder.16.conv.0.weight: copying a param with shape torch.Size([512, 1, 87]) from checkpoint, the shape in current model is torch.Size([512, 512, 87]).
	size mismatch for jasper_encoder.encoder.16.conv.1.weight: copying a param with shape torch.Size([512, 512, 1]) from checkpoint, the shape in current model is torch.Size([512]).`

**Comment by awasthiabhijeet** [comment]
The converted toml file looks like this:

model = "QuartzNet"

[input]
normalize = "per_feature"
sample_rate = 16000
window_size = 0.02
window_stride = 0.01
window = "hann"
features = 64
n_fft = 512
frame_splicing = 1
dither = 0.00001
feat_type = "logfbank"
normalize_transcripts = true
trim_silence = true
pad_to = 16
max_duration = 16.7
speed_perturbation = false
stft_conv = true


cutout_rect_regions = 0
cutout_rect_time = 60
cutout_rect_freq = 25

cutout_x_regions = 0
cutout_y_regions = 0
cutout_x_width = 6
cutout_y_width = 6


[input_eval]
normalize = "per_feature"
sample_rate = 16000
window_size = 0.02
window_stride = 0.01
window = "hann"
features = 64
n_fft = 512
frame_splicing = 1
dither = 0.00001
feat_type = "logfbank"
normalize_transcripts = true
trim_silence = true
pad_to = 16
stft_conv = true

[encoder]
activation = "relu"
convmask = true

[[jasper]]
filters = 256
repeat = 1
kernel = [33]
stride = [2]
dilation = [1]
dropout = 0.0
residual = false
separable = true

[[jasper]]
filters = 256
repeat = 5
kernel = [33]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 256
repeat = 5
kernel = [33]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 256
repeat = 5
kernel = [33]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 256
repeat = 5
kernel = [39]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 256
repeat = 5
kernel = [39]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 256
repeat = 5
kernel = [39]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [51]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [51]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [51]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [63]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [63]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [63]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [75]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [75]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 5
kernel = [75]
stride = [1]
dilation = [1]
dropout = 0.0
residual = true
separable = true

[[jasper]]
filters = 512
repeat = 1
kernel = [87]
stride = [1]
dilation = [2]
dropout = 0.0
residual = false
separable = true

[[jasper]]
filters = 1024
repeat = 1
kernel = [1]
stride = [1]
dilation = [1]
dropout = 0.0
residual = false

[labels]
labels = [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]

**Comment by AshishSardana** [comment]
Hi @awasthiabhijeet, are you sure that the checkpoint corresponds to the same QuartzNet architecture that you're loading it into? NGC has QuartzNet15x5 weights.

**Comment by awasthiabhijeet** [comment]
Hi @AshishSardana 
Yes, I am loading [this checkpoint](https://ngc.nvidia.com/catalog/models/nvidia:multidataset_quartznet15x5) as pointed by @okuchaiev.

However, I wish to work in the PyTorch framework, instead of NeMo. (hence I filed an issue in this repo).

So, I wrote this script which converts the above checkpoint which is NeMo compatible, to a format which is compatible with Jasper's code in this repository (broadly speaking, I am just merging the encoder and decoder ckpt into a single ckpt)

Here is the script I am using:

```
import os,sys
import torch
from collections import OrderedDict

pt_jasper = torch.load("jasper_fp16.pt")
jasper_encoder = torch.load("JasperEncoder-STEP-406556.pt")
jasper_decoder = torch.load("quartznet/JasperDecoderForCTC-STEP-406556.pt")
path_new_ckpt =  "quartznet/quartznet.pt" # path to converted ckpt


nemo_keys = set(jasper_encoder.keys()).union(set(jasper_decoder.keys()))
pt_keys = set(pt_jasper["state_dict"].keys())

def get_pt_jasper_compatible_key(key):
	#key: key from nemo checkpoint
	if 'encoder' in key:
		key = 'jasper_encoder.' + key
	elif 'decoder' in key:
		key = 'jasper_decoder.' + key 
	if '.res.' in key and '.conv.' in key:
		key = key.replace('.conv.','.') 
	
	if '.mconv.' in key:
		key = key.replace('.mconv.','.conv.')
		if 'conv.weight' in key:
			key = key.replace('conv.weight','weight')
	return key


new_ckpt = {}
for item in pt_jasper.keys():
	if item != "state_dict":
		new_ckpt[item]=pt_jasper[item]
	else:
		new_state_dict = OrderedDict()
		
		for key,value in jasper_encoder.items():
			key = get_pt_jasper_compatible_key(key)
			new_state_dict[key]=value

		for key,value in jasper_decoder.items():
			key = get_pt_jasper_compatible_key(key)
			new_state_dict[key]=value


		new_state_dict['audio_preprocessor.featurizer.window'] = pt_jasper['state_dict']['audio_preprocessor.featurizer.window']
		new_state_dict['audio_preprocessor.featurizer.fb'] = pt_jasper['state_dict']['audio_preprocessor.featurizer.fb']
		new_ckpt[item]=new_state_dict


torch.save(new_ckpt,path_new_ckpt)
```

Here `pt_jasper = torch.load("jasper_fp16.pt")` simply loads a [jasper ckpt compatible with jasper code repository](https://ngc.nvidia.com/catalog/models/nvidia:jasperpyt_fp16). This ckpt is only used to copy the audio_preprocesser model into the converted ckpt.

**Comment by manjuke** [comment]
Hi All, I still Have this issue. I have done transfer learning on confermer-ctc-model and I have ckpt files generated. But, I am unable to load them as they are not in .nemo format. 
I am getting error, if I try to load them using model = nemo_asr.models.EncDecCTCModelBPE.restore_from(restore_path="<path>/checkpoints/epoch_5-step_82700.ckpt")

So, How do I convert .ckpt to .nemo format. 
I could not find any relevant answers in internet as well. Thanks.

**Comment by titu1994** [comment]
Please do not spam old and closed issues.

**Comment by manjuke** [comment]
Sure. Thank you.  Sorry, for posting here.
