### ISSUE TITLE
Custom g2p module

### ISSUE THREAD

**Issue by huydang2106** [NVIDIA/NeMo#6268]
I am trying to build my own TTS model for my dataset. I already have a good g2p module. Instead of being a neural network model, it is a collection of rules to convert text into phonemes and I am struggling to find a way to integrate my own g2p module into the code to run training TTS.
Are there any instructions or documentation about this?

**Comment by redoctopus** [comment]
We don't currently support any way for users to drop in custom G2P modules, sorry about that. You might be able to hack it by wrapping it in a new G2P class, implementing the functions that the tokenizer expects to be able to call, and replacing the current G2P class in the config with yours.

**Comment by huydang2106** [comment]
okay thank you.

**Comment by sastryvs-sporai** [comment]
Is there any Phoneme dictionary and G2P module for hindi language so that I can fine tune Nvidia Fastpitch?
