### ISSUE TITLE
LinAlg Error When Running Clustering Diarizer

### ISSUE THREAD

**Issue by SammyVincent-Dasion** [NVIDIA/NeMo#6282]
**Describe the bug**

Diarization continues until clustering, upon which I get this error.
"linalg.eigh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 529)"

**Steps/Code to reproduce bug**

I'm loosely following the notebook at https://github.com/NVIDIA/NeMo/blob/main/tutorials/speaker_tasks/Speaker_Diarization_Inference.ipynb except i turned oracle vad off.

Here's the diarization part of my notebook
https://colab.research.google.com/drive/1zN9LZ5-hPEI15K1NWl2obvEapJbTWd9P?usp=sharing

**Comment by tango4j** [comment]
Hi, we are looking into this issue with the input file you provided. 
I will comment again once I figure out a way to prevent this ill-conditioned matrix issue.

**Comment by xro7** [comment]
I face the same issue with multiple input audios. Any updates?

**Comment by FrankTianTT** [comment]
I even encountered this issue on the apple chip of MacOS, perhaps this issue is not just on Nvidia cuda?
