### ISSUE TITLE
Evaluation of ASR with LM increases WER

### ISSUE THREAD

**Issue by janvainer** [NVIDIA/NeMo#629]
Hi, I use the pretrained Quartznet checkpoint and adapt it to custom data. After some training, the model reaches around 27% WER. Then, when I use [KenLM for beam search rescoring](https://nvidia.github.io/NeMo/asr/tutorial.html#evaluation-with-language-model), the WER increases by approx. 5%. I tried the KenLM pretrained on LibriSpeech as well as KenLM trained on my data. The former was slightly worse than the latter, but both increased WER. WHat could be the possible causes? I checked if the models use the same alphabet etc., but could not find a reasonable answer.

**Comment by vsl9** [comment]
Hi, have you tried to tune [`alpha`](https://github.com/NVIDIA/NeMo/blob/c09f54dded4264bf1b4e0602fc7b6350da1dac46/examples/asr/jasper_eval.py#L45), [`beta`](https://github.com/NVIDIA/NeMo/blob/c09f54dded4264bf1b4e0602fc7b6350da1dac46/examples/asr/jasper_eval.py#L55) parameters?

**Comment by LordOfLuck** [comment]
Yes, I used the jasper_eval script from the [documentation ](https://nvidia.github.io/NeMo/asr/tutorial.html#evaluation)and there is a grid search over alphas and betas included.

**Comment by dangvansam98** [comment]
> Hi, have you tried to tune [`alpha`](https://github.com/NVIDIA/NeMo/blob/c09f54dded4264bf1b4e0602fc7b6350da1dac46/examples/asr/jasper_eval.py#L45), [`beta`](https://github.com/NVIDIA/NeMo/blob/c09f54dded4264bf1b4e0602fc7b6350da1dac46/examples/asr/jasper_eval.py#L55) parameters?

how i tune it?
