### ISSUE TITLE
Nemo Toolkit install fail

### ISSUE THREAD

**Issue by drvrh** [NVIDIA/NeMo#6298]
Hello, 
I run command: 
`pip install "nemo_toolkit[all]"
`
And I get more errors, 

the first one is: 

`
->nemo_toolkit[all]) (0.9.1)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      /home/grega/miniconda3/envs/nemo/lib/python3.8/site-packages/setuptools/dist.py:720: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
`

the second one is: 

` 
    RuntimeError: Unsupported compiler -- at least C++11 support is needed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fasttext
  Running setup.py clean for fasttext
Failed to build fasttext
Installing collected packages: fasttext, black, beautifulsoup4, anyio, aiosignal, texterrors, starlette, sphinx, numba, mdit-py-plugins, matplotlib, markdown, hydra-core, httpcore, GitPython, Flask, botocore, aiohttp, wandb, transformers, torchmetrics, s3transfer, pybtex-docutils, pyannote.database, paramiko, librosa, kornia, ipython, httpx, google-auth-oauthlib, gdown, g2p-en, flask-restful, fastapi, tensorboard, sphinxcontrib-bibtex, sentence-transformers, pytorch-lightning, pyannote.metrics, ipywidgets, gradio, boto3, nemo_toolkit
  Running setup.py install for fasttext ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for fasttext did not run successfully.
  │ exit code: 1
  ╰─> [64 lines of output]
`

the last one is: 

```
      RuntimeError: Unsupported compiler -- at least C++11 support is needed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> fasttext

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

Please help me. 

Thank you.

**Comment by drvrh** [comment]
When install:

`apt-get install build-essential -y`

the install Nemo inner pip ok.

**Comment by titu1994** [comment]
NeMos install instructions require first installing pytorch, then Cython and then finally do pip install nemo_toolkit.
