### ISSUE TITLE
Questions About Pre-trained Models for ACEVC

### ISSUE THREAD

**Issue by windforestfiremountain** [NVIDIA/NeMo#6312]
Hi. Thank you very much for your implementation on ACEVC. I'm interested in this Zero-shot Voice Conversion project. I tried to train the model following the document on the website https://paarthneekhara.github.io/ace/code.html. However, it takes much time because of my poor hardware conditions. Are there any pretrained models for ACEVC,such as the pre-trained Conformer-SSL in step 1 or the HiFiGAN model in step 3. I'm sincerely thankful with your help.

**Comment by windforestfiremountain** [comment]
Okay, thanks for your anwser!

**Comment by JunjieLl** [comment]
> Okay, thanks for your anwser!
Hi!
I'm also interested in the area, could you show me which pretrained models you use and how?
Thank you!
