### ISSUE TITLE
Support of other asr models

### ISSUE THREAD

**Issue by viralrupapara36** [NVIDIA/NeMo#6329]
I have customised wav2vec model for my asr task and I want to use it in this diarization pipeline but I can't do it, because it is not supported.

Please, update the library so that we can use any pytorch models.

**Comment by titu1994** [comment]
This is not feasible to support arbitrary models. You are welcome to submit a PR to add support for Wav2Vec however.

**Comment by viralrupapara36** [comment]
Okay thanks
Can you please give me some guidance/reference for that ?

**Comment by titu1994** [comment]
You can push code to your branch, and select create PR from your branch to Nemo
