### ISSUE TITLE
Add word beam search

### ISSUE THREAD

**Issue by janvainer** [NVIDIA/NeMo#636]
I was wondering, are there any plans to integrate the [word beam search](https://ieeexplore.ieee.org/document/8583770) into the framework? There is a cpp [code ](https://github.com/githubharald/CTCWordBeamSearch) for tensorflow and the adaptation for pytorch should be relatively straightforward.

**Comment by okuchaiev** [comment]
We currently only have char-level beam search with word-level (or n-gramm level) language model https://nvidia.github.io/NeMo/asr/tutorial.html#evaluation-with-language-model
