### ISSUE TITLE
ASR_with_Subword_Tokenization.ipynb's guide on process_asr_text_tokenizer script is broken

### ISSUE THREAD

**Issue by lolbus** [NVIDIA/NeMo#6369]
**Describe the bug**

When following guide to Build a Customize Tokenizer, process_asr_text_tokenizer.py does not create intended tokenizer folder with required content. Unable to pre-trained on any models that use BPE vocab since no one can pass anything to the new_tokenizer_dir argument now. 

**Steps/Code to reproduce bug**
Try to run below command as taught by the tutorial, see if it works for you.
`!python /content/drive/MyDrive/Colab\sNotebooks/AI6127\sNLP/GroupProject/Data/process_asr_text_tokenizer.py \
  --manifest="/content/drive/MyDrive/Colab Notebooks/AI6127 NLP/GroupProject/Data/manifest_train.json" \
  --data_root="/content/drive/MyDrive/Colab Notebooks/AI6127 NLP/GroupProject/Data" \
  --vocab_size=32 \
  --tokenizer="spe" \
  --no_lower_case \
  --log`

**Expected behavior**

![image](https://user-images.githubusercontent.com/1837762/230006481-47a2e2e2-f0bf-4d95-8eae-2267bad5f565.png)

**Environment overview (please complete the following information)**

Colab Pro +

**Environment details**

NA
**Additional context**

NA

**Comment by titu1994** [comment]
> /content/drive/MyDrive/Colab\sNotebooks/AI6127\sNLP/GroupProject/Data/process_asr_text_tokenizer.py

Your path has backslash and other odd path separators. This causes the path to split before and after "NLP". Best to put it in string quotes and use correct path.

**Comment by lolbus** [comment]
Well I did tried to change the path to string quotes as well, but the same error persists. :/

In the meantime, I could only load pre-trained models based on characters vocab.

**Comment by titu1994** [comment]
Could you try creating a shorter path without spaces or any special character separator

**Comment by lolbus** [comment]
Yes seems like long directory path is an issue.

That error disappeared now with a shorter path.

Working on another issue now!

`[NeMo W 2023-04-05 07:37:55 optimizers:54] Apex was not found. Using the lamb or fused_adam optimizer will error out.
INFO:root:Corpus already exists at path : /content/drive/MyDrive//t/text_corpus/document.txt
[NeMo I 2023-04-05 07:37:55 sentencepiece_tokenizer:315] Processing /content/drive/MyDrive//t/text_corpus/document.txt and store at /content/drive/MyDrive//t/tokenizer_spe_bpe_v32
sentencepiece_trainer.cc(177) LOG(INFO) Running command: --input=/content/drive/MyDrive//t/text_corpus/document.txt --model_prefix=/content/drive/MyDrive//t/tokenizer_spe_bpe_v32/tokenizer --vocab_size=32 --shuffle_input_sentence=true --hard_vocab_limit=false --model_type=bpe --character_coverage=1.0 --bos_id=-1 --eos_id=-1
sentencepiece_trainer.cc(77) LOG(INFO) Starts training with : 
trainer_spec {
  input: /content/drive/MyDrive//t/text_corpus/document.txt
  input_format: 
  model_prefix: /content/drive/MyDrive//t/tokenizer_spe_bpe_v32/tokenizer
  model_type: BPE
  vocab_size: 32
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars: 
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  hard_vocab_limit: 0
  use_all_vocab: 0
  unk_id: 0
  bos_id: -1
  eos_id: -1
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇ 
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv: 
}
denormalizer_spec {}
trainer_interface.cc(350) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(181) LOG(INFO) Loading corpus: /content/drive/MyDrive//t/text_corpus/document.txt
trainer_interface.cc(406) LOG(INFO) Loaded all 0 sentences
trainer_interface.cc(422) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(427) LOG(INFO) Normalizing sentences...
Traceback (most recent call last):
  File "/content/./scripts/process_asr_text_tokenizer.py", line 324, in <module>
    main()
  File "/content/./scripts/process_asr_text_tokenizer.py", line 302, in main
    tokenizer_path = __process_data(
  File "/content/./scripts/process_asr_text_tokenizer.py", line 247, in __process_data
    tokenizer_path, vocab_path = create_spt_model(
  File "/usr/local/lib/python3.9/dist-packages/nemo/collections/common/tokenizers/sentencepiece_tokenizer.py", line 372, in create_spt_model
    sentencepiece.SentencePieceTrainer.Train(cmd)
  File "/usr/local/lib/python3.9/dist-packages/sentencepiece/__init__.py", line 989, in Train
    SentencePieceTrainer._Train(arg=arg, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sentencepiece/__init__.py", line 945, in _Train
    return SentencePieceTrainer._TrainFromString(arg)
  File "/usr/local/lib/python3.9/dist-packages/sentencepiece/__init__.py", line 923, in _TrainFromString
    return _sentencepiece.SentencePieceTrainer__TrainFromString(arg)
RuntimeError: Internal: src/trainer_interface.cc(428) [!sentences_.empty()] `
