### ISSUE TITLE
GPT Training process hangs during sanity checking dataloader with TP=2, PP=2 and bias=false

### ISSUE THREAD

**Issue by hiyijian** [NVIDIA/NeMo#6396]
**Describe the bug**

With TP=2 ,PP=2 and model.bias=false, GPT Training process hangs during dataloader sanity checking

**Steps/Code to reproduce bug**
Clone r1.15.0 realese branch and then run the offical GPT pretrain example with my trivial modification
```shell
git clone https://github.com/NVIDIA/NeMo.git
cd Nemo
git branch r1.15.0
bash reinstall.sh
cd examples/nlp/language_modeling
bash train.sh
``` 
Below is the content of train.sh:
```shell
MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}
MASTER_PORT=29503

NUM_NODES=1
NODE_RANK=0
GPUS_PER_NODE=8

DATA_PREFIX="[1.0,/data/pretrain/openwebtext2/hfbpe_gpt_training_data_text_document]"

torchrun --nnodes ${NUM_NODES} --nproc_per_node ${GPUS_PER_NODE} \
    --master_addr ${MASTER_ADDR} --master_port ${MASTER_PORT} --node_rank ${NODE_RANK} \
    ./megatron_gpt_pretraining.py  \
    --config-name=megatron_gpt_config.yaml \
    trainer.devices=${GPUS_PER_NODE} \
    trainer.num_nodes=${NUM_NODES} \
    model.data.data_prefix=${DATA_PREFIX} \
    model.tensor_model_parallel_size=2 \
    model.pipeline_model_parallel_size=2 \
    +model.bias=false \
    model.bias_activation_fusion=false \
    model.bias_dropout_add_fusion=false \
``` 
As we can see, the modification here is just: 
- disable all the bias item of linear layer in GPT model
- diabale bias related CUDA kernal fusion, as we do not need bias yet

The program hangs during dataloader sanity checking at very early stage of training.

It is OK if I turn on the bias and the related kernal fusion, or if I set PP=1

Logically, there should be no relevance between bias and pipeline. So I think it is an unexpected behaviour.

**Expected behavior**

It is expected that NeMo is able to train very large model without any bias term in pipeline parallel mode, such as LLama-65B.

**Environment overview (please complete the following information)**

 - Environment location: Docker
 - Method of NeMo install: `bash reinstall.sh`
 - If method of install is [Docker], provide `docker pull nvcr.io/nvidia/nemo:23.01 ` & `docker run --shm-size 64g --network=host -v ${HOME}:${HOME} -v ${DATAROOT}:/data -it nvcr.io/nvidia/nemo:23.01 bash` commands used

```[tasklist]
```

**Comment by distinction1111** [comment]
@hiyijian ，have you found any workaround? I also meet the same problem but can't find the reason, thx

**Comment by flymark2010** [comment]
@distinction1111 I found that it will hang when using non-fused method [get_bias_dropout_add](https://github.com/NVIDIA/NeMo/blob/ecc116c29a14534abfe393f6eee4339b24ca6e57/nemo/collections/nlp/modules/common/megatron/transformer.py#L427) and [get_dropout_add](https://github.com/NVIDIA/NeMo/blob/ecc116c29a14534abfe393f6eee4339b24ca6e57/nemo/collections/nlp/modules/common/megatron/transformer.py#L430). I don't know why. So I use a workaround by implementing a fused version `dropout_add_fused_train` based on the [bias_dropout_add_fused_train](https://github.com/NVIDIA/NeMo/blob/ecc116c29a14534abfe393f6eee4339b24ca6e57/nemo/collections/nlp/modules/common/megatron/fused_bias_dropout_add.py#L51), and always using the fused one. This makes the training going on.

**Comment by hiyijian** [comment]
no nvidia/nemo contributor involved now. pls do not close this issue at this moment

**Comment by ericharper** [comment]
You can disable bias for GPT training as of this pr: https://github.com/NVIDIA/NeMo/pull/5991

Could you try r1.17.0 release or later?

**Comment by hiyijian** [comment]
@ericharper , thanks for helping. I noticed the PR you mentioned, but this problem happened with bias=False, not bias=True

BTW: higher version such asr1.17.0 also has this problem

**Comment by hiyijian** [comment]
@ericharper Is there any clue, please?

**Comment by absol13** [comment]
This problem still occurs at the latest release(1.19.0). Please handle it, at least by applying patch by @flymark2010.

**Comment by ahxt** [comment]
This problem still occurs in the latest version. Does anyone have a solution to this?

**Comment by ahxt** [comment]
> This problem still occurs in the latest version. Does anyone have a solution to this?

Anyone has the same issue?

**Comment by PurvangL** [comment]
@ahxt Any luck finding solution to the issue? I am facing similar issue.
