### ISSUE TITLE
Inconsistent documentation?

### ISSUE THREAD

**Issue by nilsjohanbjorck** [NVIDIA/NeMo#6398]
The documentation at [https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/nlp/nemo_megatron/parallelisms.html] states that

`NeMo Megatron supports 4 types of parallelisms (can be mixed together arbitraritly)`

The documentation at [https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/nlp/megatron.html#model-parallelism] states that

`Currently, NeMo only supports tensor model parallelism.`

This seems inconsistent. What kind of parallelisms are supported for training and eval? Thanks!

**Comment by ericharper** [comment]
NM supports 4 types of parallelism. Will send a PR cleaning up the documentation.

**Comment by nilsjohanbjorck** [comment]
Awesome, thanks! I'd want to play around with the different types of parallelisms available. E.g. just train a model with 1 hidden layer on some dummy data. Any pointers regarding tutorials for this?

**Comment by ericharper** [comment]
We don't have such a tutorial but it would be very nice to have!
