### ISSUE TITLE
Config `share_embeddings_and_output_weights` does not work.

### ISSUE THREAD

**Issue by flymark2010** [NVIDIA/NeMo#6406]
**Describe the bug**

The code [here](https://github.com/NVIDIA/NeMo/blob/ecc116c29a14534abfe393f6eee4339b24ca6e57/nemo/collections/nlp/modules/common/megatron/module.py#L262) init the super class [MegatronModule](https://github.com/NVIDIA/NeMo/blob/ecc116c29a14534abfe393f6eee4339b24ca6e57/nemo/collections/nlp/modules/common/megatron/module.py#L46)  with default parameter `share_token_embeddings=True`, so the attribute `share_embeddings_and_output_weights` of the input `module` parameter will never be used in `Float16Module`. Is that a bug or designed?

**Comment by MaximumEntropy** [comment]
Hi, thanks for raising this issue. We're working on a fix here https://github.com/NVIDIA/NeMo/pull/6276.
