### ISSUE TITLE
Is MoE implemented correctly?

### ISSUE THREAD

**Issue by njb-ms** [NVIDIA/NeMo#6410]
MoE FFNs are supposed to be sharded between GPUs. It seems like the current MoE implementation puts all FFNs on each GPU. See e.g. `https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/modules/common/megatron/mlp.py#L321`. Am I missing something here?

**Comment by aklife97** [comment]
closing this issue. If there are any other questions, feel free to open a new issue
