### ISSUE TITLE
Mac m1 arm

### ISSUE THREAD

**Issue by PabloSergi** [NVIDIA/NeMo#6470]
Hello, i cant make docker container on mac m1, I get this error: failed to copy: httpReadSeeker: failed open: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 401 Unauthorized What to do with it?Authorization doesnt help.

**Comment by titu1994** [comment]
I don't think docker container will work with Mac. You can try the instructions on the installation page of docs to manually install the requirements for Mac for ASR
