### ISSUE TITLE
Broken Notebook

### ISSUE THREAD

**Issue by muxitox** [NVIDIA/NeMo#6503]
**Describe the bug**

The notebook in https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Offline_ASR.ipynb cannot be visualized as it says "The Notebook Does Not Appear to Be Valid JSON"

**Steps/Code to reproduce bug**

Open https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Offline_ASR.ipynb

**Comment by titu1994** [comment]
Fixed via https://github.com/NVIDIA/NeMo/pull/6561

**Comment by titu1994** [comment]
Thanks for finding the bug !
