### ISSUE TITLE
False error message: 'last epoch number of samples exceeded max value' when training model

### ISSUE THREAD

**Issue by singleheart** [NVIDIA/NeMo#6513]
**Describe the bug**

This bug occurs on a specific dataset where the data loading process mistakenly checks for `<` instead of `<=` in an assert statement, causing the "last epoch number of samples exceeded max value" error message to be falsely displayed.

**Steps/Code to reproduce bug**

1. Prepare a dataset and configure the GPT training. The size of the model is not important.
2. Start the training process.
3. During the data loading phase, the issue arises.

This issue does not occur on all datasets. It is difficult to specify which datasets it occurs on.

**Expected behavior**

If the training process excludes the dataset where the issue occurs, it proceeds normally.

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal with slurm and enroot
 - Method of NeMo install: `docker pull nvcr.io/ea-bignlp/bignlp-training:23.03-py3`
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Additional context**

It appears that https://github.com/NVIDIA/NeMo/blob/65db9359bcb1cee96ffe13f36325f66bb8f17fd5/nemo/collections/nlp/data/language_modeling/megatron/gpt_dataset.py#L588-L590 is causing the issue. It should work properly if `<=` is used instead.

**Comment by ericharper** [comment]
This should be resolved in 1.19.0: #6798
