### ISSUE TITLE
Facing issue when i run model with my own audio file

### ISSUE THREAD

**Issue by 21pa1a05d1ganesh** [NVIDIA/NeMo#6516]
Specifically, it would be helpful to know the audio format, bitrate, size and sampling rate of the audio file. These details will help me to identify any potential issues that might be causing the problem.
![issue1](https://user-images.githubusercontent.com/105053572/235134513-93dcd5f7-8144-4c40-9551-293493ce3378.png)

**Comment by nithinraok** [comment]
Audio is fine, looks like the audio contains only silence. If audio has speech then change vad threshold for this specific audio.

**Comment by 21pa1a05d1ganesh** [comment]
No the file which i sent as input contains audio
