### ISSUE TITLE
ModuleNotFoundError: No module named 'kenlm_utils'

### ISSUE THREAD

**Issue by marziye-A** [NVIDIA/NeMo#6534]
hi, 
while trying to import "kenlm_utils" i face this error:

ModuleNotFoundError: No module named 'kenlm_utils'

and after manually adding kenlm_utils.py to my directory i encounter the  following error:

"UnsupportedOperation                      Traceback (most recent call last)
[<ipython-input-29-cec13af5ea4e>](https://localhost:8080/#) in <cell line: 83>()
     82 
     83 if __name__ == '__main__':
---> 84     main()

3 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in _get_handles(self, stdin, stdout, stderr)
   1636             else:
   1637                 # Assuming file-like object
-> 1638                 c2pwrite = stdout.fileno()
   1639 
   1640             if stderr is None:

UnsupportedOperation: fileno"

any help is really appreciated.
thanks!

**Comment by titu1994** [comment]
@karpnv please take a look

**Comment by karpnv** [comment]
Hi, can you provide more details how do you use it?
kenlm_utils is a utility file [scripts/asr_language_modeling/ngram_lm/kenlm_utils.py](https://github.com/NVIDIA/NeMo/blob/main/scripts/asr_language_modeling/ngram_lm/kenlm_utils.py). It suppose to import from train_kenlm.py while it is in the same folder with kenlm_utils.py. 
Usage example:
```shell
python /home/user/NeMo/scripts/asr_language_modeling/ngram_lm/train_kenlm.py \
                   nemo_model_file=/path/to/the/model.nemo \
                   train_file=/path/to/the/training/text.txt \
                   kenlm_bin_path=/path/to/the/bin/folder/of/KenLM/bin \
                   kenlm_model_file=/path/to/store/the/binary/KenLM/model \
                   ngram_length=5
``` 
From root NeMo folder you can import it as `from scripts.asr_language_modeling.ngram_lm import kenlm_utils` but not sure if you really need it.

**Comment by marziye-A** [comment]
thank you so much.it really helped!

**Comment by titu1994** [comment]
@karpnv can you add that instruction to the NeMo docs page next week
