### ISSUE TITLE
GPT-2B-001_bf16_tp1 gibberish on 4090

### ISSUE THREAD

**Issue by lizelive** [NVIDIA/NeMo#6564]
using the image `nvcr.io/nvidia/nemo:23.02`
4090
start server with
`python /workspace/nemo/examples/nlp/language_modeling/megatron_gpt_eval.py gpt_model_file=GPT-2B-001_bf16_tp1.nemo trainer.precision=bf16 server=True tensor_model_parallel_size=1 trainer.devices=1`
run unmodified sample code
```python
import json
import requests

port_num = 5555
headers = {"Content-Type": "application/json"}

def request_data(data):
    resp = requests.put('http://localhost:{}/generate'.format(port_num),
                        data=json.dumps(data),
                        headers=headers)
    sentences = resp.json()['sentences']
    return sentences


data = {
    "sentences": ["Tell me an interesting fact about space travel."]*1,
    "tokens_to_generate": 50,
    "temperature": 1.0,
    "add_BOS": True,
    "top_k": 0,
    "top_p": 0.9,
    "greedy": False,
    "all_probs": False,
    "repetition_penalty": 1.2,
    "min_tokens_to_generate": 2,
}

sentences = request_data(data)
print(sentences[0])
```
output (gibberish) 
> Tell me an interesting fact about space travel. My version of health. A method of therapy for gonorrhoea by a man. A man presented with this complaint of "despair for me for a man for a man with gonorrhea. I presented to a man with gonoragia. My man

**Comment by MaximumEntropy** [comment]
This was poor example of a prompt for us to include in the HF model card - Can you try a prompt that is more friendly for a base model ex: "It was a warm summer morning when". This is a base LM rather than one that has instruction-following ability.
