### ISSUE TITLE
transcribe multilanguage in multilingual model

### ISSUE THREAD

**Issue by alexandercesarr** [NVIDIA/NeMo#6585]
I took a multilingual pretrained english model and wanted to fine-tune it for ASR task on english and arabic together at once. I used a tokenizer that contains both English and arabic manifest.

Can this https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/multilang/conformer_ctc_bpe_multilang.yaml
Setting give results like this if yes then how. I was not able to find one.
I want the transcription to be:
مرحبًا ، أريد apple لذيذة

I've checked the tutorial file https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Multilang_ASR.ipynb but in this tutorial in the inference, it is a sample just for english and the other one is just for spanish. In fact it doesn't have an inference that transcribe a multi-languange like I said.

How one can do code switching? I wanna transcribe an audio file that a person speak in english and arabic simultaneously?

**Comment by alexandercesarr** [comment]
@titu1994

**Comment by titu1994** [comment]
We do support that, it is called code switched ASR. To create synthetic code switched dataset you can use this - https://github.com/NVIDIA/NeMo/tree/main/scripts/speech_recognition/code_switching

If you have a shared tokenizer for both Arabic and English then you don't need to follow the multi lingual ASR tutorial and train as a ordinary ASR training task. You will however not get per timestep language id, which may be ok. 

For shared tokenizer, there is no special trick - simply have ground truth data that contains both English and Arabic text + speech and train it as always. However if you don't have any code switched train data, you need to create language specific Tokenizers and use the code switch script above. 

To note, there is going to be a major upgrade of code switching which will enable lots of more complex capabilities but you don't need to wait for that - you can try a first model with the current code in main. See pr https://github.com/NVIDIA/NeMo/pull/6579

cc @bmwshop @KunalDhawan we need to significantly improve docs for code switching.
