### ISSUE TITLE
language model training toolkit

### ISSUE THREAD

**Issue by marziye-A** [NVIDIA/NeMo#6586]
hello
what language model training toolkit does nemo uses for asr language model training?

**Comment by titu1994** [comment]
We use kenlm for ASR. More information can be found in https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html

**Comment by marziye-A** [comment]
as much as i know, kenlm is just for querying language models not for training them.
that page doesn't mention anything about that.

**Comment by marziye-A** [comment]
thank you very much for your answer!
