### ISSUE TITLE
ASR inference stops without any error

### ISSUE THREAD

**Issue by appledora** [NVIDIA/NeMo#6587]
I am following [this tutorial](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/examples/kinyarwanda_asr.html) for training and evaluating a conformer-BPE model. 
The training has finished properly and I have a `.nemo` file. I have tried following the inference script [here](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/examples/kinyarwanda_asr.html#inference-and-evaluation) on `colab pro` to no avail. The code just stops when it has to iterate over the batches. *There are no errors*. The final line is given below: 
```bash
Transcribing:   0% 0/235 [00:00<?, ?it/s]^C
``` 

This is the script I am using : 
```bash 
! HYDRA_FULL_ERROR=1 python3 ./NeMo/examples/asr/transcribe_speech.py \
  model_path=./assets/Conformer-CTC-BPE.nemo \
  dataset_manifest=./speech_test_dataset_transcript.json \
  output_filename=test_with_predictions.json \
  batch_size=32 \
  overwrite_transcripts=false
```

Can anyone please guide me here? I have also tried tinkering with the class file at  `NeMo/nemo/collections/asr/models/ctc_models.py`

**Comment by titu1994** [comment]
Can you try with on a CPU colab to see if disabling cuda works ? That might raise an appropriate error hopefully. Since theirs no stack trace it's hard to debug.

**Comment by titu1994** [comment]
You have to process your audio to be mono channel, 16 kHz.

**Comment by appledora** [comment]
This has been such a great help so far. I mistakenly expected my audio files to be preprocessed to be sampled! 
Again, huge thanks for both the support and the amazing repo!!

**Comment by tomasruizt** [comment]
> You have to process your audio to be mono channel, 16 kHz.

Here is the code I use for this:
```python
def to_16k_mono_audio(file: str) -> np.ndarray:
    audio_arr, sr = librosa.load(file, sr=None)

    if len(audio_arr.shape) > 1:
        audio_arr = librosa.to_mono(audio_arr)

    if sr != 16000:
        audio_arr = librosa.resample(audio_arr, orig_sr=sr, target_sr=16000)

    return audio_arr
```
