### ISSUE TITLE
AttributeError: module 'megatron.core.parallel_state' has no attribute 'get_amax_reduction_group'

### ISSUE THREAD

**Issue by yen-shi** [NVIDIA/NeMo#6625]
**Describe the bug**

When running megatron_gpt_eval.py with an FP8 model, The FP8 path is run and not able to find `get_amax_reduction_group()` in parallel_state.

The error is triggered at this line:
https://github.com/NVIDIA/NeMo/blob/21048627b3923c9268842990aafdef141bd14bd1/nemo/collections/nlp/modules/common/megatron/transformer.py#LL1432C70-L1432C70

**Steps/Code to reproduce bug**

Get a model trained with TE FP8

Run:
python megatron_gpt_eval.py gpt_model_file=models/5b_fp8_tp1.nemo

**Expected behavior**

The script is expected to finish and generate outputs.

**Environment overview (please complete the following information)**

 - Environment location: 
 Container: nvcr.io/nvidia/pytorch:23.03-py3
 - Method of NeMo install:
 Call `./reinstall.sh` on main branch commit c3deeac8d58f48e9283d13fb7c32fd259605705f
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 docker run --gpus '"device=0"' -it --ipc=host --ulimit memlock=-1 -v /home/scratch.yenshiw_sw/NeMo:/workspace/local-nemo --ulimit stack=67108864 nvcr.io/nvidia/pytorch:23.03-py3

**Environment details**

**Additional context**

I cannot find name `get_amax_reduction_group` in megatron source code (parallel_state):
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/parallel_state.py

**Comment by timmoon10** [comment]
Looks like this is a bug from switching from Apex to Megatron-core (https://github.com/NVIDIA/NeMo/pull/6393). There was some recent MLPerf-related development in Apex that optimized AMAX reductions in Transformer Engine (https://github.com/NVIDIA/apex/pull/1585, https://github.com/NVIDIA/apex/pull/1597).

Perhaps this belongs as its own issue, but I see more recent changes in Apex that haven't made their way to Megatron-core:
- Userbuffers support: https://github.com/NVIDIA/apex/pull/1626
- NCCL configuration for certain systems: https://github.com/NVIDIA/apex/pull/1620
- Overlapped pipeline communication with interleaved pipeline parallelism: https://github.com/NVIDIA/apex/pull/1616

**Comment by aklife97** [comment]
@erhoo82, thanks to @timmoon10 this is already in core now.
I'm waiting for #6627 to merge, and we should be able to close this issue
