### ISSUE TITLE
lang field in Multilingual ASR models

### ISSUE THREAD

**Issue by kthworks** [NVIDIA/NeMo#6645]
Hello, 

I have a question about Multilingual ASR models.

In a Multilingual ASR model, when using an Aggregate tokenizer, the "lang" field needs to be added in the manifest. From what I understand from tech blogs and tutorials, the "lang" field is primarily used to assign offset indices to tokens for each language during token aggregation.

However, I'm curious if the "lang" field in Multilingual models is utilized for purposes other than token indexing. For example, I would like to know if it is designed to provide language information in the form of a one-hot vector or embedding vector, which can assist in the training process of the model.

Thank you

**Comment by titu1994** [comment]
That can be one option, to give apriori information of which language the user wants to transcribe the text to. 
In NeMo we do not do this currently and instead only use it for indexing. 
There's other ways to use it - if you have monolingual corpus with lang id prepared, you can use scripts we have to generate code switched multilingual ASR models that can transcribe two or more languages in the same sentence

**Comment by kthworks** [comment]
Thank you for your reply!
