### ISSUE TITLE
Error in Aggregate Tokenizer for multilingual ASR

### ISSUE THREAD

**Issue by kthworks** [NVIDIA/NeMo#6661]
Hello, 
I built Multilingual ASR model with Korean and English.
However, I found that tokens are assigned not correctly.

I used 128 tokens for english, and 1641 tokens for korean (Total 1749)
when i checked vocabulary, there were several suspicious points.

When i printed asr_model.tokenizer.langs_by_token_id, it correctly shows tokens. (from 0 to 128 : 'en', from 129 to 1749: 'kor').
However, some alphabet token is assigned in korean. For example, print(asr_model.tokenizer.token_to_id('q', 'kor')) results 1702.

Also, in my knowledge, the aggregated tokenizer must remove duplicated token such as 'unkown'. But, there is two 'unk' tokens in both index 0 and 128

I also saw same phenomonon in pretrained_model, Conformer_transducer_enes_large.

1. tokens such as 'pre', 'ble' 'is', 'to' etc are assigned in Es, not En. I think these tokens are close to english tokens rather than spanish token.

2. there were two 'unk' tokens. 
print(asr_model.tokenizer.token_to_id('unk', 'en')) results in 0, and
print(asr_model.tokenizer.token_to_id('unk', 'es')) results in 1024.

**Comment by bmwshop** [comment]
I believe this is working as designed currently. Each language uses a separately trained tokenizer - potentially, on a much larger text-only corpora -  and a consequence, has a non-overlapping set of tokens. Therefore, yes, there may be two 'unk' tokens - as well as any number of others. In this design, we do not attempt to find and handle duplicate tokens or merge the tokenizers. As a consequence, it is easy to determine language ID from the id of each token.
