### ISSUE TITLE
Speaker Recognition with clean and phone call audio

### ISSUE THREAD

**Issue by ihfreitas** [NVIDIA/NeMo#6684]
Hello everyone,
We are working on a project that identifies if is the same person in different audios, basically speaker recognition. We put 75% of threshold to identify the same person.

We work with clean audios and phone call audios in Portuguese, the correct was have a model for each audio type, or could join these two audio type for a robust model? For example, I do a train only with phone call audios and after that a finetune with clean audios, or the other way around.
We try to do both together, a train with two dataset and a finetune with two dataset, and we had an unsatisfactory result

```
Clean audios, 44959 train, 2351 dev

Predict           Fraud                 Same Person              

Fraud             23060                 13.925                            

Same Person       18                    449                                 


Clean and phone call audios, 11334 train, 1214 dev

Predict           Fraud                Same Person              

Fraud             20921                16.064                            

Same Person       6                    461   


Phone call audios, 6658 train, 975 dev

Predict           Fraud                 Same Person              

Fraud             35271                 1.714                           

Same Person       78                    389                            

```

For parameters we're using 'titanet-large', 32 batch_size for both, 0.011823477534453206 for lr,  0.07095099595312822 for margin, 60 for scale, 'sgd' optimizer and 2 epochs.

Here some audios that we have problem to identify as different persons:
[WrongResults.zip](https://github.com/NVIDIA/NeMo/files/11531858/WrongResults.zip)
All of these audios have a high score to the wrong person, like 85% to 90% of confidence.

With this context, make sense this results? Why I get this high confidence with different persons? Have any way to improve this results? And how many audios are expected to have a good result?
Also we use an issue, https://github.com/NVIDIA/NeMo/issues/5930, as recommendation to train and test.

**Comment by jeremy110** [comment]
How many people were used to fine-tune the Titanet-Large dataset? Typically, a dataset with more than a thousand people is considered more effective.
