### ISSUE TITLE
Can save the base Diarizer model.

### ISSUE THREAD

**Issue by HatterTheMad** [NVIDIA/NeMo#6712]
**Describe the bug**

I get the following error

```
AttributeError                            Traceback (most recent call last)

[<ipython-input-55-5354c1522db5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 msdd_model.save_to(save_path="xyz.nemo")

1 frames

[/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/models/msdd_models.py](https://localhost:8080/#) in save_to(self, save_path)
   1036             self.clus_diar._speaker_model.save_to(spkr_model)
   1037             self.msdd_model.save_to(neural_diar_model)
-> 1038             self.clus_diar.__make_nemo_file_from_folder(filename=save_path, source_dir=tmpdir)
   1039 
   1040     def extract_standalone_speaker_model(self, prefix: str = 'msdd._speaker_model.') -> Dict:

AttributeError: 'ClusteringDiarizer' object has no attribute '_NeuralDiarizer__make_nemo_file_from_folder'
```

**Steps/Code to reproduce bug**

This is literally all the code I am trying to run on google colab.
```
msdd_model = NeuralDiarizer(cfg=create_config())
msdd_model.save_to(save_path="xyz.nemo")
```
Everything else works the model works etc

**Expected behavior**

I expected the model to be saved.

**Environment overview (please complete the following information)**

 - Environment location: Collab
 - Method of NeMo install: !pip install nemo_toolkit[asr]

**Environment details**

- PyTorch version 1.13.1+cu116

**Comment by tango4j** [comment]
Hi.

It appears that you have created an attribute named `_NeuralDiarizer__make_nemo_file_from_folder` that does not exist in the original class. Can you check that part?
