### ISSUE TITLE
Not finding correct phoneme dictionary file for tts_es_fastpitch_multispeaker

### ISSUE THREAD

**Issue by MatiasDiBernardo** [NVIDIA/NeMo#6720]
Hello, I want to finetune the tts_es_fastpitch_multispeaker model but I don't know where to find the correct file for the phoneme dictionary. This is the code I’m running for finetuning:

`!(python fastpitch_finetune.py --config-name=fastpitch_align_44100_ipa_multi.yaml \
  train_dataset=./transcript_train.json \
  validation_datasets=./transcript_dev.json \
  sup_data_path=./fastpitch_sup_data \
  pitch_stats_path=tts_dataset_files/pitch_stats.json \
  phoneme_dict_path=tts_dataset_files/es_LA_nv230301.dict \
  exp_manager.exp_dir=./ljspeech_to_9017_no_mixing_5_mins \
  +init_from_nemo_model=./tts_es_fastpitch_multispeaker.nemo \
  trainer.check_val_every_n_epoch=25 \
  model.train_ds.dataloader_params.batch_size=12 model.validation_ds.dataloader_params.batch_size=12 \
  model.n_speakers=174 \
  model.pitch_fmin=30 model.pitch_fmax=512 model.optim.lr=2e-4 \
  ~model.optim.sched model.optim.name=adam trainer.devices=1 trainer.strategy=null \
)`

I tried with the two phoneme files avaliable in this repository:
`
NeMo/scripts/tts_dataset_files/es_ES/es_ES_nv230301.dict
`
`NeMo/scripts/tts_dataset_files/es_LA/es_LA_nv230301.dict`

And with both I have this error:
`size mismatch for fastpitch.encoder.word_emb.weight: copying a param with shape torch.Size([101, 384]) from checkpoint, the shape in current model is torch.Size([103, 384]).`

I was able to by pass this by simple removing some lines from one of the files but, if possible, I would like to use the same dictionary used in the original training to avoid unknown char/phoneme errors. Thanks.

**Comment by MatiasDiBernardo** [comment]
@rlangman any idea?

**Comment by rlangman** [comment]
Sorry for the late reply.

I don't think the issue is with the dictionary itself. The code that is parsing it to determine the vocabulary was changed a while ago. We need to retrain it and upload a new checkpoint that is compatible with the current code.

Until then we did include a "fixed_vocab" argument as a workaround for this issue https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/common/tokenizers/text_to_speech/tts_tokenizers.py#L508.

The vocab for the pretrained Spanish model is:

```
from nemo.collections.tts.models.fastpitch import FastPitchModel

model = FastPitchModel.from_pretrained("tts_es_fastpitch_multispeaker")

print(model.vocab.tokens)
```
```
['!',  '"',  "'",  '(',  ')',  ',',  '-',  '.',  '/',  ':',  ';',  '?',  'A',  'B',  'C',  'D',  'E',  'F',  'G',  'H',  'I',  'J',  'K',  'L',  'M',  'N',  'O',  'P',  'Q',  'R',  'S',  'T',  'U',  'V',  'W',  'X',  'Y',  'Z',  '[',  ']',  'a',  'b',  'd',  'e',  'f',  'h',  'i',  'j',  'k',  'l',  'm',  'n',  'o',  'p',  'r',  's',  't',  'u',  'w',  'x',  '{',  '}',  '¡',  '«',  '»',  '¿',  'Á',  'Ç',  'É',  'Í',  'Î',  'Ñ',  'Ó',  'Ö',  'Ú',  'Ü',  'Ý',  'ð',  'ŋ',  'ə',  'ɛ',  'ɟ',  'ɡ',  'ɣ',  'ɪ',  'ɲ',  'ɾ',  'ʃ',  'ʊ',  'ʎ',  'ʒ',  'ʝ',  'ˈ',  'ˌ',  'ː',  'β',  '‹',  '›',  ' ',  '<pad>',  '<oov>']
```
