### ISSUE TITLE
Results for ASR

### ISSUE THREAD

**Issue by cyaaronk** [NVIDIA/NeMo#6736]
Dear Sir/Madam,

Do you have results of ASR models on benchmark datatsets? I want to compare your toolkit with wenet/espnet.

Best regards,
Aaron

**Comment by VahidooX** [comment]
Which model are you looking for? 
You may find a list of most of the models here:
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/results.html

You can also find some results here:
https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/scores.html

If you want more numbers, you need to look into the NGC or HF page of the model, for example:
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_fastconformer_transducer_xxlarge
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_fastconformer_transducer_large
https://huggingface.co/nvidia/stt_en_fastconformer_transducer_xxlarge
