### ISSUE TITLE
How can I export titanet-l model to onnx?

### ISSUE THREAD

**Issue by gabitza-tech** [NVIDIA/NeMo#6759]
Hello, I have exported the marblenet vad model to onnx using the https://github.com/NVIDIA/NeMo/blob/stable/tutorials/asr/Online_Offline_Microphone_VAD_Demo.ipynb tutorial. 

Unfortunately, when I try to replicate the steps for the titanet model in the _extract_embeddings function, but it doesn't work.

Is there a tutorial about exporting the speaker model to onnx, or is it possible to export ?

```
    def _extract_embeddings(self, manifest_file: str, scale_idx: int, num_scales: int):
        """
        This method extracts speaker embeddings from segments passed through manifest_file
        Optionally you may save the intermediate speaker embeddings for debugging or any use. 
        """
        self._setup_spkr_test_data(manifest_file)
        self.embeddings = {}
        self._speaker_model = self._speaker_model.to(self._device)
        self._speaker_model.eval()
        self.time_stamps = {}
        
        self.speaker_model.export('titanet_l.onnx')
        ort_session = onnxruntime.InferenceSession('titanet_l.onnx')
        
        all_embs = torch.empty([0])
        for test_batch in tqdm(self._speaker_model.test_dataloader(), desc=f'[{scale_idx+1}/{num_scales}] extract embeddings',leave=True):
            test_batch = [x.to(self._device) for x in test_batch]
            processed_signal, processed_signal_len = self.speaker_model.preprocessor(input_signal=test_batch[0],length=test_batch[1])
            with autocast():
                
                #_, embs = self._speaker_model.forward(input_signal=test_batch[0], input_signal_length=test_batch[1])
                ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(processed_signal), }
                _,ologits = ort_session.run(None, ort_inputs)
                alogits = np.asarray(ologits)
                logits = torch.from_numpy(alogits[0])
                emb_shape = ologits.shape[-1]
                embs = embs.view(-1, emb_shape)
                all_embs = torch.cat((all_embs, embs.cpu().detach()), dim=0)
                
            del test_batch```

```[tasklist]
### Tasks
```

**Comment by nithinraok** [comment]
Did you try with this script? 
https://github.com/NVIDIA/NeMo/blob/main/scripts/export.py

**Comment by gabitza-tech** [comment]
Hey, thanks for the response. I managed to solve it eventually. This is the code for anyone that might need help using embeddings extractors with onnx model:

```python
    def _extract_embeddings(self, manifest_file: str, scale_idx: int, num_scales: int):
        """
        This method extracts speaker embeddings from segments passed through manifest_file
        Optionally you may save the intermediate speaker embeddings for debugging or any use. 
        """
        
        self._speaker_model = self._speaker_model.to(self._device)
        self._speaker_model.eval()
        self._speaker_model.export('nemo_models/titanet-l.onnx')

        sess = ort.InferenceSession('nemo_models/titanet-l.onnx')
       
        self._setup_spkr_test_data(manifest_file)
        self.embeddings = {}
        self.time_stamps = {}
        all_embs = torch.empty([0])
        for test_batch in tqdm(self._speaker_model.test_dataloader(), desc=f'[{scale_idx+1}/{num_scales}] extract embeddings',leave=True):
            test_batch = [x.to(self._device) for x in test_batch]

            processed_signal, processed_signal_len = self._speaker_model.preprocessor(input_signal=test_batch[0].to(self._speaker_model.device),length=test_batch[1].to(self._speaker_model.device))
            
            with autocast():
                ort_inputs = {sess.get_inputs()[0].name: self.to_numpy(processed_signal),sess.get_inputs()[1].name: self.to_numpy(processed_signal_len) }
                _,oembs = sess.run(None, ort_inputs)

                aembs = np.asarray(oembs)
                aembs = torch.from_numpy(aembs)

                all_embs = torch.cat((all_embs, aembs.cpu().detach()), dim=0)
                

            del test_batch
```

NOTE: I did not use it, it didn't provide any speed-up/memory reduction. I recommend using: `with torch.no_grad():` and the normal `self._speaker_model.forward(...)` code.

**Comment by divyansh2681** [comment]
When exporting a model from nemo to onnx, I get separate files for encoder, decoder and the weights. How do I get a single file for the whole model?

**Comment by divyansh2681** [comment]
> Did you try with this script? https://github.com/NVIDIA/NeMo/blob/main/scripts/export.py

When exporting a model from nemo to onnx, I get separate files for encoder, decoder and the weights. How do I get a single file for the whole model?

**Comment by nithinraok** [comment]
What is the command have you used to export? Using `titanet-l.nemo` you should get only onnx file as output.

**Comment by divyansh2681** [comment]
> What is the command have you used to export? Using `titanet-l.nemo` you should get only one onnx file as output.

Oh sorry, I am using a different model. I am converting the stt_en_fastconformer_transducer_xxlarge.nemo model to onnx. Using the given export.py, I get multiple files.

**Comment by nithinraok** [comment]
What is the command have you tried. If you cannot post your running script, its hard to comprehend the issue.

**Comment by divyansh2681** [comment]
> What is the command have you tried. If you cannot post your running script, its hard to comprehend the issue.

the command that I used is:
python3 export.py /path-to-nemo-file /path-to-onnx
example: python3 export.py stt_en_fastconformer_transducer_xxlarge.nemo model.onnx

**Comment by divyansh2681** [comment]
I have another question, if you could answer that too, please: When I run inference using the converted onnx model (the smaller model), the time taken for transcription is much much more as compared to the normal nemo model. Are you aware of the reason/solution to this issue?

**Comment by nithinraok** [comment]
Can you post another question as a new issue? That would help to track it easily. Regarding creation of multiple onnx files, looks like it is happening with transducer nemo files. @borisfom can you look at this issue?

**Comment by divyansh2681** [comment]
> Can you post another question as a new issue? That would help to track it easily. Regarding creation of multiple onnx files, looks like it is happening with transducer nemo files. @borisfom can you look at this issue?

Sure, I will create a new issue for the 2nd question. Thank you!

**Comment by borisfom** [comment]
Multiple files are being produced because "external weights" option is being forced when the size of ONNX file would be > 2G (protobuf binary can't be large than this). This is perfectly normal. 
Re ONNX (I assume onnxruntime) speed: how big is the slowdown ? Some classes of networks are know to run slower in onnxruntime than in PyTorch. Are you sure you running it on GPU? Which EP (execution provider): CUDA or TRT ?

**Comment by divyansh2681** [comment]
> Multiple files are being produced because "external weights" option is being forced when the size of ONNX file would be > 2G (protobuf binary can't be large than this). This is perfectly normal. Re ONNX (I assume onnxruntime) speed: how big is the slowdown ? Some classes of networks are know to run slower in onnxruntime than in PyTorch. Are you sure you running it on GPU? Which EP (execution provider): CUDA or TRT ?

If I want to use a model for which onnx is > 2G, do I need to load the encoder and decoder separately? Or is there any other way around this? 

Regarding the execution time issuse -->
I was using TRT until now. I tried using CPU and GPU as well. With TensorRT, it takes 36 seconds for the onnxruntime, with CUDA it takes 2 seconds, with CPU it takes 0.05 seconds. 

When using CUDA, I get a warning:
W:onnxruntime:, session_state.cc:1169 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
[W:onnxruntime:, session_state.cc:1171 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.

I want to run it on CUDA and not CPU, how can I resolve this?

**Comment by divyansh2681** [comment]
@borisfom If I want to use the exported onnx model with onnxruntime, how are the weights to be used?
