### ISSUE TITLE
[Bug] A bug in filtering checkpoints

### ISSUE THREAD

**Issue by yaox12** [NVIDIA/NeMo#6796]
**Describe the bug**

https://github.com/NVIDIA/NeMo/blob/cfbe0924db02a1a557aeeea55cc1a01b83903e71/nemo/utils/callbacks/nemo_model_checkpoint.py#L98-L99

I think Line 99 should be
```python
 if index != len(self.monitor): 
```

**Comment by titu1994** [comment]
-1 seems correct, do you have a case where it breaks ?

**Comment by yaox12** [comment]
When we cannot find `self.monitor` in `checkpoint`, `checkpoint.find(self.monitor)` should be -1 so index should be `len(self.monitor)`.

With the current code, `mp_rank_00_model_weights.ckpt` would go to the True condition and cause an error in Line 103 because  it cannot find the correct `value` to be converted to float.
https://github.com/NVIDIA/NeMo/blob/5c3ed943d8b23ae32719f8fd0e51fca5801596d3/nemo/utils/callbacks/nemo_model_checkpoint.py#L98-L103
