### ISSUE TITLE
[question] Pad time-dimension to a multiple

### ISSUE THREAD

**Issue by vadimkantorov** [NVIDIA/NeMo#6797]
For Conformer setups, does NeMo support / recommend padding batches after frontend to a certain multiple, e.g. so that after Conformer input batch time dimension is e.g. a multiple of 32 (which may suit best cudnn / gemm kernels for fp16/TensorCores)

Having batches of a few fixed shapes also benefits pytorch allocator performance and cudnn benchmarking / cache

**Comment by vadimkantorov** [comment]
Having a small fixed collection of batch shapes is important for benefitting from CUDA graphs btw and its integration into torch.compile: https://github.com/pytorch/pytorch/pull/103290

**Comment by titu1994** [comment]
You can use "pad_to" in the preprocessor for CTC models. It is risky to do so for the RNNT and hybrid models as the cuda kernels cannot tolerate any padding.

**Comment by vadimkantorov** [comment]
Any reason why RNNT losses have problems with the padding of the longest example?

Because they have to work with padding anyway, so this constraint seems quite arbitrary and maybe workaroundable. Is it just for saving time for Joiner? If so, it should not be a blocker at least.

I would argue that the best way for this would be to implement some proper padding-less functioning (e.g. with NestedTensor)
