### ISSUE TITLE
tts_infer.py so slow...

### ISSUE THREAD

**Issue by laohur** [NVIDIA/NeMo#681]
- more than 6s on Tesla V100 for one sentence.

tried default, optimized. batch_size=1
 only nf.infer(text_embedding) cost 3.7s
 all cost ~6s

And asr qps ~25 on V100.

- As generate torch.tensors for export input_examples failed ,is thers a reliable way to convert modules to onnx/torchscript/trt or load as native torch ?

- what is the general way to speedup such nemo infer qps?

**Comment by okuchaiev** [comment]
increasing batch size will greatly improve throughput. 
You can convert modules used in ASR into .onnx. Have a look at these scripts: https://github.com/NVIDIA/NeMo/blob/master/scripts/export_jasper_to_onnx.py

In general, NeMo is focused on training so its inference capabilities are rather basic. For a full, performance-oriented inference solution you might be interested to have a look at https://developer.nvidia.com/nvidia-jarvis

**Comment by Mddct** [comment]
How to write feature extraction for onnx

**Comment by laohur** [comment]
> 
> 
> increasing batch size will greatly improve throughput.
> You can convert modules used in ASR into .onnx. Have a look at these scripts: https://github.com/NVIDIA/NeMo/blob/master/scripts/export_jasper_to_onnx.py
> 
> In general, NeMo is focused on training so its inference capabilities are rather basic. For a full, performance-oriented inference solution you might be interested to have a look at https://developer.nvidia.com/nvidia-jarvis

yeah。butb tts batch_size=4 still cost seconds. And asr nemo infer qps =20+. 
convertting tts(not asr) to onnx/torchscript meet many errors about torch.jit not supprotted.
when jarvis comes?
