### ISSUE TITLE
Diarization returning only 2 speakers with 3 in the audio

### ISSUE THREAD

**Issue by ihfreitas** [NVIDIA/NeMo#6848]
Hello everyone,
I'm working with speaker diarization to identify 2 or more speakers in the same audio. When I try that returns the same results, something like 2 speaker in a audio when have 3.

For that I using Neural Diarizer with titanet_large or my own model to speaker_embedding and 'diar_msdd_telephonic' to mssd model.
Parameters:
```
config.diarizer.manifest_filepath = 'data/input_manifest.json'
config.diarizer.out_dir = output_dir # Directory to store intermediate files and prediction outputs
pretrained_speaker_model = 'finetune-Epochs_2-Batch_32-sgd-Lr_0.011823477534453206-Scale_60-Margin_0.07095099595312822-Date_18-05-2023_10-26-20-917.nemo'
config.diarizer.speaker_embeddings.model_path = pretrained_speaker_model

config.diarizer.speaker_embeddings.parameters.window_length_in_sec = [1.5,1.25,1.0,0.75,0.5] #[1.5,1.25,1.0,0.75,0.5]
config.diarizer.speaker_embeddings.parameters.shift_length_in_sec = [0.75,0.625,0.5,0.375,0.1] #[0.75,0.625,0.5,0.375,0.1]
config.diarizer.speaker_embeddings.parameters.multiscale_weights= [0.5,0.5,0.5,0.5,0.5] #[1,1,1,1,1]

config.diarizer.msdd_model.model_path = 'diar_msdd_telephonic' # Telephonic speaker diarization model 
config.diarizer.msdd_model.parameters.sigmoid_threshold = [0.03] # Evaluate with T=0.7 and T=1.0
config.diarizer.msdd_model.parameters.infer_batch_size = 64
config.diarizer.msdd_model.parameters.seq_eval_mode = True 
config.diarizer.msdd_model.parameters.split_infer = True
config.diarizer.msdd_model.parameters.diar_window_length = 10
config.diarizer.msdd_model.parameters.overlap_infer_spk_limit = 8
```

I tried to change sigmoid_threshold between 0.02 - 0.7, diar_window_length between 5-50 and batch_size between 64-16 to improve the output

Here an example:
[diarized_1.zip](https://github.com/NVIDIA/NeMo/files/11708476/diarized_1.zip)
Just 2 speakers were recognized in a audio with 3 speakers.

Why can't I return 3 speakers with this parameters? How can I improve this results? Maybe I did something wrong? Maybe audios need to be cleaned up, doing that without noise?
Thanks in advance

**Comment by jeremy110** [comment]
Perhaps you should try longer audio files. It's more challenging to achieve better results with short audio files.

**Comment by ihfreitas** [comment]
Thank's for the advice, that's works better then I expected!

By the way, if you can help me with this issue I would be very grateful. I'm trying to do speaker recognition with short audio, and it's giving me bad results (issues I talk about: https://github.com/NVIDIA/NeMo/issues/6684, https://github.com/NVIDIA/NeMo/issues/6706). Could these results be from using short audio files? 
And again, thanks for the help

**Comment by robinjmf** [comment]
same problem here I have a relatively clean datum with 5 speakers but the model predicts 2 speakers.

here are my model configs:

config.diarizer.manifest_filepath = 'data/input_manifest.json'
config.diarizer.out_dir = output_dir # Directory to store intermediate files and prediction outputs
pretrained_speaker_model = 'titanet_large'
config.diarizer.speaker_embeddings.model_path = pretrained_speaker_model
config.diarizer.speaker_embeddings.parameters.window_length_in_sec = [1.5,1.25,1.0,0.75,0.5] 
config.diarizer.speaker_embeddings.parameters.shift_length_in_sec = [0.75,0.625,0.5,0.375,0.1] 
config.diarizer.speaker_embeddings.parameters.multiscale_weights= [1,1,1,1,1] 
config.diarizer.oracle_vad = True # ----> ORACLE VAD 
config.diarizer.clustering.parameters.oracle_num_speakers = 5
