### ISSUE TITLE
Do Contextnet and Squeezeformer support streaming training

### ISSUE THREAD

**Issue by nullscc** [NVIDIA/NeMo#6878]
So far, I know all ASR model but Contextnet and Squeezeformer in Nemo support streaming  training.

So I want to ask : Do Contextnet and Squeezeformer support streaming training?

BTW, by streaming  training, I mean chunk based like Cache-aware Streaming Conformer or model support streaming input itself during both training and inference stage, not the strategy just in inference stage like Buffered streaming.

Thanks in advance for anyone who give tips on this.

**Comment by titu1994** [comment]
No, context net and Squeezeformer do not support chunk aware streaming training or inference. Squeezeformer architecture is not suitable for this, and context net is a convolution architecture.

**Comment by titu1994** [comment]
On the other hand, Fast Conformer should support chunk aware training and inference.

**Comment by nullscc** [comment]
OK, thank you for your reply. Best!
