### ISSUE TITLE
Online_ASR_Microphone_Demo: 8kHz models

### ISSUE THREAD

**Issue by dmitrytyrin** [NVIDIA/NeMo#688]
Dear team,
thank you for amazing demo with online ASR!

How can I modify given example to use with 8k models?
I get this error:
```
NeuralPortNmTensorMismatchError: 

In AudioToMelSpectrogramPreprocessor. 
Port: input_signal and a NmTensor it was fed are 
of incompatible neural types:

axes: (batch, time);  elements_type: AudioSignal 

 and 

axes: (batch, time);  elements_type: AudioSignal

Type comparison result: NeuralTypeComparisonResult.SAME_TYPE_INCOMPATIBLE_PARAMS
```

Error comes from here:
```
processed_signal, processed_signal_len = data_preprocessor(
     input_signal=audio_signal,
---> length=audio_signal_len)
```

**Comment by okuchaiev** [comment]
If you are using your own 8Khz model, then in this line set sample_rate to 8000:
```python
data_layer = AudioDataLayer(sample_rate=model_definition['sample_rate'])
```

However, if you are using provided checkpoints, then all of them were trained using 16Khz audio, so you need to upsample your data to 16Khz.

Currently for 8Khz data we recommend upsampling 8Khz to 16Khz and using provided checkpoints on it. We did try to re-train our models on 8Khz data, but so far, that leads to a slightly worse results.

**Comment by dmitrytyrin** [comment]
This does not help... model_definition['sample_rate'] = 8000, it is taken from config file.
May be something wrong with ```output_ports``` in ```AudioDataLayer``` class?

**Comment by vsl9** [comment]
If you would like to do inference on 8 kHz test data with a model that was trained on 8 kHz data, then please pass `sample_rate` to the constructor of `AudioToMelSpectrogramPreprocessor`:
```python
data_preprocessor = nemo_asr.AudioToMelSpectrogramPreprocessor(
    sample_rate = model_definition['sample_rate'],
    **model_definition["AudioToMelSpectrogramPreprocessor"])
```

**Comment by dmitrytyrin** [comment]
@vsl9, thank you! Now it works.

**Comment by ArtemisZGL** [comment]
@okuchaiev hello, when you training your 8k model, did you just change the sample rate param, or have you change the kernel in the config file?
