### ISSUE TITLE
Finetuning ASR on another language (tokenizer)

### ISSUE THREAD

**Issue by gabitza-tech** [NVIDIA/NeMo#6895]
Hello, 

I would like to finetune the stt_en_conformer_transducer_medium on 200 hours of another language (romanian). I am at the tokenization step and I am unsure of what would be the best practice:

1. Prepare the tokens using the text from the training audio transcripts (around 2 million words, not necessarily different). I would use sentencepiece, with unigram and vocab of 1024.
2. Prepare the tokens using a big text corpus of around 50 million words, one that is usually used for training LMs. Same configuration.

I am unsure if it is ok to train the tokenizer on more text than the training audios, I was not able to find if this is an OK practice and can lead to better/worse results. I was thinking that it might generalize better if it has more possible tokens. The tokenizer I obtained on just 200 hours looked rather limited, with lots of big words that are not actually that common outside of the training set. However, I am scared that it might not learn to pronounce some tokens based on the audio dataset, but I consider this rather unlikely.

One last question would be: What are the "##" , "_", "_de", etc. tokens representing? 

Thank you in advance!

**Comment by titu1994** [comment]
You can absolutely train Tokenizers on more text than asr corpus alone. For such large corpus, it is impractical to use unigram, so spe bpe is a valid alternative which gives almost same results. 

Do note that beyond 1m words of text, using small vocabularies of 1024 may not have any significant different tokens between 50 M words or 1 m words. So you might not see any major change in wer between the two. 

We see barely 3-8 subword difference between 1m rows of text and 40m rows of text with a vocab size of 1024.  It has no effect on wer at that scale.

**Comment by gabitza-tech** [comment]
Hey @titu1994, thank you for your response! It would be more beneficial to me to solely train on the audios transcripts, as it would take much less time. But I am curios, the audios contain a "not so common vocabulary", but they contain subwords that would be found anywhere. In case of tokenizers, it matters if groups of characters are common, not the words themselves right?

**Comment by titu1994** [comment]
It matters only if your vocab size is large enough to get copies of words that are rarer as "subwords". It doesn't matter with vocab sizes of 1024. Between 50 M rows of text (some 4B words of more) and 1 M rows of text, only 3-8 subwords changes out of 1024

**Comment by gabitza-tech** [comment]
> It matters only if your vocab size is large enough to get copies of words that are rarer as "subwords". It doesn't matter with vocab sizes of 1024. Between 50 M rows of text (some 4B words of more) and 1 M rows of text, only 3-8 subwords changes out of 1024

And could you explain why you consider using BPE instead of unigram? From what I understood unigram achieves better results overall.

**Comment by titu1994** [comment]
Unigram takes more memory and much more time to build. The improvements over spe bpe also reduce significantly with the amount of data available

**Comment by titu1994** [comment]
Tokenization itself does improve wer compared to character encoding, but beyond that there is no need to tune your tokenizer

**Comment by gabitza-tech** [comment]
Thank you so much for all clarifications!
