### ISSUE TITLE
Support about Streaming inference of Conformer Transducer?

### ISSUE THREAD

**Issue by nullscc** [NVIDIA/NeMo#6905]
Does Nemo support about streaming inference of Conformer Transducer?

From my view, as long as Conformer Transducer trained using Cache-aware Streaming Conformer, then it can be used on streaming situation.

But from this: https://github.com/NVIDIA/NeMo/issues/3144#issuecomment-962420001, it seems we can train a Cache-aware Streaming based Conformer Transducer model to use it in streaming situation.

So my question is:
1. Can I train a Cache-aware Streaming based Conformer Transducer model using https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/cache_aware_streaming/conformer_transducer_bpe_streaming.yaml?
2. Can I inference using script from https://github.com/NVIDIA/NeMo/blob/main/examples/asr/asr_cache_aware_streaming/speech_to_text_cache_aware_streaming_infer.py with a Confomer Transducer model, which means does speech_to_text_cache_aware_streaming_infer.py support Cache-aware Streaming based Conformer Transducer model?
3. If I want use a Conformer Transducer model in streaming situation, what can I do for now? Because from Librispeech 960 experiments, it seems Conformer Transducer is best with respect to WER?

Thanks for any tips.

**Comment by VahidooX** [comment]
>Can I train a Cache-aware Streaming based Conformer Transducer model using https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/cache_aware_streaming/conformer_transducer_bpe_streaming.yaml?

Yes, but we recommend to use FastConformer version which is more than 2x faster in both train and inference:
https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/fastconformer/cache_aware_streaming/fastconformer_transducer_bpe_streaming.yaml

>Can I inference using script from https://github.com/NVIDIA/NeMo/blob/main/examples/asr/asr_cache_aware_streaming/speech_to_text_cache_aware_streaming_infer.py with a Confomer Transducer model, which means does speech_to_text_cache_aware_streaming_infer.py support Cache-aware Streaming based Conformer Transducer model?

If I understand your question correctly, you may use this script for models not trained with cache-aware (offline models) but the accuracy is bad. This script works best for cache-aware models and it supports Transducer models. 


>If I want use a Conformer Transducer model in streaming situation, what can I do for now? Because from Librispeech 960 experiments, it seems Conformer Transducer is best with respect to WER?
Do you mean using offline Transducer models or cache-aware models?
For using offline Transducer models in streaming mode, you need to use buffered streaming with this script:
https://github.com/NVIDIA/NeMo/blob/main/examples/asr/asr_chunked_inference/rnnt/speech_to_text_buffered_infer_rnnt.py
