### ISSUE TITLE
QuartzNet Inference on Triton

### ISSUE THREAD

**Issue by rinjac** [NVIDIA/NeMo#694]
Hello, 

I am wondering what is the best way to deploy the QuartzNet model on the Triton Inference Server.

You have provided the scripts with which I converted the QuartzNet encoder and decoder into TensorRT models. I created an ensemble of them in Triton and can call it for inference. 

However, how to include pre- and post-processing of QuartzNet in this setup? As far as I see, there are two options:

1. Do the pre-processing (for example, with a NeMo pipeline just for pre-processing), take the pre-processed tensor, send it to Triton for inference, get the result back, then do post-processing (for example, with a NeMo pipeline for post-processing). However, in this setup pre- and post-processing is not done in Triton. Can this cause bottlenecks in performance?
2. Perform pre- and post-processing in the Triton Inference Server. Triton supports custom backends, but they must be written in C++ (so all pre- and post- processing code from NeMo must be rewritten into C++). Is there an easier way to do this? 

Thank you in advance,
Robert

**Comment by okuchaiev** [comment]
NeMo is primarily concerned with training and fine-tuning. 
Once you've trained your ASR model, the most user-friendly and performance-efficient route to deploy ASR model would be to use Jarvis ASR service. I'd encourage you to apply for Jarvis early access here https://developer.nvidia.com/nvidia-jarvis 

If for whatever reason you can not use Jarvis, you can still deploy QuartzNet.
Your point # 2 is a good direction to go, but, of course, it would be more work on your side compared to using Jarvis service.
An alternative, and certainly, less performant way would be to just use Python/Pytorch and call forward pass (see our microphone notebook example). But I would not recommend using  this route for anything other than model testing, experimenting and prototyping.

**Comment by paklau99988** [comment]
Why do you discourage using Python/Pytorch and call forward passing?
