### ISSUE TITLE
No module named 'nemo.collections' 

### ISSUE THREAD

**Issue by muizzhaque** [NVIDIA/NeMo#6960]
I have followed the steps as mentioned in git repo for nemo, but each time I'm installing nemo_toolkit['all'] two packages pynini and mecab-python3 is failing to build wheels, also tried nemo_toolkit['asr'] which was successful but as soon as i run the code, i got the same module not found error.
btw, I'm using windows 10.

**Comment by titu1994** [comment]
NeMo does not natively support windows 10. Please use WSL 2 to run NeMo on windows

**Comment by muizzhaque** [comment]
Thanks for reaching out
