### ISSUE TITLE
Speaker Diarization - Extracting speaker embeddings for labels from files with multiple speakers from MSDD models

### ISSUE THREAD

**Issue by asusdisciple** [NVIDIA/NeMo#6965]
**Is your feature request related to a problem? Please describe.**

One problem I come across often is, that I can't verify already known speakers from other files, since inference only yields labels for a **MSDD model** approach.
For example: I have file **A** with speakers Paul, Tom and Charlie and File **B** with speaker Bert, Charlie and Johann. To determine if **Charlie is in File A and B**, I have to get his speaker embedding. At the moment I have to infer speaker diarization on file A to do this, get the timestamps for Charlie, cut the file at the marks, stitch it together again and get the corresponding feature embedding which I can then compare to file B, by doing the same. However for a production setup I would need the embedding from the MSDD model, but from my understanding the MSDD model only produces a probability vector?

**Describe the solution you'd like**

A solution would be to extract the feature embeddings with some kind of method, after diarization and associate them with the labels. I found the get_cluster_avg_embs_model() method for MSDD models, but I am not sure how to use it and if it yields the correct results (to me its not clear which parameters to use here, since there are a lot of internal states in the model after diarization). So the question would, which parameter yields the best representation of a speaker to recognize him again?

**Comment by nithinraok** [comment]
Are you looking to get representative embedding per each cluster label? 
@tango4j you did this for online diarization right? Is it part of main?

**Comment by tango4j** [comment]
@asusdisciple 
Please take a look this part of the code:
[MSDD forward function](https://github.com/NVIDIA/NeMo/blob/5a5c77aab6a2568987a19ad78299c3c57bcc9766/nemo/collections/asr/models/msdd_models.py#L565)
`clus_label_index` is containing the indices of the speakers that are in the output RTTM, CTM, JSON files. (e.g. speaker_0, speaker_1)
Now, bring this speaker index to grab the average speaker embedding from the variable [`ms_avg_embs`](https://github.com/NVIDIA/NeMo/blob/5a5c77aab6a2568987a19ad78299c3c57bcc9766/nemo/collections/asr/models/msdd_models.py#L417C24-L417C79).
`Shape: (batch_size, scale_n, emb_dim, self.num_spks_per_model)`
for example, `ms_avg_embs[0, :, :, spk_index]` will give you `(scale_n, emb_dim)` dimension of embeddings for the `spk_index`.
In this way, you can associate `speaker_x` with the speaker embeddings.

**Comment by asusdisciple** [comment]
I will try this, thanks this helped a lot.
