### ISSUE TITLE
DER as the metric for the callback in MSDD train

### ISSUE THREAD

**Issue by SagyHarpazGong** [NVIDIA/NeMo#6973]
Hi.

I'm wondering if is possible to set DER as the saving metric, as I can see I only can set loss or acc_f1 as the saving metric.
please advise

**Comment by SagyHarpazGong** [comment]
@nithinraok yes

**Comment by nithinraok** [comment]
we don't track DER while training. We currently score msdd models based on [f1_score](https://github.com/NVIDIA/NeMo/blob/2cc09425aba3e9b3cfdba43a3188eaef58227055/nemo/collections/asr/metrics/multi_binary_acc.py#L23) and track loss.
