### ISSUE TITLE
char_model = nemo_asr.models.ASRModel.from_pretrained("stt_en_quartznet15x5", map_location='cpu').And I have just been running the fine-tuning tutorial  you just put out. I dont know how to fix this . And im running it on google colab .Please help

### ISSUE THREAD

**Issue by Hid-Gh** [NVIDIA/NeMo#6976]
[NeMo I 2023-07-05 14:14:49 cloud:68] Downloading from: https://api.ngc.nvidia.com/v2/models/nvidia/nemo/stt_en_quartznet15x5/versions/1.0.0rc1/files/stt_en_quartznet15x5.nemo to /root/.cache/torch/NeMo/NeMo_1.20.0rc0/stt_en_quartznet15x5/16661021d16e679bdfd97a2a03944c49/stt_en_quartznet15x5.nemo
[NeMo I 2023-07-05 14:14:53 common:913] Instantiating model from pre-trained checkpoint
[NeMo W 2023-07-05 14:14:56 modelPT:161] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config : 
    manifest_filepath: /data2/voices/train_1k.json
    sample_rate: 16000
    labels:
    - ' '[NeMo I 2023-07-05 14:14:49 cloud:68] Downloading from: https://api.ngc.nvidia.com/v2/models/nvidia/nemo/stt_en_quartznet15x5/versions/1.0.0rc1/files/stt_en_quartznet15x5.nemo to /root/.cache/torch/NeMo/NeMo_1.20.0rc0/stt_en_quartznet15x5/16661021d16e679bdfd97a2a03944c49/stt_en_quartznet15x5.nemo
[NeMo I 2023-07-05 14:14:53 common:913] Instantiating model from pre-trained checkpoint
[NeMo W 2023-07-05 14:14:56 modelPT:161] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config : 
    manifest_filepath: /data2/voices/train_1k.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    trim_silence: true
    max_duration: 16.7
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: /asr_set_1.2/train/train_{0..1023}.tar
    num_workers: 20
    
[NeMo W 2023-07-05 14:14:56 modelPT:168] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s). 
    Validation config : 
    manifest_filepath: /data2/voices/train_1k_samp.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    shuffle: false
    
[NeMo I 2023-07-05 14:14:56 features:289] PADDING: 16
[NeMo W 2023-07-05 14:14:57 modelPT:161] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config : 
    manifest_filepath: /data2/voices/train_1k.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    trim_silence: true
    max_duration: 16.7
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: /asr_set_1.2/train/train_{0..1023}.tar
    num_workers: 20
    
[NeMo W 2023-07-05 14:14:57 modelPT:168] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s). 
    Validation config : 
    manifest_filepath: /data2/voices/train_1k_samp.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    shuffle: false
    
[NeMo I 2023-07-05 14:14:57 features:289] PADDING: 16
[NeMo E 2023-07-05 14:14:58 common:506] Model instantiation failed!
    Target class:	nemo.collections.asr.models.ctc_models.EncDecCTCModel
    Error(s):	Unexpected keyword arguments: `compute_on_step`
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/nemo/core/classes/common.py", line 485, in from_config_dict
        instance = imported_cls(cfg=config, trainer=trainer)
      File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/models/ctc_models.py", line 96, in __init__
        self._wer = WER(
      File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/metrics/wer.py", line 1128, in __init__
        super().__init__(dist_sync_on_step=dist_sync_on_step, compute_on_step=False)
      File "/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py", line 145, in __init__
        raise ValueError(f"Unexpected keyword arguments: {', '.join(kwargs_)}")
    ValueError: Unexpected keyword arguments: `compute_on_step`
    
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-34-a0f5a44992b6>](https://0pzek2a4z9i-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230629-060050-RC00_544292008#) in <cell line: 1>()
----> 1 char_model = nemo_asr.models.ASRModel.from_pretrained("stt_en_quartznet15x5", map_location='cpu')

8 frames
[/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py](https://0pzek2a4z9i-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230629-060050-RC00_544292008#) in __init__(self, **kwargs)
    143         if kwargs:
    144             kwargs_ = [f"`{a}`" for a in sorted(kwargs)]
--> 145             raise ValueError(f"Unexpected keyword arguments: {', '.join(kwargs_)}")
    146 
    147         # initialize

ValueError: Unexpected keyword arguments: `compute_on_step`
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    trim_silence: true
    max_duration: 16.7
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: /asr_set_1.2/train/train_{0..1023}.tar
    num_workers: 20
    
[NeMo W 2023-07-05 14:14:56 modelPT:168] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s). 
    Validation config : 
    manifest_filepath: /data2/voices/train_1k_samp.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    shuffle: false
    
[NeMo I 2023-07-05 14:14:56 features:289] PADDING: 16
[NeMo W 2023-07-05 14:14:57 modelPT:161] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config : 
    manifest_filepath: /data2/voices/train_1k.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    trim_silence: true
    max_duration: 16.7
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: /asr_set_1.2/train/train_{0..1023}.tar
    num_workers: 20
    
[NeMo W 2023-07-05 14:14:57 modelPT:168] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s). 
    Validation config : 
    manifest_filepath: /data2/voices/train_1k_samp.json
    sample_rate: 16000
    labels:
    - ' '
    - a
    - b
    - c
    - d
    - e
    - f
    - g
    - h
    - i
    - j
    - k
    - l
    - m
    - 'n'
    - o
    - p
    - q
    - r
    - s
    - t
    - u
    - v
    - w
    - x
    - 'y'
    - z
    - ''''
    batch_size: 32
    shuffle: false
    
[NeMo I 2023-07-05 14:14:57 features:289] PADDING: 16
[NeMo E 2023-07-05 14:14:58 common:506] Model instantiation failed!
    Target class:	nemo.collections.asr.models.ctc_models.EncDecCTCModel
    Error(s):	Unexpected keyword arguments: `compute_on_step`
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/nemo/core/classes/common.py", line 485, in from_config_dict
        instance = imported_cls(cfg=config, trainer=trainer)
      File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/models/ctc_models.py", line 96, in __init__
        self._wer = WER(
      File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/metrics/wer.py", line 1128, in __init__
        super().__init__(dist_sync_on_step=dist_sync_on_step, compute_on_step=False)
      File "/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py", line 145, in __init__
        raise ValueError(f"Unexpected keyword arguments: {', '.join(kwargs_)}")
    ValueError: Unexpected keyword arguments: `compute_on_step`
    
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-34-a0f5a44992b6>](https://0pzek2a4z9i-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230629-060050-RC00_544292008#) in <cell line: 1>()
----> 1 char_model = nemo_asr.models.ASRModel.from_pretrained("stt_en_quartznet15x5", map_location='cpu')

8 frames
[/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py](https://0pzek2a4z9i-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230629-060050-RC00_544292008#) in __init__(self, **kwargs)
    143         if kwargs:
    144             kwargs_ = [f"`{a}`" for a in sorted(kwargs)]
--> 145             raise ValueError(f"Unexpected keyword arguments: {', '.join(kwargs_)}")
    146 
    147         # initialize

ValueError: Unexpected keyword arguments: `compute_on_step`

**Comment by titu1994** [comment]
Which version of NeMo is installed? Metrics and rest should be installed by Nemo via pip in a clean conda env
