### ISSUE TITLE
NGC link to QuartzNet model doesn't list National Speech Corpus

### ISSUE THREAD

**Issue by sharonwoo** [NVIDIA/NeMo#698]
Hi Nvidia folks, someone pointed this out to me actually. 

Readme for QuartzNet15x5En states model trained on LibriSpeech, WSJ, Mozilla Common Voice (en_1488_2019-12-10), Fisher, Switchboard and Singapore English National Speech Corpus.

But the [NGC page](https://ngc.nvidia.com/catalog/models/nvidia:multidataset_quartznet15x5) reached when clicking on the Readme link states LibriSpeech, Mozilla Common Voice, WSJ, Fisher, and Switchboard. 

Can I check if the version trained on the Singapore English National Speech Corpus has been uploaded? Thanks!

**Comment by okuchaiev** [comment]
@sharonwoo Thanks for reporting. I actually believe this one doesn't wasn't trained on Singapore English National Speech Corpus, so most likely an error in README. @redoctopus could you please check?

However, we are training and planning to release soon a checkpoint trained on more data, including Singapore English National Speech Corpus.

**Comment by redoctopus** [comment]
Yes, @okuchaiev is correct--the checkpoint on NGC wasn't trained on Singapore English NSC, it's an error with the README. Thanks for letting us know!

(I imagine it was mixed up with the Jasper checkpoint, which was trained on those datasets.)

**Comment by okuchaiev** [comment]
fixed and updated README on master. thank you
