### ISSUE TITLE
I am still getting the error.

### ISSUE THREAD

**Issue by muizzhaque** [NVIDIA/NeMo#6984]
I am still getting the error
Unexpected keyword arguments: `compute_on_step`
  File "/home/muizz/nemo_workspace/Neural_netw.py", line 9, in <module>
    asr_model = nemo_asr.models.EncDecCTCModel.from_pretrained(model_name="QuartzNet15x5Base-En")
ValueError: Unexpected keyword arguments: `compute_on_step`

what do i do to avoid this

_Originally posted by @muizzhaque in https://github.com/NVIDIA/NeMo/issues/6977#issuecomment-1623474893_

**Comment by titu1994** [comment]
You have to install main branch of Nemo. Instructions are in readme

**Comment by muizzhaque** [comment]
python3 -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]
this is what i used to install nemo and when I hit run, the program gave me the same error.
Also tried Google colabs tutorial and below you can find the error msg
 Target class:	nemo.collections.asr.models.ctc_models.EncDecCTCModel
    Error(s):	Unexpected keyword arguments: `compute_on_step`
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/nemo/core/classes/common.py", line 485, in from_config_dict
        instance = imported_cls(cfg=config, trainer=trainer)
      File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/models/ctc_models.py", line 96, in __init__
        self._wer = WER(
      File "/usr/local/lib/python3.10/dist-packages/nemo/collections/asr/metrics/wer.py", line 1128, in __init__
        super().__init__(dist_sync_on_step=dist_sync_on_step, compute_on_step=False)
      File "/usr/local/lib/python3.10/dist-packages/torchmetrics/metric.py", line 145, in __init__
        raise ValueError(f"Unexpected keyword arguments: {', '.join(kwargs_)}")
    ValueError: Unexpected keyword arguments: `compute_on_step`

**Comment by titu1994** [comment]
Dunno what's the issue then. Current main has fixed this. If you're using conda check if the correct conda env was updated. Or maybe just pip install instead of the python -m 

Colab will be affected until the next release cause of this library and if doesn't install main. You can replace the BRANCH at the top of the notebooks with main to fix it for the time being.

**Comment by duckyngo** [comment]
This issue solved when I downgrade torchmetrics from 1.0.0 to 0.11.4 version

**Comment by titu1994** [comment]
But on main, all checks for this already passed so it should be safe to use the latest one. Can you post a full stack trace of where this is occuring added installing main branch?

**Comment by muizzhaque** [comment]
Just create a new environment and start fresh with the tool
type in python3 -m pip install git+[https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]] 
it will resolve the issue

Thanks for the help!
