### ISSUE TITLE
KaldiDatalayer

### ISSUE THREAD

**Issue by yuekaizhang** [NVIDIA/NeMo#699]
https://github.com/NVIDIA/NeMo/blob/1ae4aa92991ef6c3fd939774cd22d89096107794/nemo/collections/asr/data_layer.py#L643-L645

I'd like to know in this KaldiDatalayer, since Feature_len would not be return, how to call the downstream encoder function? (since no feat_len return, I am now calling by `encoded,encoded_len = encoder(audio_signal=audio_signal)`

https://github.com/NVIDIA/NeMo/blob/1ae4aa92991ef6c3fd939774cd22d89096107794/nemo/collections/asr/parts/jasper.py#L510-L518

If the lens here is None, 
there would be a bug in the forward method of maskedconv1d https://github.com/NVIDIA/NeMo/blob/1ae4aa92991ef6c3fd939774cd22d89096107794/nemo/collections/asr/parts/jasper.py#L143

**Comment by yuekaizhang** [comment]
Also, do you think change the feat_in param for the pretrained nemo model would have a big effect on the result?

**Comment by redoctopus** [comment]
Good catch, that's a bug. There should actually be a `processed_signal_length` output port as well--it actually does return a `feature_lens` tensor. I'll put in a fix.

If I understand your second question correctly, I believe that would cause a dimensionality mismatch.

**Comment by yuekaizhang** [comment]
> Good catch, that's a bug. There should actually be a `processed_signal_length` output port as well--it actually does return a `feature_lens` tensor. I'll put in a fix.
> 
> If I understand your second question correctly, I believe that would cause a dimensionality mismatch.
Sorry, I am not clear with the question. For feature mismatch, we definitely could fix by modifying kaldi or nemo's config. 
Actually, my question is does Nemo have some preprocessor that could give similar feature output with kaldi? Otherwise, if I'd like use KaldiDatalayer with features extracted by kaldi, I can't directly use nemo's pretrained model.
So, I have to trained nemo model with kaldi extracted feature. In this case, without any hyperparams tuning, whether the wer or cer would be effected?

**Comment by yuekaizhang** [comment]
Btw, the api doc should also be modified it the issue is a bug
https://nvidia.github.io/NeMo/collections/nemo_asr.html#nemo.collections.asr.data_layer.KaldiFeatureDataLayer.output_ports

**Comment by redoctopus** [comment]
> Actually, my question is does Nemo have some preprocessor that could give similar feature output with kaldi?

As far as I'm aware, we don't have a preprocessor like that. All of our audio preprocessors should be in here: https://github.com/NVIDIA/NeMo/blob/master/nemo/collections/asr/audio_preprocessing.py
Though some of them do use `torchaudio` to convert spectrograms, they are not the Kaldi compatibility versions, so we don't have anything to explicitly match Kaldi feature computation.

> So, I have to trained nemo model with kaldi extracted feature. In this case, without any hyperparams tuning, whether the wer or cer would be effected?

That's a very good question, but unfortunately I don't have an answer to that. The Kaldi data layer is an experimental feature and I haven't gotten around to thorough experimentation yet, so I can't say for sure how well it would train without changing hyperparams. Most of my experiments were to make sure it worked with much smaller datasets like AN4. If you do go forward with training with it, I would be very interested in your findings!

As for the API doc, that should be taken care of automatically on the next documentation build. Thanks for the thoroughness, though!

**Comment by yuekaizhang** [comment]
Thanks for your answer.
