### ISSUE TITLE
Trained TTS Vitsmodel Restricted to 11 Seconds of Audio Generation

### ISSUE THREAD

**Issue by shuvohishab** [NVIDIA/NeMo#6998]
By following [this tutorial](https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/Vits_Training.ipynb), I trained a TTS VitsModel.
While performing inference of the trained TTS model to convert text into speech, I observed a limitation where the system generates only up to 11 seconds of audio. So, when dealing with longer texts (e.g., equivalent to 90 seconds of audio), it just produces only first 11 seconds of equivalent audio.
On the other hand, when the text is short and equivalent to 0 to 11 seconds of audio, the system generates audio of the exact length.

Is there a workaround available to generate the complete audio for longer texts?

Note:

I'm using the latest codebase to implement the TTS model.
The audio data I am working with varies in length from 0.1 seconds to 63 seconds.

**Steps/Code to reproduce bug**

I loaded the Vits TTS model and infer with a long text.

**Expected behavior**

It was supposed to return a audio with whole text utterance.

**Environment overview (please complete the following information)**

 - Environment location: GCP
 - Method of NeMo install: from source

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Debian GNU/Linux 10 (buster)
- PyTorch version: 1.12.1+cu113
- Python version: 3.10

**Additional context**

Example: GPU model: 8xA100 GPUS

**Comment by XuesongYang** [comment]
@treacker could you please have a look? there was the same discussion: https://github.com/NVIDIA/NeMo/discussions/6972

**Comment by treacker** [comment]
Sorry for late responce. The problem is in max_len parameter, which is set by default to 1000 and can't be changed from 'convert_text_to_waveform' function. The workaround is either to use 'forward' function which is called inside 'convert_text_to_waveform' or add option to change max_len.

**Comment by shuvohishab** [comment]
Closing this issue, as we are also discussing this here #6972
