### ISSUE TITLE
Export Tacotron2 to ONNX

### ISSUE THREAD

**Issue by wannaphong** [NVIDIA/NeMo#6999]
Is it possible to export Tacotron2 model to onnx? I see #748 and doesn't have anyone can answer.

**Comment by XuesongYang** [comment]
@borisfom could you pls have a look?

**Comment by wannaphong** [comment]
Update?

**Comment by wannaphong** [comment]
I found the way to export tacotron2 to onnx model. https://github.com/PyThaiNLP/thaitts-onnx
