### ISSUE TITLE
Import Value Error

### ISSUE THREAD

**Issue by kiransview** [NVIDIA/NeMo#7002]
**Describe the bug**

Getting a Error while importing "import nemo.collections.asr as nemo_asr" the error states "ValueError: mutable default <class 'nemo.core.classes.mixins.adapter_mixin_strategies.ResidualAddAdapterStrategyConfig'> for field adapter_strategy is not allowed: use default_factory" Tried uninstalling and reinstalling the library the problem still exits.

**Steps/Code to reproduce bug**

ScreenShot added

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: Local Env (created specific new env as well)
 - Method of NeMo install: pip install nemo_tooklit[all]

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: Getting a Error while importing "import nemo.collections.asr as nemo_asr" the error states "ValueError: mutable default <class 'nemo.core.classes.mixins.adapter_mixin_strategies.ResidualAddAdapterStrategyConfig'> for field adapter_strategy is not allowed: use default_factory" Tried uninstalling and reinstalling the library the problem still exits.

**Screenshot**
![image](https://github.com/NVIDIA/NeMo/assets/61668526/b1be2fa6-26bb-4243-a37b-810461a5b6d9)

**Comment by titu1994** [comment]
Is this on main branch ?

**Comment by kiransview** [comment]
Not Sure, I have not specified the branch name while installing. Installed directly through pip "pip install nemo_toolkit[all]

**Comment by titu1994** [comment]
Can you post the full stack trace?

**Comment by titu1994** [comment]
I will need the version of the following libraries - 
nemo_toolkit
Pytorch
Python 3.10?

**Comment by titu1994** [comment]
It seems you're using python 3.11 which we donr currently support.

**Comment by kiransview** [comment]
I will need the version of the following libraries -
nemo_toolkit: 1.19
Pytorch: 2.0.1+cpu
Python 3.11

So when can we expect the support on the New Version of python?

**Comment by titu1994** [comment]
We're recently moving to python 3.10, 3.11 might take a while. On this specific issue, I can take a look in the coming month but currently we are not prioritizing 3.11 support

**Comment by softlypink** [comment]
Hello Mr. Majumdar @titu1994 , I have a noob question if that's okay.

I tried to install 'whisper-diarization' and it failed, and the owner said to "downgrade to python 3.10 until NeMo supports 3.11." My current Python version is 3.10.11 (Windows 10 64-bit), am I supposed to downgrade to Python 3.10.10 - Feb. 8, 2023, or further back? Sorry

**Comment by titu1994** [comment]
3.10 any version should be fine I think. 3.11 is the one that's breaking dataclass

**Comment by dmtrung14** [comment]
Hi, I want to follow up on the issue. It seems to me that there is also an error trying to install pyini, namely here:

```
BRANCH = `main`
!wget https://raw.githubusercontent.com/NVIDIA/NeMo/$BRANCH/nemo_text_processing/install_pynini.sh
!bash install_pynini.sh
```

It seems to me that Colab cannot find the file here

**Comment by titu1994** [comment]
You can try changing "all" to "asr" and see if that works
