### ISSUE TITLE
Is there a list of models that can export ONNX?

### ISSUE THREAD

**Issue by wxqwinner** [NVIDIA/NeMo#7020]
'vad_multilingual_frame_marblenet' can.t export. is there a restriction on exporting models for some reason?

```python
import nemo.collections.asr as nemo_asr
model = nemo_asr.models.EncDecFrameClassificationModel.from_pretrained(model_name="vad_multilingual_frame_marblenet")

model.export('test.onnx', onnx_opset_version=12)
```
error:
'EncDecFrameClassificationModel' object has no attribute 'output_names'

**Comment by stevehuang52** [comment]
sorry for the delay, I'll take a loot and update later

**Comment by stevehuang52** [comment]
@wxqwinner The export error was fixed here [7076](https://github.com/NVIDIA/NeMo/pull/7076 ), please use the latest NeMo main branch and let use know if there's further issues.
