### ISSUE TITLE
ModuleNotFoundError: BeamSearchDecoderWithLM requires the installation of ctc_decoders from nemo/scripts/install_decoders.py

### ISSUE THREAD

**Issue by yaliu777** [NVIDIA/NeMo#706]
I was trying to use Language Model during the testing process. I run this 'python <nemo_git_repo_root>/examples/asr/jasper_eval.py --model_config=<nemo_git_repo_root>/examples/asr/configs/quartznet15x5.yaml --eval_datasets "<path_to_data>/dev_clean.json" --load_dir=<directory_containing_checkpoints> --lm_path=<path_to_6gram.binary>' with paths changed. But I got ModuleNotFoundError, and there is no ctc_decoder.py in nemo.collection.ars. I also installed the packages required in this link (https://nvidia.github.io/NeMo/asr/tutorial.html#evaluation-with-language-model). The ctc_decoder.py is in the scripts.decoders. I am wondering how should I fix this bug.

**Comment by nguyendohoangkhoi** [comment]
Does anyone solve this issue?
