### ISSUE TITLE
PyYAML<6 breaks the installation on colab

### ISSUE THREAD

**Issue by mohammadjavadpirhadi** [NVIDIA/NeMo#7060]
**Describe the bug**

PyYAML<6 in requirements breaks the installation on Google Colab. Removing the PyYAML<6 requirement from requirements/requirements_lightning.txt solves the problem.

**Steps/Code to reproduce bug**

Just run the first cell of https://github.com/NVIDIA/NeMo/blob/stable/tutorials/nlp/Punctuation_and_Capitalization.ipynb

**Expected behavior**

Successful installation.

**Environment overview (please complete the following information)**

 - Environment location: Google Colab
 - Method of NeMo install: pip

**Comment by mohammadjavadpirhadi** [comment]
@ericharper thanks for your quick reply.
Do you have any plans for a bug-fix release?

**Comment by ericharper** [comment]
It's currently planned for r1.20.0 release.

**Comment by mohammadjavadpirhadi** [comment]
> It's currently planned for r1.20.0 release.

Thanks.

**Comment by hengck23** [comment]
the pip also fails because of this. maybe some quick update for pip wheel?

**Comment by titu1994** [comment]
The next pip wheel will be 1.20 - that will have the fix.

**Comment by kn** [comment]
any updates on updating pip wheel/eta?
