### ISSUE TITLE
File not found error while loading titanet_small

### ISSUE THREAD

**Issue by Sreeni1204** [NVIDIA/NeMo#7074]
Hello,

I am trying to load titanet small using the following line of code: 
```
nemo_speaker_model_small = EncDecSpeakerLabelModel.from_pretrained(model_name="titanet_small")
```

Here is the error:
```FileNotFoundError: Model titanet_small was not found. Check cls.list_available_models() for the list of all available models.```

I am using the latest nemo_toolkit

**Comment by muizzhaque** [comment]
you can check for those models that are currently present in that package which here is EncDecSpeakerLabelModel.list_available_models() and this will provide all the packages which are pretrained and ready to use.
I believe that titanet_small isn't available in that file list

**Comment by Sreeni1204** [comment]
Hello @muizzhaque 

I am using the git branch r1.20.0 which has the reference to titanet_small under EncDecSpeakerLabelModel.list_available_models()

**Comment by Sreeni1204** [comment]
Hello, Yes, I know its not part of r1.19.1, but instead I used the main branch from git r1.20.0. Even then it threw this error.
