### ISSUE TITLE
RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement

### ISSUE THREAD

**Issue by hruturajnikam** [NVIDIA/NeMo#7078]
@titu1994 @meghmak13 
Dear Team,
      I am training **conformer based SSL** model where I have configured the parameters 
**min_duration : 3.2
patch_size: 16
mask_patches: 0.5
num_negatives: 40
sample_from_same_utterance_only: true
sample_from_non_masked: false
codebook_size: 300
num_groups: 2
num_classes: 90000**

 but I am getting following error
**RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement**  

I am using **Nemo-22.05 images(ngc) and 48, A100-SXM4-40GB GPU** i.e 6 nodes for the training. Kindly suggest me what is need to be done ? Thanks in advance

**Comment by mehadi92** [comment]
@hruturajnikam 
Decreasing the value of `num_negatives` solve my issue

**Comment by mehadi92** [comment]
@titu1994 

Could you please give us any clue on param `num_negatives` and `RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement` 

Thanks

**Comment by mehadi92** [comment]
@titu1994 @sam1373 

Any update regarding this. I'm facing the same issue with SSL ASR training

**Comment by sam1373** [comment]
@mehadi92 Are you still facing the issue when using above parameters on current main? How long are the samples in your dataset? Could you try setting slightly larger min_duration, like 4.0?

**Comment by mehadi92** [comment]
Hi, @sam1373 

Thanks for your reply. 

I was able to train when I set ` min_duration: 8.0`. The default `max_duration: 16.7` I did not change max_duration. 

`I tried the min_duration value from 2,0 sec to 7.0 sec but none of this worked`. Give the same error `cannot sample n_sample > prob_dist.size(-1) samples`.

As my most of the training data is below 8 seconds (~12500 hours) by setting `min_duration: 8.0` I was only able to train with ~4500 hours of data

Is it possible to train with low-duration audio? Do I need to change other parameters in [conformer_ssl.yaml](https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/ssl/conformer/conformer_ssl.yaml) for training with 2 to 16 seconds duration audio data?

Also, let me know if you need any other information about my training setup

NOTE: I'm using the bucketing dataset for training

Thanks
