### ISSUE TITLE
No code for SLU metrics computation

### ISSUE THREAD

**Issue by maevdokimov** [NVIDIA/NeMo#7098]
Hi!
I was trying to find a place where SLU metrics are computed. AFAIU this is going to be [here](https://github.com/NVIDIA/NeMo/blob/main/examples/slu/speech_intent_slot/eval_utils/evaluator.py#L92). But I can't find where ```ErrorMetric ``` class is defined. Are you planning to make this code publicly available?

**Comment by stevehuang52** [comment]
Seems the SLURP dataset has updated the code license to CC from CC-NC, we will port those code into NeMo

**Comment by maevdokimov** [comment]
Oh, now I see. Many thanks!
