### ISSUE TITLE
unidecode module cause mandarin characters to be wrong interpretation

### ISSUE THREAD

**Issue by Slyne** [NVIDIA/NeMo#71]
The code is here: https://github.com/NVIDIA/NeMo/blob/cf85138d97ad9efe79c6dba4aafb0e80c7e46a78/collections/nemo_asr/nemo_asr/parts/cleaners.py   line 77

The package is here https://pypi.org/project/Unidecode/
From the example:
>>> unidecode(u"\u5317\u4EB0")
'Bei Jing '

u"\u5317\u4EB0"  ->  北京

If it is possible to remove this line since Chinese cannot be represented in ascii code.

**Comment by okuchaiev** [comment]
Please have a look at this PR https://github.com/NVIDIA/NeMo/pull/38 by @dhpollack - I think for Chinese you can have a ManifestCN which will use different cleaning function.
@Slyne  what do you think?

**Comment by Slyne** [comment]
I think it is ok to have another manifestCN. Currently, I set normalize_transcript=false to solve this problem. 
Close this issue.
