### ISSUE TITLE
exporting asr model in TORCHSCRIPT

### ISSUE THREAD

**Issue by bill-kalog** [NVIDIA/NeMo#712]
Hello, I am trying to export the data_preprocessor module from quartznet similarly to the encoder and decoder module example that you have in `onnx` but for `torchscript`.  However, I am getting the error `AttributeError: 'AudioToMelSpectrogramPreprocessor' object has no attribute '_forward_pre_hooks'` (I assume it happens because it is a `NonTrainableNM`) do you have any suggestion regarding how I could bypass this or how it would be possible to do it in general? Exporting the encoder and decoder works fine based on your script...

**Comment by marco-radic** [comment]
`torchscript` imposes limitations on what parts of Python it can serialize. Your best bet is probably to iteratively adapt the Preprocessor code while trying to serialize it using `torch.jit.script` until you do not get errors anymore.

**Comment by bill-kalog** [comment]
yeah that's right! I ended up following that route. Haven't tested it thoroughly so far but it seems to get exported

**Comment by laohur** [comment]
> 
> 
> `torchscript` imposes limitations on what parts of Python it can serialize. Your best bet is probably to iteratively adapt the Preprocessor code while trying to serialize it using `torch.jit.script` until you do not get errors anymore.

how about export tts models to onnx ?

**Comment by OndrejGl** [comment]
> yeah that's right! I ended up following that route. Haven't tested it thoroughly so far but it seems to get exported

Hi, would you be willing to share that piece of code?  I'm also struggling exporting the Preprocessor. 
Thanks

**Comment by bill-kalog** [comment]
@OndrejGl Hi, unfortunately I don't have a patch for the current version of NeMo but I will try to explain as much as I can the steps I took and then you can maybe try to reproduce or and improve any mistakes that I might have done. I think NeMo codebase was at v0.10 when I did the changes. 

The files that needed changes were 

```
nemo/backends/pytorch/actions.py
nemo/backends/pytorch/nm.py
nemo/collections/asr/audio_preprocessing.py
nemo/collections/asr/parts/features.py
```

At `nemo/backends/pytorch/nm.py` all you have to do is make the `NonTrainableNM` class that is used for preprocessors inherit from nn.module so that you can export the class to torchscript

```
-class NonTrainableNM(NeuralModule):
+class NonTrainableNM(NeuralModule, nn.Module):
```


At `nemo/backends/pytorch/actions.py` you had to deactivate taking gradients at some step, but since preprocessor doesn't have function to set that you need to circumvent it. 

```
-        module.eval()
+        import nemo
+        if not type(module) is nemo.collections.asr.audio_preprocessing.AudioToMelSpectrogramPreprocessor:
+            module.eval()
+            module.requires_grad_(False)
+        else:
+            module._forward_pre_hooks = {}
```
I am not sure if the line `module._forward_pre_hooks = {}` is actually needed anymore maybe it was a leftover from when I was trying things. You can check what is needed and what not.


At `nemo/collections/asr/audio_preprocessing.py` I had to remove the `disable_casts()` call

```
@@ -87,8 +86,9 @@ class AudioPreprocessor(NonTrainableNM):
     @torch.no_grad()
     def forward(self, input_signal, length):
         if self.disable_casts:
-            with amp.disable_casts():
-                processed_signal = self.get_features(input_signal.to(torch.float), length)
+            processed_signal = self.get_features(input_signal, length)
```


Finally, at `nemo/collections/asr/parts/features.py` some part of functions had to be traced with torch.jit.script because they contained control flows. 

```
-def normalize_batch(x, seq_len, normalize_type):
-    if normalize_type == "per_feature":
+@torch.jit.script
+def normalize_batch(x, seq_len, normalize_type: str, constant: float = 1e-5):
         x_mean = torch.zeros((seq_len.shape[0], x.shape[1]), dtype=x.dtype, device=x.device)
         x_std = torch.zeros((seq_len.shape[0], x.shape[1]), dtype=x.dtype, device=x.device)
         for i in range(x.shape[0]):
             x_mean[i, :] = x[i, :, : seq_len[i]].mean(dim=1)
             x_std[i, :] = x[i, :, : seq_len[i]].std(dim=1)
         # make sure x_std is not zero
-        x_std += CONSTANT
+        x_std += constant
         return (x - x_mean.unsqueeze(2)) / x_std.unsqueeze(2)
-    elif normalize_type == "all_features":
-        x_mean = torch.zeros(seq_len.shape, dtype=x.dtype, device=x.device)
-        x_std = torch.zeros(seq_len.shape, dtype=x.dtype, device=x.device)
-        for i in range(x.shape[0]):
-            x_mean[i] = x[i, :, : seq_len[i].item()].mean()
-            x_std[i] = x[i, :, : seq_len[i].item()].std()
-        # make sure x_std is not zero
-        x_std += CONSTANT
-        return (x - x_mean.view(-1, 1, 1)) / x_std.view(-1, 1, 1)
-    elif "fixed_mean" in normalize_type and "fixed_std" in normalize_type:
-        x_mean = torch.tensor(normalize_type["fixed_mean"], device=x.device)
-        x_std = torch.tensor(normalize_type["fixed_std"], device=x.device)
-        return (x - x_mean.view(x.shape[0], x.shape[1]).unsqueeze(2)) / x_std.view(x.shape[0], x.shape[1]).unsqueeze(2)
-    else:
-        return x
```

As you see, in order to make it easier for me, I removed all the code that was doing normalization which I didn't need since I used only the default `per_feature` normalization. So, if you use something different here you would need to alter that part.


```
 def splice_frames(x, frame_splicing):
@@ -283,14 +294,23 @@ class FilterbankFeatures(nn.Module):
         mask = torch.arange(max_len).to(x.device)
         mask = mask.expand(x.size(0), max_len) >= seq_len.unsqueeze(1)
         x = x.masked_fill(mask.unsqueeze(1).type(torch.bool).to(device=x.device), self.pad_value,)
-        del mask
+        # del mask
         pad_to = self.pad_to
         if not self.training:
             pad_to = 16
         if pad_to == "max":
             x = nn.functional.pad(x, (0, self.max_length - x.size(-1)), value=self.pad_value)
         elif pad_to > 0:
-            pad_amt = x.size(-1) % pad_to
-            if pad_amt != 0:
-                x = nn.functional.pad(x, (0, pad_to - pad_amt), value=self.pad_value)
+            x = padding_to_multiples(x, pad_to, self.pad_value)
+            # pad_amt = x.size(-1) % pad_to
+            # if pad_amt != 0:
+            #     x = nn.functional.pad(x, (0, pad_to - pad_amt), value=self.pad_value)
         return x
```

```
+@torch.jit.script
+def padding_to_multiples(x, pad_to: int, pad_value: float):
+    pad_amt = x.size(-1) % pad_to
+    if pad_amt != 0:
+        return nn.functional.pad(x, (0, pad_to - pad_amt), value=pad_value)
+    return x
```


In the filterbank calculation I moved the padding to multiples in its own function and stop deleting the `mask` variable because `del` is not supported in torchscript.

That's it, after you do these things you will be able to export a preprocessor similarly to how you export the encoder and decoder volumes. Also by doing mostly the class inherit change thing you will be able to export without any other further code change other modules in case you want them too like the `JasperDecoderForCTC`.

Let me know if something doesn't work or if you find a better way to do some of the steps!

**Comment by ABoltachev** [comment]
Hello, @bill-kalog
Thank you for this instruction
I would like to make one remark:
> At nemo/backends/pytorch/nm.py all you have to do is make the NonTrainableNM class that is used for preprocessors inherit from nn.module so that you can export the class to torchscript

Here you also need to add
```
class NonTrainableNM(NeuralModule, nn.Module):
    def __init__(self):
        NeuralModule.__init__(self)  # For NeuralModule API
+        nn.Module.__init__(self)  # For PyTorch API
```

Also I have one question. Have you encountered this error `module export failed for AudioToMelSpectrogramPreprocessor with exception Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (256, 256) at dimension 3 of input 4` when trying to export the preprocessor?

**Comment by bill-kalog** [comment]
Hi @ABoltachev , yeah you are right! Thanks! I forgot to mention that change too. Regarding the error I think it happens because the dummy signal input you pass through the network has very small length and thus padding fails. Should work if you increase the signal length to something bigger like 500 samples or something
