### ISSUE TITLE
SpellMapper / Missing generate_configs.sh

### ISSUE THREAD

**Issue by thomaschhh** [NVIDIA/NeMo#7134]
I am currently looking into your code base and am wondering where to find the above-mentioned script that you are referring to [here](https://github.com/NVIDIA/NeMo/blob/2fa7abfb7311f1a4115dfa47afb80339697ec88d/examples/nlp/spellchecking_asr_customization/run_training.sh#L34C29-L34C29). I have already searched in your repo but can't seem to find it. 

Any help would be greatly appreciated.

**Comment by bene-ges** [comment]
Hi, @thomaschhh,
data_preparation scripts are currently in another [repo](https://github.com/bene-ges/nemo_compatible/blob/main/scripts/nlp/en_spellmapper/dataset_preparation)

**Comment by thomaschhh** [comment]
Thank you for the clarification! :)
