### ISSUE TITLE
Upgrading `hydra-core` past 1.3

### ISSUE THREAD

**Issue by alllexx88** [NVIDIA/NeMo#7172]
**Is your feature request related to a problem? Please describe.**

Current `hydra-core` version (`hydra-core>=1.2.0,<1.3` from `requirements/requirements_lightning.txt`) doesn't work with Python 3.11: see #7166

**Describe the solution you'd like**

Now, after [Upgrade to pytorch lightning 2.0](https://github.com/NVIDIA/NeMo/commit/67de251e980ef8d8aec3b8339e70e96f6c952122) commit, would it be safe to upgrade `hydra-core` past `1.3.0`? `hydra-core==1.3.2` at least imports fine without `1.2.0` `dataclasses` related issues.

**Describe alternatives you've considered**

The only alternative I can think of is creating a fork of `1.2.0` version and patching it, but I think it's counter-productive since it has to be maintained separately.

Thanks :smiley:

**Comment by titu1994** [comment]
Seems reasonable to update hydra core

**Comment by alllexx88** [comment]
Upgraded in #7243, thanks!
