### ISSUE TITLE
Concerns about the implementation of `end_of_generation_condition()`

### ISSUE THREAD

**Issue by odelalleau** [NVIDIA/NeMo#7187]
The code of `end_of_generation_condition()` https://github.com/NVIDIA/NeMo/blob/13791d27ec8b322da11e8324ff07124aa4e6c55f/nemo/collections/nlp/modules/common/text_generation_strategy.py#L138 seems weird to me => opening an issue to clarify whether it is working as intended (cc @gshennvm @yidong72)

I have two concerns:

1. I find it weird to see `<extra_id_1>` hardcoded in this function -- I thought that the goal of providing `end_strings` as argument would be to avoid having to hardcode special strings
2. I am confused by something that is best explained through an example. Let's say I want to use `end_strings = ["abc"]`, which is tokenized into [1, 2, 3] (tokens for "a", "b", "c"), while `<extra_id_1>` is tokenized into [0]. It seems to me that this code will lead to `ids_1 = tokenizer.text_to_ids(f'<extra_id_1>abc') = [0, 1, 2, 3]`, `ids_2 = [0]`, and `token_id = ids_1[len(ids_2) :][0] = 1`. As a result, as soon as `p` (the last token generated) is equal to 1 (i.e., as soon as an `"a"` is generated), we consider that the generation has ended. Am I missing something?

**Comment by yidong72** [comment]
It is because sentence piece tokenize tends to add an extra token in front of the string. the "<extra_id_1>" is added  in the front so it won't merge with the later string after tokenization. eventually we only take the difference between id2 and id1. This is a hack to deal with the sentencepiece behavior.

**Comment by yidong72** [comment]
> I am confused by something that is best explained through an example. Let's say I want to use end_strings = ["abc"], which is tokenized into [1, 2, 3] (tokens for "a", "b", "c"), while <extra_id_1> is tokenized into [0]. It seems to me that this code will lead to ids_1 = tokenizer.text_to_ids(f'<extra_id_1>abc') = [0, 1, 2, 3], ids_2 = [0], and token_id = ids_1[len(ids_2) :][0] = 1. As a result, as soon as p (the last token generated) is equal to 1 (i.e., as soon as an "a" is generated), we consider that the generation has ended. Am I missing something?

This is a bug. The stop criteria are too aggressive as it only matches the first token of the string.  If we set stop sting as ['abc'] it will stop at 'a' even the model wants to generate other string starts with 'a'. 
This is the fix to the problem.
```python
            for end_string in end_strings:
                ids_1 = tokenizer.text_to_ids(f'<extra_id_1>{end_string}')
                ids_2 = tokenizer.text_to_ids('<extra_id_1>')
                if len(ids_1) <= len(ids_2):
                    continue
                if  len(ids_1[len(ids_2) :]) == 1:
                    token_id = ids_1[len(ids_2) :][0]
                    end_tokens.add(token_id)
```

**Comment by odelalleau** [comment]
Ah thanks, I understand now. I have a follow-up question:

The stop conditions are obtained with
```python
conditions.append(
    any([text.endswith(end_string) for end_string in end_strings] + [p.item() in end_tokens])
)
```
where the tokens in `end_tokens` are `eod_id` plus any other token added through the processus you showed above.

Let's say that `p` (the last generated token) is equal to one of those other tokens found in `end_tokens`, which triggers one of `[p.item() in end_tokens]`. Isn't it guaranteed that we would also have one of `[text.endswith(end_string) for end_string in end_strings]` being True? (for instance, if `p` is the token corresponding to `<extra_id_1>`, then the string should end with `<extra_id_1>`) If this is wrong, can you provide an example where this would not be the case?

**Comment by yidong72** [comment]
it is not guaranteed.  ` [p.item() in end_tokens]` is intended to check for single tokens. [text.endswith(end_string) for end_string in end_strings] is intended to check the full string (which has more tokens)
