### ISSUE TITLE
List index out of range when transcribing with RNNT conformer large

### ISSUE THREAD

**Issue by robertveenhoven** [NVIDIA/NeMo#7192]
**Describe the bug**

Hello, we are running a Dutch trained version of the conformer RNNT large model.
However, in a small amount of cases we receive the following list index out of range error.

![image](https://github.com/NVIDIA/NeMo/assets/10922796/5341394d-a158-43d5-a724-52261052f0bb)

I saw that in [https://github.com/NVIDIA/NeMo/issues/4981 ](url) the issue seemed solved for the word timings, but maybe this issue still exists for the confidence scores?

We use the following to enable the confidence scores:

`
decoding_config = copy.deepcopy(conformer.cfg.decoding)
`
`
confidence_cfg = ConfidenceConfig(preserve_word_confidence=True, preserve_token_confidence=False)
`
`
with open_dict(decoding_config):
`
`
decoding_config.preserve_alignments = True,
`
`
    decoding_config.confidence_cfg = confidence_cfg
`
`
conformer.change_decoding_strategy(decoding_config)
`

**Expected behavior**

Transcription succeeding without errors

**Environment overview (please complete the following information)**

Docker nvcr.io/nvidia/pytorch:23.04-py3
NeMo installed from main with git clone and ./reinstall.sh ( cloned today )

**Additional context**

Ran on a 4090 GPU

**Comment by Kipok** [comment]
@robertveenhoven do you have an audio file that we can use to reproduce this?

**Comment by robertveenhoven** [comment]
I'll try to replicate this issue today with the English RNNT model. Unfortunately, we are not able to share the Dutch model since it uses private data. I guess the Dutch audio file is irrelevant when it cant pass through the same model?

**Comment by Kipok** [comment]
That will be awesome, thanks @robertveenhoven! It would really help us to debug this problem if we had a setup where this can be reproduced. It can be either with English model on English data or you can try any of the publicly available models with your particular audio file, as long as the error reproduces and you're able to share the setup.

**Comment by robertveenhoven** [comment]
I was able to reproduce the error with a different Dutch call using the English model.

I used a new docker (  nvcr.io/nvidia/pytorch:23.04-py3 ).

apt-get update && apt-get install -y libsndfile1 ffmpeg
git clone https://github.com/NVIDIA/NeMo
cd NeMo
./reinstall.sh

The audio file can be downloaded here: https://easyupload.io/3qy7kv

Script ran:

import nemo
import nemo.collections.asr as nemo_asr
from nemo.collections import nlp as nemo_nlp
import copy
from omegaconf import DictConfig, OmegaConf, open_dict

from nemo.collections.asr.parts.utils.asr_confidence_utils import ConfidenceConfig

conformer = nemo_asr.models.EncDecRNNTBPEModel.from_pretrained(model_name="stt_en_conformer_transducer_large")

decoding_config = copy.deepcopy(conformer.cfg.decoding)
confidence_cfg = ConfidenceConfig(preserve_word_confidence=True, preserve_token_confidence=False)
with open_dict(decoding_config):
    decoding_config.preserve_alignments = True,
    decoding_config.confidence_cfg = confidence_cfg
conformer.change_decoding_strategy(decoding_config)

audio_segment_name_list = ['/workspace/14.wav']
hypotheses = conformer.transcribe(paths2audio_files=audio_segment_name_list, return_hypotheses=True,
                                      batch_size=1)

**Comment by Kipok** [comment]
Thanks @robertveenhoven! 

@GNroy can you please check if you can reproduce and fix this?

**Comment by robertveenhoven** [comment]
Any updates? @GNroy

**Comment by GNroy** [comment]
@robertveenhoven Sorry, I wasn't available.
I'll look into this issue.

**Comment by robertveenhoven** [comment]
Thanks for the fix, most calls transcribe fine now! Unfortunately, we still have this problem when I set the batch size at 8 instead of 1 in the transcribe function. When the batch size is 1 the model transcribes without problems, although it is significantly slower. Should I try to replicate this again in the English model?

**Comment by GNroy** [comment]
@robertveenhoven We're happy to help!
Sure, please do that and open an issue.
