### ISSUE TITLE
eternal import nemo.collections.asr in the Offline_ASR.ipynb

### ISSUE THREAD

**Issue by Gero39** [NVIDIA/NeMo#7206]
**Describe the bug**

After the first run of the "Installation", when trying to run it again, colab endlessly executes the line "import nemo.collections.asr as nemo_asr".

**Expected behavior**

Import all required modules in a normal period of time

**Environment details**

Free colab (Nvidia Tesla T4)

![image](https://github.com/NVIDIA/NeMo/assets/75932124/29339e76-e4e6-4575-84e2-8c470e765cdb)

**Comment by titu1994** [comment]
Hmm that's probably a faulty colab startup. You should be able to restart the notebook to fix that.
