### ISSUE TITLE
ATIS results on Joint Intent Classification and Slot Filling

### ISSUE THREAD

**Issue by cartesinus** [NVIDIA/NeMo#722]
Hello, I'm trying to understand results I've got when I run tutorial on Joint Intent Classification and Slot Filling. I train model (on code from commit ac4a76) without any important changes (when compared to tutorial): 

```bash
python examples/nlp/intent_detection_slot_tagging/joint_intent_slot_with_bert.py \
    --max_seq_length 150 \
    --num_epochs 50 \
    --optimizer_kind adam
```

and slot results for last epoch (it is not best, but last 10-15 got quite similar) look like this:

```bash
[NeMo I 2020-04-26 16:29:03 joint_intent_slot_callback:113] Slot Prediction Results:
[NeMo I 2020-04-26 16:29:03 joint_intent_slot_callback:115] Slot Accuracy: 0.9710806697108066
[NeMo I 2020-04-26 16:29:03 joint_intent_slot_callback:118] F1 weighted: 96.55
[NeMo I 2020-04-26 16:29:03 joint_intent_slot_callback:118] F1 macro: 55.23
[NeMo I 2020-04-26 16:29:03 joint_intent_slot_callback:118] F1 micro: 97.11
[NeMo I 2020-04-26 16:29:03 joint_intent_slot_callback:120]
                                                  precision    recall  f1-score   support

                  B-aircraft_code (label id: 0)       1.00      0.45      0.62        33
                   B-airline_code (label id: 1)       0.55      0.97      0.70        34
                   B-airline_name (label id: 2)       0.99      1.00      1.00       101
                   B-airport_code (label id: 3)       0.00      0.00      0.00         9
                   B-airport_name (label id: 4)       0.00      0.00      0.00        21
      B-arrive_date.date_relative (label id: 5)       0.00      0.00      0.00         2
(...)
```
As you can see F1 macro is quite low, only 55.23%, with a lot of slots not being recognized at all (e.g. B-airport_name). Now, when compared to `Qian Chen, Zhu Zhuo, and Wen Wang. Bert for joint intent classification and slot filling. arXiv preprint arXiv:1902.10909, 2019.` which tutorial refer to, we can clearly see much higher results in the paper. Normally I would say that results presented in paper are maybe micro, since 'this looks better', but ATIS is rather easy dataset with only 123 slot types in total (and that's when we count B- and I- separately), so I'm a bit confused.
 
Can anyone please:
- confirm that my results are in pair with what you are getting?
- (considerining that my results are normal) explain or suggest why NeMo results are much lower that e.g. compared to papers?
- (considering that my results are not normal) point me out to what I might do bad?

**Comment by vladgets** [comment]
Results seem to be fine. You need to look for F1 micro value which is high. F1 macro is just average of F1 for all slots, but it does not make sense to relate to it, since slot classes are very unbalanced and  in macro average calculation a class with 1 example will give the same weight as class with 1000 examples. Does it make sense?

**Comment by vladgets** [comment]
We also have more interesting and realistic data set example with assistant dataset. Unfortunately, we did not add it to the Tutorial examples yet, but you can try to run "import_datasets.py --dataset_name=assistant" to download it and convert to Nemo data format. And then to run "joint_intent_slot_with_bert.py" with additional parameter --data_dir="assistant dataset folder". In this data set you have around 60 Intents and slots taken from realistic assistant domain.

**Comment by cartesinus** [comment]
Yes, that makes sense. I really needed a confirmation that what I get is the correct result. Thank you for your quick answer!

If I may suggest one thing, I think it would be useful to add a comment to the tutorial that would say what the expected result for atis and snips is.
