### ISSUE TITLE
Possible memory leak while inference for ASR task

### ISSUE THREAD

**Issue by yzhang123** [NVIDIA/NeMo#725]
@tkornuta-nvidia , I am currently working on a project that incorporates NeMo for an asr task, when infer the result, there is a memory leak．

1. infer with language model

![image](https://user-images.githubusercontent.com/24841439/84462705-488b7580-aca2-11ea-9733-b8dd2d3dec6f.png)　

2. infer without language model
![image](https://user-images.githubusercontent.com/24841439/84462783-7b356e00-aca2-11ea-806c-0610e69a55e1.png)

and the inference code is :
class ModelASR():
    def __init__(self, args):
        parser = get_parser()
        args = parser.parse_args(args)
        self.load_model(args)
  
    def load_model(self, args):
        batch_size = args.batch_size
        load_dir = args.load_dir

        if args.local_rank is not None:
            if args.lm_path:
                raise NotImplementedError(
                    "Beam search decoder with LM does not currently support evaluation on multi-gpu."
                )
            device = nemo.core.DeviceType.AllGpu
        else:
            device = nemo.core.DeviceType.GPU

        # Instantiate Neural Factory with supported backend
        neural_factory = nemo.core.NeuralModuleFactory(
            backend=nemo.core.Backend.PyTorch,
            local_rank=args.local_rank,
            placement=device,
        )

        if args.local_rank is not None:
            logging.info('Doing ALL GPU')

        yaml = YAML(typ="safe")
        with open(args.model_config) as f:
            jasper_params = yaml.load(f)
        vocab = jasper_params['labels']
        sample_rate = jasper_params['sample_rate']

        data_preprocessor = nemo_asr.AudioToMelSpectrogramPreprocessor(
            sample_rate=sample_rate, **jasper_params["AudioToMelSpectrogramPreprocessor"]
        )
        jasper_encoder = nemo_asr.JasperEncoder(
            feat_in=jasper_params["AudioToMelSpectrogramPreprocessor"]["features"], **jasper_params["JasperEncoder"]
        )
        jasper_decoder = nemo_asr.JasperDecoderForCTC(
            feat_in=jasper_params["JasperEncoder"]["jasper"][-1]["filters"], num_classes=len(vocab)
        )
        greedy_decoder = nemo_asr.GreedyCTCDecoder()

        logging.info('================================')
        logging.info(f"Number of parameters in encoder: {jasper_encoder.num_weights}")
        logging.info(f"Number of parameters in decoder: {jasper_decoder.num_weights}")
        logging.info(f"Total number of parameters in model: " f"{jasper_decoder.num_weights + jasper_encoder.num_weights}")
        logging.info('================================')

        if args.lm_path:
            if args.alpha_max is None:
                args.alpha_max = args.alpha
            # include alpha_max in tuning range
            args.alpha_max += args.alpha_step / 10.0

            if args.beta_max is None:
                args.beta_max = args.beta
            # include beta_max in tuning range
            args.beta_max += args.beta_step / 10.0

        # language model
            for alpha in np.arange(args.alpha, args.alpha_max, args.alpha_step):
                for beta in np.arange(args.beta, args.beta_max, args.beta_step):
                    logging.info('================================')
                    logging.info(f'Infering with (alpha, beta): ({alpha}, {beta})')
                    beam_search_with_lm = nemo_asr.BeamSearchDecoderWithLM(
                        vocab=vocab,
                        beam_width=args.beam_width,
                        alpha=alpha,
                        beta=beta,
                        lm_path=args.lm_path,
                        num_cpus=max(os.cpu_count(), 1),
                        input_tensor=False,
                    )
            self.beam_search_with_lm = beam_search_with_lm
                    

        self.data_preprocessor = data_preprocessor
        self.jasper_encoder = jasper_encoder
        self.jasper_decoder = jasper_decoder
        self.greedy_decoder = greedy_decoder
        self.neural_factory = neural_factory
        self.vocab = vocab
        self.args = args
        self.sample_rate = sample_rate
        
    def infer(self, wav_path, json_file):
        get_feature_json(wav_path, json_file)
        eval_datasets=json_file
        sample_rate=self.sample_rate
        vocab=self.vocab
        batch_size=1
        data_layer = nemo_asr.AudioToTextDataLayer(
            manifest_filepath=eval_datasets,
            sample_rate=sample_rate,
            labels=vocab,
            batch_size=batch_size,
        )
        
        audio_signal_e1, a_sig_length_e1, transcript_e1, transcript_len_e1 = data_layer()
        processed_signal_e1, p_length_e1 = self.data_preprocessor(input_signal=audio_signal_e1, length=a_sig_length_e1)
        encoded_e1, encoded_len_e1 = self.jasper_encoder(audio_signal=processed_signal_e1, length=p_length_e1)
        log_probs_e1 = self.jasper_decoder(encoder_output=encoded_e1)
        predictions_e1 = self.greedy_decoder(log_probs=log_probs_e1)
        eval_tensors = [log_probs_e1, predictions_e1, transcript_e1, transcript_len_e1, encoded_len_e1]

        # inference
        evaluated_tensors = self.neural_factory.infer(tensors=eval_tensors, checkpoint_dir=self.args.load_dir)
        
        greedy_hypotheses = post_process_predictions(evaluated_tensors[1], self.vocab)
        
        logprob = []
        for i, batch in enumerate(evaluated_tensors[0]):
            for j in range(batch.shape[0]):
                logprob.append(batch[j][: evaluated_tensors[4][i][j], :].cpu().numpy())
        if self.args.lm_path: 
            logprob = [np.exp(p) for p in logprob]
            beam_predictions = self.beam_search_with_lm(log_probs=logprob, log_probs_length=None, force_pt=True)
            beam_results = [b[0][1] for b in beam_predictions[0]]          
            return beam_results
        else:
            return greedy_hypotheses

_Originally posted by @wjyfelicity in https://github.com/NVIDIA/NeMo/issues/631#issuecomment-643049482_

**Comment by Engineering-Course** [comment]
New findings.
https://github.com/NVIDIA/NeMo/issues/631#issuecomment-645732118

**Comment by dmitrytyrin** [comment]
I faced some strange issue: kernel died in Jupyter Notebook/"Killed" in terminal while inference on large amount of audio (~800k small chunks of data) and batch size 2048/1024/512 (28/21/12 Gb in GPU). I can perform successfully only on first 10-15% of dataset.
Can my issue also be related to memory leak?

**Comment by dmitrytyrin** [comment]
I also face same issue: while ASR inference RAM consumption always increases. It causes fatal crush on large dataset inference.
Is it NeMo's problem or PyTorch (https://discuss.pytorch.org/t/pytorch-runtimeerror-enforce-fail-at-cpuallocator-cpp-56-posix-memalign-data-galignment-nbytes-0-12-vs-0/46072/8) ?

**Comment by dmitrytyrin** [comment]
I also face same issue: while ASR inference RAM consumption always increases. It causes fatal crush on large dataset inference.
Is it NeMo's problem or PyTorch (https://discuss.pytorch.org/t/pytorch-runtimeerror-enforce-fail-at-cpuallocator-cpp-56-posix-memalign-data-galignment-nbytes-0-12-vs-0/46072/8) ?

**Comment by carlfm01** [comment]
Any update? same issue here on large datasets.

**Comment by Slyne** [comment]
> I also face same issue: while ASR inference RAM consumption always increases. It causes fatal crush on large dataset inference.
> Is it NeMo's problem or PyTorch's (https://discuss.pytorch.org/t/pytorch-runtimeerror-enforce-fail-at-cpuallocator-cpp-56-posix-memalign-data-galignment-nbytes-0-12-vs-0/46072/8) ?

Not sure if this will help you . https://github.com/NVIDIA/NeMo/issues/240

**Comment by blisc** [comment]
Unfortunately, we have no plans to fix this in the near future. The workaround is to divide your dataset up into smaller partitions and run inference on each partition.

**Comment by yzhang123** [comment]
@Slyne does this help you? #631 (comment)

**Comment by orena1** [comment]
@blisc can you share what is the source of the problem ?
