### ISSUE TITLE
Experiment manager MlFlow logger does not log model checkpoints as artifacts

### ISSUE THREAD

**Issue by AlirezaMorsali** [NVIDIA/NeMo#7257]
**Is your feature request related to a problem? Please describe.**

MlFlow is required for training and resuming runs from checkpoint. Currently, when the MlFlow logger is enabled in experiment manager it doesn't log model checkpoint as artifacts to MLFlow

**Describe the solution you'd like**

One of the parameters (`log_model`) must to be passed to `pytorch_lightning.loggers.MLFlowLogger` is not defined in `nemo.utils.loggers.MLFlowParams` dataclass and cannot be set without modifying the code.

**Describe alternatives you've considered**

Doesn't seem to have an alternative

**Additional context**

**Comment by AlirezaMorsali** [comment]
> Could you send a PR with this change? Seems relatively simple to update the dataclass.

Yes, I created a PR the same day: #7258 .
Just updated it to last changes.

**Comment by titu1994** [comment]
Merged, thanks for the contribution !
