### ISSUE TITLE
File lists for pretrain model

### ISSUE THREAD

**Issue by Pavloveuge** [NVIDIA/NeMo#7279]
Hello, I read [this](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_ru_conformer_ctc_large) page and it says that you used `SOVA - RuAudiobooksDevices [260 hours] and RuDevices [75 hours] subsets`.
Could you share the file lists of these subsets? Or code to reproduce these subsets?

Thank you in advance.

@titu1994

**Comment by titu1994** [comment]
@vsl9

**Comment by Pavloveuge** [comment]
Hello, @vsl9, could you answer my question?
