### ISSUE TITLE
"get_commonvoice_data.py" is still work?

### ISSUE THREAD

**Issue by 15899885850** [NVIDIA/NeMo#7309]
Hi,
When I follow the tutorial "ASR_CTC_Language-Finetuning. ipynb" on Colab(https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/ASR_CTC_Language_Finetuning.ipynb),
I found this tutorial a bit outdated, so I tried to modify this line of code

```
VERSION="cv corpus 6.1-2020-12-11"
LANGUAGE="ja"
```

by
```
VERSION="cv corpus 14.0-2023-06-28"
LANGUAGE="ja"
```
Discovered that it didn't work anymore.
Here is the error message:
```
Resolving voice-prod-bundler-ee1969a6ce8178826482b88e843c335139bd3fb4.s3.amazonaws.com (voice-prod-bundler-ee1969a6ce8178826482b88e843c335139bd3fb4.s3.amazonaws.com)... 52.92.161.65, 52.218.224.66, 52.92.195.193, ...
Connecting to voice-prod-bundler-ee1969a6ce8178826482b88e843c335139bd3fb4.s3.amazonaws.com (voice-prod-bundler-ee1969a6ce8178826482b88e843c335139bd3fb4.s3.amazonaws.com)|52.92.161.65|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-08-24 02:24:22 ERROR 403: Forbidden.

Traceback (most recent call last):
  File "/content/scripts/get_commonvoice_data.py", line 214, in <module>
    main()
  File "/content/scripts/get_commonvoice_data.py", line 181, in main
    tar = tarfile.open(target_file)
  File "/usr/lib/python3.10/tarfile.py", line 1804, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('empty file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('empty file')
```

So I opened the xx file for review and found the code inside:
```
Parser.add_ Argument（
'-- version',
Default='cv corpus 5.1-2020-06-22 ',
Type=str,
Help='Version of the dataset (observable via https://commonvoice.mozilla.org/en/datasets ',
）
Parser.add_ Argument（
'-- language',
Default='en ',
Type=str,
Help='Which language to download.' (default English, '
Check https://commonvoice.mozilla.org/en/datasets For more language codes',
）
```
I don't know what to fill in for VERSION and LANGUAGE? I am on this website（ https://commonvoice.mozilla.org/en/datasets ）Didn't I find the answer I wanted in?

In addition, I would like to know if there is a relatively new tutorial that can help me train a new model. For example, if I want to train a Cantonese model, what should I do? 
I downloaded the dataset from CommonVoice and it no longer has the **dev/train/test.tsv** file. Instead, it has **other/validated/validated/reported.tsv,** times.txt, and a clip folder with audio. Does this mean I need to categorize the files in the clip into three parts of dev/train/test myself?

I hope to receive your reply as soon as possible!!!

**Comment by titu1994** [comment]
MCV no longer allows direct download via API, version 6 is the last one that allowed it and that's what we use for the demo. 

No other VERSION can be used in that tutorial unless you sign up for MCV and download dataset manually, write manifests manually etc. 

You can however change languages that were available in MCV 6

If you use Huggingface you can instead use this script to process the dataset from HF to NeMo format - https://github.com/NVIDIA/NeMo/blob/main/scripts/speech_recognition/convert_hf_dataset_to_nemo.py

You will however need to log into your hf account, visit the dataset page and manually click the button which accepts the terms and conditions of the dataset (for MCV at least). 

There is no newer tutorial for finetuning - that is the standard one for all models and is up to date.

The dataset without train valid test split are the unverified dataset that has not undergone transcription check from volunteers. The text may likely be incorrect so we don't suggest to use it. 

If you still want to use it, you'll have to create your own train dev set out of those files

**Comment by 15899885850** [comment]
> MCV no longer allows direct download via API, version 6 is the last one that allowed it and that's what we use for the demo.
> 
> No other VERSION can be used in that tutorial unless you sign up for MCV and download dataset manually, write manifests manually etc.
> 
> You can however change languages that were available in MCV 6
> 
> If you use Huggingface you can instead use this script to process the dataset from HF to NeMo format - https://github.com/NVIDIA/NeMo/blob/main/scripts/speech_recognition/convert_hf_dataset_to_nemo.py
> 
> You will however need to log into your hf account, visit the dataset page and manually click the button which accepts the terms and conditions of the dataset (for MCV at least).
> 
> There is no newer tutorial for finetuning - that is the standard one for all models and is up to date.
> 
> The dataset without train valid test split are the unverified dataset that has not undergone transcription check from volunteers. The text may likely be incorrect so we don't suggest to use it.
> 
> If you still want to use it, you'll have to create your own train dev set out of those files

Thank you for your reply! I roughly understand!
That is to say, I can manually split certain datasets into dev/train/test parts (even if they are verified to be valid), and still refer to this tutorial for training, right?

**Comment by titu1994** [comment]
Yes, but again we don't recommend it. The data in the unverified MCV is super noisy with completely incorrect transcripts sometimes

**Comment by 15899885850** [comment]
> Yes, but again we don't recommend it. The data in the unverified MCV is super noisy with completely incorrect transcripts sometimes

Thank you, I will pay special attention to this point. Wishing you a nice day!
