### ISSUE TITLE
TTS Model and Inference Tutorial not working

### ISSUE THREAD

**Issue by asusdisciple** [NVIDIA/NeMo#7313]
**Describe the bug**

The tutorial links in https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/starthere/tutorials.html are not working for the TTS stuff like Fastpitch. There are also bugs in the code of some of the jupyternotebooks. The code in the ngc models for the tutorials also does not work if you take it from the overview tab in https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/tts_de_fastpitch_multispeaker_5.

**Comment by XuesongYang** [comment]
could you pls share detailed error logs? and on what branch? Thanks.
