### ISSUE TITLE
QuartNet evaluation

### ISSUE THREAD

**Issue by BuaaAlban** [NVIDIA/NeMo#732]
Excuse me , how to make evaluation using the [pretrained model ](https://ngc.nvidia.com/catalog/models/nvidia:multidataset_quartznet15x5)??

The[ tutorial ](https://nvidia.github.io/NeMo/asr/tutorial.html) says  
python <nemo_git_repo_root>/examples/asr/jasper_eval.py --model_config=<nemo_git_repo_root>/examples/asr/configs/quartznet15x5.yaml --eval_datasets "<path_to_data>/dev_clean.json" --load_dir=<directory_containing_checkpoints>

But I don't see the file jasper_eval,  can I  use the examples/asr/speech2text_infer.py? 
By the way, where can I get asscess to the backend of the model, namely like in pytorch

Thanks 
----------------------------------------
I found it in asr/other/jasper_eval.py and run it sucessfully
But I still wonder how to change it into pytorch so that we can calculate its FLops by its forward pass

**Comment by okuchaiev** [comment]
Checkout the stable branch: https://github.com/NVIDIA/NeMo/tree/v0.10.1
If you'd like to test the new code from master, then you can run inference like this:
```
cd examples/asr && CUDA_VISIBLE_DEVICES=0 python speech2text_infer.py --asr_model=QuartzNet15x5-En --dataset=/home/TestData/librispeech/librivox-dev-other.json
```
This will grab pre-trained weights automatically.
