### ISSUE TITLE
ImportError: scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by UserName-wang** [NVIDIA/NeMo#7331]
**Describe the bug**

tried to run: NeMo/tutorials/00_NeMo_Primer.ipynb

got error message after this command:
import nemo.collections.asr as nemo_asr

**Environment details**
environment: jetson agx orin, jetpack 5.1.2, in a docker: [dustynv/nemo:r35.3.1](https://hub.docker.com/r/dustynv/nemo/tags)

[error_message.txt](https://github.com/NVIDIA/NeMo/files/12450309/error_message.txt)

**Comment by titu1994** [comment]
NeMo doesn't support Jetson. It's primarily used in Linux and mac envs only. Windows can use it with WSL2.

**Comment by UserName-wang** [comment]
oh, that's bad news for me. thank you for your reply!
