### ISSUE TITLE
Replace 'fasttext' with 'fasttext-wheel' in requirements_nlp

### ISSUE THREAD

**Issue by mirix** [NVIDIA/NeMo#7344]
**Describe the bug**

It is not possible to install the requirements of the NLP component because the fasttext wheel cannot be build any more. However, there is a fork called fasttext-wheel that can be installed with pip. I have tested it extensively and it works with NeMo

**Steps/Code to reproduce bug**

```
pip install -r requirement/requirements_nlp.txt 
```

**Expected behavior**

To be able to install NLP component of the NeMo toolkit without having to hack the requirements_nlp file each time.

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal
 - Method of NeMo install:  pip and source

```
pip install "git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]"
```

or  (from source)

```
pip install -e ".[all]"
```

**Environment details**

- OS version : Manjaro Linux (current)
- PyTorch version: Nightly builds with Cuda 12.1 (pip)
- Python version: 3.8.18 (NeMo does not work with more recent Python versions) 

**Additional context**

**Comment by RobinDong** [comment]
Hi @mirix I tried below steps but seems all the packages in `requirement/requirements_nlp.txt` could be installed successfully:
1. `conda create -n nemo_test python=3.8`
2. `conda activate nemo_test`
3. `python3 -m pip install "git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]"`
4. `python3 -m pip install -r requirement/requirements_nlp.txt (no errors)`

**Comment by mirix** [comment]
Perhaps it works within a conda environment.

I do:

```
cd ~/Downloads
python3.8 -m venv nemo
source ~/Downloads/nemo/bin/activate
python -m pip install "git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]"
```

And it fails unless I edit the requirements file manually with:

```
git clone https://github.com/NVIDIA/NeMo
cd NeMo
```

Edit requirement/requirements_nlp.txt and replace "fasttext" with "fasttext-wheel" (otherwise it fails as well).

```
pip install -e ".[all]"
```

Several people have been reporting similar issues for a while, check, for instance:

https://github.com/facebookresearch/fastText/issues/1298

**Comment by RobinDong** [comment]
@mirix I repeated your commands in my debian:
```
cd ~/Downloads
python3.8 -m venv nemo
source ~/Downloads/nemo/bin/activate
python -m pip install "git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]"
```
It reports errors like this:
```
  Building wheel for docopt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/rdong_woolworths_com_au/Downloads/nemo/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q2t2e59t/docopt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q2t2e59t/docopt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yf5s5gae
       cwd: /tmp/pip-install-q2t2e59t/docopt/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for docopt
  Running setup.py clean for docopt
```
```
ERROR: flask 2.3.3 has requirement click>=8.1.3, but you'll have click 8.0.2 which is incompatible.
ERROR: jiwer 3.0.3 has requirement click<9.0.0,>=8.1.3, but you'll have click 8.0.2 which is incompatible.
```
But at last it report
```
Successfully built nemo-toolkit
```
And by using `pip list|grep nemo`, I saw that the `nemo-toolkit` has been installed.

**Comment by mirix** [comment]
Lucky you! Thanks.
