### ISSUE TITLE
Voice Conversion Tutorial

### ISSUE THREAD

**Issue by babat00nday** [NVIDIA/NeMo#7346]
I am trying to use NeMo for voice conversion and I am looking for a tutorial notebook that explains how I can do this.

Basically I want to provide 2 wav files as input and have the output be a single wav file that contains the speech from one file with the voice from the other file.

I went through the documentation for examples and tutorials and could not find how I could achieve this.

**Comment by babat00nday** [comment]
@titu1994 or @okuchaiev 

any updates on this.

**Comment by titu1994** [comment]
Probably tts team can help

**Comment by redoctopus** [comment]
@subhankar-ghosh does this sound like something that would relate to the multispeaker models you've worked on?
