### ISSUE TITLE
cannot import name 'JobStatus' from 'hydra.core.utils'

### ISSUE THREAD

**Issue by pragyachaturvedi99** [NVIDIA/NeMo#7349]
**Describe the bug**

cannot import name 'JobStatus' from 'hydra.core.utils'.
I have cloned Nemo git repository on my vm instance and am trying to resolve this import issue
**Execute Fastpitch_fintetune.ipynb in import cell**

**Comment by RobinDong** [comment]
I run `FastPitch_Finetuning.ipynb` (from main branch) in google Colab. The only error I got was:
```
2023-09-05 05:30:02.056972: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[NeMo W 2023-09-05 05:30:06 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
    See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
      ret = run_job(
    
Error executing job with overrides: ['train_dataset=./9017_manifest_train_dur_5_mins_local.json', 'validation_datasets=./9017_manifest_dev_ns_all_local.json', 'sup_data_path=./fastpitch_sup_data', 'phoneme_dict_path=tts_dataset_files/cmudict-0.7b_nv22.10', 'heteronyms_path=tts_dataset_files/heteronyms-052722', 'exp_manager.exp_dir=./ljspeech_to_9017_no_mixing_5_mins', '+init_from_nemo_model=./tts_en_fastpitch_align.nemo', '+trainer.max_steps=1000', '~trainer.max_epochs', 'trainer.check_val_every_n_epoch=25', 'model.train_ds.dataloader_params.batch_size=24', 'model.validation_ds.dataloader_params.batch_size=24', 'model.n_speakers=1', 'model.pitch_mean=152.3', 'model.pitch_std=64.0', 'model.pitch_fmin=30', 'model.pitch_fmax=512', 'model.optim.lr=2e-4', '~model.optim.sched', 'model.optim.name=adam', 'trainer.devices=1', 'trainer.strategy=null', '+model.text_tokenizer.add_blank_at=true']
Traceback (most recent call last):
  File "/content/fastpitch_finetune.py", line 30, in main
    trainer = pl.Trainer(**cfg.trainer)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 399, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 140, in __init__
    self._check_config_and_set_final_flags(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 210, in _check_config_and_set_final_flags
    raise ValueError(
ValueError: You selected an invalid strategy name: `strategy=None`. It must be either a string or an instance of `pytorch_lightning.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai/

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
After removing `trainer.strategy=null` in argument list, all steps could pass.

@pragyachaturvedi99 Do you mind sharing your version of `FastPitch_Finetuning.ipynb` and details about the error of `JobStatus`?

**Comment by pragyachaturvedi99** [comment]
https://github.com/NVIDIA/NeMo/blob/stable/tutorials/tts/FastPitch_Finetuning.ipynb

**Comment by pragyachaturvedi99** [comment]
I tried resolving this error and ran into another error related to omegaconff what version of hydra are you using
?

**Comment by XuesongYang** [comment]
it seems related to Pytorch Lightning version.

* After Pytorch lightning 2.0: `trainer.strategy=None` is not support anymore, instead, [        strategy: Union[str, Strategy] = "auto",
](https://github.com/Lightning-AI/lightning/blob/2.0.8/src/lightning/pytorch/trainer/trainer.py#L93)
* Before Pytorch lightning 2.0: [strategy: Optional[Union[str, Strategy]] = None](https://github.com/Lightning-AI/lightning/blob/1.9.5/src/pytorch_lightning/trainer/trainer.py#L153)

**Comment by pragyachaturvedi99** [comment]
{
	"name": "NameError",
	"message": "name '_DEFAULT_MARKER_' is not defined",
	"stack": "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)\nCell \u001b[0;32mIn[5], line 9\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mmatplotlib\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mpyplot\u001b[39;00m \u001b[39mimport\u001b[39;00m imshow\n\u001b[1;32m      7\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mmatplotlib\u001b[39;00m \u001b[39mimport\u001b[39;00m pyplot \u001b[39mas\u001b[39;00m plt\n\u001b[0;32m----> 9\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mmodels\u001b[39;00m \u001b[39mimport\u001b[39;00m FastPitchModel\n\u001b[1;32m     10\u001b[0m FastPitchModel\u001b[39m.\u001b[39mfrom_pretrained(\u001b[39m\"\u001b[39m\u001b[39mtts_en_fastpitch\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m     12\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mpathlib\u001b[39;00m \u001b[39mimport\u001b[39;00m Path\n\nFile \u001b[0;32m~/.local/lib/python3.8/site-packages/nemo/collections/tts/__init__.py:15\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[39m#\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[39m# Licensed under the Apache License, Version 2.0 (the \"License\");\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[39m# See the License for the specific language governing permissions and\u001b[39;00m\n\u001b[1;32m     13\u001b[0m \u001b[39m# limitations under the License.\u001b[39;00m\n\u001b[0;32m---> 15\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m \u001b[39mimport\u001b[39;00m data, losses, models, modules\n\u001b[1;32m     16\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mpackage_info\u001b[39;00m \u001b[39mimport\u001b[39;00m __version__\n\u001b[1;32m     18\u001b[0m \u001b[39m# Set collection version equal to NeMo version.\u001b[39;00m\n\nFile \u001b[0;32m~/.local/lib/python3.8/site-packages/nemo/collections/tts/losses/__init__.py:15\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[39m#\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[39m# Licensed under the Apache License, Version 2.0 (the \"License\");\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[39m# See the License for the specific language governing permissions and\u001b[39;00m\n\u001b[1;32m     13\u001b[0m \u001b[39m# limitations under the License.\u001b[39;00m\n\u001b[0;32m---> 15\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mlosses\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mfastpitchloss\u001b[39;00m\n\u001b[1;32m     16\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mlosses\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhifigan_losses\u001b[39;00m\n\nFile \u001b[0;32m~/.local/lib/python3.8/site-packages/nemo/collections/tts/losses/fastpitchloss.py:48\u001b[0m\n\u001b[1;32m     45\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mtorch\u001b[39;00m\n\u001b[1;32m     46\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mtorch\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mnn\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mfunctional\u001b[39;00m \u001b[39mas\u001b[39;00m \u001b[39mF\u001b[39;00m\n\u001b[0;32m---> 48\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mmodules\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtransformer\u001b[39;00m \u001b[39mimport\u001b[39;00m mask_from_lens\n\u001b[1;32m     49\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcore\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mclasses\u001b[39;00m \u001b[39mimport\u001b[39;00m Loss, typecheck\n\u001b[1;32m     50\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcore\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mneural_types\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39melements\u001b[39;00m \u001b[39mimport\u001b[39;00m (\n\u001b[1;32m     51\u001b[0m     LengthsType,\n\u001b[1;32m     52\u001b[0m     LossType,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     56\u001b[0m     TokenLogDurationType,\n\u001b[1;32m     57\u001b[0m )\n\nFile \u001b[0;32m~/.local/lib/python3.8/site-packages/nemo/collections/tts/modules/__init__.py:15\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[39m#\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[39m# Licensed under the Apache License, Version 2.0 (the \"License\");\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[39m# See the License for the specific language governing permissions and\u001b[39;00m\n\u001b[1;32m     13\u001b[0m \u001b[39m# limitations under the License.\u001b[39;00m\n\u001b[0;32m---> 15\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mmodules\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39madapters\u001b[39;00m\n\u001b[1;32m     16\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mmodules\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mfastpitch\u001b[39;00m \u001b[39mimport\u001b[39;00m Decoder \u001b[39mas\u001b[39;00m FastpitchDecoder\n\u001b[1;32m     17\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mmodules\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mfastpitch\u001b[39;00m \u001b[39mimport\u001b[39;00m Encoder \u001b[39mas\u001b[39;00m FastpitchEncoder\n\nFile \u001b[0;32m~/.local/lib/python3.8/site-packages/nemo/collections/tts/modules/adapters.py:17\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \u001b[39m#\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[39m# Licensed under the Apache License, Version 2.0 (the \"License\");\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[39m# See the License for the specific language governing permissions and\u001b[39;00m\n\u001b[1;32m     13\u001b[0m \u001b[39m# limitations under the License.\u001b[39;00m\n\u001b[1;32m     15\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtyping\u001b[39;00m \u001b[39mimport\u001b[39;00m List, Optional\n\u001b[0;32m---> 17\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39momegaconf\u001b[39;00m \u001b[39mimport\u001b[39;00m DictConfig\n\u001b[1;32m     19\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39masr\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mparts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mutils\u001b[39;00m \u001b[39mimport\u001b[39;00m adapter_utils\n\u001b[1;32m     20\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mnemo\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcollections\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtts\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mmodules\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39maligner\u001b[39;00m \u001b[39mimport\u001b[39;00m AlignmentEncoder\n\nFile \u001b[0;32m~/.local/lib/python3.8/site-packages/omegaconf/__init__.py:20\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mlistconfig\u001b[39;00m \u001b[39mimport\u001b[39;00m ListConfig\n\u001b[1;32m     11\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mnodes\u001b[39;00m \u001b[39mimport\u001b[39;00m (\n\u001b[1;32m     12\u001b[0m     AnyNode,\n\u001b[1;32m     13\u001b[0m     BooleanNode,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     18\u001b[0m     ValueNode,\n\u001b[1;32m     19\u001b[0m )\n\u001b[0;32m---> 20\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39momegaconf\u001b[39;00m \u001b[39mimport\u001b[39;00m (\n\u001b[1;32m     21\u001b[0m     II,\n\u001b[1;32m     22\u001b[0m     MISSING,\n\u001b[1;32m     23\u001b[0m     SI,\n\u001b[1;32m     24\u001b[0m     OmegaConf,\n\u001b[1;32m     25\u001b[0m     Resolver,\n\u001b[1;32m     26\u001b[0m     flag_override,\n\u001b[1;32m     27\u001b[0m     open_dict,\n\u001b[1;32m     28\u001b[0m     read_write,\n\u001b[1;32m     29\u001b[0m )\n\u001b[1;32m     30\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mversion\u001b[39;00m \u001b[39mimport\u001b[39;00m __version__\n\u001b[1;32m     32\u001b[0m __all__ \u001b[39m=\u001b[39m [\n\u001b[1;32m     33\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39m__version__\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[1;32m     34\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mMissingMandatoryValue\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     57\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mII\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[1;32m     58\u001b[0m ]\n\nFile \u001b[0;32m~/.local/lib/python3.8/site-packages/omegaconf/omegaconf.py:134\u001b[0m\n\u001b[1;32m    129\u001b[0m                 \u001b[39mraise\u001b[39;00m ValidationError(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mEnvironment variable \u001b[39m\u001b[39m'\u001b[39m\u001b[39m{\u001b[39;00mkey\u001b[39m}\u001b[39;00m\u001b[39m'\u001b[39m\u001b[39m not found\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    131\u001b[0m     OmegaConf\u001b[39m.\u001b[39mregister_resolver(\u001b[39m\"\u001b[39m\u001b[39menv\u001b[39m\u001b[39m\"\u001b[39m, env)\n\u001b[0;32m--> 134\u001b[0m \u001b[39mclass\u001b[39;00m \u001b[39mOmegaConf\u001b[39;00m:\n\u001b[1;32m    135\u001b[0m \u001b[39m    \u001b[39m\u001b[39m\"\"\"OmegaConf primary class\"\"\"\u001b[39;00m\n\u001b[1;32m    137\u001b[0m     \u001b[39mdef\u001b[39;00m \u001b[39m__init__\u001b[39m(\u001b[39mself\u001b[39m) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mNone\u001b[39;00m:\n\nFile \u001b[0;32m~/.local/lib/python3.8/site-packages/omegaconf/omegaconf.py:195\u001b[0m, in \u001b[0;36mOmegaConf\u001b[0;34m()\u001b[0m\n\u001b[1;32m    184\u001b[0m \u001b[39m@staticmethod\u001b[39m\n\u001b[1;32m    185\u001b[0m \u001b[39m@overload\u001b[39m\n\u001b[1;32m    186\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mcreate\u001b[39m(\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    189\u001b[0m     flags: Optional[Dict[\u001b[39mstr\u001b[39m, \u001b[39mbool\u001b[39m]] \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m,\n\u001b[1;32m    190\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m DictConfig:\n\u001b[1;32m    191\u001b[0m     \u001b[39m.\u001b[39m\u001b[39m.\u001b[39m\u001b[39m.\u001b[39m\n\u001b[1;32m    193\u001b[0m \u001b[39m@staticmethod\u001b[39m\n\u001b[1;32m    194\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mcreate\u001b[39m(  \u001b[39m# noqa F811\u001b[39;00m\n\u001b[0;32m--> 195\u001b[0m     obj: Any \u001b[39m=\u001b[39m _DEFAULT_MARKER_,\n\u001b[1;32m    196\u001b[0m     parent: Optional[BaseContainer] \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m,\n\u001b[1;32m    197\u001b[0m     flags: Optional[Dict[\u001b[39mstr\u001b[39m, \u001b[39mbool\u001b[39m]] \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m,\n\u001b[1;32m    198\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Union[DictConfig, ListConfig]:\n\u001b[1;32m    199\u001b[0m     \u001b[39mreturn\u001b[39;00m OmegaConf\u001b[39m.\u001b[39m_create_impl(\n\u001b[1;32m    200\u001b[0m         obj\u001b[39m=\u001b[39mobj,\n\u001b[1;32m    201\u001b[0m         parent\u001b[39m=\u001b[39mparent,\n\u001b[1;32m    202\u001b[0m         flags\u001b[39m=\u001b[39mflags,\n\u001b[1;32m    203\u001b[0m     )\n\u001b[1;32m    205\u001b[0m \u001b[39m@staticmethod\u001b[39m\n\u001b[1;32m    206\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mload\u001b[39m(file_: Union[\u001b[39mstr\u001b[39m, pathlib\u001b[39m.\u001b[39mPath, IO[Any]]) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m Union[DictConfig, ListConfig]:\n\n\u001b[0;31mNameError\u001b[0m: name '_DEFAULT_MARKER_' is not defined"
}

**Comment by javyduck** [comment]
pip install --upgrade hydra-core

this works for me
