### ISSUE TITLE
N-gram Language model with Hybrid transducer CTC large. 

### ISSUE THREAD

**Issue by arvindmn01** [NVIDIA/NeMo#7350]
Hi, I am trying to use N-gram language model with Hybrid Transducer CTC large. but i am getting an error.
I loaded model using the below code.
```import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecHybridRNNTCTCBPEModel.from_pretrained(model_name="stt_en_fastconformer_hybrid_large_pc")
```

I am following this  [https://github.com/NVIDIA/NeMo/blob/acbd88257f20e776c09f5015b8a793e1bcfa584d/tutorials/asr/Offline_ASR.ipynb](tutorial) to add language model .

```lm_path="/content/5gram_correct.arpa"

beam_search_lm = nemo_asr.modules.BeamSearchDecoderWithLM(
    vocab=list(asr_model.decoder.vocabulary),
    beam_width=16,
    alpha=1, beta=1.5,
    lm_path=lm_path,
    num_cpus=max(os.cpu_count(), 1),
    input_tensor=False)
```
but i am getting this error.

`AttributeError: 'RNNTDecoder' object has no attribute 'vocabulary'`
is there any way to use N-gram language model with Hybrid Transducer CTC large?

**Comment by titu1994** [comment]
You have to first change the hybrid model to CTC mode by using 
model.change_decoding_strategy(model.cfg.decoding, decoder_type="ctc")

# optionally save the model to disk
model.save_to("XYZ-ctc.nemo")

Then you can use this model in the inference tutorial for beam search. 

By default the RNNT decoder is used for hybrid models.

**Comment by gabitza-tech** [comment]
Hi @titu1994,

Sorry if it might be unrelated to the issue, but I am curious if there are any disadvantages to training a hybrid model vs training a ctc/transducer model separately? 

Can hybrid models use external decoders such as flashlight/pyctcdecode for ctc?(if I change decoding_strategy="ctc")

Thank you in advance!

**Comment by titu1994** [comment]
There are no disadvantages as far as we can see. Since we wanted P&C capabilities, and didn't want to train two models, we developed all hybrid models only. This also improved the accuracy on CTC models along with reduced training cost. 

If you change decoder type, it should functionally be pretty much the same as CTC model. If it's not, let us know.

**Comment by gabitza-tech** [comment]
> There are no disadvantages as far as we can see. Since we wanted P&C capabilities, and didn't want to train two models, we developed all hybrid models only. This also improved the accuracy on CTC models along with reduced training cost.
> 
> If you change decoder type, it should functionally be pretty much the same as CTC model. If it's not, let us know.

Thank you so much for your clear and fast response! Have a great day!

**Comment by bofenghuang** [comment]
Hi @titu1994 !

If I comprehend correctly, hybrid models help speed up the convergence for CTC models while achieving comparable performance during CTC branch decoding with pure CTC models. How does the hybrid model with a transducer decoder compare to a pure transducer model? The Open ASR Leaderboard suggests that transducer models outperform CTC models (without LM). Where does the hybrid model with a transducer branch fit into this context? Assuming sufficient GPU resources, should I prioritize training a pure transducer model or opt for a hybrid approach to achieve optimal performance?

Thank you in advance!

**Comment by titu1994** [comment]
There's no difference between hybrid models and RNNT models in terms of accuracy. They get the same score +- init noise. If you think you will never need a CTC model trained on your dataset, you can for convenience train just an RNNT model. It will take you 1x compute (as baseline). If you think you will some day want a fast ctc model on the same dataset, you might as well just train a hybrid model in one go, paying about 1.2-1.3x compute. It's going to get better accuracy for your CTC decoder, plus the compute cost is much lower than trying to train a CTC decoder on its own (3-4x). 

So the only difference is a slight increase in compute cost. If you are ok with that, we suggest hybrid models. It's two for the cost of one, plus you can do more things with it such as CTC + ngram, forced alignment with NFA, long audio fast inference (10+ hours in seconds etc). 

CTC ain't bad, just slightly less accurate. The cost for training it is also much reduced, and the model will get better accuracy than if it was trained with just CTC loss. 

Though for purely accuracy comparison, RNNT will almost always be better than CTC.
