### ISSUE TITLE
request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by MinnerLi** [NVIDIA/NeMo#7354]
When I pull the Nemo image use command "docker pull nvcr.io/nvidia/nemo:23.06",I receive this message：
Error response from daemon: Get https://nvcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

How can i sovle this problem ?

**Comment by RobinDong** [comment]
@MinnerLi I tried `docker pull nvcr.io/nvidia/nemo:23.06` on my desktop and it works well. I guess your network environment is not good. 
You could try to use this command in another computer or network. Or run the command in a VM of a cloud.

**Comment by MinnerLi** [comment]
> @MinnerLi I tried `docker pull nvcr.io/nvidia/nemo:23.06` on my desktop and it works well. I guess your network environment is not good. You could try to use this command in another computer or network. Or run the command in a VM of a cloud.

Thank you. This is indeed a problem with my network
