### ISSUE TITLE
v1.5.0, megatron-lm == 1.1.5 not install

### ISSUE THREAD

**Issue by 60wanjinbing** [NVIDIA/NeMo#7375]
when i install v1.5.0, megatron-lm == 1.1.5 not install, can you help me? pip install megatron-lm == 1.1.5 not work

**Comment by RobinDong** [comment]
Hi @60wanjinbing , do you mean the `v1.5.0` tag? I have checked out the `v1.5.0` tag. But there isn't `megatron-lm` in `requirements/*`

**Comment by 60wanjinbing** [comment]
sorry, the v1.0.0b4 tag.

**Comment by RobinDong** [comment]
> v1.0.0b4

It's a very old tag. From this release page of [megatron-lm](https://github.com/NVIDIA/Megatron-LM/releases), I guess the old `megatron-lm 1.1.5` has been deprecated. And even the name `megatron-lm` has been changed to `megatron_core`.

**Comment by 60wanjinbing** [comment]
thank you , i want install NeMo on Jetson nano, cuda 10.2.  Which NeMo version needs to be installed?
