### ISSUE TITLE
How does the fastpitch adapter model work?

### ISSUE THREAD

**Issue by Pydataman** [NVIDIA/NeMo#7377]

**Comment by XuesongYang** [comment]
here you go: https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/FastPitch_Adapter_Finetuning.ipynb

**Comment by zaidato** [comment]
@XuesongYang, I followed the steps in https://github.com/NVIDIA/NeMo/blob/main/tutorials/tts/FastPitch_Adapter_Finetuning.ipynb. But when I train FastPitch_MultiSpeaker_Pretraining.ipynb. Inference output was just the noise. It cannot pronounce any words. I already did exactly steps in the tutorial
