### ISSUE TITLE
megatron_change_num_partitions.py does not seem to handle `dense_h_to_4h.bias`

### ISSUE THREAD

**Issue by odelalleau** [NVIDIA/NeMo#7383]
**Describe the bug**

In megatron_change_num_partitions.py  there is dedicated code to handle splitting some layers with fast GLU activations:
* https://github.com/NVIDIA/NeMo/blob/c5ef26cafa935f9966ab3f074248913aef7fa509/examples/nlp/language_modeling/megatron_change_num_partitions.py#L236
* https://github.com/NVIDIA/NeMo/blob/c5ef26cafa935f9966ab3f074248913aef7fa509/examples/nlp/language_modeling/megatron_change_num_partitions.py#L278

However, this code seems to only handle the `.weight` part, not the `.bias` part. And it seems like the bias would also require some special handling: https://github.com/NVIDIA/NeMo/blob/8508e07a20edbfac6e37fdf252c036f4e2215654/nemo/collections/nlp/modules/common/megatron/mlp.py#L220

**Steps/Code to reproduce bug**

I haven't actually tried to trigger a bug because of this -- I am opening this issue because I suspect there is a bug.

**Expected behavior**

I would have expected the `.bias` to be handled as well (or a `NotImplementedError` exception if it is known that this is not supported yet).

**Additional context**

Tagging people who dealt with this code: @titu1994 / @hsiehjackson

**Comment by titu1994** [comment]
Indeed this is a bug. Ive sent PR #7386 for a fix. 
While NeMo models don't use bias, Llama models do.
