### ISSUE TITLE
error in examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb

### ISSUE THREAD

**Issue by jackieassa** [NVIDIA/NeMo#742]
Running the current .ipynb in colab returns an error due to missing files in section " Specifying Our Model with a YAML Config File"

Resolution:

Looking into it I saw that:
in section Specifying Our Model with a YAML Config File

code block beginning with 
... Config Information 
in line 5 current code is:
config_path = '../configs/jasper_an4.yaml'
where it should be
config_path = '../configs/jasper_an4.yaml'

as the cwd on colab is /content
This solves the problem and allows me to complete the notebook

**Comment by redoctopus** [comment]
This should be fixed as of #738. Let us know if you still run into any issues!
