### ISSUE TITLE
pytorch lightning strategy = None prompt error during trainer config

### ISSUE THREAD

**Issue by tkcoding** [NVIDIA/NeMo#7439]
For trainer through pytorch lightning strategy = None prompt error.

```
ValueError: You selected an invalid strategy name: `strategy=None`. It must be either a string or an instance of `pytorch_lightning.strategies.Strategy`. Example choices: auto, ddp, ddp_spawn, deepspeed, ... Find a complete list of options in our documentation at https://lightning.ai/
```

To reproduce :
- Running notebook on strategy = None with pytorch lightning version 2.0.7 
-https://github.com/NVIDIA/NeMo/blame/83d6614fbf29cf885f3bc36233f6e3758ba8f1e3/tutorials/speaker_tasks/Speaker_Identification_Verification.ipynb#L478
- Run https://github.com/NVIDIA/NeMo/blame/83d6614fbf29cf885f3bc36233f6e3758ba8f1e3/tutorials/speaker_tasks/Speaker_Identification_Verification.ipynb#L494

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

**Expected behavior**
https://github.com/NVIDIA/NeMo/blame/83d6614fbf29cf885f3bc36233f6e3758ba8f1e3/tutorials/speaker_tasks/Speaker_Identification_Verification.ipynb#L494 pytorch trainer should be able to configured without issue.

**Environment overview (please complete the following information)**

 - Environment location: AWS
 - Method of NeMo install:  pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[asr]

**Environment details**

- PyTorch version

**Additional context**

**Comment by titu1994** [comment]
This will be fixed in NeMo 1.21.0
