### ISSUE TITLE
Resuming from last checkpoint is broken with tensor parallelism

### ISSUE THREAD

**Issue by odelalleau** [NVIDIA/NeMo#7458]
**Describe the bug**

When running an experiment where the model is using tensor parallelism, the `exp_manager.resume_if_exists` option fails to load the last checkpoint when resuming the experiment.

**Steps/Code to reproduce bug**

* Launch an experiment with a TP>1 model and stop it after saving the first checkpoint
* Try to resume the experiment, and notice the warning:

```
`[NeMo W 2023-09-19 01:42:57 exp_manager:591] There were no checkpoints found in checkpoint_dir or no
checkpoint folder at checkpoint_dir:  /path/to/checkpoints. Training from scratch.`
```

**Expected behavior**

It should resume from the last checkpoint saved.

**Environment overview (please complete the following information)**

 - Environment location: Docker
 - Method of NeMo install: from Docker image (was taken from a recent nightly build)

**Additional context**

At first glance I suspect the issue came from https://github.com/NVIDIA/NeMo/pull/7116/files due to changing `rglob` into `glob` (cc @ericharper) ==> since the .ckpt files are under the `mp_rank_xy` subfolders, they are not found by `glob`.

(if the fix is just to change it back to `rglob` I'm happy to submit a PR, but I assume there's a reason why it was changed)

**Comment by ericharper** [comment]
I think we fixed this in the release branch already, the PR here just needs to be merged to main

**Comment by odelalleau** [comment]
This works, thanks!
