### ISSUE TITLE
Request to change setuptools version

### ISSUE THREAD

**Issue by pplantinga** [NVIDIA/NeMo#7475]
**Describe the bug**

In my environment, the pinned version of setuptools is unavailable (`setuptools==65.5.1`). This is a request to unpin or update to a more recent version (latest is `setuptools==68.2.2`).

**Comment by RobinDong** [comment]
The `nemo-toolkit` need the package `nemo-text-processing`, which is also set a fixed version for `setuptools` https://github.com/NVIDIA/NeMo-text-processing/blob/main/requirements/requirements.txt#L9
To unpin the version, we may need to change `requirement.txt` for at least these two repos.
