### ISSUE TITLE
Converting NeMo TTS models to ONNX / TensorRT

### ISSUE THREAD

**Issue by rinjac** [NVIDIA/NeMo#748]
Hello,

I have a question regarding conversion of NeMo-created TTS models. While for speech-2-text models there is a script available (in /scripts folder) to convert a NeMo-created PyTorch model into ONNX and then into TensorRT, no such script exists for text-2-speech models (Tacatron2 and WaveGlow). Is there a plan to create/provide those scripts?

Thank you in advance,
Robert

**Comment by sciai-ai** [comment]
Any update on this?

**Comment by ahkarami** [comment]
Can we convert TTS models (e.g., Tacotron2) to ONNX?

**Comment by JayZ92-99** [comment]
Can we convert FastPitch and HifiGan nemo models to TensorRT ?

**Comment by prashantskit** [comment]
@ahkarami Were you able to convert tacotron2 to onnx?

**Comment by eliashossain001** [comment]
result = self.forward(*input, **kwargs)
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/TTS/tts/models/align_tts.py", line 326, in forward
    raise KeyError("Expected 'mels' key in 'y' input")
KeyError: "Expected 'mels' key in 'y' input"
Can someone please help me to convert AlignTTS model to ONNX? I get the above error when converting to ONNX.

Here is my example code:
`
args = AlignTTSArgs(num_chars=105, out_channels=80, hidden_channels=256, hidden_channels_dp=256, 
                    encoder_type='fftransformer', encoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                    decoder_type='fftransformer', decoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                    length_scale=1.0, num_speakers=0, use_speaker_embedding=False, use_d_vector_file=False, d_vector_dim=0)

# create an instance of AlignTTS
model = AlignTTS(config=args)

# load the saved checkpoint
checkpoint_path = '/path/to/modified_checkpoint.pth'
checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))

# load the state dict into the model
model.load_state_dict(checkpoint['model'])

# set the model to evaluation mode
model.eval()

# convert the model to ONNX format
input_shape = (8, 80, 105)
output_path = 'align_tts_model.onnx'
dummy_input = torch.randn(input_shape)
y_lengths = torch.LongTensor([105, 102, 98, 101, 100, 103, 97, 104])  # example values for y_lengths
torch.onnx.export(model, (dummy_input, y_lengths), output_path, verbose=True)`
