### ISSUE TITLE
KeyError for T5 Text Normalization with latest transformers version

### ISSUE THREAD

**Issue by murali1996** [NVIDIA/NeMo#7526]
**Describe the bug**

Following the installation guide in README installs the latest transformers version. However the starter code provided here https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/neural_text_normalization_t5 fails to work with an error 
```
RuntimeError: Error(s) in loading state_dict for DuplexTaggerModel:
        Unexpected key(s) in state_dict: "model.albert.embeddings.position_ids".
```

**Steps/Code to reproduce bug**

[Same as in description above]

**Expected behavior**

RuntimeError in this line
```
tagger = nemo_nlp.models.duplex_text_normalization.DuplexTaggerModel.from_pretrained(model_name="neural_text_normalization_t5")
```

---

One solution that worked in my case is to re-install an earlier version of transformers, eg. 4.30.2

**Comment by murali1996** [comment]
Not sure if this is a related error, but upon doing all the required installs, when i try to run the following
```
python [NEMO_GIT_FOLDER]/examples/nlp/duplex_text_normalization/duplex_text_normalization_infer.py lang=en mode=tn tagger_pretrained_model=neural_text_normalization_t5 decoder_pretrained_model=neural_text_normalization_t5 inference.interactive=True

```
following error is thrown
```
      electonic_graph = ElectronicFst(deterministic=deterministic).fst
TypeError: __init__() missing 1 required positional argument: 'cardinal'
```
Any thoughts? (I am following this tutorial: https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/neural_text_normalization_t5)

**Comment by tranctan** [comment]
I suppose this is kinda mismatch between the versions of this repo and [NeMo-text-processing](https://github.com/NVIDIA/NeMo-text-processing). Also see a lot of other issues about this bug but still has not resolved.

One quick solution to make this work is inside 
```
[NEMO_GIT_FOLDER]/examples/nlp/duplex_text_normalization//nn_wfst/en/electronic/tokenize_and_classify.py
```
which is where the bug occured,

You should update:
```
from nemo_text_processing.text_normalization.en.taggers.cardinal import CardinalFst
```
declare and place the `cardinal` variable as argument to `ElectronicFst`
```
cardinal = CardinalFst(deterministic=deterministic)
electonic_graph = ElectronicFst(cardinal=cardinal, deterministic=deterministic).fst
```

You also may want to the same for `whitelist` as you may encounter the same issue with this file.

**Disclaimer**: 
- I follow the usage of `ElectronicFst` as in [Nemo Text Processing](https://github.com/NVIDIA/NeMo-text-processing/blob/0.1.6rc0/nemo_text_processing/text_normalization/en/taggers/tokenize_and_classify.py#L126)
- The bug will go away but i don't know if it's the correct logic as the tutorial wanted.

**Comment by ekmb** [comment]
@tranctan, thank you for reporting the issues! Fixed in [PR 7808](https://github.com/NVIDIA/NeMo/pull/7808)
