### ISSUE TITLE
AttributeError: type object 'MegatronGPTPromptLearningModel' has no attribute 'frozen_model'

### ISSUE THREAD

**Issue by csung7** [NVIDIA/NeMo#7544]
from nemo.collections.nlp.models.language_modeling.megatron_gpt_prompt_learning_model import MegatronGPTPromptLearningModel

AttributeError: 'MegatronGPTPromptLearningModel' object has no attribute 'frozen_model'

https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/models/language_modeling/megatron_base_prompt_learning_model.py

```

    def load_frozen_model(self, cfg, trainer):
        pass

```
empty. Any idea?

**Comment by RYangData** [comment]
I am facing this too. Was there a solution?

**Comment by cuichenx** [comment]
Hi, MegatronGPTPromptLearningModel will be deprecated soon. Please check out the new and improved PTuning example [here](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/language_modeling/tuning/megatron_gpt_peft_tuning.py).
More info: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/nemo_megatron/peft/landing_page.html
