### ISSUE TITLE
How to run online inference with Quartzet?

### ISSUE THREAD

**Issue by janvainer** [NVIDIA/NeMo#756]
Is it possible to somehow utilize Quartznet for online ASR?

**Comment by tuanphan09** [comment]
I think this is what you need
https://github.com/NVIDIA/NeMo/blob/master/examples/asr/notebooks/2_Online_ASR_Microphone_Demo.ipynb

Could you send me the KenLM project in ```nemo/scripts/decoders/kenlm```? I can't install the decoders because that project was deleted on github.

Thanks in advance, my email ```tuanptit09@gmail.com```.
