### ISSUE TITLE
replace json with ujson?

### ISSUE THREAD

**Issue by XuesongYang** [NVIDIA/NeMo#7593]
**Is your feature request related to a problem? Please describe.**

Recently facing too many warning message during model training like `NOTE! Installing ujson may make loading annotations faster.`. Went over a little on `ujson` vs `json`, it seems a worth to switch mostly because `ujson` is faster, 

ref: https://github.com/ultrajson/ultrajson

**Comment by RobinDong** [comment]
Sounds good. The only problem is this will be a big task since a lot of code files are importing `json`

**Comment by titu1994** [comment]
json is a python core library. Why should it be necessary to move to a user library - faster or not, it means you have to now install a separate library to do just json manipulation. 
I get it is useful for speed, but realistically being part of the python language is more important for ease of use.

**Comment by XuesongYang** [comment]
Gotcha! thanks! we can close this issue for now.
