### ISSUE TITLE
Export to mlmodel/mlpackage?

### ISSUE THREAD

**Issue by hadiidbouk** [NVIDIA/NeMo#7603]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to export to models like ECAPA-TDNN to an mlmodel/mlpackage so we can add it easily to our iOS applications

Provide a code snippet on how new APIs/changes would be used by others.

**Describe alternatives you've considered**
I already traced the model and used Libtorch, it works well, but I believe having a mlpackage will reduce the size of the model and the performance will be better. Without forgetting how easy the implementation is.

**Comment by titu1994** [comment]
Export of models is a best effort by our team. We only support torchscript and onnx for our models. From there, there are many further export options available - especially onnx to X
