### ISSUE TITLE
[NLP] Rotary embeddings issue with TransformersEngine

### ISSUE THREAD

**Issue by Mirmu** [NVIDIA/NeMo#7628]
**Describe the bug**

We observed a discrepancy between numerical outputs of the NeMo and TE implementations of GPT. It seems to come from rotary embeddings not being passed to the TE module.

**Steps/Code to reproduce bug**

In https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/nlp/modules/common/megatron/transformer.py#L1531 , the `rotary_pos_emb` argument is missing from the forward call to TE module.

**Expected behavior**

Same results with and without TE for GPT arch with rotary embeddings.

**Additional context**

Same issue seems present with checkpointing.

**Comment by hsiehjackson** [comment]
Confirmed from @ericharper. TE is now integrated into Megatron Core, the issue for `AutocastTransformerLayer` is a legacy. If you plan to use TE, please refer to this [repo](https://github.com/NVIDIA/Megatron-LM/tree/main/megatron/core).
