### ISSUE TITLE
Installation from source ./reinstall.sh fails with Failed to build mecab-python3

### ISSUE THREAD

**Issue by RuslanSel** [NVIDIA/NeMo#7646]
Ubuntu 18.04
python 3.11.5
torch 2.11.0
conda
I have installed MeCab via pip3 install mecab-python3.

      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/MeCab
      copying src/MeCab/cli.py -> build/lib.linux-x86_64-cpython-311/MeCab
      copying src/MeCab/__init__.py -> build/lib.linux-x86_64-cpython-311/MeCab
      running build_ext
      error: [Errno 2] No such file or directory: 'mecab-config'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mecab-python3
  Running setup.py clean for mecab-python3                                                                                      
Successfully built nemo-toolkit
Failed to build mecab-python3
ERROR: Could not build wheels for mecab-python3, which is required to install pyproject.toml-based projects

Thanks in advance.

**Comment by titu1994** [comment]
This should be fixed in main and r1.21 branch now. https://github.com/NVIDIA/NeMo/pull/7616

Pr was merged just an hour ago so please retry

**Comment by RuslanSel** [comment]
All done!
Thank you!
