### ISSUE TITLE
megatron-core was not found

### ISSUE THREAD

**Issue by RuslanSel** [NVIDIA/NeMo#7647]
python punctuation_capitalization_train_evaluate.py
gives me
[NeMo W 2023-10-05 22:24:59 nemo_logging:393] megatron-core was not found. Please see the NeMo README for installation instructions: https://github.com/NVIDIA/NeMo#megatron-gpt.
I can't understand how can I install megatron-gpt?
There is an instruction how to install Apex. But I already have Apex.
Or maybe I need to install Transformer Engine?

Thanks in advance.

**Comment by RuslanSel** [comment]
In the nemo/collections/nlp/modules/common/megatron/module.py
we have
from megatron.core import ModelParallelConfig, parallel_state, tensor_parallel
But in the python3.11/site-packages/megatron/core/__init__.py
we have
__all__ = [
    "parallel_state",
    "tensor_parallel",
    "utils",
]
There is no ModelParallelConfig.

**Comment by RuslanSel** [comment]
There is no ModelParallelConfig in megatron 0.2.
There is ModelParallelConfig in megatron 0.5.
I changed requirements_nlp.txt
megatron_core==0.5
But ./reinstall.sh gives
ERROR: Could not find a version that satisfies the requirement megatron-core==0.5; extra == "all" (from nemo-toolkit[all]) (from versions: 0.1.0, 0.2.0)                                                                                                                                
ERROR: No matching distribution found for megatron-core==0.5; extra == "all"

**Comment by aklife97** [comment]
Hi @RuslanSel, what branch/version of NeMo are you using?

In case you're using main, can you please shift to the latest stable release i.e. NeMo r1.20? It looks like there is a mismatch between your NeMo code and the megatron-core version it expects

**Comment by RuslanSel** [comment]
Thank you!
I solved the problem via
git clone https://github.com/NVIDIA/Megatron-LM.git
cd Meg*
pip install -e .
