### ISSUE TITLE
Accessing intermediate activation tensors in QuartzNet

### ISSUE THREAD

**Issue by jeremyholleman** [NVIDIA/NeMo#766]
I have run the example training script for QuartzNet and it worked fine.  I am interested in looking at some of the intermediate activations.  Is there a good way to do that?  I see that I could pass the tensors to neural_factory.infer(), but I can't figure out how to identify the tensors I want or get a list of all of the available tensors.

**Comment by okuchaiev** [comment]
what kind of activations you'd like to see? I'd say outputs of the encoder (e.g. running only encoder) would be interesting.

**Comment by jeremyholleman** [comment]
Running just the encoder would be interesting, but I really want to look at *all* of the intermediate activations.  I want to recreate the outputs manually to make sure I understand what's happening.  I also want to look at the statistics of all those activations to try to understand the representations being learned at each stage.

**Comment by jeremyholleman** [comment]
As a workaround, (pointed to me by ptrblck on the pytorch discussion board), I found that I can use the method here:
https://discuss.pytorch.org/t/how-can-l-load-my-best-model-as-a-feature-extractor-evaluator/17254/6
And register the hook with, for example, this line for the 1D convolution in the first block of a QuartzNet encoder model.
`encoder.encoder[1].mconv[0].conv.register_forward_hook(get_activation('B1(a).mconv.1D'))`

It still seems like it should be possible to find the tensor you could pass to nf.infer() in the tensors=[x,y,z] argument, but I haven't figure out how.

**Comment by dmitrytyrin** [comment]
@okuchaiev, how to perform forward pass on single sample and get encoder output as numpy tensor?

**Comment by jeremyholleman** [comment]
@dmitrytyrin If you look at the example [here](https://nvidia.github.io/NeMo/asr/tutorial.html#introduction), the encoded values are returned explicitly, in this line:
```
encoded, encoded_len = encoder(
    audio_signal=aug_signal, length=processed_signal_len)
```
So if you use that script, and then when you run inference, do something like 
```evaluated_tensors = nf.infer(tensors=[...  encoded_v, ...],  checkpoint_dir=model_path)```
you'll get the encodings back as one element of the `evaluated_tensors` list.  To run just a single recording,  I have just edited the evaluation manifest json file down to one line.  There is probably a cleaner way, and I'd like to hear about it, but that works.
