### ISSUE TITLE
I am wondering is there a way to use NeMo in the application of multi Speaker transcript with Speaker diarisation

### ISSUE THREAD

**Issue by jainal09** [NVIDIA/NeMo#767]
![image](https://user-images.githubusercontent.com/34179361/85634294-b2d7e900-b698-11ea-81a3-98a1a84ccce8.png)
 As shown in the above (taken from image of Nvidia Jarvis website - https://developer.nvidia.com/nvidia-jarvis)
I want to perform speech to text on a wav file and get Multi speaker transcript with Speaker diarisation (who spoke what and when)

But, I am confused is this possible with Nemo and if not what is this website of Nvidia jarvis -https://developer.nvidia.com/nvidia-jarvis referring to in terms of Pre - trained models for Multi speaker transcript?

**Comment by okuchaiev** [comment]
Sorry - we have not open-sourced speaker diarisation models in NeMo yet (certainly on our to-do list). 
Jarvis website is for those interested to sign up for Early Access program for Jarvis

**Comment by jainal09** [comment]
I am working on a product with a necessary requirement of Diarilization.

Our release deadline is set for jan 2021 .
So, can we expect a open sourced nemo Diarilization till that date?

**Comment by jainal09** [comment]
hey @okuchaiev any release dates for speaker diarisation models in NeMo??

**Comment by jainal09** [comment]
hey @okuchaiev  any near plans for open-sourced speaker diarisation models in NeMo?

**Comment by borisgin** [comment]
Work in progress...
