### ISSUE TITLE
different config file

### ISSUE THREAD

**Issue by MordehayM** [NVIDIA/NeMo#7674]
in this line:
https://github.com/NVIDIA/NeMo/blob/c1881f2105a0b65cb9513bcd85456b430ff81bb2/examples/asr/asr_ctc/speech_to_text_ctc_bpe.py#L76

Should it be conformer_ctc_bpe config file instead of citrinet config file?

**Comment by nithinraok** [comment]
Citrinet is one of the models that use ctc loss and bpe encoding, its not a bug. However its a old model and you can replace it with fastconformer config instead.
