### ISSUE TITLE
How to get timestamp pretrained RNNTBPEModel

### ISSUE THREAD

**Issue by sh1man** [NVIDIA/NeMo#7677]
asr_model = nemo_asr.models.EncDecRNNTBPEModel.from_pretrained("nvidia/stt_en_conformer_transducer_large")
words_dict, word_ts_dict = {}, {}
hypotheses = asr_model.transcribe(paths2audio_files=[AUDIO_FILENAME], return_hypotheses=True)

**Comment by titu1994** [comment]
You can follow the second section of this tutorial - the ctc decoding with timestamps. Same flags should mostly work for rnnt as well 

https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Offline_ASR.ipynb

**Comment by sh1man** [comment]
It does not have a logprobs argument

`TypeError: EncDecRNNTModel.transcribe() got an unexpected keyword argument 'logprobs'`

**Comment by sh1man** [comment]
I haven't figured it out, can you be more specific? 
[](https://github.com/NVIDIA/NeMo/discussions/4503)

**Comment by titu1994** [comment]
You don't need the first part - only after Greedy Decoding Time Stamps section in that tutorial

**Comment by sh1man** [comment]
omegaconf.errors.ConfigAttributeError: Key 'preserve_alignments' is not in struct
decoding_cfg.preserve_alignments = True

```
asr_model = nemo_asr.models.EncDecRNNTBPEModel.from_pretrained("nvidia/stt_en_conformer_transducer_large")
decoding_cfg = asr_model.cfg.decoding
decoding_cfg.preserve_alignments = True
decoding_cfg.compute_timestamps = True
asr_model.change_decoding_strategy(decoding_cfg)
```

**Comment by titu1994** [comment]
Ah I forgot to mention that, rnnt transcribe returns a paid (greedy, beam) results when you do transcribe(). [0][0] basically says zeroth sample, of the greedy results. Ofc if bean search is not performed then the second beam list will be None instead.
