### ISSUE TITLE
ASR Language Modeling

### ISSUE THREAD

**Issue by Pri4tam** [NVIDIA/NeMo#7685]
**Describe the bug**
Aim: To Imporve the ASR model Accuracy with the help of LM.
ASR Model Used: Nvidia Nemo: Conformer-CTC-BPE.nemo
As per my understanding steps to implement ASR Language Modeling
1. Create KenLM Library.
2. Install Beam Search Decoder
3. Train N-Gram LM using ASR Model and KenLM Library. #output of step 3 is we have train N-Gram Model which can be used in beam search decoder on top of ASR model. (Decoder used PyCTCdecoder)
4. Evaluate by beam search decoder and N-Gram LM ##To tune parameter of beam search decoder. 
My question is after performing this steps how can I used my trained N-Gram Model with beam search decoder on top of ASR model.

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by titu1994** [comment]
These docs may help - https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/asr_language_modeling.html

**Comment by Pri4tam** [comment]
I have referred this site only but not able to figure out the way for my mention problem.
Can you please be specific on it.

**Comment by vsl9** [comment]
The evaluation script https://github.com/NVIDIA/NeMo/blob/stable/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py includes inference code and can save predictions if `preds_output_folder` argument is given.
