### ISSUE TITLE
Speaker Diarization Task: Clustering stage crashes(Cuda out of memory) for long audio files using Gpu

### ISSUE THREAD

**Issue by ahmedkotb98** [NVIDIA/NeMo#7691]
Speaker Diarization Task: Clustering stage cuda out of memory for long audio files using GPU

**Comment by tango4j** [comment]
Hi. Currently working on the new PR for long-form audio speaker diarization (clustering).
https://github.com/NVIDIA/NeMo/pull/7737

If you need it urgently, take a look at this PR.

**Comment by tango4j** [comment]
@ahmedkotb98 
Now that the long form 

Check out this comment also:
[Parameters for longform clustering](https://github.com/NVIDIA/NeMo/pull/7737#issuecomment-1808724046)
