### ISSUE TITLE
memory not released

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/NeMo#771]
I am doing this notebook: https://github.com/NVIDIA/NeMo/blob/master/examples/nlp/token_classification/PunctuationWithBERT.ipynb.

After completing the training and inference, the memory is still in the gpu. Why it is not released? and is there a way to flush it out?

I found an issue (https://github.com/NVIDIA/NeMo/issues/35) not sure if related.

Appreciate any help.

**Comment by ekmb** [comment]
To release the memory, you'd have to restart the notebook. You can also try punctuation_capitalization(_infer).py scripts, the memory will be released once the scripts are executed.

**Comment by ethem-kinginthenorth** [comment]
ok. thanks
