### ISSUE TITLE
Expose --user-defined-symbols and --control-symbols in scripts/tokenizers/process_asr_text_tokenizer.py

### ISSUE THREAD

**Issue by Jesteinbe** [NVIDIA/NeMo#7711]
`scripts/tokenizers/process_asr_text_tokenizer.py` creates the tokenizer with create_spt_model (`from nemo.collections.common.tokenizers.sentencepiece_tokenizer import create_spt_model`) which already includes those flags. can you just expose those options in the top level script for creating the tokenizer?

**Comment by titu1994** [comment]
Fixed via https://github.com/NVIDIA/NeMo/pull/7790
