### ISSUE TITLE
Need full cmudict  to ipa mappings

### ISSUE THREAD

**Issue by JohnHerry** [NVIDIA/NeMo#7725]
**Is your feature request related to a problem? Please describe.**

 in the NeMo/scripts/tts-dataset_files, there is a cmudict phoneme to ipa phoneme mapping file : cmudict-arpabet_to_ipa_nv22.08.tsv,  but this file contains only 42 cmudict phonemes, this seems not enough to translate all cmudict phonemes to ipa, is there any full version of this mapping file?

**Describe the solution you'd like**

A full mapping file so that I can convert  cmudict phonemes into IPA

**Describe alternatives you've considered**

**Additional context**

**Comment by XuesongYang** [comment]
If I recall correctly, we applied ARPABET to represent English phoneme set. This ARPABET is actually directly borrowed from http://www.speech.cs.cmu.edu/cgi-bin/cmudict, where 39 symbols are used, instead of 42. 

Agreed that 39 or 42 symbols may not fully represent English phonetic systems from linguistics point of view, but they are suffice for practical purposes. For example, it is not necessary to detail `L` as either one of l, ɫ, or lɪ̯.

So to answer your question, `cmudict-arpabet_to_ipa_nv22.08.tsv` is the only version we provide.

**Comment by JohnHerry** [comment]
Get it， Thanks

**Comment by JohnHerry** [comment]
> If I recall correctly, we applied ARPABET to represent English phoneme set. This ARPABET is actually directly borrowed from http://www.speech.cs.cmu.edu/cgi-bin/cmudict, where 39 symbols are used, instead of 42.
> 
> Agreed that 39 or 42 symbols may not fully represent English phonetic systems from linguistics point of view, but they are suffice for practical purposes. For example, it is not necessary to detail `L` as either one of l, ɫ, or lɪ̯.
> 
> So to answer your question, `cmudict-arpabet_to_ipa_nv22.08.tsv` is the only version we provide.

How did NeMo process out of range inputs then?  And I see the 42 symbols map did not give any information about stress, Is the stress symbols in ARPA or IPA not important in English TTS?

**Comment by XuesongYang** [comment]
> Is the stress symbols in ARPA or IPA not important in English TTS?

primary and secondary lexical stresses do matters for English TTS in terms of intonation. It is rare for lexical stresses to alter the pronunciations. To my knowledge, only `/AH/` maps to subtly different sounds according to different stresses, i.e. /AH0/ -> /ə/, /AH1/ or /AH2/ -> /ʌ/.

Both our APRABET dict and IPA dict for English have lexical stress markers, digit suffix in ARPABET and '/" for IPA. You can always consider those markers as part of token set.

- ARPABET dict: https://github.com/NVIDIA/NeMo/blob/main/scripts/tts_dataset_files/cmudict-0.7b_nv22.10  
- IPA dict: https://github.com/NVIDIA/NeMo/blob/main/scripts/tts_dataset_files/ipa_cmudict-0.7b_nv23.01.txt
- ARPABET to IPA map table: https://github.com/NVIDIA/NeMo/blob/main/scripts/tts_dataset_files/cmudict-arpabet_to_ipa_nv22.08.tsv

**Comment by JohnHerry** [comment]
> Are you referring `out of range inputs` to out of vocabulary (OOV) words that doesn't exist in the ARPABET dictionary? If so, English tokenizer/g2p will take care of it. In general, English g2p/tokenizer consider the mixture of graphemes and phonemes as its token set. In other words, the system would tokenize graphemes of OOV words instead of unknown phonemes.

Thanks for help.  What I was talking is about the table of cmudict-arpabet_to_ipa_nv22.08.tsv,  I see in the 42 items there are some ARPA phoneme with stress labels but not all. what‘s more, the ARPA phoneme mapped IPA symbols are not stressed. eg: the following items in this file

`
AH1	ʌ

AH2	ʌ
`

Those two ARPA items with different stress are mapped to the sample IPA, It seems in the mapping that when converting into IPA transcription, the stress tags are ignored.  and I think the primary stress should be tagged as a leading "Superscript Vertical Line", like the tag before the "b" below:


**ˈ**bɑz


and the secondary stress should be tagged as a leading “Subscript Vertical Line” ， like the tag before the "k" below


ˈbæ**ˌ**keɪk

As you mentioned, the stress may affect less  on the phoneme uttering，but this is report that [different stress may result in different meaning ]( https://www.engvid.com/english-resource/35-words-stress-changes-meaning/ )
I am not English speaker and has little language known about English pronunciation, so I want to know, If I use this  ARAP-IPA mapping of the ( cmudict-arpabet_to_ipa_nv22.08.tsv)  to make preprocessing, will the model trained with this IPA transcription effect.
