### ISSUE TITLE
Zarr directory not found for checkpoint_dir

### ISSUE THREAD

**Issue by premmotgi** [NVIDIA/NeMo#7756]
**Describe the bug**

When I run a tuning job with default nvidia callback configuration. I get below error. If checkpoint_callback is disabled then epoch finishes fine. This seems to be an internal issue to me.

Image used: Nemo 28.03

A clear and concise description of what the bug is.Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Traceback (most recent call last):
  File "/opt/NeMo/examples/nlp/language_modeling/tuning/megatron_gpt_sft.py", line 212, in main
    trainer.fit(model)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/training_epoch_loop.py", line 134, in run
    self.on_advance_end()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/training_epoch_loop.py", line 249, in on_advance_end
    self.val_loop.run()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/evaluation_loop.py", line 122, in run
    return self.on_run_end()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/evaluation_loop.py", line 258, in on_run_end
    self._on_evaluation_end()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/evaluation_loop.py", line 303, in _on_evaluation_end
    call._call_callback_hooks(trainer, hook_name, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 194, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 311, in on_validation_end
    self._save_topk_checkpoint(trainer, monitor_candidates)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 360, in _save_topk_checkpoint
    self._save_monitor_checkpoint(trainer, monitor_candidates)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 663, in _save_monitor_checkpoint
    self._update_best_and_save(current, trainer, monitor_candidates)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 714, in _update_best_and_save
    self._save_checkpoint(trainer, filepath)
  File "/opt/NeMo/nemo/utils/callbacks/nemo_model_checkpoint.py", line 272, in _save_checkpoint
    super()._save_checkpoint(trainer, filepath)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 365, in _save_checkpoint
    trainer.save_checkpoint(filepath, self.save_weights_only)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1316, in save_checkpoint
    self._checkpoint_connector.save_checkpoint(filepath, weights_only=weights_only, storage_options=storage_options)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 506, in save_checkpoint
    _checkpoint = self.dump_checkpoint(weights_only)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 491, in dump_checkpoint
    call._call_callbacks_on_save_checkpoint(trainer, checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 221, in _call_callbacks_on_save_checkpoint
    callback.on_save_checkpoint(trainer, trainer.lightning_module, checkpoint)
  File "/opt/NeMo/nemo/utils/callbacks/nemo_model_checkpoint.py", line 181, in on_save_checkpoint
    pl_module.save_to(save_path=app_state.model_restore_path)
  File "/opt/NeMo/nemo/core/classes/modelPT.py", line 385, in save_to
    self._save_restore_connector.save_to(self, str(save_path))  # downstream tasks expect str, not Path
  File "/opt/NeMo/nemo/collections/nlp/parts/nlp_overrides.py", line 489, in save_to
    dist_checkpointing.save(sharded_state_dict=sharded_state_dict, checkpoint_dir=dist_ckpt_dir)
  File "/opt/Megatron-LM/megatron/core/dist_checkpointing/serialization.py", line 174, in save
    sharded_strategy.save(sharded_tensors, checkpoint_dir)
  File "/opt/Megatron-LM/megatron/core/dist_checkpointing/strategies/zarr.py", line 49, in save
    arrays = _create_or_open_zarr_arrays(sharded_tensors, checkpoint_dir)
  File "/opt/Megatron-LM/megatron/core/dist_checkpointing/strategies/zarr.py", line 73, in _create_or_open_zarr_arrays
    arr = zarr.open(checkpoint_dir / ten.key, 'r+', **open_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/zarr/convenience.py", line 130, in open
    raise PathNotFoundError(path)
zarr.errors.PathNotFoundError: nothing found at path ''

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: H100

**Comment by premmotgi** [comment]
@ericharper Is there any way to work around this issue?

**Comment by ericharper** [comment]
Could you share the python command that was used? We need a way to try and reproduce this.

**Comment by premmotgi** [comment]
I am using slurm batch file to submit a multinode job. Here's the python command from that slurm batch file:
`srun -l --container-mounts=/f810-share/prem_sft/results/${SLURM_JOBID}/:/results,/home/pmotgi/:/workspace,/dev/infiniband/:/dev/infiniband,/f810-share/project-helix/datasets/databricks-dolly-15k/:/dataset,/f810-share/project-helix/models/NeMo-models/llama2-NGC-v2.0/:/models --container-image="docker://nvcr.io/ea-bignlp/ga-prtcpnts-dell/nemofw-training-debug:23.08.03-verbose-logging-prints" bash -c "python /opt/NeMo/examples/nlp/language_modeling/tuning/megatron_gpt_sft.py \
trainer.precision=bf16 \
trainer.devices=8 \
trainer.num_nodes=2 \
trainer.val_check_interval=0.5 \
trainer.max_steps=10 \
model.restore_from_path=${MODEL} \
model.micro_batch_size=1 \
model.global_batch_size=128 \
model.tensor_model_parallel_size=${TP_SIZE} \
model.pipeline_model_parallel_size=${PP_SIZE} \
model.megatron_amp_O2=True \
model.sequence_parallel=True \
model.activations_checkpoint_granularity=selective \
model.activations_checkpoint_method=uniform \
model.optim.name=distributed_fused_adam \
model.optim.lr=5e-6 \
model.answer_only_loss=True \
model.data.train_ds.file_names=${TRAIN_DS} \
model.data.validation_ds.file_names=${VALID_DS} \
model.data.test_ds.file_names=${TEST_DS} \
model.data.train_ds.concat_sampling_probabilities=${CONCAT_SAMPLING_PROBS} \
model.data.train_ds.max_seq_length=2048 \
model.data.validation_ds.max_seq_length=2048 \
model.data.train_ds.micro_batch_size=1 \
model.data.train_ds.global_batch_size=128 \
model.data.validation_ds.micro_batch_size=1 \
model.data.validation_ds.global_batch_size=128 \
model.data.test_ds.micro_batch_size=1 \
model.data.test_ds.global_batch_size=256 \
model.data.train_ds.num_workers=0 \
model.data.validation_ds.num_workers=0 \
model.data.test_ds.num_workers=0 \
model.data.validation_ds.metric.name=loss \
model.data.test_ds.metric.name=loss \
exp_manager.exp_dir=/results \
exp_manager.explicit_log_dir=/results \
+exp_manager.seconds_to_sleep=70 \
exp_manager.resume_if_exists=True \
exp_manager.resume_ignore_no_checkpoint=True \
exp_manager.create_checkpoint_callback=True \
exp_manager.checkpoint_callback_params.save_nemo_on_train_end=True"
`

Error seems to be at checkpointing at 50% of epoch based on val_check_interval. If I run the same slurm batch file for single node training job runs fine. Is there any way to disable distributed checkpointing?

**Comment by premmotgi** [comment]
I am using slurm batch file to submit a multinode job. Here's the python command from that slurm batch file:



```
TRAIN_DS="[/dataset/data/training.jsonl]"
VALID_DS="[/dataset/data/validation.jsonl]"
TEST_DS="[/dataset/data/test.jsonl]"
VALID_NAMES="[databricks-dolly-15k]"
CONCAT_SAMPLING_PROBS="[1.0]"
TP_SIZE=2
PP_SIZE=1
MODEL="/models/llama2-7b-bf16-tp1.nemo"

```

```
srun -l --container-mounts=/nfs/project/prem_sft/results/${SLURM_JOBID}/:/results,/home/pmotgi/:/workspace,/dev/infiniband/:/dev/infiniband,/nfs/project/datasets/databricks-dolly-15k/:/dataset,/nfs/project/models/NeMo-models/llama2-NGC-v2.0/:/models --container-image="docker://nvcr.io/ea-bignlp/ga-prtcpnts-dell/nemofw-training-debug:23.08.03-verbose-logging-prints" bash -c "python /opt/NeMo/examples/nlp/language_modeling/tuning/megatron_gpt_sft.py \ 
trainer.precision=bf16 \ 
trainer.devices=8 \
 trainer.num_nodes=2 \ 
 trainer.val_check_interval=0.5 \
  trainer.max_steps=10 \ 
  model.restore_from_path=${MODEL} \
   model.micro_batch_size=1 \ 
   model.global_batch_size=128 \ 
   model.tensor_model_parallel_size=${TP_SIZE} \ 
   model.pipeline_model_parallel_size=${PP_SIZE} \ 
   model.megatron_amp_O2=True \ 
   model.sequence_parallel=True \ 
   model.activations_checkpoint_granularity=selective \ 
   model.activations_checkpoint_method=uniform \ 
   model.optim.name=distributed_fused_adam \ 
   model.optim.lr=5e-6 \ 
   model.answer_only_loss=True \
    model.data.train_ds.file_names=${TRAIN_DS} \ 
    model.data.validation_ds.file_names=${VALID_DS} \ 
    model.data.test_ds.file_names=${TEST_DS} \ model.data.train_ds.concat_sampling_probabilities=${CONCAT_SAMPLING_PROBS} \ 
    model.data.train_ds.max_seq_length=2048 \ 
    model.data.validation_ds.max_seq_length=2048 \ 
    model.data.train_ds.micro_batch_size=1 \ 
    model.data.train_ds.global_batch_size=128 \ 
    model.data.validation_ds.micro_batch_size=1 \
     model.data.validation_ds.global_batch_size=128 \ 
     model.data.test_ds.micro_batch_size=1 \ 
     model.data.test_ds.global_batch_size=256 \
      model.data.train_ds.num_workers=0 \ 
      model.data.validation_ds.num_workers=0 \
       model.data.test_ds.num_workers=0 \ 
       model.data.validation_ds.metric.name=loss \ 
       model.data.test_ds.metric.name=loss \ 
       exp_manager.exp_dir=/results \ 
       exp_manager.explicit_log_dir=/results \ 
       exp_manager.resume_if_exists=True \
        exp_manager.resume_ignore_no_checkpoint=True \
         exp_manager.create_checkpoint_callback=True \ exp_manager.checkpoint_callback_params.save_nemo_on_train_end=True"
```
         

Error seems to be at checkpointing at 50% of epoch based on val_check_interval. If I run the same slurm batch file for single node training job runs fine. Is there any way to disable distributed checkpointing?

**Comment by premmotgi** [comment]
@ericharper Disabling the cache on NFS storage fixed it. Thanks.

**Comment by akaanirban** [comment]
@premmotgi I am facing a similar problem. Can you please elaborate on how you solved it and what you mean by disabling caching on NFS storage? Much appreciated thanks !

**Comment by itzsimpl** [comment]
@akaanirban can you try running with `exp_manager.checkpoint_callback_params.save_best_model=false`?

**Comment by premmotgi** [comment]
> @premmotgi I am facing a similar problem. Can you please elaborate on how you solved it and what you mean by disabling caching on NFS storage? Much appreciated thanks !

There is a config on NFS storage called **actimeo**, that needs to be set 0. From what I heard Nvidia doesnot recommend NFS for large model training usecases. They recommend to use Luster which is a parallel file system for HPC systems. Setting actimeo to zero makes sure that there's no downtime in cacheing and distributed checkpointing can happen real time. Thanks.

**Comment by itzsimpl** [comment]
It will save a nemo model, but it will not make sure it is the best one, i.e. it will not reload the best checkpoint and then save a nemo file. If that solves your training, there are other scripts with which you can convert any checkpoint to nemo. 

I mentioned just to check if it is perhaps related to https://github.com/NVIDIA/NeMo/issues/7938.

**Comment by premmotgi** [comment]
> It will save a nemo model, but it will not make sure it is the best one, i.e. it will not reload the best checkpoint and then save a nemo file. If that solves your training, there are other scripts with which you can convert any checkpoint to nemo.
> 
> I mentioned just to check if it is perhaps related to #7938.

Gothu I agree.

**Comment by akaanirban** [comment]
Thank you @premmotgi , we ended up landing to similar solution in kubernetes, we also set the `noac` flag and the `lookupcache=None` flag in the mount options so that all the workers see the checkpointing directory without waiting, albeit with little performance penalty. There also seem to be a open PR in NeMo at the moment that aims to solve this https://github.com/NVIDIA/NeMo/pull/8153. Although I must admit I have not tried this.

**Comment by premmotgi** [comment]
> Thank you @premmotgi , we ended up landing to similar solution in kubernetes, we also set the `noac` flag and the `lookupcache=None` flag in the mount options so that all the workers see the checkpointing directory without waiting, albeit with little performance penalty. There also seem to be a open PR in NeMo at the moment that aims to solve this #8153. Although I must admit I have not tried this.

With Kubernetes I had to configure actimeo=0 in PV/PVC manifest files. Also, the PR is something that is fix on this bug, but it didn't make it to main branch.

**Comment by premmotgi** [comment]
> Thank you @premmotgi , we ended up landing to similar solution in kubernetes, we also set the `noac` flag and the `lookupcache=None` flag in the mount options so that all the workers see the checkpointing directory without waiting, albeit with little performance penalty. There also seem to be a open PR in NeMo at the moment that aims to solve this #8153. Although I must admit I have not tried this.

Here's the design guide that we have written for multinode model customization with Nvidia that might be of help: https://infohub.delltechnologies.com/t/design-guide-generative-ai-in-the-enterprise-model-customization/
