### ISSUE TITLE
Llama 2 70b convert & finetuning

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/NeMo#7766]
**Describe the bug**

I am following the tutorial: https://docs.nvidia.com/nemo-framework/user-guide/latest/playbooks/llama2peft.html
to finetuning llama 2 on custom dataset.

when convert the llama 2 70b-hf to .nemo with the script
```
python3 ./scripts/nlp_language_modeling/convert_hf_llama_to_nemo.py --in-file=$1 --out-file=$2
```

the output of conversion is 
![image](https://github.com/NVIDIA/NeMo/assets/22444830/f22fc475-36c4-400a-b372-c06f0da408e5)

but there exist no file named "llama2-70b.nemo" , only outputs a ``model_weights'':
![image](https://github.com/NVIDIA/NeMo/assets/22444830/ccf96378-900a-4065-9dab-dccf705e192b)

the  ``model_weights'' cannot feed to the training script:
![image](https://github.com/NVIDIA/NeMo/assets/22444830/93923895-9b1b-4fcf-87e5-ca00dfc99043)

 
How can we successfully run the tutorial ?

 
**Environment details**

- OS version: Ubuntu 18.04
- PyTorch version: '2.2.0.dev20231013+cu118'
- Python version: 3.8
- transformers: 4.33.0
- transformer_engine:  stable branch
- CUDA : 11.8
- CUDNN: 8.6

**Additional context**
GPU:  8xA100

**Comment by HuiyingLi** [comment]
The expected output should be a single llama2-70b.nemo file, and if untar the llama2-70b.nemo file it should contain a file model_congif.yaml  and a directory model_weights/ , which looks like the model weights shown in the image. Seems like the model_weights/ dir is generated but not tar-ed up with the config file. The line I saw suspicious is "model_weights already exists, skipping saving"

**Comment by JosephChenHub** [comment]
> The expected output should be a single llama2-70b.nemo file, and if untar the llama2-70b.nemo file it should contain a file model_congif.yaml and a directory model_weights/ , which looks like the model weights shown in the image. Seems like the model_weights/ dir is generated but not tar-ed up with the config file. The line I saw suspicious is "model_weights already exists, skipping saving"

yes, there is no "model_config.yaml"
