### ISSUE TITLE
How to achieve real-time dialogue with AI ?

### ISSUE THREAD

**Issue by monkeycc** [NVIDIA/NeMo#7776]
ASR - LLM - TTS
ASR+VAD ? 
How to achieve real-time dialogue with AI ?

ASR real-time detection, human speech, converted into text
Human beings stop talking,
Text submission to LLM
LLM sends text to TTS

**Comment by titu1994** [comment]
If by real time you mean streaming pipeline of ASR LLM and TTS, then NeMo is not the correct toolkit for it. We are mostly focused on the offline aspect of inference, with some models being developed for streaming. But we don't have true streaming pipelines on NeMo. 

You should explore Nvidia Riva for streaming ASR and TTS, and TRT LLM for streaming llm inference.

**Comment by monkeycc** [comment]
Thank you for your help and advice

**Comment by AI-General** [comment]
@titu1994 

Thank you for your advice.
I'd like to ask one more. NVIDIA Riva is open source?
And What is input and output of NeMo's streaming STT

Thank you
