### ISSUE TITLE
ASR in real time?

### ISSUE THREAD

**Issue by TonSotin** [NVIDIA/NeMo#7799]
Is it possible to use one of [ASR NeMo models](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/models.html) in real time speech recognition?

**Comment by nithinraok** [comment]
Yes, look at [Online ASR notebook](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Online_ASR_Microphone_Demo.ipynb) for performing ASR on audio coming through microphone. If you are looking for even faster inference you may refer to [RIVA](https://developer.nvidia.com/riva)
