### ISSUE TITLE
ASR Tutorial Notebook: RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).`

### ISSUE THREAD

**Issue by siddiqaa** [NVIDIA/NeMo#78]
Getting following error when running "examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb" on Google Colab with GPU runtime

"RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).`"

2019-10-27 04:10:44,396 - WARNING - Data Layer does not have any weights to return. This get_weights call returns None.
2019-10-27 04:10:44,408 - INFO - Restoring checkpoint from folder ./an4_checkpoints ...
Selected optimization level O0:  Pure FP32 training.

Defaults for this optimization level are:
enabled                : True
opt_level              : O0
cast_model_type        : torch.float32
patch_torch_functions  : False
keep_batchnorm_fp32    : None
master_weights         : False
loss_scale             : 1.0
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O0
cast_model_type        : torch.float32
patch_torch_functions  : False
keep_batchnorm_fp32    : None
master_weights         : False
loss_scale             : 1.0
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",)
Starting .....
No file matches  in ./an4_checkpoints
Checkpoint folder ./an4_checkpoints present but did not restore
Starting epoch 0

RuntimeError                              Traceback (most recent call last)
<ipython-input-15-0947afe841a3> in <module>()
      4     optimizer='novograd',
      5     optimization_params={
----> 6         "num_epochs": 150, "lr": 0.01, "weight_decay": 1e-4
      7     })
      8 

4 frames
/usr/local/lib/python3.6/dist-packages/nemo/core/neural_factory.py in train(self, tensors_to_optimize, optimizer, optimization_params, callbacks, lr_policy, batches_per_step, stop_on_nan_loss, reset)
    516             lr_policy=lr_policy,
    517             batches_per_step=batches_per_step,
--> 518             stop_on_nan_loss=stop_on_nan_loss)
    519 
    520     def eval(self,

/usr/local/lib/python3.6/dist-packages/nemo/backends/pytorch/actions.py in train(self, tensors_to_optimize, optimizer, optimization_params, callbacks, lr_policy, batches_per_step, stop_on_nan_loss)
   1191                             continue
   1192                         scaled_loss.backward(
-> 1193                             bps_scale.to(scaled_loss.get_device()))
   1194                 else:
   1195                     final_loss.backward(

/usr/local/lib/python3.6/dist-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    148                 products. Defaults to ``False``.
    149         """
--> 150         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    151 
    152     def register_hook(self, hook):

/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     91         grad_tensors = list(grad_tensors)
     92 
---> 93     grad_tensors = _make_grads(tensors, grad_tensors)
     94     if retain_graph is None:
     95         retain_graph = create_graph

/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in _make_grads(outputs, grads)
     27                                    + str(grad.shape) + " and output["
     28                                    + str(outputs.index(out)) + "] has a shape of "
---> 29                                    + str(out.shape) + ".")
     30             new_grads.append(grad)
     31         elif grad is None:

RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).`

**Comment by borisgin** [comment]
which pytorch version do you use?

**Comment by siddiqaa** [comment]
1.3.0+cu100

**Comment by siddiqaa** [comment]
The error disappears if I add the following lines to the top of the notebook.

!pip uninstall -y torch
!pip install torch==1.2.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by okuchaiev** [comment]
yes, we currently require torch 1.12. We plan on going to 1.13 for 0.9 version. Closing this.
