### ISSUE TITLE
ConfidenceMethodConfig DEPRECATED compatibility problem between r1.21.0 and r1.20.0

### ISSUE THREAD

**Issue by FredSRichardson** [NVIDIA/NeMo#7805]
**Describe the bug**

Loading models trained with Nemo version `r1.21.0` using Nemo `r1.20.0` codebase fails with the following error:
```
[NeMo E 2023-10-23 16:21:42 common:506] Model instantiation failed!
    Target class:       nemo.collections.asr.models.hybrid_rnnt_ctc_bpe_models.EncDecHybridRNNTCTCBPEModel
    Error(s):   'str' object has no attribute 'temperature'
```
This is due to changes in `nemo/collections/asr/parts/utils/asr_confidence_utils.py` - the newer [version ](https://github.com/NVIDIA/NeMo/blob/c0022aec9c8fedd59458935f0378a775b28d0444/nemo/collections/asr/parts/utils/asr_confidence_utils.py#L93-L120) supports the `str` value `DEPRECATED`: 

**Steps/Code to reproduce bug**

The bug occurs when using Nemo `r1.21.0` and finetuning the model [here](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_multilingual_fastconformer_hybrid_large_pc) using the script `examples/asr/speech_to_text_finetune.py` and the config file `examples/asr/conf/speech_to_text_finetune.yaml` with minor modifications.

**Expected behavior**

The `r1.20.0` codebase should be able to load models trained with `r1.21.0` unless the models differ in ways that simply can't be supported by the old code base.  In the later situation, a meaningful error message should indicate that code base is too old for the model.

**Environment overview (please complete the following information)**

 - Environment location: Bare Metal
 - Method of NeMo install: `python -m pip install 'git+https://github.com/NVIDIA/NeMo.git@r1.21.0#egg=nemo_toolkit[all]'`

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 20.04
- PyTorch version: pytorch-lightning 2.0.7
- Python version: Conda Python 3.10.13

**Additional context**

Example: GPU model: NVIDIA A100

**Comment by titu1994** [comment]
We provide backward compatibility, not forward. A model trained with 1.21 would be compatible only with models 1.21+ (this is defined by the nemo_version in the models config file inside the NeMo file). 

Code models would work, with some manual effort. You can modify the yaml config with omegaconf and then call restore from, should work.
