### ISSUE TITLE
Does the project support QLora

### ISSUE THREAD

**Issue by 2033329616** [NVIDIA/NeMo#7850]
**Is your feature request related to a problem? Please describe.**

I have limit gpu resources， so I want to use qlora with model paralelism for LLM model.

**Describe the solution you'd like**

Using qlora and model paralelism or pipeline parallelism together。

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by thincal** [comment]
@minitu Is there any plan for QloRA support ? thanks.
