### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by sriks8** [NVIDIA/NeMo#7855]
Traceback (most recent call last):
  File "/home/user/app/app.py", line 3, in <module>
    gr.Interface.load("models/nvidia/stt_en_fastconformer_transducer_xlarge").launch()
AttributeError: 'Dependency' object has no attribute 'launch'

**Comment by nithinraok** [comment]
Its an error from gradio not nemo. Not sure what you are trying to do.

**Comment by sriks8** [comment]
Thanks for looking at this. 

I tried to deploy the model (https://huggingface.co/nvidia/stt_en_fastconformer_transducer_xlarge) as an gardio app in click deploy option on the right) but it is failing. It errors out during the build phase.

**Comment by nithinraok** [comment]
Its an error from launch() not during load. You might need to upgrade or downgrade gradio version

**Comment by nithinraok** [comment]
Looks like you need to pass `model` not `models` https://www.gradio.app/guides/advanced-interface-features

**Comment by nithinraok** [comment]
I dont see it working for other models as well. Can you provide an working example for other models. 
I tried `model/segmind/SSD-1B`

**Comment by sriks8** [comment]
You are right! I tried a few other models and they too failed with the same error. I guess it has something do with Spaces in HF. I will ask from help there.

Thanks for your help!
