### ISSUE TITLE
Continue training from 'ckpt' file

### ISSUE THREAD

**Issue by TonSotin** [NVIDIA/NeMo#7869]
Is it possible somehow to continue training from checkpoint that made by pytorch_lightning? I have been training ASR model and load pretrained model. I want to continue training from exact position when server shut down. Do I need load from model.nemo or is there more gentle way to do this?

**Comment by nithinraok** [comment]
if you are using `https://github.com/NVIDIA/NeMo/blob/main/examples/asr/speech_to_text_finetune.py` to finetune then we currently don;t support loading from ckpt file. 
However while training you can always save nemo file by toggling https://github.com/NVIDIA/NeMo/blob/d49b73cb495dfd17554b01cf1b0f6f8f1bbbbc7c/nemo/utils/exp_manager.py#L105 through config. 

Make sure you toggle and use these values accordingly: https://github.com/NVIDIA/NeMo/blob/d49b73cb495dfd17554b01cf1b0f6f8f1bbbbc7c/nemo/utils/exp_manager.py#L135..L143

**Comment by mukherjeesougata** [comment]
I am using https://github.com/Open-Speech-EkStep/vakyansh-nemo-experimentation/blob/main/src/finetuning/speech_to_text_ctc_bpe.py#L104 to finetune. I have trained the pre-trained model up to 30 epochs. So, can I continue training from the 'ckpt' generated at the 30th epoch?

**Comment by TonSotin** [comment]
@mukherjeesougata I did something like that:
```
    trainer = ptl.Trainer(
        #callbacks=[early_stop_callback],
        devices=-1 if device == torch.device('cuda') else 1,
        accelerator = "gpu",
        max_epochs=settings.num_epochs,
        accumulate_grad_batches=settings.accumulate_grad_batches,
        enable_checkpointing=True,
        logger=True,
        log_every_n_steps=1,
        check_val_every_n_epoch=1,
        resume_from_checkpoint=ckpt_path
    )

    trainer.fit(model)
```

**Comment by nithinraok** [comment]
@mukherjeesougata 
> I am using https://github.com/Open-Speech-EkStep/vakyansh-nemo-experimentation/blob/main/src/finetuning/speech_to_text_ctc_bpe.py#L104 to finetune. I have trained the pre-trained model up to 30 epochs. So, can I continue training from the 'ckpt' generated at the 30th epoch?

Yes.
