### ISSUE TITLE
Issue faced in Nemo Model Inference using Farward collection

### ISSUE THREAD

**Issue by Pri4tam** [NVIDIA/NeMo#7870]
**Describe the bug**

The farward nemo collection of Nemo ASR model requires following parameters.

-  input_signal – Tensor that represents a batch of raw audio signals, of shape [B, T]. T here represents timesteps, with 1 second of audio represented as self.sample_rate number of floating point values.

- input_signal_length – Vector of length B, that contains the individual lengths of the audio sequences.

**Steps/Code to reproduce bug**
Load the model
hi_nemo_asr=nemo_asr.models.EncDecCTCModelBPE.restore_from(en_model_path).cpu()
waveform, sample_rate = torchaudio.load(speech_file[0])
input_signal_length=input_signal.shape[1]
log_prob,_,_=hi_nemo_asr.forward(input_signal=waveform,input_signal_length=waveform.shape[1])

This gives the following error
IndexError: tuple index out of range

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
-Os =Linux
- PyTorch version =2.1.0
- Python version=3.8.10

**Comment by nithinraok** [comment]
Your reproducible steps are unclear as you are using some variables which are out of scope from what described. 

However for forward, signal should be BxT and signal_length should be B size **tensors**. 

 Waveform.shape[idx] would return int but not torch tensor. 

Can you change it to `torch.tensor([waveform.shape[1]])` and retry?

**Comment by jbalam-nv** [comment]
@Pri4tam Assuming tha tthe above uggestions solved your bug.. Please reopen if it is unresolved.
