### ISSUE TITLE
swig_decoders dependency

### ISSUE THREAD

**Issue by vsokolovskii** [NVIDIA/NeMo#7874]
**Describe the bug**

Cannot run the n-gram beam search script.

**Steps/Code to reproduce bug**

Run the `./install_beamsearch_decoders.sh`

 ``` import swig_decoders
ModuleNotFoundError: No module named 'swig_decoders'
```

Ubuntu 22.04.3

**Comment by nithinraok** [comment]
It should have been installed as per [line](https://github.com/NVIDIA/NeMo/blob/77d1386174930239fb619a7d4660a88f2061a5b3/scripts/installers/setup_os2s_decoders.py#L138C18-L138C30).


Was it unsuccessful during installation? Can you check your logs and post the error here?

**Comment by mehadi92** [comment]
@nithinraok When I run `./install_beamsearch_decoders.sh` I'm getting this for `NeMo 1.23.1`

```
writing manifest file 'ctc_decoders.egg-info/SOURCES.txt'
file swig_decoders.py (for module swig_decoders) not found
reading manifest file 'ctc_decoders.egg-info/SOURCES.txt'
writing manifest file 'ctc_decoders.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file swig_decoders.py (for module swig_decoders) not found
creating build
creating build/lib.linux-x86_64-cpython-310
copying ctc_decoders.py -> build/lib.linux-x86_64-cpython-310
file swig_decoders.py (for module swig_decoders) not found
```

**Comment by nithinraok** [comment]
It should be installed as part of OpenSeqtoSeq decoder installers setup:https://github.com/NVIDIA/OpenSeq2Seq/blob/master/decoders/setup.py 

Relevant issue: https://github.com/PaddlePaddle/models/issues/315 

@karpov-nick do you know if users need to install it separately?

**Comment by mehadi92** [comment]
@nithinraok @karpov-nick 

I did not face `file swig_decoders.py (for module swig_decoders) not found` when I use image `docker pull nvcr.io/nvidia/nemo:24.01.speech` But I faced `Segmentation fault issue` please check details in [10557](https://github.com/NVIDIA/NeMo/discussions/10557)

**Comment by mehadi92** [comment]
Hi @nithinraok Any update regarding this?
