### ISSUE TITLE
How to get the data_process code in NeMo doc for common crawl?

### ISSUE THREAD

**Issue by SefaZeng** [NVIDIA/NeMo#7914]
**Is your feature request related to a problem? Please describe.**

I read the doc for NeMO about data processing [here,](https://docs.nvidia.com/nemo-framework/user-guide/latest/modelguide/pretrainingdatasets/textcleaningandlanguageseparation.html) and I want to use these scripts for data preprocessing. But I can't find a way to get them.

**Describe the solution you'd like**

A website or a github URL to download all these scripts.

**Comment by nithinraok** [comment]
@SefaZeng there is a issue with links, its not open sourced through NeMo. 
Currently you can request for access to NeMo framework at https://developer.nvidia.com/nemo-framework and run scripts

**Comment by ericharper** [comment]
@SefaZeng closing this issue, feel free to reopen if you are unable to run the scripts after downloading the nemo-framework container.

**Comment by SefaZeng** [comment]
> @SefaZeng there is a issue with links, its not open sourced through NeMo. Currently you can request for access to NeMo framework at https://developer.nvidia.com/nemo-framework and run scripts

Thank you for your reply. Could you please tell what is the difference between NeMo and NeMo-Framework?

**Comment by nithinraok** [comment]
(As of current)
[NeMo](https://nvidia.github.io/NeMo/) is open source conversational toolkit for training ASR, TTS, NLP and Speaker Diarization models. 
[NeMo framework](https://developer.nvidia.com/nemo-framework) is a open access container based framework for building, customizing and deploying LLM/multi-modal models.
