### ISSUE TITLE
Language model use on Windows!

### ISSUE THREAD

**Issue by jainal09** [NVIDIA/NeMo#792]
Hi, 
I tried a 100 times installing and compiling open fst and kenlm and tried PaddlePaddle/DeepSpeech decoder package! But it failed everytime!
Is there a way I can directly use the pretrained Nvidia Nemo lm in beamsearch without compiling the PaddlePaddle/DeepSpeech decoder ?

**Comment by tuanphan09** [comment]
I have the same problem. It's a bug in DeepSpeech KenLM setup.sh, but they fixed it already. 
https://github.com/PaddlePaddle/DeepSpeech/commit/c4a8f0b455f09266d8559a1525daa7c1eaacc5ac

It seems Nemo is late behind. You coud do it yourself or wait for update version.

**Comment by jainal09** [comment]
Are you successfull in installing on windows?
Because i had already solved that kenlm repository link issue myself but getting errors during python setup.py installation! @tuanphan09

**Comment by tuanphan09** [comment]
I don't use Window, but I ran successfully on Ubuntu. It required sudo permission. 
I don't know if that is the solution for you.
