### ISSUE TITLE
How to remove Punctuation and Capitalization from appearing in a P&C ASR model's output?

### ISSUE THREAD

**Issue by abarcovschi** [NVIDIA/NeMo#7936]
I am running `transcribe_speech.py` on the [STT En FastConformer Hybrid Transducer-CTC Large P&C](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_fastconformer_hybrid_large_pc) model, but I do not need the P&C feature. Is there a flag I can give to the script to stop the model from generating those tokens, or do I have to filter out the tokens as a postprocessing step myself?

**Comment by KunalDhawan** [comment]
Hi @abarcovschi, we don't support P&C stripping currently but would be adding this feature very soon! The easiest way would be to filter-out/ convert (capitalization) the tokens in post-processing. We would soon be adding text post-processors for ASR, initial implementation (not tested/merged) is available here - [TextPostProcessor](https://github.com/NVIDIA/NeMo/blob/asr_normalize/nemo/collections/asr/parts/postprocessing/asr_text_postprocessor.py) class, [language specific normalizations](https://github.com/NVIDIA/NeMo/tree/asr_normalize/nemo/collections/asr/parts/postprocessing/language_normalizations).
