### ISSUE TITLE
How to apply early stopping criterion while finetuning conformer?

### ISSUE THREAD

**Issue by mukherjeesougata** [NVIDIA/NeMo#7937]
I am trying out conformer-ctc and conformer-transducer finetuning with 5hrs of data using https://storage.googleapis.com/vakyansh-open-models/pretrained_models/vakyansh-conformer-ssl/ssl_conformer_large_e178.nemo pretrained model . I have seen that during training after certain number of epochs the wer is increasing during validation. So, I want to apply early stopping criterion for that. Can anybody kindly please help me out how to do that?

**Comment by mukherjeesougata** [comment]
@okuchaiev A gentle reminder for the same

**Comment by mukherjeesougata** [comment]
@titu1994 can you kindly please answer this

**Comment by KunalDhawan** [comment]
Hi @mukherjeesougata, we do provide support for early stopping based on [PTL's EarlyStopping callback](https://lightning.ai/docs/pytorch/stable/common/early_stopping.html). The config parameters **create_checkpoint_callback** and **checkpoint_callback_params** in [ExpManager](https://github.com/NVIDIA/NeMo/blob/main/nemo/utils/exp_manager.py) might be of interest to you - https://github.com/NVIDIA/NeMo/blob/main/nemo/utils/exp_manager.py#L156-L157
