### ISSUE TITLE
[ASR] Beam Search Decoding How to Get Beam of Tokens as Output

### ISSUE THREAD

**Issue by abarcovschi** [NVIDIA/NeMo#7954]
I am using a Conformer-Transducer model and using the `transcribe_speech.py` script for transcript generation.
I am looking to get a time-aligned word-level transcript output, but instead of just the best hypothesis, I want to get N best tokens for each token location, i.e. for each word location, I want the N best predicted words and the time for that location (beam size = N).

For example, with a beam size of 2:

Spoken text: "I can see clearly"

What I have now:
"timestamps_word": [{"word": "I", "start_offset": 16, "end_offset": 20}, {"word": "can", "start_offset": 20, "end_offset": 159}, {"word": "see", "start_offset": 159, "end_offset": 164}, {"word": "clearly", "start_offset": 164, "end_offset": 326}]

Theoretically what I am looking for: "timestamps_word":
[{"words": ["I", "eye"], "start_offset": 16, "end_offset": 20}, {"words": ["can", "cam"], "start_offset": 20, "end_offset": 159}, {"words": ["see", "sea"], "start_offset": 159, "end_offset": 164}, {"words": ["clearly", "freely"], "start_offset": 164, "end_offset": 326}]

My current decoder-specific arguments to the script are as follows:
```decoder_type='rnnt' compute_timestamps=True rnnt_decoding.strategy='beam' rnnt_decoding.beam.beam_size=3 rnnt_decoding.preserve_alignments=True rnnt_decoding.beam.return_best_hypothesis=False```

Is what I am looking for possible?

**Comment by titu1994** [comment]
I don't believe we've implemented beam search for transducer plus greedy word timestamp extraction.

**Comment by abarcovschi** [comment]
Would this be possible using CTC decoding, if I used a Conformer-CTC model instead?

**Comment by abarcovschi** [comment]
@titu1994 does this PR not give the results that I am looking for? Or does the 'preserve_alignments' part refer to something else? https://github.com/NVIDIA/NeMo/pull/5925

**Comment by titu1994** [comment]
Alignment extraction is one required step of greedy word timestamp collection, since that alignment information is used to build the consecutive chunks of sequences that correspond to tokens. 

However while alignment extraction may be implemented for all models, word timestamp calculation is implemented only for greedy decoding as far as I remember. You could implement it yourself with modifying the logic in AbstractRNNTDecoding or extracting the alignments and manually building the time stamp list

**Comment by abarcovschi** [comment]
So could I extract the alignments for beam search decoding and then building the timestamp list for each N full hypothesis (beam size = N)? Would this mean that with beam search decoding I could only extract N full hypotheses, or could I extract N words per word location and then build the time stamp list for each word location?

**Comment by abarcovschi** [comment]
Ah sorry nevermind, I had a brief lapse of understanding. 

As I understand, transcriptions[0] contains a list of just the **best** Hypothesis per audio file, and transcriptions[1] contains a list per each audio file, where the lists contain **all** the Hypothesis objects returned by beam search decoding for that audio file. Also creating the timestamp information can be done by following https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/asr/Offline_ASR.ipynb#scrollTo=_5hfsiDGsM19
All that's needed is to write a custom function to write the results to separate files per hypothesis.
