### ISSUE TITLE
The process_asr_text_tokenizer file excludes an argument.

### ISSUE THREAD

**Issue by cinjon** [NVIDIA/NeMo#7996]
**Describe the bug**

There is no `spe_byte_fallback` argument in process_asr_text_tokenizer.py

**Steps/Code to reproduce bug**

Just run the process_asr_text_tokenizer with any args, e.g.:
`python ./scripts/tokenizers/process_asr_text_tokenizer.py --manifest=/path/to/manifest --vocab_size=1024 --tokenizer=spe --data_root=/path/to/dataroot --spe_type=unigram

**Expected behavior**

The expected behavior is that this works, but the error thrown is 
`AttributeError: 'Namespace' object has no attribute 'spe_byte_fallback'`.
This makes sense because this commit - https://github.com/NVIDIA/NeMo/commit/1d4d3975e339df819b97d29ceafdd98f37b34906 - added three of the four required args for the argparse, excluding the `spe_byte_fallback` one.

@titu1994 
```[tasklist]
### Tasks
```

**Comment by nithinraok** [comment]
It has fixed, please re open if you face additional issues. 
https://github.com/NVIDIA/NeMo/blob/c67243521b048e7ce1446a0d45a0b6e262528e73/scripts/tokenizers/process_asr_text_tokenizer.py#L162
