### ISSUE TITLE
Finetuning 

### ISSUE THREAD

**Issue by Hid-Gh** [NVIDIA/NeMo#8023]
How is it possible to finetune the citrinet model? On nvidias documentation I saw something similar to TAO toolkit but never saw any example on it. On the other hand I saw the japanese finetuning process. And for me I’m spotting for a wer of less 5%. I got a deadline in less than 3 weeks , can someone help ?!

**Comment by nithinraok** [comment]
Hi, apologies for late response. 

Have you looked at these sections on finetuning: https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/configs.html#fine-tuning-configurations and https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/asr/examples/kinyarwanda_asr.html#training-from-scratch-and-finetuning 

Let us know if you have issues using the scripts.
