### ISSUE TITLE
Nemo Documentation User Guide doesn't work 

### ISSUE THREAD

**Issue by NoorAlaaSaad** [NVIDIA/NeMo#8043]
**Describe the bug**

Nemo Documentation User Guide doesn't work 

Link:
https://docs.nvidia.com/deeplearning/nemo/user-guide/index.html

Output Message:
An error occurred while processing your request.
Reference #30.3ff01202.1702902642.32d3d058

**Comment by titu1994** [comment]
Thanks for letting us know, we're looking into it.

**Comment by titu1994** [comment]
This should be fixee now. Thanks for letting us know !
