### ISSUE TITLE
Broken links in main README (leading to NVIDIA docs)

### ISSUE THREAD

**Issue by ptannor** [NVIDIA/NeMo#8050]
Links in README lead to docs on NVIDIA website, but at least some of them seem to be broken. I checked the NLP section, specifically these two:

NLP
[NeMo Megatron pre-training of Large Language Models](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/nlp/nemo_megatron/intro.html)
[Neural Machine Translation (NMT)](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/machine_translation/machine_translation.html)

and the links send me to a page with this error:

An error occurred while processing your request.
Reference #30.4cf01202.1702990306.31b50b8c

Worth fixing the links

**Comment by titu1994** [comment]
The docs should be up and running again, I'll inform the team about the broken links.

**Comment by nithinraok** [comment]
Links are updated, pls let us know if you find any issues.
