### ISSUE TITLE
official training logs with loss/wer

### ISSUE THREAD

**Issue by orena1** [NVIDIA/NeMo#8089]
**Is your feature request related to a problem? - Describe the solution you'd like**

Firstly, I want to express my gratitude for the comprehensive documentation provided, which I find immensely valuable.

When initiating training for a new model, distinguishing between a potential bug and normal behavior during the training process can be quite challenging. Having access to continues logging metrics loss/WER (Word Error Rate) from your training sessions would significantly enhance our debugging capabilities and the security of our training procedures. Would it be feasible for you to release or publish these logs?

**Additional context**
Something of that kind would be amaizng:
https://wandb.ai/patrickvonplaten/wav2vec2-pretrained-demo/reports/Wav2Vec2-PreTraining-Demo-Run--VmlldzoxMDk3MjAw?accessToken=oa05s1y57lizo2ocxy3k01g6db1u4pt8m6ur2n8nl4cb0ug02ms2cw313kb8ruch
But even just screenshot of tensorboard will be great

**Comment by titu1994** [comment]
Probably won't be possible to share wandb

**Comment by orena1** [comment]
thanks @titu1994 , wandb would be a best case scenario, but even a tensorboard screenshot will be amazingly valuable
