### ISSUE TITLE
Read files BytesIO format

### ISSUE THREAD

**Issue by Andrey-Nikitin** [NVIDIA/NeMo#8098]
**Is your feature request related to a problem? Please describe.**

I have audio files in BytesIO, how can I feed them into transcribe if this function expects file_path?

**Describe the solution you'd like**

The transcribe method expects not only file_path but also BytesIO

**Describe alternatives you've considered**

I made a custom EncDecCTCModelBPE and read librosa files, but the accuracy of the transcription is reduced in contrast to the basic EncDecCTCModelBPE.

**Additional context**

-

**Comment by titu1994** [comment]
We currently do not support any input other than file path. However, subclassing and overriding the transcribe function should be fine, usually does not cause wer degradation.

**Comment by Andrey-Nikitin** [comment]
> We currently do not support any input other than file path. However, subclassing and overriding the transcribe function should be fine, usually does not cause wer degradation.
How Nemo reads sound files by default? DALI, librosa?
