### ISSUE TITLE
Installation error on M1 Macbook - No matching distribution found for triton

### ISSUE THREAD

**Issue by stephenmcconnachie** [NVIDIA/NeMo#8116]
I am installing NeMo on M1 Macbook, following the installation guide for M1:
https://github.com/NVIDIA/NeMo?tab=readme-ov-file#mac-computers-with-apple-silicon

All works fine in Conda environment, up to running ./reinstall.sh. After a few successful packages installed I get this error:

```
INFO: pip is looking at multiple versions of nemo-toolkit to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement triton (from nemo-toolkit) (from versions: none)
ERROR: No matching distribution found for triton
```

The triton compatibility statement on the GitHub readme says Linux only:
https://github.com/openai/triton#compatibility

Is there a way to work around this in the M1 Mac installation?

- OS version: 14.1.2 (23B92)
- PyTorch version: 2.1.2 
- Python version: 3.11.0

**Comment by titu1994** [comment]
Triton dependency comes from pytorch 2.0 - you can try to install pytorch CPU first and then install NeMo instead of installing everything at the same time

**Comment by titu1994** [comment]
Btw only the asr toolkit can be guaranteed installed on MacBook. Don't use reinstall.sh, use pip install nemo_toolkit[asr]

**Comment by titu1994** [comment]
Those instructions were fine for pytorch 1.x but triton complicates things

**Comment by stephenmcconnachie** [comment]
Thank you so much for your help - that worked with `pip 'install nemo_toolkit[asr]'`
