### ISSUE TITLE
Remove Pydantic Version Constraint Due to Inflect Update

### ISSUE THREAD

**Issue by Joost385** [NVIDIA/NeMo#8118]
Currently, pydantic is pinned to version 1, which leads to conflicts with common frameworks such as fastapi.

https://github.com/NVIDIA/NeMo/blob/d3c589646b453f0395f19c2eef1ed958d048c6c7/requirements/requirements_common.txt#L4

It seems that inflect now supports pydantic 2, see https://github.com/jaraco/inflect/issues/187. Their requirements now list `pydantic >= 1.9.1`. Given this update, is it possible to remove the pydantic version constraint without further changes?

**Comment by titu1994** [comment]
I'll unpin it tomorrow, seems it should be fine.
