### ISSUE TITLE
Install decoders fails due to missing KenLM repository

### ISSUE THREAD

**Issue by diego-fustes** [NVIDIA/NeMo#813]
When executing the script `scripts/install_decoders.sh` an error is raised: "deepspeech scorer.h:9:10: fatal error: lm/enumerate vocab.hh". This is related with the following issue: https://github.com/PaddlePaddle/DeepSpeech/issues/465.

I was able to find a workaround by replacing the `setup.sh` file coming from DeepSpeech, but I guess that the fix should be applied to NeMo once it is pushed to DeepSpeech.

**Comment by sumeet559** [comment]
hey, can you share your new setup.sh file here. Thanks

**Comment by diego-fustes** [comment]
Sure, there it is. It's just pointing to the current official KenLM repo


`
#!/usr/bin/env bash
if [ ! -d kenlm ]; then
    git clone https://github.com/kpu/kenlm.git
    echo -e "\n"
fi

if [ ! -d openfst-1.6.3 ]; then
    echo "Download and extract openfst ..."
    wget http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.6.3.tar.gz
    tar -xzvf openfst-1.6.3.tar.gz
    echo -e "\n"
fi

if [ ! -d ThreadPool ]; then
    git clone https://github.com/progschj/ThreadPool.git
    echo -e "\n"
fi

echo "Install decoders ..."
python setup.py install --num_processes 4
`
