### ISSUE TITLE
VAD Quartz accuracy

### ISSUE THREAD

**Issue by byebye1** [NVIDIA/NeMo#814]
Hello!
I am using notebook 6_VAD_using_NeMo.ipynb to train the VAD model. The description says that you can achieve 98% accuracy on freesound, however, I get only 50% on the test sample. Maybe someone came across \ solved the problem?

**Comment by fayejf** [comment]
Hi! Thanks for your question.
Are you using real freesound data or the generated background data we provide for the demonstration? 

Please note we only have 6 ** _background_noise_  toy data for background in the tutorial** and that probably the result you get only 50% on the test sample. Please download freesound data (or use your own background data) and change your background_data_root. Don't forget to delete **--generate**.

For your convenience, we provide tutorial and scripts to help you download freesound data. Please have a look at https://github.com/NVIDIA/NeMo/blob/master/docs/sources/source/voice_activity_detection/tutorial.rst

**Comment by byebye1** [comment]
Thanks for the answer.
Indeed, only 6 tracks were used for the background.
the tutorial that you attached solved my problem
