### ISSUE TITLE
Set up microphone for Colab

### ISSUE THREAD

**Issue by MostafaAlaviyan** [NVIDIA/NeMo#8173]
Hello everyone
I want to run the 
https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Online_Offline_Microphone_VAD_Demo.ipynb
in colab, but colab dose not access to the microphone.
How can I resolve the issue?

**Comment by erastorgueva-nv** [comment]
Hi, the real-time streaming notebooks (such as that one) won't work in Colab unfortunately. You need to run the notebooks locally. They will not be able to record your microphone audio if you run them in Colab or in a Docker container.
