### ISSUE TITLE
Llama example scripts

### ISSUE THREAD

**Issue by Teng-xu** [NVIDIA/NeMo#8193]
I was trying to configure a test for the Llama model using Megatron Nemo. While I discovered an example configuration file (https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/language_modeling/conf/megatron_llama_config.yaml), I couldn't locate any sample scripts specifically designed for launching training with Llama. In my attempt, I used the Llama config file along with "megatron_gpt_pretraining.py," but unfortunately, it didn't work. Could you provide guidance or share any example scripts tailored for Llama pretraining?

**Comment by ethanhe42** [comment]
have you tried training recipes here? https://github.com/NVIDIA/NeMo-Megatron-Launcher/tree/master/launcher_scripts/conf/training/llama
