### ISSUE TITLE
Unable to train ASR model on multiple GPUs

### ISSUE THREAD

**Issue by ericininder** [NVIDIA/NeMo#8214]
The following is my command to launch distributed training in NeMO

 python3 -m torch.distributed.launch --nproc_per_node=2 --nnode=1 examples/asr/asr_ctc/speech_to_text_ctc.py --config-path=examples/asr/conf/quartznet/  --config-name=quartznet_15x5
 
torch vision：2.0.1+cu118
GPU：A100 

then, the error would occur due to unrecognized argument：--local-rank
![image](https://github.com/NVIDIA/NeMo/assets/155972611/6e921d54-cafd-41b2-97b2-125a85b383c5)

How do I change the source code from "--local_rank" to "--local-rank"

**Comment by titu1994** [comment]
This is not the correct way to use distributed training in NeMo. We utilize pytorch lightning which calls ddp and torch distributed for you. Simply call your script with python ABC.py --config-path xyz/ --config-name something.yaml. 

You can see some of the NeMo tutorials to see how we setup training with our scripts

**Comment by ericininder** [comment]
Thanks for your replying.
I have already trained on one node & multiple GPU cards.
@titu1994 
Here's the another question, how to set up multi nodes' information such as MASTER_ADDRESS or MASTER_PORT by PyTorch Lightning.
Is there any available tutorials?
Thanks a lot.

**Comment by titu1994** [comment]
It would be better to ask the folks at Pytorch Lightning since they might have the solution
