### ISSUE TITLE
Is there a method to add an N-gram to streaming ASR with cache-aware model?

### ISSUE THREAD

**Issue by gabitza-tech** [NVIDIA/NeMo#8225]
Hi,

I would like to use a cache-aware streaming model with CTC decoder + n-gram. Is this feature supported or could you give me some ideas on how I could implement this?

Thank you in advance! Any help is greatly appreaciated!

Best regards,
Gabi

**Comment by titu1994** [comment]
Streaming ASR at the moment does not support ngram
