### ISSUE TITLE
No such file or directory: 'megatron/core/requirements.txt' when installing nemo 1.22

### ISSUE THREAD

**Issue by bene-ges** [NVIDIA/NeMo#8244]
**Describe the bug**

No such file or directory: 'megatron/core/requirements.txt' when installing nemo 1.22

**Steps/Code to reproduce bug**
```
File "/tmp/pip-build-env-93j56cnr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 52, in <module>
    File "<string>", line 45, in req_file
  FileNotFoundError: [Errno 2] No such file or directory: 'megatron/core/requirements.txt'
```
A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by ethanhe42** [comment]
using the docker container is highly recommended https://github.com/NVIDIA/NeMo?tab=readme-ov-file#docker-containers

**Comment by VahidooX** [comment]
You are using the wrong version of python, you need to use python 3.10.12.

**Comment by bene-ges** [comment]
For some reasons, I need to stick to python3.8.
Previous Nemo version installed and worked ok (I do not use anything related to megatron). Is the reported error (missing file) related to Python version?

**Comment by titu1994** [comment]
If you need just ASR, you can safely install nemo_toolkit[ASR]. However it may be time to update. 3.8 has been deprecated for over a year now, and ASR has also started using syntax from 3.10 for Lhotse datasets. So in the coming month or two even pip install nemo_toolkit[ASR] will no longer safely work on python ,3.8

**Comment by titu1994** [comment]
As to docker, it's actually not the primary path we recommend for local 1 GPU development. 

NeMo ASR at least is designed to be a pip installable package. Ofc, docker is very convenient when you just want to start working on clusters, and we too only use docker containers in those cases

**Comment by ericharper** [comment]
This should fixed with this PR: https://github.com/NVIDIA/NeMo/pull/8465

Please try again and close the bug if your issue is solved.

**Comment by bene-ges** [comment]
thanks
