### ISSUE TITLE
Make checkpoint more robust

### ISSUE THREAD

**Issue by gshennvm** [NVIDIA/NeMo#8295]
currently when saving a nemo checkpoint it creates a directory and then it will save.

this is not robust because the training job can get preempted in the middle of save, creating a corrupted checkpoint.

Ideally we want nemo to create a temporary file, save to the temporary file and only when done saving should this file be renamed to an actual checkpoint

**Comment by jbieniusiewi** [comment]
Hi @gshennvm 
Fix for incomplete checkpoints was recently merged into main [[PR7952](https://github.com/NVIDIA/NeMo/pull/7952)].
Would it be possible for you to verify if that resolves the problem you noticed?
