### ISSUE TITLE
nemo on colab issue 

### ISSUE THREAD

**Issue by haythemtellili** [NVIDIA/NeMo#830]
Please how to setup nemo_nlp in google colab, i have this issue when i import nemo_nlp :

`ModuleNotFoundError: No module named 'nemo.utils.decorators'; 'nemo.utils' is not a package`

and also when i import nemo.collections.nlp i got another issue :+1: 

`   ```
   1 import nemo
----> 2 import nemo.collections.nlp as nemo_nlp

2 frames

/usr/local/lib/python3.6/dist-packages/nemo/collections/nlp/callbacks/glue_benchmark_callback.py in <module>()
     27 from sklearn.metrics import f1_score, matthews_corrcoef
     28 
---> 29 from nemo import logging
     30 from nemo.collections.nlp.utils.callback_utils import list2str, tensor2list
     31 

ImportError: cannot import name 'logging'
```
`

**Comment by ekmb** [comment]
@haythemtellili couldn't reproduce your error, but could you try:
`! pip install transformers==2.6 # due to HuggingFace transformer library updates
! pip install nemo_toolkit[all]
import nemo.collections.nlp as nemo_nlp`

**Comment by haythemtellili** [comment]
Thank you! issue fixed :)
one last question please, how can i use external models with nemo for example Arabic-bert or XLM-Roberta ?

**Comment by ekmb** [comment]
If you have a pre-trained checkpoint, config and vocab for Arabic Bert it should work with the existing Bert class https://github.com/NVIDIA/NeMo/blob/master/nemo/collections/nlp/nm/trainables/common/huggingface/bert_nm.py
To use XLM-Roberta you would need to add a wrapper similar to this https://github.com/NVIDIA/NeMo/blob/master/nemo/collections/nlp/nm/trainables/common/huggingface/roberta_nm.py

**Comment by haythemtellili** [comment]
Yes i have a checkpoint, config and vocab for Arabic Bert but can you explain me please how to match them with the your question_answering.py file ?

**Comment by ekmb** [comment]
In the questions_answering.py try:
model = nemo_nlp.nm.trainables.huggingface.BERT(config_filename=path_to_your_config)
tokenizer = nemo_nlp.data.tokenizers.NemoBertTokenizer(vocab_file=path_to_your_vocab, do_lower_case=True/False)

**Comment by haythemtellili** [comment]
Soory but it did'nt work and i got this error 
`
AttributeError: module 'nemo.collections.nlp.nm.trainables' has no attribute 'get_pretrained_lm_models_list'`

**Comment by haythemtellili** [comment]
I ran this command `!python /content/question_answering2.py --train_file  /content/SOQAL/data/arcd-train.json --eval_file /content/SOQAL/data/arcd-test.json --pretrained_model_name 'aubmindlab/bert-base-arabertv01'`
and i changed the model and tokenizer as you mentioned above .
Thanks a lot for your help :).
