### ISSUE TITLE
ERROR: Cannot uninstall 'llvmlite'.

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/NeMo#841]
I have the following line in my docker file:
`RUN pip install nemo_toolkit[all]` 
When I build the docker file, it errors out while trying to uninstall llvmlight with the following message
`  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.32.0
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
`

I also have a question about why it is uninstalling a number of python packages and then re-install it?

**Comment by ethem-kinginthenorth** [comment]
I figured it out and sharing it out for reference:
I needed to add 
`RUN pip install llvmlite --ignore installed` before 
`RUN pip install nemo_toolkit[all]`

and seems like it is some sort of dependency to nemo that would be why it is uninstalling / installing

**Comment by SCRIER-org** [comment]
seems to require --ignore-installed with a hyphen.  Same problem w/ NeMo.

**Comment by vk4arm** [comment]
hmm... 
for numba v0.54 you need to have:

pip install llvmlite==0.37.0rc2 --ignore-installed

at least it works for me

**Comment by titu1994** [comment]
I would really suggest using conda for Numba. conda install -c conda-forge numba==0.54.0

**Comment by vk4arm** [comment]
Is it works with newer version of llvmlite...? Honestly, it looks ilttle buggy )

**Comment by prviin** [comment]
pip install llvmlite --ignore-installed
