### ISSUE TITLE
installing apex without --global-option="--cpp_ext" --global-option="--cuda_ext" causes errors

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [NVIDIA/NeMo#842]
Apex package needs to be compiled with the following options:
`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`
otherwise (e.g., `pip install -v --no-cache-dir ./`) it errors out indicating something like:
ModuleNotFoundError("No module named 'amp_C')

**Comment by okuchaiev** [comment]
yes

**Comment by ethem-kinginthenorth** [comment]
is this documented somewhere?
