### ISSUE TITLE
How to do fine-tuning for Nvidia - NEMO canary-1b models

### ISSUE THREAD

**Issue by kurianbenoy** [NVIDIA/NeMo#8450]
**Is your feature request related to a problem? Please describe.**

- Can you explain, how to fine-tune Nvidia latest ASR models like Canary 1B and NeMo Parakeet ASR Models.

https://nvidia.github.io/NeMo/blogs/2024/2024-02-canary/
https://nvidia.github.io/NeMo/blogs/2024/2024-01-parakeet/

**Describe the solution you'd like**

- A notebook/code block explaining how to fine-tune Nvidia Canary models for low-resource Indic languages like Malayalam.

**Comment by titu1994** [comment]
For Parakeet, we have several tutorials in the Nemo tutorials directory - here is one to get started - https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/ASR_CTC_Language_Finetuning.ipynb

Most of the concepts will apply to Parakeet CTC / RNNT/ TDT. 

For Canary, it is a very new model, we are still adding documentation and tutorials for finetuning and scratch training

**Comment by kurianbenoy** [comment]
Thank @titu1994 for sharing these detials.

**Comment by JonneryR** [comment]
> For Parakeet, we have several tutorials in the Nemo tutorials directory - here is one to get started - https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/ASR_CTC_Language_Finetuning.ipynb
> 
> Most of the concepts will apply to Parakeet CTC / RNNT/ TDT.
> 
> For Canary, it is a very new model, we are still adding documentation and tutorials for finetuning and scratch training

Hello, I would like to know about the progress on Canary finetuning. Thanks.
