### ISSUE TITLE
Typo this needs to be replace

### ISSUE THREAD

**Issue by prathwishshetty** [NVIDIA/NeMo#8488]
https://github.com/NVIDIA/NeMo/blob/88e332d31a9ed54d5e19c5250e876eac18ad8936/tools/nemo_forced_aligner/utils/data_prep.py#L155

**Comment by nagavenkateshgavini** [comment]
@prathwishshetty 
I have raised a PR for this at https://github.com/NVIDIA/NeMo/pull/8498
Let's wait to get it merged soon. Thanks for raising PR

**Comment by nagavenkateshgavini** [comment]
This can be closed as PR gets merged

**Comment by prathwishshetty** [comment]
Thank you for the quick PR!
