### ISSUE TITLE
Why do you run all the examples with this errors?

### ISSUE THREAD

**Issue by CoffeeXC** [NVIDIA/NeMo#85]
RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([1]) and output[0] has a shape of torch.Size([]).

**Comment by blisc** [comment]
We have an issue with pytorch 1.13. Please uninstall pytorch and torch vision and try installing pytorch version 1.12 and torch vision 0.4.0

**Comment by okuchaiev** [comment]
closing this, @CoffeeXC  please re-open if you encounter the same issue for pytorch 1.12 and torchvision 0.4.0

**Comment by CoffeeXC** [comment]
Thank you, it has been solved, it is version incompatibility problem
