### ISSUE TITLE
Ratio Fine-Tuning Corpus to Pre-Training Corpus during Fine-Tuning

### ISSUE THREAD

**Issue by maxschwendeler** [NVIDIA/NeMo#853]
In the paper _Cross-Language Transfer Learning, Continuous Learning, and Domain Adaptation for End-to-End Automatic Speech Recognition  (https://arxiv.org/abs/2005.04290)_ you wrote that you use 2 the fine-tuning and pre-training corpus during fine-tuning the network to prevent catastrophic forgetting. I suppose this is especially essential when the fine-tuning corpus has very limited data, eg ~10 hours.
Do you have any suggestions or insights if the pre-trained-corpus should be cropped (limited in time) that the ratio of the pre-training and fine-tuning corpus has a good magnitude? 50/50? 80/20?

**Comment by okuchaiev** [comment]
@vsl9  any isights on this?

**Comment by vsl9** [comment]
> Do you have any suggestions or insights if the pre-trained-corpus should be cropped (limited in time) that the ratio of the pre-training and fine-tuning corpus has a good magnitude?

It depends on datasets and target balance between WERs. If it is important to keep good WERs on both datasets then it is worth to oversample smaller dataset (of course, applying data augmentation) to get distribution of datasets closer to uniform. Usually, a larger proportion of some corpus in training (or fine-tuning) mix results in better WER on that corpus.

**Comment by maxschwendeler** [comment]
Thanks for replying!

That sounds reasonable, I will give it a shot.
