### ISSUE TITLE
Cannot install version 1.23.0 because of missing megatron-core version

### ISSUE THREAD

**Issue by tshastry** [NVIDIA/NeMo#8566]
**Describe the bug**

When trying to install nemo version 1.23.0 via poetry, I get this error:

```
#21 257.6   RuntimeError
#21 257.6
#21 257.6   Unable to find installation candidates for megatron-core (0.5.0)
#21 257.6
#21 257.6   at /usr/local/lib/python3.8/dist-packages/poetry/installation/chooser.py:76 in choose_for
#21 257.7        72│  
#21 257.7        73│             links.append(link)
#21 257.7        74│  
#21 257.7        75│         if not links:
#21 257.7     →  76│             raise RuntimeError(f"Unable to find installation candidates for {package}")
#21 257.7        77│  
#21 257.7        78│         # Get the best link
#21 257.7        79│         chosen = max(links, key=lambda link: self._sort_key(package, link))
#21 257.7        80│  
```

**Steps/Code to reproduce bug**

poetry install nemo with this configuration:
```
nemo-toolkit = { extras = [
  "asr",
  "nlp",
  "core",
  "text_processing",
  "tts",
], version="1.23.0"}
```

**Expected behavior**

Install succeeds

**Environment overview (please complete the following information)**

 - Environment location: Local environment Ubuntu 18.04.3 LTS
 - Method of NeMo install: poetry install

**Environment details**

Ubuntu 18.04.3 LTS
Poetry version 1.4.2
Cuda 11.6

**Additional context**

**Comment by LL-AI-dev** [comment]
the latest megatron version for python 3.8 is 0.4.0. you will need to upgrage to python 3.10 for any nemo version after 1.20.0 (i think that is when the megatron version requirement was upgraded from 0.4.0 which is still python 3.8 compatible)

I believe megatron core is just used for NLP so if you install all the extras but that you might be able to stick to python 3.8

**Comment by titu1994** [comment]
3.10 python is a requirement for both NeMo ASR and NLP as of 1.23. Python 3.8 will be EOL this year, so it would be good to update to a newer version
