### ISSUE TITLE
 No module named 'nemo.collections.multimodal.models'

### ISSUE THREAD

**Issue by ranga-godhandaraman** [NVIDIA/NeMo#8572]
**Problem statement**
~ I'm working on the "Stable-Diffusion" model. 
~ while converting to ".nemo" I'm facing some issues in the code from file "convert_external_clip_to_nemo.py" on line 41
![image](https://github.com/NVIDIA/NeMo/assets/111883012/b18d0378-c19c-477c-bfbf-113186aa3cc2)

~ This is the import line:
![image](https://github.com/NVIDIA/NeMo/assets/111883012/e6eaec71-69c9-4bc7-a24d-774ab6bb1ec3)
~ Even though those Classes are defined, they don't get imported. 

![image](https://github.com/NVIDIA/NeMo/assets/111883012/3d12db34-93ab-4856-a343-3bbfa4e80e4f)

~please provide a solution

**Comment by titu1994** [comment]
These collections are under active development, we hope to stabilize them soon
