### ISSUE TITLE
Cannot disable progress bar

### ISSUE THREAD

**Issue by ksivaman** [NVIDIA/NeMo#8577]
When setting `+trainer.enable_progress_bar=False` in the config, the application crashes since `CustomProgressBar` is always passed as callback to PyTorch lightning trainer.

```
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: Trainer was configured with `enable_progress_bar=False` but found `CustomProgressBar` in callbacks list.
```

**Comment by ericharper** [comment]
@athitten, can you take a look at this when you have time?

**Comment by athitten** [comment]
@ksivaman this issue should be fixed in this PR: [](https://github.com/NVIDIA/NeMo/pull/8663). Can you please help review it ? Thank you.
