### ISSUE TITLE
ValueError when higher minimum_timestamp_duration given : "start_time must be a float or str containing float, but got int"

### ISSUE THREAD

**Issue by Stephane-Lpt** [NVIDIA/NeMo#8592]
**Describe the bug**
I wanted to put a `minimum_timestamp_duration` to visualize the result given by nemo forced aligner with [Gecko](https://github.com/gong-io/gecko) as the documentation recommends. 
When I change the value of `minimum_timestamp_duration` to 0.4, it's all good.
If I try to change the `minimum_timestamp_duration` for a higher value like 0.5, I get a `ValueError` : 
![image](https://github.com/NVIDIA/NeMo/assets/66870443/ca90e8df-a4f2-41d4-a3a2-1867e0b37cae)
**Steps/Code to reproduce bug**

- Notice the option **ctm_file_config.minimum_timestamp_duration=0.5** to change the value of `minimum_timestamp_duration`. To be sure to have the error, you can put an extremely high value like 50.
```
python <path to NeMo>/tools/nemo_forced_aligner/align.py pretrained_name="stt_en_fastconformer_hybrid_large_pc" manifest_filepath=nemo/manifest.json output_dir=nemo/output ctm_file_config.minimum_timestamp_duration=0.5
```
The value that is too high and causes the error **depends on** the **respective duration of your tokens/words/segments** that are calculated in this [loop](https://github.com/NVIDIA/NeMo/blob/1882d0d0025832a530063e5b699347253b2ab768/tools/nemo_forced_ligner/utils/make_ctm_files.py#L83). The loop iterates over **each token/word/segment** of the transcription and finally produces the `ctm` file).

**Expected behavior**

- No error should be raised.

**Environment overview**

 - Method of NeMo install: source

**Additional context**
**_This is a minor error that I've already fixed locally, so I'll make a pull request in a few minutes_**

**Comment by erastorgueva-nv** [comment]
PR with fix has been merged, so closing this. Thank you for the fix.
