### ISSUE TITLE
No module named 'nemo'

### ISSUE THREAD

**Issue by wuhongsheng** [NVIDIA/NeMo#8707]
**Describe the bug**

I run Speaker_Diarization_Inference.ipynb on my mac book pro(M2)

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version.  14.2.1
- PyTorch version 2.0.1
- Python version 3.11

**Additional context**

Example: GPU model

**Comment by titu1994** [comment]
Please install NeMo with pip install nemo_toolkit[all]

**Comment by wuhongsheng** [comment]
> Please install NeMo with pip install nemo_toolkit[all]

Thank you ,I solved it. It's an environmental problem.
