### ISSUE TITLE
Tutorials broken due to Megatron-Core dependency

### ISSUE THREAD

**Issue by jasoncwik** [NVIDIA/NeMo#8714]
**Describe the bug**

The NeMo [tutorials ](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/starthere/tutorials.html) on Google Colab do not run due to a dependency issue with Megatron-Core. Currently, NeMo is pinned to Megatron-Core 0.5.0, but references the `IndexedDataset` class. In 0.5.0 this class is called `MMIndexedDataset`. In Megatron-Core `main` branch is is now `IndexedDataset`.

**Steps/Code to reproduce bug**
1. Load the tutorial at https://colab.research.google.com/github/NVIDIA/NeMo/blob/stable/tutorials/00_NeMo_Primer.ipynb
2. Run the first three cells.

On the third cell:
```
import nemo.collections.asr as nemo_asr
import nemo.collections.nlp as nemo_nlp
import nemo.collections.tts as nemo_tts
```

You get the error:
```
ImportError                               Traceback (most recent call last)
[<ipython-input-6-424875f6207b>](https://localhost:8080/#) in <cell line: 2>()
      1 import nemo.collections.asr as nemo_asr
----> 2 import nemo.collections.nlp as nemo_nlp
      3 import nemo.collections.tts as nemo_tts

5 frames
[/usr/local/lib/python3.10/dist-packages/nemo/collections/nlp/data/language_modeling/megatron/gpt_fim_dataset.py](https://localhost:8080/#) in <module>
     17 import numpy as np
     18 from megatron.core.datasets.gpt_dataset import GPTDataset, GPTDatasetConfig
---> 19 from megatron.core.datasets.indexed_dataset import IndexedDataset
     20 from megatron.core.datasets.utils import Split
     21 

ImportError: cannot import name 'IndexedDataset' from 'megatron.core.datasets.indexed_dataset' (/usr/local/lib/python3.10/dist-packages/megatron/core/datasets/indexed_dataset.py)
```

It looks like I see the same error on any of the NLP tutorials

**Expected behavior**

The tutorial should run to completion.

**Environment overview (please complete the following information)**

Google Collab
Tutorials loaded from https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/stable/starthere/tutorials.html

**Comment by titu1994** [comment]
There was a temporary error due to the `stable` tag pointing to NeMo main instead of NeMo r1.23.0. Please try again, it should work now.

**Comment by jasoncwik** [comment]
That worked. Thanks!
