### ISSUE TITLE
Error in loading models from checkpoint for class NeMoModel

### ISSUE THREAD

**Issue by bagavi** [NVIDIA/NeMo#872]
Quartz ASR, checkpoint has three neural modules  -- Encoder, Decoder, Quartznet. The first two modules can be [restored](https://github.com/NVIDIA/NeMo/blob/3366abbda42a41d200e4d437c24e9874779ed2d0/nemo/core/callbacks.py#L493) using `restore_from()` function. However, the third module is should be restored from `from_pretrained()` function right? I might be totally wrong here :-)

**Comment by okuchaiev** [comment]
if you are using NeMo version 0.11 then you can restore the whole model from .nemo file using .from_pretrained method.
Individual modules (e.g. encoder, decoder) can be restored using restore_from function like you mentioned.
