### ISSUE TITLE
sample rate error in asr

### ISSUE THREAD

**Issue by anhtuanluu** [NVIDIA/NeMo#873]
I ran the speech2text.py script using quartznet15x5 for my data. But when set sample_rate = 8000 in AudioToTextDataLayer raise error (nemo.core.neural_types.neural_type.NeuralPortNmTensorMismatchError: ('AudioToMelSpectrogramPreprocessor', 'input_signal', 'axes: (batch, time); elements_type: AudioSignal', 'axes: (batch, time); elements_type: AudioSignal', <NeuralTypeComparisonResult.SAME_TYPE_INCOMPATIBLE_PARAMS: 7>))
How can I fix that?

**Comment by okuchaiev** [comment]
This means that our model was trained with 16Khz data and can not be used with 8Khz data.
If you want to use our checkpoint, then you can upsamples your 8Khz data to 16Khz and use speech2text.py as-is (e.g. without changing sample rate parameter).
If you want to train your own model from scratch on 16Khz - they you need to change sample rate parameter and train from scratch (e.g. not using pre-trained checkpoint)
