### ISSUE TITLE
Restoring from pretrained checkpoint is broke for "stt_ua_fastconformer_hybrid_large_pc"

### ISSUE THREAD

**Issue by taras-sereda** [NVIDIA/NeMo#8736]
Hi folks! I'm trying to restore `EncDecHybridRNNTCTCModel` from checkpoint trained on Ukrainian

```
In [4]: from nemo.collections.asr.models import EncDecHybridRNNTCTCBPEModel
In [5]: model = EncDecHybridRNNTCTCBPEModel.from_pretrained("stt_ua_fastconformer_hybrid_large_pc")
```

model can't be restored because of keyword argument `conv_pointwise_type`

```
InstantiationException: Error in call to target 'nemo.collections.asr.modules.conformer_encoder.ConformerEncoder':
TypeError("ConformerEncoder.__init__() got an unexpected keyword argument 'conv_pointwise_type'")
```

Search through NeMo repository I only found `conv_pointwise_type` keyword  in one [PR](https://github.com/NVIDIA/NeMo/pull/6476), and nowhere in the code base, that looks suspicious. Is there any recommendation how one would make that checkpoint compatible?

Env:
- Nemo version: nemo_toolkit==1.23.0
- OS: Ubuntu 22.04

**Comment by taras-sereda** [comment]
I figured how to load the parameters, though with the hack.

1. I obtained model's config by doing this:
```
ckpt_name = "stt_ua_fastconformer_hybrid_large_pc"
cfg = nemo_asr.models.EncDecHybridRNNTCTCBPEModel.from_pretrained(model_name=ckpt_name, return_config=True)
omegaconf.OmegaConf.save(cfg, f="cfg.yaml")
```

2. then I commented out the `conv_pointwise_type` attribute of encoder's parameters.

3. loaded model by providing a patched config:
```
model = nemo_asr.models.EncDecHybridRNNTCTCBPEModel.from_pretrained(
    model_name=ckpt_path,
    override_config_path="./cfg_modified.yaml",
```

The above hack works, though I wonder if the loaded model works correctly? Also it will be good to update the official checkpoints in the NGC registry.

Same issue happens to `stt_ru_fastconformer_hybrid_large_pc` russian checkpoint.

**Comment by titu1994** [comment]
Thank you for reporting the issue and the fix ! We'll take a look soon. I think we updated the huggingface version but not NGC

**Comment by kzelias** [comment]
Still relevant for nvcr.io/nvidia/nemo:24.01.speech

**Comment by jamanz** [comment]
I encountered a similar issue with the `stt_fr_fastconformer_hybrid_large_pc` model while working in the Kaggle environment for a forced alignment task. Using the pip-installed version of NeMo (2.3.0), I received the following error:

```
TypeError: ConformerEncoder.__init__() got an unexpected keyword argument 'conv_pointwise_type'
```

### Workaround:
To resolve this issue, I downloaded the `.nemo` model file from Hugging Face ([link](https://huggingface.co/nvidia/stt_fr_fastconformer_hybrid_large_pc)) and used it by specifying the `model_path` in the alignment configuration. Below are the steps I followed:

1. **Download the Model**:
   ```python
   import requests

   huggingface_url = "https://huggingface.co/nvidia/stt_fr_fastconformer_hybrid_large_pc/resolve/main/stt_fr_fastconformer_hybrid_large_pc.nemo"
   local_model_path = "stt_fr_fastconformer_hybrid_large_pc.nemo"
   
   response = requests.get(huggingface_url, stream=True)
   with open(local_model_path, "wb") as f:
       for chunk in response.iter_content(chunk_size=8192):
           f.write(chunk)
   ```

2. **Add the Model to the Configuration**:
   I set the downloaded model's path in the alignment configuration as follows:
   ```python
   align_config = {
       "model_path": "stt_fr_fastconformer_hybrid_large_pc.nemo",
       "manifest_filepath": manifest_filepath,
       "output_dir": output_dir,
       # Other alignment parameters...
   }
   ```
