### ISSUE TITLE
ImportError: cannot import name 'CTCDecodingConfig' from 'nemo.collections.asr.parts.submodules' 

### ISSUE THREAD

**Issue by wuhongsheng** [NVIDIA/NeMo#8745]
**Describe the bug**

when I run speech_to_text_with_vad.py with some parameters below

!python /Users/whs/PycharmProjects/NeMo/examples/asr/asr_vad/speech_to_text_with_vad.py \
    manifest_filepath=/Users/whs/PycharmProjects/ava-speech-downloader/temp_manifest_input.json \
    vad_model=vad_multilingual_frame_marblenet \
    vad_config=../conf/vad/frame_vad_infer_postprocess.yaml

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version  mac 14.2.1 
- PyTorch version 
- Python version 3.11

**Additional context**

Example: GPU model

**Comment by titu1994** [comment]
Which version of NeMo is installed? If you're using NeMo 1.23, you need to change branch to r1.23.0 before selecting and using the script

**Comment by wuhongsheng** [comment]
> Which version of NeMo is installed? If you're using NeMo 1.23, you need to change branch to r1.23.0 before selecting and using the script

I try install  pip3 install 'nemo_toolkit[asr]==1.23.0'  print errer info :

INFO: pip is looking at multiple versions of nemo-toolkit to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement triton (from nemo-toolkit) (from versions: none)
ERROR: No matching distribution found for triton
