### ISSUE TITLE
Error in loading biomegatron models from checkpoints

### ISSUE THREAD

**Issue by gserb-datascientist** [NVIDIA/NeMo#875]
Attempt to train BioBERT on a biomedical named entity recognition (NER) dataset  using
https://github.com/NVIDIA/NeMo/blob/master/examples/nlp/biobert_notebooks/biobert_ner.ipynb
and "BioMegatron345mUncased" checkpoint failed on model load stage:

model = nemo_nlp.nm.trainables.get_pretrained_lm_model(
--->          config=model_config, pretrained_model_name=pretrained_model_name[model_type], checkpoint=model_checkpoint
          )

RuntimeError: Error(s) in loading state_dict for BERT:
Missing key(s) in state_dict: "bert.embeddings.word_embeddings.weight", "bert.embeddings.position_embeddings.weight", "bert.embeddings.token_type_embeddings.weight", "bert.embeddings.LayerNorm.weight", "bert.embeddings.LayerNorm.bias", "bert.encoder.layer.0.attention, ........"bert.encoder.layer.11.intermediate.dense.bias", "bert.encoder.layer.11.output.dense.weight", "bert.encoder.layer.11.output.dense.bias", "bert.encoder.layer.11.output.LayerNorm.weight", "bert.encoder.layer.11.output.LayerNorm.bias", "bert.pooler.dense.weight", "bert.pooler.dense.bias". 
	Unexpected key(s) in state_dict: "iteration", "model".

**Comment by yzhang123** [comment]
what are your values for config=model_config, pretrained_model_name=pretrained_model_name[model_type], checkpoint=model_checkpoint ?

**Comment by FatimaArshad-DS** [comment]
This issue is still persistent. What can be done about it?

**Comment by FatimaArshad-DS** [comment]
https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Token_Classification-BioMegatron.ipynb

This notebook still can't load BioMegatron. It throws an error.

**Comment by yzhang123** [comment]
@okuchaiev could you assign someone?

**Comment by titu1994** [comment]
This issue is over a year old, please refer to newer issues regarding biomegatron.
