### ISSUE TITLE
Convert Llama-7b to nemo: checkpoint ckpts are not saved as a model_weights.ckpt file

### ISSUE THREAD

**Issue by yanzhaodong2024** [NVIDIA/NeMo#8753]
While I am trying to convert llama-hf model to Nemo via scripts/nlp_language_modeling/convert_llama_hf_to_nemo.py, the checkpoints are saved with each params type as a separate folder, as below
<img width="1284" alt="image" src="https://github.com/NVIDIA/NeMo/assets/157778011/cb83ef47-eb43-4c08-8093-c169c628d8f7">
However, when I am running Nemo-aligner, I was told that a model_weights.ckpt file is required, what is the problem here?

btw: I am using the latest version of Nemo

**Comment by qijiaxing** [comment]
The converter `convert_llama_hf_to_nemo.py` should produce a `.nemo` file, not a dir. Can you try using NeMo docker image? https://catalog.ngc.nvidia.com/orgs/nvidia/containers/nemo
