### ISSUE TITLE
Speaker Diarization Inference: cuda=False, using CPU for eigen decomposition when creating model from NeuralDiarizer.from_pretrained()

### ISSUE THREAD

**Issue by Hyprnx** [NVIDIA/NeMo#8760]
Hi, im having the same problem as above, 

I tried to create the model with:
```
        model = NeuralDiarizer.from_pretrained('diar_msdd_telephonic', map_location='cuda')
```
```
        model = NeuralDiarizer.from_pretrained('diar_msdd_telephonic', map_location='cuda:0')
```
```
        model = NeuralDiarizer.from_pretrained('diar_msdd_telephonic', map_location='cuda').to('cuda')
```
```
        model = NeuralDiarizer.from_pretrained('diar_msdd_telephonic', map_location='cuda:0').to('cuda:0')
```
and even
```
        model = NeuralDiarizer.from_pretrained('diar_msdd_telephonic').to('cuda:0')
```

On a certain machine (the jupyter notebook on AWS Sagemaker, running on Data Science 3.0, ml.g4dn.xlarge machine), all of these option worked with GPU flawlessly, this only takes 6 seconds for my audio file.

But when i deploy it on AWS Sagemaker Endpoint(with the container [PyTorch 2.0.0 with HuggingFace transformers](763104351884.dkr.ecr.ap-southeast-1.amazonaws.com/huggingface-pytorch-inference:2.0.0-transformers4.28.1-gpu-py310-cu118-ubuntu20.04), running on ml.g4dn.xlarge), Nemo keeps telling me:
```
... speaker_utils:464] cuda=False, using CPU for eigen decomposition. This might slow down the clustering process.
``` 
just as above. This took 112 seconds to complete with the same audio file.

i dont understand why with the same audio file, same code, it could result in two completely different outcomes?

I appreciate any help, thank you in advanced

**Comment by Dec1mo** [comment]
I'm having this same issue!

**Comment by hhd52859** [comment]
same issue

**Comment by tango4j** [comment]
The environment you are deploying the NeMo diarization seems like CUDA is not enabled.
If your CUDA setting is not properly set, it will run it on CPU then it will get very slow.
Check `torch.cuda.is_available()` is True in your container environment on the instance you are using.

**Comment by ytcheng** [comment]
I'm having this same issue!
