### ISSUE TITLE
FileNotFoundError: Model stt_zh_citrinet_1024_gamma_0_25 was not found. Check cls.list_available_models() for the list of all available models.

### ISSUE THREAD

**Issue by wuhongsheng** [NVIDIA/NeMo#8761]
**Describe the bug**

I try offline_diar_with_asr_infer wish zh asr model 
!python ./clustering_diarizer/offline_diar_with_asr_infer.py \
    diarizer.manifest_filepath="/home/zhibo/Eval_Ali/Eval_Ali_far/audio_dir/temp_manifest_input.json"  \
    diarizer.out_dir='demo_asr_output' \
    diarizer.speaker_embeddings.parameters.save_embeddings=False \
    diarizer.asr.parameters.asr_based_vad=True \
    diarizer.asr.model_path="stt_zh_citrinet_1024_gamma_0_25" 

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by wuhongsheng** [comment]
I try restory form local print error info :
ValueError: `cfg` must have `tokenizer` config to create a tokenizer !

**Comment by nithinraok** [comment]
@weiqingw4ng will submit a PR to fix this. Thank you Weiqing

**Comment by nithinraok** [comment]
@weiqingw4ng is working on this, he is working to improve the code for other non-english languages as well.
