### ISSUE TITLE
AttributeError: module 'nemo.core.classes' has no attribute 'dataset'

### ISSUE THREAD

**Issue by biswajit0511** [NVIDIA/NeMo#8777]
**Describe the bug**

NeMo version: '1.23.0rc0'

Running on MAC OS <Sonoma 14.3.1> ,  Conda environment 

 import nemo.collections.asr as nemo_asr gives the following error:

---> 31 class ASRDatasetConfig(nemo.core.classes.dataset.DatasetConfig):
     32     manifest_filepath: Optional[Any] = None
     33     sample_rate: int = MISSING

AttributeError: module 'nemo.core.classes' has no attribute 'dataset'

**Comment by nithinraok** [comment]
Can you show steps on how you installed NeMo. Chances are you probably installed one NeMo version but using different version code.

**Comment by biswajit0511** [comment]
NeMo version: '1.23.0rc0' 
I followed the instructions as under Conda :


# clone the repo and install in development mode
git clone https://github.com/NVIDIA/NeMo
cd NeMo
pip install 'nemo_toolkit[all]'

**Comment by titu1994** [comment]
If you're cloning the repo you need to follow the installation from source part of the readme - pip install -e .[asr]
