### ISSUE TITLE
Getiing an error called  ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by roshanjoebenny** [NVIDIA/NeMo#8830]
When I am importing from nemo.collections import nlp as nemo_nlp
I was  getting an error as module not found of apex.So I tryed installing apex using the below given commands
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir \
--global-option="--cpp_ext" --global-option="--cuda_ext" ./

When executing this command I was getting an error called 

ModuleNotFoundError: No module named 'packaging'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  etting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by nithinraok** [comment]
@roshanjoebenny could you raise this issue on https://github.com/NVIDIA/apex
