### ISSUE TITLE
A bug in AudioToTextDataLayer.

### ISSUE THREAD

**Issue by aijianiula0601** [NVIDIA/NeMo#884]
There is a bug in class 'AudioToTextDataLayer' where i eval the mandarin with the speech2text_infer.py. It will change the chinese char to pinyin. The bug is the variable dataset_params in class 'AudioToTextDataLayer'. The value of  key in dataset_params  is  parser='en'  in default. But the right default value should be 'base'. 

The bug display:
It will conver the text '相 关 公 司 股 票 走 势 国 海 证 券' to 'xiang guan gong si gu piao zou shi guo hai zheng quan' when eval.
This will make transcript to all zeros in eval due to asr_model.vocabulary can not find any label for changed char.

**Comment by paklau99988** [comment]
How did you get the pinyin?

**Comment by aijianiula0601** [comment]
> How did you get the pinyin?

in traning
