### ISSUE TITLE
vad finetune on my dataset

### ISSUE THREAD

**Issue by freshpearYoon** [NVIDIA/NeMo#8858]
Hi, I am trying to finetune vad and speaker diarization model on korean dataset. However, I cannot find tutorial related to vad. I've found [File not found (github.com)](https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/06_Voice_Activiy_Detection.ipynb) tutorial from previous issues, but it seems that the tutorial is deleted. How can I finetune vad model with my dataset?
Also, Is there any way to train vad&speaker diarization model together?

**Comment by nithinraok** [comment]
Here is the tutorial for VAD: https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Voice_Activity_Detection.ipynb 

Currently we don;t support training VAD and SD model together

**Comment by freshpearYoon** [comment]
> Here is the tutorial for VAD: https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/Voice_Activity_Detection.ipynb
> 
> Currently we don;t support training VAD and SD model together

Thank you for your answer! Additionally, I am confused about how the dataset. Can one example of dataset contain more than 2 speech chunks?

**Comment by nithinraok** [comment]
I didn;t understand your question well: `Can one utterance contain more than 2 speech chunks?` 
Do you mean, if VAD is frame or segment based?
