### ISSUE TITLE
How to search for pretrained model

### ISSUE THREAD

**Issue by zydjohnHotmail** [NVIDIA/NeMo#8871]
**Is your feature request related to a problem? Please describe.**
How can I search for a pretrained ONNX model?
Hi, since my PC has no powerful GPU, so training any model is almost mission impossible, so I have to use some pretrained model, for example: I know one ONNX model: stt_en_quartznet15x5.onnx
But I can't find such pretrained model from ONNX zoo.

**Describe the solution you'd like**
I want to have some kind of pre-trained model search, so I can either input the model name or something to describe the pre-trained models, like: "Transcribe French", then the searching engine can return a list of pre-trained models meet the searching conditions, and provide download link, so I can download the models I want.
Please note that not everyone has the computing power to train any complicated model, not many people can host computing power like a data center.

Provide a code snippet on how new APIs/changes would be used by others.

**Describe alternatives you've considered**
No alternatives I can think about.

**Additional context**

**Comment by titu1994** [comment]
We don't have pretrained onnx models released in NeMo. Nvidia Riva might have .Riva files that contain a compiled model but that isn't supported in NeMo
