### ISSUE TITLE
TypeError: EncDecCTCModel.transcribe() got an unexpected keyword argument 'logprobs'

### ISSUE THREAD

**Issue by ican24** [NVIDIA/NeMo#8884]
Hi,

I am trying to use language model described in Offline_ASR.ipynb, but I am receiving error:

`TypeError: EncDecCTCModel.transcribe() got an unexpected keyword argument 'logprobs'`

My code is

`import nemo
import nemo.collections.asr as nemo_asr
import sys
import os
import ctc_decoders
import numpy as np

wave_file = ['test2.wav']
quartznet = nemo_asr.models.EncDecCTCModel.restore_from(restore_path="checkpoints/ASR-Char-Model-Language-hy.nemo",strict=False)
#print(quartznet.transcribe(wave_file,batch_size=1))
#softmax implementation in NumPy
def softmax(logits):
    e = np.exp(logits - np.max(logits))
    return e / e.sum(axis=-1).reshape([logits.shape[0], 1])

#let's do inference once again but without decoder
logits = quartznet.transcribe(wave_file, logprobs=True)[0]
probs = softmax(logits)

lm_path='/corpuses/hye/corpus/19.0/lm_tgsmall.arpa.gz'
beam_search_lm = nemo_asr.modules.BeamSearchDecoderWithLM(
    vocab=list(quartznet.decoder.vocabulary),
    beam_width=16,
    alpha=2, beta=1.5,
    lm_path=lm_path,
    num_cpus=max(os.cpu_count(), 1),
    input_tensor=False)

beam_search_lm.forward(log_probs = np.expand_dims(probs, axis=0), log_probs_length=None)`

The single difference from Offline_ASR.ipynb is nemo_asr.models.EncDecCTCModel.restore_from instead nemo_asr.models.EncDecCTCModel.from_pretrained.

Could you advise me error reason?
Thank you advance!

**Comment by titu1994** [comment]
NeMo main has an updated version of transcribe() that supports more functionality and deprecated old arguments with new ways of doing things. 

You can use and install Nemo 1.23.0 branch to get it to work. Or you can use the following to fix transcribe on main. 

Change 
logits = quartznet.transcribe(wave_file, logprobs=True)[0]

To 

```python

Logits_hyps = asr_model.transcribe(
                self.audio_file_list, batch_size=self.asr_batch_size, return_hypotheses=True
            )  # type: 
List[nemo_asr.parts.Hypothesis]
            
Logits = [hyp.alignments for hyp in Logits_hyps]
```

**Comment by ican24** [comment]
Thank you very much!
