### ISSUE TITLE
NeMo License Discrepancy?

### ISSUE THREAD

**Issue by rgleaton** [NVIDIA/NeMo#8886]
Howdy,

So I noticed that in the readme of this GitHub Repo it states that NeMo is released under the Apache 2.0 license.
![image](https://github.com/NVIDIA/NeMo/assets/166728544/b705b16e-afbe-43e1-9038-c36e81b559aa)
This is also the license [linked](https://github.com/NVIDIA/NeMo/blob/main/LICENSE) in the repo.

However, on the NVIDIA website, the page for the [NeMo Framework Docker Container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/nemo) states that NeMo is licensed under the NVIDIA AI Product Agreement.
![image](https://github.com/NVIDIA/NeMo/assets/166728544/bf298587-4d52-4fd6-b7ea-2c60e8fa5824)

Is there a reason for this discrepancy, or could anyone provide any guidance on which license is correct?

**Comment by jgerh** [comment]
Here are the suggested revisions to the Licenses subtopic in the Overview file:

Licenses

- NVIDIA NeMo is released under an [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) license
- NVIDIA NeMo Framework container is licensed under the [NVIDIA AI Product Agreement](https://www.nvidia.com/en-us/data-center/products/nvidia-ai-enterprise/eula/)
