### ISSUE TITLE
Streaming example provided for Hinglish doesnt work.

### ISSUE THREAD

**Issue by nairajay2k** [NVIDIA/NeMo#8901]
python ~/pcs/NeMo//examples/asr/asr_chunked_inference/ctc/speech_to_text_buffered_infer_ctc.py  --asr_model="stt_hi_conformer_ctc_large"  --test_manifest=""  --output_path=""  --model_stride=4
usage: speech_to_text_buffered_infer_ctc.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE] [--run] [--multirun] [--shell-completion] [--config-path CONFIG_PATH]
                                            [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR] [--experimental-rerun EXPERIMENTAL_RERUN] [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
                                            [overrides ...]
speech_to_text_buffered_infer_ctc.py: error: unrecognized arguments: --asr_model=stt_hi_conformer_ctc_large --test_manifest= --output_path= --model_stride=4

This is when I run as per the streaming example on https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_hi_conformer_ctc_large

I am using python 3.10 and pip.

**Steps/Code to reproduce bug**

To reproduce 
 git clone https://github.com/NVIDIA/NeMo.git
python ~/pcs/NeMo//examples/asr/asr_chunked_inference/ctc/speech_to_text_buffered_infer_ctc.py  --asr_model="stt_hi_conformer_ctc_large"  --test_manifest=""  --output_path=""  --model_stride=4

**Expected behavior**
The code should work and accept stream input and generate text.

**Environment overview (please complete the following information)**
Im running this on my laptop ubuntu 22.04 with RTX 4070

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
Personal laptop
 - Method of NeMo install: [pip install or from source]. Please specify exact commands you used to install.
 sudo apt-get update && sudo apt-get install -y libsndfile1 ffmpeg
pip install Cython
pip install nemo_toolkit['all']
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model

**Comment by titu1994** [comment]
This is a monolingual Hindi only model, it doesn't support English.

**Comment by nairajay2k** [comment]
How can i get this hindi model to work for hindi alone. I followed the steps but havent been successful
