### ISSUE TITLE
Saving and reloading the pretrained model's vocab breaks the tokenizer.

### ISSUE THREAD

**Issue by owos** [NVIDIA/NeMo#9024]
**Describe the bug**

So I picked [nvidia/parakeet-ctc-0.6b](https://huggingface.co/nvidia/parakeet-ctc-0.6b) and I untarred the the `.nemo`  file.
After that, I then loaded the model and changed the the vocab this way:

**Steps/Code to reproduce bug**

```python
model.change_vocabulary(
            new_tokenizer_dir=vocab_extension_path, new_tokenizer_type="bpe"
        )
```
where `vocab_extension_path` = the path of the pretrained model.
 

**Expected behavior**
The model's tokenizer is supposed to remain intact and not start generating gibberish because I am just reloading the extact tokenizer that was used to pretrain the model.

**Why I need this**
I need to replace some tokens in the model's vocab while keeping the order tokens intact. If I cant keep other parts of the tokenizer intact then my replacement of tokens cannot work.

**Comment by nithinraok** [comment]
It should be path to a tokenizer directory not model. 

the directory should contain:
* `tokenizer.model`
* `tokenizer.vocab`
* `vocab.txt`
