### ISSUE TITLE
Flashlight decoder for ASR

### ISSUE THREAD

**Issue by Mark-Serin** [NVIDIA/NeMo#9103]
[At this page](https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/asr/asr_language_modeling.html#flashlight-flashlight) you describe how to use flashlight decoder by launching your python script. But I can't find any parameters it should have. In further NeMo versions you have [installation guide](https://github.com/NVIDIA/NeMo/blob/2331b063d6f0282fa79c32e4e780db6cc7ef19f2/scripts/asr_language_modeling/ngram_lm/install_beamsearch_decoders.sh#L53) but no python script to use it.

Can you please help me with that? This feature (flashlight decoder) is still in progress or deprecated?

**Comment by titu1994** [comment]
Yes it's supported, please find installation instructions here - https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/asr/asr_language_modeling.html#n-gram-language-modeling

That bash script has to be run by users as is, rather than python to install flashlight

**Comment by Mark-Serin** [comment]
I followed this guide but it refers to scrips that don't exist anymore. For example the following script is not relevant already:
```
python eval_beamsearch_ngram.py nemo_model_file=<path to the .nemo file of the model> \
       input_manifest=<path to the evaluation JSON manifest file \
       kenlm_model_file=<path to the binary KenLM model> \
       beam_width=[<list of the beam widths, separated with commas>] \
       beam_alpha=[<list of the beam alphas, separated with commas>] \
       beam_beta=[<list of the beam betas, separated with commas>] \
       preds_output_folder=<optional folder to store the predictions> \
       probs_cache_file=null \
       decoding_mode=beamsearch_ngram \
       decoding_strategy="<Beam library such as beam, pyctcdecode or flashlight>"
```
because there is no eval_breamsearch_ngram.py [here](https://github.com/NVIDIA/NeMo/blob/stable/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram.py).

**Comment by titu1994** [comment]
@karpnv could you update docs ?

**Comment by Mark-Serin** [comment]
NeMo of previous versions has it but there are no such parameters as `decoding_strategy`. I mean it can't be used as flashlight. And even in older versions of NeMo it's absent

**Comment by vadimkantorov** [comment]
@titu1994 
> Yes it's supported, please find installation instructions here

This page no longer exists

Given that flashlight isn't being developed anymore for several years, could instead https://pytorch.org/audio/0.12.0/models.decoder.html be used? It appears, torchaudio have ported and included the flashlight decoder into torchaudio

Alternatively, maybe Nemo could also port those flashlight source codes and include it directly? Similar to https://github.com/nvidia-riva/riva-asrlib-decoder
