### ISSUE TITLE
Issue with pip installing on windows due to youtokentome dependency 

### ISSUE THREAD

**Issue by pyth0nic** [NVIDIA/NeMo#9115]
**Describe the bug**

Youtokentome was archived in April 2024. It has several issues when installing on windows related to cython and visual studio C++ MSVC.

**Steps/Code to reproduce bug**
Try workaround described on issues of youtokentome:
```pip install git+https://github.com/gburlet/YouTokenToMe.git@dependencies```

Encounter the following even though c++ msvc is installed:
     "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iyoutokentome/cpp "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpyoutokentome/cpp/bpe.cpp /Fobuild\temp.win-amd64-cpython-311\Release\youtokentome/cpp/bpe.obj -std=c++11 -pthread -O3
      cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
      cl : Command line warning D9002 : ignoring unknown option '-pthread'
      cl : Command line warning D9002 : ignoring unknown option '-O3'
      bpe.cpp
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\cstddef(11): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Expected behavior**

Should be clean to install on windows using ```pip install nemo_toolkit['all']```

**Environment overview (please complete the following information)**

 - Environment location: Windows 11
 - Method of NeMo install: pip

**Comment by titu1994** [comment]
[all] was never guaranteed to work on Windows. 
[asr] can and should work on windows just fine. 
Yttm has long been removed from NeMo #8322
