### ISSUE TITLE
Titanet-L Augmentation

### ISSUE THREAD

**Issue by CreativeSelf0** [NVIDIA/NeMo#9127]
**Is your feature request related to a problem? Please describe.**

I want to train TitaNet with augmentation.
However, I do not know how can I prepare the rir_noise_manifest.json, file for training Titanet-L with rir noise augmentation.

**Describe the solution you'd like**

Provide a code snippet on how to add augmentation for TitaNet-L training.

**Comment by CreativeSelf0** [comment]
I added the following to augmentor, and used the following snippet from online augmentation tutorial
```python
rir_data_path = f'{data_dir}/dataset'
!python {NEMO_ROOT}/scripts/dataset_processing/get_openslr_rir_data.py --data_root {rir_data_path}
rir_manifest_path = os.path.join(rir_data_path, 'processed', 'rir.json')
!head -n 3 {rir_manifest_path}
```
Then to use the augmentation I applied the following 
```python
audio_augmentations = dict(
    speed = dict(
        sr=16000,
        prob=0.3,
        resample_type='kaiser_fast',
        min_speed_rate=0.95,
        max_speed_rate=1.05,
    ),
    noise = dict(
        manifest_path=rir_manifest_path,
        prob=0.5,
        min_snr_db=0,
        max_snr_db=15,
    ),
)
finetune_config.model.train_ds.augmentor = audio_augmentations
```
Am I correct and thanks @okuchaiev

**Comment by CreativeSelf0** [comment]
@nithinraok that's what I thought, Howeer in Titanet-Large they use noise instead of impulse, and it says we are using impulse pertubation. So, does that mean in their training they made an error using RIR corpora for noise instead of pulse petrubtion.
https://github.com/NVIDIA/NeMo/blob/6442bb67275759f5ece6bd5e366966216e050cfe/examples/speaker_tasks/recognition/conf/titanet-large.yaml#L14-L26

The paper statment:

![image](https://github.com/NVIDIA/NeMo/assets/18738089/6b21ef9e-c761-4ab9-98a3-163acc0fdfdf)


Thank you @nithinraok

**Comment by nithinraok** [comment]
I don;t remember details exactly but as far I remember RIR corpora also has noise samples as well along with impulse responses, and  I have not added impulse section to this config file but was added to titanet-small config.

**Comment by ukemamaster** [comment]
@nithinraok So you mean only RIR data augmentation is enough to train titanet-large model? if not, which noise data was augmented? Musan noise?

**Comment by ukemamaster** [comment]
@CreativeSelf0 Did you finally augmented both RIR and Noise? or only RIR?
