### ISSUE TITLE
module 'nemo.collections.asr' has no attribute 'models'

### ISSUE THREAD

**Issue by soheiltehranipour** [NVIDIA/NeMo#918]
Hi, During using Quartznet for my SpeechToText project, I faced this problem.
I want to load pretrained models of NeMo based on the the file below: 
[QuartzNetModel.ipynb](https://github.com/NVIDIA/NeMo/blob/master/examples/asr/QuartzNetModel.ipynb)

And i got this error:
**AttributeError: module 'nemo.collections.asr' has no attribute 'models'**

I will appreciate if anyone can help me with loading pretrained models via **nemo.collection.asr**.

@okuchaiev

**Comment by IsakWesterlundBitville** [comment]
I ecountered the same problem. In case anyone else has the same issue in my case it fixed itself after downgrading from python 3.8 to 3.7.
