### ISSUE TITLE
[solved] preprocess error  to loss

### ISSUE THREAD

**Issue by laohur** [NVIDIA/NeMo#921]
[solved] preprocess error to loss .
It is nomal of removing length input tensor and mask ops for export jsaper encoder.

**Comment by okuchaiev** [comment]
try using this script https://github.com/NVIDIA/NeMo/blob/master/scripts/export_jasper_to_onnx.py

**Comment by laohur** [comment]
> 
> 
> try using this script https://github.com/NVIDIA/NeMo/blob/master/scripts/export_jasper_to_onnx.py

this script results encoder output having time_steps=256，and F1 loss 3%。

**Comment by okuchaiev** [comment]
what F1 loss? Are you sure you are exporting jasper's encoder/decoder? ASR is measured by WER (word-error-rate)

**Comment by laohur** [comment]
> 
> 
> what F1 loss? Are you sure you are exporting jasper's encoder/decoder? ASR is measured by WER (word-error-rate)

Yes, WER. Remove lengths input tensor and mask ops does not matters.   Preprocesss cause the WER loss.  

This issue has no meaning. I will delete it.
