### ISSUE TITLE
AUDIO FILE SIZE for fine tuning STT En FastConformer Hybrid Transducer-CTC Large Streaming Multi

### ISSUE THREAD

**Issue by rkchamp25** [NVIDIA/NeMo#9216]
Hi
What should be the audio lengths for fine tuning stt_en_fastconformer_hybrid_large_streaming_multi? Should the length of audio files be same or  they can be of different? 
Thank You

**Comment by titu1994** [comment]
Audio duration can be different. In general we train usually with max duration of 20-40 seconds
