### ISSUE TITLE
[Conversion] How to convert Finetuned T5 checkpoint ended with `.ckpt` to `.nemo` checkpoint with NeMo toolkit?

### ISSUE THREAD

**Issue by jacklanda** [NVIDIA/NeMo#9248]
rt.

**Comment by ericharper** [comment]
This script should work: https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/language_modeling/megatron_ckpt_to_nemo.py

**Comment by ericharper** [comment]
Did the script work? Feel free to re-open if not.
