### ISSUE TITLE
setuptools 70.0.0 results in ImportError: cannot import name 'packaging' from 'pkg_resources' 

### ISSUE THREAD

**Issue by noralutz** [NVIDIA/NeMo#9284]
**Describe the bug**

NeMo uses the deprecated pkg_resources component of setuptools in the [Megatron GPT model](https://github.com/NVIDIA/NeMo/blob/v1.23.0/nemo/collections/nlp/models/language_modeling/megatron_gpt_model.py#L28). As of yesterday's v70.0.0 release of Setuptools, [this change](https://github.com/pypa/setuptools/commit/e9995828311c5e0c843622ca2be85e7f09f1ff0d)
 removes packaging from being imported by pkg_resouces and results in the above ImportError

**Steps/Code to reproduce bug**

1. install setuptools v70.0.0
2. install NeMo 1.23
3. Attempt to import nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel

**Expected behavior**

Model to import with no ImportError

**Environment overview (please complete the following information)**

 - Environment location: Cloud (GCP Vertex Workbench instance)
 - Method of NeMo install: pip install nemo-toolkit[all]==1.23

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Debian 11
- PyTorch version: 2.0.1
- Python version: 3.10.9

**Comment by yonas-g** [comment]
Did you find a solution for this error

**Comment by tfogal** [comment]
> Did you find a solution for this error

Just pin the setuptools version, e.g. `python3 -m pip install setuptools==69.5.1`

**Comment by crcrpar** [comment]
why not switching to [`packaging`](https://pypi.org/project/packaging/)?
