### ISSUE TITLE
asr_postprocessor seems to shuffle batches

### ISSUE THREAD

**Issue by m-zat** [NVIDIA/NeMo#930]
Hello,

I am trying to implement an inference script for the `asr_postprocessor` in ` NeMo/examples/nlp/asr_postprocessor/`.
I took the training script there and simply replaced `nf.train` with an `nf.infer` call. However I encounter the issue that batches are shuffled, thus when trying to pass a conversation to the post processor in the form
```
[ "Hi, how are you?", "I am fine, thanks"]
```
the meaning is completely lost as the sentences are shuffled around.

I tried to play with the `TranslationDataLayer` by forcing shuffle to be False but the result is still the same.
Is there something that I am missing that has to be done to preserve the order of the input list?

**Comment by okuchaiev** [comment]
For ASR you should be using AudioToTextDataLayer. Is shuffle set to False there https://docs.nvidia.com/deeplearning/nemo/developer_guide/en/v0.11.0/collections/nemo_asr.html?highlight=AudioToTextDataLayer#nemo.collections.asr.data_layer.AudioToTextDataLayer   (by default it is True)

**Comment by m-zat** [comment]
Hi @okuchaiev,

This is not an ASR, but an ASR post processor as described in tutorial 

https://docs.nvidia.com/deeplearning/nemo/developer_guide/en/v0.11.0/nlp/asr-improvement.html#asr-improvement

The input here is the output of an ASR, therefore text. The data layer needed is the `TranslationDataLayer` for which shuffle is set to False by default. However data seem to be shuffled anyway.
Is there maybe something wrong in that data layer or are there additional steps to be done on my side to avoid shuffling?

**Comment by m-zat** [comment]
Hi @okuchaiev ,

I think I have found the culprit.
The method defined for the 
https://github.com/NVIDIA/NeMo/blob/7ba27fed809b19e85717887b4893d37c335f32ad/nemo/collections/nlp/data/datasets/machine_translation_dataset.py#L29
has the method 
https://github.com/NVIDIA/NeMo/blob/7ba27fed809b19e85717887b4893d37c335f32ad/nemo/collections/nlp/data/datasets/machine_translation_dataset.py#L74
that sorts the input sentences, thus shuffling them.
While this might make sense for training, it is not really useful for inference, as when we apply a function `f` on a series `[a,b,c]`, we expect to get as output `[f(a), f(b), f(c)]`.
Would it be possible to allow preventing shuffling? As this is also confusing because the child class `TranslationDataLayer` has a parameter shuffle that one can set to false, but it is currently not working.
