### ISSUE TITLE
Nvidia GPU is Not accessing in my Docker Container

### ISSUE THREAD

**Issue by BBALU1660** [NVIDIA/NeMo#9334]
Error:
```
ERROR: The NVIDIA Driver is present, but CUDA failed to initialize. GPU functionality will not be available.
   [[ System has unsupported display driver / cuda driver combination (error 803) ]]
```

Command:
```
docker run --gpus device=0 --shm-size=2g --net=host --ulimit memlock=-1 --rm -it -v ${PWD}:/workspace -w /workspace -v ${PWD}/results:/results nvcr.io/nvidia/nemo:24.03.01.framework bash
```

![image](https://github.com/NVIDIA/NeMo/assets/116936023/86a68453-4596-47ca-b183-5c138bf4236e)

My Docker version: Docker version 26.1.3, build b72abbb  
My GPU: NVIDIA RTX A6000
Nvidia-smi (non docker)
![image](https://github.com/NVIDIA/NeMo/assets/116936023/9f79917b-1676-4fcc-8214-87cfb7e3bd5c)
Nvidia-smi(docker container)
![image](https://github.com/NVIDIA/NeMo/assets/116936023/c8d4608d-6f02-42a4-9072-55026b0601c9)

---

**Comment by nithinraok** [comment]
Similar issue: https://github.com/NVIDIA/NeMo/issues/9268

**Comment by BBALU1660** [comment]
My issue got solved instead of pulling nvcr.io/nvidia/nemo:24.03.01.framework pull nvcr.io/nvidia/nemo:dev.framework

**Comment by DannyP0** [comment]
install nvidia fabric if using nvlink
