### ISSUE TITLE
why we reverse the RGB channels in video processor

### ISSUE THREAD

**Issue by Slyne** [NVIDIA/NeMo#9346]
**Describe the bug**
Hi developers,
I noticed we reverse the video frame channels [here](https://github.com/NVIDIA/NeMo/blob/main/nemo/collections/multimodal/data/neva/neva_dataset.py#L103) and [here](https://github.com/NVIDIA/NeMo/blob/deb613adc7b7ad0a540f5cc1f0bc5032ddb345ff/nemo/collections/multimodal/parts/utils.py#L471).
```
frames = [Image.fromarray(vr[i].asnumpy()[:, :, ::-1]).convert('RGB') for i in indices]
```
Here are the images that without reversing vs reversing:
Normal image:
![img1](https://github.com/NVIDIA/NeMo/assets/6286804/2b41d859-dfb3-43c2-8cc7-aaa2c3937c96)

Reverse image:
![img2](https://github.com/NVIDIA/NeMo/assets/6286804/44200c0d-e6f4-48b5-a773-687d75221652)

In some other project like [LITA](https://github.com/NVlabs/LITA/blob/56a23db03197beab45b28f0971129eadc1a6db03/lita/utils.py#L58) and [video LLaVA](https://github.com/PKU-YuanGroup/Video-LLaVA/blob/c5d2b7250f0a082f733974cfa40d4b09b97b88f5/videollava/model/multimodal_encoder/languagebind/video/processing_video.py#L89)
They simply do the below: 
```
decord.bridge.set_bridge("torch")
video_reader = VideoReader(uri=video_path)   
idx = np.round(np.linspace(0, len(video_reader) - 1, num_frames)).astype(int)
frames = video_reader.get_batch(idx)   
frames = processor.preprocess(frames, return_tensors='pt')['pixel_values']
```

If we use opencv, we probably need to convert  BGR2RGB. But now we are using `decord`, not sure if it's still the case.

**Comment by yaoyu-33** [comment]
This has been fixed by https://github.com/NVIDIA/NeMo/pull/9245
