### ISSUE TITLE
How can I use  manifest_filepath from a string, not a file in disk in nemo_asr.AudioToTextDataLayer? 

### ISSUE THREAD

**Issue by paklau99988** [NVIDIA/NeMo#944]
Hello, 
``
  with open("./static/wav/test_single.json", 'w') as outfile: # this 
        json.dump(data, outfile)
    eval_data_layer = nemo_asr.AudioToTextDataLayer(
        manifest_filepath="./static/wav/test_single.json",
        labels=asr_model.vocabulary,
        batch_size=4,
        trim_silence=True,
        shuffle=False,
        normalize_transcripts=False,
    )
``

**Comment by viveksj** [comment]
What does your manifest look like?
