### ISSUE TITLE
Latest release version 1.23.0 missing the AudioCodecModel checkpoint list.

### ISSUE THREAD

**Issue by shreeshailgan** [NVIDIA/NeMo#9447]
**Describe the bug**

Latest release version `1.23.0` is missing the `AudioCodecModel` checkpoint list.

**Steps/Code to reproduce bug**

As instructed [here](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/audio_codec_16khz_small), run the following code
```
from  nemo.collections.tts.models  import  AudioCodecModel
nemo_codec_model  =  AudioCodecModel.from_pretrained('audio_codec_16khz_small')
```

**Expected behavior**

I expect to load the 16kHz checkpoint of `AudioCodecModel`. However, on running the above code, I get the following error
```
FileNotFoundError: Model audio_codec_16khz_small was not found. Check cls.list_available_models() for the list of all available models.
```
On checking the function in the latest release version `==1.23.0`, https://github.com/NVIDIA/NeMo/blob/e772dbf53145a7b45f13440cf6e0ef51035f80dc/nemo/collections/tts/models/audio_codec.py#L646
we see that the function returns an empty list.
\
This problem is resolved on the latest commit on the `main` branch
https://github.com/NVIDIA/NeMo/blob/3c29fefe9ac442e594f1c35c0f8ecc09b5ef5015/nemo/collections/tts/models/audio_codec.py#L652

but installing `nemo_toolkit` using `pip` as instructed installs the latest release version.

**Environment overview**

 - Environment location: Linux Cloud Server
 - Method of NeMo install: `pip install nemo_toolkit['all']`

**Environment details**
- OS version: Ubuntu 22.04.3 LTS
- PyTorch version: 2.3.0
- Python version: 3.10.12

**Comment by titu1994** [comment]
Audio codec is in NeMo 2.0.0rc0. You can get it by using pip install nemo_toolkit[asr,tts] --pre
