### ISSUE TITLE
Can we add emotions to the produced audio?

### ISSUE THREAD

**Issue by shivgit07** [NVIDIA/NeMo#9498]
Hello,

I was just trying some combinations of Mel-Spectogram-Generators and Vocoders to produce different audio samples. 

I was thinking if it was possible to make the produced audio sound more naturally by adding some kind of emotional embeddings in the Mel spectogram generator models. Or any other suitable approach to do this.

I am new to TTS so not sure if such thing is possible. 

I would be highly grateful if somebody could help me out.

Thanks.

**Comment by blisc** [comment]
You will need to train your spectrogram generator / acoustic model with emotional data. Tag the emotional data as a new speaker and do inference with the emotional-speaker tag.
