### ISSUE TITLE
LM on Parakeet models

### ISSUE THREAD

**Issue by jinmingteo** [NVIDIA/NeMo#9500]
Hi team,

I am trying to add LM into parakeet models and i think this is the script related to it. 

[eval_beamsearch_ngram_transducer.py](https://github.com/NVIDIA/NeMo/blob/main/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram_transducer.py)

I have tried using it and encountered a couple of issues with EncDecRNNTBPEModel. For example, there are 3 outputs in [forward](https://github.com/NVIDIA/NeMo/blob/main/scripts/asr_language_modeling/ngram_lm/eval_beamsearch_ngram_transducer.py#L336) function now. 
Is there other scripts that i should be looking into? 

Thanks

**Comment by titu1994** [comment]
For transducer, there were always 3 outputs in forward because it's just end encoder forward. During decoding we take those encoder outputs and pass them auto regressively to the decoder and joint. 

For beam search support, @karpnv
