### ISSUE TITLE
to support deepseekv2

### ISSUE THREAD

**Issue by panjianfei** [NVIDIA/NeMo#9501]
hi, do you have plan to support deepseekv2 model?

**Comment by ntajbakhsh** [comment]
Thanks for your inquiry. DeepSeek was in our roadmap but it has now been deprioritized. Here is a list of currently supported LLMs: https://docs.nvidia.com/nemo-framework/user-guide/latest/llms/index.html

**Comment by ZhangAustin** [comment]
given DeepSeekV3 and R1, shouldn't we reopen it
