### ISSUE TITLE
When Trying to import nlp collections in the Nemo Primer getting error "No Module named megatron"

### ISSUE THREAD

**Issue by evodata123** [NVIDIA/NeMo#9509]
This is being done in google colab environment.
with Nemo version 2.0.0rc0

![image](https://github.com/NVIDIA/NeMo/assets/168087860/9b4114f7-e12d-4cc7-8b33-dbf903257b34)

**Comment by ashors1** [comment]
Hi @evodata123, the specific `'ApexGuardDefaults' is not defined` error you are seeing should be fixed by [this PR](https://github.com/NVIDIA/NeMo/pull/9732). But note that Megatron core is a required dependency of NeMo, so if Megatron core is not installed, you may see some orthogonal issues.

**Comment by philm001** [comment]
I would like to re-open this issue. I am getting the same issue as OP. As for the PR, was this applied to the 'r2.0.0rc0' branch?
