### ISSUE TITLE
PreTrainig Jasper

### ISSUE THREAD

**Issue by 4nton-P** [NVIDIA/NeMo#952]
Hello!
Can someone tell me how to use your trained checkpoint as a pretraining
We need to start training from this checkpoint with random initialization of parameters, as if we were training from scratch
in general, does it make sense or not?

**Comment by byebye1** [comment]
Hello!
Can someone tell me how to use your trained checkpoint as a pretraining
We need to start training from this checkpoint with random initialization of parameters, as if we were training from scratch
in general, does it make sense or not?
Jasper model

**Comment by okuchaiev** [comment]
If you want to train from scratch, then pass .yaml config file (for example, https://github.com/NVIDIA/NeMo/blob/master/examples/asr/configs/jasper10x5.yaml)  as "--asr_model" parameter to this script  https://github.com/NVIDIA/NeMo/blob/master/examples/asr/speech2text.py

**Comment by okuchaiev** [comment]
"start training from this checkpoint with random initialization of parameters"
- so do you want to start training from checkpoint or from random parameters?

**Comment by byebye1** [comment]
> "start training from this checkpoint with random initialization of parameters"
> 
> * so do you want to start training from checkpoint or from random parameters?

I want to use my pretrained model with randomly initialized parameters
