### ISSUE TITLE
Can you support DoRA?

### ISSUE THREAD

**Issue by SJmdy** [NVIDIA/NeMo#9520]
Hi Team,
Do you have any plans to support DoRA?

Paper: https://arxiv.org/abs/2402.09353
peft: https://github.com/huggingface/peft/pull/1474

Thank you

**Comment by cuichenx** [comment]
Hi @SJmdy 
Dora is a planned feature in the near future. We plan on supporting it once to transition to NeMo 2.0 is mature.
