### ISSUE TITLE
Very poor WER for Conformer_CTC_large model in streaming mode

### ISSUE THREAD

**Issue by SerhiiArtemuk** [NVIDIA/NeMo#9615]
Hello. I am testing the [STT En Conformer-CTC Large](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_conformer_ctc_large/files) model in streaming mode. To do this, I use the [speech_to_text_cache_aware_streaming_infer.py](https://github.com/NVIDIA/NeMo/blob/main/examples/asr/asr_cache_aware_streaming/speech_to_text_cache_aware_streaming_infer.py) script and the [librispeech-test-other](https://www.openslr.org/12) dataset. With the default `chunk_size` value of 4000 ms, everything works quite well. The WER is 8.67%. However, when I reduce the `chunk_size` to 800 ms, I get very poor results. The WER increases to 35.6%.
I understand that this model was trained with full context in offline mode. And the accuracy would not be very good with small chunks. But I also tested this model in streaming mode (`chunk_size` = 800ms) with RIVA. I converted the nemo model to riva with [nemo2riva](https://github.com/nvidia-riva/nemo2riva) and built a pipeline. In this case, the WER was 7.9%. I understand that the RIVA service contains certain techniques and optimizations for working with the streaming mode. But I wonder why there is such a difference in WER when using the same model and the same chunk size. 
Can anyone explain this behavior? Maybe RIVA reconfigures the model in some way or something else that I might have missed?

**Comment by VahidooX** [comment]
An offline model is not supposed to be used with cache-aware scripts with small chunk sizes. You need to use cache-aware models like:
 Riva does not support cache-aware models publicly yet as far as I know.
