### ISSUE TITLE
More complete example of using S3CheckpointIO

### ISSUE THREAD

**Issue by dementrock** [NVIDIA/NeMo#9645]
The existing doc on S3CheckpointIO is pretty sparse. Can there be a more complete example of using it within a script like https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/language_modeling/megatron_gpt_pretraining.py?

**Comment by alxzhang-amazon** [comment]
Review seemed closed but can use it as reference if still needing help.
https://github.com/NVIDIA/NeMo/pull/9812
