### ISSUE TITLE
Util for measuring MFU?

### ISSUE THREAD

**Issue by dementrock** [NVIDIA/NeMo#9673]
We'd like to track model flops utilization (MFU) during training. Is there any pointers for how to do this or would it be possible to add support for this within NeMo?

**Comment by pablo-garay** [comment]
We will add support for this in this repo: computing Model Flops Utilization. 
Our team has this task in the backlog and will be working on it.

**Comment by malay-nagda** [comment]
@dementrock I'll be adding this support this week. Any particular model(s) that you are looking at? 
@ericharper Could you assign this to me?

**Comment by malay-nagda** [comment]
@ericharper can you help review and merge this PR- #9735?

**Comment by dementrock** [comment]
@malay-nagda thanks a lot! Support for the common models like llama / mistral would be sufficient for us for now
