### ISSUE TITLE
1_ASR_tutorial_using_NeMo.ipynb Runtime exception during training on colab

### ISSUE THREAD

**Issue by micheldanjou** [NVIDIA/NeMo#981]
Hi,
Just noticed today that the example file 1_ASR_tutorial_using_NeMo.ipynb no longer works on Google Colab.

```python
neural_factory.train(
    tensors_to_optimize=[loss],
    callbacks=[train_callback, eval_callback, checkpoint_saver_callback],
    optimizer='novograd',
    optimization_params={
        "num_epochs": 100, "lr": 0.01, "weight_decay": 1e-4
    })
```

I get the following error:

```python
/usr/local/lib/python3.6/dist-packages/nemo/collections/asr/parts/jasper.py in get_seq_len(self, lens)
    109         return (
    110             lens + 2 * self.conv.padding[0] - self.conv.dilation[0] * (self.conv.kernel_size[0] - 1) - 1
--> 111         ) / self.conv.stride[0] + 1
    112 
    113     def forward(self, x, lens):
```
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

**Steps to reproduce:**
1. clone https://github.com/NVIDIA/NeMo.git on your local drive
1. connect to google colab: https://colab.research.google.com/
1. select "uppload" and select this file on your local drive from Nemo's git repo: examples/asr/notebooks/1_ASR_tutorial_using_NeMo.ipynb
1. run the notebook

**Expected output**
the notebook should run without errors

**Additional information**
  * This used to work well up to at least 2-3 weeks ago.
  * version of python: !python -V => 3.6.9

**Workaround**
no workaround found so far.

Any idea?
Many thanks,
Michel

**Comment by soheiltehranipour** [comment]
This Error happens because of latest version of **PyTorch**. 
Recently PyTorch updgraded to 1.6 and in this version you will face this runtime error.

I had your issue too.
_Simplest way is downgrading PyTorch with this command :_
"!pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html"

But keep in mind that after executing this command you should "**Restart the Runtime**".

**Comment by micheldanjou** [comment]
Hi Soheil,

Your fix worked like a charm! 
Thank you very much.

Regards,
Michel
