### ISSUE TITLE
ImportError: cannot import name 'CanaryTokenizer' from 'nemo.collections.common.tokenizers

### ISSUE THREAD

**Issue by Rumeysakeskin** [NVIDIA/NeMo#9845]
ImportError: cannot import name 'CanaryTokenizer' from 'nemo.collections.common.tokenizers' (/usr/local/lib/python3.10/dist-packages/nemo/collections/common/tokenizers/__init__.py)

**Comment by nithinraok** [comment]
@Rumeysakeskin pls provide additional information on which file you were trying to run and how you encountered this error for reproducibility.,
